### PR TITLE
Disable luks format for discard test

### PR DESCRIPTION
**Pull request by qingwangrh**
ID:1900962
Signed-off-by: qingwangrh <qinwang@redhat.com>

### CODE REVIEW

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=block_discard_hotplug --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=RHEL.8.4.0 --driveformat=virtio_scsi --nicmodel=virtio_net --imageformat=luks --machines=q35 --customsparams="image_aio=native" --dryrun

(1/3) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (2/3) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.rh_kernel_update.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (3/3) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.block_discard_hotplug.scsi_debug.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

**Comment by qingwangrh** [comment]
@YongxueHong @zhenyzha Please help to review, thanks.

**Comment by XueqiangWei** [comment]
LGTM,
Acked-by: xuwei@redhat.com

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by zhenyzha** [comment]
LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Review by zhenyzha — APPROVED** [review]

**Pull request merged**
