### PR TITLE
win_heavyload: Use vm.cpuinfo.smp instead of params["smp"]

### PR DESCRIPTION
**Pull request by huangyum**
ID: 1784231
Signed-off-by: Yumei Huang <yuhuang@redhat.com>

### CODE REVIEW

**Comment by huangyum** [comment]
(1/1) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.hotplug_memory.during.stress.hotplug.backend_ram.policy_default.two.q35: PASS (1118.29 s)

**Comment by huangyum** [comment]
@lijinlijin Please help review, thanks.

**Comment by PaulYuuu** [comment]
It is more appropriate to use `vm.cpuinfo` to get CPU information.
Acked-by: Yihuang Yu <yihyu@redhat.com>

**Comment by lijinlijin** [comment]
Acked-by: Li Jin lijin@redhat.com

**Pull request merged**
