### PR TITLE
tp-qemu: quick fix miss import data_dir module error

### PR DESCRIPTION
**Pull request by xutian**
Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by CongSmile** [comment]
@xutian 

Could you provide the ID?

**Comment by xutian** [comment]
ID: 1313153

**Comment by xutian** [comment]
syntax found when review another PR, so made a quick fix.

**Comment by CongSmile** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by spcui** [comment]
Acked-by: scui@redhat.com

**Pull request merged**
