### PR TITLE
libblkio_release_test: Ignore the case from aarch64 and s390x

### PR DESCRIPTION
**Pull request by SiboWang1997**
skip aarch64 and s390x in this case.

ID:2230227

### CODE REVIEW

**Comment by SiboWang1997** [comment]
Hi @zhenyzha @XueqiangWei  @qingwangrh could you please help to review this patch? Thanks a lot.

**Comment by XueqiangWei** [comment]
LGTM,
Acked-by: xuwei@redhat.com

**Comment by qingwangrh** [comment]
LGTM

**Review by hereischen — APPROVED** [review]

**Review by zhenyzha — APPROVED** [review]
git am 3806.patch
Applying: libblkio_release_test: Ignore the case from aarch64 and s390x

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Pull request merged**
