### PR TITLE
add windows support for remote_block_hotplug

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>
ID: 2125857

### CODE REVIEW

**Comment by XueqiangWei** [comment]
1-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_qcow2.q35 Finshed 2022-09-11 02:48:19 2022-09-11 02:55:42 PASS 442.588238
2-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_raw.q35 Finshed 2022-09-11 02:55:43 2022-09-11 03:00:57 PASS 313.755635
3-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_luks.q35 Finshed 2022-09-11 03:00:58 2022-09-11 03:06:07 PASS 309.173224
4-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_qcow2.q35 Finshed 2022-09-11 03:06:09 2022-09-11 03:11:50 PASS 341.244668
5-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_raw.q35 Finshed 2022-09-11 03:11:51 2022-09-11 03:16:47 PASS 296.012406
6-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_luks.q35 Finshed 2022-09-11 03:16:49 2022-09-11 03:21:41 PASS 292.055276
Summary: 
Finshed=6, PASS=6

**Comment by XueqiangWei** [comment]
@zhencliu @hellohellenmao Please help review it. Many thanks.

**Comment by zhencliu** [comment]
LGTM

also suggest commit header: remote_block_hotplug: add windows support

**Comment by XueqiangWei** [comment]
Updated, thanks Zhenchao.

**Comment by hellohellenmao** [comment]
Tried with raw, qcow2 and luks, all passed.

Ack.

**Pull request merged**
