### PR TITLE
tp-qemu: update vectors number

### PR DESCRIPTION
**Pull request by xutian**
ID: 1241435 

Signed-off-by: Xu Tian xutian@redhat.com

### CODE REVIEW

**Comment by CongSmile** [comment]
Hi @xutian 

It does not mean that queues should be equal to smp, right?

I'm a little confused now, could you help explain it?

Thanks.

**Comment by PyLearner** [comment]
failed to review
check the qemu-commandline could see that
smp=32 but fd=4

    -netdev tap,id=idktAOiz,vhost=on,vhostfds=26:27:28:29,fds=22:23:24:25  \
    -m 16384  \
    -smp 32,maxcpus=32,cores=16,threads=1,sockets=2  \

**Comment by PyLearner** [comment]
smp=1 but fd=4
    -netdev tap,id=idnsKCgJ,vhost=on,vhostfds=27:28:29:30,fds=20:21:22:24  \
    -m 16384  \
    -smp 1,maxcpus=1,cores=1,threads=1,sockets=2  \

**Comment by xutian** [comment]
link to 415

**Pull request closed without merging**
