### PR TITLE
stress: Fix softlockup case issues

### PR DESCRIPTION
**Pull request by yiqianwei**
ID: 1869584

### CODE REVIEW

**Comment by yiqianwei** [comment]
Test results:
(1/1) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.softlockup.q35: PASS (524.49 s)

**Comment by yiqianwei** [comment]
@yanan-fu and @jingzhao84 , Could you help to review this patch? thanks

**Comment by jingzhao84** [comment]
@yiqianwei  did you consider about multi-arch part? how about the multi-arch test result?

Thanks
Jing

**Comment by yiqianwei** [comment]
@MiriamDeng , Could you help to check it on ppc? thanks

**Comment by yiqianwei** [comment]
@fbq815 , @PaulYuuu ,  Could you help to check it on host?

**Comment by fbq815** [comment]
since this test cases is related stress test, s390x would skip, thanks for let me know

**Review by PaulYuuu — APPROVED** [review]

**Comment by MiriamDeng** [comment]
LGTM
 (1/1) Host_RHEL.m8.u9.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.ppc64le.io-github-autotest-qemu.softlockup: STARTED
 (1/1) Host_RHEL.m8.u9.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.ppc64le.io-github-autotest-qemu.softlockup: PASS (924.70 s)

**Review by yanan-fu — APPROVED** [review]
Ack

**Pull request merged**
