### PR TITLE
readonly_disk:update format_guest_disk function after it was rewritten in utils_misc

### PR DESCRIPTION
**Pull request by yanan-fu**
The function "format_guest_disk" has be rewritten in utils_misc, params
changed, so update it in readonly_disk.

id: 1420597

Signed-off-by: Yanan Fu <yfu@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
@ngu-niny could you help review this patch ? 
This patch is based on the one you send before in avocado-vt,
https://github.com/avocado-framework/avocado-vt/pull/712/

@PyLearner could you help review it too ?

**Comment by ngu-niny** [comment]
@yanan-fu shuang intended to change the function "format_guest_disk", so let's wait until the new change comes.

cc @suqinhuang

**Comment by yanan-fu** [comment]
@suqinhuang  any new progress in your side ?

**Comment by yanan-fu** [comment]
depends on  https://github.com/avocado-framework/avocado-vt/pull/887

**Comment by yanan-fu** [comment]
@luckyh  this patch has been pending for too long time as it depends on another patch. 
This modification is based on the status of current code, in utils_misc, the function "format_guest_disk" was be modified in patch avocado-framework/avocado-vt#712, but it miss to change all of the code that call for this function.  This is what this patch for.   Now, i have two suggestions, could you give some advise ?

1. No need to wait the dependent patch avocado-framework/avocado-vt#887,  the owner who send the new patch to modify the function again should cover all the code that call for that function.  and we can merge this patch if it is ok for you.

2. Drop this patch, and the new patch avocado-framework/avocado-vt#887 will cover all the code that call for this function.

Which one do you think is better? i prefer the first one because the case "readonly_disk" can not run normally now.

**Comment by yanan-fu** [comment]
Don't depends on avocado-framework/avocado-vt#887 .

**Comment by yanan-fu** [comment]
(1/1) smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_blk.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.readonly_disk: PASS (226.05 s)

**Comment by yanan-fu** [comment]
@luckyh  If so, i will close this PR, thanks ~

**Pull request closed without merging**
