### PR TITLE
qemu_img: fix sub case of commit

### PR DESCRIPTION
**Pull request by hellohellenmao**
add base image format for the command of snapshot creation

Signed-off-by: Tingting Mao <timao@redhat.com>

ID: 2002513

### CODE REVIEW

**Comment by hellohellenmao** [comment]
PASS 2-Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.qemu_img.commit.q35

**Comment by hellohellenmao** [comment]
@XueqiangWei Could you please help to review? Thanks.

**Comment by XueqiangWei** [comment]
1-Host_RHEL.m8.u5.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img.commit.q35 Finshed 2021-09-23 04:51:15 2021-09-23 04:53:24 PASS 128.977146

LGTM,
Acked-by: xuwei@redhat.com

**Comment by XueqiangWei** [comment]
@zhencliu Please help review it. Many thanks.

**Comment by zhencliu** [comment]
LGTM

**Pull request merged**
