### PR TITLE
discard_for_raw_block_target: add 4k sector size support

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>
ID: 2008616

### CODE REVIEW

**Comment by XueqiangWei** [comment]
(1/2) Host_RHEL.m8.u5.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.discard_for_raw_block_target.q35: PASS (5.09 s)
 (2/2) Host_RHEL.m8.u5.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.discard_for_raw_block_target.with_4k_sector_size.q35: PASS (4.96 s)

(1/2) Host_RHEL.m9.u0.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.discard_for_raw_block_target.q35: PASS (3.78 s)
 (2/2) Host_RHEL.m9.u0.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.discard_for_raw_block_target.with_4k_sector_size.q35: PASS (3.73 s)

**Comment by XueqiangWei** [comment]
@zhencliu @hellohellenmao Please help review it. Many thanks.

**Comment by zhencliu** [comment]
LGTM

**Comment by hellohellenmao** [comment]
(1/2) Host_RHEL.m9.u0.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.discard_for_raw_block_target.q35: PASS (4.51 s)
 (2/2) Host_RHEL.m9.u0.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.discard_for_raw_block_target.with_4k_sector_size.q35: PASS (4.20 s)

Ack. Thanks.

**Pull request merged**
