### PR TITLE
qemu.tests.pktgen: Small fix for log format

### PR DESCRIPTION
**Pull request by spcui**
Change log "packet lost ratio is '%100'" to '100%'.

Signed-off-by: Shuping Cui <scui@redhat.com>

### CODE REVIEW

**Comment by spcui** [comment]
ID: 1241467

**Comment by vipmike007** [comment]
Acked By Mike Cao <bcao@redhat.com>

**Comment by vipmike007** [comment]
Acked By Mike Cao <bcao@redhat.com>

**Comment by xutian** [comment]
Please check do we have function to get default gateway in  utils_misc or utils_net module. it better to use default getway to do this kind of tests.

Thanks,
Xu

**Comment by spcui** [comment]
Hi @xutian 
Already setup on line 31:34 for get Default gateway if not set external_host":
    external_host = params.get("external_host")
    if not external_host:
        get_host_cmd = "ip route | awk '/default/ {print $3}'"
        external_host = utils.system_output(get_host_cmd)

**Comment by xutian** [comment]
LGTM,

Acked-by: Xu Tian <xutian@redhat.com>

**Comment by xutian** [comment]
Merged. thanks @spcui  and @vipmike007

**Pull request merged**
