### PR TITLE
Use fs_log_level to set log levels in test cases

### PR DESCRIPTION
**Pull request by qcheng-redhat**
Use the new variable `fs_log_level` to set log levels in test cases. 

ID: 2796

### CODE REVIEW

**Comment by qcheng-redhat** [comment]
This patch requires https://github.com/avocado-framework/avocado-vt/pull/4017

**Comment by qcheng-redhat** [comment]
Hi @hellohellenmao, please help review this patch. Thanks!

**Comment by hellohellenmao** [comment]
The cases passed and check the virtiofsd target log: /usr/libexec/virtiofsd --socket-path=/var/tmp/avocado_bdmbg5tc/avocado-vt-vm1-fs-virtiofsd.sock --shared-dir /root/avocado/data/avocado-vt/virtio_fs_test/ --log-level debug, which LGTM.
Thanks.

**Review by hellohellenmao — APPROVED** [review]

**Comment by hellohellenmao** [comment]
@YongxueHong Could you please help to review here? Thanks

**Comment by YongxueHong** [comment]
Hi @fbq815 , @MiriamDeng , @xiagao 
Could you help review it from your platform?
Thanks in advance.

**Comment by xiagao** [comment]
LGTM.

**Comment by XueqiangWei** [comment]
Hi @fbq815 , @MiriamDeng Could you help review it from your platform? Many thanks.

**Comment by fbq815** [comment]
@qcheng-redhat sees the scenarios is windows only and s390x don't support windows guest, please igore me

**Comment by MiriamDeng** [comment]
LGTM

**Review by fbq815 — APPROVED** [review]

**Pull request merged**
