### PR TITLE
numa_opts: Set maxcpus equal to smp

### PR DESCRIPTION
**Pull request by huangyum**
ID: 1783854
Signed-off-by: Yumei Huang <yuhuang@redhat.com>

### CODE REVIEW

**Comment by huangyum** [comment]
(1/2) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.numa_opts.nodes.2.defaults: PASS (8.56 s)
 (2/2) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.numa_opts.nodes.3.defaults: PASS (8.40 s)

**Comment by PaulYuuu** [comment]
I would suggest overwrite `smp` and `smp` in cfg file instead of using `smp_override` and `mem_override`
https://github.com/autotest/tp-qemu/blob/71a331a14d3601422bab8099e6a7a96242e27c9e/qemu/tests/numa_opts.py#L21-L26

**Comment by huangyum** [comment]
> I would suggest overwrite `smp` and `mem` in cfg file instead of using `smp_override` and `mem_override`
> https://github.com/autotest/tp-qemu/blob/71a331a14d3601422bab8099e6a7a96242e27c9e/qemu/tests/numa_opts.py#L21-L26

Yes, it would work too. Then we don't need to start vm in paused status too.

**Comment by huangyum** [comment]
@xutian @PaulYuuu Updated, pls help reivew again, thanks.

**Comment by huangyum** [comment]
(1/9) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.numa_opts.nodes.0: PASS (15.05 s)
 (2/9) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.numa_opts.nodes.1: PASS (15.67 s)
 (3/9) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.numa_opts.nodes.2.defaults: PASS (15.56 s)
 (4/9) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.numa_opts.nodes.2.custom_values.implicit_ids: PASS (15.68 s)
 (5/9) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.numa_opts.nodes.2.custom_values.unordered_ids: PASS (15.46 s)
 (6/9) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.numa_opts.nodes.3.defaults: PASS (15.38 s)
 (7/9) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.numa_opts.nodes.3.custom_values.implicit_ids: PASS (21.52 s)
 (8/9) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.numa_opts.nodes.3.custom_values.unordered_ids: PASS (15.92 s)
 (9/9) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.numa_opts.nodes.128: PASS (103.01 s)

**Comment by PaulYuuu** [comment]
LGTM
Acked-by: Yihuang Yu <yihyu@redhat.com>

**Pull request merged**
