### PR TITLE
rfe: Support custom ansible connection plugin

### PR DESCRIPTION
**Pull request by PaulYuuu**
The default connection plugin for ansible is ssh, but when using password with ssh plugin, the sshpass is required. To support flexible connection, make the connection plugin is customizable.

ID: 2651

### CODE REVIEW

**Comment by PaulYuuu** [comment]
Hello @ybduan @fbq815, please help review this. You should set `package_dict = python=paramiko` and `ansible_connection_plugin = paramiko_ssh` for your usage.

Hello @yanan-fu @lkotek, I also refactor the package installation methods, so please help review it as well.

**Comment by lkotek** [comment]
> Hello @yanan-fu @lkotek, I also refactor the package installation methods, so please help review it as well.

Hi @PaulYuuu, I checked the code – especially having in mind https://github.com/autotest/tp-qemu/pull/3688 and our discussion last year we had there – my feeling regarding ansible provider is it is a bit fragile zone :wink: Nevertheless my conclusion is we should be safe with your changes regarding ansible provider here. Thanks for the PR!

Just one thing: can you double check the current status of configuration option `package_list` as it is used in `subtests-internal.cfg` in our internal automation, please? And eventually prepare MR to align it with this PR (if necessary), please?

**Comment by PaulYuuu** [comment]
> > Hello @yanan-fu @lkotek, I also refactor the package installation methods, so please help review it as well.
> 
> Hi @PaulYuuu, I checked the code – especially having in mind #3688 and our discussion last year we had there – my feeling regarding ansible provider is it is a bit fragile zone 😉 Nevertheless my conclusion is we should be safe with your changes regarding ansible provider here. Thanks for the PR!
> 
> Just one thing: can you double check the current status of configuration option `package_list` as it is used in `subtests-internal.cfg` in our internal automation, please? And eventually prepare MR to align it with this PR (if necessary), please?

Yes, with this breaking change, I think feature owners should migrate package_list to package_dict according to their usage, in addition to aligning existing, they should also add some to adapt to new products.

**Comment by ybduan** [comment]
Tests pass with this PR. Test results are present in corresponding JIRA issue.

LGTM.
ACKed-by: Yanbin Duan <yduan@redhat.com>

**Review by ybduan — APPROVED** [review]

**Review by fbq815 — APPROVED** [review]
LGTM:
PASS 8 | ERROR 0 | FAIL 3 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

Failed cases are caused by other issues

**Pull request merged**
