### PR TITLE
usbredir_negative: update re pattern to get USB device info

### PR DESCRIPTION
**Pull request by ybduan**
Update re pattern to get USB device info in host dmesg correctly
ID: 2118189
Signed-off-by: ybduan <yduan@redhat.com>

### CODE REVIEW

**Comment by ybduan** [comment]
(1/2) Host_RHEL.m8.u7.product_rhel.spice.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.x86_64.io-github-autotest-qemu.usb.usb_redir.with_negative_config.without_usb_hub.nec-xhci.q35: STARTED
 (1/2) Host_RHEL.m8.u7.product_rhel.spice.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.x86_64.io-github-autotest-qemu.usb.usb_redir.with_negative_config.without_usb_hub.nec-xhci.q35: PASS (142.15 s)
 (2/2) Host_RHEL.m8.u7.product_rhel.spice.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.x86_64.io-github-autotest-qemu.usb.usb_redir.with_negative_config.without_usb_hub.qemu-xhci.q35: STARTED
 (2/2) Host_RHEL.m8.u7.product_rhel.spice.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.x86_64.io-github-autotest-qemu.usb.usb_redir.with_negative_config.without_usb_hub.qemu-xhci.q35: PASS (141.88 s)

**Comment by yanan-fu** [comment]
@ybduan Could you share an example for this change, thanks!

**Comment by ybduan** [comment]
The original RE pattern only works for 'usb 1-1: ...', but not 'usb 1-11: ...'.
With the latest change, there can be multi-digits after hyphen sign.
dmesg output: usb 1-11: New USB device found, idVendor=0951, idProduct=1666, bcdDevice= 1.10
Thanks!

**Comment by yanan-fu** [comment]
Thanks!

**Review by yanan-fu — APPROVED** [review]
Ack

**Pull request merged**
