### PR TITLE
virtio_mem_numa_basic.cfg: Add support on windows side

### PR DESCRIPTION
**Pull request by menli820**
Add support on windows side to test viomem.

ID: 2496
Signed-off-by: menli <menli@redhat.com>

### CODE REVIEW

**Comment by menli820** [comment]
for windows side, the case will fail as a existing product bug.

# python3 ConfigTest.py --testcase=virtio_mem_numa_basic  --guestname=Win2019 --firmware=default_bios  --driveformat=virtio_blk --platform=x86_64 --customsparams="cdrom_virtio = isos/windows/virtio-win-prewhql-0.1-262.iso"  --machines=q35 --clone=no

 (1/1) Host_RHEL.m9.u5.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_mem_numa_basic.q35: STARTED
 (1/1) Host_RHEL.m9.u5.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_mem_numa_basic.q35: FAIL: Error, size: 1396703232 and requested-size: 1073741824 are not equals. (189.58 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2024-08-21T05.07-4c84ed4/results.html
JOB TIME   : 190.92 s

**Comment by menli820** [comment]
@mcasquer could you please help me review it when you free, thanks

**Comment by mcasquer** [comment]
@menli820 just to clarify... why the reboot scenario is not supported?

**Comment by mcasquer** [comment]
The test case fails for both Win11 and Win2025 VMs
```
 (1/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.virtio_mem_numa_basic.q35: STARTED
 (1/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.virtio_mem_numa_basic.q35: FAIL: Error, size: 8589934592 and requested-size: 0 are not equals. (213.25 s)
 (2/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.virtio_mem_numa_basic.q35: STARTED
 (2/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.virtio_mem_numa_basic.q35: FAIL: Error, size: 8587837440 and requested-size: 0 are not equals. (269.06 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 2 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```

**Comment by menli820** [comment]
> The test case fails for both Win11 and Win2025 VMs
> 
> ```
>  (1/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.virtio_mem_numa_basic.q35: STARTED
>  (1/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.virtio_mem_numa_basic.q35: FAIL: Error, size: 8589934592 and requested-size: 0 are not equals. (213.25 s)
>  (2/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.virtio_mem_numa_basic.q35: STARTED
>  (2/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.virtio_mem_numa_basic.q35: FAIL: Error, size: 8587837440 and requested-size: 0 are not equals. (269.06 s)
> RESULTS    : PASS 0 | ERROR 0 | FAIL 2 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
> ```

Thanks for testing, the fail is expected as an existing product bug,  more details , you can refer to the jira issue comment.

**Comment by menli820** [comment]
> @menli820 just to clarify... why the reboot scenario is not supported?

Sorry for the confusion, actually it not mean 'not supported' , I just want to test a basic viomem function case  along with some unique cases on the driver side at the first time.

But currently， I will also test 'reboot scenario' to make the 'cfg file ' clear.



> @menli820 just to clarify... why the reboot scenario is not supported?

Sorry for the confusion, actually it not mean 'not supported' , I just want to test a basic viomem function case  along with some unique cases on the driver side at the first time.

But currently， I will also test 'reboot scenario' to make the 'cfg file ' clear.

**Comment by mcasquer** [comment]
@menli820 I see; so keeping in mind the product bug, the rest looks fine to me

**Review by mcasquer — APPROVED** [review]
LGTM

**Comment by menli820** [comment]
@PaulYuuu  please help me review it when you free, thanks

**Comment by PaulYuuu** [comment]
I don't have any comments for your code, only one regarding for your git commit.

Git will automatically add the signoff trailer for new commits with `-s`, with the correct format. the email address should be quoted with `<>`.

**Comment by menli820** [comment]
> I don't have any comments for your code, only one regarding for your git commit.
> 
> Git will automatically add the signoff trailer for new commits with `-s`, with the correct format. the email address should be quoted with `<>`.

Many thanks for point it, update it.

**Review by PaulYuuu — APPROVED** [review]

**Pull request merged**
