### PR TITLE
Add some basic test cases of SVE

### PR DESCRIPTION
**Pull request by PaulYuuu**
ID: 1970784, 1970785, 1970786
Depends on: https://github.com/avocado-framework/avocado-vt/pull/3094
Signed-off-by: Yihuang Yu <yihyu@redhat.com>

### CODE REVIEW

**Comment by zhenyzha** [comment]
After discussion, PaulYuuu will optimize a new version, and the review will be available next week.

**Comment by PaulYuuu** [comment]
Hello @zhenyzha , could you help review the patch? Thanks.

**Comment by zhenyzha** [comment]
git am 3094.patch 
Applying: qemu_monitor: Introduce query_cpu_model_expansion in QMPMonitor

git am 2854.patch 
Applying: Add some basic test cases of SVE

python3 ConfigTest.py --guestname=RHEL.8.5.0 --platform=aarch64 --machines=arm64-pci --driveformat=virtio_scsi --nicmodel=virtio_net --mem=8192 --vcpu=8 --testcase=boot 

```
 (1/3) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.aarch64.io-github-autotest-qemu.sve_basic.arm64-pci: PASS (309.38 s)
 (2/3) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.aarch64.io-github-autotest-qemu.sve_basic.unsupported_length.arm64-pci: PASS (39.21 s)
 (3/3) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.aarch64.io-github-autotest-qemu.sve_basic.unsupported_length.invalid_length.arm64-pci: PASS (8.07 s)
```

Hello @PaulYuuu 
Do we plan to continue to develop new cases in this patch or push a new patch?

**Comment by PaulYuuu** [comment]
@zhenyzha yes, this patch only contains basic SVE test cases, and another patch will be sent to test some suite for SVE.

**Review by zhenyzha — APPROVED** [review]

**Comment by zhenyzha** [comment]
Ok, I got it.

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Comment by PaulYuuu** [comment]
Thank you @zhenyzha. Could you also help to review the dependency patch https://github.com/avocado-framework/avocado-vt/pull/3094 as well?

**Comment by PaulYuuu** [comment]
Thank you.

**Pull request merged**
