### PR TITLE
Remove the compilation options "--enable-demo=yes"

### PR DESCRIPTION
**Pull request by yanglei-rh**
Does not compile netperf package

ID:1792856
Signed-off-by: Lei Yang <leiyang@redhat.com>

### CODE REVIEW

**Comment by yanglei-rh** [comment]
@kimi1978wy @xutian Please help to review it,thanks.

**Comment by kimi1978wy** [comment]
LGTM

Acked by: Yu Wang <wyu@redhat.com>

No compile error now, test on RHEL8.2.0
 (1/4) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.nic_opt.opt_test_netperf.indirect_desc.opt_on.q35: PASS (320.10 s)
 (2/4) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.nic_opt.opt_test_netperf.indirect_desc.opt_off.q35: PASS (307.91 s)
 (3/4) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.nic_opt.opt_test_netperf.mrg_rxbuf.opt_on.q35: PASS (302.51 s)
 (4/4) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.nic_opt.opt_test_netperf.mrg_rxbuf.opt_off.q35: PASS (303.22 s)

**Comment by yanglei-rh** [comment]
@xutian During the run automation,command "./configure --build=x86_64 && make" has compiled package netperf-2.6.0.tar.bz2,so i think "compile_option" should be None.

**Comment by xutian** [comment]
Please double check and confirm the package.  if it's compiled package, it will not work for ppc platform.

**Comment by PaulYuuu** [comment]
The point of the issue is the compilation options `--enable-demo`
https://github.com/avocado-framework/avocado-vt/blob/3f96d3897ffff6073d57156d1e99e231b64932df/virttest/utils_netperf.py#L178-L183

>      configure --enable-demo
> and compile netperf to enable netperf to emit “interim results” at semi-regular intervals. This enables a global -D option which takes a reporting interval as an argument. With that specified, the output of netperf will then look something like

It should be a compatibility issue caused by rhel8.2 upgraded gcc version, so other netperf test cases may hit the same situation. We need to consider if this option is really necessary in our tests.

**Comment by yanglei-rh** [comment]
@PaulYuuu Could you help me review it with the ppc plateform.

**Comment by PaulYuuu** [comment]
For this case, `enable-demo` is not needed.
But I recommend leaving `compile_option` empty on avocado-vt.

Acked-by: Yihuang Yu <yihyu@redhat.com>

**Comment by PaulYuuu** [comment]
For this case, `enable-demo` is not needed.

**Comment by yanglei-rh** [comment]
@xutian Please help me review it again,thanks a lot.

**Pull request merged**
