### PR TITLE
Snapshot during guest reboot for blockdev

### PR DESCRIPTION
**Pull request by aliang123**
blockdev_snapshot_reboot:do snapshot during guest reboot

Signed-off-by: aliang123 <aliang@redhat.com>

id: 1798920

### CODE REVIEW

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_reboot: PASS (58.76 s)

**Comment by aliang123** [comment]
@meet-lucky, @ngu, @xutian , please help to review, thanks

**Comment by meet-lucky** [comment]
(1/3) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (1121.12 s)
 (2/3) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.rh_kernel_update.q35: CANCEL: The snapshot=on is not supported by -blockdev. (10.08 s)
 (3/3) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_reboot.q35: PASS (92.44 s)

Acked-by:   Qian Dong   qdong@redhat.com

**Comment by ngu-niny** [comment]
Test Pass and LGTM:

 (1/6) repeat1.Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.ppc64le.io-github-autotest-qemu.blockdev_snapshot_reboot: PASS (92.74 s)
 (2/6) repeat2.Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.ppc64le.io-github-autotest-qemu.blockdev_snapshot_reboot: PASS (83.07 s)

Acked-by: Nini Gu <ngu@redhat.com>

**Comment by aliang123** [comment]
@xutian, please help to merge, thanks.

**Comment by aliang123** [comment]
thanks all, @xutian, @ngu-niny  and @meet-lucky

**Pull request merged**
