### PR TITLE
passthrough_fc_with_lun_device: Fix cache mode error

### PR DESCRIPTION
**Pull request by qingwangrh**
ID:2027252
Signed-off-by: qingwangrh <qinwang@redhat.com>

### CODE REVIEW

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=passthrough_fc_with_lun_device.with_scsi_generic.q35 --guestname=RHEL.8.4.0 --machines=q35 --clone=no  --customsparams="image_aio=native"

(1/1) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_generic.q35: PASS (55.11 s)

**Comment by qingwangrh** [comment]
@zhenyzha @YongxueHong Please help to review.

**Comment by YongxueHong** [comment]
Can you explain the detail about the cache mode error and what the reason leads in your commit message?
Thanks.

**Comment by qingwangrh** [comment]
> Can you explain the detail about the cache mode error and what the reason leads in your commit message? Thanks.

-blockdev node-name=host_device_stg0,driver=host_device,auto-read-only=on,discard=unmap,aio=native,filename=/dev/sg2,cache.direct=on,cache.no-flush=off \
-blockdev node-name=drive_stg0,driver=raw,read-only=off,cache.direct=on,cache.no-flush=off,file=host_device_stg0 \
-device scsi-generic,id=stg0,drive=drive_stg0 \

After fix:

-blockdev node-name=host_device_stg0,driver=host_device,auto-read-only=on,discard=unmap,aio=threads,filename=/dev/sg2,cache.direct=off,cache.no-flush=off \
-blockdev node-name=drive_stg0,driver=raw,read-only=off,cache.direct=off,cache.no-flush=off,file=host_device_stg0 \
-device scsi-generic,id=stg0,drive=drive_stg0 \

**Comment by YongxueHong** [comment]
Sorry, maybe I didn't show my point clearly.
I mean what is the cache mode error, why do you set the aio to threads.
And please add those into your commit message, not conversation here.

**Comment by qingwangrh** [comment]
> Sorry, maybe I didn't show my point clearly. I mean what is the cache mode error, why do you set the aio to threads. And please add those into your commit message, not conversation here.

updated

**Review by YongxueHong — APPROVED** [review]

**Comment by zhenyzha** [comment]
Sorry for the delay, there is no host for FC devices on ARM, please ignore me

**Comment by qingwangrh** [comment]
@XueqiangWei Please help to review

**Pull request merged**
