### PR TITLE
Fix some style issues in python files

### PR DESCRIPTION
**Pull request by PaulYuuu**
inspekt enables a new pylint style check, so some issues are reported,
and it causes the gh actions check to fail.

ID: 2114624
Signed-off-by: Yihuang Yu <yihyu@redhat.com>

### CODE REVIEW

**Comment by PaulYuuu** [comment]
Hello @luckyh @yanan-fu @YongxueHong, feel free to review this PR, thanks.

**Comment by luckyh** [comment]
@zhencliu

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by zhencliu** [comment]
> @zhencliu

Thanks Xu for letting me know this, and thanks Yihuang for the fix.
LGTM

**Review by yanan-fu — APPROVED** [review]
Ack

**Pull request merged**
