### PR TITLE
Update cfg info for slof_hugepage

### PR DESCRIPTION
**Pull request by fbq815**
correct the params' key values which includes 'mem1'
ID:1862900

Signed-off-by: Boqiao Fu <bfu@redhat.com>

### CODE REVIEW

**Comment by fbq815** [comment]
@PaulYuuu @wangxianxian

**Comment by fbq815** [comment]
@PaulYuuu @wangxianxian please help me review this update

**Comment by PaulYuuu** [comment]
> correct the params' key values which includes 'mem1'
> 
> Signed-off-by: Boqiao Fu [bfu@redhat.com](mailto:bfu@redhat.com)

Please add the bug ID.

**Comment by wangxianxian** [comment]
slof_hugepage.with_backing_file_hotplug: PASS
slof_hugepage.without_backing_file_hotplug: PASS

ACK

**Pull request merged**
