### PR TITLE
qemu.tests: Add qemu_disk_img_rebase test case

### PR DESCRIPTION
**Pull request by Chenditang**
test "-b """ for qemu-img rebase.

This PR depends on autotest/virt-test#2231

### CODE REVIEW

**Comment by Chenditang** [comment]
The test result on libvirt-1.2.13 fc20.x86_64

\# ./run -t qemu --no-downloads -k --tests qemu_disk_img.rebase
SETUP: PASS (0.20 s)
DATA DIR: /var/lib/virt_test
DEBUG LOG: /root/autotest/client/tests/virt/logs/run-2015-06-29-17.47.10/debug.log
TESTS: 6
(1/6) type_specific.io-github-autotest-qemu.qemu_disk_img.rebase.snB.to_base: PASS (195.20 s)
(2/6) type_specific.io-github-autotest-qemu.qemu_disk_img.rebase.snB.to_null: PASS (542.23 s)
(3/6) type_specific.io-github-autotest-qemu.qemu_disk_img.rebase.snC.to_base: PASS (787.46 s)
(4/6) type_specific.io-github-autotest-qemu.qemu_disk_img.rebase.snC.to_new.default: PASS (798.77 s)
(5/6) type_specific.io-github-autotest-qemu.qemu_disk_img.rebase.snC.to_new.restore_to_snB: PASS (832.81 s)
(6/6) type_specific.io-github-autotest-qemu.qemu_disk_img.rebase.snD.to_snB_snA_base: PASS (363.35 s)
TOTAL TIME: 3519.90 s (58:39)
TESTS PASSED: 6
TESTS FAILED: 0
SUCCESS RATE: 100.00 %

**Comment by xutian** [comment]
LGTM,

Acked-by: Xu Tian <xutian@redhat.com>

**Comment by xiagao** [comment]
NACK-by <xiagao@redhat.com>

python ConfigTest.py --testcase=qemu_disk_img.rebase.snB.to_null --guestname=RHEL.7.1 --clone=no

debug log:
08/05 13:43:25 DEBUG|      virt:0063|     name = smp_16.16384m.repeat1.run_test.Host_RHEL.7.2.i440fx.vnc.bridge.default_bios.no_virtio_rng.(image_backend=filesystem).no_9p_export.smallpages.no_pci_assignable.qcow2.virtio_blk.up.virtio_net.Linux.RHEL.7.1.x86_64.(subtest=type_specific).(subtest=io-github-autotest-qemu).(subtest=qemu_disk_img).rebase.snB.to_null


08/05 13:44:59 INFO |     error:0085| Context: rebase snapshot to backingfile
08/05 13:44:59 INFO |qemu_stora:0278| Rebase snapshot /home/my_auto/autotest-devel/client/tests/virt/shared/data/images/snB.qcow2 to /home/my_auto/autotest-devel/client/tests/virt/shared/data/images/snB.qcow2...
                                                                 ^^^^^^^^^^^^^^
08/05 13:44:59 DEBUG|     utils:0114| Running '/bin/qemu-img rebase -f qcow2 -b /home/my_auto/autotest-devel/client/tests/virt/shared/data/images/snB.qcow2 -F qcow2 /home/my_auto/autotest-devel/client/tests/virt/shared/data/images/snB.qcow2'
08/05 13:45:01 WARNI|env_proces:1296| virt-tests-vm1 is not alive. Can't query the register status
08/05 13:45:15 DEBUG|qemu_stora:0367| Run qemu-img info comamnd on /home/my_auto/autotest-devel/client/tests/virt/shared/data/images/snB.qcow2
08/05 13:45:15 DEBUG|     utils:0114| Running '/bin/qemu-img info /home/my_auto/autotest-devel/client/tests/virt/shared/data/images/snB.qcow2'
08/05 13:45:15 ERROR|      virt:0171| Test failed: TestFail: Expected backing file is null! Actual backing file: <_sre.SRE_Match object at 0x7faca5279828>

**Comment by ypu** [comment]
Confirmed with @xiagao seems she didn't apply the virt part patch. So ignore her Nack.

**Comment by ypu** [comment]
LGTM 

Acked-by: Yiqiao Pu <ypu@redhat.com>

Thanks @Chenditang and @xutian will merge it

**Pull request merged**
