### PR TITLE
Add function test after install vioser by installer

### PR DESCRIPTION
**Pull request by 6-dehan**
Add driver vioser function test if the driver installed by installer.

ID: 2102925
Signed-off-by: demeng <demeng@redhat.com>

### CODE REVIEW

**Comment by 6-dehan** [comment]
@vivianQizhu @xiagao  Could you guys please help to review it?  
comment: this case still can hit an existing auto bug 1931711.

**Review by vivianQizhu — DISMISSED** [review]
LGTM, @xiagao Would you please help test it? Thanks.

**Comment by 6-dehan** [comment]
it's my comment. this is an existed automation bug.

**Comment by vivianQizhu** [comment]
@xiagao Thanks for the test, if it went there then if means this patch is fine. But considering our status, I leave this PR here until I fix the other issue you hit.

**Comment by 6-dehan** [comment]
update result here, Case  can be passed with @vivianQizhu patch https://github.com/avocado-framework/avocado-vt/pull/3602
 (1/1) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.win_virtio_driver_install_by_installer.driver_install.single_driver.with_vioser.q35: STARTED
 (1/1) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.win_virtio_driver_install_by_installer.driver_install.single_driver.with_vioser.q35: PASS (463.34 s)

**Comment by vivianQizhu** [comment]
@6-dehan Please resolve the conflict so that we can merge it.

**Comment by 6-dehan** [comment]
> @6-dehan Please resolve the conflict so that we can merge it.

done.

**Review by vivianQizhu — APPROVED** [review]

**Pull request merged**
