### PR TITLE
expose_host_mtu:fix the issue of module not found

### PR DESCRIPTION
**Pull request by leidwang**
Since configure_network.py has been deleted,So some changes
were made to solve the issue.

Signed-off-by: Leidong Wang <leidwang@redhat.com>
ID:2030091

### CODE REVIEW

**Comment by leidwang** [comment]
Hi @PaulYuuu ,Could you help to review this patch?Thanks!

**Review by PaulYuuu — APPROVED** [review]

**Comment by leidwang** [comment]
Hi @yanglei-rh Could you help to review this patch?Thanks!

**Comment by leidwang** [comment]
JOB LOG    : /root/avocado/job-results/job-2021-12-09T20.46-f8c32e3/job.log
 (1/1) Host_RHEL.mx.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.expose_host_mtu.q35: PASS (143.36 s)

**Comment by yanglei-rh** [comment]
(1/1) Host_RHEL.m8.u6.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.expose_host_mtu.q35: PASS (58.01 s)

**Comment by yanglei-rh** [comment]
LGTM

**Review by yanglei-rh — APPROVED** [review]

**Pull request merged**
