### PR TITLE
drive_mirror_negative_tests: fix typo

### PR DESCRIPTION
**Pull request by vivianQizhu**
id: 1409036
Signed-off-by: Qianqian Zhu <qizhu@redhat.com>

### CODE REVIEW

**Comment by vivianQizhu** [comment]
@CongLi Would you help review? Thanks.

**Comment by CongLi** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by yanan-fu** [comment]
LGTM.
Acked-by Yanan Fu yfu@redhat.com

And, will you replace "drive_mirror_negtive_tests"  with "drive_mirror_negative_tests" in all of the code?
such as function_all.cfg in staf.

**Comment by xutian** [comment]
@vivianQizhu don't forget to update case name in staf test loop.

**Comment by vivianQizhu** [comment]
@yanan-fu Thanks for your reminding, I will.

**Comment by CongLi** [comment]
Add results:
 (1/6) smp_8.8192m.repeat1.run_test.Host_RHEL.m6.u9.qcow2.virtio_blk.up.virtio_net.RHEL.6.9.x86_64.io-github-autotest-qemu.drive_mirror_negative_tests.readonly_target.2qcow2: PASS (343.85 s)

**Pull request merged**
