### PR TITLE
blockdev_full_backup_x_perf: backup with performance options

### PR DESCRIPTION
**Pull request by aliang123**
Backup with performace options:x-perf

Signed-off-by: Aihua Liang <aliang@redhat.com>
id:2013536

### CODE REVIEW

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_full_backup_x_perf.q35: PASS (75.88 s)

**Comment by aliang123** [comment]
@zhencliu @ngu-niny, please help to review, thanks.

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_full_backup_x_perf.q35: PASS (69.73 s)

**Comment by ngu-niny** [comment]
Test on ppc PASS:

PASS 1-Host_RHEL.m8.u6.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_full_backup_x_perf

**Pull request merged**
