### PR TITLE
multi_disk: Set timeout for getting windows disk index

### PR DESCRIPTION
**Pull request by YongxueHong**
Set timeout for getting multiple disks in windows.

ID: 1699204
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by XueqiangWei** [comment]
LGTM,
Acked-by xuwei@redhat.com

**Comment by YongxueHong** [comment]
Depends on https://github.com/avocado-framework/avocado-vt/pull/2039

**Comment by YongxueHong** [comment]
@peixiu  Could you help me to review, thanks.

**Comment by peixiu** [comment]
LGTM,
Acked-by: Peixiu Hou phou@redhat.com

**Review by peixiu — APPROVED** [review]

**Pull request merged**
