### PR TITLE
qemu.tests: Add timeout for prepare_cmd in openflow_test

### PR DESCRIPTION
**Pull request by spcui**
dd copy_file=1G will spend more time in guest, default timeout=60
is not enough for it, so update it.

Signed-off-by: Shuping Cui <scui@redhat.com>

### CODE REVIEW

**Comment by spcui** [comment]
ID: 1203120

**Comment by spcui** [comment]
# ../../tools/scan_results.py 
Test                                                                                                                                                Status     Seconds  Info
----                                                                                                                                                ------     -------  ----
        (Result file: /root/staf-kvm-devel/autotest-devel/client/results/default/status)
virt.qemu.smp_8.16384m.repeat1.run_test.Host_RHEL.6.6.qcow2.virtio_scsi.up.virtio_net.RHEL.7.1.x86_64.io-github-autotest-qemu.openflow_test.icmp    GOOD       294      completed successfully

**Comment by xutian** [comment]
@spcui  why not make it configurable?

@xutian

**Comment by spcui** [comment]
Hi @xutian updated, help review again, thx

**Comment by CongSmile** [comment]
Hi @spcui 

Why not use /dev/zero instead?

**Comment by spcui** [comment]
Hi @CongSmile  updated via your comment, could you help review it?

**Comment by CongSmile** [comment]
Hi scui,

Is it enough (360s) of the timeout that uses the login_timeout as timeout?

**Comment by spcui** [comment]
@CongSmile , yes, if using /dev/zero for 1GB file, login_timeout is enough.

**Comment by ypu** [comment]
@spcui although login_timeout is enough for scp but we'd better use different parameters for different use. It is more clear and easier for others to read the code.

**Comment by spcui** [comment]
@ypu updated now, help review again, thanks.

**Comment by ypu** [comment]
LGTM
Acked-by: Yiqiao Pu <ypu@redhat.com>

**Comment by suqinhuang** [comment]
Acked-by: Suqin Huang

**Comment by xutian** [comment]
Thanks  @spcui  @CongSmile  @ypu  and @suqinhuang 

Merged

**Pull request merged**
