### PR TITLE
usb.usb_host: fixs a string formatting error for communicating with HMP

### PR DESCRIPTION
**Pull request by hereischen**
usb.usb_host: fixs a string formatting error for communicating with HMP
Signed-off-by: Haotong Chen <hachen@redhat.com>

ID:1422746

### CODE REVIEW

**Comment by xutian** [comment]
better to test with QMP,  @hereischen  please try to refractory  this case with qdevice

**Comment by maxujun** [comment]
@hereischen The sleep time in usb_dev_hotplug() it not enough for some case .suggest increasing to 2s.

**Comment by hereischen** [comment]
@maxujun Updated. Many thanks.

**Comment by maxujun** [comment]
LGTM,Acked-by: xuma@redhat.com

**Comment by xutian** [comment]
@hereischen  I will merged this pull first, please send a new pull request to re-factor this test case with qdevice.

Thanks,
Xu

**Comment by hereischen** [comment]
@xutian OK, Many thanks, will do it later

**Pull request merged**
