### PR TITLE
qemu.tests.device_option_check: fix the issue of finding property from qtree

### PR DESCRIPTION
**Pull request by luckyh**
Depends on: https://github.com/avocado-framework/avocado-vt/pull/479

ID: 1327925

### CODE REVIEW

**Comment by PandaWei** [comment]
TESTed and ACK

**Comment by Zhengtong** [comment]
Acked-by : Zhengtong <zhengtli@redhat.com>

The code is fine for me , and run passed with test case device_option_check.blk_serial_check.

**Comment by spcui** [comment]
LGTM
Acked-by: scui@redhat.com

**Comment by xutian** [comment]
Merged, thanks @luckyh @PandaWei and @spcui

**Pull request merged**
