### PR TITLE
nic_opt: Change to ping guest from host

### PR DESCRIPTION
**Pull request by yanglei-rh**
ID:2023143

Signed-off-by: Lei Yang <leiayang@redhat.com>

### CODE REVIEW

**Comment by yanglei-rh** [comment]
Test Pass:
 (1/8) Host_RHEL.m8.u6.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.nic_opt.opt_test_ping.poll-us.opt_30.q35: PASS (261.55 s)
 (2/8) Host_RHEL.m8.u6.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.nic_opt.opt_test_ping.poll-us.opt_50.q35: PASS (241.19 s)
 (3/8) Host_RHEL.m8.u6.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_1.ctrl_vq_on.mq_opt_on.q35: PASS (287.43 s)
 (4/8) Host_RHEL.m8.u6.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_1.ctrl_vq_on.mq_opt_off.q35: PASS (282.79 s)
 (5/8) Host_RHEL.m8.u6.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_4.ctrl_vq_on.mq_opt_on.q35: PASS (253.58 s)
 (6/8) Host_RHEL.m8.u6.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_4.ctrl_vq_on.mq_opt_off.q35: PASS (239.95 s)
 (7/8) Host_RHEL.m8.u6.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_8.ctrl_vq_on.mq_opt_on.q35: CANCEL: The number of smp counts in this host is not big enough (24.00 s)
 (8/8) Host_RHEL.m8.u6.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_8.ctrl_vq_on.mq_opt_off.q35: CANCEL: The number of smp counts in this host is not big enough (52.33 s)

**Comment by yanglei-rh** [comment]
Hi @PaulYuuu Could you please help me review it？ Thanks a lot.

**Review by PaulYuuu — APPROVED** [review]

**Comment by PaulYuuu** [comment]
Can you also provide test results of Linux guest?

**Comment by yanglei-rh** [comment]
Test Pass:
 (1/8) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.nic_opt.opt_test_ping.poll-us.opt_30.q35: PASS (196.68 s)
 (2/8) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.nic_opt.opt_test_ping.poll-us.opt_50.q35: PASS (189.72 s)
 (3/8) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_1.ctrl_vq_on.mq_opt_on.q35: PASS (205.40 s)
 (4/8) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_1.ctrl_vq_on.mq_opt_off.q35: PASS (205.87 s)
 (5/8) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_4.ctrl_vq_on.mq_opt_on.q35: PASS (188.97 s)
 (6/8) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_4.ctrl_vq_on.mq_opt_off.q35: PASS (191.58 s)
 (7/8) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_8.ctrl_vq_on.mq_opt_on.q35: CANCEL: The number of smp counts in this host is not big enough (34.71 s)
 (8/8) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_8.ctrl_vq_on.mq_opt_off.q35: CANCEL: The number of smp counts in this host is not big enough (52.28 s)

**Pull request merged**
