### PR TITLE
Make ovs mirror works on private ovs bridge

### PR DESCRIPTION
**Pull request by xutian**
make ovs mirror related case works on private ovs birdge to avoid complex network environment impact test result.

ID: 1189025
Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by CongSmile** [comment]
14:49:22 INFO | 		ERROR	virt.qemu.smp_4.4096m.repeat1.run_test.Host_RHEL.7.1.qcow2.virtio_blk.up.virtio_net.RHEL.7.1.x86_64.io-github-autotest-qemu.ovs_mirror.mirror_output	virt.qemu.smp_4.4096m.repeat1.run_test.Host_RHEL.7.1.qcow2.virtio_blk.up.virtio_net.RHEL.7.1.x86_64.io-github-autotest-qemu.ovs_mirror.mirror_output	timestamp=1425538162	localtime=Mar 05 14:49:22	Command <ovs-vsctl set Bridge br0 mirrors=@m  - -   - - i d = @ t 0 - U L k r Y V   g e t   P o r t   t 0 - U L k r Y V   - -   - - i d = @ t 0 - n D 1 k O 1   g e t   P o r t   t 0 - n D 1 k O 1   -- --id=@m create Mirror name=output_of_t0-nD1kO1 select-src-port=@t0-nD1kO1 output-port=@t0-ULkrYV> failed, rc=1, Command returned non-zero exit status    [context: Create mirror port in ovs]
  * Command: 
      ovs-vsctl set Bridge br0 mirrors=@m  - -   - - i d = @ t 0 - U L k r Y V
      g e t   P o r t   t 0 - U L k r Y V   - -   - - i d = @ t 0 - n D 1 k O 1
      g e t   P o r t   t 0 - n D 1 k O 1   -- --id=@m create Mirror
      name=output_of_t0-nD1kO1 select-src-port=@t0-nD1kO1 output-port=@t0-ULkrYV
  Exit status: 1
  Duration: 0.014132976532
  
  stderr:
  ovs-vsctl: Bridge does not contain a column whose name matches "-"

**Comment by xutian** [comment]
@CongSmile 

thanks for you kindly test. has fixed it, would you like to review it.

Thanks,
Xu

**Comment by CongSmile** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by spcui** [comment]
Acked-by: @spcui

**Comment by xutian** [comment]
Merged it, thanks comment from  @spcui  and @CongSmile .

**Pull request merged**
