### PR TITLE
virtio-fs: use virtiofs service method for driver test

### PR DESCRIPTION
**Pull request by xiagao**
Using service method to start virtiofs exd for driver
 load stress test case and driver update test case.
ID: 1958471
Signed-off-by: Xiaoling Gao <xiagao@redhat.com>

### CODE REVIEW

**Comment by xiagao** [comment]
@YongxueHong Could you help review?

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by YongxueHong** [comment]
Please upload the test results of the latest codes, thanks.

**Comment by xiagao** [comment]
@YongxueHong  
(1/3) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.driver_load_stress.with_viofs.during_bg_test.q35: PASS (1093.39 s)
 (2/3) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_viofs.during_bg_test.uninstall_install.q35: PASS (466.65 s)
 (3/3) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_viofs.during_bg_test.downgrade_upgrade.q35: PASS (565.62 s)

**Pull request merged**
