### PR TITLE
usb_multi_disk: add "msdos" labeltype for Windows guest

### PR DESCRIPTION
**Pull request by ybduan**
ID: 1846592

Signed-off-by: ybduan <yduan@redhat.com>

### CODE REVIEW

**Comment by ybduan** [comment]
(1/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.usb.usb_multi_disk.one_disk_repeat.without_usb_hub.nec-xhci.q35: PASS (206.07 s)
 (2/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.usb.usb_multi_disk.one_disk_repeat.without_usb_hub.qemu-xhci.q35: PASS (206.85 s)
 (3/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.usb.usb_multi_disk.max_disk.without_usb_hub.nec-xhci.q35: PASS (509.34 s)
 (4/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.usb.usb_multi_disk.max_disk.without_usb_hub.qemu-xhci.q35: PASS (520.45 s)

**Comment by ybduan** [comment]
Please help review this PR, thanks! @yanan-fu

**Comment by yanan-fu** [comment]
@ybduan  Double confirm:
1. For linux guest: labeltype: gpt,  file_system/fstype: ext4
2. For Windows guest: labeltype:  msdos, file_system/fstype: random ntfs, fat32

Is it right ?

**Comment by ybduan** [comment]
> @ybduan Double confirm:
> 
>     1. For linux guest: labeltype: gpt,  file_system/fstype: ext4
> 
>     2. For Windows guest: labeltype:  msdos, file_system/fstype: random ntfs, fat32
> 
> 
> Is it right ?

yes

**Comment by yanan-fu** [comment]
Ok, thanks!

Acked-by: Yanan Fu <yfu@redhat.com>

**Pull request merged**
