### PR TITLE
Updated vsock_test_suite to include new test cases

### PR DESCRIPTION
**Pull request by qcheng-redhat**
Updated vsock_test_suite to include new test cases

ID: 1753

### CODE REVIEW

**Comment by qcheng-redhat** [comment]
Hi @XueqiangWei, please help review this patch, thanks.

**Comment by qcheng-redhat** [comment]
(14/14) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.vsock_test.vsock_test_suite.q35: PASS (89.63 s)

**Comment by XueqiangWei** [comment]
@zhenyzha  Could you please verify it on aarch64 platform? Many thanks.

**Comment by XueqiangWei** [comment]
suggest to update the commit message, like "vsock_test: update vsock_test_suite to include new test cases"

**Comment by zhenyzha** [comment]
@BohdanMar Could you pls help review when you are free? thanks.

**Comment by BohdanMar** [comment]
Testcase PASS:

JOB ID     : 3384ca259e4676c8fa6f4ce24b362df30fdda3c3
JOB LOG    : /root/avocado/job-results/job-2024-01-02T08.39-3384ca2/job.log
 (1/1) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.vsock_test.vsock_test_suite.arm64-pci: STARTED
 (1/1) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.vsock_test.vsock_test_suite.arm64-pci: PASS (67.97 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2024-01-02T08.39-3384ca2/results.html
JOB TIME   : 69.07 s

LGTM

**Review by XueqiangWei — APPROVED** [review]
LGTM,
Acked-by: xuwei@redhat.com

**Pull request merged**
