### PR TITLE
block_multifunction_scale:fix syntax error for 'or'

### PR DESCRIPTION
**Pull request by maxujun**
Add separate 'in' item for both condition
ID:2168474

### CODE REVIEW

**Comment by maxujun** [comment]
Same issue as https://github.com/autotest/tp-qemu/pull/3536
@MiriamDeng @qingwangrh @zhenyzha Could you help review?

**Review by zhenyzha — APPROVED** [review]

**Comment by MiriamDeng** [comment]
Can you provide test results ? Thanks

**Comment by maxujun** [comment]
(1/1) Host_RHEL.m8.u4.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.2.0.ppc64le.io-github-autotest-qemu.block_multifunction.multi_disks: PASS (115.23 s)

**Comment by MiriamDeng** [comment]
LGTM

**Comment by qingwangrh** [comment]
LGTM

**Comment by maxujun** [comment]
@PaulYuuu Could you have a look?

**Review by PaulYuuu — APPROVED** [review]

**Pull request merged**
