### PR TITLE
Update all cases that called setup_win_driver_verifier()

### PR DESCRIPTION
**Pull request by peixiu**
For all called setup_win_driver_verifier() cases,
do updates to match with adjusts.

ID: 1919753
Signed-off-by: Peixiu Hou <phou@redhat.com>

### CODE REVIEW

**Comment by peixiu** [comment]
(1/3) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.vioinput_mice.device_mouse: PASS (104.47 s)
 (2/3) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.vioinput_mice.device_tablet: PASS (102.26 s)
 (3/3) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.vioinput_keyboard: PASS (117.24 s)

 (01/12) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_shutdown: PASS (181.98 s)
 (02/12) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_reboot: PASS (175.44 s)
 (03/12) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_system_reset: PASS (167.58 s)
 (04/12) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_live_migration: PASS (153.78 s)
 (05/12) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.vioinput_enable.device_mouse.with_shutdown: PASS (167.18 s)
 (06/12) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.vioinput_enable.device_mouse.with_reboot: PASS (179.98 s)
 (07/12) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.vioinput_enable.device_mouse.with_system_reset: PASS (144.44 s)
 (08/12) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.vioinput_enable.device_mouse.with_live_migration: PASS (141.76 s)
 (09/12) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.vioinput_enable.device_tablet.with_shutdown: PASS (165.10 s)
 (10/12) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.vioinput_enable.device_tablet.with_reboot: PASS (158.66 s)
 (11/12) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.vioinput_enable.device_tablet.with_system_reset: PASS (152.99 s)
 (12/12) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.vioinput_enable.device_tablet.with_live_migration: PASS (140.34 s)

**Comment by peixiu** [comment]
@kimi1978wy Could you help to review this patch? it's based to https://github.com/avocado-framework/avocado-vt/pull/3003

Thanks~
Peixiu

**Comment by peixiu** [comment]
@YongxueHong Could you help to review it when you free? it's based to avocado-framework/avocado-vt#3003

Thanks~
Peixiu

**Review by kimi1978wy — COMMENTED** [review]
LGTM
Acked-by: Yu Wang <wyu@redhat.com>

**Review by kimi1978wy — APPROVED** [review]

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
