### PR TITLE
spapr_vty: New case to test spapr-vty device to login and hot-unplug

### PR DESCRIPTION
**Pull request by zhenyzha**
New case to test spapr-vty device to login and hot-unplug.

id:1865726,1865795

Signed-off-by: Zhenyu Zhang <zhenyzha@redhat.com>

### CODE REVIEW

**Comment by zhenyzha** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.chardev_pci_serial_login: PASS (537.63 s)

@PaulYuuu @MiriamDeng Please help me to review, thanks.

**Comment by MiriamDeng** [comment]
The patch works  and I just have one concern it's a bit confusing for us to use pci-serial as the test case name but not spapr-vty  since pci-serial is only supported on x86.  They are different. Correct me if I was wrong, thanks.

**Comment by zhenyzha** [comment]
> The patch works and I just have one concern it's a bit confusing for us to use pci-serial as the test case name but not spapr-vty since pci-serial is only supported on x86. They are different. Correct me if I was wrong, thanks.

Considering the problem of code redundancy, I do not recommend writing a new one. We can add it to a loop with an appropriate name. What do you think@PaulYuuu

**Comment by PaulYuuu** [comment]
You can modify the cfg with a new name or create another one cfg but make `type = chardev_pci_serial_login`, I pick the latter.

**Comment by zhenyzha** [comment]
> You can modify the cfg with a new name or create another one cfg but make `type = chardev_pci_serial_login`, I pick the latter.

Good idea, I think creating a new cfg is suitable for this situation. Update later.

**Comment by zhenyzha** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.spapr_vty_console_login: PASS (504.92 s)

@PaulYuuu @MiriamDeng Please help me to review, thanks.

**Comment by PaulYuuu** [comment]
LGTM

**Comment by MiriamDeng** [comment]
ACK

**Comment by MiriamDeng** [comment]
ACK

**Pull request merged**
