### PR TITLE
qsd_blockdev_check:fix qcow2 format support

### PR DESCRIPTION
**Pull request by qingwangrh**
Explicitly declare the image format.
Avoid mismatches with default value.

ID:2210617

### CODE REVIEW

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=qsd_blockdev_check --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=RHEL.9.3.0 --driveformat=virtio_scsi --imageformat=raw,qcow2 --firmware=default_bios --netdst=virbr0 --clone=no

 (1/2) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.qsd_blockdev_check.q35: STARTED
 (1/2) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.qsd_blockdev_check.q35: PASS (7.66 s)
 (2/2) Host_RHEL.m9.u3.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.qsd_blockdev_check.q35: STARTED
 (2/2) Host_RHEL.m9.u3.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.qsd_blockdev_check.q35: PASS (7.25 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by qingwangrh** [comment]
@XueqiangWei @zhenyzha Please help to review. thanks.

**Comment by XueqiangWei** [comment]
tested with edk2, the results were passed.

 (1/2) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.qsd_blockdev_check.q35: STARTED
 (1/2) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.qsd_blockdev_check.q35: PASS (7.16 s)
 (2/2) Host_RHEL.m9.u3.ovmf.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.qsd_blockdev_check.q35: STARTED
 (2/2) Host_RHEL.m9.u3.ovmf.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.qsd_blockdev_check.q35: PASS (6.78 s)

**Review by XueqiangWei — APPROVED** [review]

**Comment by XueqiangWei** [comment]
@zhenyzha Could you please help review it? Many thanks.

**Comment by zhenyzha** [comment]
git am 3770.patch
Applying: qsd_blockdev_check:fix qcow2 format support

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>
` (1/1) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.qsd_blockdev_check.arm64-pci: PASS (5.62 s)`

**Review by zhenyzha — APPROVED** [review]

**Pull request merged**
