### PR TITLE
sgx: Add thread_context object

### PR DESCRIPTION
**Pull request by zixi-chen**
ID: 2212

### CODE REVIEW

**Comment by zixi-chen** [comment]
@zhencliu could you please help to review this?
 (1/7) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.sgx_multi_vms.8_epcs_4_vms.q35: STARTED
 (1/7) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.sgx_multi_vms.8_epcs_4_vms.q35: PASS (163.41 s)
 (2/7) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.sgx_basic.without_numa.single_epc.q35: STARTED
 (2/7) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.sgx_basic.without_numa.single_epc.q35: PASS (94.24 s)
 (3/7) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.sgx_basic.without_numa.multi_epc.q35: STARTED
 (3/7) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.sgx_basic.without_numa.multi_epc.q35: PASS (45.32 s)
 (4/7) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.sgx_basic.with_numa.single_epc.q35: STARTED
 (4/7) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.sgx_basic.with_numa.single_epc.q35: PASS (45.02 s)
 (5/7) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.sgx_basic.with_numa.multi_epc.q35: STARTED
 (5/7) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.sgx_basic.with_numa.multi_epc.q35: PASS (43.66 s)
 (6/7) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.sgx_cpu.q35: STARTED
 (6/7) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.sgx_cpu.q35: PASS. (120.77 s)
 (7/7) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.sgx_cpu.sgx_cpu_host.q35: STARTED
 (7/7) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.sgx_cpu.sgx_cpu_host.q35: PASS (78.85 s)

**Comment by zhencliu** [comment]
> est-qemu.sgx_multi_vms.8_epcs_4_vms.q35: STARTED
> (1/7) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio

hi @zixi-chen , could you possibly paste the related qemu cmdline snippets?

**Comment by zixi-chen** [comment]
@zhencliu Also add sgx migration test case.
qemu cmdline of sgx_basic.with_numa.multi_epc
[stdlog]     -object '{"size": 67108864, "prealloc": true, "policy": "bind", "host-nodes": [0], "prealloc-context": "thread_context-tc0", "id": "mem-epc0", "qom-type": "memory-backend-epc"}' \
[stdlog]     -object '{"size": 29360128, "prealloc": true, "policy": "bind", "host-nodes": [1], "prealloc-context": "thread_context-tc1", "id": "mem-epc1", "qom-type": "memory-backend-epc"}' \
[stdlog]     -object '{"size": 67108864, "prealloc": false, "policy": "bind", "host-nodes": [0], "id": "mem-epc2", "qom-type": "memory-backend-epc"}' \
[stdlog]     -object '{"size": 29360128, "prealloc": false, "policy": "bind", "host-nodes": [1], "id": "mem-epc3", "qom-type": "memory-backend-epc"}' \
[stdlog]     -object '{"size": 3221225472, "policy": "bind", "host-nodes": [0], "id": "mem-mem0", "qom-type": "memory-backend-ram"}' \
[stdlog]     -object '{"size": 1073741824, "policy": "bind", "host-nodes": [1], "id": "mem-mem1", "qom-type": "memory-backend-ram"}' \
[stdlog]     -object thread-context,node-affinity=0,id=thread_context-tc0 \
[stdlog]     -object thread-context,node-affinity=0,id=thread_context-tc1  \
[stdlog]     -smp 6,maxcpus=6,cores=3,threads=1,dies=1,sockets=2  \
[stdlog]     -numa node,memdev=mem-mem0,cpus=4,cpus=5,nodeid=0  \
[stdlog]     -numa node,memdev=mem-mem1,cpus=0,cpus=1,cpus=2,cpus=3,nodeid=1  \

**Comment by zhencliu** [comment]
The thread context is a default setting by our layer product libvirt, to remove the gap, we add it in the sgx test cases. Currently VT *cannot* support thread context combined with any memory backend and it may take some time to implement it, so we have to workaround it by setting its id explicitly in the cfg, e.g. prealloc-context_epc0 = "thread_context-tc0". It's OK for the code change IMO.

**Review by zhencliu — APPROVED** [review]

**Pull request merged**
