### PR TITLE
virtio-fs: install viofs driver in Windows vm

### PR DESCRIPTION
**Pull request by xiagao**
Install viofs driver in a preinstalled windows guest.
ID: 1877701 
Signed-off-by: Xiaoling Gao <xiagao@redhat.com>

### CODE REVIEW

**Comment by xiagao** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.single_driver_install.with_viofs.virtio_win_iso_media.q35: PASS (251.66 s)

**Comment by xiagao** [comment]
some debug log:
03:55:40 INFO | Running virtiofs daemon command /usr/libexec/virtiofsd --socket-path=/var/tmp/avocado_279dzv36/avocado-vt-vm1-fs-virtiofsd.sock -o source=/var/lib/avocado/data/avocado-vt/virtio_fs_test/ -d.
03:55:41 INFO | Created virtiofs daemon process with parent PID 100932.
03:55:41 INFO | Running qemu command (reformatted):
MALLOC_PERTURB_=1  /usr/libexec/qemu-kvm \
    -S  \
.........
    -chardev socket,id=char_virtiofs_fs,path=/var/tmp/avocado_279dzv36/avocado-vt-vm1-fs-virtiofsd.sock \
    -device vhost-user-fs-pci,id=vufs_virtiofs_fs,chardev=char_virtiofs_fs,tag=myfs,queue-size=1024,bus=pcie.0,addr=0x3 \
    -m 4096 \
    -object memory-backend-file,size=4G,mem-path=/dev/shm,share=yes,id=mem-mem1  \
03:57:00 DEBUG| Sending command: D:\devcon\win7_amd64\devcon.exe updateni E:\viofs\2k19\amd64\viofs.inf "PCI\VEN_1AF4&DEV_105A"

**Comment by xiagao** [comment]
@menli820 @YongxueHong
Could you help review?

**Review by YongxueHong — APPROVED** [review]
LGTM

**Comment by menli820** [comment]
LGTM

python3 ConfigTest.py --testcase=single_driver_install.with_viofs.virtio_win_iso_media.q35  --guestname=Win2016 --platform=x86_64  --clone=no  --customsparams="cdrom_virtio = isos/windows/virtio-win-1.9.13-1.el8.iso" --machines=q35   --driveformat=virtio_blk

 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.single_driver_install.with_viofs.virtio_win_iso_media.q35: PASS (169.34 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2020-09-14T23.18-1c5fee0/results.html

related log:
MALLOC_PERTURB_=1  /usr/libexec/qemu-kvm \
    -S  \
    -name 'avocado-vt-vm1'  \
    -sandbox on  \
    -machine q35 \
    .......
    -m 4096 \
    -object memory-backend-file,size=4G,mem-path=/dev/shm,share=yes,id=mem-mem1  \
    -smp 20,maxcpus=20,cores=10,threads=1,dies=1,sockets=2  \
    -numa node,memdev=mem-mem1,nodeid=0  \
    .......
    -chardev socket,id=char_virtiofs_fs,path=/var/tmp/avocado_4icutxpi/avocado-vt-vm1-fs-virtiofsd.sock \
    -device vhost-user-fs-pci,id=vufs_virtiofs_fs,chardev=char_virtiofs_fs,tag=myfs,queue-size=1024,bus=pcie.0,addr=0x3 \
      ......



23:20:00 INFO | Context: Installing target driver
23:20:00 DEBUG| Sending command: D:\devcon\win7_amd64\devcon.exe find "PCI\VEN_1AF4&DEV_105A"
23:20:01 DEBUG| Sending command: D:\devcon\win7_amd64\devcon.exe updateni E:\viofs\2k16\amd64\viofs.inf "PCI\VEN_1AF4&DEV_105A"
23:20:05 DEBUG| Sending command: echo %errorlevel%
23:20:05 INFO | Context: Verifying target driver
23:20:05 INFO | Context: Verifying target driver --> rebooting 'avocado-vt-vm1'
.......

23:21:10 INFO | Context: Verifying target driver --> Check viofs driver state.
23:21:10 DEBUG| Sending command: wmic sysdriver where PathName="C:\\Windows\\System32\\drivers\\viofs.sys" get State /value
23:21:17 DEBUG| Sending command: wmic path win32_pnpsigneddriver where (DeviceName like 'VirtIO FS Device') get DriverVersion /format:list
23:21:23 DEBUG| Sending command: echo %errorlevel%
23:21:23 DEBUG| Destroying VM avocado-vt-vm1 (PID 124910)

**Pull request merged**
