### PR TITLE
qemu.tests.boot_order_check: Update boot_order_check config

### PR DESCRIPTION
**Pull request by sitoliu**
Del the unmatched sentences for status checking, update to matched ones. 

ID: 1447594

Signed-off-by: Sitong Liu <siliu@redhat.com>

### CODE REVIEW

**Comment by sitoliu** [comment]
smp_2.8192m.repeat1.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.RHEL.7.4.x86_64.io-github-autotest-qemu.boot_order_check.bootorder0: PASS (393.40 s)
smp_2.8192m.repeat1.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.RHEL.7.4.x86_64.io-github-autotest-qemu.boot_order_check.bootorder1: PASS (390.56 s)
smp_2.8192m.repeat1.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.RHEL.7.4.x86_64.io-github-autotest-qemu.boot_order_check.bootorder2: PASS (376.34 s)

**Comment by CongLi** [comment]
How about other guests/hosts?

**Comment by yanan-fu** [comment]
Check the output of seabios log: 
----------
Press ESC for boot menu.

Booting from ROM...
iPXE (PCI 00:04.0) starting execution...ok
iPXE initialising devices...ok
iPXE 1.0.0+ (4e85b27) -- Open Source Network Boot Firmware -- http://ipxe.org
Features: DNS HTTP iSCSI TFTP AoE ELF MBOOT PXE bzImage Menu PXEXT
Press Ctrl-B for the iPXE command line..^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^Hnet0: 9a:d5:d6:d7:d8:d9 using virtio-net on 0000:00:04.0 (open)
  [Link:up, TX:0 TXE:0 RX:0 RXE:0]
Configuring (net0 9a:d5:d6:d7:d8:d9)................................................................... **No configuration methods
succeeded** (http://ipxe.org/040ee119)
No more network devices
Press Ctrl-B for the iPXE command line..^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^HBooting from ROM...
iPXE (PCI 00:05.0) starting execution...ok
----------


LGTM
Acked-by: Yanan Fu yfu@redhat.com

**Comment by CongLi** [comment]
Need consider backward compatibility.

**Comment by yanan-fu** [comment]
@CongLi  I think this is related to seabios version only, has nothing to do with guest. 

Agree with your advise,  we only test this patch with rhel7.4 host now, and will test with rhel 6.9 host later.
thanks you very much!

**Comment by aliang123** [comment]
Considering the compatibility of seabios versions, "No more network devices" will be better than "No configuration methods succeeded" as ipxe_boot_fail_info.

**Comment by yanan-fu** [comment]
@aliang123  agree, Siliu get same conclusion after test with rhel6 host. She will update details later, thanks !

**Comment by sitoliu** [comment]
The seabios result of RHEL 6.9:

Press ESC or F12 for boot menu.

Booting from ROM...
gPXE (PCI 00:05.0) starting execution
ggPXE initialising devices...



ggPXE 0.9.7 -- Open Source Boot Firmware -- http://etherboot.org
FFeatures: HTTP DNS TFTP AoE iSCSI bzImage COMBOOT ELF Multiboot PXE PXEXT

PPress Ctrl-B for the gPXE command line...                                          nnet0: 9a:85:86:87:88:89 on PCI00:05.0 (open)
   [Link:up, TX:0 TXE:0 RX:0 RXE:0]
WWaiting for link-up on net0... ok
DDHCP (net0 9a:85:86:87:88:89)............................................................... **Connection timed out**(0x4c106035)
N**No more network devices**

PPress Ctrl-B for the gPXE command line...                                          Booting from Hard Disk...
Boot failed: not a bootable disk

Booting from ROM...
gPXE (PCI 00:06.0) starting execution
ggPXE initialising devices...

**Comment by sitoliu** [comment]
Thanks @aliang123  @yanan-fu, I agree with you that "No more network devices" will be better.

**Comment by sitoliu** [comment]
@yanan-fu @CongLi @aliang123. Patch has updated. Could you please review it again? Thanks so much.

Result:
RHEL 6.9:
smp_8.16384m.repeat1.Host_RHEL.m6.u9.qcow2.virtio_scsi.up.virtio_net.RHEL.6.9.x86_64.io-github-autotest-qemu.boot_order_check.bootorder1: PASS (396.81 s)

RHEL 7.4:
smp_2.8192m.repeat1.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.RHEL.7.4.x86_64.io-github-autotest-qemu.boot_order_check.bootorder1: PASS (393.25 s)

**Comment by CongLi** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by yanan-fu** [comment]
Acked-by: Yanan Fu yfu@redhat.com

@CongLi  could you help merge it, thank you so much !

**Comment by aliang123** [comment]
Acked-by: Aihua Liang <aliang@redhat.com>

**Comment by CongLi** [comment]
Thanks @sitoliu @yanan-fu @aliang123 .

**Pull request merged**
