### PR TITLE
Add QSD object option test

### PR DESCRIPTION
**Pull request by qingwangrh**
ID:2124449
Signed-off-by: qingwangrh <qinwang@redhat.com>

### CODE REVIEW

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=qsd_object_check --guestname=RHEL.9.0.0 --machines=q35 --firmware=default_bios --driveformat=virtio_blk --clone=no --debug
(1/1) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qsd_object_check.q35: STARTED
 (1/1) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qsd_object_check.q35: PASS (6.32 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by qingwangrh** [comment]
@YongxueHong @zhenyzha Please help to review ,thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by zhenyzha** [comment]
```
 (1/2) Host_RHEL.m9.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.aarch64.io-github-autotest-qemu.qsd_object_check.arm64-pci: PASS (8.18 s)
 (2/2) Host_RHEL.m9.u2.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.2.0.aarch64.io-github-autotest-qemu.qsd_object_check.arm64-pci: PASS (8.10 s)
```

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Review by zhenyzha — APPROVED** [review]

**Comment by XueqiangWei** [comment]
@YongxueHong If you have no more question, please help merge it. Many thanks.

**Pull request merged**
