### PR TITLE
insert_media: New case that inserts media in blockdev mode

### PR DESCRIPTION
**Pull request by YongxueHong**
New a case that inserts a media in the blockdev mode.

ID: 1822053
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by YongxueHong** [comment]
python3 ConfigTest.py --clone=no --nrepeat=1 --platform=x86_64 --guestname=RHEL.8.3.0 --testcase=insert_media --driveformat=virtio_scsi --machine=q35

` (1/1) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.insert_media.q35: PASS (39.48 s)`

**Comment by YongxueHong** [comment]
Hi, @qingwangrh  @zhenyzha  please me to review, thanks.

**Comment by zhenyzha** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.ppc64le.io-github-autotest-qemu.insert_media: PASS (43.46 s)
 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.insert_media: PASS (43.75 s)

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Comment by qingwangrh** [comment]
python ConfigTest.py  --testcase=insert_media --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=RHEL.8.3.0 --driveformat=virtio_scsi --nicmodel=virtio_net --imageformat=qcow2 --machines=q35 --customsparams="image_aio=native\nqemu_force_use_drive_expression = no" --clone=no

(1/1) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.insert_media.q35: PASS (33.34 s)

LGTM

**Pull request merged**
