### PR TITLE
Add support for vlan on s390x

### PR DESCRIPTION
**Pull request by fbq815**
Virtual-network: add support for vlan with "driver_verifier" on s390x

ID: 1987282

Signed-off-by: Boqiao Fu <bfu@redhat.com>

### CODE REVIEW

**Comment by fbq815** [comment]
Test result:
 (2/3) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.vlan.s390-virtio: PASS (655.21 s)
 (3/3) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.vlan.vlan_scalability_test.s390-virtio: PASS (2508.51 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2021-07-29T05.36-590e51e/results.html
JOB TIME   : 3345.62 s

**Comment by fbq815** [comment]
@PaulYuuu @ngu-niny  please help me review this patch

**Comment by PaulYuuu** [comment]
Only Windows guests need to verify the `netkvm` driver.

**Comment by fbq815** [comment]
> Only Windows guests need to verify the `netkvm` driver.
The code has been changed if I don't add netkvm, I could not run this case anymore

**Review by PaulYuuu — CHANGES_REQUESTED** [review]
`driver_verifier` setting in the cfg is right, it should only be under `Windows` part.
The problem is that the logic in py is wrong.

**Comment by fbq815** [comment]
Test result:
<testsuite errors="0" failures="0" name="job-2021-08-06T02.37-378b955" skipped="0" tests="2" time="3171.956" timestamp="2021-08-06T03:30:10.310990">
<testcase classname="VirtTest" name="1-Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.vlan.s390-virtio" time="657.906"/>
<testcase classname="VirtTest" name="2-Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.vlan.vlan_scalability_test.s390-virtio" time="2514.050"/>
</testsuite>

@PaulYuuu @ngu-niny  please help me review this patch

**Review by PaulYuuu — APPROVED** [review]

**Comment by ngu-niny** [comment]
LGTM

**Pull request merged**
