### PR TITLE
Add pvpanic function test after install driver via installer

### PR DESCRIPTION
**Pull request by leidwang**
ID:2114649
Signed-off-by: Leidong Wang <leidwang@redhat.com>

### CODE REVIEW

**Comment by leidwang** [comment]
(1/1) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.win_virtio_driver_install_by_installer.driver_install.single_driver.with_pvpanic.q35: PASS (361.54 s)

**Comment by leidwang** [comment]
Hi @vivianQizhu Could you help to review this patch?Thanks a lot!

**Review by vivianQizhu — DISMISSED** [review]

**Comment by vivianQizhu** [comment]
Typo in commit title: s/Add pvpanic function test after installer driver via installer/Add pvpanic function test after install driver via installer/g

**Comment by leidwang** [comment]
> Typo in commit title: s/Add pvpanic function test after installer driver via installer/Add pvpanic function test after install driver via installer/g

Yes,updated the commit title.Thanks!

**Review by vivianQizhu — APPROVED** [review]

**Pull request merged**
