### PR TITLE
CPUID test code updates

### PR DESCRIPTION
**Pull request by ehabkost**
This includes:
* QOM-based testing to allow us to check CPU models that can't run in the host
* Whitelisting of known issues in qemu_cpu.cfg
* New CPUID dumps from multiple hosts/versions

### CODE REVIEW

**Comment by lmr** [comment]
I was trying this out on my laptop, I've got 7 `ERRORs` from the 354 tests executed. The errors are along these lines:

    18:05:28 ERROR| VMCreateError: VM creation command failed:    "MALLOC_PERTURB_=1  /bin/qemu-kvm -S  -name 'avocado-vt-vm1' -machine pc-1.3  -nodefaults  -vga std  -chardev socket,id=hmp_id_hmp1,path=/tmp/monitor-hmp1-20150921-112121-bCLFyaHl,server,nowait -mon chardev=hmp_id_hmp1,mode=readline  -chardev socket,id=hmp_id_catch_monitor,path=/tmp/monitor-catch_monitor-20150921-112121-bCLFyaHl,server,nowait -mon chardev=hmp_id_catch_monitor,mode=readline -device pvpanic,ioport=0x505,id=idbgCMEk  -chardev socket,id=serial_id_serial0,path=/tmp/serial-serial0-20150921-112121-bCLFyaHl,server,nowait -device isa-serial,chardev=serial_id_serial0  -chardev socket,id=seabioslog_id_20150921-112121-bCLFyaHl,path=/tmp/seabios-20150921-112121-bCLFyaHl,server,nowait -device isa-debugcon,chardev=seabioslog_id_20150921-112121-bCLFyaHl,iobase=0x402  -m 1024  -smp 1,maxcpus=1,cores=1,threads=1,sockets=1  -cpu 'Haswell',enforce  -kernel '/home/lmr/avocado/data/avocado-vt/test-providers.d/downloads/io-github-ehabkost-qemu/qemu/deps/cpuid/src/cpuid_dump_kernel.bin'  -vnc :0  -rtc base=utc,clock=host  -boot order=cdn,once=c,menu=off,strict=off -enable-kvm"    (status: 1,    output: "warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]\nwarning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]\nqemu-system-x86_64: Host doesn't support requested features")

**Comment by lmr** [comment]
And another 8 failures along the lines:

    18:12:47 ERROR| TestFail: Guest vendor [GenuineIntel], doesn't match required vendor [AuthenticAMD] for CPU [Opteron_G1]

**Comment by lmr** [comment]
If you want to take a look at the full results, please download https://lmr.fedorapeople.org/avocado-job-logs/job-2015-09-22T18.01-d73b918.tar.gz

**Comment by lmr** [comment]
Oh, I'm using a fairly up to date Fedora 22 (although I know there are a few package updates pending, some of them with qemu updates), qemu 2.3.1

**Comment by lmr** [comment]
Nope, my mistake, I did update before running the tests: `qemu-kvm-2.3.1-3.fc22.x86_64`

**Comment by ehabkost** [comment]
The vendor mismatch errors are because of this:

        #KNOWN BUG: RHEL-7.0 qemu-kvm doesn't show the -no-kvm option on -help,
        # so virt-test doesn't use the option and disable_kvm=yes doesn't work
        no Host_RHEL.7

This line needs to be updated to:

        no Host_RHEL.7, qemu_flavor_unknown

to make sure we don't try to run the nokvm tests if we don't know if `disable_kvm` really works.

I will add a new commit to the pull request fixing that issue.

I will take a look at the `VMCreationError` errors, now.

**Comment by lmr** [comment]
There's a slight style problem captured by pylint:

    $ inspekt style
    /home/travis/build/autotest/tp-qemu/qemu/tests/cpuid.py:101:80: E227 missing whitespace around bitwise or shift operator
    /home/travis/build/autotest/tp-qemu/qemu/tests/cpuid.py:202:24: E127 12
    /home/travis/build/autotest/tp-qemu/qemu/tests/cpuid.py:205:24: E127 12
    /home/travis/build/autotest/tp-qemu/qemu/tests/cpuid.py:208:24: E127 12
    PEP8 check fail: /home/travis/build/autotest/tp-qemu/qemu/tests/cpuid.py

**Comment by ehabkost** [comment]
I need help interpreting the results.

About:

    /home/travis/build/autotest/tp-qemu/qemu/tests/cpuid.py:101:80: E227 missing whitespace around bitwise or shift operator

I don't know where's the error:

      98                  dbg("invalid cpuid dump line: %r", l)
      99                  return None
     100              in_eax = int(m.group(1), 16)
     101              in_ecx = int(m.group(2), 16)
     102              result[in_eax, in_ecx, 'eax'] = int(m.group(3), 16)
     103              result[in_eax, in_ecx, 'ebx'] = int(m.group(4), 16)
     104              result[in_eax, in_ecx, 'ecx'] = int(m.group(5), 16)

About:

    /home/travis/build/autotest/tp-qemu/qemu/tests/cpuid.py:202:24: E127 12
    /home/travis/build/autotest/tp-qemu/qemu/tests/cpuid.py:205:24: E127 12
    /home/travis/build/autotest/tp-qemu/qemu/tests/cpuid.py:208:24: E127 12

I don't know what "E127 12" means.

**Comment by lmr** [comment]
Here are the fixes:

    diff --git a/qemu/tests/cpuid.py b/qemu/tests/cpuid.py
    index b12fd7c..99d969b 100644
    --- a/qemu/tests/cpuid.py
    +++ b/qemu/tests/cpuid.py
    @@ -98,7 +98,7 @@ def run(test, params, env):
             dbg("parsing cpuid dump: %r", output)
             cpuid_re = re.compile(
                 "^ *(0x[0-9a-f]+) +0x([0-9a-f]+): +eax=0x([0-9a-f]+) ebx=0x([0-9a-f]+) ecx=0x([0-9a-f]+) edx=0x([0-9a-f]+)$")
    -        output_match = re.search('(==START TEST==.*==END TEST==)', output, re.M|re.DOTALL)
    +        output_match = re.search('(==START TEST==.*==END TEST==)', output, re.M | re.DOTALL)
             if output_match is None:
                 dbg("cpuid dump doesn't follow expected pattern")
                 return None
    @@ -199,13 +199,13 @@ def run(test, params, env):
             dst = []
             map(lambda i:
                 dst.append((chr(cpuid_dump[idx, 0, 'ebx'] >> (8 * i) & 0xff))),
    -                       range(0, 4))
    +            range(0, 4))
             map(lambda i:
                 dst.append((chr(cpuid_dump[idx, 0, 'edx'] >> (8 * i) & 0xff))),
    -                       range(0, 4))
    +            range(0, 4))
             map(lambda i:
                 dst.append((chr(cpuid_dump[idx, 0, 'ecx'] >> (8 * i) & 0xff))),
    -                       range(0, 4))
    +            range(0, 4))
             return ''.join(dst)
     
         def default_vendor(self):

**Comment by lmr** [comment]
Oh, I forgot to mention that there are easy ways to catch this on tp-qemu now:

    $ yum install inspektor
    $ inspekt lint; inspekt style

`inspektor` comes from the same yum repo that holds `avocado` and `avocado-plugins-vt`.

**Comment by ehabkost** [comment]
I have made a non-fast-forward push to the branch, rebased to latest master, with changes in:
* 8e3a0d1593299e2e300ae0ebe80aaa5a4a8acd12 cpuid: Accept extra data on CPUID output
* 1126801556141d454b49299f201cef0f1cf1ca3e cpuid: Use (eax,ecx,reg) as index for parsed CPUID data
* 9d30fe445c58ee398564359ed3f4eb74d71455b3 cpuid: Don't try to run the nokvm tests if host system is unknown

The other commits were rebased cleanly with no additional changes.

**Comment by lmr** [comment]
Great!

**Comment by lmr** [comment]
Thank you very much, @ehabkost !

**Pull request merged**
