### PR TITLE
guest_test: Use nmcli to control network on rhel8

### PR DESCRIPTION
**Pull request by yanan-fu**
1. guest_test.isa_serial_operations: don't need to reboot before test
2. Remove existing "dst_rsc_path" for both linux and windows
3. Use 'dhclient -r' instead of kill and restart on old version
4. For RHEL8 and later, use nmcli to control network

id: 1781468
Signed-off-by: Yanan Fu <yfu@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
@nanliu-r @vivianQizhu  could you help review, thanks a lot!

**Comment by yanan-fu** [comment]
> please used " dhclient -r " instead kill and restart step.

@xutia thanks, make sense, updated. 
However, i also want to say,  this is the old design for RHEL7 and before, not related with the root cause of bz 1781468, the key step is use nmcli on rhel8.

**Comment by yanan-fu** [comment]
Test for 50 times:
```
python3 ConfigTest.py --testcase=guest_test.isa_serial_operations --guestname=RHEL.8.2.0 --clone=no --nrepeat=50
....
....
RESULTS    : PASS 50 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 6365.28 s
JOB HTML   : /root/avocado/job-results/job-2019-12-22T21.49-4a1cf2c/results.html
```

**Comment by nanliu-r** [comment]
looks good for me and test pass, thanks, ACK.

**Pull request merged**
