### PR TITLE
for "aexpect", make it work under both autotest-framework and avocado-framework

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>
ID: 1415457

### CODE REVIEW

**Comment by suqinhuang** [comment]
suggest to update the summary to
make aecpect module works for both ...

others good ok to me

**Comment by XueqiangWei** [comment]
@suqinhuang updated, thank you

**Comment by xutian** [comment]
@XueqiangWei  please fix typo in commit summary.

**Comment by XueqiangWei** [comment]
@xutian updated, many thanks.

**Pull request merged**
