### PR TITLE
perf cases: stop and flush firewalld, iptables and nftables

### PR DESCRIPTION
**Pull request by quanwenli**
Signed-off-by: Wenli Quan <wquan@redhat.com>
 
id: 2601

### CODE REVIEW

**Comment by quanwenli** [comment]
@PaulYuuu could you help to review it , thanks a lot.

**Review by PaulYuuu — COMMENTED** [review]
I think the best solution is to detect the backend used by firewalld, and then flush rules based on the result. Otherwise, if new backend is introduced in the future, the stop command will longer and longer.

```bash
$ sudo grep "^FirewallBackend" /etc/firewalld/firewalld.conf
FirewallBackend=nftables
```

Not only for these 4 cfg files, but also many cases need to be changed.

**Comment by quanwenli** [comment]
> I think the best solution is to detect the backend used by firewalld, and then flush rules based on the result. Otherwise, if new backend is introduced in the future, the stop command will longer and longer.
> 
> ```shell
> $ sudo grep "^FirewallBackend" /etc/firewalld/firewalld.conf
> FirewallBackend=nftables
> ```
> 
> Not only for these 4 cfg files, but also many cases need to be changed.

Firewalld only serves as a frontend management tools, some iptables or nftables rules might be set up directly in scripts or settings. disabling firewalld might not change these rules. 

Like FirewallBackend=nftables in firewalld.conf, but iptables command is using directly in vt framework, so Firewall remains active.

**Comment by PaulYuuu** [comment]
> > I think the best solution is to detect the backend used by firewalld, and then flush rules based on the result. Otherwise, if new backend is introduced in the future, the stop command will longer and longer.
> > ```shell
> > $ sudo grep "^FirewallBackend" /etc/firewalld/firewalld.conf
> > FirewallBackend=nftables
> > ```
> >   
> > Not only for these 4 cfg files, but also many cases need to be changed.
> 
> Firewalld only serves as a frontend management tools, some iptables or nftables rules might be set up directly in scripts or settings. disabling firewalld might not change these rules.
> 
> Like FirewallBackend=nftables in firewalld.conf, but iptables command is using directly in vt framework, so Firewall remains active.

I knew it, disabling firewalld will only disable rules managed by itself. However, disabling iptables and nftables will disable all rules even if those rules are created by others like libvirt, I don't think this is good. For test cases, it should manage rules in the step and fallback at the end. At the beginning, accept all traffic and reset to default when the test is finished.

**Comment by quanwenli** [comment]
> > > I think the best solution is to detect the backend used by firewalld, and then flush rules based on the result. Otherwise, if new backend is introduced in the future, the stop command will longer and longer.
> > > ```shell
> > > $ sudo grep "^FirewallBackend" /etc/firewalld/firewalld.conf
> > > FirewallBackend=nftables
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Not only for these 4 cfg files, but also many cases need to be changed.
> > 
> > 
> > Firewalld only serves as a frontend management tools, some iptables or nftables rules might be set up directly in scripts or settings. disabling firewalld might not change these rules.
> > Like FirewallBackend=nftables in firewalld.conf,THe  but iptables command is using directly in vt framework, so Firewall remains active.
> 
> I knew it, disabling firewalld will only disable rules managed by itself. However, disabling iptables and nftables will disable all rules even if those rules are created by others like libvirt, I don't think this is good. For test cases, it should manage rules in the step and fallback at the end. At the beginning, accept all traffic and reset to default when the test is finished. Mixing processing rules with different tools is hard to manage.

**Comment by quanwenli** [comment]
> > > > I think the best solution is to detect the backend used by firewalld, and then flush rules based on the result. Otherwise, if new backend is introduced in the future, the stop command will longer and longer.
> > > > ```shell
> > > > $ sudo grep "^FirewallBackend" /etc/firewalld/firewalld.conf
> > > > FirewallBackend=nftables
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Not only for these 4 cfg files, but also many cases need to be changed.
> > > 
> > > 
> > > Firewalld only serves as a frontend management tools, some iptables or nftables rules might be set up directly in scripts or settings. disabling firewalld might not change these rules.
> > > Like FirewallBackend=nftables in firewalld.conf,THe  but iptables command is using directly in vt framework, so Firewall remains active.
> > 
> > 
> > I knew it, disabling firewalld will only disable rules managed by itself. However, disabling iptables and nftables will disable all rules even if those rules are created by others like libvirt, I don't think this is good. For test cases, it should manage rules in the step and fallback at the end. At the beginning, accept all traffic and reset to default when the test is finished. Mixing processing rules with different tools is hard to manage.

For this pull request, they are all for perf cases, we need to disable all the "firewalls".

**Comment by quanwenli** [comment]
@luckyh could you help review it. thanks a lot.

**Comment by fbq815** [comment]
netperf cases could PASS on s390x with 10 without attaching this PR, and I agree we need more modification include in this PR, such as nfs etc.

**Comment by quanwenli** [comment]
> netperf cases could PASS on s390x with 10 without attaching this PR, and I agree we need more modification include in this PR, such as nfs etc.

This only affects the perf test cases：netperf, netperf_udp_perf, pktgen_perf, and pktgen_burst_test，I’ve reviewed your test results, and they do not include the tests mentioned in my pull request.

**Comment by quanwenli** [comment]
I have updated the git summary to make it clearer.

**Comment by luckyh** [comment]
I'd agree with @PaulYuuu that we definitely need a better way to disable all the firewall rules for these tests. However, the key point is if we would like to do that with this one or it would be some future improvement and now get things work with the workaround like this.

@PaulYuuu @quanwenli let me know your opinion, thanks.

**Comment by quanwenli** [comment]
> I'd agree with @PaulYuuu that we definitely need a better way to disable all the firewall rules for these tests. However, the key point is if we would like to do that with this one or it would be some future improvement and now get things work with the workaround like this.
> 
> @PaulYuuu @quanwenli let me know your opinion, thanks.

 I agree with getting things to work with the workaround like this.

**Comment by PaulYuuu** [comment]
> I'd agree with @PaulYuuu that we definitely need a better way to disable all the firewall rules for these tests. However, the key point is if we would like to do that with this one or it would be some future improvement and now get things work with the workaround like this.
> 
> @PaulYuuu @quanwenli let me know your opinion, thanks.

It's okay to add a workaround this time, but should add a FIXME comment to track.

**Comment by quanwenli** [comment]
> > I'd agree with @PaulYuuu that we definitely need a better way to disable all the firewall rules for these tests. However, the key point is if we would like to do that with this one or it would be some future improvement and now get things work with the workaround like this.
> > @PaulYuuu @quanwenli let me know your opinion, thanks.
> 
> It's okay to add a workaround this time, but should add a FIXME comment to track.

I have updated. please help review. thanks a lot.

**Review by PaulYuuu — APPROVED** [review]

**Pull request merged**
