### PR TITLE
block_devices_plug: Fix the order of hotplugging blockdev nodes

### PR DESCRIPTION
**Pull request by YongxueHong**
Failed to hotplug the format node since need to hotplug a protocol
node before it, so modify the order of hotplugging blockdev nodes.

ID: 1788350
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by YongxueHong** [comment]
@lolyu  @qingwangrh  @kimi1978wy @zhenyzha @peixiu 
Please help me to review when you are free, thanks.

**Comment by YongxueHong** [comment]
Suggest: 
You could run it through cases: `plug_cdrom,hotplug_unplug_during_io_repeat,unplug_block_during_io_reboot`

**Comment by YongxueHong** [comment]
BTW, please help me to review it in the drive mode, thanks.

**Comment by zhenyzha** [comment]
(3/7) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.ppc64le.io-github-autotest-qemu.plug_cdrom.with_hotplug.reboot_vm: ERROR: Shell command failed: 'mount /dev/sr0 /mnt && ls /mnt && umount /mnt'    (status: 32,    output: 'mount: special device /dev/sr0 does not exist\n') (87.78 s)
 (4/7) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.ppc64le.io-github-autotest-qemu.plug_cdrom.with_unplug.reboot_vm: PASS (146.51 s)
 (5/7) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.ppc64le.io-github-autotest-qemu.hotplug_unplug_during_io_repeat: ERROR: unplug--> Actual: 0 disks. Expected: 1 disks. (504.59 s)

**Comment by YongxueHong** [comment]
BTW, please help me to review it in the drive mode and blockdev mode, thanks.

**Comment by YongxueHong** [comment]
> (3/7) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.ppc64le.io-github-autotest-qemu.plug_cdrom.with_hotplug.reboot_vm: ERROR: Shell command failed: 'mount /dev/sr0 /mnt && ls /mnt && umount /mnt' (status: 32, output: 'mount: special device /dev/sr0 does not exist\n') (87.78 s)
> (4/7) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.ppc64le.io-github-autotest-qemu.plug_cdrom.with_unplug.reboot_vm: PASS (146.51 s)
> (5/7) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.ppc64le.io-github-autotest-qemu.hotplug_unplug_during_io_repeat: ERROR: unplug--> Actual: 0 disks. Expected: 1 disks. (504.59 s)

@zhenyzha , I checked the log, it's another issue, not involved by this patch.
And please help me to review it in both drive and blockdev mode. thanks.

**Comment by zhenyzha** [comment]
-blockdev mode: 
(1/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.hotplug_unplug_during_io_repeat: PASS (4801.43 s)
 (2/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.hotplug_unplug_during_io_repeat.with_scsi_hba: PASS (5447.49 s)
 (3/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.unplug_block_during_io_reboot: PASS (385.57 s)
 (4/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.plug_cdrom.with_hotplug.reboot_vm: PASS (234.52 s)
 (5/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.plug_cdrom.with_unplug.reboot_vm: PASS (244.86 s)

 -drive mode:
 (1/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.unplug_block_during_io_reboot: PASS (326.44 s)
 (2/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.plug_cdrom.with_hotplug.reboot_vm: PASS (200.97 s)
 (3/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.plug_cdrom.with_unplug.reboot_vm: PASS (200.31 s)
 (4/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.hotplug_unplug_during_io_repeat: PASS (4811.72 s)
 (5/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.hotplug_unplug_during_io_repeat.with_scsi_hba: PASS (5453.44 s)

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Comment by qingwangrh** [comment]
python3 ConfigTest.py  --clone=no --platform=x86_64 --customsparams="qemu_force_use_drive_expression = no" --guestname=RHEL.8.2.0 --testcase=plug_cdrom,hotplug_unplug_during_io_repeat,unplug_block_during_io_reboot --driveformat=virtio_scsi,virtio_blk --machine=q35,i440fx

'01-Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.unplug_block_during_io_reboot' Finshed 2020-01-15 05:27:17 2020-01-15 05:29:56 PASS 159.5154
'02-Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.unplug_block_during_io_reboot.q35' Finshed 2020-01-15 05:29:56 2020-01-15 05:32:41 PASS 164.428182
'03-Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.hotplug_unplug_during_io_repeat' Finshed 2020-01-15 05:32:41 2020-01-15 06:58:27 PASS 5146.166674
'04-Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.hotplug_unplug_during_io_repeat.q35' Finshed 2020-01-15 06:58:27 2020-01-15 08:41:03 PASS 6155.925998
'05-Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.plug_cdrom.with_hotplug.reboot_vm' Finshed 2020-01-15 08:41:03 2020-01-15 08:42:46 PASS 102.813007
'06-Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.plug_cdrom.with_hotplug.reboot_vm.q35' Finshed 2020-01-15 08:42:46 2020-01-15 08:44:29 PASS 102.793836
'07-Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.plug_cdrom.with_unplug.reboot_vm' Finshed 2020-01-15 08:44:29 2020-01-15 08:46:08 PASS 99.119592
'08-Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.plug_cdrom.with_unplug.reboot_vm.q35' Finshed 2020-01-15 08:46:08 2020-01-15 08:47:50 PASS 101.739046
'09-Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.unplug_block_during_io_reboot' Finshed 2020-01-15 08:47:50 2020-01-15 08:50:28 PASS 158.355387
'10-Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.unplug_block_during_io_reboot.q35' Finshed 2020-01-15 08:50:28 2020-01-15 08:53:08 PASS 159.868682
'11-Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.hotplug_unplug_during_io_repeat' Finshed 2020-01-15 08:53:08 2020-01-15 10:18:41 PASS 5132.500195
'12-Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.hotplug_unplug_during_io_repeat.q35' Finshed 2020-01-15 10:18:41 2020-01-15 11:44:39 PASS 5158.09466
'13-Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.hotplug_unplug_during_io_repeat.with_scsi_hba' Finshed 2020-01-15 11:44:39 2020-01-15 13:12:27 PASS 5267.962789
'14-Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.hotplug_unplug_during_io_repeat.with_scsi_hba.q35' Finshed 2020-01-15 13:12:27 2020-01-15 14:56:38 PASS 6251.148788

LGTM

**Comment by YongxueHong** [comment]
@lolyu  pls help me to review, thanks.

**Comment by peixiu** [comment]
for window blockdev mode scsi disk hotplug will hit this product bug:
Bug 1708490 - Hotplug a SCSI disk via blockdev hits bsod in windows guest
so cannot test this patch's blockdev related codes for scsi on windows now.

and currently, on windows guest, hotplug a scsi-hd/ scsi-cd to a existed virtio-scsi-pci bus will trigger upper bug, but can be passed when hotplug a scsi-hd/scsi-cd to a new virtio-scsi-pci bus, can we set a workaround like change to hotplug a scsi-hd/scsi-cd to a new virtio-scsi-pci bus for all block_hotplug related cases? because all block_hotplug related cases failed as the upper bug, we cannot use automation to run these tests, manually will spent many times.

Thanks a lot~
Peixiu

**Comment by YongxueHong** [comment]
> for window blockdev mode scsi disk hotplug will hit this product bug:
> Bug 1708490 - Hotplug a SCSI disk via blockdev hits bsod in windows guest
> so cannot test this patch's blockdev related codes for scsi on windows now.
> 
> and currently, on windows guest, hotplug a scsi-hd/ scsi-cd to a existed virtio-scsi-pci bus will trigger upper bug, but can be passed when hotplug a scsi-hd/scsi-cd to a new virtio-scsi-pci bus, can we set a workaround like change to hotplug a scsi-hd/scsi-cd to a new virtio-scsi-pci bus for all block_hotplug related cases? because all block_hotplug related cases failed as the upper bug, we cannot use automation to run these tests, manually will spent many times.
> 
> Thanks a lot~
> Peixiu

Ok, I suggest you could file a new auto RFE bug, we could merge it since this patch just for fixing the order of hotplugging blockdev nodes and  your requirement we could workaround it on the case level. 
how about my advice?

**Comment by peixiu** [comment]
> > for window blockdev mode scsi disk hotplug will hit this product bug:
> > Bug 1708490 - Hotplug a SCSI disk via blockdev hits bsod in windows guest
> > so cannot test this patch's blockdev related codes for scsi on windows now.
> > and currently, on windows guest, hotplug a scsi-hd/ scsi-cd to a existed virtio-scsi-pci bus will trigger upper bug, but can be passed when hotplug a scsi-hd/scsi-cd to a new virtio-scsi-pci bus, can we set a workaround like change to hotplug a scsi-hd/scsi-cd to a new virtio-scsi-pci bus for all block_hotplug related cases? because all block_hotplug related cases failed as the upper bug, we cannot use automation to run these tests, manually will spent many times.
> > Thanks a lot~
> > Peixiu
> 
> Ok, I suggest you could file a new auto RFE bug, we could merge it since this patch just for fixing the order of hotplugging blockdev nodes and your requirement we could workaround it on the case level.
> how about my advice?

about this patch, that's ok for me, for file new RFE auto bug, I also need to discuss with scsi feature owner, it's should not a RFE bug, because the case will not be changed, and we also need re-back the code when the product bug is fixed.
you can merge this patch if others all acked, i also think the code is ok, just I cannot run these jobs passed due to product bug.

**Comment by YongxueHong** [comment]
> changed

Okay. will merge it firstly.

**Pull request merged**
