### PR TITLE
unsafe_rebase_to_none_existing_backing_file: fix rebase

### PR DESCRIPTION
**Pull request by lolyu**
Update `rebase` to adjust the way to specify rebase target.

Signed-off-by: lolyu <lolyu@redhat.com>

### CODE REVIEW

**Comment by lolyu** [comment]
@hellohellenmao @PaulYuuu Please take a review.
thx.

**Comment by lolyu** [comment]
```
 (1/2) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.io-github-autotest-qemu.unsafe_rebase_to_none_existing_backing_file.compat_0.10: PASS (2.37 s)
 (2/2) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.io-github-autotest-qemu.unsafe_rebase_to_none_existing_backing_file.compat_default: PASS (2.25 s)
```

**Comment by PaulYuuu** [comment]
Acked-by: Yihuang Yu <yihyu@redhat.com>

**Comment by lolyu** [comment]
depends on #https://github.com/avocado-framework/avocado-vt/pull/2288

**Pull request merged**
