### PR TITLE
qemu.tests.cfg: Update the boot_menu_hint config

### PR DESCRIPTION
**Pull request by spcui**
For RHEL6 host, boot menu hint message changed.

ID: 1224039

### CODE REVIEW

**Comment by CongSmile** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by suqinhuang** [comment]
Acked-by: Suqin Huang

**Comment by xutian** [comment]
Acked,   I think we should print what actual  catch  when raise catch mismatch expect, so that tester can judge is necessary  to report qemu bug or just a autotest bug when failed. so please update your raise message to.

**Comment by spcui** [comment]
@xutian updated now, could you review again?

**Comment by xutian** [comment]
Acked-by:  Xu Tian <xutian@redhat.com>

**Pull request merged**
