### PR TITLE
blockdev_stream_to_invalid_node:Stream to an invalid node of the chain

### PR DESCRIPTION
**Pull request by aliang123**
Stream to an invalid node of the chain

Signed-off-by: Aihua Liang <aliang@redhat.com>
id:1989000

### CODE REVIEW

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.blockdev_stream_to_invalid_node.q35: PASS (40.04 s)

**Comment by aliang123** [comment]
@zhencliu @ngu-niny, please help to review, thanks.

**Comment by ngu-niny** [comment]
2-Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.blockdev_stream_to_invalid_node Finshed 2021-08-04 23:36:45 2021-08-04 23:38:25 PASS 100.397002
4-Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_stream_to_invalid_node Finshed 2021-08-04 23:40:13 2021-08-04 23:41:41 PASS 87.795501

Acked-by: Nini Gu <ngu@redhat.com>

**Comment by zhencliu** [comment]
LGTM

**Pull request merged**
