### PR TITLE
Expose data image with persistent bitmap via qemu-nbd

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1869202

### CODE REVIEW

**Comment by zhencliu** [comment]
hi @aliang123 , can you please help to review the patch, thanks.
it deps on https://github.com/avocado-framework/avocado-vt/pull/2712

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by aliang123** [comment]
FAIL 1-Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_xpt_bitmap.q35 -> TestFail: Failed to run map command: qemu-img: Could not open 'json:{"driver": "nbd", "server.type": "inet", "server.host": "dell-per440-10.lab.eng.pek2.redhat.com", "server.port": "10850", "x-dirty-bitmap": "qemu:dirty-bitmap:bitmap_data"}': requested x-dirty-bitmap qemu:dirty-bitmap:bitmap_data not found

Root case:
   no bitmap exposed, in your script:
    /usr/bin/qemu-nbd   -f qcow2 -t  -p 10850  --fork --pid-file /var/tmp/avocado_h9mtqskm/data_nbd_server-20200819-041211-O46H.pid  /var/lib/avocado/data/avocado-vt/data.qcow2   
     --> -B bitmap_data lacked in your expose cmd

 correct cmd example:
   qemu-nbd -t -p 9000 /home/data.qcow2 -B bitmap0

**Comment by zhencliu** [comment]
> FAIL 1-Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_xpt_bitmap.q35 -> TestFail: Failed to run map command: qemu-img: Could not open 'json:{"driver": "nbd", "server.type": "inet", "server.host": "dell-per440-10.lab.eng.pek2.redhat.com", "server.port": "10850", "x-dirty-bitmap": "qemu:dirty-bitmap:bitmap_data"}': requested x-dirty-bitmap qemu:dirty-bitmap:bitmap_data not found
> 
> Root case:
> no bitmap exposed, in your script:
> /usr/bin/qemu-nbd -f qcow2 -t -p 10850 --fork --pid-file /var/tmp/avocado_h9mtqskm/data_nbd_server-20200819-041211-O46H.pid /var/lib/avocado/data/avocado-vt/data.qcow2
> --> -B bitmap_data lacked in your expose cmd
> 
> correct cmd example:
> qemu-nbd -t -p 9000 /home/data.qcow2 -B bitmap0

Hi @aliang123 , sorry that I didn't tell you I have made VT code change for supporting this patch,  please pull the latest VT code from upstream, when you update VT code, you will get the right qemu-nbd command line and everything works fine.  Thank you.

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_xpt_bitmap.q35: PASS (47.18 s)


Acked-by: Aihua Liang <aliang@redhat.com>

**Comment by zhencliu** [comment]
hi @ngu-niny , can you please help to verify the patch on ppc? Thanks.

**Comment by ngu-niny** [comment]
Test PASS on ppc:

'1-Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_xpt_bitmap' Finshed 2020-08-20 07:38:30 2020-08-20 07:41:02 PASS 151.407259

Acked-by: Nini Gu <ngu@redhat.com>

**Comment by zhencliu** [comment]
Thanks all, hi @YongxueHong , can you please help to merge it, all acked, thanks.

**Pull request merged**
