### PR TITLE
Fix data plane on scsi_cd issue

### PR DESCRIPTION
**Pull request by qingwangrh**
ID:1793742
Signed-off-by: qingwangrh <qinwang@redhat.com>

### CODE REVIEW

**Comment by qingwangrh** [comment]
python3 ConfigTest.py --testcase=cdrom_block_size_check.q35 --guestname=RHEL.8.2.0,Win2019 --imageformat=qcow2 --driveformat=virtio_scsi --nicmodel=virtio_net --machines=q35 --platform=x86_64 --clone=no --iothread_scheme=rhv


(1/2) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.cdrom_block_size_check.q35: PASS (115.07 s)
 (2/2) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.cdrom_block_size_check.q35: PASS (135.02 s)

**Comment by qingwangrh** [comment]
@zhenyzha @YongxueHong Please help to review.

**Comment by YongxueHong** [comment]
Mabe the commit title changed to `Disable data plane for scsi_cd` is more clearly.

**Comment by zhenyzha** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.cdrom_block_size_check: PASS (172.20 s)

LGTM.Acked-by: Zhenyu Zhang zhenyzha@redhat.com

**Comment by qingwangrh** [comment]
> Mabe the commit title changed to `Disable data plane for scsi_cd` is more clearly and match your changed codes.

Updated

**Pull request merged**
