### PR TITLE
virtio_fs: add IO test after rebooting guest os

### PR DESCRIPTION
**Pull request by xiagao**
Add a checkpoint that doing io test after reboot guest os.

ID: 1310

### CODE REVIEW

**Comment by xiagao** [comment]
(1/1) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.with_reboot.q35: STARTED
 (1/1) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.with_reboot.q35: PASS (331.83 s)
 (1/1) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.with_reboot.q35: STARTED
 (1/1) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.with_reboot.q35: PASS (113.86 s)

--testcase=virtio_fs_share_data.default.default.with_cache.auto.default.with_reboot

**Comment by xiagao** [comment]
@nickzhq Could you help review this patch? Thanks.

**Comment by nickzhq** [comment]
> @nickzhq Could you help review this patch? Thanks.

Ack.

cc @zhencliu @YongxueHong

**Review by nickzhq — APPROVED** [review]

**Review by hereischen — APPROVED** [review]

**Comment by zhencliu** [comment]
LGTM

**Comment by xiagao** [comment]
@fbq815 @zhenyzha Could you have a check of this patch per multi-arch?

**Comment by zhenyzha** [comment]
LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

--testcase=virtio_fs_share_data..with_cache.auto..with_reboot

` (1/1) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.with_reboot.arm64-pci: PASS (117.53 s)`

**Review by zhenyzha — APPROVED** [review]

**Review by fbq815 — APPROVED** [review]
LGTM
 (1/1) Host_RHEL.m8.u10.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.with_reboot.s390-virtio: PASS (53.27 s)

**Review by YongxueHong — APPROVED** [review]
LGTM

**Pull request merged**
