### PR TITLE
Specify vga insert into pci(e).0 bus

### PR DESCRIPTION
**Pull request by JinLiul**
ID: 2213407
Signed-off-by: Jin Liu jinl@redhat.com

### CODE REVIEW

**Comment by JinLiul** [comment]
(1/2) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.guest_iommu_group.intel_iommu.q35: STARTED
 (1/2) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.guest_iommu_group.intel_iommu.q35: PASS (149.96 s)
 (2/2) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.guest_iommu_group.virtio_iommu.q35: STARTED
 (2/2) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.guest_iommu_group.virtio_iommu.q35: PASS (86.59 s)

**Comment by JinLiul** [comment]
@XueqiangWei @PaulYuuu Could you please help to review? Thanks.

**Comment by JinLiul** [comment]
Updated the commit message.

**Comment by XueqiangWei** [comment]
(1/2) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.guest_iommu_group.intel_iommu.q35: STARTED
 (1/2) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.guest_iommu_group.intel_iommu.q35: PASS (102.08 s)
 (2/2) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.guest_iommu_group.virtio_iommu.q35: STARTED
 (2/2) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.guest_iommu_group.virtio_iommu.q35: PASS (59.68 s)

**Comment by PaulYuuu** [comment]
@JinLiul Can you explain the reason for inserting to pci.0 instead of updating the pattern?

**Pull request closed without merging**
