### PR TITLE
virtio_serial: provide more accurate error info

### PR DESCRIPTION
**Pull request by vivianQizhu**
ID: 1931711
Signed-off-by: Qianqian Zhu <qizhu@redhat.com>

### CODE REVIEW

**Comment by vivianQizhu** [comment]
@6-dehan @nanliu-r Please help review, thanks.

**Review by hereischen — APPROVED** [review]

**Comment by nanliu-r** [comment]
Test PASS, thanks!
 python3 ConfigTest.py --guestname=RHEL.9.2.0 --clone=no --testcase=virtio_serial_file_transfer.default.unix_socket.boot_with_multiple_virtserialports,virtio_serial_file_transfer.default.pty.default --nrepeat=8

RESULTS    : PASS 32 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by nanliu-r** [comment]
ACK.

**Comment by vivianQizhu** [comment]
@6-dehan Please help test this without https://github.com/avocado-framework/avocado-vt/pull/3602 so it can really trigger the issue and check if it reports properer error.

**Comment by 6-dehan** [comment]
HI @vivianQizhu, this is what I got. it's not the proper error info that we expect.

(3/3) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.virtio_serial_file_transfer.unix_socket.boot_with_multiple_virtserialports.N_1.q35: STARTED
Failed to print_line '()' '10.73.75.149Please wait...'
Failed to print_line '()' '10.73.75.149Microsoft Windows [Version 10.0.14393]'
Failed to print_line '()' '10.73.75.149(c) 2016 Microsoft Corporation. All rights reserved.'
Failed to print_line '()' '10.73.75.149'

**Comment by vivianQizhu** [comment]
Seems this does not work as expected, will rewrite later.

**Pull request closed without merging**
