### PR TITLE
hotplug_mem_negative: Fix 'no valid keyword' issue

### PR DESCRIPTION
**Pull request by huangyum**
ID: 1839630
Signed-off-by: Yumei Huang <yuhuang@redhat.com>

### CODE REVIEW

**Comment by huangyum** [comment]
(1/1) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.hotplug_mem_negative.overcommit_host_mem: PASS (38.57 s)

**Comment by huangyum** [comment]
@zhenyzha @PaulYuuu Please help review, thanks.

**Comment by zhenyzha** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.hotplug_mem_negative.overcommit_host_mem: PASS (257.85 s)

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Comment by PaulYuuu** [comment]
LGTM.

**Comment by yanan-fu** [comment]
The code change is ok for me. It is better to make the commit info more clear.
As it is not related with the 'keyword'.  It is aim to make 'overcommit_mem' don't exceed the 'maxmem', but larger than the total mem that the host can provide.

Could you also update the typo `No invalid/valid keywords were found`

**Comment by huangyum** [comment]
@yanan-fu Thanks, updated.

**Comment by yanan-fu** [comment]
Acked-by: Yanan Fu <yfu@redhat.com>

**Pull request merged**
