### PR TITLE
nmi_bsod_catch: change win2025 min memory to 4096

### PR DESCRIPTION
**Pull request by menli820**
Guest min memory has to be 4096.0 for win2025.

ID: 2113
Signed-off-by: menli <menli@redhat.com>

### CODE REVIEW

**Comment by menli820** [comment]
@peixiu please help to review it when you free, thanks

 (1/1) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.nmi_bsod_catch.q35: PASS (430.31 s)

**Comment by peixiu** [comment]
Looks Good To Me!

Thanks @menli820 

Acked-by: Peixiu Hou phou@redhat.com

**Review by peixiu — APPROVED** [review]

**Comment by menli820** [comment]
@XueqiangWei  please help to review it when you free, thanks

**Review by XueqiangWei — APPROVED** [review]
LGTM,
Acked-by: xuwei@redhat.com

**Pull request merged**
