### PR TITLE
Update the function 'utils_test.qemu.windrv_check_running_verifier'

### PR DESCRIPTION
**Pull request by kimi1978wy**
Add a session login if no session exists

Signed-off-by: Yu Wang <wyu@redhat.com>

based on:https://github.com/avocado-framework/avocado-vt/pull/1451/

id: 1557143

### CODE REVIEW

**Comment by kimi1978wy** [comment]
Root Cause:
If driver is not verified successfully when installing guest, it will verify driver by utils_test.qemu.setup_win_driver_verifier, and the guest will reboot in this function. So this session is closed in this case.

Results:
(1/1) smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_blk.up.virtio_net.Win10.i386.io-github-autotest-qemu.pvpanic_basic.nmi: PASS (330.01 s)

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

**Comment by kimi1978wy** [comment]
@luckyh could you help to review this patch?

**Comment by kimi1978wy** [comment]
related cases results:
 (1/1) smp_4.2048m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_blk.up.virtio_net.Guest.Win2008.i386.sp2.io-github-autotest-qemu.win_irq_check.with_balloon: PASS (434.44 s)
 (1/1) smp_4.2048m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_blk.up.virtio_net.Guest.Win2008.i386.sp2.io-github-autotest-qemu.balloon_service.sc_interrogate: PASS (636.01 s)
 (1/1) smp_4.2048m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_blk.up.virtio_net.Guest.Win2008.i386.sp2.io-github-autotest-qemu.pvpanic_basic.nmi: PASS (629.14 s)
 (1/2) smp_4.2048m.repeat1.run_test.Host_RHEL.m7.u5.virtio_rng.rng_random.qcow2.virtio_blk.up.virtio_net.Guest.Win2008.i386.sp2.io-github-autotest-qemu.rng_bat: PASS (241.99 s)
 (2/2) smp_4.2048m.repeat1.run_test.Host_RHEL.m7.u5.virtio_rng.rng_egd.qcow2.virtio_blk.up.virtio_net.Guest.Win2008.i386.sp2.io-github-autotest-qemu.rng_bat: PASS (262.29 s)
 (1/1) smp_4.2048m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_blk.up.virtio_net.Guest.Win2008.i386.sp2.io-github-autotest-qemu.block_resize: PASS (449.41 s)
 (1/1) smp_4.2048m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_blk.up.virtio_net.Guest.Win2008.i386.sp2.io-github-autotest-qemu.balloon_stress: PASS (712.09 s)
 (1/1) smp_4.2048m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_blk.up.virtio_net.Guest.Win2008.i386.sp2.io-github-autotest-qemu.iozone_windows.aio_native: PASS (3357.16 s)

**Comment by xiagao** [comment]
Acked-by: Xiaoling Gao <xiagao@redhat.com>

**Comment by kimi1978wy** [comment]
@xuhan could you help to review this pr and https://github.com/avocado-framework/avocado-vt/pull/1451 , they fix the same bug.

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
