### PR TITLE
pci_bridge: update list devices returned by disk_hotplug for BLOCKDEV compatibility

### PR DESCRIPTION
**Pull request by ybduan**
ID: 1843403

Signed-off-by: ybduan <yduan@redhat.com>

### CODE REVIEW

**Comment by ybduan** [comment]
(1/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.pci_bridge.hotplug_unplug.one_bridge: PASS (61.37 s)
 (2/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.pci_bridge.hotplug_unplug.multi_parallel_bridges: PASS (59.32 s)

**Comment by ybduan** [comment]
Please help review this PR, thanks! @luckyh

**Comment by ybduan** [comment]
Please help review this PR, thanks! @yanan-fu

**Comment by ybduan** [comment]
(1/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.pci_bridge.hotplug_unplug.one_bridge: PASS (60.55 s)
 (2/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.pci_bridge.hotplug_unplug.multi_parallel_bridges: PASS (59.60 s)

**Comment by yanan-fu** [comment]
LGTM, 
Acked-by: Yanan Fu <yfu@redhat.com>

**Pull request merged**
