### PR TITLE
Add pattern to adapt qga on s390x

### PR DESCRIPTION
**Pull request by fbq815**
qga: add pattern to adapt qga command "halt" and "reboot" on s390x

ID: 2124750

Signed-off-by: Boqiao Fu <bfu@redhat.com>

### CODE REVIEW

**Comment by fbq815** [comment]
Test result:

RHEL.8.7:
JOB ID     : 49f337b2925675f33807ec010af0970915204c64
JOB LOG    : /root/avocado/job-results/job-2022-09-06T23.12-49f337b/job.log
 (1/1) Host_RHEL.m8.u7.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_halt.s390-virtio: STARTED
 (1/1) Host_RHEL.m8.u7.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_halt.s390-virtio: PASS (24.81 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2022-09-06T23.12-49f337b/results.html
JOB TIME   : 26.96 s

RHEL.9.1:
INFO | Start to run test
JOB ID     : 15988d7762caa9ab327d7ee6290cf1ab234bfd38
JOB LOG    : /root/avocado/job-results/job-2022-09-06T23.10-15988d7/job.log
 (1/1) Host_RHEL.m9.u1.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_halt.s390-virtio: STARTED
 (1/1) Host_RHEL.m9.u1.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_halt.s390-virtio: PASS (23.15 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2022-09-06T23.10-15988d7/results.html
JOB TIME   : 24.30 s

**Comment by fbq815** [comment]
@PaulYuuu please help me review this patch

**Comment by fbq815** [comment]
Test result:
RHEL.8.7 host:
with RHEL.7.9 guest:
JOB ID     : 3af3c8364ecb1dd4be1a1a06eff844204e9183dd
JOB LOG    : /root/avocado/job-results/job-2022-09-08T04.59-3af3c83/job.log
 (1/2) Host_RHEL.m8.u7.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_reboot.s390-virtio: STARTED
 (1/2) Host_RHEL.m8.u7.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_reboot.s390-virtio: PASS (46.87 s)
 (2/2) Host_RHEL.m8.u7.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_halt.s390-virtio: STARTED
 (2/2) Host_RHEL.m8.u7.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_halt.s390-virtio: PASS (23.72 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2022-09-08T04.59-3af3c83/results.html
JOB TIME   : 74.15 s

with RHEL.8.6 guest:
JOB ID     : 90517c4a4e2194763a86813870cb1a690fc3a8b9
JOB LOG    : /root/avocado/job-results/job-2022-09-08T05.10-90517c4/job.log
 (1/3) Host_RHEL.m8.u7.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.s390-virtio: STARTED
 (1/3) Host_RHEL.m8.u7.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.s390-virtio: PASS (796.36 s)
 (2/3) Host_RHEL.m8.u7.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_reboot.s390-virtio: STARTED
 (2/3) Host_RHEL.m8.u7.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_reboot.s390-virtio: PASS (50.63 s)
 (3/3) Host_RHEL.m8.u7.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_halt.s390-virtio: STARTED
 (3/3) Host_RHEL.m8.u7.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_halt.s390-virtio: PASS (24.42 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2022-09-08T05.10-90517c4/results.html
JOB TIME   : 876.87 s

with RHEL.8.7 guest:
JOB ID     : 50aa2c4b9268d5da8f5f62f73ac34cb169b88e53
JOB LOG    : /root/avocado/job-results/job-2022-09-08T05.34-50aa2c4/job.log
 (1/3) Host_RHEL.m8.u7.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.s390x.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.s390-virtio: STARTED
 (1/3) Host_RHEL.m8.u7.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.s390x.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.s390-virtio: PASS (634.26 s)
 (2/3) Host_RHEL.m8.u7.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_reboot.s390-virtio: STARTED
 (2/3) Host_RHEL.m8.u7.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_reboot.s390-virtio: PASS (49.65 s)
 (3/3) Host_RHEL.m8.u7.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_halt.s390-virtio: STARTED
 (3/3) Host_RHEL.m8.u7.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_halt.s390-virtio: PASS (24.28 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2022-09-08T05.34-50aa2c4/results.html
JOB TIME   : 712.82 s

RHEL.9.1 host:
with RHEL.7.9 guest:
JOB ID     : 78677f75505ad8105484beb421a726c1d9faf7d5
JOB LOG    : /root/avocado/job-results/job-2022-09-08T04.59-78677f7/job.log
 (1/2) Host_RHEL.m9.u1.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_reboot.s390-virtio: STARTED
 (1/2) Host_RHEL.m9.u1.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_reboot.s390-virtio: PASS (45.27 s)
 (2/2) Host_RHEL.m9.u1.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_halt.s390-virtio: STARTED
 (2/2) Host_RHEL.m9.u1.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_halt.s390-virtio: PASS (21.95 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2022-09-08T04.59-78677f7/results.html
JOB TIME   : 69.27 s

with RHEL.9.0 guest:
JOB ID     : ee34f885b221bceb42704980017a65d8bccf2e8d
JOB LOG    : /root/avocado/job-results/job-2022-09-08T05.01-ee34f88/job.log
 (1/2) Host_RHEL.m9.u1.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_reboot.s390-virtio: STARTED
 (1/2) Host_RHEL.m9.u1.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_reboot.s390-virtio: PASS (42.31 s)
 (2/2) Host_RHEL.m9.u1.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_halt.s390-virtio: STARTED
 (2/2) Host_RHEL.m9.u1.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_halt.s390-virtio: PASS (19.72 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2022-09-08T05.01-ee34f88/results.html
JOB TIME   : 64.07 s

with RHEL.9.1 guest:
JOB ID     : cb63c25680faa4f5bb937d1505fb4f8265db81f5
JOB LOG    : /root/avocado/job-results/job-2022-09-08T05.09-cb63c25/job.log
 (1/2) Host_RHEL.m9.u1.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_reboot.s390-virtio: STARTED
 (1/2) Host_RHEL.m9.u1.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_reboot.s390-virtio: PASS (39.26 s)
 (2/2) Host_RHEL.m9.u1.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_halt.s390-virtio: STARTED
 (2/2) Host_RHEL.m9.u1.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.s390x.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_halt.s390-virtio: PASS (18.66 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2022-09-08T05.09-cb63c25/results.html
JOB TIME   : 59.96 s

**Comment by fbq815** [comment]
@PaulYuuu please help me review this patch

**Review by PaulYuuu — APPROVED** [review]

**Pull request merged**
