### PR TITLE
deps:Update memory stress test package

### PR DESCRIPTION
**Pull request by maxujun**
Update stressapptest.tar to latest version

ID:2672

### CODE REVIEW

**Comment by maxujun** [comment]
(1/1) Host_RHEL.m8.u10.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.s390x.io-github-autotest-qemu.migration_with_block.with_post_copy.with_mem_stress.s390-virtio: STARTED
 (1/1) Host_RHEL.m8.u10.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.s390x.io-github-autotest-qemu.migration_with_block.with_post_copy.with_mem_stress.s390-virtio: PASS (209.16 s)

**Comment by maxujun** [comment]
@PaulYuuu @fbq815 Could you help review?

**Comment by PaulYuuu** [comment]
Should be an all platforms issue.

**Review by fbq815 — APPROVED** [review]
LGTM and I agree with yihyu, please involve feature owner from other paltform as well

**Comment by maxujun** [comment]
@mcasquer @zhenyzha Could you help review?

**Comment by maxujun** [comment]
(1/1) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.migration_with_block.with_post_copy.with_mem_stress: STARTED
 (1/1) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.migration_with_block.with_post_copy.with_mem_stress: PASS (215.07 s)

**Comment by mcasquer** [comment]
I am getting the following error, perhaps it's not dependent on the patch

```bash
[stdlog] 2024-11-12 03:03:45,162 avocado.virttest.virt_vm virt_vm          L1254 ERROR| Can't get guest network status information, reason: Login timeout expired    (output: '\x1b[13;40H\x1b[13;40H\x1b[0m\x1b[37m\x1b[40m\x1b[14;40H     Reset system     \x1b[0m\x1b[37m\x1b[44m\x1b[15;40H    Continue boot     \x1b[16;40H Always continue boot \x1b[17;40H')
```

**Comment by maxujun** [comment]
@mcasquer Any comment for this patch?

**Comment by mcasquer** [comment]
> @mcasquer Any comment for this patch?

@maxujun 
Yeah I've tried again in RHEL 10 it still fails, I will share the log internally

**Comment by maxujun** [comment]
I did test on x86 platform，It passed.
(1/1) Host_RHEL.m10.u0.raw.virtio_blk.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.migration_with_block.with_post_copy.with_mem_stress.q35: STARTED
 (1/1) Host_RHEL.m10.u0.raw.virtio_blk.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.migration_with_block.with_post_copy.with_mem_stress.q35: PASS (521.37 s)

**Comment by mcasquer** [comment]
@maxujun I see it passed now
```
 (1/1) Host_RHEL.m10.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.migration_with_block.with_post_copy.with_mem_stress.q35: STARTED
 (1/1) Host_RHEL.m10.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.migration_with_block.with_post_copy.with_mem_stress.q35: PASS (353.09 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```

**Comment by mcasquer** [comment]
Please @maxujun verify your commit with `-S` as requested :)

**Review by PaulYuuu — APPROVED** [review]

**Pull request merged**
