### PR TITLE
virtio_fs: new case of selinux_testsuits

### PR DESCRIPTION
**Pull request by xiagao**
Only for linux guest, add selinux-testsuits on virtiofs.
ID: 2130148
Signed-off-by: Xiaoling Gao <xiagao@redhat.com>

### CODE REVIEW

**Comment by xiagao** [comment]
--testcase=virtio_fs_security_label.selinux_testsuits
 (1/1) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.virtio_fs_security_label.selinux_testsuits.q35: STARTED
 (1/1) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.virtio_fs_security_label.selinux_testsuits.q35: PASS (247.86 s)

**Comment by zhenyzha** [comment]
sorry for the late reply

```
 (1/2) Host_RHEL.m9.u2.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.2.0.aarch64.io-github-autotest-qemu.virtio_fs_security_label.arm64-pci: STARTED
 (1/2) Host_RHEL.m9.u2.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.2.0.aarch64.io-github-autotest-qemu.virtio_fs_security_label.arm64-pci: PASS (69.56 s)
 (2/2) Host_RHEL.m9.u2.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.2.0.aarch64.io-github-autotest-qemu.virtio_fs_security_label.selinux_testsuits.arm64-pci: STARTED
 (2/2) Host_RHEL.m9.u2.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.2.0.aarch64.io-github-autotest-qemu.virtio_fs_security_label.selinux_testsuits.arm64-pci: ERROR: Shell command failed: 'rpm -ivh /tmp/jfsutils-1.1.15-18.el9.1.x86_64.rpm'    (status: 1,    output: 'error: Failed dependencies:\n\tlibc.so.6(GLIBC_2.14)(64bit) is needed by jfsutils-1.1.15-18.el9.1.x86_64\n\tlibc.so.6(GLIBC_2.2.5)(64bit) is needed by jfs... (60.89 s)
```

jfsutils-1.1.15-18.el9.1.x86_64 This package is x86 only. Maybe we need to consider other platforms and future versions.

**Comment by xiagao** [comment]
> sorry for the late reply
> 
> ```
>  (1/2) Host_RHEL.m9.u2.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.2.0.aarch64.io-github-autotest-qemu.virtio_fs_security_label.arm64-pci: STARTED
>  (1/2) Host_RHEL.m9.u2.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.2.0.aarch64.io-github-autotest-qemu.virtio_fs_security_label.arm64-pci: PASS (69.56 s)
>  (2/2) Host_RHEL.m9.u2.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.2.0.aarch64.io-github-autotest-qemu.virtio_fs_security_label.selinux_testsuits.arm64-pci: STARTED
>  (2/2) Host_RHEL.m9.u2.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.2.0.aarch64.io-github-autotest-qemu.virtio_fs_security_label.selinux_testsuits.arm64-pci: ERROR: Shell command failed: 'rpm -ivh /tmp/jfsutils-1.1.15-18.el9.1.x86_64.rpm'    (status: 1,    output: 'error: Failed dependencies:\n\tlibc.so.6(GLIBC_2.14)(64bit) is needed by jfsutils-1.1.15-18.el9.1.x86_64\n\tlibc.so.6(GLIBC_2.2.5)(64bit) is needed by jfs... (60.89 s)
> ```
> 
> jfsutils-1.1.15-18.el9.1.x86_64 This package is x86 only. Maybe we need to consider other platforms and future versions.

I'm not sure if the selinux_testsuits is suitable to test on arm, could you help to check?

**Comment by zhenyzha** [comment]
@xiagao I found jfsutils has src.rpm version and did some tests.
Unfortunately, selinux-testsuite currently seems to fail to compile on arm, 
so I think we can set this patch to x86 only.

**Comment by xiagao** [comment]
> @xiagao I found jfsutils has src.rpm version and did some tests. Unfortunately, selinux-testsuite currently seems to fail to compile on arm, so I think we can set this patch to x86 only.

Ok, thanks for your confirmation, I'll set the limitation.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
