### PR TITLE
x86_cpu_hotplug: Fix regEx pattern error

### PR DESCRIPTION
**Pull request by nanliu-r**
ID: 2513

regEx pattern error because of dmesg log changed.

### CODE REVIEW

**Comment by nanliu-r** [comment]
(1/1) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.cpu_device_hotplug_time_jump.q35: PASS (82.43 s)

**Comment by nanliu-r** [comment]
@PaulYuuu @huangyum Please help review this patch, thanks!

**Review by PaulYuuu — APPROVED** [review]

**Comment by huangyum** [comment]
The code looks good to me.  Just wanna double confirm, is the case only for x86 as in the summary?

**Comment by nanliu-r** [comment]
> The code looks good to me. Just wanna double confirm, is the case only for x86 as in the summary?

Yes, only x86_64 platform.

**Review by huangyum — APPROVED** [review]

**Pull request merged**
