### PR TITLE
qmp_event_notification: fix watchdog cases issue

### PR DESCRIPTION
**Pull request by yiqianwei**
1.Fix connection method of watchdog device in Q35
2.Remove '-watchdog' option and use '-device' instead

ID: 2155958

Signed-off-by: Yiqian Wei <yiwei@redhat.com>

### CODE REVIEW

**Comment by yiqianwei** [comment]
test results:
 (01/10) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: STARTED
 (01/10) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (02/10) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_quit.from_qmp.q35: STARTED
 (02/10) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_quit.from_qmp.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (03/10) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_system_reset.from_guest.q35: STARTED
 (03/10) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_system_reset.from_guest.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (04/10) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_system_reset.from_qmp.q35: STARTED
 (04/10) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_system_reset.from_qmp.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (05/10) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_system_powerdown.from_guest.q35: STARTED
 (05/10) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_system_powerdown.from_guest.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (06/10) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_system_powerdown.from_qmp.q35: STARTED
 (06/10) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_system_powerdown.from_qmp.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (07/10) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_stop.from_hmp.q35: STARTED
 (07/10) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_stop.from_hmp.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (08/10) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_resume.from_hmp.q35: STARTED
 (08/10) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_resume.from_hmp.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (09/10) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_rtc_change.from_guest.q35: STARTED
 (09/10) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_rtc_change.from_guest.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (10/10) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_guest_panicked.from_guest.q35: STARTED
 (10/10) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_guest_panicked.from_guest.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 10
JOB HTML   : /tmp/avocado-dry-run-qc2epjjv/job-2023-01-13T03.51-25e72c1/results.html
JOB TIME   : 7.28 s

**Comment by yiqianwei** [comment]
@yanan-fu  and @jingzhao84 , could you review this patch? thanks

**Comment by yanan-fu** [comment]
The issue with `watchdog` need be fixed in qmp,  we can not remove it in upstream, thanks!

**Comment by yiqianwei** [comment]
(1/7) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (650.63 s)

 (2/7) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_watchdog.qmp_pause.from_guest.q35: PASS (147.27 s)

 (3/7) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_watchdog.qmp_reset.from_guest.q35: PASS (151.01 s)

 (4/7) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_watchdog.qmp_poweroff.from_guest.q35: PASS (132.37 s)

 (5/7) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_watchdog.qmp_shutdown.from_guest.q35: PASS (136.41 s)

 (6/7) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_watchdog.qmp_debug.from_guest.q35: PASS (141.09 s)

 (7/7) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_watchdog.qmp_none.from_guest.q35: PASS (142.30 s)

**Comment by yiqianwei** [comment]
@yanan-fu , I already changed this patch, please review it. thanks

**Comment by yanan-fu** [comment]
Call for test result , thanks!

**Comment by yiqianwei** [comment]
test results:

 (1/6) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_watchdog.qmp_pause.from_guest.q35: PASS (127.07 s)

 (2/6) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_watchdog.qmp_reset.from_guest.q35: PASS (129.77 s)

  (3/6) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_watchdog.qmp_poweroff.from_guest.q35: PASS (108.04 s)

 (4/6) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_watchdog.qmp_shutdown.from_guest.q35: PASS (109.54 s)

 (6/6) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_watchdog.qmp_none.from_guest.q35: PASS (116.82 s)

RESULTS    : PASS 6 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2023-03-14T05.56-705dde5/results.html
JOB TIME   : 711.01 s

**Review by yanan-fu — APPROVED** [review]

**Pull request merged**
