### PR TITLE
usb: Refine test cases in the config file

### PR DESCRIPTION
**Pull request by ngu-niny**
1. Replace parameter 'usb_max_port*' to the correct one 'max_ports*'.
2. Add 'no ppc64 ppc64le' in 'ich9-ehci' part.
3. Delete usb_boot test for usb_kbd, usb_mouse and usb_tablet part
   since it's covered by cases in usb_device_check.cfg.
4. Correct usb controllers to be 'only usb-ehci, ich9-ehci' in
   usb_hotplug..usb_negative_test part.
5. Delete usb_hotplug.usb_multi_times.usb_negative_test and
   usb_host.usb_multi_times.usb_negative_test cases, since they are
   meaningless.
6. Add/delete lines to make usb_multi_disk part work.

ID: 1411609, 1560843
Signed-off-by: Nini Gu <ngu@redhat.com>

### CODE REVIEW

**Comment by ngu-niny** [comment]
24 cases was analyzed after applying the patch:

# python ConfigTest.py --testcase=usb..nec-xhci --nicmodel=virtio_net --driveformat=virtio_scsi --platform=x86_64 --guestname=RHEL.7.5 --clone=no --verbose=yes --dryrun=yes
......
Test results available in /var/tmp/avocado-dry-run-8kALjK/job-2018-03-27T05.19-0000000
# 
# ll -h /var/tmp/avocado-dry-run-8kALjK/job-2018-03-27T05.19-0000000/test-results/
total 0
drwxr-xr-x 3 root root 95 Mar 27 05:19 01-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_one_time.usb_kbd.without_usb_hub.nec-xhci
drwxr-xr-x 3 root root 95 Mar 27 05:19 02-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_one_time.usb_kbd.with_usb_hub.nec-xhci
drwxr-xr-x 3 root root 95 Mar 27 05:19 03-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_one_time.usb_mouse.without_usb_hub.nec-xhci
drwxr-xr-x 3 root root 95 Mar 27 05:19 04-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_one_time.usb_mouse.with_usb_hub.nec-xhci
drwxr-xr-x 3 root root 95 Mar 27 05:19 05-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_one_time.usb_tablet.without_usb_hub.nec-xhci
drwxr-xr-x 3 root root 95 Mar 27 05:19 06-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_one_time.usb_tablet.with_usb_hub.nec-xhci
drwxr-xr-x 3 root root 95 Mar 27 05:19 07-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_one_time.usb_ccid.without_usb_hub.nec-xhci
drwxr-xr-x 3 root root 95 Mar 27 05:19 08-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_one_time.usb_ccid.with_usb_hub.nec-xhci
drwxr-xr-x 3 root root 95 Mar 27 05:19 09-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_one_time.usb_hub.without_usb_hub.nec-xhci
drwxr-xr-x 3 root root 95 Mar 27 05:19 10-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_one_time.usb_hub.with_usb_hub.nec-xhci
drwxr-xr-x 3 root root 95 Mar 27 05:19 11-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_multi_times.usb_kbd.without_usb_hub.nec-xhci
drwxr-xr-x 3 root root 95 Mar 27 05:19 12-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_multi_times.usb_kbd.with_usb_hub.nec-xhci
drwxr-xr-x 3 root root 95 Mar 27 05:19 13-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_multi_times.usb_mouse.without_usb_hub.nec-xhci
drwxr-xr-x 3 root root 95 Mar 27 05:19 14-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_multi_times.usb_mouse.with_usb_hub.nec-xhci
drwxr-xr-x 3 root root 95 Mar 27 05:19 15-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_multi_times.usb_tablet.without_usb_hub.nec-xhci
drwxr-xr-x 3 root root 95 Mar 27 05:19 16-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_multi_times.usb_tablet.with_usb_hub.nec-xhci
drwxr-xr-x 3 root root 95 Mar 27 05:19 17-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_multi_times.usb_ccid.without_usb_hub.nec-xhci
drwxr-xr-x 3 root root 95 Mar 27 05:19 18-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_multi_times.usb_ccid.with_usb_hub.nec-xhci
drwxr-xr-x 3 root root 95 Mar 27 05:19 19-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_multi_times.usb_hub.without_usb_hub.nec-xhci
drwxr-xr-x 3 root root 95 Mar 27 05:19 20-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_multi_times.usb_hub.with_usb_hub.nec-xhci
drwxr-xr-x 3 root root 95 Mar 27 05:19 21-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_storage.without_usb_hub.nec-xhci
drwxr-xr-x 3 root root 95 Mar 27 05:19 22-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_host.usb_one_time.usb_normal_test.without_usb_hub.nec-xhci
drwxr-xr-x 3 root root 95 Mar 27 05:19 23-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_host.usb_one_time.usb_negative_test.without_usb_hub.nec-xhci
drwxr-xr-x 3 root root 95 Mar 27 05:19 24-smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_host.usb_multi_times.usb_normal_test.without_usb_hub.nec-xhci

**Comment by ngu-niny** [comment]
@maxujun @hereischen Could you help to review the patch? Thanks.

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

It looks OK to me.  Please use different commits next time when you have different groups of changes like this one. Thanks.

**Comment by ngu-niny** [comment]
The PR is based on following PR:
https://github.com/avocado-framework/avocado-vt/pull/1481

**Comment by ngu-niny** [comment]
New test PASS:
[root@hp-z220-02 staf-kvm-devel]# python ConfigTest.py --testcase=usb.usb_multi_disk.max_disk,usb.usb_hotplug..usb_negative_test,usb.usb_host..usb_negative_test,usb..usb_kbd.without_usb_hub.ich9-ehci,usb..usb_mouse.without_usb_hub.ich9-ehci,usb..usb_tablet.without_usb_hub.ich9-ehci --driveformat=virtio_scsi --nicmodel=virtio_net --guestname=RHEL.7.5 --platform=x86_64 --verbose=yes --clone=no
[root@hp-z220-02 staf-kvm-devel]# 
[root@hp-z220-02 staf-kvm-devel]# ./workspace/avocado-vt/scripts/scan_results.py 
CaseName                                 Status          StartTime       EndTime         Result     TimeElapsed
'01-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_reboot.usb_kbd.without_usb_hub.ich9-ehci' Finshed 2018-04-08 04:12:06 2018-04-08 04:13:59 PASS 112.445344
'02-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_reboot.usb_mouse.without_usb_hub.ich9-ehci' Finshed 2018-04-08 04:13:59 2018-04-08 04:15:48 PASS 109.384551
'03-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_reboot.usb_tablet.without_usb_hub.ich9-ehci' Finshed 2018-04-08 04:15:48 2018-04-08 04:17:38 PASS 109.224158
'04-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_one_time.usb_normal_test.usb_kbd.without_usb_hub.ich9-ehci' Finshed 2018-04-08 04:17:38 2018-04-08 04:18:53 PASS 75.707862
'05-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_one_time.usb_normal_test.usb_mouse.without_usb_hub.ich9-ehci' Finshed 2018-04-08 04:18:54 2018-04-08 04:20:09 PASS 75.015401
'06-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_one_time.usb_normal_test.usb_tablet.without_usb_hub.ich9-ehci' Finshed 2018-04-08 04:20:09 2018-04-08 04:21:26 PASS 77.230609
'07-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_one_time.usb_negative_test.usb_hub.without_usb_hub.ich9-ehci.ich9-ehci2' Finshed 2018-04-08 04:21:26 2018-04-08 04:22:20 PASS 54.039595
'08-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_multi_times.usb_normal_test.usb_kbd.without_usb_hub.ich9-ehci' Finshed 2018-04-08 04:22:20 2018-04-08 04:40:41 PASS 1101.199944
'09-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_multi_times.usb_normal_test.usb_mouse.without_usb_hub.ich9-ehci' Finshed 2018-04-08 04:40:42 2018-04-08 04:59:04 PASS 1102.242068
'10-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_hotplug.usb_multi_times.usb_normal_test.usb_tablet.without_usb_hub.ich9-ehci' Finshed 2018-04-08 04:59:04 2018-04-08 05:17:24 PASS 1100.297578
'11-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_host.usb_one_time.usb_negative_test.without_usb_hub.piix3-uhci' Finshed 2018-04-08 05:17:24 2018-04-08 05:19:05 PASS 100.440369
'12-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_host.usb_one_time.usb_negative_test.without_usb_hub.piix4-uhci' Finshed 2018-04-08 05:19:05 2018-04-08 05:20:48 PASS 102.597032
'13-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_host.usb_one_time.usb_negative_test.without_usb_hub.ich9-uhci' Finshed 2018-04-08 05:20:48 2018-04-08 05:22:29 PASS 101.58533
'14-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_host.usb_one_time.usb_negative_test.without_usb_hub.ich9-ehci' Finshed 2018-04-08 05:22:30 2018-04-08 05:24:14 PASS 104.198321
'15-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_host.usb_one_time.usb_negative_test.without_usb_hub.usb-ehci' Finshed 2018-04-08 05:24:14 2018-04-08 05:25:54 PASS 99.700445
'16-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_host.usb_one_time.usb_negative_test.without_usb_hub.nec-xhci' Finshed 2018-04-08 05:25:54 2018-04-08 05:27:34 PASS 99.936541
'17-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_host.usb_one_time.usb_negative_test.without_usb_hub.qemu-xhci' Finshed 2018-04-08 05:27:34 2018-04-08 05:29:15 PASS 101.032417
'18-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_multi_disk.max_disk.without_usb_hub.ich9-ehci.ich9-ehci2' Finshed 2018-04-08 05:29:15 2018-04-08 05:31:43 PASS 148.344182
'19-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_multi_disk.max_disk.without_usb_hub.usb-ehci' Finshed 2018-04-08 05:31:44 2018-04-08 05:34:21 PASS 157.620415
'20-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_multi_disk.max_disk.without_usb_hub.nec-xhci' Finshed 2018-04-08 05:34:21 2018-04-08 05:36:36 PASS 134.599321
'21-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.usb.usb_multi_disk.max_disk.without_usb_hub.qemu-xhci' Finshed 2018-04-08 05:36:36 2018-04-08 05:38:47 PASS 131.063156
Summary: 
Finshed=21, PASS=21

**Pull request merged**
