### PR TITLE
qmp_command: Update command line about s3/s4 for q35 machine type

### PR DESCRIPTION
**Pull request by jingzhao84**
ID: 1592773, 1592774

Signed-off-by: jinzhao <jinzhao@redhat.com>

### CODE REVIEW

**Comment by jingzhao84** [comment]
Host_RHEL.m7.u6.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_suspend.from_guest.q35: PASS

Host_RHEL.m7.u6.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_suspend.from_guest: PASS

**Comment by jingzhao84** [comment]
@yanan-fu @huangyum  could you help to review it? thanks

**Comment by jingzhao84** [comment]
(09/17) Host_RHEL.m7.u6.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_suspend.from_guest.q35: PASS (120.81 s)
 (10/17) Host_RHEL.m7.u6.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_disk_suspend.from_guest.q35: PASS (109.46 s)

**Comment by jingzhao84** [comment]
@yanan-fu @huangyum combine 2 bzs into this pr, could you help to review it again? thanks

**Comment by yanan-fu** [comment]
@jingzhao84  Please ensure the the head of the commit less than 72 characters.
refer http://avocado-framework.readthedocs.io/en/latest/ContributionGuide.html?highlight=commit%20format#git-workflow

**Comment by yanan-fu** [comment]
Acked-by: Yanan Fu <yfu@redhat.com>

**Pull request merged**
