### PR TITLE
Add test cases using test suites to test SVE

### PR DESCRIPTION
**Pull request by PaulYuuu**
Add 3 test cases to use test suites to test SVE on host and guest.

ID: 1979211, 1979213, 1979214
Signed-off-by: Yihuang Yu <yihyu@redhat.com>

### CODE REVIEW

**Comment by PaulYuuu** [comment]
```
 (4/6) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.aarch64.io-github-autotest-qemu.sve_suite.optimized_routines.arm64-pci: PASS (359.05 s)
 (5/6) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.aarch64.io-github-autotest-qemu.sve_suite.get_reg_list.arm64-pci: ERROR: Failed to compile the test suite. (224.28 s)
 (6/6) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.aarch64.io-github-autotest-qemu.sve_suite.sve_stress.arm64-pci: PASS (1293.45 s)
```
`get-reg-list` is failed by the upstream problem, checkout to `2fea6cf7d32141b9e95e30500f1d50a9f92a7371` is okay.

**Comment by PaulYuuu** [comment]
Hello @zhenyzha , request for your review, thanks.

**Comment by zhenyzha** [comment]
Hit another error, the detailed log is attached to the 1979211.

```
 (1/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.sve_suite.optimized_routines.arm64-pci: ERROR: Timeout expired while waiting for shell command to complete: 'make check 2>/dev/null'    (output: 'cat ./math/test/testcases/directed/cosf.tst ./math/test/testcases/directed/erf.tst ./math/test/testcases/directed/erff.tst ./math/test/testcases/directed/ex... (524.15 s)
 (2/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.sve_suite.get_reg_list.arm64-pci: ERROR: Failed to compile the test suite. (375.95 s)
 (3/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.sve_suite.sve_stress.arm64-pci: PASS (1349.89 s)
```

**Comment by PaulYuuu** [comment]
> Hit another error, the detailed log is attached to the 1979211.
> 
> ```
>  (1/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.sve_suite.optimized_routines.arm64-pci: ERROR: Timeout expired while waiting for shell command to complete: 'make check 2>/dev/null'    (output: 'cat ./math/test/testcases/directed/cosf.tst ./math/test/testcases/directed/erf.tst ./math/test/testcases/directed/erff.tst ./math/test/testcases/directed/ex... (524.15 s)
>  (2/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.sve_suite.get_reg_list.arm64-pci: ERROR: Failed to compile the test suite. (375.95 s)
>  (3/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.sve_suite.sve_stress.arm64-pci: PASS (1349.89 s)
> ```

Thank you @zhenyzha , I tried it manually, the time longer than 180s, so I will increase the timeout.
```
real	3m8.595s
user	3m7.947s
sys	0m4.376s
```

**Comment by zhenyzha** [comment]
```
 (1/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.sve_suite.optimized_routines.arm64-pci: PASS (553.54 s)
 (2/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.sve_suite.get_reg_list.arm64-pci: ERROR: Failed to compile the test suite. (292.26 s)
 (3/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.sve_suite.sve_stress.arm64-pci: PASS (1364.74 s)
```
LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Review by zhenyzha — APPROVED** [review]

**Pull request merged**
