### PR TITLE
edk2_basic: Add edk2 output info checkpoint

### PR DESCRIPTION
**Pull request by zhenyzha**
Add edk2 output information checkpoint due to product issue.

Signed-off-by: zhenyzha <zhenyzha@redhat.com>
ID: 2866

### CODE REVIEW

**Comment by zhenyzha** [comment]
io-github-autotest-qemu.edk2_basic.arm64-pci: FAIL: edk2 failed to start. Please check the serial log for details. (43.91 s)

@PaulYuuu @XueqiangWei Could you pls help review when you are free, thanks.

**Review by dzhengfy — APPROVED** [review]
LGTM

**Review by PaulYuuu — APPROVED** [review]

**Comment by XueqiangWei** [comment]
Passed on x86 platform.

**Review by XueqiangWei — APPROVED** [review]
LGTM,
Acked-by: xuwei@redhat.com

**Pull request merged**
