### PR TITLE
Reduce the number of disks in unattended installation

### PR DESCRIPTION
**Pull request by qingwangrh**
ID:1861580
Signed-off-by: qingwangrh <qinwang@redhat.com>

### CODE REVIEW

**Comment by qingwangrh** [comment]
Pending on Bug 1677833 - [Q35]Drive number is incorrect during install windows guest os when with two virtio-blk disks.
But it may fix bug in seabios log "WARNING - Unable to allocate resource at vp_find_vq ..."

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=unattended_install.cdrom.extra_cdrom_ks.multi_disk_install.aio_native.q35 --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=Win2019 --driveformat=virtio_blk --nicmodel=virtio_net --imageformat=qcow2 --machines=q35 --customsparams="image_aio=threads\ncd_format=ide" --clone=no

(1/1) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.multi_disk_install.aio_native.q35: ERROR: Background error is detected, please refer to file: 'background-error.log' for more details. 

It is expected result due to Bug 1677833

python ConfigTest.py --testcase=unattended_install.cdrom.extra_cdrom_ks.multi_disk_install.aio_native --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=Win2019 --driveformat=virtio_blk --nicmodel=virtio_net --imageformat=qcow2 --machines=i440fx --customsparams="image_aio=threads\ncd_format=ide" --clone=no

(1/1) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.multi_disk_install.aio_native: PASS

**Comment by qingwangrh** [comment]
@YongxueHong @menli820 please help to review

**Comment by menli820** [comment]
python3 ConfigTest.py --testcase=unattended_install.cdrom.extra_cdrom_ks.multi_disk_install.aio_native.q35 --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=Win10 --driveformat=virtio_blk --nicmodel=virtio_net --imageformat=qcow2 --machines=q35 --customsparams="image_aio=threads\ncd_format=ide" --clone=no

 (1/1) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.multi_disk_install.aio_native.q35: ERROR: Background error is detected, please refer to file: 'background-error.log' for more details. (4294.17 s) (It is expected result due to Bug 1677833)

python ConfigTest.py --testcase=unattended_install.cdrom.extra_cdrom_ks.multi_disk_install.aio_native --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=Win2019 --driveformat=virtio_blk --nicmodel=virtio_net --imageformat=qcow2 --machines=i440fx --customsparams="image_aio=threads\ncd_format=ide" --clone=no
(1/1) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.multi_disk_install.aio_native: PASS (1549.61 s)

commit title had better limited to 72 characters, and suggest add why need this patch,thanks

**Comment by qingwangrh** [comment]
@menli820 updated title and desc.

**Comment by menli820** [comment]
LGTM

**Pull request merged**
