### PR TITLE
virtio_fs_set_capability: update virtiofsd user config method

### PR DESCRIPTION
**Pull request by zhenyzha**
qcontainer: Add virtiofsd user config method
Update this method in tp-qemu case

ID: 1969269
Signed-off-by: Zhenyu Zhang <zhenyzha@redhat.com>

### CODE REVIEW

**Comment by zhenyzha** [comment]
depend on: https://github.com/avocado-framework/avocado-vt/pull/3080

**Comment by zhenyzha** [comment]
avocado-vt]# git am 3080.patch 
Applying: Modify virtiofsd daemon and qemu cmd decouple

io-github-autotest-qemu]# git am 2852.patch 
Applying: Update virtiofsd user config method

```
 (1/2) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.aarch64.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_dac_read_search.with_cache.auto.arm64-pci: PASS (73.21 s)
 (2/2) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.aarch64.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_sys_admin.with_cache.none.arm64-pci: PASS (77.07 s)
```
@YongxueHong Could you pls help review when you are free. thanks.

**Comment by zhenyzha** [comment]
@xiagao @YongxueHong Could you pls help review when you are free. thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM

**Comment by xiagao** [comment]
Result is good, I will review the code. 
(1/4) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_dac_read_search.with_cache.auto.q35: PASS (72.88 s)
 (2/4) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_sys_admin.with_cache.none.q35: PASS (86.58 s)
 (3/4) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_dac_read_search.with_cache.auto.q35: PASS (227.95 s)
 (4/4) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_sys_admin.with_cache.none.q35: PASS (95.64 s)

**Review by xiagao — APPROVED** [review]
LGTM

**Pull request merged**
