### PR TITLE
block_hotplug_scsi_hba: Add cases to test options of hotplug scsi hba

### PR DESCRIPTION
**Pull request by YongxueHong**
Add cases that test hotplug scsi hba with the options
"hotplug=on" and "hotplug=off".

ID: 1731615
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by YongxueHong** [comment]
Depends on https://github.com/autotest/tp-qemu/pull/1735

**Comment by qingwangrh** [comment]
./workspace/bin/python ConfigTest.py --testcase=block_hotplug_scsi_hba --guestname=RHEL.8.1.0 --driveformat=virtio_blk,virtio_scsi --clone=no

(1/2) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.block_hotplug_scsi_hba.with_hotplug_on: PASS (69.58 s)
 (2/2) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.block_hotplug_scsi_hba.with_hotplug_off: PASS (96.25 s)

**Comment by qingwangrh** [comment]
LGTM

**Comment by zhenyzha** [comment]
python3 -blockdev
 (1/2) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.block_hotplug_scsi_hba.with_hotplug_on: PASS (143.23 s)
 (2/2) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.block_hotplug_scsi_hba.with_hotplug_off: PASS (198.55 s)

python2 -drive testing

**Comment by zhenyzha** [comment]
python2 -drive 
 (1/2) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (1021.17 s)
 (2/2) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.rh_kernel_update: PASS (335.09 s)

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Comment by peixiu** [comment]
**Tested with -drive format on win2012-64 guest os, all passed.**
 (1/2) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.block_hotplug_scsi_hba.with_hotplug_on.q35: PASS (98.95 s)
 (2/2) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.block_hotplug_scsi_hba.with_hotplug_off.q35: PASS (141.29 s)

**Tested with -blockdev format on win2012-64 guest os, all failed:**
 (2/3) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.block_hotplug_scsi_hba.with_hotplug_on.q35: ERROR: QMP command 'blockdev-add' failed    (arguments: {'node-name': 'drive_stg0', 'driver': 'qcow2', 'cache': {'direct': True, 'no-flush': False}, 'file': 'file_stg0'},    error message: {'class': 'GenericError', 'desc': 'Cannot find device=file_stg0 nor node_... (62.22 s)
 (3/3) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.block_hotplug_scsi_hba.with_hotplug_off.q35: ERROR: QMP command 'blockdev-add' failed    (arguments: {'node-name': 'drive_stg0', 'driver': 'qcow2', 'cache': {'direct': True, 'no-flush': False}, 'file': 'file_stg0'},    error message: {'class': 'GenericError', 'desc': 'Cannot find device=file_stg0 nor node_... (33.49 s)

**The code create new image as /home/kvm_autotest_root/images/storage0.qcow2, but not added this image first when hotplug, it seems the blockdev-add command order is incorrect.**
Error log as follows,
04:33:14 DEBUG| (monitor avocado-vt-vm1.qmpmonitor1) Sending command 'blockdev-add'
04:33:14 DEBUG| Send command: {'execute': 'blockdev-add', 'arguments': {'node-name': 'drive_stg0', 'driver': 'qcow2', 'cache': {'direct': True, 'no-flush': False}, 'file': 'file_stg0'}, 'id': '3hZXXisR'}
04:33:14 ERROR|
04:33:14 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework_plugins_vt-73.0-py3.6.egg/avocado_vt/test.py:439
04:33:14 ERROR| Traceback (most recent call last):
04:33:14 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework_plugins_vt-73.0-py3.6.egg/virttest/error_context.py", line 135, in new_fn
04:33:14 ERROR|     return fn(*args, **kwargs)
04:33:14 ERROR|   File "/var/lib/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/block_hotplug_scsi_hba.py", line 69, in run
04:33:14 ERROR|     plug.hotplug_devs_serial(interval=int(params['hotplug_interval']))
04:33:14 ERROR|   File "/var/lib/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/provider/block_devices_plug.py", line 50, in wrapper
04:33:14 ERROR|     result = func(self, *args, **kwargs)
04:33:14 ERROR|   File "/var/lib/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/provider/block_devices_plug.py", line 440, in hotplug_devs_serial
04:33:14 ERROR|     self._hotplug_devs(self._imgs, monitor, bus)
04:33:14 ERROR|   File "/var/lib/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/provider/block_devices_plug.py", line 369, in _hotplug_devs
04:33:14 ERROR|     self._plug_devs(HOTPLUG, self._hotplugged_devs, monitor, bus)
04:33:14 ERROR|   File "/var/lib/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/provider/block_devices_plug.py", line 359, in _plug_devs
04:33:14 ERROR|     self, '_%s_atomic' % action)(*args)
04:33:14 ERROR|   File "/var/lib/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/provider/block_devices_plug.py", line 281, in _hotplug_atomic
04:33:14 ERROR|     out = device.hotplug(monitor)
04:33:14 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework_plugins_vt-73.0-py3.6.egg/virttest/qemu_devices/qdevices.py", line 257, in hotplug
04:33:14 ERROR|     return monitor.cmd(cmd, args)
04:33:14 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework_plugins_vt-73.0-py3.6.egg/virttest/qemu_monitor.py", line 1947, in cmd
04:33:14 ERROR|     raise QMPCmdError(cmd, args, r["error"])
04:33:14 ERROR| virttest.qemu_monitor.QMPCmdError: QMP command 'blockdev-add' failed    (arguments: {'node-name': 'drive_stg0', 'driver': 'qcow2', 'cache': {'direct': True, 'no-flush': False}, 'file': 'file_stg0'},    error message: {'class': 'GenericError', 'desc': 'Cannot find device=file_stg0 nor node_name=file_stg0'})

**Comment by peixiu** [comment]
Tested with latest code, cannot hit upper mentioned error, the hotplug order is correct.

01:37:42 DEBUG| Send command: {'execute': 'blockdev-add', 'arguments': {'node-name': 'file_stg0', 'driver': 'file', 'aio': 'threads', 'filename': '/home/kvm_autotest_root/images/storage0.qcow2', 'cache': {'direct': True, 'no-flush': False}}, 'id': 'SP9wmcYe'}
01:37:52 DEBUG| (monitor avocado-vt-vm1.qmpmonitor1) Sending command 'blockdev-add'
01:37:52 DEBUG| Send command: {'execute': 'blockdev-add', 'arguments': {'node-name': 'drive_stg0', 'driver': 'qcow2', 'cache': {'direct': True, 'no-flush': False}, 'file': 'file_stg0'}, 'id': 'E7aQT5bu'}
01:38:02 DEBUG| (monitor avocado-vt-vm1.qmpmonitor1) Sending command 'device_add'
01:38:02 DEBUG| Send command: {'execute': 'device_add', 'arguments': OrderedDict([('id', 'virtio_scsi_pci1'), ('driver', 'virtio-scsi-pci'), ('hotplug', 'off'), ('bus', 'pcie_extra_root_port_0'), ('addr', '0x0')]), 'id': 'Gzp0TvqH'}
01:38:13 DEBUG| (monitor avocado-vt-vm1.qmpmonitor1) Sending command 'device_add'
01:38:13 DEBUG| Send command: {'execute': 'device_add', 'arguments': OrderedDict([('driver', 'scsi-hd'), ('id', 'stg0'), ('bus', 'virtio_scsi_pci1.0'), ('drive', 'drive_stg0'), ('write-cache', 'on')]), 'id': 'bTOajVPC'}

Results as:
 (1/2) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.block_hotplug_scsi_hba.with_hotplug_on.q35: PASS (133.79 s)
 (2/2) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.block_hotplug_scsi_hba.with_hotplug_off.q35: ERROR: Shell command failed: 'echo rescan > diskpart_script && echo exit >> diskpart_script && diskpart / diskpart_script && del /f diskpart_script'    (status: 1,    output: '\nMicrosoft DiskPart version 6.2.9200\n\nCopyright (C) 1999-2012 Microsoft Corporation... (126.54 s)

Job 2/2 failed, due to product bug Bug 1711167 - Windows guest hits BSOD after rescan disks in Disk Management. So the code is ok for me～

Acked-by: Peixiu Hou phou@redhat.com

**Comment by YongxueHong** [comment]
@lolyu  pls help me to review it, thanks.

**Pull request merged**
