### PR TITLE
blockdev_stream_to_invalid_node.cfg:update error msg

### PR DESCRIPTION
**Pull request by aliang123**
Update error msg for virtio_blk

Signed-off-by: Aihua Liang <aliang@redhat.com>
id:1995397

### CODE REVIEW

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u5.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.blockdev_stream_to_invalid_node.q35: PASS (40.66 s)
(1/1) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.blockdev_stream_to_invalid_node.q35: PASS (40.76 s)

**Comment by aliang123** [comment]
@zhencliu @ngu-niny, please help to review, thanks.

**Comment by zhencliu** [comment]
LGTM

**Comment by ngu-niny** [comment]
1-Host_RHEL.m8.u6.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.blockdev_stream_to_invalid_node Finshed 2021-08-22 23:27:21 2021-08-22 23:29:01 PASS 99.707354
2-Host_RHEL.m8.u6.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.blockdev_stream_to_invalid_node Finshed 2021-08-22 23:29:01 2021-08-22 23:31:26 PASS 145.549944

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
