### PR TITLE
qemu.tests.virtio_storage_in_use: Add scenario live migration during …

### PR DESCRIPTION
**Pull request by CongLi**
…virtio storage in use.

Signed-off-by: Cong Li <coli@redhat.com>

id: 1272927 1231663

### CODE REVIEW

**Comment by CongLi** [comment]
virtio_scsi:
 (1/6) smp_16.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win7.i386.sp1.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.system_disk.with_live_migration.before_bg_test: PASS (462.82 s)
 (2/6) smp_16.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win7.i386.sp1.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.system_disk.with_live_migration.during_bg_test: PASS (299.67 s)
 (3/6) smp_16.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win7.i386.sp1.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.system_disk.with_live_migration.after_bg_test: PASS (322.78 s)
 (4/6) smp_16.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win7.i386.sp1.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.data_disk.with_live_migration.before_bg_test: PASS (377.89 s)
 (5/6) smp_16.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win7.i386.sp1.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.data_disk.with_live_migration.during_bg_test: PASS (379.34 s)
 (6/6) smp_16.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win7.i386.sp1.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.data_disk.with_live_migration.after_bg_test: PASS (407.98 s)

**Comment by suqinhuang** [comment]
1. find the id is old, do we still need this case
2. we'd better have a check, how many migration cases will be run in whql test. which need to run with multi-host, which can be run with local host. as we almost give up the code of local host migration, except some basic test

**Comment by CongLi** [comment]
Hi shuang,

According to the owner, this case is still needed and localhost is fine.

**Comment by pingl2016** [comment]
Acked-by: Ping Li \<pingl@redhat.com\>
'073-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.virtio_storage_in_use.with_block.system_disk.with_live_migration.before_bg_test' Finshed 2016-11-30 03:26:39 2016-11-30 03:31:35 PASS 295.54897
'074-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.virtio_storage_in_use.with_block.system_disk.with_live_migration.during_bg_test' Finshed 2016-11-30 03:31:35 2016-11-30 03:36:25 PASS 289.300772
'075-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.virtio_storage_in_use.with_block.system_disk.with_live_migration.after_bg_test' Finshed 2016-11-30 03:36:25 2016-11-30 03:41:32 PASS 307.179608
'088-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.virtio_storage_in_use.with_block.data_disk.with_live_migration.before_bg_test' Finshed 2016-11-30 04:39:39 2016-11-30 04:44:35 PASS 295.999541
'089-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.virtio_storage_in_use.with_block.data_disk.with_live_migration.during_bg_test' Finshed 2016-11-30 04:44:35 2016-11-30 04:48:54 PASS 259.166349
'090-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.virtio_storage_in_use.with_block.data_disk.with_live_migration.after_bg_test' Finshed 2016-11-30 04:48:54 2016-11-30 04:54:00 PASS 305.846889
'103-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.system_disk.with_live_migration.before_bg_test' Finshed 2016-11-30 05:50:33 2016-11-30 05:55:28 PASS 294.885751
'104-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.system_disk.with_live_migration.during_bg_test' Finshed 2016-11-30 05:55:28 2016-11-30 05:59:53 PASS 265.348966
'105-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.system_disk.with_live_migration.after_bg_test' Finshed 2016-11-30 05:59:54 2016-11-30 06:04:47 PASS 293.311846
'118-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.data_disk.with_live_migration.before_bg_test' Finshed 2016-11-30 07:02:44 2016-11-30 07:07:21 PASS 276.725384
'119-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.data_disk.with_live_migration.during_bg_test' Finshed 2016-11-30 07:07:21 2016-11-30 07:11:42 PASS 261.254737
'120-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.data_disk.with_live_migration.after_bg_test' Finshed 2016-11-30 07:11:42 2016-11-30 07:16:54 PASS 311.082738

**Comment by aliang123** [comment]
Test Result:
13-smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.Win2008.x86_64.r2.io-github-autotest-qemu.virtio_storage_in_use.with_block.system_disk.with_live_migration.before_bg_test' Finshed 2016-11-30 20:16:04 2016-11-30 20:21:15 PASS 310.717861
'14-smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.Win2008.x86_64.r2.io-github-autotest-qemu.virtio_storage_in_use.with_block.system_disk.with_live_migration.during_bg_test' Finshed 2016-11-30 20:21:15 2016-11-30 20:26:24 PASS 308.931342
'15-smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.Win2008.x86_64.r2.io-github-autotest-qemu.virtio_storage_in_use.with_block.system_disk.with_live_migration.after_bg_test' Finshed 2016-11-30 20:26:24 2016-11-30 20:31:53 PASS 329.325716
'28-smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.Win2008.x86_64.r2.io-github-autotest-qemu.virtio_storage_in_use.with_block.data_disk.with_live_migration.before_bg_test' Finshed 2016-11-30 21:45:42 2016-11-30 21:51:08 PASS 326.039438
'29-smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.Win2008.x86_64.r2.io-github-autotest-qemu.virtio_storage_in_use.with_block.data_disk.with_live_migration.during_bg_test' Finshed 2016-11-30 21:51:08 2016-11-30 21:57:05 PASS 357.184122
'30-smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.Win2008.x86_64.r2.io-github-autotest-qemu.virtio_storage_in_use.with_block.data_disk.with_live_migration.after_bg_test' Finshed 2016-11-30 21:57:05 2016-11-30 22:02:48 PASS 343.4044
'43-smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.Win2008.x86_64.r2.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.system_disk.with_live_migration.before_bg_test' Finshed 2016-11-30 23:15:19 2016-11-30 23:20:28 PASS 308.888609
'44-smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.Win2008.x86_64.r2.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.system_disk.with_live_migration.during_bg_test' Finshed 2016-11-30 23:20:28 2016-11-30 23:26:30 PASS 362.150829
'45-smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.Win2008.x86_64.r2.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.system_disk.with_live_migration.after_bg_test' Finshed 2016-11-30 23:26:30 2016-11-30 23:31:53 PASS 322.508633
'58-smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.Win2008.x86_64.r2.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.data_disk.with_live_migration.before_bg_test' Finshed 2016-12-01 00:49:15 2016-12-01 00:54:35 PASS 319.628172
'59-smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.Win2008.x86_64.r2.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.data_disk.with_live_migration.during_bg_test' Finshed 2016-12-01 00:54:35 2016-12-01 01:00:05 PASS 329.531981
'60-smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.Win2008.x86_64.r2.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.data_disk.with_live_migration.after_bg_test' Finshed 2016-12-01 01:00:05 2016-12-01 01:06:20 PASS 375.433324

Test cmd:
    python ConfigTest.py --guestname=Win2008..r2 --platform=x86_64 --testcase=virtio_storage_in_use --verbose=yes

**Comment by xutian** [comment]
LGTM

**Pull request merged**
