### PR TITLE
pre and post command: Make them can be combined correctly

### PR DESCRIPTION
**Pull request by yanan-fu**
id: 1631619
Signed-off-by: Yanan Fu <yfu@redhat.com>

### CODE REVIEW

**Comment by vivianQizhu** [comment]
@yanan-fu What about add `;` before `+= ''`, this might requires smaller scale change.

**Comment by yanan-fu** [comment]
@vivianQizhu  we can use `;` at the begining of `+=`, because  pre_command may be empty, then
`; new_command`  can be execute.

**Comment by vivianQizhu** [comment]
@yanan-fu Right, and `command &&` without later command added will cause failure too, so your current solution seems to be the most proper one.

**Comment by yanan-fu** [comment]
Assume, `pre_command = "a; b; c;"`
The return value of the `pre_command` above is the return value of the last command `c`
This is not what we want.
Close this PR, to find better solution.

**Pull request closed without merging**
