### PR TITLE
tp-qemu: module_probe.py: Update module name under avocado.

### PR DESCRIPTION
**Pull request by CongSmile**
Signed-off-by: Cong Li <coli@redhat.com>

id: 1328710

### CODE REVIEW

**Comment by CongSmile** [comment]
PASS smp_8.2048m.repeat1.post_check.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.check_coredump

**Comment by CongSmile** [comment]
@ngu-niny  Could you help review this one?

Thanks.

**Comment by PandaWei** [comment]
Do you consider the user who still use autotest?
We'd better to keep compatibility in mind.

**Comment by xutian** [comment]
Ok let's do it like:
`try`
`    from autotest.client import utils as linux_modules`
`except ImportError:`
`    from avocado.utils import linux_modules`

**Comment by PandaWei** [comment]
@xutian @CongSmile 
I noticed that qemu/tests/hotplug_mem.py fixed the similar problem and gave higher priority to avocado than autotest.  So i suggest we keep consistent with it and give higher priority to avocado for all of importing module.


PS, Formerly I spent most of my energy on tp-libvirt.
Now I turn to tp-qemu.
You‘re very active on tp-qemu, I'm happy to work with you together.

**Comment by CongSmile** [comment]
@PandaWei @xutian 

Thanks for your helpful and kindly suggestions.
I will consider compatibility in the future.

And it's great to work together with you. :)

Thanks.

**Comment by ngu-niny** [comment]
Acked-by: Nini Gu <ngu@redhat.com>

Now the script work well:

16:03:12 DEBUG| [stdout] 50
16:03:12 INFO | Running 'echo 5000 > /sys/kernel/mm/ksm/pages_to_scan'
16:03:12 INFO | Running 'echo 1 > /sys/kernel/mm/ksm/run'
16:03:12 INFO | Running 'echo 50 > /sys/kernel/mm/ksm/sleep_millisecs'
16:03:13 INFO | PASS smp_8.8192m.repeat1.run_test.Host_RHEL.m6.u8.qcow2.virtio_blk.up.virtio_net.Win2012.x86_64.r2.io-github-autotest-qemu.module_probe
16:03:13 INFO |

**Comment by xutian** [comment]
@PandaWei  any comments?

Thanks,
Xu

**Comment by maxujun** [comment]
Acked-by: xuma@redhat.com
LGTM

**Comment by xutian** [comment]
looks fine. merged thanks @CongSmile @PandaWei @ngu-niny  and @maxujun

**Pull request merged**
