### PR TITLE
trim_support_test:disable luks format for trim feature

### PR DESCRIPTION
**Pull request by qingwangrh**
ID:2048013
Signed-off-by: qingwangrh <qinwang@redhat.com>

### CODE REVIEW

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=trim_support_test --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=Win2016 --driveformat=virtio_scsi --nicmodel=virtio_net --imageformat=luks,qcow2 --machines=i440fx --customsparams="vm_mem_limit = 12G\nimage_aio=threads\ncd_format=ide" --clone=no
(1/1) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.trim_support_test: PASS (129.29 s)

**Comment by qingwangrh** [comment]
@YongxueHong @peixiu Please help to review.thanks

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by peixiu** [comment]
(1/1) Host_RHEL.m.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.trim_support_test: STARTED
| (1/1) Host_RHEL.m.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.trim_support_test: PASS (502.90 s)

LGTM~

**Review by peixiu — APPROVED** [review]

**Pull request merged**
