### PR TITLE
Get sgx-epc size only from the current boot journal

### PR DESCRIPTION
**Pull request by zixi-chen**
ID: 2599

### CODE REVIEW

**Comment by zixi-chen** [comment]
Add --boot only shows the current boot msg.
# journalctl|grep -i 'sgx: EPC section'
 kernel: sgx: EPC section 0x7e03000000-0x7fff3fdfff
 kernel: sgx: EPC section 0xfe03000000-0xffffffffff
 kernel: sgx: EPC section 0x7e03000000-0x7fff3fdfff
 kernel: sgx: EPC section 0xfe03000000-0xffffffffff
 kernel: sgx: EPC section 0x7e03000000-0x7fff3fdfff
 kernel: sgx: EPC section 0xfe03000000-0xffffffffff
 kernel: sgx: EPC section 0x7e03000000-0x7fff3fdfff
 kernel: sgx: EPC section 0xfe03000000-0xffffffffff
# journalctl --boot|grep -i 'sgx: EPC section'
 kernel: sgx: EPC section 0x7e03000000-0x7fff3fdfff
 kernel: sgx: EPC section 0xfe03000000-0xffffffffff

**Comment by zixi-chen** [comment]
(1/4) Host_RHEL.x86_64.io-github-autotest-qemu.sgx_basic.without_numa.single_epc.q35: STARTED
 (1/4) Host_RHEL.x86_64.io-github-autotest-qemu.sgx_basic.without_numa.single_epc.q35: PASS (101.42 s)
 (2/4) Host_RHEL.x86_64.io-github-autotest-qemu.sgx_basic.without_numa.multi_epc.q35: STARTED
 (2/4) Host_RHEL.x86_64.io-github-autotest-qemu.sgx_basic.without_numa.multi_epc.q35: PASS (100.66 s)
 (3/4) Host_RHEL.x86_64.io-github-autotest-qemu.sgx_basic.with_numa.single_epc.q35: STARTED
 (3/4) Host_RHEL.x86_64.io-github-autotest-qemu.sgx_basic.with_numa.single_epc.q35: PASS (97.82 s)
 (4/4) Host_RHEL.x86_64.io-github-autotest-qemu.sgx_basic.with_numa.multi_epc.q35: STARTED
 (4/4) Host_RHEL.x86_64.io-github-autotest-qemu.sgx_basic.with_numa.multi_epc.q35: PASS (98.45 s)
@zhencliu @XueqiangWei Could you please help to review this patch?

**Review by zhencliu — APPROVED** [review]

**Comment by XueqiangWei** [comment]
@zixi-chen the commit signature verification has been enabled, please re-push it with -S. Thanks.

**Comment by zixi-chen** [comment]
> @zixi-chen the commit signature verification has been enabled, please re-push it with -S. Thanks.

Thanks @XueqiangWei , updated signiture.

**Review by XueqiangWei — APPROVED** [review]
LGTM,
Acked-by: xuwei@redhat.com

**Pull request merged**
