### PR TITLE
rng_driver: re-locate variable 'rng_driver' to add Windows guest support

### PR DESCRIPTION
**Pull request by ybduan**
ID: 2128588
Signed-off-by: ybduan <yduan@redhat.com>

### CODE REVIEW

**Comment by ybduan** [comment]
1-Host_RHEL.m9.u2.ovmf.virtio_rng.rng_builtin.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.rng_hotplug.multi_rngs.q35 Finshed 2022-09-21 04:45:51 2022-09-21 04:50:07 PASS 256.161891
2-Host_RHEL.m9.u2.ovmf.virtio_rng.rng_builtin.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.rng_hotplug.one_rng.q35 Finshed 2022-09-21 04:50:08 2022-09-21 04:53:29 PASS 200.965466
3-Host_RHEL.m9.u2.ovmf.virtio_rng.rng_builtin.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.rng_hotplug.one_rng.with_reboot.q35 Finshed 2022-09-21 04:53:31 2022-09-21 05:01:21 PASS 469.915597
4-Host_RHEL.m9.u2.ovmf.virtio_rng.rng_builtin.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.rng_hotplug.one_rng.with_system_reset.q35 Finshed 2022-09-21 05:01:22 2022-09-21 05:08:24 PASS 421.947294
5-Host_RHEL.m9.u2.ovmf.virtio_rng.rng_builtin.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.rng_hotplug.one_rng.with_shutdown_after_unplug.q35 Finshed 2022-09-21 05:08:25 2022-09-21 05:11:43 PASS 198.061846
6-Host_RHEL.m9.u2.ovmf.virtio_rng.rng_builtin.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.rng_hotplug.one_rng.with_shutdown_after_plug.q35 Finshed 2022-09-21 05:11:44 2022-09-21 05:14:43 PASS 179.147049
7-Host_RHEL.m9.u2.ovmf.virtio_rng.rng_builtin.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.rng_hotplug.repeat_in_loop.q35 Finshed 2022-09-21 05:14:45 2022-09-21 05:57:34 PASS 2569.058405
Summary: 
Finshed=7, PASS=7
1-Host_RHEL.m9.u2.ovmf.virtio_rng.rng_builtin.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.rng_stress.two_device.q35 Finshed 2022-09-21 06:50:15 2022-09-21 06:52:52 PASS 157.213343
2-Host_RHEL.m9.u2.ovmf.virtio_rng.rng_builtin.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.rng_stress.one_device.q35 Finshed 2022-09-21 06:52:53 2022-09-21 06:55:29 PASS 155.103073
Summary: 
Finshed=2, PASS=2

**Comment by ybduan** [comment]
Please help review this PR, thanks! @yanan-fu

**Comment by yanan-fu** [comment]
@BohdanMar  FYI, x86 is different with s390x, it support Linux and Windows, please be aware of this kind of problem, thanks!  cc @PaulYuuu  :)

**Review by yanan-fu — APPROVED** [review]
Acked-by: Yanan Fu <yfu@redhat.com>

**Comment by yanan-fu** [comment]
@PaulYuuu  Could you help review ? Thanks!

**Review by PaulYuuu — APPROVED** [review]

**Comment by yanan-fu** [comment]
Thanks all!

**Comment by BohdanMar** [comment]
@yanan-fu Okay, got it, thank you for the info

**Pull request merged**
