### PR TITLE
blockdev_inc_backup_bitmap_with_granularity: bitmap granularity test

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1907816

### CODE REVIEW

**Comment by zhencliu** [comment]
local fs:
(1/3) type_specific.io-github-autotest-qemu.blockdev_inc_backup_bitmap_with_granularity.granularity_512: PASS (85.26 s)
 (2/3) type_specific.io-github-autotest-qemu.blockdev_inc_backup_bitmap_with_granularity.granularity_2G:PASS (81.95 s)
 (3/3) type_specific.io-github-autotest-qemu.blockdev_inc_backup_bitmap_with_granularity.granularity_between_512_2G: PASS (82.44 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-15T07.53-44ffa74/results.html
JOB TIME   : 252.78 s
iscsi-direct + virtio-blk:
(1/3) type_specific.io-github-autotest-qemu.blockdev_inc_backup_bitmap_with_granularity.granularity_512: PASS (83.63 s)
 (2/3) type_specific.io-github-autotest-qemu.blockdev_inc_backup_bitmap_with_granularity.granularity_2G:PASS (87.98 s)
 (3/3) type_specific.io-github-autotest-qemu.blockdev_inc_backup_bitmap_with_granularity.granularity_between_512_2G: PASS (85.50 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-15T09.34-9f01e6c/results.html
JOB TIME   : 260.31 s
nbd:
(1/3) type_specific.io-github-autotest-qemu.blockdev_inc_backup_bitmap_with_granularity.granularity_512: PASS (219.41 s)
 (2/3) type_specific.io-github-autotest-qemu.blockdev_inc_backup_bitmap_with_granularity.granularity_2G:PASS (223.02 s)
 (3/3) type_specific.io-github-autotest-qemu.blockdev_inc_backup_bitmap_with_granularity.granularity_between_512_2G: PASS (242.76 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-15T09.41-5e86494/results.html
JOB TIME   : 688.62 s

ceph:
 (1/3) type_specific.io-github-autotest-qemu.blockdev_inc_backup_bitmap_with_granularity.granularity_512: PASS (108.29 s)
 (2/3) type_specific.io-github-autotest-qemu.blockdev_inc_backup_bitmap_with_granularity.granularity_2G:PASS (96.87 s)
 (3/3) type_specific.io-github-autotest-qemu.blockdev_inc_backup_bitmap_with_granularity.granularity_between_512_2G: PASS (105.41 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-15T09.54-6f4914e/results.html
JOB TIME   : 313.69 s

**Comment by zhencliu** [comment]
hi @YongxueHong @ngu-niny , can you please help to review this patch? Thanks.
it deps on #2547

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by ngu-niny** [comment]
Test PASS and LGTM:

PASS 12-Host_RHEL.m8.u4.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_bitmap_with_granularity.granularity_512
PASS 13-Host_RHEL.m8.u4.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_bitmap_with_granularity.granularity_2G
PASS 14-Host_RHEL.m8.u4.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_bitmap_with_granularity.granularity_between_512_2G

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
