### PR TITLE
Sendbuf test for macvtap

### PR DESCRIPTION
**Pull request by yanglei-rh**
ID:1867953

Signed-off-by: Lei Yang <leiyang@redhat.com>

### CODE REVIEW

**Comment by yanglei-rh** [comment]
@PaulYuuu @huangyum Please help me review it.thanks.

**Comment by PaulYuuu** [comment]
"macvtap" and "bridge" should be a nettype of test matrix. I recommend testing `virtual_nic.send_buffer` directly if there has not specific macvtap checkpoint.

**Comment by yanglei-rh** [comment]
@PaulYuuu Thanks for your advice. If other macvtap cases have the same situation。 Can I take the same method to add related test cases name to the test loop of macvtap?

**Comment by PaulYuuu** [comment]
> @PaulYuuu Thanks for your advice. If other macvtap cases have the same situation。 Can I take the same method to add related test cases name to the test loop of macvtap?

I think so. Most test cases should pass because "macvtap" just a type of network. If we have some checkpoint of macvtap like vepa, we can develop a new case for it.
You can have a try at first.

**Comment by huangyum** [comment]
Agree with @PaulYuuu. The configure is same to virtual_nic.send_buffer except nettype. We don't need a new cfg for that.

**Comment by yanglei-rh** [comment]
@PaulYuuu @huangyum Thanks for your review, "virtual_nic.send_buffer" can match the test requirements.So i will close this patch and add "virtual_nic.send_buffer" to the macvtap loop.

**Pull request closed without merging**
