### PR TITLE
tpm_unattended_install: New case to test unattended install with tpm

### PR DESCRIPTION
**Pull request by YongxueHong**
ID: 1861269

Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by YongxueHong** [comment]
Depends on https://github.com/avocado-framework/avocado-vt/pull/2673

**Comment by YongxueHong** [comment]
hi @vivianQizhu @qcheng-redhat
Could you help me to review, thanks.
cc @CongLi

**Comment by qcheng-redhat** [comment]
Please add send_key_at_install = ret in .cfg for windows guests, then we could start installation automatically.

**Comment by YongxueHong** [comment]
> Please add send_key_at_install = ret in .cfg for windows guests, then we could start installation automatically.

Hi @qcheng-redhat 
have updated.
Thanks.

**Comment by YongxueHong** [comment]
Hi @ngu-niny 
Please help me to review, thanks.

**Comment by YongxueHong** [comment]
hi @vivianQizhu @qcheng-redhat @ngu-niny 
Could you help me to review, thanks.
cc @CongLi

**Comment by qcheng-redhat** [comment]
LGTM. 

python3 ConfigTest.py --platform=x86_64 --guestname=Win10,Win2016,Win2019 --testcase=tpm_unattended_install --machine=q35 --firmware=ovmf --customsparams=cdrom_virtio=isos/windows/virtio-win-1.9.12-2.el8.iso

 (1/3) Host_RHEL.m8.u3.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.tpm_unattended_install.q35: PASS (910.56 s)
 (2/3) Host_RHEL.m8.u3.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.tpm_unattended_install.q35: PASS (713.33 s)
 (3/3) Host_RHEL.m8.u3.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.tpm_unattended_install.q35: PASS (872.28 s)

python3 ConfigTest.py --platform=x86_64 --guestname=RHEL.8.3.0,RHEL.8.2.1 --testcase=tpm_unattended_install --machine=q35 --firmware=ovmf --customsparams="cdrom_cd1=isos/linux/edk2-secureboot-signed.iso"

 (1/2) Host_RHEL.m8.u3.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.1.x86_64.io-github-autotest-qemu.tpm_unattended_install.q35: PASS (1473.49 s)
 (2/2) Host_RHEL.m8.u3.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.tpm_unattended_install.q35: PASS (1782.77 s)

**Comment by YongxueHong** [comment]
hi @ngu-niny
Could you help me to review, thanks.

**Comment by ngu-niny** [comment]
@YongxueHong 

The test on ppc failed for couldn't get IP issue when booting up the guest after installation, please help to have a check:

07:59:50 ERROR| Can't get guest network status information, reason: Login timeout expired    (output: '\x07')
07:59:50 ERROR|
07:59:50 ERROR| Reproduced traceback from: /home/ngu/kar/workspace/avocado-vt/avocado_vt/test.py:442
07:59:50 ERROR| Traceback (most recent call last):
07:59:50 ERROR|   File "/home/ngu/kar/workspace/avocado-vt/virttest/error_context.py", line 135, in new_fn
07:59:50 ERROR|     return fn(*args, **kwargs)
07:59:50 ERROR|   File "/home/ngu/kar/workspace/var/lib/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/tpm_unattended_install.py", line 49, in run
07:59:50 ERROR|     session = vm.wait_for_login()
07:59:50 ERROR|   File "/home/ngu/kar/workspace/avocado-vt/virttest/virt_vm.py", line 1196, in wait_for_login
07:59:50 ERROR|     ip_version=self.ip_version)
07:59:50 ERROR|   File "/home/ngu/kar/workspace/avocado-vt/virttest/error_context.py", line 135, in new_fn
07:59:50 ERROR|     return fn(*args, **kwargs)
07:59:50 ERROR|   File "/home/ngu/kar/workspace/avocado-vt/virttest/virt_vm.py", line 915, in wait_for_get_address
07:59:50 ERROR|     ipaddr = self.get_address(nic_index, ip_version)
07:59:50 ERROR|   File "/home/ngu/kar/workspace/avocado-vt/virttest/virt_vm.py", line 779, in get_address
07:59:50 ERROR|     timeout=timeout)
07:59:50 ERROR|   File "/home/ngu/kar/workspace/avocado-vt/virttest/virt_vm.py", line 822, in _get_address
07:59:50 ERROR|     raise VMIPAddressMissingError(mac, ip_version)
07:59:50 ERROR| virttest.virt_vm.VMIPAddressMissingError: No ipv4 DHCP lease for MAC 9a:ce:af:82:9f:62

**Comment by YongxueHong** [comment]
> @YongxueHong
> 
> The test on ppc failed for couldn't get IP issue when booting up the guest after installation, please help to have a check:
> 
> 07:59:50 ERROR| Can't get guest network status information, reason: Login timeout expired (output: '\x07')
> 07:59:50 ERROR|
> 07:59:50 ERROR| Reproduced traceback from: /home/ngu/kar/workspace/avocado-vt/avocado_vt/test.py:442
> 07:59:50 ERROR| Traceback (most recent call last):
> 07:59:50 ERROR| File "/home/ngu/kar/workspace/avocado-vt/virttest/error_context.py", line 135, in new_fn
> 07:59:50 ERROR| return fn(*args, **kwargs)
> 07:59:50 ERROR| File "/home/ngu/kar/workspace/var/lib/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/tpm_unattended_install.py", line 49, in run
> 07:59:50 ERROR| session = vm.wait_for_login()
> 07:59:50 ERROR| File "/home/ngu/kar/workspace/avocado-vt/virttest/virt_vm.py", line 1196, in wait_for_login
> 07:59:50 ERROR| ip_version=self.ip_version)
> 07:59:50 ERROR| File "/home/ngu/kar/workspace/avocado-vt/virttest/error_context.py", line 135, in new_fn
> 07:59:50 ERROR| return fn(*args, **kwargs)
> 07:59:50 ERROR| File "/home/ngu/kar/workspace/avocado-vt/virttest/virt_vm.py", line 915, in wait_for_get_address
> 07:59:50 ERROR| ipaddr = self.get_address(nic_index, ip_version)
> 07:59:50 ERROR| File "/home/ngu/kar/workspace/avocado-vt/virttest/virt_vm.py", line 779, in get_address
> 07:59:50 ERROR| timeout=timeout)
> 07:59:50 ERROR| File "/home/ngu/kar/workspace/avocado-vt/virttest/virt_vm.py", line 822, in _get_address
> 07:59:50 ERROR| raise VMIPAddressMissingError(mac, ip_version)
> 07:59:50 ERROR| virttest.virt_vm.VMIPAddressMissingError: No ipv4 DHCP lease for MAC 9a:ce:af:82:9f:62

Hi @ngu-niny  have fix this issue, pls help me to review it again, thanks.

**Comment by ngu-niny** [comment]
Test PASS on ppc:

 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.tpm_unattended_install: PASS (1554.39 s)

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
