### PR TITLE
cgroup: Fix blkio_throttle_read/write limitation's issues

### PR DESCRIPTION
**Pull request by xiangchunfu**
As dd transfer unit is bytes, But blkio throttle unit is K.
So convert bytes to K for dd transfer data. and modifying limit values.

id: 1766114

Signed-off-by: Xiangchun Fu <xfu@redhat.com>

### CODE REVIEW

**Comment by xiangchunfu** [comment]
(1/1) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.cgroup.blkio_throttle_multi: PASS (345.50 s)

**Comment by vivianQizhu** [comment]
@xiangchunfu Where is the convert and why change the limitation?

**Comment by xiangchunfu** [comment]
Updated, Don't change limitation.  Actual speed don't exceed default speed.

**Comment by xiangchunfu** [comment]
'1-Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.cgroup.blkio_throttle' Finshed 2020-01-09 10:43:17 2020-01-09 10:46:37 PASS

**Pull request merged**
