### PR TITLE
qemu_img:Reduce the cycle interval time and add dd step

### PR DESCRIPTION
**Pull request by zhenyzha**
Due to the process completion time being too fast, 
Reduce the cycle interval time and add dd step.

ID:2023601
Signed-off-by: Zhenyu Zhang <zhenyzha@redhat.com>

### CODE REVIEW

**Comment by zhenyzha** [comment]
` (1/1) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.aarch64.io-github-autotest-qemu.qemu_img.rebase.show_progress.show_progress_off.arm64-pci: PASS (47.01 s)
`
@hellohellenmao @YongxueHong Could you pls help review when you are free. thanks.

**Comment by zhenyzha** [comment]
` (1/1) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.aarch64.io-github-autotest-qemu.qemu_img.rebase.show_progress.show_progress_off.arm64-pci: PASS (47.37 s)`

@hellohellenmao @YongxueHong Could you pls help review when you are free. thanks.

**Comment by hellohellenmao** [comment]
Still fails, but not every time. I have tried 4 times, failed 2 times.
(1/1) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.qemu_img.rebase.show_progress.show_progress_off.q35: FAIL: Fail to get expected result!Output: b'', expected pattern: \(\d+\.\d+/100%\) (2.29 s)

**Comment by zhenyzha** [comment]
` (1/1) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.aarch64.io-github-autotest-qemu.qemu_img.rebase.show_progress.show_progress_off.arm64-pci: PASS (140.94 s)`

@hellohellenmao @YongxueHong Could you pls help review when you are free. thanks.

**Comment by hellohellenmao** [comment]
Changed 2 machines and tried 5 times, all passed.
(1/1) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qemu_img.rebase.show_progress.show_progress_off.q35: PASS (94.05 s)

Ack from my side.  Thanks.

**Comment by YongxueHong** [comment]
Hi @zhencliu
Can you help to review it?

**Comment by zhenyzha** [comment]
```
 (1/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qemu_img.rebase.unsafe: PASS (62.49 s)
 (2/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qemu_img.rebase.show_progress.show_progress_on: PASS (93.92 s)
 (3/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qemu_img.rebase.show_progress.show_progress_off: PASS (91.99 s)
```

@hellohellenmao @zhencliu Could you pls help review when you are free. thanks.

**Comment by hellohellenmao** [comment]
Ack from my side.

 (02/17) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qemu_img_negative.rebase.nonexist_new_backing_file.q35: PASS (2.10 s)
 (03/17) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qemu_img.rebase.unsafe.q35: PASS (63.64 s)
 (04/17) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qemu_img.rebase.show_progress.show_progress_on.q35: PASS (95.94 s)
 (05/17) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qemu_img.rebase.show_progress.show_progress_off.q35: PASS (93.11 s)
 (06/17) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qemu_disk_img.rebase.snB.to_base.q35: PASS (205.93 s)
 (07/17) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qemu_disk_img.rebase.snB.to_base.cache_mode.none.q35: PASS (197.53 s)
 (08/17) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qemu_disk_img.rebase.snB.to_base.cache_mode.writeback.q35: PASS (196.14 s)
 (09/17) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qemu_disk_img.rebase.snB.to_base.cache_mode.unsafe.q35: PASS (195.74 s)
 (10/17) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qemu_disk_img.rebase.snB.to_base.cache_mode.directsync.q35: PASS (200.85 s)
 (11/17) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qemu_disk_img.rebase.snB.to_base.cache_mode.writethrough.q35: PASS (196.83 s)
 (12/17) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qemu_disk_img.rebase.snB.to_null.q35: PASS (226.67 s)
 (13/17) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qemu_disk_img.rebase.snC.to_base.q35: PASS (258.73 s)
 (14/17) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qemu_disk_img.rebase.snC.to_new.q35: PASS (281.51 s)
 (15/17) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qemu_disk_img.rebase.snC.to_new.restore_to_snB.q35: PASS (335.96 s)
 (16/17) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qemu_disk_img.rebase.snD.to_snB_snA_base.q35: PASS (412.70 s)
 (17/17) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.image_rebase_bypass_host_cache.q35: PASS (138.08 s)

**Comment by zhencliu** [comment]
We might also hit the error that qemu-img stops when sending a signal on the host with high IO performance, i.e. rebase is done in less than 0.1s.

An easy way is to introduce a param for this test scenario in cfg, e.g. dd_file_size=1024, which means a 1G file, for other test scenarios, use the default one (i.e. 1M file size), then I think it's not so easy to rebase 2G content in less than 0.1s. 

Just fyi. Your code change is still OK for me.

LGTM

**Comment by zhenyzha** [comment]
> We might also hit the error that qemu-img stops when sending a signal on the host with high IO performance, i.e. rebase is done in less than 0.1s.
> 
> An easy way is to introduce a param for this test scenario in cfg, e.g. dd_file_size=1024, which means a 1G file, for other test scenarios, use the default one (i.e. 1M file size), then I think it's not so easy to rebase 2G content in less than 0.1s.
> 
> Just fyi. Your code change is still OK for me.
> 
> LGTM

You are right, considering that the performance of the machine will get higher and higher in the future, we can add a parameter interface.
Thank you very much, update later.

**Comment by zhenyzha** [comment]
```
 (1/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.qemu_img.rebase.show_progress.show_progress_on.arm64-pci: PASS (289.30 s)
 (2/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.qemu_img.rebase.show_progress.show_progress_off.arm64-pci: PASS (290.08 s)
```

@hellohellenmao @zhencliu Could you pls help review when you are free. thanks.

**Comment by zhencliu** [comment]
LGTM

**Comment by hellohellenmao** [comment]
Ack. 

(1/1) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qemu_img.rebase.show_progress.show_progress_off.q35: PASS (98.89 s)
(1/1) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qemu_img.convert.to_qcow2.show_progress.show_progress_off.q35: PASS

**Pull request merged**
