### PR TITLE
usb_storage: add support for testing usb-storage under usb-hub

### PR DESCRIPTION
**Pull request by ybduan**
ID: 1802010
Signed-off-by: ybduan <yduan@redhat.com>

### CODE REVIEW

**Comment by ybduan** [comment]
Based on https://github.com/avocado-framework/avocado-vt/pull/2454

**Comment by ybduan** [comment]
Please help review this PR, thanks! @XueqiangWei

**Comment by XueqiangWei** [comment]
(01/13) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.usb.usb_storage.without_usb_hub.piix3-uhci.q35: PASS (658.91 s)
 (02/13) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.usb.usb_storage.without_usb_hub.piix4-uhci.q35: PASS (668.44 s)
 (03/13) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.usb.usb_storage.without_usb_hub.ich9-uhci.q35: PASS (648.40 s)
 (04/13) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.usb.usb_storage.without_usb_hub.ich9-ehci.q35: PASS (676.77 s)
 (05/13) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.usb.usb_storage.without_usb_hub.usb-ehci.q35: PASS (673.03 s)
 (06/13) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.usb.usb_storage.without_usb_hub.nec-xhci.q35: PASS (641.01 s)
 (07/13) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.usb.usb_storage.without_usb_hub.qemu-xhci.q35: PASS (640.10 s)
 (08/13) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.usb.usb_storage.with_usb_hub.one_usb_dev.piix3-uhci.q35: PASS (657.13 s)
 (09/13) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.usb.usb_storage.with_usb_hub.one_usb_dev.piix4-uhci.q35: PASS (727.79 s)
 (10/13) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.usb.usb_storage.with_usb_hub.one_usb_dev.ich9-uhci.q35: PASS (660.52 s)
 (11/13) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.usb.usb_storage.with_usb_hub.one_usb_dev.ich9-ehci.q35: PASS (666.60 s)
 (12/13) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.usb.usb_storage.with_usb_hub.one_usb_dev.nec-xhci.q35: PASS (647.78 s)
 (13/13) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.usb.usb_storage.with_usb_hub.one_usb_dev.qemu-xhci.q35: PASS (696.75 s)

**Comment by XueqiangWei** [comment]
LGTM,
Acked-by: xuwei@redhat.com

**Comment by ybduan** [comment]
Please help review this PR, thanks! @lolyu

**Pull request merged**
