### PR TITLE
virtio_fs: remove generic/263 from xfstest

### PR DESCRIPTION
**Pull request by xiagao**
virtiofs doesn't support it.
ID: 1744

### CODE REVIEW

**Comment by xiagao** [comment]
@zhenyzha @fbq815  Could you please help review this patch?

**Comment by zhenyzha** [comment]
Applying: virtio_fs: remove generic/263 from xfstest

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Review by zhenyzha — APPROVED** [review]

**Comment by zhenyzha** [comment]
@SiboWang1997 Could you pls help review when you are free. thanks.

**Comment by SiboWang1997** [comment]
I have a consideration, should we also remove  generic/263 from xfstest with multi_backend? Or just remove in this case.

**Comment by xiagao** [comment]
> I have a consideration, should we also remove generic/263 from xfstest with multi_backend? Or just remove in this case.

Seems that it passed on virtiofs on top of NFS.

**Comment by SiboWang1997** [comment]
xfstests+xfs:
`[stdlog] generic/263       [expunged]`
xfstesets+nfs:
`[stdlog] generic/263        1s`

LGTM
Acked-by: Sibo Wang [siwang@redhat.com](mailto:siwang@redhat.com)

**Comment by xiagao** [comment]
@YongxueHong Could you help review this patch?

**Comment by fbq815** [comment]
- with_xfstest:
    no s390 s390x
    generic_blacklist = 'generic/003\ngeneric/120\ngeneric/426\ngeneric/467\ngeneric/477\ngeneric/551\n'
Since the code above, ignore s390x for this patch

**Comment by xiagao** [comment]
@YongxueHong Could you help review this patch?

**Comment by xiagao** [comment]
Updated @YongxueHong

**Review by YongxueHong — APPROVED** [review]

**Pull request merged**
