### PR TITLE
throttle_operation_test:change warn message to info

### PR DESCRIPTION
**Pull request by qingwangrh**
BZ:2072863,2073317
Signed-off-by: qingwangrh <qinwang@redhat.com>

### CODE REVIEW

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=throttle_operation_test.group_change.to_burst --guestname=RHEL.9.0.0 --machines=q35 --clone=no

(1/1) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.throttle_operation_test.group_change.to_burst.q35: STARTED
- (1/1) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.throttle_operation_test.group_change.to_burst.q35: PASS (362.73 s)

**Comment by qingwangrh** [comment]
@YongxueHong @zhenyzha Please help to review ,thanks.

**Comment by zhenyzha** [comment]
```
/ (01/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.bps_non_4k.arm64-pci:
PASS (335.08 s)
 (02/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.bps_iops.arm64-pci: STA
RTED
/ (02/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.bps_iops.arm64-pci: PA
SS (259.14 s)
 (03/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.to_burst.arm64-pci: STA
RTED
- (03/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.to_burst.arm64-pci: PA
SS (396.02 s)
 (04/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.to_empty.arm64-pci: STA
RTED
- (04/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.to_empty.arm64-pci: WARN: Test passed but there were warnings during execution. Check the log for details. (270.87 s)
 (05/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_move.to_normal.arm64-pci: STARTED
/ (05/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_move.to_normal.arm64-pci: PASS (198.22 s)
 (06/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_move.to_burst.arm64-pci: STARTED
/ (06/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_move.to_burst.arm64-pci: PASS (255.53 s)
 (07/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_reboot.arm64-pci: STARTED
| (07/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_reboot.arm64-pci: PASS (313.87 s)
 (08/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_stop_resume.arm64-pci: STARTED
/ (08/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_stop_resume.arm64-pci: PASS (268.08 s)
 (09/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_hotplug.arm64-pci: STARTED
| (09/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_hotplug.arm64-pci: PASS (273.92 s)
 (10/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.negative.wrong_value.arm64-pci: STARTED
- (10/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.negative.wrong_value.arm64-pci: PASS (257.25 s)
 (11/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.negative.wrong_option.arm64-pci: STARTED
/ (11/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.negative.wrong_option.arm64-pci: PASS (262.34 s)
 (12/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_snapshot.normal.arm64-pci: STARTED
\ (12/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_snapshot.normal.arm64-pci: PASS (253.26 s)
 (13/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_snapshot.burst.arm64-pci: STARTED
/ (13/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_snapshot.burst.arm64-pci: PASS (312.80 s)

```

Looks like the same issue here:
https://github.com/autotest/tp-qemu/blob/master/provider/throttle_utils.py#L352

**Comment by zhenyzha** [comment]
```
/ (01/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.bps_non_4k.arm64-pci:
PASS (335.08 s)
 (02/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.bps_iops.arm64-pci: STA
RTED
/ (02/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.bps_iops.arm64-pci: PA
SS (259.14 s)
 (03/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.to_burst.arm64-pci: STA
RTED
- (03/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.to_burst.arm64-pci: PA
SS (396.02 s)
 (04/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.to_empty.arm64-pci: STA
RTED
- (04/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.to_empty.arm64-pci: WARN: Test passed but there were warnings during execution. Check the log for details. (270.87 s)
 (05/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_move.to_normal.arm64-pci: STARTED
/ (05/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_move.to_normal.arm64-pci: PASS (198.22 s)
 (06/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_move.to_burst.arm64-pci: STARTED
/ (06/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_move.to_burst.arm64-pci: PASS (255.53 s)
 (07/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_reboot.arm64-pci: STARTED
| (07/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_reboot.arm64-pci: PASS (313.87 s)
 (08/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_stop_resume.arm64-pci: STARTED
/ (08/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_stop_resume.arm64-pci: PASS (268.08 s)
 (09/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_hotplug.arm64-pci: STARTED
| (09/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_hotplug.arm64-pci: PASS (273.92 s)
 (10/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.negative.wrong_value.arm64-pci: STARTED
- (10/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.negative.wrong_value.arm64-pci: PASS (257.25 s)
 (11/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.negative.wrong_option.arm64-pci: STARTED
/ (11/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.negative.wrong_option.arm64-pci: PASS (262.34 s)
 (12/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_snapshot.normal.arm64-pci: STARTED
\ (12/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_snapshot.normal.arm64-pci: PASS (253.26 s)
 (13/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_snapshot.burst.arm64-pci: STARTED
/ (13/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_snapshot.burst.arm64-pci: PASS (312.80 s)

```

Looks like the same issue here:
https://github.com/autotest/tp-qemu/blob/master/provider/throttle_utils.py#L352

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=throttle_operation_test.group_change.to_burst,throttle_operation_test.group_change.to_empty --guestname=RHEL.9.0.0 --machines=q35 --clone=no
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by qingwangrh** [comment]
> Would you like to give the explanations in the commit message? Thanks.

updated.

**Comment by qingwangrh** [comment]
> ```
> / (01/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.bps_non_4k.arm64-pci:
> PASS (335.08 s)
>  (02/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.bps_iops.arm64-pci: STA
> RTED
> / (02/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.bps_iops.arm64-pci: PA
> SS (259.14 s)
>  (03/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.to_burst.arm64-pci: STA
> RTED
> - (03/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.to_burst.arm64-pci: PA
> SS (396.02 s)
>  (04/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.to_empty.arm64-pci: STA
> RTED
> - (04/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.to_empty.arm64-pci: WARN: Test passed but there were warnings during execution. Check the log for details. (270.87 s)
>  (05/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_move.to_normal.arm64-pci: STARTED
> / (05/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_move.to_normal.arm64-pci: PASS (198.22 s)
>  (06/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_move.to_burst.arm64-pci: STARTED
> / (06/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_move.to_burst.arm64-pci: PASS (255.53 s)
>  (07/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_reboot.arm64-pci: STARTED
> | (07/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_reboot.arm64-pci: PASS (313.87 s)
>  (08/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_stop_resume.arm64-pci: STARTED
> / (08/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_stop_resume.arm64-pci: PASS (268.08 s)
>  (09/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_hotplug.arm64-pci: STARTED
> | (09/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_hotplug.arm64-pci: PASS (273.92 s)
>  (10/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.negative.wrong_value.arm64-pci: STARTED
> - (10/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.negative.wrong_value.arm64-pci: PASS (257.25 s)
>  (11/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.negative.wrong_option.arm64-pci: STARTED
> / (11/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.negative.wrong_option.arm64-pci: PASS (262.34 s)
>  (12/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_snapshot.normal.arm64-pci: STARTED
> \ (12/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_snapshot.normal.arm64-pci: PASS (253.26 s)
>  (13/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_snapshot.burst.arm64-pci: STARTED
> / (13/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_snapshot.burst.arm64-pci: PASS (312.80 s)
> ```
> 
> Looks like the same issue here on (04/13): https://github.com/autotest/tp-qemu/blob/master/provider/throttle_utils.py#L352

updated.

**Comment by zhenyzha** [comment]
LGTM.Acked-by: Zhenyu Zhang <[zhenyzha@redhat.com](mailto:zhenyzha@redhat.com)>

```
 (01/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.bps_non_4k.arm64-pci: STARTED
/ (01/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.bps_non_4k.arm64-pci: PASS (333.40 s)
 (02/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.bps_iops.arm64-pci: STARTED
- (02/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.bps_iops.arm64-pci: PASS (260.56 s)
 (03/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.to_burst.arm64-pci: STARTED
/ (03/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.to_burst.arm64-pci: PASS (395.16 s)
 (04/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.to_empty.arm64-pci: STARTED
\ (04/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_change.to_empty.arm64-pci: PASS (269.46 s)
 (05/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_move.to_normal.arm64-pci: STARTED
| (05/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_move.to_normal.arm64-pci: PASS (191.64 s)
 (06/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_move.to_burst.arm64-pci: STARTED
- (06/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.group_move.to_burst.arm64-pci: PASS (253.28 s)
 (07/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_reboot.arm64-pci: STARTED
- (07/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_reboot.arm64-pci: PASS (309.33 s)
 (08/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_stop_resume.arm64-pci: STARTED
- (08/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_stop_resume.arm64-pci: PASS (268.06 s)
 (09/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_hotplug.arm64-pci: STARTED
\ (09/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_hotplug.arm64-pci: PASS (269.52 s)
 (10/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.negative.wrong_value.arm64-pci: STARTED
| (10/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.negative.wrong_value.arm64-pci: PASS (261.74 s)
 (11/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.negative.wrong_option.arm64-pci: STARTED
| (11/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.negative.wrong_option.arm64-pci: PASS (259.45 s)
 (12/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_snapshot.normal.arm64-pci: STARTED
- (12/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_snapshot.normal.arm64-pci: PASS (256.95 s)
 (13/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_snapshot.burst.arm64-pci: STARTED
- (13/13) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.throttle_operation_test.with_snapshot.burst.arm64-pci: PASS (311.86 s)
```

**Review by zhenyzha — APPROVED** [review]

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
