### PR TITLE
x86_cpu_model: Add some -noTSX cpu models

### PR DESCRIPTION
**Pull request by huangyum**
ID: 1817806, 1817323, 1817324, 1817807, 1817326
Signed-off-by: Yumei Huang <yuhuang@redhat.com>

### CODE REVIEW

**Comment by huangyum** [comment]
(05/40) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.x86_cpu_model.Icelake-Server: CANCEL: This host doesn't support cpu model Icelake-Server (2.13 s)
 (06/40) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.x86_cpu_model.Icelake-Server-noTSX: CANCEL: This host doesn't support cpu model Icelake-Server-noTSX (2.15 s)
 (07/40) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.x86_cpu_model.Icelake-Client: CANCEL: This host doesn't support cpu model Icelake-Client (2.15 s)
 (08/40) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.x86_cpu_model.Icelake-Client-noTSX: CANCEL: This host doesn't support cpu model Icelake-Client-noTSX (2.13 s)
 (09/40) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.x86_cpu_model.Cascadelake-Server: CANCEL: This host doesn't support cpu model Cascadelake-Server (2.14 s)
 (10/40) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.x86_cpu_model.Cascadelake-Server-noTSX: CANCEL: This host doesn't support cpu model Cascadelake-Server-noTSX (2.15 s)
 (11/40) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.x86_cpu_model.Skylake-Server: PASS (49.26 s)
 (12/40) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.x86_cpu_model.Skylake-Server-noTSX: PASS (47.63 s)
 (13/40) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.x86_cpu_model.Skylake-Client: PASS (49.55 s)
 (14/40) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.x86_cpu_model.Skylake-Client-noTSX: PASS (49.12 s)
 (15/40) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.x86_cpu_model.Broadwell: PASS (49.09 s)
 (16/40) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.x86_cpu_model.Broadwell-noTSX: PASS (48.65 s)
 (17/40) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.x86_cpu_model.Haswell: PASS (47.52 s)
 (18/40) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.x86_cpu_model.Haswell-noTSX: PASS (48.10 s)

**Comment by yanan-fu** [comment]
@huangyum comment in bugzilla 1817322

**Comment by huangyum** [comment]
@yanan-fu Have updated case link in the bz.

**Comment by yanan-fu** [comment]
Acked-by: Yanan Fu <yfu@redhat.com>

**Pull request merged**
