### PR TITLE
blockdev_stream_none_existed_overlay: Stream to a non-existed snapshot

### PR DESCRIPTION
**Pull request by zhencliu**
Do block-stream to a non-existed snapshot image

Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1900975

### CODE REVIEW

**Comment by zhencliu** [comment]
iscsi direct:
 (1/1) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_none_existed_overlay.q35: PASS (30.19 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-25T10.57-b76d3aa/results.html
JOB TIME   : 32.12 s

local fs:
 (3/3) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream_none_existed_overlay.q35: PASS (79.83 s)

ceph:
 (1/1) Host_RHEL.m8.u3.product_av.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_stream_none_existed_overlay.q35: PASS (29.36 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-25T11.25-4eee3c8/results.html
JOB TIME   : 31.20 s

nbd:
 (1/1) Host_RHEL.m8.u3.product_av.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_none_existed_overlay: PASS (33.41 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-24T22.26-1066a62/results.html
JOB TIME   : 35.14 s

**Comment by zhencliu** [comment]
hi @YongxueHong  @ngu-niny , can you please help to review this patch? Thanks.

**Comment by ngu-niny** [comment]
LGTM and test PASS:

(3/3) type_specific.io-github-autotest-qemu.blockdev_stream_none_existed_overlay: PASS (33.20 s)

Acked-by: Nini Gu <ngu@redhat.com>

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
