### PR TITLE
Fix the pattern format

### PR DESCRIPTION
**Pull request by meet-lucky**
block_stream_drop_backingfile: fix encoding issue in re.search()

Signed-off-by: meet-lucky <qdong@redhat.com>

id:1640052

### CODE REVIEW

**Comment by meet-lucky** [comment]
(1/1) Host_RHEL.m8.u2.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.block_stream.drop_backingfile.q35: PASS (413.55 s)
(1/2) Host_RHEL.m7.u8.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.7.8.x86_64.io-github-autotest-qemu.block_stream.drop_backingfile.q35: PASS (332.35 s)
(2/2) Host_RHEL.m7.u8.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.7.8.x86_64.io-github-autotest-qemu.block_stream.drop_backingfile.with_data_plane.q35: PASS (314.94 s)

**Comment by meet-lucky** [comment]
@lolyu @xutian , please help to review.

**Comment by aliang123** [comment]
Test on RHEL8:
   Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.block_stream.drop_backingfile: PASS (215.11 s)

Test on RHEL7:
   (1/3) Host_RHEL.m7.u8.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.8.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (3477.24 s)
 (2/3) Host_RHEL.m7.u8.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.8.x86_64.io-github-autotest-qemu.rh_kernel_update: PASS (234.49 s)
 (3/3) Host_RHEL.m7.u8.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.8.x86_64.io-github-autotest-qemu.block_stream.drop_backingfile: PASS (359.25 s)

Acked-by: Aihua Liang <aliang@redhat.com>

**Comment by xutian** [comment]
LGTM

**Pull request merged**
