### PR TITLE
Basic block mirror during vm stop_cont -- only system disk

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1876405

### CODE REVIEW

**Comment by zhencliu** [comment]
local fs:
 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_vm_stop_cont: PASS (425.26 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-07T07.41-894667c/results.html
JOB TIME   : 431.31 s

gluster direct:
 (1/1) Host_RHEL.m8.u2.product_av.gluster_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_vm_stop_cont: PASS (532.51 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2020-09-07T19.52-38fe61d/results.html
JOB TIME   : 536.51 s

iscsi direct:
 (1/1) Host_RHEL.m8.u3.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_vm_stop_cont: PASS (402.71 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-07T09.17-b29c586/results.html
JOB TIME   : 408.72 s

nbd:
 (1/1) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_vm_stop_cont: PASS (516.49 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-07T09.31-2bb0efc/results.html
JOB TIME   : 522.14 s

hi @aliang123 @YongxueHong , can you please help to review the patch? Thanks much.
This patch deps on #2379 , so please ignore the CI check error.

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_vm_stop_cont.q35: PASS (610.06 s)

Acked-by: Aihua Liang<aliang@redhat.com>

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_vm_stop_cont.q35: PASS (731.47 s)

Acked-by: Aihua Liang<aliang@redhat.com>

**Comment by ngu-niny** [comment]
Test PASS on ppc:

PASS 3-Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.blockdev_mirror_vm_stop_cont

Acked-by: Nini Gu <ngu@redhat.com>

**Comment by YongxueHong** [comment]
Please update the commit header, too long.
Thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
