### PR TITLE
single_driver_install: workaround for install driver without signture

### PR DESCRIPTION
**Pull request by menli820**
ID: 2090095
Signed-off-by: Menghuan Li menli@redhat.com

### CODE REVIEW

**Comment by menli820** [comment]
python3 ConfigTest.py --testcase=win_virtio_driver_update_test.with_viorng.during_bg_test.uninstall_install.q35  --guestname=Win2016 --firmware=default_bios  --driveformat=virtio_blk --platform=x86_64 --machines=q35 --customsparams="cdrom_virtio = isos/windows/virtio-win-prewhql-0.1-221.iso"  --rng_type=rng_builtin  --clone=no

 (1/1) Host_RHEL.m9.u1.virtio_rng.rng_builtin.qcow2.virtio_blk.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_viorng.during_bg_test.uninstall_install.q35: PASS (223.23 s)


python3 ConfigTest.py --testcase=win_virtio_driver_update_test.with_viorng.during_bg_test.uninstall_install.q35  --guestname=Win2016 --firmware=default_bios  --driveformat=virtio_blk --platform=x86_64 --machines=q35 --customsparams="cdrom_virtio = isos/windows/virtio-win-prewhql-0.1-221.iso"  --rng_type=rng_builtin  --clone=no

 (1/1) Host_RHEL.m9.u1.qcow2.virtio_blk.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_viostor.during_bg_test.uninstall_install.q35: PASS (236.08 s)

**Comment by 6-dehan** [comment]
@menli820 LGTM
1-Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_vioser.during_bg_test.uninstall_install.q35
Summary: 
Finshed=1, PASS=1

**Comment by Kemama** [comment]
Hi @menli820 , 

Unfortunately, it doesn't work on netkvm. My command cannot passed:
python3 ConfigTest.py --testcase=win_virtio_driver_update_test.with_netkvm.during_bg_test.uninstall_install --guestname=Win2016 --firmware=default_bios --platform=x86_64 --machines=q35 --customsparams="cdrom_virtio = isos/windows/virtio-win-prewhql-0.1-218.iso"

Shall we give another try?

**Comment by peixiu** [comment]
python3 ConfigTest.py --testcase=win_virtio_driver_update_test.with_vioscsi.during_bg_test.uninstall_install.q35 --guestname=Win2022 --firmware=default_bios --platform=x86_64 --machines=q35 --customsparams="cdrom_virtio = isos/windows/virtio-win-prewhql-0.1-221.iso" --rng_type=rng_builtin --clone=no

 (1/1) Host_RHEL.m9.u0.virtio_rng.rng_builtin.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_vioscsi.during_bg_test.uninstall_install.q35: STARTED
 (1/1) Host_RHEL.m9.u0.virtio_rng.rng_builtin.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_vioscsi.during_bg_test.uninstall_install.q35: PASS (695.58 s)

LGTM, Thanks~
Acked-By: Peixiu Hou ,phou@redhat.com>

**Review by peixiu — APPROVED** [review]

**Comment by menli820** [comment]
> 
 @Kemama This work on my side, could you please provide your error/fail log directly?

**Comment by menli820** [comment]
> > 
> 
> @Kemama This work on my side with win2019, could you please provide your error/fail log directly?

@Kemama  After we discuss win2016 for netkvm error as BSOD and maybe a bug  and need your further debug.
I test netkvm with win2019, win10 PASS.  You can choose another guest to see whether for you, thanks

` (1/1) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_netkvm.during_bg_test.uninstall_install.q35: PASS (373.56 s)`

**Comment by leidwang** [comment]
JOB LOG    : /root/avocado/job-results/job-2022-06-22T04.53-dbffc0a/job.log
 (1/3) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_vioinput.device_keyboard.before_bg_test.uninstall_install.q35: STARTED
 (1/3) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_vioinput.device_keyboard.before_bg_test.uninstall_install.q35: PASS (501.18 s)
 (2/3) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_vioinput.device_mouse.before_bg_test.uninstall_install.q35: STARTED
 (2/3) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_vioinput.device_mouse.before_bg_test.uninstall_install.q35: PASS (448.31 s)
 (3/3) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_vioinput.device_tablet.before_bg_test.uninstall_install.q35: STARTED
 (3/3) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_vioinput.device_tablet.before_bg_test.uninstall_install.q35: PASS (447.13 s)

**Comment by xiagao** [comment]
Ack
 (1/2) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_balloon.during_bg_test.uninstall_install.q35: STARTED
 (1/2) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_balloon.during_bg_test.uninstall_install.q35: PASS (731.05 s)
 (2/2) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_viofs.during_bg_test.uninstall_install.q35: STARTED
 (2/2) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_viofs.during_bg_test.uninstall_install.q35: PASS (495.53 s)

**Comment by menli820** [comment]
@Kemama  please help to check it whether it works for you with other guest except win2016 when you free, thanks

**Comment by Kemama** [comment]
@menli820 Sure. Will take it soon.

**Comment by Kemama** [comment]
Hi @menli820,  

After testing, the patch works.
```
 (1/2) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: STARTED
 (1/2) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35:PASS (973.29 s)
 (2/2) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_netkvm.during_bg_test.uninstall_install.q35: STARTED
 (2/2) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_netkvm.during_bg_test.uninstall_install.q35: PASS (424.80 s)
```
```
 (1/2) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: STARTED
 (1/2) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35:PASS (713.28 s)
 (2/2) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_netkvm.during_bg_test.uninstall_install.q35: STARTED
 (2/2) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_netkvm.during_bg_test.uninstall_install.q35: PASS (196.14 s)
```
```
 (1/2) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win8.x86_64.1.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: STARTED
 (1/2) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win8.x86_64.1.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (821.15 s)
 (2/2) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win8.x86_64.1.io-github-autotest-qemu.win_virtio_driver_update_test.with_netkvm.during_bg_test.uninstall_install.q35: STARTED
 (2/2) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win8.x86_64.1.io-github-autotest-qemu.win_virtio_driver_update_test.with_netkvm.during_bg_test.uninstall_install.q35: PASS (274.39 s)
```
```
 (1/2) Host_RHEL.m9.u0.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: STARTED
 (1/2) Host_RHEL.m9.u0.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (791.19 s)
 (2/2) Host_RHEL.m9.u0.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_netkvm.during_bg_test.uninstall_install.q35: STARTED
 (2/2) Host_RHEL.m9.u0.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.win_virtio_driver_update_test.with_netkvm.during_bg_test.uninstall_install.q35: PASS (376.46 s)
```
ACK: mama <mama@redhat.com> Thanks for your effort.

**Comment by menli820** [comment]
Thanks all.
@vivianQizhu  please help to review it when you free, thanks

**Comment by vivianQizhu** [comment]
Thanks all.

**Pull request merged**
