### PR TITLE
block_resize:fix no response to QMP command 'block_resize'

### PR DESCRIPTION
**Pull request by qingwangrh**
It has no issue on manual testing but failed
auto testing. It need to some timeout after
format operation in guest.

ID:2209962
Signed-off-by: qingwangrh <qinwang@redhat.com>

### CODE REVIEW

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=block_resize.with_iozone.with_data_disk.fmt_qcow2 --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=RHEL.9.2.0 --driveformat=virtio_scsi --nicmodel=virtio_net --imageformat=qcow2 --machines=i440fx --customsparams="vm_mem_limit = 12G\nimage_aio=io_uring" --firmware=default_bios --netdst=virbr0 --clone=no
(1/4) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.block_resize.with_iozone.with_data_disk.fmt_qcow2.default_partition: PASS (167.12 s)
 (2/4) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.block_resize.with_iozone.with_data_disk.fmt_qcow2.with_gpt_ext4: STARTED
 (2/4) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.block_resize.with_iozone.with_data_disk.fmt_qcow2.with_gpt_ext4: PASS (109.00 s)
 (3/4) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.block_resize.with_iozone.with_data_disk.fmt_qcow2.with_msdos_xfs: STARTED
 (3/4) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.block_resize.with_iozone.with_data_disk.fmt_qcow2.with_msdos_xfs: PASS (227.48 s)
 (4/4) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.block_resize.with_iozone.with_data_disk.fmt_qcow2.with_gpt_xfs: STARTED
 (4/4) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.block_resize.with_iozone.with_data_disk.fmt_qcow2.with_gpt_xfs: PASS (104.10 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by qingwangrh** [comment]
@YongxueHong @XueqiangWei Please help to review. thanks.

**Comment by XueqiangWei** [comment]
Still hit the issue "Received no response to QMP command 'block_resize', or received a response with an incorrect id" when testing with the following command lines.

python ConfigTest.py --testcase=block_resize.with_iozone.with_data_disk.fmt_qcow2 --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=RHEL.9.3.0 --driveformat=virtio_scsi --nicmodel=virtio_net --imageformat=qcow2 --machines=q35 --customsparams="vm_mem_limit = 12G\nimage_aio=io_uring" --firmware=ovmf --clone=no

**Comment by XueqiangWei** [comment]
retested with sleep 30s, the results were passed.

(1/4) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autote
st-qemu.block_resize.with_iozone.with_data_disk.fmt_qcow2.default_partition.q35: STARTED
 (1/4) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autote
st-qemu.block_resize.with_iozone.with_data_disk.fmt_qcow2.default_partition.q35: PASS (368.35 s)
 (2/4) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autote
st-qemu.block_resize.with_iozone.with_data_disk.fmt_qcow2.with_gpt_ext4.q35: STARTED
 (2/4) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autote
st-qemu.block_resize.with_iozone.with_data_disk.fmt_qcow2.with_gpt_ext4.q35: PASS (249.18 s)
 (3/4) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autote
st-qemu.block_resize.with_iozone.with_data_disk.fmt_qcow2.with_msdos_xfs.q35: STARTED
 (3/4) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autote
st-qemu.block_resize.with_iozone.with_data_disk.fmt_qcow2.with_msdos_xfs.q35: PASS (226.72 s)
 (4/4) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autote
st-qemu.block_resize.with_iozone.with_data_disk.fmt_qcow2.with_gpt_xfs.q35: STARTED
 (4/4) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autote
st-qemu.block_resize.with_iozone.with_data_disk.fmt_qcow2.with_gpt_xfs.q35: PASS (227.82 s)

**Comment by XueqiangWei** [comment]
retested with the qemu sratch build you provided, sleep 0 and sleep 10 both work well.

**Comment by qingwangrh** [comment]
> retested with the qemu sratch build you provided, sleep 0 and sleep 10 both work well.

Thanks, we may keep this patch open to see the automation situation.  if the scratch build is merged and this issue disappears, we may close it.

**Comment by XueqiangWei** [comment]
> > retested with the qemu sratch build you provided, sleep 0 and sleep 10 both work well.
> 
> Thanks, we may keep this patch open to see the automation situation. if the scratch build is merged and this issue disappears, we may close it.

Qing, If we don't hit this issue in the latest qemu, please close this pullreq. Thanks.

**Pull request closed without merging**
