### PR TITLE
block_hotplug_in_pause: New a case that hotplug then unplug in pause

### PR DESCRIPTION
**Pull request by YongxueHong**
New a case that hot plug a disk then unplug it under the status
of vm is stopping, resume vm at last.

ID: 1703871
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by ybduan** [comment]
LGTM.
Acked-by: Yanbin Duan yduan@redhat.com

**Comment by XueqiangWei** [comment]
Both linux and windows guest are all passed.
(1/4) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.block_hotplug_in_pause.with_hotplug_no_resume_unplug.one_pci.q35: PASS (85.22 s)
 (2/4) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.block_hotplug_in_pause.data_plane.with_hotplug_no_resume_unplug.one_pci.q35: PASS (72.17 s)
 (3/4) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.block_hotplug_in_pause.with_hotplug_no_resume_unplug.one_pci.q35: PASS (157.46 s)
 (4/4) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.block_hotplug_in_pause.data_plane.with_hotplug_no_resume_unplug.one_pci.q35: PASS (145.79 s)

**Comment by XueqiangWei** [comment]
LGTM,
Acked-by xuwei@redhat.com

**Comment by YongxueHong** [comment]
@peixiu  help me review, thanks.

**Comment by peixiu** [comment]
Tested with win2016 guest, all passed:
 (1/6) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.block_hotplug_in_pause.with_plug.one_pci.q35: PASS (146.11 s)
 (2/6) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.block_hotplug_in_pause.without_plug.one_pci.q35: PASS (91.08 s)
 (3/6) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.block_hotplug_in_pause.with_hotplug_no_resume_unplug.one_pci.q35: PASS (75.22 s)
 (4/6) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.block_hotplug_in_pause.data_plane.with_plug.one_pci.q35: PASS (122.93 s)
 (5/6) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.block_hotplug_in_pause.data_plane.without_plug.one_pci.q35: PASS (73.33 s)
 (6/6) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.block_hotplug_in_pause.data_plane.with_hotplug_no_resume_unplug.one_pci.q35: PASS (74.76 s)

LTGM
Acked-by: Peixiu Hou phou@redhat.com

**Comment by YongxueHong** [comment]
Thanks all

**Pull request merged**
