### PR TITLE
gluster storage backend: support snapshot

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1789284

### CODE REVIEW

**Comment by zhencliu** [comment]
@hellohellenmao @lolyu Can U please help to review it, thanks.

**Comment by zhencliu** [comment]
(1/2) Host_RHEL.m8.u2.product_av.gluster.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.remote_image_snapshot.to_local: PASS (230.82 s)
 (2/2) Host_RHEL.m8.u2.product_av.gluster.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.remote_image_snapshot.to_remote: PASS (273.78 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 510.10 s
JOB HTML   : /root/avocado/job-results/job-2020-03-19T16.28-7d74e72/results.html

**Comment by zhencliu** [comment]
(1/2) Host_RHEL.m8.u2.product_av.gluster.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.remote_image_snapshot.to_local: PASS (413.53 s)
 (2/2) Host_RHEL.m8.u2.product_av.gluster.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.remote_image_snapshot.to_remote: PASS (452.98 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by hellohellenmao** [comment]
(1/2) Host_RHEL.m8.u2.product_av.gluster.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.remote_image_snapshot.to_local.q35: PASS (199.59 s)
 (2/2) Host_RHEL.m8.u2.product_av.gluster.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.remote_image_snapshot.to_remote.q35: PASS (228.00 s)

**Pull request merged**
