### PR TITLE
virtio_fs: add git init test on shared dir

### PR DESCRIPTION
**Pull request by xiagao**
ID: 2070387
Signed-off-by: Xiaoling Gao <xiagao@redhat.com>

### CODE REVIEW

**Comment by xiagao** [comment]
(1/3) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.git_init.q35: STARTED
 (1/3) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.git_init.q35: PASS (97.97 s)
 (2/3) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.git_init.q35: STARTED
 (2/3) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.git_init.q35: FAIL: Git init failed with fatal: cannot mkdir Z:\test: Permission denied\n\n (224.57 s)
 (3/3) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.git_init.q35: STARTED
 (3/3) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.git_init.q35: FAIL: Git init failed with fatal: cannot mkdir Z:\test: Permission denied\n\n (221.92 s)

**Comment by xiagao** [comment]
@zhenyzha @YongxueHong Could you pls help review when you are free,thanks.

**Comment by zhenyzha** [comment]
git am 3345.patch
Applying: virtio_fs: add git init test on shared dir

 (1/1) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.git_init.arm64-pci: PASS (191.65 s)

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Review by zhenyzha — APPROVED** [review]

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
