### PR TITLE
Revert "Add new case that start qga container"

### PR DESCRIPTION
**Pull request by 6-dehan**
This reverts commit 08b5a4150546a59172d990c696816cecc912d15f.

ID: 2024789
Signed-off-by: demeng demeng@redhat.com

### CODE REVIEW

**Comment by 6-dehan** [comment]
@vivianQizhu @yanan-fu could you review this one. thanks

**Comment by yanan-fu** [comment]
Suggest add a bit explanation in the commit message for this revert, thanks!

**Comment by 6-dehan** [comment]
> Suggest add a bit explanation in the commit message for this revert, thanks!

yeah, you're right, commit has been updated, thanks yfu.

**Review by yanan-fu — APPROVED** [review]
Ack

**Pull request merged**
