### PR TITLE
virtio_fs: update winfsp version to a default one

### PR DESCRIPTION
**Pull request by xiagao**
To make it easy to maintain, change the winfsp version to a stable one.
ID: 2136715
Signed-off-by: Xiaoling Gao <xiagao@redhat.com>

### CODE REVIEW

**Comment by xiagao** [comment]
@leidwang @nickzhq @YongxueHong Call for your review, thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Review by YongxueHong — DISMISSED** [review]
LGTM.

**Comment by nickzhq** [comment]
LGTM.

**Comment by xiagao** [comment]
(1/2) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: STARTED
 (1/2) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (1181.87 s)
 (2/2) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_hotplug.plug.one_fs_source.q35: STARTED
 (2/2) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_hotplug.plug.one_fs_source.q35: PASS (620.44 s)

**Review by leidwang — DISMISSED** [review]

**Comment by YongxueHong** [comment]
Hi @xiagao 
For your commit message:
```
To make it easy wo maintain, change the winfsp version to stable one.
Selinux-label option support for virtiofsd.
```
The second sentence `Selinux-label option support for virtiofsd.`, does it relate to this commit?
And there is typo `wo`.
Thanks.

**Comment by xiagao** [comment]
> Hi @xiagao For your commit message:
> 
> ```
> To make it easy wo maintain, change the winfsp version to stable one.
> Selinux-label option support for virtiofsd.
> ```
> 
> The second sentence `Selinux-label option support for virtiofsd.`, does it relate to this commit? And there is typo `wo`. Thanks.

Sorry for that, it's my typo,actually there is no relationship with selinux-label.
Updated, and pls have a look.
Thanks.

**Review by YongxueHong — APPROVED** [review]

**Pull request merged**
