### PR TITLE
Add vendor variant check in nested test case

### PR DESCRIPTION
**Pull request by qcheng-redhat**
Signed-off-by: Qinghua Cheng <qcheng@redhat.com>

Add vendor variant check in nested test case.

ID: 1804521

### CODE REVIEW

**Comment by qcheng-redhat** [comment]
@yanan-fu @luckyh @CongLi

**Comment by CongLi** [comment]
Please paste the test result for AMD here.

**Comment by qcheng-redhat** [comment]
Test results:
 (1/3) Host_RHEL.m8.u2.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (1022.75 s)
 (2/3) Host_RHEL.m8.u2.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.rh_kernel_update.q35: PASS (178.03 s)
 (3/3) Host_RHEL.m8.u2.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.nested_test.boot_l2.q35: PASS (1605.93 s)

On AMD host, with check_vendor = yes:
 (1/1) Host_RHEL.m8.u2.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.nested_test.boot_l2.q35: CANCEL: We only test this case with Intel platform now (51.68 s)

**Comment by xutian** [comment]
LGTM

**Pull request merged**
