### PR TITLE
virtio_mode: Update cmd to make it work in rhel6 guest

### PR DESCRIPTION
**Pull request by huangyum**
ID: 1728097
Signed-off-by: Yumei Huang <yuhuang@redhat.com>

### CODE REVIEW

**Comment by huangyum** [comment]
(1/1) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.6.10.x86_64.io-github-autotest-qemu.virtio_mode.with_balloon.with_legacy: PASS (74.23 s)
 (1/1) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_mode.with_balloon.with_legacy: PASS (70.40 s)

**Comment by huangyum** [comment]
@lijinlijin @yanan-fu Please help review, thanks.

**Comment by yanan-fu** [comment]
@huangyum  Could you explain the background ?
From code perspective,  i can not see any difference between `cat /****`  and `grep . /***`

**Comment by huangyum** [comment]
@yanan-fu It's same issue as https://github.com/autotest/tp-qemu/pull/953#discussion_r121844790.
The output of original cmd in rhel6 guest is:
02:16:56 DEBUG| [stdout] cat /sys/bus/pci/devices/0000:00:06.0/virtio*/feat<cat /sys/bus/pci/devices/0000:00:06.0/virtio*/featu                         ^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^Hres

02:16:56 DEBUG| [stdout] 0100000000000000000000000000110000000000000000000000000000000000

**Comment by yanan-fu** [comment]
Thanks for your explanation,  LGTM

Acked-by: Yanan Fu <yfu@redhat.com>

**Comment by yanan-fu** [comment]
Better explain it in commit message i think.

**Comment by lijinlijin** [comment]
LGTM
Acked-by: Li Jin lijin@redhat.com

**Comment by huangyum** [comment]
@yanan-fu Updated commit message, thanks.

**Comment by yanan-fu** [comment]
LGTM, Thanks all!

**Pull request merged**
