### PR TITLE
block installation test: Disable data plane when using virtio-scsi

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>
ID: 1949473

### CODE REVIEW

**Comment by zhencliu** [comment]
enabled data plane
 (1/4) Host_RHEL.m8.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_commit_install.q35: PASS (1346.37 s)
 (2/4) Host_RHEL.m8.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_mirror_install.q35: PASS (1759.80 s)
 (3/4) Host_RHEL.m8.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream_install.q35: PASS (1579.27 s)
 (4/4) Host_RHEL.m8.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_install.q35: PASS (1624.56 s)
without dataplan:
 (1/1) Host_RHEL.m8.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_mirror_install.q35: PASS (1757.88 s)

**Comment by zhencliu** [comment]
hi @leidwang @ngu-niny , can you please help to review this patch? Thanks much.

**Comment by leidwang** [comment]
Test pass,LGTM.
 (1/4) Host_RHEL.m8.u4.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_commit_install.q35:PASS (1175.73 s)
 (2/4) Host_RHEL.m8.u4.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_mirror_install.q35:PASS (1463.75 s)
 (3/4) Host_RHEL.m8.u4.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_install.q35: PASS (1221.53 s)
 (4/4) Host_RHEL.m8.u4.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream_install.q35:PASS (1239.36 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2021-04-22T22.56-aeb0ff4/results.html
JOB TIME   : 5102.95 s

 (1/4) Host_RHEL.m8.u4.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_mirror_install.q35: PASS (1297.30 s)
 (2/4) Host_RHEL.m8.u4.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_install.q35: PASS (1169.46 s)
 (3/4) Host_RHEL.m8.u4.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream_install.q35: PASS (1259.55 s)
 (4/4) Host_RHEL.m8.u4.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_commit_install.q35: PASS (1399.36 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2021-04-23T02.04-b4de7c9/results.html
JOB TIME   : 5128.14 s

**Comment by ngu-niny** [comment]
LGTM, test pass, the FAIL case is not caused by this patch:

 (1/4) Host_RHEL.m8.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.blockdev_mirror_install:  PASS (1893.77 s)
 (2/4) Host_RHEL.m8.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_install:  FAIL: Failed to install guest (128.27 s)
 (3/4) Host_RHEL.m8.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.blockdev_stream_install:  PASS (1610.33 s)
 (4/4) Host_RHEL.m8.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.blockdev_commit_install:  PASS (1536.44 s)

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
