### PR TITLE
made linux stress test use local stress package

### PR DESCRIPTION
**Pull request by xutian**
fix bug id=1732749

Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
[root@ibm-x3250m6-10 deps]# avocado run --vt-config /var/lib/avocado/data/avocado-vt/backends/qemu/cfg/tests-example.cfg  
JOB ID     : d4eb8a26d23875e613f5c1e79e6422d549473747
JOB LOG    : /root/avocado/job-results/job-2019-07-24T23.04-d4eb8a2/job.log
 (1/1) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.live_snapshot.with_payload.data_integrity.q35: PASS (123.51 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 125.36 s
JOB HTML   : /root/avocado/job-results/job-2019-07-24T23.04-d4eb8a2/results.html

**Comment by xutian** [comment]
deps on https://github.com/avocado-framework/avocado-vt/pull/2169/

**Comment by aliang123** [comment]
Also suggest to make an optimize on utils_test.__init.py,
 def download_stress(self):
        """
        Download stress tool
        """
        url = self.download_url
        tmp_path = data_dir.get_tmp_dir()
        logging.info('Download stress tool from %s', url)
       try:
            download_method = getattr(
                self, "_%s_download" % self.download_type)
            download_method(url, tmp_path)
   If self.download_type not in ["wget","git"], the url download info will be skipped.

**Comment by xutian** [comment]
thanks your comments, see fix in pullreq deps on avocado-framework/avocado-vt#2169

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m7.u7.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.live_snapshot.with_payload.data_integrity: PASS 

Acked-by: Aihua Liang <aliang@redhat.com>

**Comment by xutian** [comment]
thanks @aliang123

**Pull request merged**
