### PR TITLE
block_hotplug_with_remote_storage: support nbd storage

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1845073

### CODE REVIEW

**Comment by zhencliu** [comment]
(1/8) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (3062.26 s)
 (2/8) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.rh_kernel_update: ERROR: 'list' object has no attribute 'splitlines' (323.95 s)
 (3/8) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_qcow2: PASS (107.41 s)
 (4/8) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_raw: PASS (90.99 s)
 (5/8) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_luks: PASS (98.69 s)
 (6/8) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_qcow2: PASS (85.33 s)
 (7/8) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_raw: PASS (86.23 s)
 (8/8) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_luks: PASS (92.40 s)
RESULTS    : PASS 7 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-06-10T11.39-b8df19e/results.html
JOB TIME   : 3952.97 s

**Comment by zhencliu** [comment]
@XueqiangWei @YongxueHong Can you please help to review the case, thanks.

--testcase=block_hotplug_with_remote_storage

**Comment by zixi-chen** [comment]
@zhencliu cc @XueqiangWei 
when hot-plug a img, the img should be exported over nbd.

Error log:
06:02:24 DEBUG| (monitor avocado-vt-vm1.qmpmonitor1) Sending command 'blockdev-add'
06:02:24 DEBUG| Send command: {'execute': 'blockdev-add', 'arguments': {'node-name': 'nbd_stg0', 'driver': 'nbd', 'server': {'type': 'inet', 'host': 'dell-per440-11.lab.eng.pek2.redhat.com', 'port': '10820'}, 'cache': {'direct': True, 'no-flush': False}}, 'id': 'IfvxdMyp'}
06:02:24 ERROR|
06:02:24 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework_plugin_vt-80.0-py3.6.egg/avocado_vt/test.py:438
06:02:24 ERROR| Traceback (most recent call last):
06:02:24 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework_plugin_vt-80.0-py3.6.egg/virttest/error_context.py", line 135, in new_fn
06:02:24 ERROR|     return fn(*args, **kwargs)
06:02:24 ERROR|   File "/var/lib/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/block_hotplug.py", line 177, in run
06:02:24 ERROR|     new_disk = plug_block_devices('hotplug', data_devs).pop()
06:02:24 ERROR|   File "/var/lib/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/block_hotplug.py", line 77, in plug_block_devices
06:02:24 ERROR|     ret = getattr(vm.devices, 'simple_%s' % action)(dev, vm.monitor)
06:02:24 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework_plugin_vt-80.0-py3.6.egg/virttest/qemu_devices/qcontainer.py", line 801, in simple_hotplug
06:02:24 ERROR|     out = device.hotplug(monitor)
06:02:24 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework_plugin_vt-80.0-py3.6.egg/virttest/qemu_devices/qdevices.py", line 258, in hotplug
06:02:24 ERROR|     return monitor.cmd(cmd, args)
06:02:24 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework_plugin_vt-80.0-py3.6.egg/virttest/qemu_monitor.py", line 1977, in cmd
06:02:24 ERROR|     raise QMPCmdError(cmd, args, r["error"])
06:02:24 ERROR| virttest.qemu_monitor.QMPCmdError: QMP command 'blockdev-add' failed    (arguments: {'node-name': 'nbd_stg0', 'driver': 'nbd', 'server': {'type': 'inet', 'host': 'dell-per440-11.lab.eng.pek2.redhat.com', 'port': '10820'}, 'cache': {'direct': True, 'no-flush': False}},    error message: {'class': 'GenericError', 'desc': 'Failed to connect socket: Connection refused'})
06:02:24 ERROR|
...
6:02:28 DEBUG| Checking image file nbd://dell-per440-11.lab.eng.pek2.redhat.com:10820
06:02:28 ERROR| [stderr] qemu-img: Could not open 'nbd://dell-per440-11.lab.eng.pek2.redhat.com:10820': Failed to connect socket: Connection refused

**Comment by zhencliu** [comment]
@zixi-chen that's because there are no image exported on port 10820

[root@dell-per440-11 ~]# ps -ef|grep qemu-nbd
root      116381       1  0 04:02 ?        00:00:33 qemu-nbd -t -e 3 --fork -f raw /home/nbd/nbd_system.qcow2
root      128651  109915  0 06:22 pts/19   00:00:00 grep --color=auto qemu-nbd

**Comment by zixi-chen** [comment]
'1-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_qcow2' Finshed 2020-07-01 09:57:48 2020-07-01 09:58:33 PASS 45.558363
'2-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_raw' Finshed 2020-07-01 09:58:33 2020-07-01 09:59:13 PASS 40.232165
'3-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_luks' Finshed 2020-07-01 09:59:14 2020-07-01 09:59:57 PASS 43.68071
'4-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_qcow2' Finshed 2020-07-01 09:59:57 2020-07-01 10:00:40 PASS 43.287447
'5-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_raw' Finshed 2020-07-01 10:00:40 2020-07-01 10:01:21 PASS 40.770465
'6-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_luks' Finshed 2020-07-01 10:01:21 2020-07-01 10:02:03 PASS 42.167345

LGTM
ACK

**Comment by zhencliu** [comment]
with latest vt patch
 (1/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.migration_with_remote_storage: PASS (302.79 s)
 (2/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.migration_with_remote_storage.with_post_copy: PASS (118.14 s)
 (3/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_snapshot.to_local: PASS (208.71 s)
 (4/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_qcow2: PASS (144.16 s)
 (5/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_raw: PASS (147.89 s)
 (6/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_luks: PASS (173.43 s)
 (7/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_qcow2: PASS (169.89 s)
 (8/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_raw: PASS (158.17 s)
 (9/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_luks: PASS (151.73 s)
RESULTS    : PASS 9 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by zhencliu** [comment]
(1/6) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_qcow2: PASS (157.15 s)
 (2/6) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_raw: PASS (144.77 s)
 (3/6) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_luks: PASS (233.61 s)
 (4/6) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_qcow2: PASS (146.19 s)
 (5/6) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_raw: PASS (146.33 s)
 (6/6) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_luks: PASS (144.71 s)
RESULTS    : PASS 6 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-07-03T05.45-4cc3129/results.html
JOB TIME   : 978.12 s


hi @YongxueHong ,can you please help to merge it, thanks.

**Pull request merged**
