### PR TITLE
qemu_guest_agent: Fix connect monitor failed issue

### PR DESCRIPTION
**Pull request by yanan-fu**
The interface of class 'Monitor' have changed, update the call

id: 1806375
Signed-off-by: Yanan Fu <yfu@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
(1/3) Host_RHEL.m8.u2.v0.product_av.spice.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.gagent_install.q35: PASS (61.98 s)
 (2/3) Host_RHEL.m8.u2.v0.product_av.spice.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_powerdown.q35: PASS (60.14 s)
 (3/3) Host_RHEL.m8.u2.v0.product_av.spice.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_reboot.q35: PASS (108.17 s)

**Comment by yanan-fu** [comment]
@xiagao @nanliu-r  could you help review, thanks!

**Comment by xiagao** [comment]
(1/1) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win8.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.check_get_time.q35: PASS (42.85 s)

**Comment by xiagao** [comment]
ACK

**Comment by xiagao** [comment]
@yanan-fu 
it works with this modification.
But I think it's better to modify it in avocado-vt/virttest/guest_agent.py, the parameter is still serial_filename but not monitor_params

**Comment by yanan-fu** [comment]
@xiagao  i already updated with https://github.com/avocado-framework/avocado-vt/pull/2440

**Comment by nanliu-r** [comment]
ACK.

**Comment by yanan-fu** [comment]
Thanks all!

**Pull request merged**
