### PR TITLE
guest_test: using safe mode when execute cmd with serial session

### PR DESCRIPTION
**Pull request by yanan-fu**
id: 1796924
Signed-off-by: Yanan Fu <yfu@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
Test pass for 50 times:
```
# python3 ConfigTest.py --testcase=guest_test.isa_serial_operations --clone=no --guestname=RHEL.8.2.0 --nrepeat=50
... 
(50/50) repeat50.Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.guest_test.isa_serial_operations: PASS (150.99 s)
RESULTS    : PASS 50 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```

**Comment by yanan-fu** [comment]
@luckyh could you help review, thanks!

**Comment by yanan-fu** [comment]
@nanliu-r  call for your review, thanks!

**Comment by nanliu-r** [comment]
> @nanliu-r call for your review, thanks!
Can reproduce this issue probabilistic without this patch and tests pass now. Thanks.
(20/20) repeat20.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.guest_test.isa_serial_operations: PASS (155.77 s)
RESULTS    : PASS 20 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

ACK.

**Comment by yanan-fu** [comment]
Thanks all!

**Pull request merged**
