### PR TITLE
qemu.tests.qmp_event_notification: add "system_wakeup" event check.

### PR DESCRIPTION
**Pull request by CongLi**
Signed-off-by: Cong Li <coli@redhat.com>

id: 1343300
Based on: https://github.com/avocado-framework/avocado-vt/pull/667

### CODE REVIEW

**Comment by CongLi** [comment]
16:05:52 INFO | PASS 1-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_suspend.from_guest

**Comment by PandaWei** [comment]
ACK

**Comment by PyLearner** [comment]
smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.qmp_event_notification.qmp_suspend.from_guest: PASS 

Acked-by: Meng Yang meyang@redhat.com

**Comment by CongLi** [comment]
Thanks @PandaWei @PyLearner , merged.

**Pull request merged**
