### PR TITLE
fio_perf: fix scp failed issue on virtiofs perf test

### PR DESCRIPTION
**Pull request by xiagao**
The output file of fio cmd isn't the same with it in scp cmd,
fix this issue.
ID: 2031500
Signed-off-by: Xiaoling Gao <xiagao@redhat.com>

### CODE REVIEW

**Comment by xiagao** [comment]
@yanan-fu Could you help review this one?THanks.

**Comment by xiagao** [comment]
(1/4) repeat1.Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.fio_perf.shared_fs.virtio_fs_perf.auto.q35: PASS (4232.71 s)
 (2/4) repeat2.Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.fio_perf.shared_fs.virtio_fs_perf.auto.q35: PASS (4207.28 s)
 (3/4) repeat3.Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.fio_perf.shared_fs.virtio_fs_perf.auto.q35: PASS (4229.04 s)
 (4/4) repeat4.Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.fio_perf.shared_fs.virtio_fs_perf.auto.q35: PASS (4234.55 s)

**Comment by xiagao** [comment]
@YanhuiMa Could you also review it?Thx.

**Comment by yanan-fu** [comment]
Well, when we correct `fio_cmd` with `fio_options` with patch 3116 2 days ago, this case can pass according to the test result you provided,  any new change cause this regression issue ?

**Comment by yanan-fu** [comment]
@hellohellenmao suggest `raw_disk` use parameter `guest_result_file` instead of hardcode output file too.

**Comment by xiagao** [comment]
> Well, when we correct `fio_cmd` with `fio_options` with patch 3116 2 days ago, this case can pass according to the test result you provided, any new change cause this regression issue ?

No regression, just update it manually based on 3116.

**Comment by xiagao** [comment]
> @hellohellenmao suggest `raw_disk` use parameter `guest_result_file` instead of hardcode output file too.

Need I modify it together? @hellohellenmao

**Comment by hellohellenmao** [comment]
> > @hellohellenmao suggest `raw_disk` use parameter `guest_result_file` instead of hardcode output file too.
> 
> Need I modify it together? @hellohellenmao

That would be great. Thanks @xiagao

**Comment by xiagao** [comment]
@yanan-fu Do you know what cause the python2.7 check error?From the log I see something installation error,
do we need to resolve it?
Thanks.

**Comment by yanan-fu** [comment]
> @yanan-fu Do you know what cause the python2.7 check error?From the log I see something installation error, do we need to resolve it? Thanks.

Not related with this patch, refer: https://github.com/autotest/tp-qemu/pull/3133

**Comment by yanan-fu** [comment]
> > Well, when we correct `fio_cmd` with `fio_options` with patch 3116 2 days ago, this case can pass according to the test result you provided, any new change cause this regression issue ?
> 
> No regression, just update it manually based on 3116.

So the test result that be added with patch 3116 is in-correct ?  Hope to provide the accurate test result in the future.

**Comment by xiagao** [comment]
> > > Well, when we correct `fio_cmd` with `fio_options` with patch 3116 2 days ago, this case can pass according to the test result you provided, any new change cause this regression issue ?
> > 
> > 
> > No regression, just update it manually based on 3116.
> 
> So the test result that be added with patch 3116 is in-correct ? Hope to provide the accurate test result in the future.

The result is correct.
After apply 3116 patch,then modify --output=${guest_result_file}.

**Comment by yanan-fu** [comment]
> > > > Well, when we correct `fio_cmd` with `fio_options` with patch 3116 2 days ago, this case can pass according to the test result you provided, any new change cause this regression issue ?
> > > 
> > > 
> > > No regression, just update it manually based on 3116.
> > 
> > 
> > So the test result that be added with patch 3116 is in-correct ? Hope to provide the accurate test result in the future.
> 
> The result is correct. After apply 3116 patch,then modify --output=${guest_result_file}.

When we call for test result with a patch,  the expected test result  is for  patch + master.   Add result pass with manual change(for issues you know about it) is not make sense.  
The accurate result with patch + master is needed,   and explain the reason of the failing is not related with the current patch (something like this), then we can decide fix the known issues with new patch or not. Thanks!

**Comment by yanan-fu** [comment]
@hellohellenmao  could you help provide test result with `raw_disk`, need cover both windows and linux, thanks!

**Comment by hellohellenmao** [comment]
All passed. And Ack from my side.

Linux:
 (1/2) Host_RHEL.m9.u0.raw.virtio_blk.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.fio_perf.single_disk.raw_disk.NVMe.q35: PASS (168.00 s)
 (2/2) Host_RHEL.m9.u0.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.fio_perf.single_disk.raw_disk.NVMe.q35: PASS (174.73 s)

Win:
 (1/2) Host_RHEL.m9.u0.raw.virtio_blk.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.fio_perf.single_disk.raw_disk.NVMe.q35: PASS (246.05 s)
 (2/2) Host_RHEL.m9.u0.raw.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.fio_perf.single_disk.raw_disk.NVMe.q35: PASS (248.41 s)

**Review by yanan-fu — APPROVED** [review]
Ack

**Pull request merged**
