### PR TITLE
Add supported for ioeventfd.virtio_serial for s390x

### PR DESCRIPTION
**Pull request by fbq815**
virtual_block:add virtio_serial_ccw0 to adapt s390x

ID:1951608

Signed-off-by: Boqiao Fu <bfu@redhat.com>

### CODE REVIEW

**Comment by fbq815** [comment]
Test result:JOB ID     : e2edde3db405c75989dc1538ae28e0524453c963
JOB LOG    : /home/bfu/kar/workspace/job-results/job-2021-04-20T09.30-e2edde3/job.log
 (1/1) Host_RHEL.m8.u4.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.s390x.io-github-autotest-qemu.ioeventfd.virtio_serial.s390-virtio: PASS (67.18 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/bfu/kar/workspace/job-results/job-2021-04-20T09.30-e2edde3/results.html
JOB TIME   : 67.79 s

**Comment by fbq815** [comment]
@PaulYuuu @zhenyzha  please help me review this patch

**Comment by fbq815** [comment]
Test result for blk:
JOB ID     : 6fee83b9c3a74f01dbc952db69e43c25b2091715
JOB LOG    : /home/bfu/kar/workspace/job-results/job-2021-04-20T14.02-6fee83b/job.log
 (1/1) Host_RHEL.m8.u4.product_rhel.nographic.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.s390x.io-github-autotest-qemu.ioeventfd.virtio_serial.s390-virtio: PASS (81.72 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/bfu/kar/workspace/job-results/job-2021-04-20T14.02-6fee83b/results.html
JOB TIME   : 82.33 s

**Review by PaulYuuu — APPROVED** [review]

**Comment by fbq815** [comment]
@zhenyzha  please help me review this patch

**Comment by zhenyzha** [comment]
on ppc64le:
` (1/1) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.ioeventfd.virtio_serial: PASS (191.81 s)
`
LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Review by zhenyzha — APPROVED** [review]

**Pull request merged**
