### PR TITLE
commit_with_backing: support luks

### PR DESCRIPTION
**Pull request by lolyu**
1. add support for luks as base image
2. refactor the code with functions provided in
provider/qemu_img_utils.py

Signed-off-by: lolyu <lolyu@redhat.com>

### CODE REVIEW

**Comment by lolyu** [comment]
```
 (1/1) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.1.x86_64.io-github-autotest-qemu.commit_with_backing: PASS (220.52 s)
```

**Comment by lolyu** [comment]
depends on https://github.com/avocado-framework/avocado-vt/pull/2282

**Comment by hellohellenmao** [comment]
Tested with win2019. passed. And the log is ok to me.

(1/1) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.commit_with_backing: PASS (448.11 s)

**Comment by lolyu** [comment]
Thanks all.

**Pull request merged**
