### PR TITLE
 blockdev_stream_speed:remove the dup code

### PR DESCRIPTION
**Pull request by aliang123**
Remove dup code for speed check

Signed-off-by: Aihua Liang <aliang@redhat.com>
id:2113796

### CODE REVIEW

**Comment by aliang123** [comment]
(01/50) repeat1.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (01/50) repeat1.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (120.74 s)
 (02/50) repeat2.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (02/50) repeat2.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (99.16 s)
 (03/50) repeat3.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (03/50) repeat3.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (98.61 s)
 (04/50) repeat4.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (04/50) repeat4.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (99.14 s)
 (05/50) repeat5.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (05/50) repeat5.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (97.17 s)
 (06/50) repeat6.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (06/50) repeat6.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (97.92 s)
 (07/50) repeat7.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (07/50) repeat7.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (99.29 s)
 (08/50) repeat8.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (08/50) repeat8.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (98.63 s)
 (09/50) repeat9.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (09/50) repeat9.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (96.68 s)
 (10/50) repeat10.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (10/50) repeat10.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (96.38 s)
 (11/50) repeat11.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (11/50) repeat11.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (98.03 s)
 (12/50) repeat12.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (12/50) repeat12.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (99.81 s)
 (13/50) repeat13.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (13/50) repeat13.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (98.04 s)
 (14/50) repeat14.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (14/50) repeat14.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (97.87 s)
 (15/50) repeat15.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (15/50) repeat15.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (96.37 s)
 (16/50) repeat16.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (16/50) repeat16.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (97.88 s)
 (17/50) repeat17.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (17/50) repeat17.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (125.10 s)
 (18/50) repeat18.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (18/50) repeat18.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (97.47 s)
 (19/50) repeat19.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (19/50) repeat19.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (97.68 s)
 (20/50) repeat20.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (20/50) repeat20.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (96.88 s)
 (21/50) repeat21.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (21/50) repeat21.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (97.88 s)
 (22/50) repeat22.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (22/50) repeat22.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (98.78 s)
 (23/50) repeat23.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (23/50) repeat23.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (97.99 s)
 (24/50) repeat24.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (24/50) repeat24.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (96.31 s)
 (25/50) repeat25.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (25/50) repeat25.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (99.18 s)
 (26/50) repeat26.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (26/50) repeat26.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (97.90 s)
 (27/50) repeat27.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (27/50) repeat27.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (97.70 s)
 (28/50) repeat28.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (28/50) repeat28.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (98.87 s)
 (29/50) repeat29.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (29/50) repeat29.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (97.93 s)
 (30/50) repeat30.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (30/50) repeat30.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (96.31 s)
 (31/50) repeat31.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (31/50) repeat31.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (99.14 s)
 (32/50) repeat32.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (32/50) repeat32.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (123.39 s)
 (33/50) repeat33.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (33/50) repeat33.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (99.20 s)
 (34/50) repeat34.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (34/50) repeat34.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (100.12 s)
 (35/50) repeat35.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (35/50) repeat35.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (99.02 s)
 (36/50) repeat36.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (36/50) repeat36.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (99.63 s)
 (37/50) repeat37.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (37/50) repeat37.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (97.80 s)
 (38/50) repeat38.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (38/50) repeat38.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (98.28 s)
 (39/50) repeat39.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (39/50) repeat39.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (99.92 s)
 (40/50) repeat40.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (40/50) repeat40.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (99.85 s)
 (41/50) repeat41.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (41/50) repeat41.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (98.34 s)
 (42/50) repeat42.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (42/50) repeat42.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (96.90 s)
 (43/50) repeat43.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (43/50) repeat43.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (98.59 s)
 (44/50) repeat44.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (44/50) repeat44.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (98.35 s)
 (45/50) repeat45.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (45/50) repeat45.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (100.60 s)
 (46/50) repeat46.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (46/50) repeat46.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (121.77 s)
 (47/50) repeat47.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (47/50) repeat47.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (97.72 s)
 (48/50) repeat48.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (48/50) repeat48.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (97.99 s)
 (49/50) repeat49.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (49/50) repeat49.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (98.96 s)
 (50/50) repeat50.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (50/50) repeat50.Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (98.26 s)

**Comment by aliang123** [comment]
@zhencliu @MiriamDeng, please help to review, thanks.

**Comment by MiriamDeng** [comment]
ACK

**Comment by zhencliu** [comment]
LGTM

**Pull request merged**
