### PR TITLE
convert_image_from_raw: Add luks and raw formats for target images

### PR DESCRIPTION
**Pull request by hellohellenmao**
1. Update the config file with luks and raw formats for targets
2. Rename the py and config files from 'convert_image_from_raw_to_qcow2'
    to 'convert_image_from_raw'

Signed-off-by: Tingting Mao <timao@redhat.com>

### CODE REVIEW

**Comment by hellohellenmao** [comment]
# python ConfigTest.py --testcase=convert_image_from_raw --clone=no --guestname=RHEL.8.1.0 --imageformat=raw 
.......
......
(01/10) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.convert_image_from_raw.to_raw: PASS (224.96 s)
 (02/10) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.convert_image_from_raw.to_qcow2: PASS (188.77 s)
 (03/10) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.convert_image_from_raw.to_qcow2.cache_mode.writethrough: PASS (333.09 s)
 (04/10) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.convert_image_from_raw.to_qcow2.cache_mode.writeback: PASS (190.84 s)
 (05/10) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.convert_image_from_raw.to_qcow2.cache_mode.none: PASS (214.20 s)
 (06/10) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.convert_image_from_raw.to_qcow2.cache_mode.unsafe: PASS (183.92 s)
 (07/10) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.convert_image_from_raw.to_qcow2.cache_mode.directsync: PASS (336.33 s)
 (08/10) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.convert_image_from_raw.to_qcow2.compat_level.compat_0.10: PASS (185.20 s)
 (09/10) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.convert_image_from_raw.to_qcow2.compat_level.compat_default: PASS (182.14 s)
 (10/10) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.convert_image_from_raw.to_luks: PASS (309.14 s)

**Comment by hellohellenmao** [comment]
@lolyu Help to review, please.

**Comment by hellohellenmao** [comment]
@PaulYuuu Help to take a review, please.

**Comment by hellohellenmao** [comment]
@zhenyzha Help to take review, please.

**Comment by zhenyzha** [comment]
(01/10) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.convert_image_from_raw.to_raw: P
ASS (254.94 s)
 (02/10) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.convert_image_from_raw.to_qcow2:
 PASS (208.93 s)
 (03/10) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.convert_image_from_raw.to_qcow2.
cache_mode.writethrough: PASS (463.43 s)
 (04/10) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.convert_image_from_raw.to_qcow2.
cache_mode.writeback: PASS (229.94 s)
 (05/10) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.convert_image_from_raw.to_qcow2.
cache_mode.none: PASS (315.57 s)
 (06/10) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.convert_image_from_raw.to_qcow2.
cache_mode.unsafe: PASS (216.72 s)
 (07/10) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.convert_image_from_raw.to_qcow2.
cache_mode.directsync: PASS (473.49 s)
 (08/10) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.convert_image_from_raw.to_qcow2.
compat_level.compat_0.10: PASS (232.71 s)
 (09/10) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.convert_image_from_raw.to_qcow2.
compat_level.compat_default: PASS (229.02 s)
 (10/10) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.convert_image_from_raw.to_luks: 
PASS (709.22 s)

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Pull request merged**
