### PR TITLE
blockdev_inc_backup_xpt_multiple_bitmaps: Mutiple bitmaps export

### PR DESCRIPTION
**Pull request by zhencliu**
Export image with multiple bitmaps from nbd server

Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1922941, 1922946

### CODE REVIEW

**Comment by zhencliu** [comment]
virtio-blk:
 (1/2) Host_RHEL.m8.u3.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_xpt_multiple_bitmaps.with_qemu_nbd.q35: PASS (37.88 s)
 (2/2) Host_RHEL.m8.u3.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_xpt_multiple_bitmaps.with_block_export.q35: PASS (45.04 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2021-01-29T10.53-885d4bb/results.html
JOB TIME   : 85.56 s

virtio-scsi:
 (1/2) Host_RHEL.m8.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_xpt_multiple_bitmaps.with_qemu_nbd.q35: PASS (42.49 s)
 (2/2) Host_RHEL.m8.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_xpt_multiple_bitmaps.with_block_export.q35: PASS (44.76 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2021-01-29T10.56-a422cda/results.html
JOB TIME   : 90.06 s

**Comment by zhencliu** [comment]
hi @ngu-niny @YongxueHong , can you please help to review this patch, thanks.
it deps on:
https://github.com/avocado-framework/avocado-vt/pull/2890
https://github.com/autotest/tp-qemu/pull/2604

**Comment by ngu-niny** [comment]
LGTM and test PASS:

'05-Host_RHEL.m8.u4.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_xpt_multiple_bitmaps.with_qemu_nbd' Finshed 2021-02-07 15:21:14 2021-02-07 15:22:58 PASS 104.689151
'06-Host_RHEL.m8.u4.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_xpt_multiple_bitmaps.with_block_export' Finshed 2021-02-07 15:22:58 2021-02-07 15:24:41 PASS 102.786677

'15-Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_xpt_multiple_bitmaps.with_qemu_nbd' Finshed 2021-02-07 16:21:59 2021-02-07 16:23:42 PASS 103.069608
'16-Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_xpt_multiple_bitmaps.with_block_export' Finshed 2021-02-07 16:23:42 2021-02-07 16:25:13 PASS 90.929828

Acked-by: Nini Gu <ngu@redhat.com>

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
