### PR TITLE
Update test case cfg files as cfg file include order is updated

### PR DESCRIPTION
**Pull request by suqinhuang**
As subtests.cfg is updated to the end, some setup need to move to case cfg file

Signed-off-by: Suqin Huang <shuang@redhat.com>

id: 1405894

### CODE REVIEW

**Comment by suqinhuang** [comment]
https://github.com/avocado-framework/avocado-vt/pull/842

**Comment by xutian** [comment]
some configuration used frequently by many tests we can keep it in guest-os.cfg, eg  with_stress.

**Comment by suqinhuang** [comment]
I didn't update with_stress as xiywang's patch is under review
but with_stress is a common test for many cases, the setup for with_stress may effect others with use diff params

**Comment by xutian** [comment]
many with_stress case used same stress tool, and i don't any case use special stress tool, so that kind of special cases we can ask developer to use a different name.

**Comment by CongLi** [comment]
Could you share the test results?

Thanks.

**Comment by aliang123** [comment]
Some error occur when i apply the patch.
********Details: *******************
[root@intel-e5530-8-2 qemu]# git apply 893.patch
qemu/893.patch:404: trailing whitespace.
        file_create_cmd = "D:\coreutils\DummyCMD.exe C:\test\%s.blockfiles 1048576 1" 
qemu/893.patch:321: new blank line at EOF.
+
qemu/893.patch:585: new blank line at EOF.
+
error: patch failed: qemu/tests/cfg/qemu_disk_img.cfg:12
error: qemu/tests/cfg/qemu_disk_img.cfg: patch does not apply
qemu/893.patch:702: new blank line at EOF.
+
qemu/893.patch:815: new blank line at EOF.

**Pull request closed without merging**
