### PR TITLE
nested_block_resize: cancel test if `ansible-playbook` is not available

### PR DESCRIPTION
**Pull request by lkotek**
Change aligns test logic with `ansible_test` using the same approach.

ID: 2124295

Signed-off-by: Lukas Kotek <lkotek@redhat.com>

### CODE REVIEW

**Review by yanan-fu — APPROVED** [review]
Ack

**Comment by yanan-fu** [comment]
@qingwangrh Could you please help review it ? Thanks!

**Comment by qingwangrh** [comment]
It will install ansible on clean ENV. 

LGTM

**Comment by yanan-fu** [comment]
Thanks all!

**Pull request merged**
