### PR TITLE
netperf: bypass compilation with -Wno-implicit-function-declaration

### PR DESCRIPTION
**Pull request by quanwenli**
Signed-off-by: Wenli Quan [wquan@redhat.com]

id: 2529

### CODE REVIEW

**Comment by quanwenli** [comment]
JOB LOG    : /root/avocado/job-results/job-2024-06-20T04.27-6b39272/job.log
 (1/1) 82599.bridge_test.1q.acceptance.repeat1.Host_RHEL.m9.u5.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.netperf.default.host_guest.q35: STARTED
 (1/1) 82599.bridge_test.1q.acceptance.repeat1.Host_RHEL.m9.u5.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.netperf.default.host_guest.q35: PASS (317.71 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2024-06-20T04.27-6b39272/results.html

**Comment by quanwenli** [comment]
@PaulYuuu could you help to review this. thanks a lot.

**Comment by PaulYuuu** [comment]
This is the netperf pkg issue, and should be handled at the upper level. @yanglei-rh, I think you can update the status of this.

**Comment by yanglei-rh** [comment]
> This is the netperf pkg issue, and should be handled at the upper level. @yanglei-rh, I think you can update the status of this.

Thanks for reminder, I will update this to upstream bug.

**Review by PaulYuuu — APPROVED** [review]

**Pull request merged**
