### PR TITLE
qemu.tests: Use dhclient -r to release the current lease

### PR DESCRIPTION
**Pull request by ypu**
As pkill will failed in our test sometime. So use dhclient -r to
exit the dhclient process in system.

### CODE REVIEW

**Comment by ypu** [comment]
ID: 1081151

**Comment by CongSmile** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by spcui** [comment]
LGTM
Acked-by: @spcui

**Comment by ypu** [comment]
Thanks @CongSmile and @spcui will merge it.

**Pull request merged**
