### PR TITLE
resolve latest kernel installation dependency problems of RHEL7.3

### PR DESCRIPTION
**Pull request by PyLearner**
ID:1350706

### CODE REVIEW

**Comment by PyLearner** [comment]
smp_8.16384m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.rh_kernel_update: PASS (953.99 s)

log:

06:01:07 DEBUG| Sending command: rpm -q --whatrequires xfsprogs --queryformat='%{NAME}
'
06:01:07 DEBUG| Running 'brew latest-pkg rhel-7.3-candidate xfsprogs --arch=x86_64 --paths'
06:01:09 DEBUG| Brew URL is http://download.devel.redhat.com/brewroot/packages/xfsprogs/4.5.0/4.el7/x86_64/xfsprogs-4.5.0-4.el7.x86_64.rpm
06:01:09 DEBUG| Brew URL is http://download.devel.redhat.com/brewroot/packages/xfsprogs/4.5.0/4.el7/x86_64/xfsprogs-debuginfo-4.5.0-4.el7.x86_64.rpm
06:01:09 DEBUG| Brew URL is http://download.devel.redhat.com/brewroot/packages/xfsprogs/4.5.0/4.el7/x86_64/xfsprogs-devel-4.5.0-4.el7.x86_64.rpm
06:01:09 INFO | Install packages from: http://download.devel.redhat.com/brewroot/packages/xfsprogs/4.5.0/4.el7/x86_64/xfsprogs-4.5.0-4.el7.x86_64.rpm
06:01:09 DEBUG| Sending command: rpm -Uvhf http://download.devel.redhat.com/brewroot/packages/xfsprogs/4.5.0/4.el7/x86_64/xfsprogs-4.5.0-4.el7.x86_64.rpm --nodeps
06:01:18 DEBUG| Sending command: echo $?
06:01:18 INFO | Install packages from: http://download.devel.redhat.com/brewroot/packages/xfsprogs/4.5.0/4.el7/x86_64/xfsprogs-devel-4.5.0-4.el7.x86_64.rpm
06:01:18 DEBUG| Sending command: rpm -Uvhf http://download.devel.redhat.com/brewroot/packages/xfsprogs/4.5.0/4.el7/x86_64/xfsprogs-devel-4.5.0-4.el7.x86_64.rpm --nodeps

**Comment by CongLi** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by CongLi** [comment]
Thanks @PyLearner

**Comment by ngu-niny** [comment]
Acked-by: Nini Gu <ngu@redhat.com>

Now the rh_kernel_update function works correctly.

**Pull request merged**
