### PR TITLE
virtio_fs: new case of winfsp-tests suit

### PR DESCRIPTION
**Pull request by xiagao**
Add new case of winfsp-tests on shred directory for windows guest.
ID: 2130452
Signed-off-by: Xiaoling Gao <xiagao@redhat.com>

### CODE REVIEW

**Comment by xiagao** [comment]
(1/1) Host_RHEL.m9.u2.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.virtio_fs_winfsp_test.q35: STARTED
 (1/1) Host_RHEL.m9.u2.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.virtio_fs_winfsp_test.q35: PASS (152.75 s)

**Comment by xiagao** [comment]
@leidwang @YongxueHong  Pls have a look, thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Review by leidwang — APPROVED** [review]
LGTM.

**Pull request merged**
