### PR TITLE
tp-qemu: mq_max_queues: RHEL.6 host does not support multi host.

### PR DESCRIPTION
**Pull request by CongSmile**
Signed-off-by: Cong Li <coli@redhat.com>

### CODE REVIEW

**Comment by CongSmile** [comment]
id: 1214593

**Comment by spcui** [comment]
LGTM
Acked-by: @spcui

**Comment by PyLearner** [comment]
Works for me ,case will be not parsed now .

**Comment by xutian** [comment]
thanks @CongSmile , @spcui  and @PyLearner. merged

**Pull request merged**
