### PR TITLE
qemu.tests: Add rescan after hot unplug and timeout for commands runn…

### PR DESCRIPTION
**Pull request by ypu**
…ing in guest

As some device need manually rescan disk inside guest after hot unplug, so add the step
to the script.
Also add timeout for the disk operations in the test as sometime the commands need more
time to finish.

### CODE REVIEW

**Comment by ypu** [comment]
ID: 1231017

**Comment by XueqiangWei** [comment]
LGTM,
Acked by Xueqiang Wei <xuwei@redhat.com>

**Comment by spcui** [comment]
Acked-by: <scui@redhat.com>

**Comment by xutian** [comment]
thanks @ypu  @XueqiangWei  and @spcui. Merged.

**Pull request merged**
