### PR TITLE
numa.numa_stress: Get tmpfs_write_speed of the host

### PR DESCRIPTION
**Pull request by huangyum**
Get the speed of "dd if=/dev/urandom of=tmpfs"  on host, in order to get appropriate timeout.

ID: 1404125
Signed-off-by: Yumei Huang <yuhuang@redhat.com>

### CODE REVIEW

**Comment by huangyum** [comment]
@MiriamDeng could you please help review ? Thanks!

**Comment by xutian** [comment]
Not a good idea to set  default speed.  how about pre-create 1M file to get a actual speed, then count a timeout value ?

**Comment by MiriamDeng** [comment]
From my opinion,it there an effective way to check the speed before executing this command ?After all we need to execute the script on different hosts.

**Comment by huangyum** [comment]
Thanks @xutian @MiriamDeng , updated, please help review again.

**Pull request closed without merging**
