### PR TITLE
qemu_img: Support nvme storage backend for creating test

### PR DESCRIPTION
**Pull request by YongxueHong**
Support nvme storage backend for creating test.

ID: 1850608
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by YongxueHong** [comment]
Depends on https://github.com/avocado-framework/avocado-vt/pull/2608

**Comment by YongxueHong** [comment]
Hi, @XueqiangWei 
Please help me to review, thanks.

**Comment by XueqiangWei** [comment]
@YongxueHong run test cases with below command line, just get qcow2 and luks related cases. I'm not sure whether the command line is correct. Please help check it. Many thanks.

python3 ConfigTest.py --testcase=qemu_img.create --guestname=RHEL.8.3.0 --driveformat=virtio_scsi --nicmodel=virtio_net  --imageformat=qcow2,raw,nvme,luks --nvme_pci_address=0000:bc:00.0 --image_backend=nvme_direct --clone=no

(01/24) Host_RHEL.m8.u2.nvme_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.non-preallocated: CANCEL: Test cancelled due to --dry-run (0.01 s)
 (02/24) Host_RHEL.m8.u2.nvme_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.non-preallocated.cluster_size.cluster_512: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (03/24) Host_RHEL.m8.u2.nvme_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.non-preallocated.cluster_size.cluster_1024: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (04/24) Host_RHEL.m8.u2.nvme_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.non-preallocated.cluster_size.cluster_4096: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (05/24) Host_RHEL.m8.u2.nvme_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.non-preallocated.cluster_size.cluster_1M: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (06/24) Host_RHEL.m8.u2.nvme_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.non-preallocated.cluster_size.cluster_2M: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (07/24) Host_RHEL.m8.u2.nvme_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.preallocated: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (08/24) Host_RHEL.m8.u2.nvme_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.preallocated.cluster_size.cluster_512: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (09/24) Host_RHEL.m8.u2.nvme_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.preallocated.cluster_size.cluster_1024: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (10/24) Host_RHEL.m8.u2.nvme_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.preallocated.cluster_size.cluster_4096: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (11/24) Host_RHEL.m8.u2.nvme_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.preallocated.cluster_size.cluster_1M: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (12/24) Host_RHEL.m8.u2.nvme_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.preallocated.cluster_size.cluster_2M: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (13/24) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.non-preallocated: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (14/24) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.non-preallocated.cluster_size.cluster_512: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (15/24) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.non-preallocated.cluster_size.cluster_1024: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (16/24) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.non-preallocated.cluster_size.cluster_4096: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (17/24) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.non-preallocated.cluster_size.cluster_1M: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (18/24) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.non-preallocated.cluster_size.cluster_2M: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (19/24) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.preallocated: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (20/24) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.preallocated.cluster_size.cluster_512: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (21/24) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.preallocated.cluster_size.cluster_1024: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (22/24) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.preallocated.cluster_size.cluster_4096: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (23/24) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.preallocated.cluster_size.cluster_1M: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (24/24) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.preallocated.cluster_size.cluster_2M: CANCEL: Test cancelled due to --dry-run (0.00 s)


Test results:
luks, not support, tracked by product bug.
qcow2, 2 test cases are failed. tracked by product bug.

(01/12) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.non-preallocated: PASS (7.06 s)
 (02/12) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.non-preallocated.cluster_size.cluster_512: PASS (27.14 s)
 (03/12) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.non-preallocated.cluster_size.cluster_1024: PASS (16.88 s)
 (04/12) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.non-preallocated.cluster_size.cluster_4096: PASS (9.28 s)
 (05/12) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.non-preallocated.cluster_size.cluster_1M: PASS (6.82 s)
 (06/12) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.non-preallocated.cluster_size.cluster_2M: PASS (6.83 s)
 (07/12) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.preallocated: PASS (6.88 s)
 (08/12) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.preallocated.cluster_size.cluster_512: ERROR: Failed to create image nvme://0000:bc:00.0/1\ncommand: '/usr/bin/qemu-img create -f qcow2 -o preallocation=metadata,cluster_size=512 nvme://0000:bc:00.0/1 2G'\nexit_status: 1\nduration: 4.411943674087524\ninterrupted: False\npid: 53122\nencoding: 'UTF-8'\nstdout... (16.59 s)
 (09/12) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.preallocated.cluster_size.cluster_1024: ERROR: Failed to create image nvme://0000:bc:00.0/1\ncommand: '/usr/bin/qemu-img create -f qcow2 -o preallocation=metadata,cluster_size=1024 nvme://0000:bc:00.0/1 2G'\nexit_status: 1\nduration: 4.234623432159424\ninterrupted: False\npid: 53232\nencoding: 'UTF-8'\nstdou... (13.03 s)
 (10/12) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.preallocated.cluster_size.cluster_4096: PASS (10.74 s)
 (11/12) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.preallocated.cluster_size.cluster_1M: PASS (6.83 s)
 (12/12) Host_RHEL.m8.u2.nvme_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.qemu_img.create.preallocated.cluster_size.cluster_2M: PASS (6.89 s)

**Comment by YongxueHong** [comment]
Hi @XueqiangWei 
For the new format, we did not consider to add it as talked with @CongLi .
Please refer to https://github.com/avocado-framework/avocado-vt/pull/2608#discussion_r448796184
Thanks.
CC @CongLi

**Comment by XueqiangWei** [comment]
> Hi @XueqiangWei
> For the new format, we did not consider to add it as talked with @CongLi .
> Please refer to [avocado-framework/avocado-vt#2608 (comment)](https://github.com/avocado-framework/avocado-vt/pull/2608#discussion_r448796184)
> Thanks.
> CC @CongLi 
OK, got it. I have no other question. 

LGTM,
Acked-by: xuwei@redhat.com

**Pull request merged**
