### PR TITLE
nmi_bsod_catch: fix a bug on win10.i386

### PR DESCRIPTION
**Pull request by leidwang**
windbg install path is different between x64 and i386, so update the configuration file to fix the error.

ID:2218864

### CODE REVIEW

**Comment by leidwang** [comment]
Windbg can be installed with this patch, but seems this case still has some other errors.I will try to fix it first.

**Comment by leidwang** [comment]
@menli820 Could you please help to review this patch?Thanks!

**Comment by menli820** [comment]
LGTM， thanks！ 

(01/10) repeat1.Host_RHEL.m9.u3.qcow2.virtio_blk.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.nmi_bsod_catch.q35: STARTED
 (01/10) repeat1.Host_RHEL.m9.u3.qcow2.virtio_blk.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.nmi_bsod_catch.q35: PASS (304.24 s)
 (02/10) repeat2.Host_RHEL.m9.u3.qcow2.virtio_blk.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.nmi_bsod_catch.q35: STARTED
 (02/10) repeat2.Host_RHEL.m9.u3.qcow2.virtio_blk.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.nmi_bsod_catch.q35: PASS (303.73 s

**Review by menli820 — APPROVED** [review]

**Comment by leidwang** [comment]
@peixiu Could you help to review this patch?

**Comment by peixiu** [comment]
python ConfigTest.py --testcase=nmi_bsod_catch --guestname=Win10 --platform=i386 --firmware=default_bios --clone=yes

 (1/2) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: STARTED
 (1/2) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (708.71 s)
 (2/2) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.nmi_bsod_catch.q35: STARTED
 (2/2) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.nmi_bsod_catch.q35: PASS (508.81 s)

LGTM~
Acked-by: Peixiu Hou phou@redhat.com

**Review by peixiu — APPROVED** [review]

**Comment by leidwang** [comment]
Hi @vivianQizhu Could you help to review this patch?Thanks

**Comment by vivianQizhu** [comment]
This is okay but I would prefer have a uniformed params for the directory 'Program Files (x86)', let's have the hotfix first and another patch for the universal changes later.

**Review by vivianQizhu — APPROVED** [review]

**Pull request merged**
