### PR TITLE
virtio_scsi_cdrom: Support 32 bit guest

### PR DESCRIPTION
**Pull request by YongxueHong**
ID: 1694944
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by YongxueHong** [comment]
@CongLi  @kimi1978wy  @peixiu  if you are free , pls help review, thanks.

**Comment by CongLi** [comment]
It should work for linux 32 bit guest, please update the commit log.

**Comment by CongLi** [comment]
Ack.

**Comment by peixiu** [comment]
Acked-by: Peixiu Hou phou@redhat.com

**Comment by kimi1978wy** [comment]
Acked-by: Yu Wang <wyu@redhat.com>

**Comment by YongxueHong** [comment]
Thanks all.

**Pull request merged**
