### PR TITLE
virtio_mode: remove rhel6 guest from modern driver case

### PR DESCRIPTION
**Pull request by huangyum**
ID: 1728098
Signed-off-by: Yumei Huang <yuhuang@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
@jingzhao84  I remember, rhel6 guest are suggested to test with `transitional`, how about `legacy` ?

**Comment by jingzhao84** [comment]
@yanan-fu if you boot up rhel6 guest with q35 machine type, please use virtio-*-transitional controller

**Comment by jingzhao84** [comment]
@huangyum we can use virtio-*-transitional controller when test rhel6 guest.  i think you don't need to test rhel6 with legacy

**Comment by huangyum** [comment]
@jingzhao84 Seems if boot rhel6 with virtio-balloon-pci, it will use 0.9 driver by default and work normally. IIUC, as long as it uses 0.9 driver, it would be fine. Do you agree? Or do you think we can just skip all the virtio_mode cases with rhel6 guest?

**Comment by jingzhao84** [comment]
@huangyum yes I think so

**Comment by jingzhao84** [comment]
ack-by jinzhao@redhat.com

**Pull request merged**
