### PR TITLE
disable windows guest for case uefi_check_debugcon

### PR DESCRIPTION
**Pull request by XueqiangWei**
ID: 1823802
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>

### CODE REVIEW

**Comment by XueqiangWei** [comment]
run with linux and windows guest, filter out windows guest.

python3 ConfigTest.py --testcase=uefi_check_debugcon  --guestname=RHEL.8.1.0,Win2019 --platform=x86_64 --driveformat=virtio_scsi  --nicmodel=virtio_net --imageformat=qcow2  --machine=q35 --firmware=ovmf --clone=no --dryrun
 (1/2) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.uefi_check_debugcon.disable.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (2/2) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.uefi_check_debugcon.enable.q35: CANCEL: Test cancelled due to --dry-run (0.01 s)

**Comment by XueqiangWei** [comment]
@leidwang please help review it. Many thanks.

**Comment by leidwang** [comment]
> @leidwang please help review it. Many thanks.

LGTM

**Comment by yanan-fu** [comment]
Ack

**Pull request merged**
