### PR TITLE
x86_cpu_flags: fix incorrect dies topology issue

### PR DESCRIPTION
**Pull request by nanliu-r**
ID: 1900974

Signed-off-by: Nana Liu <nanliu@redhat.com>

### CODE REVIEW

**Comment by nanliu-r** [comment]
@yanan-fu  please help to review this, thanks a lot.

**Comment by yanan-fu** [comment]
Suggest `filter out this case for RHEL8.1` to explain the specific modification.

**Comment by nanliu-r** [comment]
> Suggest `filter out this case for RHEL8.1` to explain the specific modification.

How about this output?
type_specific.io-github-autotest-qemu.x86_cpu_flags.others.test_dies: CANCEL: Current guest's kernel doesn't support 'die'. (2.24 s)

**Comment by yanan-fu** [comment]
> > Suggest `filter out this case for RHEL8.1` to explain the specific modification.
> 
> How about this output?
> type_specific.io-github-autotest-qemu.x86_cpu_flags.others.test_dies: CANCEL: Current guest's kernel doesn't support 'die'. (2.24 s)

I think no need, the pre fix is enough, the comment i added before if for the commit title :)

**Comment by nanliu-r** [comment]
> > > Suggest `filter out this case for RHEL8.1` to explain the specific modification.
> > 
> > 
> > How about this output?
> > type_specific.io-github-autotest-qemu.x86_cpu_flags.others.test_dies: CANCEL: Current guest's kernel doesn't support 'die'. (2.24 s)
> 
> I think no need, the pre fix is enough, the comment i added before if for the commit title :)

Thanks and update.

**Review by yanan-fu — APPROVED** [review]
Ack

**Pull request merged**
