### PR TITLE
Fix inspekt checking failures for Python 3.9

### PR DESCRIPTION
**Pull request by misanjumn**
Fixup inspekt checking failures in the latest python 3.9 job 
Use isinstance() for comparing types

Signed-off-by: Misbah Anjum N <misanjum@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by misanjumn** [comment]
The new PRs being submitted are failing Python 3.9 inspekt check.
This is the following issue

```
Run inspekt checkall --disable-style E501,E265,W601,E402,E722,E741 --disable-lint=W,R,C,E0601,E1002,E1101,E1103,E1120,F0401,I0011,I1101 --enable-lint W0611,W1201 --no-license-check
PEP8 disabled: E501,E265,W601,E402,E722,E741
Pylint disabled: W,R,C,E0601,E1002,E[11](https://github.com/autotest/tp-qemu/actions/runs/5737113286/job/15548089523?pr=3756#step:6:12)01,E1103,E1[12](https://github.com/autotest/tp-qemu/actions/runs/5737113286/job/15548089523?pr=3756#step:6:13)0,F0401,I0011,I1101
Pylint enabled : W0611,W1201
License check: disabled
/home/runner/work/tp-qemu/tp-qemu/qemu/deps/win_serial/VirtIoChannel_guest_recieve.py:70:12: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
Style: /home/runner/work/tp-qemu/tp-qemu/qemu/deps/win_serial/VirtIoChannel_guest_recieve.py FAIL 
/home/runner/work/tp-qemu/tp-qemu/qemu/deps/win_serial/VirtIoChannel_guest_recieve.py:72:12: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
Global check FAIL

------------------------------------
Your code has been rated at 10.00/10

Error: Process completed with exit code 1.
```

**Comment by zhenyzha** [comment]
@yanan-fu @PaulYuuu Could you pls help review when you are free. thanks.

**Review by PaulYuuu — APPROVED** [review]

**Comment by misanjumn** [comment]
> Hello @misanjumn, can you rebase your branch instead of merge it? Such as using `git pull <remote> master --rebase`, so that you will only have one commit in this PR.

Hi, let me fix the commit issue. Sorry for the trouble, I am pretty new to this.
Thanks.

**Comment by misanjumn** [comment]
> Hello @misanjumn, can you rebase your branch instead of merge it? Such as using `git pull <remote> master --rebase`, so that you will only have one commit in this PR.

@PaulYuuu I have pushed the changes into single commit by using git rebase as you instructed. Can you review it now. Thank You.

**Review by yanan-fu — APPROVED** [review]
Sorry for the late response!   LGTM

**Comment by yanan-fu** [comment]
Except the code rebase,  no new code change after @PaulYuuu approved this patch.

Let's merge it now, thanks all!

**Comment by misanjumn** [comment]
> Except the code rebase, no new code change after @PaulYuuu approved this patch.
> 
> Let's merge it now, thanks all!

Thank You!

**Pull request merged**
