### PR TITLE
Intel_iommu: add x2apic support

### PR DESCRIPTION
**Pull request by JinLiul**
Set eim=on in x2apic mode.

ID: 2284

### CODE REVIEW

**Comment by JinLiul** [comment]
(1/3) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.guest_iommu_test.x2apic.q35: STARTED
 (1/3) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.guest_iommu_test.x2apic.q35: PASS (152.45 s)
 (2/3) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.guest_iommu_test.x2apic.scenario1.q35: STARTED
 (2/3) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.guest_iommu_test.x2apic.scenario1.q35: PASS (118.35 s)
 (3/3) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.guest_iommu_test.x2apic.scenario2.q35: STARTED
 (3/3) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.guest_iommu_test.x2apic.scenario2.q35: PASS (83.34 s)

**Comment by JinLiul** [comment]
(1/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: STARTED
 (1/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (1522.82 s)
 (2/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.guest_iommu_test.x2apic.q35: STARTED
 (2/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.guest_iommu_test.x2apic.q35: PASS (136.88 s)

**Comment by JinLiul** [comment]
Hi @XueqiangWei  Could you please help to review? Thanks.

**Comment by XueqiangWei** [comment]
(1/3) Host_RHEL.m10.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.guest_iommu_test.x2apic.q35: STARTED
 (1/3) Host_RHEL.m10.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.guest_iommu_test.x2apic.q35: PASS (155.92 s)
 (2/3) Host_RHEL.m10.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.guest_iommu_test.x2apic.scenario1.q35: STARTED
 (2/3) Host_RHEL.m10.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.guest_iommu_test.x2apic.scenario1.q35: PASS (183.72 s)
 (3/3) Host_RHEL.m10.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.guest_iommu_test.x2apic.scenario2.q35: STARTED
 (3/3) Host_RHEL.m10.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.guest_iommu_test.x2apic.scenario2.q35: PASS (184.44 s)

**Comment by XueqiangWei** [comment]
(1/1) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.guest_iommu_test.x2apic.q35: STARTED
 (1/1) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.guest_iommu_test.x2apic.q35: PASS (150.61 s)

**Comment by XueqiangWei** [comment]
(1/1) Host_RHEL.m10.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.guest_iommu_test.x2apic.q35: STARTED
 (1/1) Host_RHEL.m10.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.guest_iommu_test.x2apic.q35: PASS (163.11 s)

**Comment by XueqiangWei** [comment]
We usually use the format “case name: ***” in commit header. Thanks.

**Comment by JinLiul** [comment]
Updated the commit message. Thanks.

**Review by XueqiangWei — APPROVED** [review]
LGTM,
Acked-by: xuwei@redhat.com

**Pull request merged**
