### PR TITLE
drive_mirror_negtive_tests: remove the duplicate variant and modified commands

### PR DESCRIPTION
**Pull request by luckyh**
Remove the duplicate variant and modified commands.

ID: 1263067

### CODE REVIEW

**Comment by PyLearner** [comment]
Acked-by : Meng Yang meyang@redhat.com

**Comment by vivianQizhu** [comment]
Acked-by : Qianqian Zhu qizhu@redhat.com

**Comment by PandaWei** [comment]
The content of PR is good.
But the title of commit  is appropriate, 
Your explanation "Remove the duplicate variant and modified commands." looks more better.

commit 218833b645d646c5c2ab715cc763edf2b18bc1d9
Author: Xu Han <xuhan@redhat.com>
Date:   Wed Jun 29 15:22:48 2016 +0800

    drive_mirror_negtive_tests: fix the typo
    
    Signed-off-by: Xu Han <xuhan@redhat.com>

**Comment by luckyh** [comment]
Okay, updated.

**Comment by PandaWei** [comment]
Thanks @luckyh @PyLearner @vivianQizhu

**Pull request merged**
