### PR TITLE
Block mirror with '"on-source-error": "stop", "on-target-error": "stop"'

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1877748

### CODE REVIEW

**Comment by zhencliu** [comment]
local fs:
 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_error: PASS (134.31 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-10T11.01-011032f/results.html
JOB TIME   : 140.23 s

nbd:
 (1/1) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_error: PASS (167.09 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-10T11.20-6378650/results.html
JOB TIME   : 172.41 s

iscsi direct:
 (1/1) Host_RHEL.m8.u3.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_error: PASS (142.25 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-10T11.26-862a02b/results.html
JOB TIME   : 147.87 s

gluster direct:
 (1/1) Host_RHEL.m8.u2.product_av.gluster_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_error: PASS (250.34 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2020-09-10T23.28-fa8133b/results.html
JOB TIME   : 264.86 s

hi @aliang123 @YongxueHong , can you please help to review the patch? Thanks much.
Also, this patch deps on #2379 , please ignore the CI check error.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_error.q35: FAIL: AssertionError("wait job status to 'paused' timeout in 300 seconds",) (508.30 s)

Acked-by: Aihua Liang <aliang@redhat.com>

**Comment by ngu-niny** [comment]
On ppc, get the same error as x86 for a product bug:

FAIL 8-Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.blockdev_mirror_error -> TestFail: AssertionError("wait job status to 'paused' timeout in 300 seconds",)

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
