### PR TITLE
balloon_hotplug: add balloon device addr for migraiton cases

### PR DESCRIPTION
**Pull request by huangyum**
ID: 1645981
Signed-off-by: Yumei Huang <yuhuang@redhat.com>
Depends on https://github.com/avocado-framework/avocado-vt/pull/1929

### CODE REVIEW

**Comment by huangyum** [comment]
@MiriamDeng Please help review and test it on ppc host. Thanks.

**Comment by MiriamDeng** [comment]
@ huangyum ,could you please re-check this pr since it didn't work as expected.Still failed in my side.

**Comment by huangyum** [comment]
@MiriamDeng Could you please show me the error log, thanks.

**Comment by huangyum** [comment]
Turns out the hotplugged device's addr is 0x0 on ppc while devs[0]["addr"] is 0x6.  Tried to assign 0x0 directly, and guest failed to boot due to address conflict.  Close this one.

**Comment by MiriamDeng** [comment]
Thanks for your feedback.

**Pull request closed without merging**
