### PR TITLE
blockdev_full_backup_invalid_sync_mode: Full backup with invalid sync mode

### PR DESCRIPTION
**Pull request by aliang123**
Signed-off-by: Aihua Liang <aliang@redhat.com>
id:1982582

### CODE REVIEW

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.blockdev_full_backup_invalid_sync_mode.q35: PASS (40.66 s)

**Comment by aliang123** [comment]
@zhencliu @ngu-niny please help to review, thanks

**Comment by zhencliu** [comment]
Hi @aliang123 , the commit msg is too long, the others look good

**Comment by aliang123** [comment]
@zhenchao， have updated, thanks

**Comment by zhencliu** [comment]
LGTM

**Comment by ngu-niny** [comment]
(1/2) Host_RHEL.m8.u5.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.blockdev_full_backup_invalid_sync_mode: PASS (87.98 s)
 (2/2) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.blockdev_full_backup_invalid_sync_mode: PASS (98.57 s)

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
