### PR TITLE
Change image_chain to image_backup_chain for backup use

### PR DESCRIPTION
**Pull request by zhencliu**
image_chain is used for showing the backing info between images

Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1861951

### CODE REVIEW

**Comment by zhencliu** [comment]
(01/21) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_512: PASS (177.14 s)
 (02/21) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_8K: PASS (185.30 s)
 (03/21) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_16M: PASS (184.68 s)
 (04/21) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_64M: PASS (182.91 s)
 (05/21) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_2G: PASS (182.84 s)
 (06/21) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_random: PASS (1312.72 s)
 (07/21) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup: PASS (200.49 s)
 (08/21) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_data_disks: PASS (237.34 s)
 (09/21) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_data_disks.grouped_complete: PASS (236.43 s)
 (10/21) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_data_disks.negative_test: FAIL: ShellTimeoutError('dd if=/dev/urandom of=/mnt/sdc1/jo7d bs=4k count=327680 oflag=direct', '') (1009.10 s)
 (11/21) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_data_disks.negative_test.grouped_complete: FAIL: ShellTimeoutError('dd if=/dev/urandom of=/mnt/sdc1/KAJp bs=4k count=327680 oflag=direct', '') (1010.18 s)
 (12/21) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_data_disks.manual_complete: PASS (215.47 s)
 (13/21) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_data_disks.manual_complete.grouped_complete: PASS (216.82 s)
 (14/21) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_bitmap_mode.bitmap_always: PASS (127.37 s)
 (15/21) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_bitmap_mode.bitmap_never: PASS (125.16 s)
 (16/21) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_bitmap_mode.bitmap_success: PASS (122.48 s)
 (17/21) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_bitmap_mode.bitmap_top: PASS (128.20 s)
 (18/21) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_cluster.inc_cluster_size.size_512: PASS (195.71 s)
 (19/21) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_cluster.inc_cluster_size.size_4K: PASS (182.82 s)
 (20/21) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_cluster.inc_cluster_size.size_2M: PASS (179.75 s)
 (21/21) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_cluster.inc_cluster_size: PASS (181.61 s)
RESULTS    : PASS 19 | ERROR 0 | FAIL 2 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-07-29T04.36-17caa2b/results.html
JOB TIME   : 6603.87 s

**Comment by zhencliu** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_pull_mode: PASS (209.19 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-07-29T07.56-ed29d7b/results.html
JOB TIME   : 214.26 s

**Comment by zhencliu** [comment]
(01/22) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_bitmap_mode.bitmap_always: PASS (122.65 s)
 (02/22) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_bitmap_mode.bitmap_never: PASS (123.61 s)
 (03/22) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_bitmap_mode.bitmap_success: PASS (122.87 s)
 (04/22) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_bitmap_mode.bitmap_top: PASS (124.98 s)
 (05/22) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_512: PASS (181.19 s)
 (06/22) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_8K: PASS (181.46 s)
 (07/22) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_16M: PASS (189.49 s)
 (08/22) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_64M: PASS (182.71 s)
 (09/22) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_2G: PASS (182.88 s)
 (10/22) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_random: PASS (1274.89 s)
 (11/22) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup: PASS (209.89 s)
 (12/22) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_data_disks: PASS (235.89 s)
 (13/22) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_data_disks.grouped_complete: PASS (221.77 s)
 (14/22) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_data_disks.negative_test: FAIL: ShellTimeoutError('dd if=/dev/urandom of=/mnt/sdc1/jy93 bs=4k count=327680 oflag=direct', '') (1015.71 s)
 (15/22) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_data_disks.negative_test.grouped_complete: FAIL: ShellTimeoutError('dd if=/dev/urandom of=/mnt/sdc1/zvdu bs=4k count=327680 oflag=direct', '') (1006.30 s)
 (16/22) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_data_disks.manual_complete: PASS (212.57 s)
 (17/22) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_data_disks.manual_complete.grouped_complete: PASS (223.11 s)
 (18/22) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_pull_mode: PASS (200.03 s)
 (19/22) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_cluster.inc_cluster_size.size_512: PASS (203.62 s)
 (20/22) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_cluster.inc_cluster_size.size_4K: PASS (185.25 s)
 (21/22) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_cluster.inc_cluster_size.size_2M: PASS (180.60 s)
 (22/22) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_cluster.inc_cluster_size: PASS (186.22 s)
RESULTS    : PASS 20 | ERROR 0 | FAIL 2 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-07-30T09.19-1782596/results.html
JOB TIME   : 6776.74 s

**Comment by zhencliu** [comment]
hi @YongxueHong @aliang123 , can you please help to review the code change, it's a fix instead of a new case, thanks.

**Comment by aliang123** [comment]
Acked-by: Aihua Liang <aliang@redhat.com>
cfg: blockdev_inc_backup_bitmap_mode
(1/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_bitmap_mode.bitmap_always.q35: PASS (65.12 s)
 (2/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_bitmap_mode.bitmap_never.q35: PASS (78.69 s)
 (3/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_bitmap_mode.bitmap_success.q35: PASS (82.02 s)
 (4/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_bitmap_mode.bitmap_top.q35: PASS (81.56 s)

cfg: blockdev_inc_backup_cluster
(1/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_cluster.inc_cluster_size.size_512.q35: PASS (118.61 s)
 (2/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_cluster.inc_cluster_size.size_4K.q35: PASS (110.64 s)
 (3/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_cluster.inc_cluster_size.size_2M.q35: PASS (101.12 s)
 (4/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_cluster.inc_cluster_size.q35: PASS (101.76 s)

cfg:blockdev_inc_backup
(01/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_512.q35: PASS (111.73 s)
 (02/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_8K.q35: PASS (99.65 s)
 (03/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_16M.q35: PASS (99.76 s)
 (04/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_64M.q35: PASS (101.62 s)
 (05/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_2G.q35: PASS (100.72 s)
 (06/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_random.q35: PASS (593.69 s)
 (07/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.q35: PASS (100.49 s)
 (08/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_data_disks.q35: PASS (119.38 s)
 (09/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_data_disks.grouped_complete.q35: PASS (134.18 s)
 (10/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_data_disks.negative_test.q35: FAIL: QMPCmdError('transaction', {'actions': [{'type': 'blockdev-backup', 'data': {'device': 'drive_data', 'target': 'drive_inc', 'job-id': 'drive_data_Touh', 'sync': 'incremental', 'speed': 0, 'compress': False, 'auto-finalize': True, 'auto-dismiss': True, 'on... (230.79 s)
 (11/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_data_disks.negative_test.grouped_complete.q35: FAIL: QMPCmdError('transaction', {'actions': [{'type': 'blockdev-backup', 'data': {'device': 'drive_data', 'target': 'drive_inc', 'job-id': 'drive_data_CevB', 'sync': 'incremental', 'speed': 0, 'compress': False, 'auto-finalize': True, 'auto-dismiss': True, 'on... (238.05 s)
 (12/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_data_disks.manual_complete.q35: PASS (135.08 s)
 (13/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_data_disks.manual_complete.grouped_complete.q35: PASS (134.74 s)
(12,13) failed for existed auto bugs: Bug 1845865 - [KVM_AUTOTEST]Incremental_live_backup:update test step for behavior change "src and dst should have same size" when do backup

cfg:blockdev_inc_backup_pull_mode
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_pull_mode.q35: PASS (127.68 s)

**Pull request merged**
