### PR TITLE
add windows support for case remote_image_snapshot

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>
ID: 2111985

### CODE REVIEW

**Comment by XueqiangWei** [comment]
Tested with windows2019, all work well.

(1/1) Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (4397.49 s)

(1/2) Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_snapshot.to_local.q35: STARTED
 (1/2) Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_snapshot.to_local.q35: PASS (290.71 s)
 (2/2) Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_snapshot.to_remote.q35: STARTED
 (2/2) Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_snapshot.to_remote.q35: PASS (391.85 s)

**Comment by XueqiangWei** [comment]
@hellohellenmao @zhencliu Please help review it. Many thanks.

**Comment by zhencliu** [comment]
LGTM

**Comment by hellohellenmao** [comment]
1-Host_RHEL.m9.u1.ovmf.ceph.raw.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35 Finshed 2022-07-28 22:06:58 2022-07-28 23:34:18 PASS 5240.23663
2-Host_RHEL.m9.u1.ovmf.ceph.raw.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.remote_image_snapshot.to_local.q35 Finshed 2022-07-28 23:34:19 2022-07-28 23:42:08 PASS 469.096643
3-Host_RHEL.m9.u1.ovmf.ceph.raw.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.remote_image_snapshot.to_remote.q35 Finshed 2022-07-28 23:42:09 2022-07-28 23:51:53 PASS 583.723466

Ack. Thanks.

**Pull request merged**
