### PR TITLE
ntttcp.cfg: need not use numa_node for this case

### PR DESCRIPTION
**Pull request by kimi1978wy**
delete "numa_node = -1"

Signed-off-by: Yu Wang <wyu@redhat.com>

id:1709635

### CODE REVIEW

**Comment by kimi1978wy** [comment]
(1/1) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win7.x86_64.io-github-autotest-qemu.ntttcp.q35: PASS (1140.55 s)

**Comment by kimi1978wy** [comment]
@peixiu @xiywang Could you help to review this patch?

**Comment by peixiu** [comment]
Acked-by: Peixiu Hou phou@redhat.com

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

**Pull request merged**
