### PR TITLE
Adjust multi_disk test and cgroup tests to work on PPC64

### PR DESCRIPTION
**Pull request by ldoktor**
Hi guys,

the multi_disk test worked almost out of the box, it only doesn't support some of the drive formats.

The cgroup test is a bit trickier as it's more often to see sparse cpu/mem layouts on PPC. I used a class to map sparse definition to list (and back) to support various layouts and tested it on PPC64 and it works fine.

Additionally I tweaked the test to decrease the number of false-negatives (while avoiding false-positives) so now it should work better on x86 too.

__Beware: On x86_64 F20 the `blkio_throttle` test causes kernel panic (reported) and you might want to set `migrate_vms = ""` as this test uses custom `vms` setup and you might end-up with unused VMS running in the background.__

### CODE REVIEW

**Comment by ldoktor** [comment]
OK, new pep8 released... Let me take care of Autotest libraries...

**Comment by ldoktor** [comment]
Incorporated the PEP8 fixes from: https://github.com/autotest/tp-qemu/pull/285

**Comment by ypu** [comment]
Others looks good to me.

**Comment by ldoktor** [comment]
Fixed the non-modified docstrings

**Comment by ypu** [comment]
Thanks @ldoktor LGTM
Acked-by:Yiqiao Pu <ypu@redhat.com>
and will merge it.

**Pull request merged**
