### PR TITLE
blockdev_commit_forbidden_actions:update resize err msg

### PR DESCRIPTION
**Pull request by aliang123**
Error msg for resizing during commit changed since qemu9.0, update the error msg to compatible with both old and new qemu version

id: 2295

Signed-off-by: Aihua Liang <aliang@redhat.com>

### CODE REVIEW

**Comment by aliang123** [comment]
- For qemu-kvm-9.0.0.el9
(1/1) Host_RHEL.m9.ux.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.x.0.x86_64.io-github-autotest-qemu.blockdev_commit_forbidden_actions.q35: PASS (58.04 s)

**Comment by aliang123** [comment]
@zhencliu @maxujun @XueqiangWei  , please help review it, thanks.

**Comment by aliang123** [comment]
- For RHEL8.8:
(1/1) Host_RHEL.m8.u8.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.x.0.x86_64.io-github-autotest-qemu.blockdev_commit_forbidden_actions.q35: PASS (74.08 s)

- For > RHEL9.4:
(1/1) Host_RHEL.m9.ux.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.x.0.x86_64.io-github-autotest-qemu.blockdev_commit_forbidden_actions.q35: PASS (58.36 s)

**Review by zhencliu — APPROVED** [review]

**Comment by XueqiangWei** [comment]
@maxujun Could you help review it? Many thanks.

**Comment by maxujun** [comment]
(1/1) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.ppc64le.io-github-autotest-qemu.blockdev_commit_forbidden_actions: STARTED
 (1/1) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.ppc64le.io-github-autotest-qemu.blockdev_commit_forbidden_actions: PASS (175.34 s)

LGTM.

**Pull request merged**
