### PR TITLE
block_vhost_vdpa_test:improve test

### PR DESCRIPTION
**Pull request by qingwangrh**
1. Combinate options cache/discard/detect_zeroes
2. Change DummyCMD to dd command for windows test
3. Fix aio to threads when cache direct is off

ID:2270,2451,2452

### CODE REVIEW

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=block_vhost_vdpa_test --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=RHEL.9.5.0 --driveformat=virtio_blk,virtio_scsi  --imageformat=qcow2 --machines=q35 --customsparams="vm_mem_limit = 12G\nimage_aio=native" --firmware=default_bios  --netdst=virbr0  --clone=no

(01/14) Host_RHEL.m9.u5.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.multi_disks.q35: STARTED
 (01/14) Host_RHEL.m9.u5.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.multi_disks.q35: PASS (58.93 s)
 (02/14) Host_RHEL.m9.u5.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.hotplug_unplug.q35: STARTED
 (02/14) Host_RHEL.m9.u5.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.hotplug_unplug.q35: PASS (60.05 s)
 (03/14) Host_RHEL.m9.u5.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_unmap.with_direct_on.q35: STARTED
 (03/14) Host_RHEL.m9.u5.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_unmap.with_direct_on.q35: FAIL: Shell command failed: 'mkdir -p /var/tmp/test && mkfs.xfs -f /dev/vdc  && mount -t xfs /dev/vdc /var/tmp/test && dd if=/dev/zero  of=/var/tmp/test/test.img bs=1M count=100 oflag=direct &&  umount /var/tmp/test'    (status: 1,    output: 'Filesystem should... (44.12 s)
 (04/14) Host_RHEL.m9.u5.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_unmap.with_direct_off.q35: STARTED
 (04/14) Host_RHEL.m9.u5.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_unmap.with_direct_off.q35: PASS (9.61 s)
 (05/14) Host_RHEL.m9.u5.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_ignore.with_direct_on.q35: STARTED
 (05/14) Host_RHEL.m9.u5.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_ignore.with_direct_on.q35: PASS (45.91 s)
 (06/14) Host_RHEL.m9.u5.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_ignore.with_direct_off.q35: STARTED
 (06/14) Host_RHEL.m9.u5.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_ignore.with_direct_off.q35: PASS (9.60 s)
 (07/14) Host_RHEL.m9.u5.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: STARTED
 (07/14) Host_RHEL.m9.u5.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: PASS (43.65 s)
 (08/14) Host_RHEL.m9.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.multi_disks.q35: STARTED
 (08/14) Host_RHEL.m9.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.multi_disks.q35: PASS (64.70 s)
 (09/14) Host_RHEL.m9.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.hotplug_unplug.q35: STARTED
 (09/14) Host_RHEL.m9.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.hotplug_unplug.q35: PASS (61.34 s)
 (10/14) Host_RHEL.m9.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_unmap.with_direct_on.q35: STARTED
 (10/14) Host_RHEL.m9.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_unmap.with_direct_on.q35: FAIL: Shell command failed: 'mkdir -p /var/tmp/test && mkfs.xfs -f /dev/sdc  && mount -t xfs /dev/sdc /var/tmp/test && dd if=/dev/zero  of=/var/tmp/test/test.img bs=1M count=100 oflag=direct &&  umount /var/tmp/test'    (status: 1,    output: 'Filesystem should... (44.22 s)
 (11/14) Host_RHEL.m9.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_unmap.with_direct_off.q35: STARTED
 (11/14) Host_RHEL.m9.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_unmap.with_direct_off.q35: PASS (9.68 s)
 (12/14) Host_RHEL.m9.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_ignore.with_direct_on.q35: STARTED
 (12/14) Host_RHEL.m9.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_ignore.with_direct_on.q35: PASS (45.68 s)
 (13/14) Host_RHEL.m9.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_ignore.with_direct_off.q35: STARTED
 (13/14) Host_RHEL.m9.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_ignore.with_direct_off.q35: PASS (9.67 s)
 (14/14) Host_RHEL.m9.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: STARTED
 (14/14) Host_RHEL.m9.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: PASS (43.73 s)
RESULTS    : PASS 12 | ERROR 0 | FAIL 2 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2024-06-11T05.38-4e6deed/results.html
JOB TIME   : 562.47 s

failed cases are expected.

**Comment by qingwangrh** [comment]
@XueqiangWei @zhenyzha @peixiu Please help to review ,thanks.

**Comment by zhenyzha** [comment]
This tests `only x86_64 i386`, so please ignore me. thanks

**Comment by XueqiangWei** [comment]
@peixiu Could you please help take a look at it? Many thanks.

**Comment by peixiu** [comment]
python ConfigTest.py --testcase=block_vhost_vdpa_test --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 -guestname=Win2025 --driveformat=virtio_blk,virtio_scsi --imageformat=qcow2 --machines=q35 --customsparams="vm_mem_limit = 12G\nimage_aio=native" --clone=yes

 (01/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.defaunstall.aio_threads.q35: STARTED
 (01/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.defaunstall.aio_threads.q35: PASS (1161.66 s)
 (02/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.defainstall.aio_threads.q35: STARTED
 (02/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.defainstall.aio_threads.q35: PASS (1295.20 s)
 (03/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.multi_disks.q35: STARTE
 (03/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.multi_disks.q35: PASS (55 s)
 (04/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.hotplug_unplug.q35: STA (04/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.hotplug_unplug.q35: PAS44.05 s)
 (05/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_p.with_direct_on.q35: STARTED
 (05/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_p.with_direct_on.q35: PASS (121.41 s)
 (06/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_p.with_direct_off.q35: STARTED
 (06/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_p.with_direct_off.q35: PASS (16.55 s)
 (07/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_re.with_direct_on.q35: STARTED
 (07/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_re.with_direct_on.q35: PASS (120.04 s)
 (08/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_re.with_direct_off.q35: STARTED
 (08/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discard_re.with_direct_off.q35: PASS (16.46 s)
 (09/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: STA (09/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: PAS02.82 s)
 (10/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.multi_disks.q35: START
 (10/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.multi_disks.q35: PASS .88 s)
 (11/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.hotplug_unplug.q35: STD
 (11/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.hotplug_unplug.q35: PA135.85 s)
 (12/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discardap.with_direct_on.q35: STARTED
 (12/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discardap.with_direct_on.q35: FAIL: Shell command failed: 'echo select volume F > disk_idKL && echo format fs=ntfs quick >> disk_idKL && echo exit >> disk_idK diskpart /s disk_idKL && del /f disk_idKL'    (status: -2147024770,    output: '\nMicrosoft DiskPart version 10.0.26080.1\n\nCop... (119.64 s)
 (13/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discardap.with_direct_off.q35: STARTED
 (13/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discardap.with_direct_off.q35: PASS (15.21 s)
 (14/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discardore.with_direct_on.q35: STARTED
 (14/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discardore.with_direct_on.q35: PASS (120.04 s)
 (15/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discardore.with_direct_off.q35: STARTED
 (15/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_opts.with_discardore.with_direct_off.q35: PASS (15.20 s)
 (16/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: STD
 (16/16) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: PA97.37 s)

Job [16] failed as existed product issue: [RHEL-32878]

Acked-by: Peixiu Hou phou@redhat.com

**Review by peixiu — APPROVED** [review]
LGTM, thanks!

**Comment by XueqiangWei** [comment]
commit signature verification has been enabled, please re-push it with -S. Thanks.

**Comment by qingwangrh** [comment]
> commit signature verification has been enabled, please re-push it with -S. Thanks.

done

**Review by XueqiangWei — APPROVED** [review]
LGTM,
Acked-by: xuwei@redhat.com

**Pull request merged**
