### PR TITLE
need higher version package kmod to update kernel

### PR DESCRIPTION
**Pull request by PyLearner**
Signed-off-by: Meng Yang meyang@redhat.com

ID: 1379203

### CODE REVIEW

**Comment by PyLearner** [comment]
(1/3) smp_4.8192m.repeat1.pre_test.Host_RHEL.m7.u2.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native: PASS (2049.07 s)
 (2/3) smp_4.8192m.repeat1.pre_test.Host_RHEL.m7.u2.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.rh_kernel_update: PASS (466.79 s)

**Comment by xutian** [comment]
do you have a test for rhel6 guest?

**Comment by yanan-fu** [comment]
Test  with rhel6.8 guest: 
(1/3) smp_8.16384m.repeat1.pre_test.Host_RHEL.m6.u8.qcow2.virtio_scsi.up.virtio_net.RHEL.6.8.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native: PASS (937.73 s)
 (2/3) smp_8.16384m.repeat1.pre_test.Host_RHEL.m6.u8.qcow2.virtio_scsi.up.virtio_net.RHEL.6.8.x86_64.io-github-autotest-qemu.rh_kernel_update: PASS (624.48 s)

@xutian   
In (2/3),  debug log show:
06:03:43 INFO | Context: Upgrade package 'kmod' in guest
06:03:43 DEBUG| Sending command: rpm -q --whatrequires kmod --queryformat='%{NAME}'
06:03:44 DEBUG| Running 'brew latest-pkg RHEL-6.8-Z-candidate kmod --arch=x86_64 --paths'

As these has no kmod package for rhel6, so "brew latest-pkg RHEL-6.8-Z-candidate kmod --arch=x86_64 --paths"  get no output.   It is redundant for rhel 6 guest,  but seems no side effect,

**Comment by PyLearner** [comment]
@yanan-fu, thanks.

**Comment by pingl2016** [comment]
For RHEL 6 guest, I think skip installation if the packages don't exist is enough.
Acked-by: Ping Li <pingl@redhat.com>
(01/12) smp_8.8192m.repeat1.pre_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.6.8.i386.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native:  PASS (963.60 s)
 (02/12) smp_8.8192m.repeat1.pre_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.6.8.i386.io-github-autotest-qemu.rh_kernel_update:  PASS (458.00 s)
 (03/12) smp_8.8192m.repeat1.pre_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.6.8.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native:  PASS (909.86 s)
 (04/12) smp_8.8192m.repeat1.pre_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.6.8.x86_64.io-github-autotest-qemu.rh_kernel_update:  PASS (425.00 s)
 (05/12) smp_8.8192m.repeat1.pre_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native:  PASS (1874.97 s)
 (06/12) smp_8.8192m.repeat1.pre_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.rh_kernel_update:  PASS (484.49 s)
 (07/12) smp_8.8192m.repeat1.pre_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native:  PASS (1686.87 s)
 (08/12) smp_8.8192m.repeat1.pre_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.rh_kernel_update:  PASS (191.60 s)

**Comment by yanan-fu** [comment]
For rhel6 guest, no side effect, skip installation is enough.
Acked-by: Yanan Fu yfu@redhat.com

**Comment by xutian** [comment]
@PyLearner  base on test results in comments#3, kmod is not requried for rhel6.8's guest, so please keep default value for "kernel_deps_pkgs", then overwrite  it in match variant rhel.7.

**Comment by PyLearner** [comment]
hi @xutian, could you help to review again, thanks.

**Comment by suqinhuang** [comment]
Acked-by: Suqin Huang

**Comment by xutian** [comment]
Merged, thanks @PyLearner

**Pull request merged**
