### PR TITLE
add ballon device support on s390x

### PR DESCRIPTION
**Pull request by fbq815**
Memory: add parent_bus to support ballon device on s390x

ID: 2022207

Signed-off-by: Boqiao Fu <bfu@redhat.com>

### CODE REVIEW

**Comment by fbq815** [comment]
Test result:
JOB ID     : 1c882b750378ae627a1f661d3753fc472308cf3b
JOB LOG    : /root/avocado/job-results/job-2021-11-11T00.12-1c882b7/job.log
 (1/1) Host_RHEL.m8.u6.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.balloon_hotplug.with_migrate.migrate_after_hotplug.s390-virtio: PASS (167.71 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2021-11-11T00.12-1c882b7/results.html
JOB TIME   : 168.14 s

**Comment by fbq815** [comment]
@PaulYuuu @ngu-niny @MiriamDeng  please help me review this patch

**Review by PaulYuuu — APPROVED** [review]

**Comment by MiriamDeng** [comment]
[root@z15-kvm-guest io-github-autotest-qemu]# git am 3075.patch
Applying: add ballon device support on s390x
Test result,
PASS 1-Host_RHEL.m8.u6.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.balloon_hotplug.with_migrate.migrate_after_hotplug.s390-virtio

**Comment by MiriamDeng** [comment]
LGTM
By the way, as far as I remember hotplug test case for balloon is only priority 3  or so. Maybe you can add some other test cases too.

**Comment by ngu-niny** [comment]
LGTM.

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
