### PR TITLE
qemu_img_lock.reject_boot_base_img_and_snapshot: support luks

### PR DESCRIPTION
**Pull request by lolyu**
id: 1771289
As the subject, add support to test if boot base and snapshot images
simultaneously.

Signed-off-by: lolyu <lolyu@redhat.com>

### CODE REVIEW

**Comment by lolyu** [comment]
@hellohellenmao @YongxueHong Please help to review, thanks.

**Comment by lolyu** [comment]
```
 (1/1) Host_RHEL.m7.u7.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.io-github-autotest-qemu.qemu_img_lock.reject_boot_base_img_and_snapshot.luks_format: PASS (65.56 s)
```

**Comment by hellohellenmao** [comment]
Compatibility test of raw with this patch, passed.

 (1/2) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.qemu_img_lock.reject_boot_same_img_twice: PASS (32.80 s)
 (2/2) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.qemu_img_lock.reject_boot_base_img_and_snapshot.raw_format: PASS (32.24 s)

**Comment by hellohellenmao** [comment]
Cases passed, and the log is LGTM.

 (1/2) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.qemu_img_lock.reject_boot_same_img_twice: PASS (32.21 s)
 (2/2) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.qemu_img_lock.reject_boot_base_img_and_snapshot.luks_format: PASS (32.91 s)

**Pull request merged**
