### PR TITLE
balloon_service: Fix bug when error happens in try block 

### PR DESCRIPTION
**Pull request by huangyum**
Move related code out of try block, so when it fails the finally block won't execute which could lead error "local variable 'drive_letter' referenced before assignment"

ID: 1491184
Signed-off-by: Yumei Huang <yuhuang@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
If `get_disk_vol` failed, L42~L43:
```
       except Exception:
           raise exceptions.TestFail("Could not get virtio-win disk vol!")
```
This problem still exist.

**Comment by huangyum** [comment]
@yanan-fu how about we move all related code out of try block?  Please help review, thanks!

**Comment by huangyum** [comment]
Run case balloon_service.small_polling_interval 20 times,  didn't hit the "variable referenced before assignment" bug.

**Comment by luckyh** [comment]
@huangyum please change your commit message by following http://avocado-framework.readthedocs.io/en/55.0/ContributionGuide.html#git-workflow

**Comment by yanan-fu** [comment]
@huangyum  Current modification is ok for me. We need to do `uninstall_balloon_service` in "finally" only if `config_balloon_service` succeed.  So move these out of try block is enough.

LGTM
Ackec-by:Yanan Fu <yfu@redhat.com>

**Comment by huangyum** [comment]
@luckyh Updated, thanks!

**Comment by hereischen** [comment]
Ackec-by: Haotong Chen hachen@redhat.com

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
