### PR TITLE
qemu_nobody:int object has no attribute strip 

### PR DESCRIPTION
**Pull request by yiqianwei**
qemu_nobody:int object has no attribute strip 

Signed-off-by: yiqian <yiqian@localhost.localdomain>

### CODE REVIEW

**Comment by yiqianwei** [comment]
for python3
 (1/1) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.qemu_nobody.q35: PASS (28.47 s)

for python2
(1/1) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.qemu_nobody.q35: PASS (49.11 s)

**Comment by yiqianwei** [comment]
@yanan-fu could you help to review this patch, thanks

**Comment by vivianQizhu** [comment]
@yiqianwei Please notice that RHEL8 host does not install python2 by default, only if you install it by yourself and compile and execute the test with python2, otherwise you don't use python2 on RHEL8.
Or you might test it on RHEL7 host instead of RHEL7 guest.

**Comment by yanan-fu** [comment]
Please provide the test result for python2.

**Comment by yiqianwei** [comment]
the test result for python2:
 (1/1) Host_RHEL.m7.u7.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.qemu_nobody.q35: PASS (35.81 s)

**Comment by jingzhao84** [comment]
@lolyu could you help to review it again since yiwei had updated

thanks

**Pull request merged**
