### PR TITLE
PPC:disable some xfstests test cases from test suite

### PR DESCRIPTION
**Pull request by MiriamDeng**
Remove some generic test cases from test suite of xfstest
ID: 1584

### CODE REVIEW

**Comment by MiriamDeng** [comment]
Blacklist excludes the test cases.
echo -e "generic/003\ngeneric/120\ngeneric/426\ngeneric/467\ngeneric/477\ngeneric/551\ngeneric/263\ngeneric/075\ngeneric/091\ngeneric/099\ngeneric/237\ngeneric/263\ngeneric/319\ngeneric/375\ngeneric/444\ngeneric/683\ngeneric/684\ngeneric/685\n" > blacklist
A piece of corresponding test results
 (1/6) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.ppc64le.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_xfstest.with_cache.auto: STARTED
Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.ppc64le.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_xfstest.with_cache.auto: PASS (4938.66 s)

**Comment by MiriamDeng** [comment]
@maxujun @PaulYuuu Please help to review the patch, thanks !

**Review by PaulYuuu — DISMISSED** [review]

**Comment by maxujun** [comment]
LGTM, Acked.

**Review by PaulYuuu — APPROVED** [review]

**Review by PaulYuuu — CHANGES_REQUESTED** [review]
Please remove the unnecessary commit.

**Comment by MiriamDeng** [comment]
Thanks, updated !

**Review by PaulYuuu — APPROVED** [review]

**Pull request merged**
