### PR TITLE
virtio_fs: support more options for xfstest

### PR DESCRIPTION
**Pull request by xiagao**
ID: 2212610
Allow running xfstest with virtiofsd writeback option.

### CODE REVIEW

**Comment by leidwang** [comment]
Please mark this patch as draft or @ someone to review this patch.

**Comment by xiagao** [comment]
@zhenyzha @leidwang pls help to review.

**Comment by zhenyzha** [comment]
Failed cases are product issues, not related to the patch.
LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

testcase=virtio_fs_share_data..run_stress,virtio_fs_share_data_multi_backend

```
 (01/73) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_cache.auto.with_nfs_source.arm64-pci: STARTED
......
 (73/73) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_xfstest.posix_acl.with_cache.auto.arm64-pci: STARTED
 (73/73) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_xfstest.posix_acl.with_cache.auto.arm64-pci: PASS (99.84 s)
```
RESULTS    : PASS 69 | ERROR 3 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Review by zhenyzha — APPROVED** [review]

**Comment by xiagao** [comment]
@YongxueHong Could you help to review? thx.

**Comment by YongxueHong** [comment]
Hi @nickzhq 
Would you like to help review it?
Thanks.

**Comment by nickzhq** [comment]
> Hi @nickzhq Would you like to help review it? Thanks.

LGTM, thanks!

**Review by leidwang — APPROVED** [review]

**Comment by YongxueHong** [comment]
Hi @xiagao @leidwang @zhenyzha 
Just a reminder that we changed the filtering rule which maybe leads to the test case name changing, please update the related test case name in the internal test loop if the case is affected to avoid the regression error before the next rebase.
Thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by xiagao** [comment]
> Hi @xiagao @leidwang @zhenyzha Just a reminder that we changed the filtering rule which maybe leads to the test case name changing, please update the related test case name in the internal test loop if the case is affected to avoid the regression error before the next rebase. Thanks.

Okay, thanks the reminder.

**Pull request merged**
