### PR TITLE
blockdev_inc_backup_pull_mode_vm_down: fix the issue when qemu quits after vm poweroff

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1926549

### CODE REVIEW

**Comment by zhencliu** [comment]
qemu with the bug fix:
 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.1.x86_64.io-github-autotest-qemu.blockdev_inc_backup_pull_mode_vm_down.q35: PASS (34.16 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2021-02-09T05.20-c3dc690/results.html
JOB TIME   : 34.88 s

qemu without the bug fix:
 (1/1) Host_RHEL.m8.u3.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_pull_mode_vm_down.q35: FAIL: qemu hangs: Received no response to QMP command 'query-status', or received a response with an incorrect id (378.35 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2021-02-09T05.51-06f9dc5/results.html
JOB TIME   : 381.23 s

**Comment by zhencliu** [comment]
hi @leidwang @ngu-niny , can U please help to review this patch? Thanks.

**Comment by ngu-niny** [comment]
@zhencliu Test PASS, but the error message was threw out in the debug.log. 

09:34:14 INFO | Running '/usr/bin/qemu-io -C -c "r 273678336 160956416" -f qcow2 /home/ngu/kar/workspace/var/lib/avocado/data/avocado-vt/cimage2.qcow2'
09:34:16 INFO | [qemu output] qemu-kvm: Disconnect client, due to: Failed to send reply: Unable to write to socket: Broken pipe
09:34:16 INFO | [qemu output] qemu-kvm: Disconnect client, due to: Failed to send reply: Unable to write to socket: Broken pipe
09:34:16 INFO | [qemu output] qemu-kvm: Disconnect client, due to: Failed to send reply: Unable to write to socket: Broken pipe
09:34:16 INFO | [qemu output] (Process terminated with status 0)
09:34:17 DEBUG| [stdout] read failed: Input/output error
09:34:17 INFO | Command '/usr/bin/qemu-io -C -c "r 273678336 160956416" -f qcow2 /home/ngu/kar/workspace/var/lib/avocado/data/avocado-vt/cimage1.qcow2' finished with 1 after 3.9656407833099365s
09:34:17 DEBUG| [stderr] Process Process-2:1:

09:34:17 INFO | qemu quit after vm poweroff
09:34:17 DEBUG| [stderr] Process Process-2:2:

09:34:17 DEBUG| [stderr] Process Process-2:3:

09:34:17 DEBUG| [stdout] read failed: Input/output error
09:34:18 DEBUG| [stdout] read failed: Input/output error
09:34:18 DEBUG| [stderr] Traceback (most recent call last):

09:34:18 DEBUG| [stderr] Traceback (most recent call last):

09:34:18 DEBUG| [stderr]   File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap

09:34:18 DEBUG| [stderr]   File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap

09:34:18 DEBUG| [stderr]     self.run()

09:34:18 DEBUG| [stderr]     self.run()

09:34:18 DEBUG| [stderr]   File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run

09:34:18 DEBUG| [stderr]   File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run

09:34:18 DEBUG| [stderr]     self._target(*self._args, **self._kwargs)

09:34:18 DEBUG| [stderr]     self._target(*self._args, **self._kwargs)

09:34:18 DEBUG| [stderr]   File "/home/ngu/kar/workspace/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/provider/backup_utils.py", line 474, in copyif

09:34:18 DEBUG| [stderr]   File "/home/ngu/kar/workspace/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/provider/backup_utils.py", line 474, in copyif

09:34:18 DEBUG| [stderr]     _qemu_io_read(qemu_io, start, length, img_obj)

09:34:18 DEBUG| [stderr]     _qemu_io_read(qemu_io, start, length, img_obj)

09:34:18 DEBUG| [stderr]   File "/home/ngu/kar/workspace/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/provider/backup_utils.py", line 431, in _qemu_io_read

09:34:18 DEBUG| [stderr]   File "/home/ngu/kar/workspace/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/provider/backup_utils.py", line 431, in _qemu_io_read

09:34:18 DEBUG| [stderr]     process.system(cmd, ignore_status=False, shell=True)

09:34:18 DEBUG| [stderr]     process.system(cmd, ignore_status=False, shell=True)
09:34:18 DEBUG| [stderr]   File "/home/ngu/kar/workspace/avocado/avocado/utils/process.py", line 1100, in system

09:34:18 DEBUG| [stderr]   File "/home/ngu/kar/workspace/avocado/avocado/utils/process.py", line 1100, in system

09:34:18 DEBUG| [stderr]     encoding=encoding)

09:34:18 DEBUG| [stderr]     encoding=encoding)

09:34:18 DEBUG| [stderr]   File "/home/ngu/kar/workspace/avocado/avocado/utils/process.py", line 1034, in run

09:34:18 DEBUG| [stderr]   File "/home/ngu/kar/workspace/avocado/avocado/utils/process.py", line 1034, in run

09:34:18 DEBUG| [stderr]     cmd_result = sp.run(timeout=timeout)

09:34:18 DEBUG| [stderr]     cmd_result = sp.run(timeout=timeout)

09:34:18 DEBUG| [stderr]   File "/home/ngu/kar/workspace/avocado/avocado/utils/process.py", line 908, in run

09:34:18 DEBUG| [stderr]   File "/home/ngu/kar/workspace/avocado/avocado/utils/process.py", line 908, in run

09:34:18 DEBUG| [stderr]     self.wait(timeout, sig)

09:34:18 DEBUG| [stderr]     self.wait(timeout, sig)

09:34:18 DEBUG| [stderr]   File "/home/ngu/kar/workspace/avocado/avocado/utils/process.py", line 822, in wait

09:34:18 DEBUG| [stderr]   File "/home/ngu/kar/workspace/avocado/avocado/utils/process.py", line 822, in wait

09:34:18 DEBUG| [stderr]     rc = self._popen.wait()

09:34:18 DEBUG| [stderr]     rc = self._popen.wait()
09:34:18 DEBUG| [stderr]   File "/usr/lib64/python3.6/subprocess.py", line 1477, in wait

09:34:18 DEBUG| [stderr]   File "/usr/lib64/python3.6/subprocess.py", line 1477, in wait

09:34:18 DEBUG| [stderr]     (pid, sts) = self._try_wait(0)

09:34:18 DEBUG| [stderr]     (pid, sts) = self._try_wait(0)

09:34:18 DEBUG| [stderr]   File "/usr/lib64/python3.6/subprocess.py", line 1424, in _try_wait

09:34:18 DEBUG| [stderr]   File "/usr/lib64/python3.6/subprocess.py", line 1424, in _try_wait

09:34:18 DEBUG| [stderr]     (pid, sts) = os.waitpid(self.pid, wait_flags)

09:34:18 DEBUG| [stderr]     (pid, sts) = os.waitpid(self.pid, wait_flags)
09:34:18 DEBUG| [stderr]   File "/home/ngu/kar/workspace/avocado/avocado/plugins/runner.py", line 77, in sigterm_handler

09:34:18 DEBUG| [stderr]   File "/home/ngu/kar/workspace/avocado/avocado/plugins/runner.py", line 77, in sigterm_handler

09:34:18 DEBUG| [stderr]     raise RuntimeError("Test interrupted by SIGTERM")

09:34:18 DEBUG| [stderr]     raise RuntimeError("Test interrupted by SIGTERM")

09:34:18 DEBUG| [stderr] RuntimeError: Test interrupted by SIGTERM

09:34:18 DEBUG| [stderr] RuntimeError: Test interrupted by SIGTERM

09:34:18 DEBUG| Removing image file /home/ngu/kar/workspace/var/lib/avocado/data/avocado-vt/full.qcow2
09:34:18 DEBUG| Removing image file /home/ngu/kar/workspace/var/lib/avocado/data/avocado-vt/cimage3.qcow2
09:34:18 DEBUG| Removing image file /home/ngu/kar/workspace/var/lib/avocado/data/avocado-vt/cimage1.qcow2
09:34:18 DEBUG| Removing image file /home/ngu/kar/workspace/var/lib/avocado/data/avocado-vt/cimage2.qcow2
09:34:19 DEBUG| Host does not support OpenVSwitch: Command 'ovs-vswitchd' could not be found in any of the PATH dirs: ['/bin', '/home/ngu/kar/workspace/bin', '/root/bin', '/sbin', '/usr/bin', '/usr/libexec', '/usr/local/bin', '/usr/local/sbin', '/usr/sbin']
09:34:19 DEBUG| Checking image file /home/ngu/kar/vt_test_images/rhel840-ppc64le-virtio-scsi.qcow2
09:34:19 DEBUG| Run qemu-img info command on /home/ngu/kar/vt_test_images/rhel840-ppc64le-virtio-scsi.qcow2
09:34:19 INFO | Running '/usr/bin/qemu-img info -U /home/ngu/kar/vt_test_images/rhel840-ppc64le-virtio-scsi.qcow2 --output=human'
09:34:19 DEBUG| [stdout] image: /home/ngu/kar/vt_test_images/rhel840-ppc64le-virtio-scsi.qcow2
09:34:19 INFO | Command '/usr/bin/qemu-img info -U /home/ngu/kar/vt_test_images/rhel840-ppc64le-virtio-scsi.qcow2 --output=human' finished with 0 after 0.0263521671295166s
09:34:19 DEBUG| [stdout] file format: qcow2
09:34:19 DEBUG| [stdout] virtual size: 20 GiB (21474836480 bytes)
09:34:19 DEBUG| [stdout] disk size: 5.08 GiB
09:34:19 DEBUG| [stdout] cluster_size: 65536
09:34:19 DEBUG| [stdout] Format specific information:
09:34:19 DEBUG| [stdout]     compat: 1.1
09:34:19 DEBUG| [stdout]     compression type: zlib
09:34:19 DEBUG| [stdout]     lazy refcounts: false
09:34:19 DEBUG| [stdout]     refcount bits: 16
09:34:19 DEBUG| [stdout]     corrupt: false
09:34:19 DEBUG| Checking image file /home/ngu/kar/vt_test_images/rhel840-ppc64le-virtio-scsi.qcow2
09:34:20 DEBUG| Encoding video file /home/ngu/kar/workspace/job-results/job-2021-02-09T09.31-94e0c39/test-results/2-Host_RHEL.m8.u3.v0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_pull_mode_vm_down/screendumps_avocado-vt-vm1_67774_iter0.webm
09:34:20 WARNI| registers is not alive. Can't query the avocado-vt-vm1 status
09:34:51 DEBUG| Thread quit. Used to failed to get registers info from guest 20210209-093119-LBxWdgDP for 8 times.
09:34:51 INFO | Running 'grep revision /proc/cpuinfo | awk '{print $3}' | head -n 1'
09:34:51 DEBUG| [stdout] 2.2
09:34:51 INFO | Command 'grep revision /proc/cpuinfo | awk '{print $3}' | head -n 1' finished with 0 after 0.08761477470397949s
09:34:51 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
09:34:51 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
09:34:51 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
09:34:51 INFO | PASS 2-Host_RHEL.m8.u3.v0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_pull_mode_vm_down
09:34:51 INFO |

**Comment by zhencliu** [comment]
hi @ngu-niny , that's expected, when we poweroff vm, qemu process quit, then the internal nbd server was dead too, all qemu-io processes died with errors.

**Comment by leidwang** [comment]
Test pass, if the error(same with ngu's comment) in debug.log is expected, LGTM.
JOB ID     : 1c02eb8f0c3444252850614d49bae13f04d4e76a
JOB LOG    : /root/avocado/job-results/job-2021-02-09T20.34-1c02eb8/job.log
 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.1.x86_64.io-github-autotest-qemu.blockdev_inc_backup_pull_mode_vm_down.q35: PASS (28.68 s)

**Comment by zhencliu** [comment]
Thank you @ngu-niny and @leidwang for your quick review.

@ngu-niny , your concern might be that the error messages in log file might be confusing that  error occurred for  a passed case, then I can make some code change to hide most error messages, but just throw several warning message like:
20:53:13 WARNI| qemu-io failed as expected for nbd server was dead
But the code change is only for the message handling, which neither make sense for the testing scenarios, nor for shortening the running time. So can you please confirm if the code change is needed? Thanks.

**Comment by ngu-niny** [comment]
@zhencliu Since it's as design, it make sense to me to keep the error message.

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
