### PR TITLE
blockdev_inc_backup_xpt_allocation_depth: Allocation export test

### PR DESCRIPTION
**Pull request by zhencliu**
Export allocation depth with qemu-nbd and block-export-add

Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1922947, 1922948

### CODE REVIEW

**Comment by zhencliu** [comment]
virtio-scsi:
 (1/2) Host_RHEL.m8.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_xpt_allocation_depth.with_qemu_nbd.q35: PASS (90.83 s)
 (2/2) Host_RHEL.m8.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_xpt_allocation_depth.with_block_export.q35: PASS (80.48 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2021-01-29T10.12-399efaa/results.html
JOB TIME   : 174.24 s

virtio-blk:
 (1/2) Host_RHEL.m8.u3.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_xpt_allocation_depth.with_qemu_nbd.q35: PASS (93.39 s)
 (2/2) Host_RHEL.m8.u3.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_xpt_allocation_depth.with_block_export.q35: PASS (89.07 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2021-01-29T10.33-7a22fd9/results.html
JOB TIME   : 185.28 s

**Comment by zhencliu** [comment]
hi @ngu-niny @YongxueHong , can you please help to review this patch, thanks.
it deps on:
avocado-framework/avocado-vt#2890
#2604

**Comment by ngu-niny** [comment]
LGTM and test PASS:

'1-Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_xpt_allocation_depth.with_qemu_nbd' Finshed 2021-02-10 04:05:44 2021-02-10 04:08:04 PASS 140.268686
'2-Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_xpt_allocation_depth.with_block_export' Finshed 2021-02-10 04:08:04 2021-02-10 04:10:12 PASS 127.321662

Acked-by: Nini Gu <ngu@redhat.com>

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
