### PR TITLE
numa_cpu: Fix issue with 32bit guests

### PR DESCRIPTION
**Pull request by huangyum**
Signed-off-by: Yumei Huang <yuhuang@redhat.com>
ID： 1968255

### CODE REVIEW

**Comment by huangyum** [comment]
Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.numa_cpu: PASS (29.06 s)
@yanan-fu  Pls help review, thanks.

**Comment by yanan-fu** [comment]
@huangyum  It is 32 bit guest issue,  so i would like suggest to remove `Windows` in the title, although the Linux guest do not test 32 bit.

**Comment by huangyum** [comment]
> @huangyum It is 32 bit guest issue, so i would like suggest to remove `Windows` in the title, although the Linux guest do not test 32 bit.

Thanks, updated.

**Comment by yanan-fu** [comment]
LGTM

Acked-by: Yanan Fu <yfu@redhat.com>

**Pull request merged**
