### PR TITLE
virtio_serial:hot-unplug relative ports before hot-unplugging pci

### PR DESCRIPTION
**Pull request by nanliu-r**
ID:1766850

Signed-off-by: Nana Liu <nanliu@redhat.com>

### CODE REVIEW

**Comment by nanliu-r** [comment]
Test results:
 (1/9) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.virtio_port_hotplug.hotplug_port_pci: PASS (83.27 s)
 (2/9) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.virtio_port_hotplug.hotplug_port_pci.with_reboot: PASS (210.98 s)
 (3/9) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.virtio_port_hotplug.hotplug_port_pci.with_system_reset: PASS (181.52 s)
 (4/9) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.virtio_port_hotplug.hotplug_port_pci.with_shutdown_after_unplug: PASS (69.00 s)
 (5/9) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.virtio_port_hotplug.hotplug_port_pci.with_shutdown_after_plug: PASS (73.75 s)
 (6/9) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.virtio_port_hotplug.hotplug_port_pci.with_live_migration_after_unplug: PASS (86.93 s)
 (7/9) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.virtio_port_hotplug.hotplug_port_pci.repeat_pci_in_loop: PASS (1844.95 s)
 (8/9) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.virtio_port_hotplug.hotplug_port_pci.without_chardev: PASS (68.73 s)
 (9/9) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.virtio_port_hotplug.hotplug_port_pci.with_console_negative: PASS (70.92 s)

**Comment by nanliu-r** [comment]
@vivianQizhu @lijinlijin  Please help to reviw this. Line 136 and Line 137 are code change, the others  are format adjustment. Thanks a lot.

**Comment by lijinlijin** [comment]
@xiagao

**Comment by xiagao** [comment]
@nanliu-r  your modification is not suitable for other polarion case, such as 96883,96885,96887,could you have a check?

**Comment by nanliu-r** [comment]
> @nanliu-r your modification is not suitable for other polarion case, such as 96883,96885,96887,could you have a check?

My modification is make code `out = vm.devices.simple_unplug(buses[0], vm.monitor)` more reasonable, I have no change on case design.

**Comment by nanliu-r** [comment]
Win10 Test results:

 (1/9) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.virtio_port_hotplug.hotplug_port_pci: PASS (128.38 s)
 (2/9) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.virtio_port_hotplug.hotplug_port_pci.with_reboot: PASS (296.81 s)
 (3/9) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.virtio_port_hotplug.hotplug_port_pci.with_system_reset: PASS (184.58 s)
 (4/9) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.virtio_port_hotplug.hotplug_port_pci.with_shutdown_after_unplug: PASS (99.36 s)
 (5/9) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.virtio_port_hotplug.hotplug_port_pci.with_shutdown_after_plug: PASS (97.88 s)
 (6/9) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.virtio_port_hotplug.hotplug_port_pci.with_live_migration_after_unplug: PASS (114.79 s)
 (7/9) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.virtio_port_hotplug.hotplug_port_pci.repeat_pci_in_loop: PASS (1589.50 s)
 (8/9) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.virtio_port_hotplug.hotplug_port_pci.without_chardev: PASS (90.50 s)
 (9/9) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.virtio_port_hotplug.hotplug_port_pci.with_console_negative: PASS (88.43 s)

**Comment by xiagao** [comment]
LGTM
Acked-by: Xiaoling Gao <xiagao@redhat.com>

**Comment by vivianQizhu** [comment]
Ack.

**Pull request merged**
