### PR TITLE
passthrough_fc_with_lun_device:add default max_sectors case

### PR DESCRIPTION
**Pull request by qingwangrh**
ID:2867

### CODE REVIEW

**Comment by qingwangrh** [comment]
Pass case parsing.

**Comment by qingwangrh** [comment]
@XueqiangWei @peixiu Please help to review, thanks.

**Comment by XueqiangWei** [comment]
(1/3) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_block.with_default.q35: STARTED
 (1/3) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_block.with_default.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (2/3) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_block.with_sectors_64.q35: STARTED
 (2/3) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_block.with_sectors_64.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (3/3) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_generic.q35: STARTED
 (3/3) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_generic.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

**Review by XueqiangWei — APPROVED** [review]
LGTM,
Acked-by: xuwei@redhat.com

**Pull request merged**
