### PR TITLE
virtio_net_dpdk: gather the result from the next to last line

### PR DESCRIPTION
**Pull request by quanwenli**
Signed-off-by: Wenli Quan <wquan@redhat.com>

id: 1874735

### CODE REVIEW

**Comment by quanwenli** [comment]
JOB LOG    : /root/avocado/job-results/job-2020-09-02T04.56-f3e9a38/job.log
 (1/1) repeat1.Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.virtio_net_dpdk.q35: PASS (162.57 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by quanwenli** [comment]
@vivianQizhu, please help to review this patch, thanks

**Comment by vivianQizhu** [comment]
@quanwenli Could you introduce a bit what's the previous result and what's now?

**Comment by quanwenli** [comment]
> @quanwenli Could you introduce a bit what's the previous result and what's now?

Before:
Category:rx
    pkt_size|        mpps
          60|        0.00
Category:tx
    pkt_size|        mpps
          60|        0.00
now:
Category:rx
    pkt_size|        mpps
          60|        0.03
Category:tx
    pkt_size|        mpps
          60|        0.87

I have updated the source data in bug.

**Comment by quanwenli** [comment]
> > @quanwenli Could you introduce a bit what's the previous result and what's now?
> 
> Before:
> Category:rx
> pkt_size| mpps
> 60| 0.00
> Category:tx
> pkt_size| mpps
> 60| 0.00
> now:
> Category:rx
> pkt_size| mpps
> 60| 0.03
> Category:tx
> pkt_size| mpps
> 60| 0.87
> 
> I have updated the source data in bug.

**Review by vivianQizhu — APPROVED** [review]

**Pull request merged**
