### PR TITLE
block_auto_detect_size_increased: support the 'luks' image format.

### PR DESCRIPTION
**Pull request by nickzhq**
block_auto_detect_size_increased: support the 'luks' image format.

ID: 1993837

Signed-off-by: Houqi (Nick) Zuo hzuo@redhat.com

### CODE REVIEW

**Comment by nickzhq** [comment]
@zhencliu Hello, please check this out! Thanks!

**Comment by nickzhq** [comment]
Hi @zhencliu , here's the new updates. Please take a look! Thanks

**Comment by zhencliu** [comment]
> Hi @zhencliu , here's the new updates. Please take a look! Thanks

hi @nickzhq , pls run the case with qcow2 and luks format, and paste results here

**Comment by nickzhq** [comment]
(1/2) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: STARTED
\ (1/2) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (2203.93 s)
 (2/2) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_auto_detect_size_increased: STARTED
/ (2/2) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_auto_detect_size_increased: PASS (837.26 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0



 (1/2) Host_RHEL.m9.u0.luks.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: STARTED
|avocado-vt-vm-
/ (1/2) Host_RHEL.m9.u0.luks.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (2096.87 s)
 (2/2) Host_RHEL.m9.u0.luks.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_auto_detect_size_increased: STARTED
/ (2/2) Host_RHEL.m9.u0.luks.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_auto_detect_size_increased: PASS (803.77 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by nickzhq** [comment]
Hi @zhencliu .Please take a look! Thanks

**Comment by zhencliu** [comment]
LGTM
@nickzhq Also, please do a double check by running the test

**Comment by nickzhq** [comment]
(1/2) Host_RHEL.m9.u0.luks.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: STARTED
| (1/2) Host_RHEL.m9.u0.luks.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (2322.26 s)
 (2/2) Host_RHEL.m9.u0.luks.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_auto_detect_size_increased: STARTED
- (2/2) Host_RHEL.m9.u0.luks.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_auto_detect_size_increased: PASS (800.46 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

@zhencliu , please take a look! Thanks!

**Comment by zhencliu** [comment]
LGTM

hi @qingwangrh , would you please help to review this pr, which fixed the issue you reported, thanks.

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=block_auto_detect_size_increased --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=Win2019 --driveformat=virtio_blk --nicmodel=virtio_net --imageformat=luks --machines=i440fx --customsparams="vm_mem_limit = 12G\ncd_format=ide\nimage_aio=threads"

 (1/2) Host_RHEL.m9.u0.luks.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: STARTED
| (1/2) Host_RHEL.m9.u0.luks.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (847.52 s)
 (2/2) Host_RHEL.m9.u0.luks.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_auto_detect_size_increased: STARTED
- (2/2) Host_RHEL.m9.u0.luks.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_auto_detect_size_increased: PASS (250.28 s)


LGTM

**Pull request merged**
