### PR TITLE
qemu_guest_agent: fix issue of read guest file with a large count

### PR DESCRIPTION
**Pull request by xiagao**
Read guest file with large count, sometimes it success and
sometimes it will prompt reasonable error info,both of them
are acceptable
ID: 1752735
Signed-off-by: Xiaoling Gao <xiagao@redhat.com>

### CODE REVIEW

**Comment by xiagao** [comment]
@xiangchunfu  Call for your review, thanks.

**Comment by xiangchunfu** [comment]
@xiagao  For large number,  I rem there is a bug for windows guest.  now, Is their behaviors(qemu return error message) the same?

**Comment by xiagao** [comment]
> @xiagao For large number, I rem there is a bug for windows guest. now, Is their behaviors(qemu return error message) the same?

yes, both os have the same behavior,  what we expected is guest agent will not hang with large count.

**Comment by xiangchunfu** [comment]
Acked by: Xiangchun Fu xfu@redhat.com

**Comment by xiagao** [comment]
@vivianQizhu Call for your review. thanks.

**Comment by xiagao** [comment]
> If success or failure both can be accepted, I think the test is totally meaningless and should be removed from the test plan.
The result is not only success or failure,sometimes there is no response or return some other type error info.

**Comment by xiagao** [comment]
@lolyu could you check if the change request is resolved?

**Comment by lolyu** [comment]
I agree with @vivianQizhu that it doesn't make any sense with your modification to accept both success and failure returns. You should take `No response` into consideration in the checking of returns instead of removing previous check point.

**Comment by xiagao** [comment]
> I agree with @vivianQizhu that it doesn't make any sense with your modification to accept both success and failure returns. You should take `No response` into consideration in the checking of returns instead of removing previous check point.

ok, working on it now.

**Comment by lolyu** [comment]
Please elaborate your change in commit log, use explicit tone instead of sometime.
And test result please.

**Comment by xiagao** [comment]
(1/3) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_guest_file.read.q35: PASS (67.70 s)
 (2/3) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_guest_file.read.q35: PASS (55.69 s)
 (3/3) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_guest_file.read.q35: PASS (98.69 s)

**Comment by xiagao** [comment]
@lolyu  commit is updated and results are pasted, could you have a look?
 Thanks.

**Pull request merged**
