### PR TITLE
virtio-fs: support viofs driver for win driver case

### PR DESCRIPTION
**Pull request by xiagao**
Support viofs driver in win_sigverify and virtio_driver_sign_check
test cases.
ID: 1883424, 1883427
Signed-off-by: Xiaoling Gao <xiagao@redhat.com>

### CODE REVIEW

**Comment by xiagao** [comment]
(1/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_driver_sign_check.with_viofs.virtio_win_iso_media: PASS (146.20 s)
 (2/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.win_sigverif.with_viofs: PASS (218.66 s)

**Comment by xiagao** [comment]
@menli820 
Could you help review?

**Comment by menli820** [comment]
The polarion link in the auto bug seems wrong, not the virtio-fs related case, maybe we should open a new auto bug to change the right polarion link then update the ID in the patch to match the auto tool, thanks


(1/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win8.x86_64.io-github-autotest-qemu.virtio_driver_sign_check.with_viofs.virtio_win_iso_media.q35: PASS (64.92 s)
(2/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win8.x86_64.io-github-autotest-qemu.win_sigverif.with_viofs.q35: PASS (355.65 s)

**Comment by menli820** [comment]
LGTM.

**Comment by xiagao** [comment]
@YongxueHong
Call for your review,thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM

**Pull request merged**
