### PR TITLE
Fix vsock tests random timing issue

### PR DESCRIPTION
**Pull request by qcheng-redhat**
Fix vsock tests random timing issue
ID: 3001

### CODE REVIEW

**Comment by qcheng-redhat** [comment]
Hi @XueqiangWei, could you help review this patch?

**Comment by qcheng-redhat** [comment]
Test result:  

(1/6) Host_RHEL.m9.u6.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.6.0.x86_64.io-github-autotest-qemu.vsock_test.q35: STARTED
 (1/6) Host_RHEL.m9.u6.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.6.0.x86_64.io-github-autotest-qemu.vsock_test.q35: PASS (158.81 s)
 (2/6) Host_RHEL.m9.u6.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.6.0.x86_64.io-github-autotest-qemu.vsock_test.negative_test.q35: STARTED
 (2/6) Host_RHEL.m9.u6.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.6.0.x86_64.io-github-autotest-qemu.vsock_test.negative_test.q35: PASS (129.89 s)
 (3/6) Host_RHEL.m9.u6.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.6.0.x86_64.io-github-autotest-qemu.vsock_test.hotplug.q35: STARTED
 (3/6) Host_RHEL.m9.u6.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.6.0.x86_64.io-github-autotest-qemu.vsock_test.hotplug.q35: PASS (196.34 s)
 (4/6) Host_RHEL.m9.u6.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.6.0.x86_64.io-github-autotest-qemu.vsock_test.migration_with_vsock.q35: STARTED
 (4/6) Host_RHEL.m9.u6.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.6.0.x86_64.io-github-autotest-qemu.vsock_test.migration_with_vsock.q35: PASS (433.83 s)
 (5/6) Host_RHEL.m9.u6.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.6.0.x86_64.io-github-autotest-qemu.vsock_test.iommu_enabled.q35: STARTED
 (5/6) Host_RHEL.m9.u6.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.6.0.x86_64.io-github-autotest-qemu.vsock_test.iommu_enabled.q35: PASS (161.83 s)
 (6/6) Host_RHEL.m9.u6.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.6.0.x86_64.io-github-autotest-qemu.vsock_test.vsock_test_suite.q35: STARTED
 (6/6) Host_RHEL.m9.u6.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.6.0.x86_64.io-github-autotest-qemu.vsock_test.vsock_test_suite.q35: PASS (87.69 s)

**Comment by qcheng-redhat** [comment]
hi @ybduan, please help review this patch. Thanks!

**Comment by ybduan** [comment]
LGTM.
Acked-by: Yanbin Duan <yduan@redhat.com>

 (1/1) vsock_l2.Host_RHEL.m9.ux.v0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.x.0.x86_64.io-github-autotest-qemu.ansible_test.q35: PASS (365.96 s)

**Review by XueqiangWei — APPROVED** [review]
LGTM,
Acked-by: xuwei@redhat.com

**Pull request merged**
