### PR TITLE
generic.guest_test: new case to test isa_serial port

### PR DESCRIPTION
**Pull request by xutian**
Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by spcui** [comment]
LGTM,
Acked-by: @spcui

**Comment by xutian** [comment]
deps  on https://github.com/autotest/virt-test/pull/1952

**Comment by ypu** [comment]
LGTM

Acked-by: Yiqiao Pu <ypu@redhat.com>

**Comment by ypu** [comment]
Thanks @xutian and @spcui will merge it.

**Pull request merged**
