### PR TITLE
Add io testing on the FC passthrough with lun device

### PR DESCRIPTION
**Pull request by qingwangrh**
ID:2001756
Signed-off-by: qingwangrh <qinwang@redhat.com>

### CODE REVIEW

**Comment by qingwangrh** [comment]
@YongxueHong @menli820 @zhenyzha Please help to review ,thanks. This case need to run on host have FC device.

**Comment by qingwangrh** [comment]
Passed 
python ConfigTest.py --testcase=passthrough_fc_with_lun_device --guestname=Win2019,RHEL.8.4.0 --machines=q35,i440fx --clone=no

1-Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_block Finshed 2021-09-06 04:02:11 2021-09-06 04:03:09 PASS 57.935825
2-Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_block.q35 Finshed 2021-09-06 04:03:09 2021-09-06 04:04:01 PASS 52.73381
3-Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_generic Finshed 2021-09-06 04:04:01 2021-09-06 04:04:53 PASS 51.232488
4-Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_generic.q35 Finshed 2021-09-06 04:04:53 2021-09-06 04:05:45 PASS 52.399908
5-Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_block Finshed 2021-09-06 04:05:45 2021-09-06 04:07:40 PASS 114.608676
6-Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_block.q35 Finshed 2021-09-06 04:07:40 2021-09-06 04:09:44 PASS 124.471928
7-Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_generic Finshed 2021-09-06 04:09:44 2021-09-06 04:11:14 PASS 89.560844
8-Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_generic.q35 Finshed 2021-09-06 04:11:14 2021-09-06 04:12:47 PASS 93.870472
Summary: 
Finshed=8, PASS=8

**Comment by zhenyzha** [comment]
` (1/2) Host_RHEL.m8.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.aarch64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_block.arm64-pci: ERROR: Command 'cd /home/kar/workspace/avocado-vt/virttest; rpm -qa | grep device-mapper-multipath && { [ -f /etc/multipath.conf ] || mpathconf --enable;systemctl restart multipathd; }' failed.\nstdout: b'device-mapper-multipath-libs-0.8.4-17.el8.aarch64\n'\nstder... (6.66 s)`

Need to add 'yum install -y device-mapper-multipath' cmd on the host

**Comment by qingwangrh** [comment]
> ` (1/2) Host_RHEL.m8.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.aarch64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_block.arm64-pci: ERROR: Command 'cd /home/kar/workspace/avocado-vt/virttest; rpm -qa | grep device-mapper-multipath && { [ -f /etc/multipath.conf ] || mpathconf --enable;systemctl restart multipathd; }' failed.\nstdout: b'device-mapper-multipath-libs-0.8.4-17.el8.aarch64\n'\nstder... (6.66 s)`
> 
> Need to add 'yum install -y device-mapper-multipath' cmd on the host

The mulitpathd service is not must for the testing ,It only be start when system have installed  device-mapper-multipath . otherwise it will be ignored. the reason is the grep is not precise. updated patch will fix it. thanks.

**Comment by zhenyzha** [comment]
> The mulitpathd service is not must for the testing ,It only be start when system have installed device-mapper-multipath . otherwise it will be ignored. the reason is the grep is not precise. updated patch will fix it. thanks.

By default, `device-mapper-multipath` is not installed on the ARM platform, so this error can still be triggered when `yum install -y device-mapper-multipath` is not used.
But when I manually running `yum install -y device-mapper-multipath`, the error will not be triggered.

**Comment by zhenyzha** [comment]
```
 (1/2) Host_RHEL.m8.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.aarch64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_block.arm64-pci: CANCEL: No FC device (6.51 s)
 (2/2) Host_RHEL.m8.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.aarch64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_generic.arm64-pci: CANCEL: No FC device (4.99 s)
```
At present, Multi-Arch does not have an FC environment, and if we encounter platform-specific problems in the future, I will solve them by myself.

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Review by zhenyzha — APPROVED** [review]

**Comment by menli820** [comment]
Add @peixiu  for scsi part, thanks

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
