### PR TITLE
add hugepage test for ppc which default hugepage size is 16M

### PR DESCRIPTION
**Pull request by Zhengtong**
ID: 1339117

### CODE REVIEW

**Comment by CongLi** [comment]
From the commit log, I have thought it's a framework update,
please specify hotplug_mem: *** if it's only for this case.

**Comment by Zhengtong** [comment]
Updated , thanks

**Comment by CongLi** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by PandaWei** [comment]
LGTM, 
But I don't test it. so just give this a ACK.
Maybe other guys can confirm again and merge it

**Pull request merged**
