### PR TITLE
ovs_quit: Fix bugs and improve code

### PR DESCRIPTION
**Pull request by PaulYuuu**
This test case does not work now, fix bugs and improve code

ID: 1768681
Signed-off-by: Yihuang Yu <yihyu@redhat.com>

### CODE REVIEW

**Comment by PaulYuuu** [comment]
(1/1) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.ovs_quit: PASS (5.47 s)

**Comment by PaulYuuu** [comment]
@pezhang @yanglei-rh Please help to review, thanks.

**Comment by yanglei-rh** [comment]
LGTM and Test pass

(1/2) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.ovs_quit.q35: PASS (4.29 s)
 (2/2) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.ovs_quit.enslave_port.q35: PASS (2.27 s)

Acked-by: Lei Yang leiyang@redhat.com

**Comment by PaulYuuu** [comment]
@vivianQizhu Could you take a time to review and merge it? thanks.

**Comment by vivianQizhu** [comment]
Ack.

**Pull request merged**
