### PR TITLE
plug_cdrom: special device /dev/sr0 does not exist

### PR DESCRIPTION
**Pull request by bgartzi**
This commit expands the "wait until the device is detected in guest then mount" that was being followed in tests involving windows guests. That way, it fixes the some tests with linux guests were having.

ID: 2032983

### CODE REVIEW

**Comment by bgartzi** [comment]
@YongxueHong @luckyh @qingwangrh @fbq815 would you help me review this and check that it fills the needs of the bz?

Thank you!

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=plug_cdrom.with_hotplug --guestname=RHEL.8.6.0,Win2019 --machines=q35,i440fx --clone=no  --nrepeat=10

RESULTS    : PASS 40 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

LGTM

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by YongxueHong** [comment]
Hi @fbq815 
Can you help me to review it, thanks.

**Comment by fbq815** [comment]
JOB ID     : e135cc0945360552d3de10158e128d9e9f9a0b89
JOB LOG    : /root/avocado/job-results/job-2022-01-27T23.25-e135cc0/job.log
 (1/2) Host_RHEL.m9.u0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.s390-virtio: PASS (462.94 s)
 (2/2) Host_RHEL.m9.u0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.plug_cdrom.with_hotplug.reboot_vm.s390-virtio: PASS (37.08 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2022-01-27T23.25-e135cc0/results.html
JOB TIME   : 501.67 s

LGTM

**Review by fbq815 — APPROVED** [review]

**Comment by YongxueHong** [comment]
Thanks all, let's merge it.

**Pull request merged**
