### PR TITLE
fix 'Could not open '/tmp/*' issue on rhel9

### PR DESCRIPTION
**Pull request by menli820**
The files in /tmp dir will be removed after reboot on rhel9
but the files still useful after reboot so change the path
to /var/tmp to let the files preserved.

ID: 1925456
Signed-off-by: Menghuan Li menli@redhat.com

### CODE REVIEW

**Comment by menli820** [comment]
python3 ConfigTest.py --testcase=block_resize.with_md5.with_data_disk.fmt_qcow2.default_partition.q35  --guestname=Win2016 --platform=x86_64  --driveformat=virtio_blk,virtio_scsi   --machines=q35

```
 (1/4) Host_RHEL.m8.u5.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (865.71 s)
 (2/4) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (850.67 s)
 (3/4) Host_RHEL.m8.u5.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.block_resize.with_md5.with_data_disk.fmt_qcow2.default_partition.q35: PASS (369.91 s)
 (4/4) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.block_resize.with_md5.with_data_disk.fmt_qcow2.default_partition.q35: PASS (361.16 s)

```


python3 ConfigTest.py --testcase=plug_cdrom  --guestname=Win2019 --platform=x86_64  --driveformat=virtio_blk,virtio_scsi   --machines=q35  --clone=no
```
 (1/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.plug_cdrom.with_hotplug.reboot_vm.q35: PASS (151.03 s)
 (2/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.plug_cdrom.with_unplug.reboot_vm.q35: PASS (140.52 s)
```

python3 ConfigTest.py --testcase=migration_with_block  --guestname=Win2019 --platform=x86_64  --driveformat=virtio_blk,virtio_scsi   --machines=q35  --clone=no

```
 (01/12) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.migration_with_block.with_scsi_on2off.send_qmp.shutdown_vm.q35: PASS (161.74 s)
 (02/12) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.migration_with_block.with_scsi_on2off.send_qmp.reboot_vm.q35: PASS (147.73 s)
 (03/12) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.migration_with_block.with_scsi_on2off.send_shell.shutdown_vm.q35: PASS (111.54 s)
 (04/12) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.migration_with_block.with_scsi_on2off.send_shell.reboot_vm.q35: PASS (177.98 s)
 (05/12) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.migration_with_block.with_dataplane_on2off.send_qmp.shutdown_vm.q35: PASS (340.60 s)
 (06/12) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.migration_with_block.with_dataplane_on2off.send_qmp.reboot_vm.q35: PASS (436.66 s)
 (07/12) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.migration_with_block.with_dataplane_on2off.send_shell.shutdown_vm.q35: FAIL: Failed to shutdown vm. (939.51 s)
 (08/12) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.migration_with_block.with_dataplane_on2off.send_shell.reboot_vm.q35: PASS (384.59 s)
 (09/12) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.migration_with_block.with_change_cdrom.send_qmp.shutdown_vm.q35: ERROR: 'drive_orig' (173.97 s)
 (10/12) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.migration_with_block.with_change_cdrom.send_qmp.reboot_vm.q35: ERROR: 'drive_orig' (167.60 s)
 (11/12) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.migration_with_block.with_change_cdrom.send_shell.shutdown_vm.q35: ERROR: 'drive_orig' (170.13 s)
 (12/12) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.migration_with_block.with_change_cdrom.send_shell.reboot_vm.q35: ERROR: 'drive_orig' (174.10 s)
RESULTS    : PASS 7 | ERROR 4 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

```
The fail and error for existing auto and product bugs.

**Comment by menli820** [comment]
@peixiu,  @qingwangrh , @YongxueHong  please help to review it when you free, thanks

**Comment by peixiu** [comment]
Hi @menli820 Could you help to update these files as well, they are impact virtio_win_scsi loop~

device_option_check.cfg
multi_disk.cfg
win_virtio_driver_update_test.cfg
block_hotplug_check.cfg
win_virtio_update.cfg
eject_media.cfg

Thanks a lot~
Peixiu

**Comment by menli820** [comment]
> device_option_check

sure， will update later

**Comment by qingwangrh** [comment]
@menli820 ,this patch related to qemu/tests/cfg/migration_with_block.cfg, there is issue for rhel9.
(1/5) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.migration_with_block.with_change_cdrom.send_qmp.shutdown_vm.q35: ERROR: 'drive_orig' (40.18 s)
 (2/5) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.migration_with_block.with_change_cdrom.send_qmp.reboot_vm.q35:ERROR: 'drive_orig' (38.74 s)
 (3/5) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.migration_with_block.with_change_cdrom.send_shell.shutdown_vm.q35: ERROR: 'drive_orig' (37.88 s)
 (4/5) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.migration_with_block.with_change_cdrom.send_shell.reboot_vm.q35: ERROR: 'drive_orig' (39.87 s)
 (5/5) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.migration_with_block.with_post_copy.with_mem_stress.q35

I think above issue maybe fixed https://github.com/autotest/tp-qemu/pull/2769, Could you please discuss with phou to see whether merge  them into one patch ? @peixiu  what is your option ?

**Comment by menli820** [comment]
> @menli820 ,this patch related to qemu/tests/cfg/migration_with_block.cfg, there is issue for rhel9.
> (1/5) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.migration_with_block.with_change_cdrom.send_qmp.shutdown_vm.q35: ERROR: 'drive_orig' (40.18 s)
> (2/5) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.migration_with_block.with_change_cdrom.send_qmp.reboot_vm.q35:ERROR: 'drive_orig' (38.74 s)
> (3/5) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.migration_with_block.with_change_cdrom.send_shell.shutdown_vm.q35: ERROR: 'drive_orig' (37.88 s)
> (4/5) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.migration_with_block.with_change_cdrom.send_shell.reboot_vm.q35: ERROR: 'drive_orig' (39.87 s)
> (5/5) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.migration_with_block.with_post_copy.with_mem_stress.q35
> 
> I think above issue maybe fixed #2769, Could you please discuss with phou to see whether merge them into one patch ? @peixiu what is your option ?

discuss with phou, plan to delete migration_with_block.cfg, from this patch and add to  #2769, let this patch continue, thanks.

**Comment by qingwangrh** [comment]
> > @menli820 ,this patch related to qemu/tests/cfg/migration_with_block.cfg, there is issue for rhel9.
> > (1/5) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.migration_with_block.with_change_cdrom.send_qmp.shutdown_vm.q35: ERROR: 'drive_orig' (40.18 s)
> > (2/5) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.migration_with_block.with_change_cdrom.send_qmp.reboot_vm.q35:ERROR: 'drive_orig' (38.74 s)
> > (3/5) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.migration_with_block.with_change_cdrom.send_shell.shutdown_vm.q35: ERROR: 'drive_orig' (37.88 s)
> > (4/5) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.migration_with_block.with_change_cdrom.send_shell.reboot_vm.q35: ERROR: 'drive_orig' (39.87 s)
> > (5/5) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.migration_with_block.with_post_copy.with_mem_stress.q35
> > I think above issue maybe fixed #2769, Could you please discuss with phou to see whether merge them into one patch ? @peixiu what is your option ?
> 
> @qingwangrh discuss with @peixiu , plan to delete migration_with_block.cfg, from this patch and add to #2769, let both patch continue, thanks.

Ok, It is ok for me

**Comment by menli820** [comment]
for case eject_media.cfg need to modify following file as well  in kar need another patch
internal_cfg/guest-os/Windows.cfg
    eject_media:
        cdroms += " cd2"
        cdrom_cd1 = /tmp/orig.iso
        cdrom_cd2 = isos/windows/winutils.iso

 (1/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.eject_media.force_eject.q35: PASS (85.73 s)
 (2/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.eject_media.eject.q35: PASS (85.21 s)

**Comment by menli820** [comment]
> Hi @menli820 Could you help to update these files as well, they are impact virtio_win_scsi loop~
> 
> device_option_check.cfg
> multi_disk.cfg
> win_virtio_driver_update_test.cfg
> block_hotplug_check.cfg
> win_virtio_update.cfg
> eject_media.cfg
> 
> Thanks a lot~
> Peixiu

As discuss with you win_virtio_driver_update_test.cfg and  win_virtio_update.cfg no need to do update now

**Comment by peixiu** [comment]
LGTM. Thanks~

Acked-by: Peixiu Hou phou@redhat.com

**Review by peixiu — APPROVED** [review]

**Comment by qingwangrh** [comment]
python3 ConfigTest.py --testcase=block_hotplug_check,block_resize,device_option_check,eject_media,multi_disk --guestname=RHEL.9.0.0 --platform=x86_64  --machines=q35 --clone=no

(01/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.multi_disk.one_disk_repeat.q35: PASS (73.14 s)
 (02/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.multi_disk.max_disk.q35: PASS (427.59 s)
 (03/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.multi_disk.all_drive_format_types.q35: PASS (49.18 s)
 (04/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.block.q35: PASS (89.49 s)
 (05/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writethrough.q35: PASS (90.70 s)
 (06/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writeback.q35: PASS (89.44 s)
 (07/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_lun.q35: PASS (610.07 s)
 (08/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_scsiid_lun.q35: PASS (240.81 s)
 (09/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun.q35: PASS (307.85 s)
 (10/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.eject_media.force_eject.q35: PASS (38.59 s)
 (11/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.eject_media.eject.q35: PASS (38.58 s)
 (12/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.block_resize.with_iozone.with_data_disk.fmt_qcow2.default_partition.q35: PASS (130.82 s)
 (13/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.block_resize.with_iozone.with_data_disk.fmt_qcow2.with_gpt_ext4.q35: PASS (84.36 s)
 (14/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.block_resize.with_iozone.with_data_disk.fmt_qcow2.with_msdos_xfs.q35: PASS (79.33 s)
 (15/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.block_resize.with_iozone.with_data_disk.fmt_qcow2.with_gpt_xfs.q35: PASS (82.18 s)
 (16/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.block_resize.with_iozone.with_data_disk.fmt_raw.default_partition.q35: PASS (129.90 s)
 (17/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.block_resize.with_iozone.with_data_disk.fmt_raw.with_gpt_ext4.q35: PASS (81.77 s)
 (18/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.block_resize.with_iozone.with_data_disk.fmt_raw.with_msdos_xfs.q35: PASS (79.10 s)
 (19/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.block_resize.with_iozone.with_data_disk.fmt_raw.with_gpt_xfs.q35: PASS (79.99 s)
 (20/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.block_resize.with_md5.with_data_disk.fmt_qcow2.default_partition.q35: PASS (91.11 s)
 (21/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.block_resize.with_md5.with_data_disk.fmt_raw.default_partition.q35: PASS (90.04 s)
 (22/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.device_option_check.blk_wwn_check.wwn_disk.default_drive_format.q35: PASS (29.90 s)
 (23/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.device_option_check.blk_wwn_check.wwn_disk.special_drive_format.q35: PASS (29.62 s)
 (24/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.device_option_check.blk_wwn_check.wwn_cdrom.default_drive_format.q35: PASS (30.75 s)
 (25/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.device_option_check.blk_wwn_check.wwn_cdrom.special_drive_format.q35: PASS (28.29 s)
 (26/26) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.device_option_check.blk_serial_check.q35: PASS (28.61 s)

LGTM

**Review by YongxueHong — APPROVED** [review]
LGTM

**Pull request merged**
