### PR TITLE
blockdev_stream_dirty_bitmap:block stream with dirty bitmap

### PR DESCRIPTION
**Pull request by aliang123**
Block-stream wouldn't dirty the bitmap of active layer

Signed-off-by: Aihua Liang <aliang@redhat.com>
id:2014380

### CODE REVIEW

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_dirty_bitmap.q35: PASS (41.45 s)

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_dirty_bitmap.q35: PASS (41.28 s)

**Comment by aliang123** [comment]
@zhencliu @ngu-niny, please help to review, thanks.

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_dirty_bitmap.q35: PASS (42.24 s)

**Comment by ngu-niny** [comment]
PASS 1-Host_RHEL.m8.u6.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_stream_dirty_bitmap

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
