### PR TITLE
Support block hotplug for gluster storage backend

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1789287

### CODE REVIEW

**Comment by zhencliu** [comment]
JOB LOG    : /home/lzc/kar/workspace/job-results/job-2020-02-26T00.57-6245756/job.log
 (1/6) Host_RHEL.m8.u2.product_av.gluster.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_qcow2: PASS (118.04 s)
 (2/6) Host_RHEL.m8.u2.product_av.gluster.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_raw: PASS (120.81 s)
 (3/6) Host_RHEL.m8.u2.product_av.gluster.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_luks: PASS (119.43 s)
 (4/6) Host_RHEL.m8.u2.product_av.gluster.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_qcow2: PASS (115.56 s)
 (5/6) Host_RHEL.m8.u2.product_av.gluster.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_raw: PASS (120.87 s)
 (6/6) Host_RHEL.m8.u2.product_av.gluster.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_luks: PASS (119.97 s)

**Comment by zhencliu** [comment]
@hellohellenmao

**Comment by YongxueHong** [comment]
Please shorten the commit message title under 69 characters.
Thanks.

**Comment by zhencliu** [comment]
> Please shorten the commit message title under 69 characters.
> Thanks.

Done, thanks @YongxueHong

**Pull request merged**
