### PR TITLE
qemu.test.pxe_boot: extend pxe_timeout to 360s

### PR DESCRIPTION
**Pull request by yanan-fu**
Signe-off-by: Yanan Fu <yfu@redhat.com>

### CODE REVIEW

**Comment by suqinhuang** [comment]
seems a little long, could you provide the reason, and the id ?

**Comment by yanan-fu** [comment]
@suqinhuang 
There has one closed bug (id: 1196475), it closed as "not a bug", and i didn't filter new one.
this is a network problem, depends on the test environment.

Now, we have two pxe server "10.73.2.110" , "10.73.60.74", different host will use different pxe server(depends on the network segment it is).
I checked when i meet bz 1196475,  after load pxelinux.cfg/*, it cause nearly 3 mins and then go ahead ... 
for pass case, it is very fast. They use different pxe server.

In this case, once it get TFTP package, it will finished. long time will not cause extra time when test pass,  and it is more guaranteed. thanks !

**Comment by suqinhuang** [comment]
LGTM
Acked

**Comment by vivianQizhu** [comment]
Acked-by: Qianqian Zhu qizhu@redhat.com

**Comment by CongLi** [comment]
Thanks @yanan-fu @suqinhuang @vivianQizhu .

**Pull request merged**
