### PR TITLE
timedrift: Bypass the issue of pickle _thread.RLock with Python < 3.7

### PR DESCRIPTION
**Pull request by PaulYuuu**
As https://bugs.python.org/issue30520 mentioned, Python < 3.7 has the
issue for picking the logger object, so here is a workaround to bypass
this issue.

ID: 2114619
Signed-off-by: Yihuang Yu <yihyu@redhat.com>

### CODE REVIEW

**Comment by PaulYuuu** [comment]
Hello @maxujun @YanhuiMa, the issue should happen on Python3.6(RHEL.8), could you help to review and test it on your architecture? Thanks in advance.

**Comment by PaulYuuu** [comment]
> (1/1) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.timedrift.shared_ntp_date.with_load.default_load: ERROR: can't pickle _thread.RLock objects (237.27 s)
> 
> It doesn't run this step "aexpect.run_bg" since "host_load_instances = 0" . Should modify guest_load_instances part,but I have tried,still have another problem.

OK, thanks for pointing it, updated it.

**Comment by maxujun** [comment]
(1/1) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.timedrift.shared_ntp_date.with_load.default_load: PASS (208.65 s)
I lost "global _picklable_logger" before. LGTM，Ack.

**Comment by YanhuiMa** [comment]
> Hello @maxujun @YanhuiMa, the issue should happen on Python3.6(RHEL.8), could you help to review and test it on your architecture? Thanks in advance.

Hello @PaulYuuu , for x86 timer device, I don't run the case.

**Comment by PaulYuuu** [comment]
> > Hello @maxujun @YanhuiMa, the issue should happen on Python3.6(RHEL.8), could you help to review and test it on your architecture? Thanks in advance.
> 
> Hello @PaulYuuu , for x86 timer device, we don't run the case.

OK, thanks for the info.

**Pull request merged**
