### PR TITLE
Switch to dhcpcd command for the newer guest

### PR DESCRIPTION
**Pull request by yanglei-rh**
Due to dhcp-client has been replaced with dhcpcd in the future, so modified these cases to switch to dhcpcd command for the newer guest.

ID:2528
Signed-off-by: Lei Yang leiyang@redhat.com

### CODE REVIEW

**Review by PaulYuuu — DISMISSED** [review]

**Comment by PaulYuuu** [comment]
cc @fbq815

**Comment by yanglei-rh** [comment]
Hi @PaulYuuu After my tests, I found that the last version had problems, so I pushed it again. Please help review it again, thanks a lot. This version can test pass on my side.

**Comment by yanglei-rh** [comment]
Hi @PaulYuuu Could you please help review this patch again? And help merge it, all cases can test pass on my side. Thanks.

**Review by PaulYuuu — APPROVED** [review]

**Comment by fbq815** [comment]
Test result on s390x:
RESULTS    : PASS 2 | ERROR 3 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2024-07-01T23.01-9a9739c/results.html
JOB TIME   : 1332.97 s

I've paste the test log as a comment in the jira issue

**Pull request merged**
