### PR TITLE
blockdev_snapshot: support backend ceph support for live snapshot

### PR DESCRIPTION
**Pull request by aliang123**
Add ceph support for live snapshot

Signed-off-by: Aihua Liang <aliang@redhat.com>
id:2045982

### CODE REVIEW

**Comment by aliang123** [comment]
(10/23) Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_chains.q35: PASS (209.63 s)
 (11/23) Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_install.q35: PASS (1001.09 s)
 (12/23) Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_stress.q35: PASS (96.76 s)
 (13/23) Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot.q35: PASS (172.33 s)
 (14/23) Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot.dst_cluster_size_512.q35: PASS (135.45 s)
 (15/23) Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot.dst_cluster_size_2M.q35: PASS (132.93 s)
 (16/23) Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_reboot.q35: PASS (70.45 s)
 (17/23) Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_multi_disks.q35: PASS (110.08 s)
 (18/23) Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_stop_cont.q35: PASS (55.28 s)
 (20/23) Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_merge.q35: PASS (109.17 s)
 (21/23) Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_readonly.q35: PASS (83.61 s)
 (22/23) Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_data_file.q35: PASS (91.41 s)
 (23/23) Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_nonexist_target.q35: PASS (38.52 s)

**Comment by aliang123** [comment]
@zhencliu @ngu-niny @MiriamDeng, please help to review, thanks.

**Comment by MiriamDeng** [comment]
Tried it with the patch, it seems there's a piece of error message. Could you help to check it again ？Thanks
[root@ibm-p9wr-06 io-github-autotest-qemu]# git am 3198.patch
Applying: blockdev_snapshot:add ceph support
error: patch failed: qemu/tests/blockdev_snapshot_chains.py:27
error: qemu/tests/blockdev_snapshot_chains.py: patch does not apply
error: qemu/tests/cfg/blockdev_snapshot_data_file.cfg: does not exist in index
Patch failed at 0001 blockdev_snapshot:add ceph support
hint: Use 'git am --show-current-patch=diff' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

**Comment by aliang123** [comment]
Test cmd:
   python3 ConfigTest.py --guestname=RHEL.8.6.0 --platform=x86_64 --category=storage_vm_migration_blockdev --imageformat=raw --storage-backend-conf=/home/ceph.cfg --customsparams="no functional_block_stream functional_block_mirror functional_live_commit functional_incremental_live_backup"

**Comment by aliang123** [comment]
> Tried it with the patch, it seems there's a piece of error message. Could you help to check it again ？Thanks [root@ibm-p9wr-06 io-github-autotest-qemu]# git am 3198.patch Applying: blockdev_snapshot:add ceph support error: patch failed: qemu/tests/blockdev_snapshot_chains.py:27 error: qemu/tests/blockdev_snapshot_chains.py: patch does not apply error: qemu/tests/cfg/blockdev_snapshot_data_file.cfg: does not exist in index Patch failed at 0001 blockdev_snapshot:add ceph support hint: Use 'git am --show-current-patch=diff' to see the failed patch When you have resolved this problem, run "git am --continue". If you prefer to skip this patch, run "git am --skip" instead. To restore the original branch and stop patching, run "git am --abort".

Please update the code to latest.

**Comment by MiriamDeng** [comment]
Tried it but hit the following issues on ppc
...
/ (22/23) Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_nonexist_target: ERROR: 'CmdNotFoundError' object has no attribute 'message' (0.26 s)
 (23/23) Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_guest_agent: STARTED
\ (23/23) Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_guest_agent: ERROR: 'CmdNotFoundError' object has no attribute 'message' (0.27 s)

**Comment by ngu-niny** [comment]
@aliang123 Aihua, we do support rbd raw since qemu4.1, so we don't need to set the data image format as raw:

    ceph:
......
        enable_ceph_data = yes
        image_format_data = raw

**Comment by ngu-niny** [comment]
> @aliang123 Aihua, we do support rbd qcow2 since qemu4.1, so we don't need to set the data image format as raw:
> 
> ```
> ceph:
>     enable_ceph_data = yes
>     image_format_data = raw
> ```
> 
> In my test, the rbd qcow2 test could pass:
> 
> 01-Host_RHEL.m8.u6.product_rhel.ceph.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads Finshed 2022-02-14 02:24:40 2022-02-14 02:45:20 PASS 1239.26371 02-Host_RHEL.m8.u6.product_rhel.ceph.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_merge Finshed 2022-02-14 02:45:20 2022-02-14 02:48:49 PASS 209.393835 03-Host_RHEL.m8.u6.product_rhel.ceph.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_stress Finshed 2022-02-14 02:48:49 2022-02-14 02:51:58 ERROR 189.426586 04-Host_RHEL.m8.u6.product_rhel.ceph.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_reboot Finshed 2022-02-14 02:51:59 2022-02-14 02:54:13 PASS 134.056628 05-Host_RHEL.m8.u6.product_rhel.ceph.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_stop_cont Finshed 2022-02-14 02:54:13 2022-02-14 02:57:07 PASS 174.714421

Talked with Aihua, since there is still product bug on rbd qcow2, will postpone to add it.

**Comment by ngu-niny** [comment]
LGTM.

Most of the test cases PASS, while the failed ones are not caused by this patch.

01-Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads Finshed 2022-02-14 04:05:05 2022-02-14 04:22:22 PASS 1037.062929
02-Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot Finshed 2022-02-14 04:22:22 2022-02-14 04:26:32 PASS 250.080525
03-Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot.dst_cluster_size_512 Finshed 2022-02-14 04:26:32 2022-02-14 04:30:17 PASS 224.368174
04-Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot.dst_cluster_size_2M Finshed 2022-02-14 04:30:17 2022-02-14 04:34:00 PASS 223.169869
05-Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_readonly Finshed 2022-02-14 04:34:00 2022-02-14 04:37:18 PASS 197.84353
06-Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_stop_cont Finshed 2022-02-14 04:37:18 2022-02-14 04:40:03 PASS 164.575892
07-Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_chains Finshed 2022-02-14 04:40:03 2022-02-14 04:44:09 PASS 246.821606
08-Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_stress Finshed 2022-02-14 04:44:09 2022-02-14 04:45:59 ERROR 109.334072
09-Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_merge Finshed 2022-02-14 04:45:59 2022-02-14 04:49:36 PASS 217.224492
10-Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_install Finshed 2022-02-14 04:49:36 2022-02-14 05:08:11 PASS 1114.469525
11-Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_reboot Finshed 2022-02-14 05:08:11 2022-02-14 05:11:18 PASS 187.544329
12-Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_guest_agent Finshed 2022-02-14 05:11:18 2022-02-14 05:16:07 PASS 289.166036
13-Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_multi_disks Finshed 2022-02-14 05:16:08 2022-02-14 05:20:14 PASS 246.460762
14-Host_RHEL.m8.u6.product_rhel.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_data_file Finshed 2022-02-14 05:20:14 2022-02-14 05:23:04 FAIL 169.872108

Acked-by: Nini Gu <ngu@redhat.com>

**Comment by zhencliu** [comment]
Confirmed with @aliang123 , we will submit a pr to make an enhancement for the image format in future.
LGTM

**Comment by MiriamDeng** [comment]
Re-test it with the patch updated and will update the result today.

**Comment by MiriamDeng** [comment]
All test cases passed except for the followings and I pasted the log to the auto bug for your reference. Thanks
 (20/23) Host_RHEL.m8.u6.product_av.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_data_file: FAIL: AssertionError("Get file ('data') MD5 with error: md5sum: /mnt/sdb1/data: No such file or directory\n",) (179.12 s)
 (21/23) Host_RHEL.m8.u6.product_av.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_guest_agent: STARTED
- (21/23) Host_RHEL.m8.u6.product_av.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_guest_agent: ERROR: Command '/usr/bin/qemu-img rebase -f qcow2 -u -b rbd:rbd/rhel900-ppc64le-virtio-scsi.raw -F raw rbd:rbd/sn1.qcow2' failed.\nstdout: b''\nstderr: b"qemu-img: Could not open 'rbd:rbd/sn1.qcow2': error reading header from sn1.qcow2: No such file or directory\n... (178.03 s)

**Comment by aliang123** [comment]
(1/2) Host_RHEL.m8.u6.product_av.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_guest_agent: PASS (229.44 s)
(2/2) Host_RHEL.m8.u6.product_av.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_data_file: PASS (183.41 s)

**Comment by MiriamDeng** [comment]
ACK

**Pull request merged**
