### PR TITLE
blockdev_mirror_after_block_error: add event timeout

### PR DESCRIPTION
**Pull request by aliang123**
Set BLOCK_IO_ERROR event timeout

Signed-off-by: Aihua Liang <aliang@redhat.com>
id:1966879

### CODE REVIEW

**Comment by aliang123** [comment]
(01/10) repeat1.Host_RHEL.m8.u6.product_rhel.raw.virtio_blk.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_mirror_after_block_error: PASS (60.99 s)
 (02/10) repeat2.Host_RHEL.m8.u6.product_rhel.raw.virtio_blk.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_mirror_after_block_error: PASS (60.26 s)
 (03/10) repeat3.Host_RHEL.m8.u6.product_rhel.raw.virtio_blk.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_mirror_after_block_error: PASS (82.61 s)
 (04/10) repeat4.Host_RHEL.m8.u6.product_rhel.raw.virtio_blk.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_mirror_after_block_error: PASS (60.25 s)
 (05/10) repeat5.Host_RHEL.m8.u6.product_rhel.raw.virtio_blk.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_mirror_after_block_error: PASS (60.29 s)
 (06/10) repeat6.Host_RHEL.m8.u6.product_rhel.raw.virtio_blk.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_mirror_after_block_error: PASS (61.44 s)
 (07/10) repeat7.Host_RHEL.m8.u6.product_rhel.raw.virtio_blk.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_mirror_after_block_error: PASS (61.48 s)
 (08/10) repeat8.Host_RHEL.m8.u6.product_rhel.raw.virtio_blk.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_mirror_after_block_error: PASS (59.10 s)
 (09/10) repeat9.Host_RHEL.m8.u6.product_rhel.raw.virtio_blk.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_mirror_after_block_error: PASS (58.20 s)
 (10/10) repeat10.Host_RHEL.m8.u6.product_rhel.raw.virtio_blk.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_mirror_after_block_error: PASS (58.31 s)

**Comment by aliang123** [comment]
@zhencliu @ngu-niny, please help to review, thanks.

**Comment by zhencliu** [comment]
hi @aliang123 , the change is OK for me, I just have a question about the failure,
is it reasonable that we got the io error event after 90+s since dd finished?

**Comment by aliang123** [comment]
> hi @aliang123 , the change is OK for me, I just have a question about the failure, is it reasonable that we got the io error event after 90+s since dd finished?

There is no defination about this time in the qemu code. And in fact, it's a performace issue. Base on the function test, 
I think, 120s is acceptable, so set the maximum value 120s here.

**Comment by zhencliu** [comment]
> I think, 120s is acceptable, so set the maximum value 120s here.

Thanks for your reply.

Acked.

**Comment by ngu-niny** [comment]
1-Host_RHEL.m8.u6.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_mirror_after_block_error Finshed 2021-11-29 00:21:03 2021-11-29 00:23:47 PASS 164.215267

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
