### PR TITLE
tp-qemu: single_driver_install: remove scenarios "downgrade" and "uninstall"

### PR DESCRIPTION
**Pull request by CongLi**
1. Remove scenarios "downgrade" and "uninstall".
This case won't upgrade / install driver after
 downgrade / uninstall, which is not acceptable.
Will write new case to cover those scenarios.
2. rename variant "uninstall".
3. remove some unreasonable cfg.

Signed-off-by: Cong Li <coli@redhat.com>

### CODE REVIEW

**Comment by CongLi** [comment]
@suqinhuang 

Could you help review this PR?

Thanks.

**Comment by suqinhuang** [comment]
Acked-by: Suqin Huang

**Comment by pingl2016** [comment]
After apply the patch, downgrade and reinstall cases are dropped. But found 2 issue about the script as below:
1. "image_name_stg = "images/storage" "  is set for variants with_viostor and with_vioscsi, but image storage.qcow2 is not created for test.
2. Login timeout after reboot guest, the script run the finally blocks in line 148 and raise driver install log exception.
Anyway, the patch itself works fine.
Acked-by: Ping Li pingl@redhat.com

**Comment by suqinhuang** [comment]
Greate, pingl, could you create an issue for the issue you find.

**Comment by CongLi** [comment]
Thanks @pingl2016 .
The problem 1 is fixed in https://github.com/autotest/tp-qemu/pull/628

**Comment by suqinhuang** [comment]
Merge it
for @pingl2016's comment
problem 1 is fixed in #628 
problem 2 is know issue

**Pull request merged**
