### PR TITLE
nvdimm:add dependent package for test case nvdimm_nvml

### PR DESCRIPTION
**Pull request by MiriamDeng**
ID:2040157
Signed-off-by: MiriamDeng <mdeng@redhat.com>

### CODE REVIEW

**Comment by MiriamDeng** [comment]
@PaulYuuu @maxujun can you help to review it ? Thanks a lot

**Comment by MiriamDeng** [comment]
Test result,
 (1/1) Host_RHEL.m8.u7.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.ppc64le.io-github-autotest-qemu.nvdimm.nvdimm_nvml: PASS (2216.15 s)

**Review by PaulYuuu — APPROVED** [review]
LGTM

**Comment by maxujun** [comment]
LGTM,Acked.

**Pull request merged**
