### PR TITLE
shutdown: system_powerdown test fails if vt_type is libvirt

### PR DESCRIPTION
**Pull request by balamuruhans**
generic tests for shutdown fails if vt_type is libvirt, handled
the monitor command using virsh for it to work.

Signed-off-by: Balamuruhan S <bala24@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by balamuruhans** [comment]
**Issue**
```
2017-11-13 13:13:09,390 stacktrace       L0047 ERROR| Traceback (most recent call last):
2017-11-13 13:13:09,390 stacktrace       L0047 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-55.0-py2.7.egg/avocado_vt/test.py", line 397, in _runTest
2017-11-13 13:13:09,390 stacktrace       L0047 ERROR|     run_func(self, params, env)
2017-11-13 13:13:09,391 stacktrace       L0047 ERROR|   File "/usr/lib/python2.7/site-packages/autotest/client/shared/error.py", line 140, in new_fn
2017-11-13 13:13:09,391 stacktrace       L0047 ERROR|     return fn(*args, **kwargs)
2017-11-13 13:13:09,391 stacktrace       L0047 ERROR|   File "/home/bala/avocado-fvt-wrapper/data/avocado-vt/test-providers.d/downloads/powerkvm-qemu/generic/tests/shutdown.py", line 50, in run
2017-11-13 13:13:09,391 stacktrace       L0047 ERROR|     vm.monitor.system_powerdown()
2017-11-13 13:13:09,391 stacktrace       L0047 ERROR| AttributeError: 'VM' object has no attribute 'monitor'
```

**Comment by balamuruhans** [comment]
**with fix**
```
# avocado run --vt-type libvirt --vt-config /home/bala/avocado-fvt-wrapper/data/avocado-vt/backends/libvirt/cfg/lifecycle.cfg  --vt-only-filter "virtio_scsi qcow2 Pegas.1.0.ppc64le" --vt-no-filter "user network macvtap"
JOB ID     : 517f184922445314ab8b4da6b10d4ef8d8241492
JOB LOG    : /home/bala/avocado-fvt-wrapper/results/job-2017-11-13T12.27-517f184/job.log
 (1/1) guest_shutdown.qemu.qcow2.virtio_scsi.smp2.virtio_net.Pegas.1.0.ppc64le.powerkvm-qemu.shutdown: PASS (999.18 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 1006.64 s
JOB HTML   : /home/bala/avocado-fvt-wrapper/results/job-2017-11-13T12.27-517f184/results.html

```

**Comment by luckyh** [comment]
LGTM, however I'm wondering why libvirt test would use a script of tp-qemu?

**Comment by balamuruhans** [comment]
> LGTM, however I'm wondering why libvirt test would use a script of tp-qemu?
@luckyh I believe generic tests in tp-qemu can be used and triggered from both libvirt and qemu, correct me if it is wrong.

**Comment by balamuruhans** [comment]
In all the cfgs in tp-qemu/generic/tests/cfg, we can observe `virt_test_type = qemu libvirt` from which I inferred so.

**Comment by luckyh** [comment]
@balamuruhans well, it's legacy problem, anyway, for this issue, now I'd suggest introducing a "high-level" interface which can be named to `system_powerdown` to the VM class (both qemu and libvirt).

**Comment by sathnaga** [comment]
@luckyh @balamuruhans I am thinking of idea of abstracting vm.monitor in virt_vm() so that both
qemu and libvirt testcases utilize it, 

thinking of using ```virsh help qemu-monitor-command
  NAME
    qemu-monitor-command - QEMU Monitor Command

  SYNOPSIS
    qemu-monitor-command <domain> [--hmp] [--pretty] {[--cmd] <string>}...

```
comment your views

**Comment by luckyh** [comment]
@sathnaga thanks for your idea, however, I'm not sure whether a `ovirt` vm can support manipulating monitor (but we can still bring it to the qemu and libvirt subclass).

I'd prefer my suggestion because any types of vm should has a `system_powerdown` operation, shouldn't it?

**Comment by sathnaga** [comment]
@luckyh Am not aware of the `ovirt` vm shortcomings, ideally the abstraction which I am mentioning should be in the same lines of this patch for libvirt, just that It would generalize for all commands instead of just one command i.e `powerdown` in this case.
Regarding shortcomings for certain vm, whom ever uses it, can be cautious in future?

**Comment by sathnaga** [comment]
@luckyh Just that, we will have system_powerdown method using that abstracted method

**Comment by balamuruhans** [comment]
@luckyh @sathnaga Thanks for the suggestions, I have implemented Monitor interface to handle this issue https://github.com/avocado-framework/avocado-vt/pull/1225.
Test works seamless with the interface, hence closing this PR.

**Pull request closed without merging**
