### PR TITLE
New test case to test bitmap mode option for blockdev backup

### PR DESCRIPTION
**Pull request by xutian**
ID: 1812383, 1812384, 1812389

### CODE REVIEW

**Comment by xutian** [comment]
INFO | Start to run test
JOB ID     : d1c75a51bb91fbd93f6c997c64f1c88ac7439baa
JOB LOG    : /root/avocado/job-results/job-2020-03-11T16.27-d1c75a5/job.log
 (1/3) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_bitmap_mode.bitmap_always.q35: PASS (88.01 s)
 (2/3) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_bitmap_mode.bitmap_never.q35: PASS (85.69 s)
 (3/3) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_bitmap_mode.bitmap_success.q35: PASS (93.56 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 269.32 s
JOB HTML   : /root/avocado/job-results/job-2020-03-11T16.27-d1c75a5/results.html

**Comment by xutian** [comment]
@aliang123  @ngu-niny  Would you help to review this PR when free. 

thanks,
Xu

**Comment by aliang123** [comment]
(1/3) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_bitmap_mode.bitmap_always.q35: PASS (73.85 s)
 (2/3) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_bitmap_mode.bitmap_never.q35: PASS (79.21 s)
 (3/3) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_bitmap_mode.bitmap_success.q35: PASS (77.91 s)

Acked-by: Aihua Liang <aliang@redhat.com>

**Comment by ngu-niny** [comment]
Test PASS:

 (1/3) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_bitmap_mode.bitmap_always: PASS (125.39 s)
 (2/3) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_bitmap_mode.bitmap_never: PASS (129.50 s)
 (3/3) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_bitmap_mode.bitmap_success: PASS (138.03 s)

Acked-by: Nini Gu <ngu@redhat.com>

**Comment by xutian** [comment]
thanks @ngu-niny and @aliang123

**Pull request merged**
