### PR TITLE
Snapshot during guest stop_cont

### PR DESCRIPTION
**Pull request by aliang123**
blockdev_snapshot_stop_cont: snapshot during guest stop_cont

Signed-off-by: Aihua Liang <aliang@redhat.com>

id: 1800428

### CODE REVIEW

**Comment by aliang123** [comment]
@meet-lucky, @ngu-niny, @xutian, please help to review, thanks.

**Comment by meet-lucky** [comment]
(1/3) Host_RHEL.m8.u2.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (983.00 s)
 (2/3) Host_RHEL.m8.u2.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.rh_kernel_update.q35: PASS (299.90 s)
 (3/3) Host_RHEL.m8.u2.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_stop_cont.q35: ERROR: 'VM' object has no attribute 'stop' (51.44 s)

Acked-by: Qian Dong  qdong@redhat.com

**Comment by meet-lucky** [comment]
(1/1) Host_RHEL.m8.u2.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_stop_cont.q35: PASS (54.15 s)

Acked-by: Qian Dong qdong@redhat.com

**Comment by ngu-niny** [comment]
Test PASS:

'1-repeat1.Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.ppc64le.io-github-autotest-qemu.blockdev_snapshot_stop_cont' Finshed 2020-02-09 21:22:05 2020-02-09 21:23:26 PASS 81.462744
'2-repeat2.Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.ppc64le.io-github-autotest-qemu.blockdev_snapshot_stop_cont' Finshed 2020-02-09 21:23:26 2020-02-09 21:25:06 PASS 100.09177

Acked-by: Nini Gu <ngu@redhat.com>

**Comment by xutian** [comment]
LGTM, thanks @aliang123 and @ngu-niny  and @meet-lucky

**Pull request merged**
