### PR TITLE
virtio_console: fix RegEx to check qemu version

### PR DESCRIPTION
**Pull request by nanliu-r**
virtio_console: fix RegEx to check qemu version

Signed-off-by: Nana Liu <nanliu@redhat.com>

### CODE REVIEW

**Comment by nanliu-r** [comment]
change RegEx "2\.\d+\.\d+" to "([2-9]|[1-9][0-9]*\d)\.\d+\.\d+" 
to check qemu version in virtio_console.cfg file

Signed-off-by: Nana Liu nanliu@redhat.com

id:1695382

**Comment by lolyu** [comment]
Please update patch title.

**Comment by nanliu-r** [comment]
> Please update patch title.

done,thanks.

**Comment by vivianQizhu** [comment]
@nanliu-r Please update commit log, it does not match the fix very well.

**Comment by nanliu-r** [comment]
> @nanliu-r Please update commit log, it does not match the fix very well.

Change commit to "check qemu version which is over 2.12", please check,thanks.

**Comment by lolyu** [comment]
Please check the files to commit.

**Comment by nanliu-r** [comment]
> Please check the files to commit.

ok, thanks.

**Comment by lolyu** [comment]
Please paste test result.

**Comment by nanliu-r** [comment]
> Please paste test result.

qemu version:  
            qemu-kvm-4.0.0-5.module+el8.1.0+3622+5812d9bf.x86_64

Test results:
 (10/20) repeat5.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_console.spread_2.incorrect_options.boot_too_much_ports: PASS (4.66 s)
 (11/20) repeat6.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_console.spread_linear.incorrect_options.boot_too_much_ports: PASS (4.68 s)
 (12/20) repeat6.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_console.spread_2.incorrect_options.boot_too_much_ports: PASS (4.64 s)
 (13/20) repeat7.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_console.spread_linear.incorrect_options.boot_too_much_ports: PASS (4.67 s)
 (14/20) repeat7.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_console.spread_2.incorrect_options.boot_too_much_ports: PASS (4.66 s)
 (15/20) repeat8.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_console.spread_linear.incorrect_options.boot_too_much_ports: PASS (4.61 s)
 (16/20) repeat8.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_console.spread_2.incorrect_options.boot_too_much_ports: PASS (10.01 s)
 (17/20) repeat9.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_console.spread_linear.incorrect_options.boot_too_much_ports: PASS (4.66 s)
 (18/20) repeat9.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_console.spread_2.incorrect_options.boot_too_much_ports: PASS (4.69 s)
 (19/20) repeat10.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_console.spread_linear.incorrect_options.boot_too_much_ports: PASS (5.71 s)
 (20/20) repeat10.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_console.spread_2.incorrect_options.boot_too_much_ports: PASS (7.10 s)

**Pull request merged**
