### PR TITLE
change /tmp to /var/tmp

### PR DESCRIPTION
**Pull request by leidwang**
uefi: change /tmp to /var/tmp

Signed-off-by: Leidong Wang <leidwang@redhat.com>
ID:1937571,1937573

### CODE REVIEW

**Comment by leidwang** [comment]
(1/6) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.uefi_check_log_info.boot_option.bootindex.hard_disk.q35: PASS (43.64 s)
 (2/6) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.uefi_check_log_info.boot_option.bootindex.cd_rom.q35: PASS (43.60 s)
 (3/6) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.uefi_boot_from_device.cdrom.ahci_cd.with_bootindex.q35: PASS (42.41 s)
 (4/6) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.uefi_boot_from_device.cdrom.ahci_cd.with_specific_device.q35: PASS (42.48 s)
 (5/6) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.uefi_boot_from_device.cdrom.scsi_cd.with_bootindex.q35: PASS (42.43 s)
 (6/6) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.uefi_boot_from_device.cdrom.scsi_cd.with_specific_device.q35: PASS (41.50 s)
RESULTS    : PASS 6 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2021-03-10T22.03-935a611/results.html
JOB TIME   : 256.85 s

**Comment by leidwang** [comment]
@vivianQizhu Could you please review this patch?Thanks a lot.

**Comment by vivianQizhu** [comment]
Please modify your commit title like: `uefi_boot_from_device.cfg: change /tmp to /var/tmp`

**Comment by leidwang** [comment]
> Please modify your commit title like: `uefi_boot_from_device.cfg: change /tmp to /var/tmp`

Since this patch changed 2 files(uefi_boot_from_device.cfg, uefi_check_log_info.cfg ), I used "tmp_path_issue" as the commit title.In this case, can we only use one file name as the commit title?

**Comment by vivianQizhu** [comment]
> > Please modify your commit title like: `uefi_boot_from_device.cfg: change /tmp to /var/tmp`
> 
> Since this patch changed 2 files(uefi_boot_from_device.cfg, uefi_check_log_info.cfg ), I used "tmp_path_issue" as the commit title.In this case, can we only use one file name as the commit title?

Right, then I suppose `uefi: change /tmp to /var/tmp` would be better, or `Change /tmp to /var/tmp for uefi test cases`.

**Comment by leidwang** [comment]
> > > Please modify your commit title like: `uefi_boot_from_device.cfg: change /tmp to /var/tmp`
> > 
> > 
> > Since this patch changed 2 files(uefi_boot_from_device.cfg, uefi_check_log_info.cfg ), I used "tmp_path_issue" as the commit title.In this case, can we only use one file name as the commit title?
> 
> Right, then I suppose `uefi: change /tmp to /var/tmp` would be better, or `Change /tmp to /var/tmp for uefi test cases`.

Ok,thanks a lot.

**Review by vivianQizhu — APPROVED** [review]

**Pull request merged**
