### PR TITLE
luks_convert: introduces cases to support convert from luks

### PR DESCRIPTION
**Pull request by lolyu**
1. add three cases:
convert from luks to qcow2
convert from luks to raw
convert from luks to luks

2. introduce new provider module `qemu_img_utils`, which includes
common funtions needed by QEMU image related testcases.

Signed-off-by: lolyu <lolyu@redhat.com>

### CODE REVIEW

**Comment by lolyu** [comment]
@hellohellenmao  @YongxueHong please take a review

**Comment by lolyu** [comment]
```
 (1/3) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.1.x86_64.io-github-autotest-qemu.luks_convert.to_raw: PASS (844.99 s)
 (2/3) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.1.x86_64.io-github-autotest-qemu.luks_convert.to_qcow2: PASS (864.47 s)
 (3/3) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.1.x86_64.io-github-autotest-qemu.luks_convert.to_luks: FAIL: CmdError('/usr/bin/qemu-img convert --object secret,id=image1_encrypt0,data=redhat --object secret,id=convert_encrypt0,data=convert -O luks -o key-secret=convert_encrypt0 \'json:{"driver": "luks", "file": {"driver": "file", "filename": "/home/kvm_autotest... (75.61 s)
```
```
 (1/3) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.luks_convert.to_raw: PASS (1058.50 s)
 (2/3) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.luks_convert.to_qcow2: PASS (1018.01 s)
 (3/3) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.luks_convert.to_luks: FAIL: CmdError('/usr/bin/qemu-img convert --object secret,id=image1_encrypt0,data=redhat --object secret,id=convert_encrypt0,data=convert -O luks -o key-secret=convert_encrypt0 \'json:{"driver": "luks", "file": {"driver": "file", "filename": "/home/kvm_autotest... (126.37 s)
```

**Comment by hellohellenmao** [comment]
Tested with win2019, passed. And the logs look good to me.

(1/3) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.luks_convert.to_raw: PASS (1119.89 s)
 (2/3) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.luks_convert.to_qcow2: PASS (1098.79 s)
 (3/3) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.luks_convert.to_luks: PASS (1670.44 s)

**Comment by hellohellenmao** [comment]
Tested with linux, also passed!

(1/3) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.io-github-autotest-qemu.luks_convert.to_raw: PASS (860.72 s)
 (2/3) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.io-github-autotest-qemu.luks_convert.to_qcow2: PASS (853.11 s)
 (3/3) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.io-github-autotest-qemu.luks_convert.to_luks: PASS (1232.61 s)

**Pull request merged**
