### PR TITLE
add windows support for migration_with_remote_storage

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>
ID: 2125862

### CODE REVIEW

**Comment by XueqiangWei** [comment]
(1/2) Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.migration_with_remote_storage.q35: PASS (233.35 s)
 (2/2) Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.migration_with_remote_storage.with_post_copy.q35: PASS (163.28 s)

**Comment by XueqiangWei** [comment]
@zhencliu @hellohellenmao Please help review it. Many thanks.

**Comment by zhencliu** [comment]
LGTM

Also suggest commit header: migration_with_remote_storage: add windows guest support

**Comment by XueqiangWei** [comment]
Updated, thanks Zhenchao.

**Comment by hellohellenmao** [comment]
Tried with raw, qcow2 and luks, all passed.

Ack.

**Pull request merged**
