### PR TITLE
tp-qemu: shutdown.py: Call the setup_runlevel() in utils_test.py directly.

### PR DESCRIPTION
**Pull request by CongSmile**
Signed-off-by: Cong Li <coli@redhat.com>

Based on: avocado-framework/avocado-vt#122

### CODE REVIEW

**Comment by xutian** [comment]
LGTM, merged. thanks @CongSmile

**Comment by xutian** [comment]
Hi guy.

you forget to import utils_test module before use it.

**Comment by CongSmile** [comment]
Hi @xutian 

Have updated the code, could you help review it again?

Btw, the CI check failed due to "E: Unable to locate package autotest".

Thanks.

**Comment by xutian** [comment]
Better to remove useless import utils_misc

**Comment by CongSmile** [comment]
@xutian  

Done. Could you please review it again?

Thanks.

**Comment by xutian** [comment]
LGTM.

Better to test your commit before modify and update your PR.

Thanks,
Xu

**Comment by xutian** [comment]
Merged, thanks @CongSmile

**Pull request merged**
