### PR TITLE
qemu/tests/cfg: Some nics model not support for power

### PR DESCRIPTION
**Pull request by spcui**
Signed-off-by: Shuping Cui <scui@redhat.com>

ID: 1327941

### CODE REVIEW

**Comment by Zhengtong** [comment]
Acked-by Zhengtong <zhengtli@redhat.com>

**Comment by xutian** [comment]
if this kind of nics not support by power platform, why not add no ppc64 and ppc64le in guest-hw.cfg。

Thanks,
Xu

**Comment by spcui** [comment]
@xutian Already have "no ppc64 ppc64le" for rtl8139 and e1000 in guest-hw.cfg, but for this case, variants of nic_8139 and nic_e1000 not same as rtl8139 and e1000 in guest-hw.cfg, so add it.

**Comment by MiriamDeng** [comment]
Acked-by MinDeng mdeng@redhat.com

**Pull request merged**
