### PR TITLE
vioinput_enable: Add new cases when vioinput device enabled

### PR DESCRIPTION
**Pull request by peixiu**
Add new cases that do reboot/shutdown/system_rest/migrate when
vioinput device enabled.

id: 1775504, 1775503, 1775505
Signed-off-by: Peixiu Hou <phou@redhat.com>

### CODE REVIEW

**Comment by peixiu** [comment]
(1/4) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_shutdown: PASS (86.56 s)
 (2/4) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_reboot:PASS (83.41 s)
 (3/4) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_system_reset: PASS (100.62 s)
 (4/4) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_live_migration: PASS (132.01 s)

**Comment by peixiu** [comment]
@luckyh Hi xuhan, could you help to review this patch? thanks a lot~

**Comment by peixiu** [comment]
I tested on win7-32, win8.1-32, win2008-r2, win8-64, win2019, win10-32 guests, all passed.

here pasted part of results:
 (1/4) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_shutdown.q35: PASS (81.48 s)
 (2/4) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_reboot.q35: PASS (67.06 s)
 (3/4) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_system_reset.q35: PASS (84.37 s)
 (4/4) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_live_migration.q35: PASS (86.42 s)

 (1/4) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.Win2008.x86_64.r2.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_shutdown.q35: PASS (101.53 s)
 (2/4) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.Win2008.x86_64.r2.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_reboot.q35: PASS (78.82 s)
 (3/4) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.Win2008.x86_64.r2.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_system_reset.q35: PASS (90.76 s)
 (4/4) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.Win2008.x86_64.r2.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_live_migration.q35: PASS (103.48 s)

 (1/4) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.Win8.x86_64.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_shutdown.q35: PASS (108.35 s)
 (2/4) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.Win8.x86_64.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_reboot.q35:PASS (74.87 s)
 (3/4) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.Win8.x86_64.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_system_reset.q35: PASS (141.23 s)
 (4/4) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.Win8.x86_64.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_live_migration.q35: PASS (151.06 s)

 (07/17) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_shutdown.q35: PASS (194.81 s)
 (08/17) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_reboot.q35: PASS (190.16 s)
 (09/17) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_system_reset.q35: PASS (172.73 s)
 (10/17) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.vioinput_enable.device_keyboard.with_live_migration.q35: PASS (237.38 s)

**Comment by kimi1978wy** [comment]
Tested  on win7-64 , it all passed after modified timeout (tested 50 times).
And tested virtio_storage_in_use.with_block.system_disk, this added function does not influence other  function.

Acked by : Yu Wang <wyu@redhat.com>

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
