### PR TITLE
blockdev_inc_backup_enable_bitmap: Add test for enabling disabled bitmaps

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1908299

### CODE REVIEW

**Comment by zhencliu** [comment]
local fs: 
(1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_enable_bitmap: PASS (92.63 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-17T04.36-2381aea/results.html
JOB TIME   : 95.36 s

iscsi-direct + virio-blk:
(1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_enable_bitmap: PASS (92.06 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-17T04.45-e09b8d0/results.html
JOB TIME   : 94.79 s

ceph:
 (1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_enable_bitmap: PASS (303.37 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-17T06.03-b71ea0a/results.html
JOB TIME   : 306.04 s

nbd:
(1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_enable_bitmap: PASS (224.03 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-17T05.52-5137d06/results.html
JOB TIME   : 226.83 s

**Comment by zhencliu** [comment]
hi @YongxueHong and @ngu-niny , can you please help to review this patch? Thanks.
it deps on #2555

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by ngu-niny** [comment]
Test PASS:

11:58:35 INFO | PASS 10-Host_RHEL.m8.u4.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_enable_bitmap
12:18:58 INFO | PASS 18-Host_RHEL.m8.u4.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_enable_bitmap
12:58:13 INFO | PASS 34-Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_enable_bitmap

Acked-by: Nini Gu ngu@redhat.com

**Pull request merged**
