### PR TITLE
throttle_block_set_io_throttle:fix change iothread configuration

### PR DESCRIPTION
**Pull request by qingwangrh**
Change configuration to comply with the new iothread scheme.

ID:2340

### CODE REVIEW

**Comment by qingwangrh** [comment]
Pass test with
python ConfigTest.py --testcase=throttle_block_set_io_throttle --iothread_scheme=full:2 --nr_iothreads=2 --platform=x86_64 --guestname=RHEL.9.5.0 --driveformat=virtio_blk --imageformat=qcow2 --machines=q35  --customsparams="vm_mem_limit = 12G\nimage_aio=io_uring" --firmware=ovmf --netdst=virbr0 --clone=no

**Comment by qingwangrh** [comment]
@XueqiangWei @zhenyzha Please help to review Thanks.

**Comment by zhenyzha** [comment]
throttle_block_set_io_throttle.arm64-pci: PASS (95.81 s)

Pass on the aarch64 platform
LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Review by zhenyzha — APPROVED** [review]

**Comment by XueqiangWei** [comment]
(1/1) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.throttle_block_set_io_throttle.q35: PASS (166.06 s)

**Review by XueqiangWei — APPROVED** [review]
LGTM,
Acked-by: xuwei@redhat.com

**Pull request merged**
