### PR TITLE
block_with_share_rw: Support virtio_blk

### PR DESCRIPTION
**Pull request by YongxueHong**
Update the config file to support virtio_blk.

ID: 1745981
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by YongxueHong** [comment]
@XueqiangWei  @lolyu  pls help me to review, thanks.

**Comment by YongxueHong** [comment]
@qingwangrh  help me to review, thanks.

**Comment by lolyu** [comment]
test result, please.

**Comment by qingwangrh** [comment]
Passed test with command:
python3 ConfigTest.py --testcase=block_with_share_rw --clone=no --guestname=RHEL.8.1.0 --driveformat=virtio_scsi,virtio_blk

LGTM

**Comment by YongxueHong** [comment]
Thanks all, let's merge it.

**Pull request merged**
