### PR TITLE
fwcfg: exclude some Windows from the test matrix

### PR DESCRIPTION
**Pull request by leidwang**
Signed-off-by: Leidong Wang <leidwang@redhat.com>

ID:2090532

### CODE REVIEW

**Comment by leidwang** [comment]
Hi @xiagao Could you help to review this patch?Thanks!

**Comment by xiagao** [comment]
Could you add some description in commit,such as
 currently, fwcfg only support x86_64

**Comment by leidwang** [comment]
> Could you add some description in commit,such as currently, fwcfg only support x86_64
Okay,updated.

**Review by xiagao — APPROVED** [review]
LGTM. ack.

**Comment by leidwang** [comment]
Hi @vivianQizhu Could you help to review this patch?Thanks!

**Review by vivianQizhu — APPROVED** [review]

**Pull request merged**
