### PR TITLE
add windows support for remote_image_convert

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>
ID: 2125550

### CODE REVIEW

**Comment by XueqiangWei** [comment]
01-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert.q35 Finshed 2022-09-08 04:08:20 2022-09-08 04:52:15 PASS 2635.506573
02-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert.cache_mode.none.q35 Finshed 2022-09-08 04:52:18 2022-09-08 05:40:41 PASS 2902.89145
03-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert.cache_mode.writeback.q35 Finshed 2022-09-08 05:40:42 2022-09-08 06:24:48 PASS 2645.599675
04-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert.cache_mode.unsafe.q35 Finshed 2022-09-08 06:24:50 2022-09-08 07:08:43 PASS 2633.079044
05-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert.cache_mode.directsync.q35 Finshed 2022-09-08 07:08:45 2022-09-08 08:01:54 PASS 3188.998185
06-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert.cache_mode.writethrough.q35 Finshed 2022-09-08 08:01:55 2022-09-08 08:50:26 PASS 2911.438523
07-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_qcow2_convert.q35 Finshed 2022-09-08 08:50:28 2022-09-08 09:33:01 PASS 2553.322885
08-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_luks_convert.q35 Finshed 2022-09-08 09:33:03 2022-09-08 10:15:50 PASS 2567.027396
09-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_qcow2_remote.fmt_raw_convert.q35 Finshed 2022-09-08 10:15:52 2022-09-08 11:18:26 PASS 3754.066347
10-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_qcow2_remote.fmt_qcow2_convert.q35 Finshed 2022-09-08 11:18:28 2022-09-08 12:16:23 PASS 3474.522779
11-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_qcow2_remote.fmt_qcow2_convert.with_compression.q35 Finshed 2022-09-08 12:16:25 2022-09-09 00:58:37 PASS 45732.326205
12-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_qcow2_remote.fmt_luks_convert.q35 Finshed 2022-09-09 00:58:39 2022-09-09 02:01:05 PASS 3745.940604
13-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_luks_remote.fmt_raw_convert.q35 Finshed 2022-09-09 02:01:08 2022-09-09 03:01:09 PASS 3600.716876
14-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_luks_remote.fmt_qcow2_convert.q35 Finshed 2022-09-09 03:01:12 2022-09-09 04:00:41 PASS 3568.752459
15-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_luks_remote.fmt_luks_convert.q35 Finshed 2022-09-09 04:00:44 2022-09-09 05:00:40 PASS 3595.405652
16-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert.q35 Finshed 2022-09-09 05:00:43 2022-09-09 05:35:15 PASS 2071.735245
17-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert.cache_mode.none.q35 Finshed 2022-09-09 05:35:16 2022-09-09 06:10:50 PASS 2134.229989
18-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert.cache_mode.writeback.q35 Finshed 2022-09-09 06:10:52 2022-09-09 06:45:39 PASS 2087.084487
19-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert.cache_mode.unsafe.q35 Finshed 2022-09-09 06:45:40 2022-09-09 07:20:31 PASS 2090.440854
20-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert.cache_mode.directsync.q35 Finshed 2022-09-09 07:20:32 2022-09-09 07:55:59 PASS 2126.860947
21-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert.cache_mode.writethrough.q35 Finshed 2022-09-09 07:56:00 2022-09-09 08:30:54 PASS 2093.906929
22-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_qcow2_convert.q35 Finshed 2022-09-09 08:30:56 2022-09-09 09:22:25 PASS 3089.165884
23-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_qcow2_convert.with_compression.q35 Finshed 2022-09-09 09:22:26 2022-09-09 21:36:13 PASS 44026.590564
24-Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_luks_convert.q35 Finshed 2022-09-09 21:36:14 2022-09-09 22:28:15 PASS 3120.533282
Summary: 
Finshed=24, PASS=24

**Comment by XueqiangWei** [comment]
@zhencliu @hellohellenmao Please help review it. Many thanks.

**Comment by zhencliu** [comment]
LGTM

**Comment by XueqiangWei** [comment]
Update commit header: remote_image_convert: add windows guest support
Thanks Zhenchao.

**Comment by hellohellenmao** [comment]
Tried with raw, qcow2 and luks, all passed.

Ack.

**Pull request merged**
