### PR TITLE
IPU: dynamically set rhel version if test is with rhsm

### PR DESCRIPTION
**Pull request by MiriamDeng**
ID: 2186172 
Signed-off-by: Min Deng <mdeng@redhat.com>

### CODE REVIEW

**Comment by MiriamDeng** [comment]
(1/2) Host_RHEL.m8.u8.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: STARTED
 (1/2) Host_RHEL.m8.u8.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (2118.89 s)
 (2/2) Host_RHEL.m8.u8.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.in_place_upgrade.with_rhsm_rhel8_to_rhel9.compose_install: STARTED
 (2/2) Host_RHEL.m8.u8.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.in_place_upgrade.with_rhsm_rhel8_to_rhel9.compose_install: PASS (5021.85 s)

**Comment by MiriamDeng** [comment]
@fbq815 @PaulYuuu Please help to review the patch, thank you !

**Review by PaulYuuu — APPROVED** [review]

**Comment by fbq815** [comment]
Test result on s390x:
with_rhsm from7 to 8:
JOB ID : 8a59c824eee73384fccc7fa830a477765f470e60
JOB LOG : /root/avocado/job-results/job-2023-07-04T03.51-8a59c82/job.log
(1/1) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.in_place_upgrade_legacy.with_rhsm_rhel7_to_rhel8.compose_install.s390-virtio: STARTED
(1/1) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.in_place_upgrade_legacy.with_rhsm_rhel7_to_rhel8.compose_install.s390-virtio: PASS (2086.22 s)
RESULTS : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML : /root/avocado/job-results/job-2023-07-04T03.51-8a59c82/results.html
JOB TIME : 2087.46 s

withouth_rhsm from 7 to 8:
INFO | Start to run test
JOB ID : a96d6f32edab71bab1665215840c5824140846af
JOB LOG : /root/avocado/job-results/job-2023-07-05T04.10-a96d6f3/job.log
(1/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.s390-virtio: STARTED
(1/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.s390-virtio: PASS (466.86 s)
(2/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.in_place_upgrade_legacy.without_rhsm_rhel7_to_rhel8.compose_install.s390-virtio: STARTED
(2/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.in_place_upgrade_legacy.without_rhsm_rhel7_to_rhel8.compose_install.s390-virtio: PASS (982.98 s)
RESULTS : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML : /root/avocado/job-results/job-2023-07-05T04.10-a96d6f3/results.html
JOB TIME : 1451.44 s

without_rhsm from 8 to 9:
JOB ID : 64805ea636ed64638e33390fd4dfb943641610c0
JOB LOG : /root/avocado/job-results/job-2023-07-05T22.30-64805ea/job.log
(1/1) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.s390x.io-github-autotest-qemu.in_place_upgrade.without_rhsm_rhel8_to_rhel9.compose_install.s390-virtio: STARTED
(1/1) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.s390x.io-github-autotest-qemu.in_place_upgrade.without_rhsm_rhel8_to_rhel9.compose_install.s390-virtio: PASS (595.22 s)
RESULTS : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML : /root/avocado/job-results/job-2023-07-05T22.30-64805ea/results.html
JOB TIME : 596.41 s

LGTM

**Review by fbq815 — APPROVED** [review]

**Comment by MiriamDeng** [comment]
@PaulYuuu can we help to check if we can merge this pr ? Thank you !

**Pull request merged**
