### PR TITLE
remote_image_snapshot: support ssh storage backend

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1855211

### CODE REVIEW

**Comment by zhencliu** [comment]
hi @YongxueHong  @zixi-chen, can you please help to review it, thanks

**Comment by zhencliu** [comment]
deps on vt: https://github.com/avocado-framework/avocado-vt/pull/2644

**Comment by zixi-chen** [comment]
(1/1) Host_RHEL.m8.u3.product_av.ssh.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_snapshot.to_local: PASS (148.34 s)
LGTM
ACK

**Comment by zhencliu** [comment]
hi @YongxueHong , can you please help to merge it, as libssh vt patch has just merged, thanks.

**Pull request merged**
