### PR TITLE
virtio_fs: new case of test posix-acl with xfstest

### PR DESCRIPTION
**Pull request by xiagao**
ID:  2130453

### CODE REVIEW

**Comment by xiagao** [comment]
(1/1) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_xfstest.posix_acl.with_cache.auto.q35: STARTED
 (1/1) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_xfstest.posix_acl.with_cache.auto.q35: PASS (175.34 s)

**Comment by xiagao** [comment]
@zhenyzha @YongxueHong Could you help review this patch? Thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by zhenyzha** [comment]
What about the `with_writeback` option? Do both modes need to test it?
https://github.com/autotest/tp-qemu/blob/master/qemu/tests/cfg/virtio_fs_share_data.cfg#L125

When I run `virtio_fs_share_data..with_xfstest`, now I can scan to 4 cases.

**Comment by xiagao** [comment]
> What about the `with_writeback` option? Do both modes need to test it? https://github.com/autotest/tp-qemu/blob/master/qemu/tests/cfg/virtio_fs_share_data.cfg#L125
> 
> When I run `virtio_fs_share_data..with_xfstest`, now I can scan to 4 cases.

I suppose it's not. Let me add a filter.

**Comment by xiagao** [comment]
@zhenyzha  I update, pls have a check.

**Comment by zhenyzha** [comment]
LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

```
 (1/3) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_xfstest.with_cache.auto.arm64-pci: STARTED
 (1/3) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_xfstest.with_cache.auto.arm64-pci: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (2/3) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_xfstest.with_cache.auto.with_writeback.arm64-pci: STARTED
 (2/3) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_xfstest.with_cache.auto.with_writeback.arm64-pci: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (3/3) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_xfstest.posix_acl.with_cache.auto.arm64-pci: STARTED
 (3/3) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_xfstest.posix_acl.with_cache.auto.arm64-pci: CANCEL: Test cancelled due to --dry-run (0.00 s)
```

**Review by zhenyzha — APPROVED** [review]

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
