### PR TITLE
netperf: update netperf to make it work with gcc 10 and above

### PR DESCRIPTION
**Pull request by yanan-fu**
patch https://github.com/HewlettPackard/netperf/pull/46
to the existing netperf

id: 1917877

Signed-off-by: Yanan Fu <yfu@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
Test result:
1. For cases that use `netperf-2.6.0.tar.bz2`
```
22:13:05 INFO | Copy file from /var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/deps/netperf/netperf-2.6.0.tar.bz2 to 10.73.224.76:/var/tmp/, elapsed time: 0.9154536724090576
22:13:05 DEBUG| Compiling netserver from source
22:13:05 DEBUG| Sending command: arch
22:13:05 DEBUG| Sending command: rm -rf /var/tmp/netperf-2.6.0
22:13:05 DEBUG| Sending command: echo $?
22:13:05 DEBUG| Sending command: cd /var/tmp/  && tar jxf netperf-2.6.0.tar.bz2 && cd /var/tmp/netperf-2.6.0  && ./autogen.sh > /dev/null 2>&1 && ./configure --build=x86_64  > /dev/null 2>&1 && make > /dev/null 2>&1
22:13:14 DEBUG| Sending command: echo $?
22:13:14 DEBUG| Using local netperf: /var/tmp/netperf-2.6.0/src/netperf and /var/tmp/netperf-2.6.0/src/netserver
22:13:14 DEBUG| Create remote session
22:13:16 INFO | Start netserver ...
22:13:16 DEBUG| Sending command (safe): ps -C netserver
22:13:16 INFO | Start netserver with cmd: '/var/tmp/netperf-2.6.0/src/netserver > /dev/null'
22:13:16 DEBUG| Sending command (safe): /var/tmp/netperf-2.6.0/src/netserver > /dev/null
22:13:16 DEBUG| Sending command (safe): ps -C netserver
22:13:16 INFO | Netserver start successfully
...
```
2. For cases that use `netperf-2.7.1.tar.bz2`
```
22:16:10 INFO | Copy file from /var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/deps/netperf/netperf-2.7.1.tar.bz2 to 10.73.224.76:/var/tmp/, elapsed time: 0.8781707286834717
22:16:10 DEBUG| Compiling netserver from source
22:16:10 DEBUG| Sending command: arch
22:16:10 DEBUG| Sending command: rm -rf /var/tmp/netperf-2.7.1
22:16:10 DEBUG| Sending command: echo $?
22:16:10 DEBUG| Sending command: cd /var/tmp/  && tar jxf netperf-2.7.1.tar.bz2 && cd /var/tmp/netperf-2.7.1  && ./autogen.sh > /dev/null 2>&1 && ./configure --build=x86_64  > /dev/null 2>&1 && make > /dev/null 2>&1
22:16:19 DEBUG| Sending command: echo $?
22:16:20 DEBUG| Using local netperf: /var/tmp/netperf-2.7.1/src/netperf and /var/tmp/netperf-2.7.1/src/netserver
22:16:20 DEBUG| Create remote session
22:16:21 INFO | Start netserver ...
22:16:21 DEBUG| Sending command (safe): ps -C netserver
22:16:21 DEBUG| Sending command (safe): ps -C netserver
22:16:21 INFO | Netserver start successfully
...
```

**Comment by yanan-fu** [comment]
@yanglei-rh @PaulYuuu  Could you help review ? Thanks!

**Comment by PaulYuuu** [comment]
@yfu `generic/deps/performance/` has netperf tar archives as well.
```
# ls generic/deps/performance/
netperf-2.6.0.tar.bz2  netperf-2.7.1.tar.bz2
```

But in order to maintain one set of netperf archives, do you also plan to make soft links? If no, let @yanglei-rh find out which scripts use `performance/netperf*` and update to `deps/netperf/netperf*` in the next patch.

**Comment by yanan-fu** [comment]
@PaulYuuu   It is useless from my checking, so i leave it.
Several cases use `performance`, but not `netperf` under `performance`.   It is MoonGen.zip, fio and some test_patch for performance test.

**Comment by PaulYuuu** [comment]
@yanan-fu , thanks for the explanation. If they are indeed useless, let's delete them to leave disagreement. Waiting for the feedback of feature owners.

**Comment by yanan-fu** [comment]
> @yanan-fu , thanks for the explanation. If they are indeed useless, let's delete them to leave disagreement. Waiting for the feedback of feature owners.

Delete useless pkg is another topic, let's focus on if netperf under `generic/deps/performance/`  needed be updated or not in this patch.
@quanwenli @yanglei-rh  Could you please check it ? Thanks!

**Comment by yanglei-rh** [comment]
> > @yanan-fu , thanks for the explanation. If they are indeed useless, let's delete them to leave disagreement. Waiting for the feedback of feature owners.
> 
> Delete useless pkg is another topic, let's focus on if netperf under `generic/deps/performance/` needed be updated or not in this patch.
> @quanwenli @yanglei-rh Could you please check it ? Thanks!

Hi @yanan-fu I double-checked that the netperf package I used comes from deps/netperf/. I will add the test results later.

**Comment by yanglei-rh** [comment]
LGTM

Test pass
netperf-2.6.0:
 (1/2) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.nic_opt.opt_test_netperf.indirect_desc.opt_on.q35: PASS (644.11 s)
 (2/2) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.nic_opt.opt_test_netperf.indirect_desc.opt_off.q35: PASS (623.18 s)
netperf-2.7.1:
(1/2) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.netperf_stress_test.TCP_STREAM.guest2guest.q35: PASS (466.26 s)
 (2/2) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.netperf_stress_test.TCP_STREAM.host2guest.q35: PASS (565.67 s)

**Comment by PaulYuuu** [comment]
@yanan-fu In order to continue our testing, let's delete the performance folder, others are well.

**Comment by yanan-fu** [comment]
> @yanan-fu In order to continue our testing, let's delete the performance folder, others are well.

Could you explain the reason ?  
performance folder is not a block for our test, to clean up the pkgs of netperf is not my purpose of this patch, i prefer feature owner to do it with a separate patch later, thanks!

**Comment by PaulYuuu** [comment]
It's also okay for me. The ultimate goal is that we only maintain a set of netperf tools.
Ack.

**Comment by yanan-fu** [comment]
@quanwenli  Looking forward for your result, thanks a lot!

**Comment by quanwenli** [comment]
LGTM

Test pass

JOB ID     : 3b3182e5ee01d2bd9a02559156f1385143fc67ae
JOB LOG    : /root/avocado/job-results/job-2021-02-08T03.56-3b3182e/job.log
 (1/1) 82599.bridge_test.1q.acceptance.repeat1.Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.netperf.with_jumbo.host_guest.q35: PASS (602.59 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2021-02-08T03.56-3b3182e/results.html
JOB TIME   : 603.10 s

**Comment by yanan-fu** [comment]
Thanks all~

**Pull request merged**
