### PR TITLE
live_snapshot: change the path of snapshot and remove it at the end 

### PR DESCRIPTION
**Pull request by yanan-fu**
For case live_snapshot.with_file_transfer:
    1. change the path of live_snapshot_img to images/*
    2. remove live_snapshot_img after test finished
For case live_snapshot.base:
    The correct parameter name should be 'snapshot_file' instead of 'snapshot_name'.

id: 1679011
Signed-off-by: Yanan Fu <yfu@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
(1/2) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.x86_64.io-github-autotest-qemu.live_snapshot.with_file_transfer: PASS (93.99 s)
 (2/2) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.x86_64.io-github-autotest-qemu.live_snapshot.base: PASS (84.52 s)

**Comment by yanan-fu** [comment]
@huangyum could you help review it, thanks !

**Comment by huangyum** [comment]
Just one question,  in case live_snapshot.simple_test, the name of snapshot image is "live_snapshot_img.qcow2" while it's "live_snapshot_img" in case live_snapshot.base.  I guess it's better to make it same.

**Comment by yanan-fu** [comment]
@huangyum yes, that it.  In fact, for all snapshot related cases, some add format and some don't.  
Not only `live_snapshot.base` miss the format.  I don't want to change all of them to use `file.format` here.
If need, can change in a new patch to cover all. Thanks!

**Comment by huangyum** [comment]
@yanan-fu If so, I'm fine with it. 
Ack.

**Pull request merged**
