### PR TITLE
cgroup.freezer:get correct vcpus for vm

### PR DESCRIPTION
**Pull request by xiangchunfu**
get correct vcpus for vm.

id: 1875669

Signed-off-by: Xiangchun Fu <xfu@redhat.com>

### CODE REVIEW

**Comment by xiangchunfu** [comment]
(01/10) repeat1.Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.cgroup.freezer: PASS (210.42 s)
 (02/10) repeat2.Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.cgroup.freezer: PASS (206.65 s)
 (03/10) repeat3.Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.cgroup.freezer: PASS (206.10 s)
 (04/10) repeat4.Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.cgroup.freezer: PASS (206.84 s)
 (05/10) repeat5.Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.cgroup.freezer: PASS (206.20 s)
 (06/10) repeat6.Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.cgroup.freezer: PASS (203.03 s)
 (07/10) repeat7.Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.cgroup.freezer: PASS (207.78 s)
 (08/10) repeat8.Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.cgroup.freezer: PASS (204.91 s)
 (09/10) repeat9.Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.cgroup.freezer: PASS (206.31 s)
 (10/10) repeat10.Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.cgroup.freezer: PASS (206.86 s)

**Comment by xiangchunfu** [comment]
@yanan-fu when you have time, please help review this patch. Thanks.

**Comment by yanan-fu** [comment]
@xiangchunfu This case get `vm_vcpu` is 0, because the framework change before, it drop `smp` and use `vcpu_maxcpus` instead.

suggest:
`vm_cpus = vm.cpuinfo.smp`

**Comment by xiangchunfu** [comment]
@yanan-fu  Thanks for Yanan's explanation. It makes sense.  
 (1/3) repeat1.Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.cgroup.freezer: PASS (221.38 s)
 (2/3) repeat2.Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.cgroup.freezer: PASS (203.38 s)
 (3/3) repeat3.Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.cgroup.freezer: PASS (202.00 s)

**Comment by xiangchunfu** [comment]
@yanan-fu  updated. Thanks.

**Comment by yanan-fu** [comment]
Acked-by: Yanan Fu <yfu@redhat.com>

**Pull request merged**
