### PR TITLE
block_discard_write_same_resource:fix resource clean issue

### PR DESCRIPTION
**Pull request by qingwangrh**
Adding loop device detach operation

ID:2183001
Signed-off-by: qingwangrh <qinwang@redhat.com>

### CODE REVIEW

**Comment by XueqiangWei** [comment]
Tested with ovmf and virtio_blk, virtio_scsi, the results were passed.

(1/4) repeat1.Host_RHEL.m9.u3.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.block_discard_write_same.local_file.q35: STARTED
 (1/4) repeat1.Host_RHEL.m9.u3.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.block_discard_write_same.local_file.q35: PASS (93.52 s)
 (2/4) repeat1.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.block_discard_write_same.local_file.q35: STARTED
 (2/4) repeat1.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.block_discard_write_same.local_file.q35: PASS (90.83 s)
 (3/4) repeat2.Host_RHEL.m9.u3.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.block_discard_write_same.local_file.q35: STARTED
 (3/4) repeat2.Host_RHEL.m9.u3.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.block_discard_write_same.local_file.q35: PASS (65.70 s)
 (4/4) repeat2.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.block_discard_write_same.local_file.q35: STARTED
 (4/4) repeat2.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.block_discard_write_same.local_file.q35: PASS (65.78 s)

**Comment by XueqiangWei** [comment]
LGTM,
Acked-by: xuwei@redhat.com

**Review by XueqiangWei — APPROVED** [review]

**Comment by YongxueHong** [comment]
Hi @zhenyzha 
Would like to help review it?
Thanks.

**Comment by zhenyzha** [comment]
Env cleanup as expected

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

git am 3692.patch
Applying: block_discard_write_same_resource:fix resource clean issue

```
 (1/1) Host_RHEL.m9.u.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.aarch64.io-github-autotest-qemu.block_discard_write_same.local_file.arm64-pci: STARTED
 (1/1) Host_RHEL.m9.u.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.aarch64.io-github-autotest-qemu.block_discard_write_same.local_file.arm64-pci: PASS (134.31 s)

losetup -l
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                                                                DIO LOG-SEC
/dev/loop0         0      0         1  1 /home/kvm_autotest_root/iso/linux/***.iso   0     512
```

**Review by zhenyzha — APPROVED** [review]

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
