### PR TITLE
seabios: add restriction for seabios-related cases

### PR DESCRIPTION
**Pull request by ybduan**
ID: 2041680

Signed-off-by: ybduan <yduan@redhat.com>

### CODE REVIEW

**Comment by ybduan** [comment]
Please help review this PR, thanks! @XueqiangWei

**Comment by XueqiangWei** [comment]
@ybduan Could you pleas add your test results. Thanks.

**Comment by ybduan** [comment]
With this PR, test cases are filtered out with argument '--firmware=ovmf'.

**Comment by XueqiangWei** [comment]
Tested with firmware=ovmf, not found any case.

Tested one case, the result is passed.
(1/1) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.seabios.bin_file.q35: PASS (529.60 s)

LGTM,
Acked-by: xuwei@redhat.com

**Comment by XueqiangWei** [comment]
@yanan-fu Please help review it. Many thanks.

**Comment by yanan-fu** [comment]
Ack

**Review by yanan-fu — APPROVED** [review]

**Pull request merged**
