### PR TITLE
for modual "aecpect", make it work 

### PR DESCRIPTION
**Pull request by XueqiangWei**
under both autotest-framework and avocado-framework

Signed-off-by: Xueqiang Wei <xuwei@redhat.com>

### CODE REVIEW

**Comment by XueqiangWei** [comment]
ID 1321727

**Comment by xutian** [comment]
Please update your commit summary to make it more readable.

**Comment by CongLi** [comment]
Agree.

And please help fix those typo.

**Comment by XueqiangWei** [comment]
close this pullreq and will resend a new one.

**Pull request closed without merging**
