### PR TITLE
qemu.tests.rh_kernel_update: rename 'grub' related params

### PR DESCRIPTION
**Pull request by luckyh**
Because not all RHEL distro use grub as its bootloader, those grub
related params no longer made sense, so change their name to boot_xxx.

ID: 1246408

### CODE REVIEW

**Comment by CongSmile** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by spcui** [comment]
LGTM
Acked-by: scui@redhat.com

**Comment by MiriamDeng** [comment]
Acked-by:mdeng@redhat.com

**Comment by xutian** [comment]
Merged, thanks @luckyh

**Pull request merged**
