### PR TITLE
added commit qcow2 snapshot to raw backing image cases

### PR DESCRIPTION
**Pull request by hereischen**
1. rebase with different compat modes
2. rebase with various cache modes

id: 1656252
Signed-off-by: Haotong Chen <hachen@redhat.com>

### CODE REVIEW

**Comment by pingl2016** [comment]
Failed the tests with Win2019 due to the command 'sync'

**Comment by pingl2016** [comment]
Original sync tool is gotten from https://docs.microsoft.com/en-us/sysinternals/downloads/sync

**Comment by hereischen** [comment]
I went through the debug and session log, it seems due to the short (60s) timeout.
When I increased it to 240s, it passed. I run it again to see how it goes.

**Comment by hereischen** [comment]
It could be a Windows 2019 driver performance issue.
On same host, virtio-scsi took 2mins to run sync:
```
07:07:21 DEBUG| Sending command: D:\Sync\sync64.exe /accepteula
...
07:09:25 DEBUG| Sending command: echo %errorlevel%
```
whereas, ide took 30s:
```
22:27:56 DEBUG| Sending command: E:\Sync\sync64.exe /accepteula
...
22:28:27 DEBUG| Sending command: echo %errorlevel%
```

**Pull request merged**
