### PR TITLE
dump_guest_core:update gdb command based on gdb usage

### PR DESCRIPTION
**Pull request by leidwang**
Signed-off-by: Leidong Wang <leidwang@redhat.com>

ID:1992436

### CODE REVIEW

**Comment by leidwang** [comment]
JOB LOG    : /root/avocado/job-results/job-2022-04-23T23.32-18a524d/job.log
 (1/2) Host_RHEL.m.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL..0.0.x86_64.io-github-autotest-qemu.dump_guest_core.on.q35: STARTED
\ (1/2) Host_RHEL.m.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL..0.0.x86_64.io-github-autotest-qemu.dump_guest_core.on.q35: PASS (202.15 s)
 (2/2) Host_RHEL.m.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL..0.0.x86_64.io-github-autotest-qemu.dump_guest_core.off.q35: STARTED
- (2/2) Host_RHEL.m.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL..0.0.x86_64.io-github-autotest-qemu.dump_guest_core.off.q35: PASS (142.18 s)

**Comment by leidwang** [comment]
@Kemama Could you help review this patch?Thanks!

**Comment by Kemama** [comment]
Hi,

The code changing is reasonable. 

In the gdb 10.2 release, the early version syntax is no longer supported. With the new version, we input the command "gdb --core" instead. 

The way to remove the limits for core dump sizes is changed via editing /etc/security/limits.conf now. This will permanently reserve the core dump size setting, even reboot the vm. 

Finally, at line 104, the patch add a core dump examiner. The time limit is 60s, which will give enough time to generate the core dump.

Acked: Ke MA <mama@redhat.com>

Reference 
1. https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob_plain;f=gdb/NEWS;hb=gdb-10.2-release 
2. https://www.cse.unsw.edu.au/~learn/debugging/modules/gdb_coredumps/ 
3. http://gnu.ist.utl.pt/software/gdb/documentation/ 
4. https://linux.die.net/man/1/gdb 
5. Bug [1931344](https://bugzilla.redhat.com/show_bug.cgi?id=1931344)

**Comment by leidwang** [comment]
> Hi,
> 
> The code changing is reasonable.
> 
> In the gdb 10.2 release, the early version syntax is no longer supported. With the new version, we input the command "gdb --core" instead.
> 
> The way to remove the limits for core dump sizes is changed via editing /etc/security/limits.conf now. This will permanently reserve the core dump size setting, even reboot the vm.
> 
> Finally, at line 104, the patch add a core dump examiner. The time limit is 60s, which will give enough time to generate the core dump.
> 
> Acked: Ke MA [mama@redhat.com](mailto:mama@redhat.com)
> 
> Reference
> 
> 1. https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob_plain;f=gdb/NEWS;hb=gdb-10.2-release
> 2. https://www.cse.unsw.edu.au/~learn/debugging/modules/gdb_coredumps/
> 3. http://gnu.ist.utl.pt/software/gdb/documentation/
> 4. https://linux.die.net/man/1/gdb
> 5. Bug [1931344](https://bugzilla.redhat.com/show_bug.cgi?id=1931344)

Thanks @Kemama.
@vivianQizhu Could you help review this patch?Thanks!

**Comment by vivianQizhu** [comment]
@Kemama Would you please help provide the test result? Thanks.

**Comment by leidwang** [comment]
Hi @Kemama Do you have any updates about this patch?

**Comment by Kemama** [comment]
@leidwang Hi, this patch is still in examination. Same as Bug 1992436, the core dump file does not generate correctly. I have tried on different RHEL versions. Next step would test on a separate machine.

**Comment by Kemama** [comment]
@leidwang @vivianQizhu Hi, sorry for the late reply. 

Here is the test results link:
http://fileshare.englab.nay.redhat.com/pub/logs/mama/patch3300/results.html

**Comment by Kemama** [comment]
Hi @leidwang . I'm not sure why my last comment has been deleted. 

The tests passed, and the results are here [1]:
(1/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.dump_guest_core.on.q35: STARTED
(1/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.dump_guest_core.on.q35: PASS (288.55 s)
 (2/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.dump_guest_core.off.q35: STARTED
(2/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.dump_guest_core.off.q35: PASS (188.73 s)

Reference:
1. /root/avocado/job-results/job-2022-05-07T05.05-e5c1162/results.html

**Comment by vivianQizhu** [comment]
Thanks @leidwang @Kemama

**Pull request merged**
