### PR TITLE
mkfs: update old fs to new one

### PR DESCRIPTION
**Pull request by XueqiangWei**
ID: 1571048
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>

### CODE REVIEW

**Comment by XueqiangWei** [comment]
(1/4) smp_8.256m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.lvm.lvm_create: PASS (130.11 s)
 (2/4) smp_8.256m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.lvm.lvm_fill: PASS (340.87 s)
 (3/4) smp_8.256m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.lvm.lvm_ioquit: PASS (174.32 s)
 (4/4) smp_8.256m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.lvm.lvm_clean: PASS (86.03 s)
(1/4) smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u5.raw.virtio_scsi.up.virtio_net.Guest.RHEL.6.9.i386.io-github-autotest-qemu.lvm.lvm_create: PASS (67.09 s)
 (2/4) smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u5.raw.virtio_scsi.up.virtio_net.Guest.RHEL.6.9.i386.io-github-autotest-qemu.lvm.lvm_fill: PASS (155.30 s)
 (3/4) smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u5.raw.virtio_scsi.up.virtio_net.Guest.RHEL.6.9.i386.io-github-autotest-qemu.lvm.lvm_ioquit: PASS (139.46 s)
 (4/4) smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u5.raw.virtio_scsi.up.virtio_net.Guest.RHEL.6.9.i386.io-github-autotest-qemu.lvm.lvm_clean: PASS (59.91 s)
(1/4) smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.cdrom_test.cdrom_default.q35: PASS (245.74 s)
 (2/4) smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.cdrom_test.cdrom_tray.q35: PASS (182.83 s)
 (3/4) smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.cdrom_test.cdrom_lock.q35: PASS (77.79 s)
 (4/4) smp_4.1024m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.cdrom_test.cdrom_not_insert.q35: PASS (72.81 s)
(1/4) smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.raw.virtio_scsi.up.virtio_net.Guest.RHEL.6.9.i386.io-github-autotest-qemu.cdrom_test.cdrom_default: PASS (215.98 s)
 (2/4) smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.raw.virtio_scsi.up.virtio_net.Guest.RHEL.6.9.i386.io-github-autotest-qemu.cdrom_test.cdrom_tray: PASS (152.38 s)
 (3/4) smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.raw.virtio_scsi.up.virtio_net.Guest.RHEL.6.9.i386.io-github-autotest-qemu.cdrom_test.cdrom_lock: PASS (50.19 s)
 (4/4) smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u5.raw.virtio_scsi.up.virtio_net.Guest.RHEL.6.9.i386.io-github-autotest-qemu.cdrom_test.cdrom_not_insert: PASS (44.40 s)
(1/1) smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.format_disk: PASS (83.71 s)

**Comment by CongLi** [comment]
Ack.

**Comment by XueqiangWei** [comment]
(1/1) smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u5.raw.virtio_scsi.up.virtio_net.Guest.RHEL.6.9.i386.io-github-autotest-qemu.format_disk: PASS (92.15 s)

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

**Pull request merged**
