### PR TITLE
blockdev_inc_backup_never: Do incremental live backup with bitmap-mode:never

### PR DESCRIPTION
**Pull request by aliang123**
Do incremental live backup with sync:incremental and
bitmap-mode:never

Signed-off-by: Aihua Liang <aliang@redhat.com>
id:1983902

### CODE REVIEW

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_never.q35: PASS (44.01 s)

**Comment by aliang123** [comment]
@zhencliu @ngu-niny, please help to review, thanks

**Comment by zhencliu** [comment]
LGTM

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_never.q35: PASS (42.97 s)

**Comment by ngu-niny** [comment]
1-Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_never Finshed 2021-07-25 22:22:13 2021-07-25 22:24:23 PASS 130.098174

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
