### PR TITLE
virtio_fs: separate folder test to a single one

### PR DESCRIPTION
**Pull request by xiagao**
Make folder test to a single case to make it more flexible.
ID: 2013071
Signed-off-by: Xiaoling Gao <xiagao@redhat.com>

### CODE REVIEW

**Comment by xiagao** [comment]
@zhenyzha Could you help review?thanks

**Comment by xiagao** [comment]
--testcase=virtio_fs_share_data_multi_backend.default..with_cache.auto.default_extra_parameters.default

 (1/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.x.0.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_cache.auto.with_nfs_source.q35: PASS (92.24 s)
 (2/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.x.0.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_folder.with_cache.auto.with_nfs_source.q35: PASS (83.29 s)

**Comment by zhenyzha** [comment]
LGTM.Acked-by: Zhenyu Zhang <[zhenyzha@redhat.com](mailto:zhenyzha@redhat.com)>

```
 (1/3) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_folder.with_cache.auto.with_nfs_source.arm64-pci: STARTED
- (1/3) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_folder.with_cache.auto.with_nfs_source.arm64-pci: PASS (257.43 s)
 (2/3) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_folder.with_cache.always.with_nfs_source.arm64-pci: STARTED
/ (2/3) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_folder.with_cache.always.with_nfs_source.arm64-pci: PASS (182.80 s)
 (3/3) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_folder.with_cache.none.with_nfs_source.arm64-pci: STARTED
| (3/3) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_folder.with_cache.none.with_nfs_source.arm64-pci: PASS (190.79 s)
```

And no regression
```
 (1/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_cache.auto.with_nfs_source.arm64-pci: STARTED
- (1/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_cache.auto.with_nfs_source.arm64-pci: PASS (200.43 s)
 (2/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_cache.always.with_nfs_source.arm64-pci: STARTED
\ (2/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_cache.always.with_nfs_source.arm64-pci: PASS (188.80 s)
 (3/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_cache.none.with_nfs_source.arm64-pci: STARTED
\ (3/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_cache.none.with_nfs_source.arm64-pci: PASS (192.17 s)
 (4/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_folder.with_cache.auto.with_nfs_source.arm64-pci: STARTED
| (4/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_folder.with_cache.auto.with_nfs_source.arm64-pci: PASS (188.95 s)
 (5/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_folder.with_cache.always.with_nfs_source.arm64-pci: STARTED
- (5/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_folder.with_cache.always.with_nfs_source.arm64-pci: PASS (193.40 s)
 (6/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_folder.with_cache.none.with_nfs_source.arm64-pci: STARTED
- (6/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_folder.with_cache.none.with_nfs_source.arm64-pci: PASS (196.11 s)
```

**Review by zhenyzha — APPROVED** [review]

**Comment by xiagao** [comment]
@YongxueHong Could you help review? Thanks.

**Pull request merged**
