### PR TITLE
virtio-fs: new case of record virtiofs log in windows guest

### PR DESCRIPTION
**Pull request by xiagao**
Register a virtiofs service to start a shared directory in windows guest and record viriofs log in it.
ID: 1946429, 1946423
Signed-off-by: Xiaoling Gao <xiagao@redhat.com>

### CODE REVIEW

**Comment by xiagao** [comment]
@YongxueHong Could you help review it?

**Comment by xiagao** [comment]
(1/9) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.virtio_fs_multi_vms.share_fs_source.q35: ERROR: No ipv4 DHCP lease for MAC 9a:b4:95:7c:72:67 (605.84 s)
 (2/9) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_dac_read_search.with_cache.auto.q35: PASS (60.19 s)
 (3/9) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_sys_admin.with_cache.none.q35: PASS (81.11 s)
 (4/9) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.q35: PASS (86.66 s)
 (5/9) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.x86_64.io-github-autotest-qemu.virtio_fs_multi_vms.share_fs_source.q35: PASS (180.02 s)
 (6/9) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.x86_64.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_dac_read_search.with_cache.auto.q35: PASS (68.16 s)
 (7/9) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.x86_64.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_sys_admin.with_cache.none.q35: PASS (68.00 s)
 (8/9) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.q35: PASS (69.47 s)
 (9/9) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.with_log_check.q35: FAIL: Virtiofs log is not created. (41.58 s)

**Review by YongxueHong — APPROVED** [review]
LGTM

**Comment by xiagao** [comment]
The latest results. @YongxueHong 
 (1/9) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.q35: PASS (90.60 s)
 (2/9) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.virtio_fs_multi_vms.share_fs_source.q35: ERROR: No ipv4 DHCP lease for MAC 9a:2f:b1:fd:b9:73 (611.10 s)
 (3/9) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_dac_read_search.with_cache.auto.q35: PASS (65.24 s)
 (4/9) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_sys_admin.with_cache.none.q35: PASS (97.77 s)
 (5/9) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.q35: PASS (153.71 s)
 (6/9) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.with_log_check.q35: FAIL: Virtiofs log is not created. (78.82 s)
 (7/9) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_fs_multi_vms.share_fs_source.q35: PASS (237.07 s)
 (8/9) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_dac_read_search.with_cache.auto.q35: PASS (95.38 s)
 (9/9) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_sys_admin.with_cache.none.q35: PASS (95.21 s)

**Pull request merged**
