### PR TITLE
driver_load: Support ppc for loading driver

### PR DESCRIPTION
**Pull request by zhenyzha**
Since ppc doesn't suppurt ide interface, so replace it
with scsi-hd.

ID: 1741400
Signed-off-by: zhenyu zhang <zhenyzha@redhat.com>

### CODE REVIEW

**Comment by zhenyzha** [comment]
(1/2) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.driver_load.with_block: PASS (125.71 s)
 (2/2) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.driver_load.with_vioscsi: PASS (124.65 s)

**Comment by zhenyzha** [comment]
@YongxueHong @ngu-niny @PaulYuuu please take a review, thanks.

**Comment by YongxueHong** [comment]
LGTM.

**Comment by ngu-niny** [comment]
Test PASS and LGTM.

 (1/2) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.driver_load.with_block: PASS (99.25 s)
 (2/2) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.driver_load.with_vioscsi: PASS (92.99 s)

Acked-by: Nini Gu <ngu@redhat.com>

**Comment by lolyu** [comment]
LGTM

**Pull request merged**
