### PR TITLE
qemu_disk_img: Support target files with luks format

### PR DESCRIPTION
**Pull request by hellohellenmao**
Update config file for targets from convertion to support luks format

Signed-off-by: Tingting Mao <timao@redhat.com>

### CODE REVIEW

**Comment by hellohellenmao** [comment]
# python ConfigTest.py --testcase=qemu_disk_img.convert.base_to_luks --clone=no --guestname=RHEL.8.1.0 --imageformat=qcow2
......
......
(1/1) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.qemu_disk_img.convert.base_to_luks: PASS (501.98 s)

**Comment by hellohellenmao** [comment]
@lolyu @PaulYuuu Help to review, please.

**Comment by hellohellenmao** [comment]
@zhenyzha Help to take review,please.

**Comment by zhenyzha** [comment]
(1/1) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.qemu_disk_img.convert.base_to_luks: PASS (780.57 s)

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Comment by lolyu** [comment]
You should mention the test case that affects either in your commit title or log.

**Pull request merged**
