### PR TITLE
Block stream test with vm installation

### PR DESCRIPTION
**Pull request by zhencliu**
ID: 1882173

### CODE REVIEW

**Comment by zhencliu** [comment]
local fs:
 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_install: PASS (1466.62 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-24T00.23-4879df2/results.html
JOB TIME   : 1471.83 s

gluster direct:
 (1/1) Host_RHEL.m8.u3.product_av.gluster_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_install: PASS (2757.99 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2020-09-24T12.23-957274c/results.html
JOB TIME   : 2761.90 s

iscsi direct:
 (1/1) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_install: PASS (1899.07 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-24T01.34-f8eeffc/results.html
JOB TIME   : 1904.22 s

nbd:
 (1/1) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_install: PASS (1746.45 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-24T02.27-5e64b6c/results.html
JOB TIME   : 1751.65 s

hi @YongxueHong @aliang123 , can you please help to review this patch? Thanks.
it deps on #2418

**Comment by aliang123** [comment]
Please run this case on system disk.

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_install.q35: PASS (3744.05 s)

Acked-by: Aihua Liang <aliang@redhat.com>

**Comment by zhencliu** [comment]
hi @ngu-niny , can you please help to review this patch? Thanks.
btw: it deps on #2418

**Comment by zhencliu** [comment]
hi @ngu-niny , code fixed for this patch, for the mirror_install, I will open a new request for it, can you please help to review this patch first? Thanks.

**Comment by ngu-niny** [comment]
Test PASS on ppc:

'1-Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.blockdev_stream_install' Finshed 2020-09-27 01:59:49 2020-09-27 02:23:04 PASS 1394.821554

Acked-by: Nini Gu <ngu@redhat.com>

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
