### PR TITLE
Add QSD pidfile option test

### PR DESCRIPTION
**Pull request by qingwangrh**
ID:2120995
Signed-off-by: qingwangrh <qinwang@redhat.com>

### CODE REVIEW

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=qsd_pidfile_check --guestname=RHEL.8.4.0 --clone=no
(1/1) Host_RHEL.m8.u6.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qsd_pidfile_check.q35: STARTED
 (1/1) Host_RHEL.m8.u6.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qsd_pidfile_check.q35: PASS (6.55 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by qingwangrh** [comment]
This patch depens on https://github.com/autotest/tp-qemu/pull/3427. It need to wait 3427 get merged.

**Comment by qingwangrh** [comment]
@YongxueHong @zhenyzha Please help to review,thanks.

**Comment by zhenyzha** [comment]
git am 3450.patch
```
Applying: Add QSD pidfile option test
.git/rebase-apply/patch:25: new blank line at EOF.
+
warning: 1 line adds whitespace errors.
```

**Comment by zhenyzha** [comment]
Other parts ok for me

` (1/1) Host_RHEL.m9.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.aarch64.io-github-autotest-qemu.qsd_pidfile_check.arm64-pci: PASS (4.23 s)`

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Comment by qingwangrh** [comment]
> git am 3450.patch
> 
> ```
> Applying: Add QSD pidfile option test
> .git/rebase-apply/patch:25: new blank line at EOF.
> +
> warning: 1 line adds whitespace errors.
> ```

updated

**Comment by XueqiangWei** [comment]
@YongxueHong  Please help review it,thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
