### PR TITLE
Mirror filter-node-name test

### PR DESCRIPTION
**Pull request by zhencliu**
blockdev_mirror_filternode: Add block mirror filter-node-name test
    
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1898035

### CODE REVIEW

**Comment by zhencliu** [comment]
local fs:
 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_filternode.q35: PASS (96.60 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-16T05.49-0ebca3e/results.html
JOB TIME   : 99.35 s

gluster direct (virtio_blk+virtio_net+8.4)
 (1/1) Host_RHEL.m8.u3.product_av.gluster_direct.luks.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_mirror_filternode.q35: PASS (139.13 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-16T17.58-fd31cf3/results.html
JOB TIME   : 142.82 s

iscsi direct:
 (1/1) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_filternode.q35: PASS (90.39 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-16T20.15-5bf363f/results.html
JOB TIME   : 93.18 s

nbd:
 (1/1) Host_RHEL.m8.u3.product_av.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_filternode: PASS (163.00 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-16T20.20-4c20a47/results.html
JOB TIME   : 165.57 s

**Comment by zhencliu** [comment]
hi @ngu-niny @YongxueHong , can you please help to review this patch? Thank you.

**Comment by zhencliu** [comment]
Add file md5sum check with mirror image as the data image

 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_mirror_filternode.q35: PASS (166.63 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-17T02.05-fc1b824/results.html
JOB TIME   : 169.60 s

 (1/1) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_filternode.q35: PASS (165.42 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-17T02.14-4ebb271/results.html
JOB TIME   : 168.41 s

**Comment by ngu-niny** [comment]
Test PASS:

 (1/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_mirror_filternode:  PASS (181.66 s)
 (2/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_mirror_filternode:  PASS (242.54 s)

Acked-by: Nini Gu <ngu@redhat.com>

**Review by YongxueHong — APPROVED** [review]
LGTM

**Pull request merged**
