### PR TITLE
generic.tests: iozone_windows, change timeout value from 7200 to 10800

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>
ID: 1445125

### CODE REVIEW

**Comment by XueqiangWei** [comment]
smp_1.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win10.x86_64.io-github-autotest-qemu.iozone_windows.aio_threads: PASS (3256.44 s)

smp_1.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win2012.x86_64.r2.io-github-autotest-qemu.iozone_windows.aio_threads: PASS (5090.90 s)

**Comment by lijinlijin** [comment]
ACK as we discussed before.
Thanks

**Comment by CongLi** [comment]
Ack.

**Comment by CongLi** [comment]
Thanks @XueqiangWei @lijinlijin

**Pull request merged**
