### PR TITLE
Update threshold for some memory hotplug test cases

### PR DESCRIPTION
**Pull request by huangyum**
ID: 1924971
Signed-off-by: Yumei Huang <yuhuang@redhat.com>

### CODE REVIEW

**Comment by huangyum** [comment]
repeat1.Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.balloon_memhp.backend_ram.q35: PASS (141.74 s)
 repeat1.Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.balloon_memhp.backend_file.q35: PASS (137.54 s)

**Comment by huangyum** [comment]
@yanan-fu Please help review, thanks.

**Comment by yanan-fu** [comment]
@huangyum  Could you explain a bit more about the reason of update these 2 cases only,  but not other hotplug mem cases ?    I wonder if it is make sense for other cases, which means, the default value in check_memory need be updated.

**Comment by yanan-fu** [comment]
For ppc, seems it use unified `threshold = 0.15`, so i wonder if x86 can also use the same threshold.

**Comment by huangyum** [comment]
> @huangyum Could you explain a bit more about the reason of update these 2 cases only, but not other hotplug mem cases ? I wonder if it is make sense for other cases, which means, the default value in check_memory need be updated.

As far as I know, only these two cases hit this issue. The total memory for the two cases are less than 4G, causing the absolute threshold is small. Other cases work fine now, so I didn't update them. If use the same threshold as ppc, it will work too but not necessary. What do you think ?

**Comment by yanan-fu** [comment]
> > @huangyum Could you explain a bit more about the reason of update these 2 cases only, but not other hotplug mem cases ? I wonder if it is make sense for other cases, which means, the default value in check_memory need be updated.
> 
> As far as I know, only these two cases hit this issue. The total memory for the two cases are less than 4G, causing the absolute threshold is small. Other cases work fine now, so I didn't update them. If use the same threshold as ppc, it will work too but not necessary. What do you think ?

I did not explain it clear enough, i mean if it possible to use an unified threshold for all x86,  do not mean to use the same value of ppc.

I prefer to use unified threshold for all x86,  but i am ok if you think only these 2 cases need this fix is enough. Thanks!

**Comment by huangyum** [comment]
> > > @huangyum Could you explain a bit more about the reason of update these 2 cases only, but not other hotplug mem cases ? I wonder if it is make sense for other cases, which means, the default value in check_memory need be updated.
> > 
> > 
> > As far as I know, only these two cases hit this issue. The total memory for the two cases are less than 4G, causing the absolute threshold is small. Other cases work fine now, so I didn't update them. If use the same threshold as ppc, it will work too but not necessary. What do you think ?
> 
> I did not explain it clear enough, i mean if it possible to use an unified threshold for all x86, do not mean to use the same value of ppc.
> 
> I prefer to use unified threshold for all x86, but i am ok if you think only these 2 cases need this fix is enough. Thanks!

I prefer to only update these two cases for now. To some extent, a bigger threshold may bring risk of missing product bugs. If current one works well, I'd keep it is. Thanks.

**Comment by yanan-fu** [comment]
Ok, i am ok with that too

Ack

**Pull request merged**
