### PR TITLE
bridge_vlan:Add NM management to support setting private ip

### PR DESCRIPTION
**Pull request by yanglei-rh**
ID:2032103

Signed-off-by: Lei Yang <leiayang@redhat.com>

### CODE REVIEW

**Comment by yanglei-rh** [comment]
Test Pass:
(1/1) Host_RHEL.m8.u6.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.bridge_vlan.q35: PASS (677.64 s)

**Comment by yanglei-rh** [comment]
@PaulYuuu Please help me review it, thanks a lot.

**Comment by PaulYuuu** [comment]
LGTM. By the way, NetworkManager will become more and more popular in the future, and RHEL8 use it instead of network-script by default. So will you plan to use nmcli to manage network interfaces in the future?

**Comment by yanglei-rh** [comment]
> LGTM. By the way, NetworkManager will become more and more popular in the future, and RHEL8 use it instead of network-script by default. So will you plan to use nmcli to manage network interfaces in the future?
Yes, I will use nmcli first to manage network interfaces in the future.Just for the current case, I use the current fix method.

**Comment by PaulYuuu** [comment]
OK

**Review by PaulYuuu — APPROVED** [review]

**Pull request merged**
