### PR TITLE
Disable luks format test for qsd relevant cases

### PR DESCRIPTION
**Pull request by qingwangrh**
Disable luks format test for qsd cases:
qsd_blockdev_check,qsd_export_vhub_check,
qsd_object_check,qsd_pidfile_check,qsd_qmp_cmd_check

ID:2208501,2208500,2208502,2208503,2208497

Signed-off-by: qingwangrh <qinwang@redhat.com>

### CODE REVIEW

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=qsd_object_check,qsd_qmp_cmd_check,qsd_export_vhub_check,qsd_pidfile_check,qsd_blockdev_check --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=RHEL.9.3.0 --driveformat=virtio_scsi  --imageformat=luks,qcow2 --machines=q35 --firmware=default_bios --netdst=virbr0 --clone=no --dryrun

Only filter out qcow2 cases

**Comment by qingwangrh** [comment]
@XueqiangWei @zhenyzha Please help to review. thanks

**Comment by zhenyzha** [comment]
LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

 --imageformat=luks,qcow2 --nicmodel=virtio_net --mem=8192 --vcpu=4 --testcase=qsd_object_check,qsd_qmp_cmd_check,qsd_export_vhub_check,qsd_pidfile_check,qsd_blockdev_check

```
 (1/5) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.qsd_export_vhub_check.arm64-pci: STARTED
 (1/5) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.qsd_export_vhub_check.arm64-pci: PASS (7.95 s)
 (2/5) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.qsd_qmp_cmd_check.arm64-pci: STARTED
 (2/5) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.qsd_qmp_cmd_check.arm64-pci: PASS (7.99 s)
 (3/5) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.qsd_blockdev_check.arm64-pci: STARTED
 (3/5) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.qsd_blockdev_check.arm64-pci: PASS (7.95 s)
 (4/5) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.qsd_pidfile_check.arm64-pci: STARTED
 (4/5) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.qsd_pidfile_check.arm64-pci: PASS (7.26 s)
 (5/5) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.qsd_object_check.arm64-pci: STARTED
 (5/5) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.qsd_object_check.arm64-pci: PASS (7.97 s)
```

**Review by zhenyzha — APPROVED** [review]

**Comment by XueqiangWei** [comment]
LGTM,
Acked-by: xuwei@redhat.com

**Review by XueqiangWei — APPROVED** [review]

**Pull request merged**
