### PR TITLE
block_iscsi_4kdisk:block_iscsi_lvm:add ovmf installation support

### PR DESCRIPTION
**Pull request by qingwangrh**
ID:2025515,2025514

Signed-off-by: qingwangrh <qinwang@redhat.com>

### CODE REVIEW

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=block_iscsi_lvm.with_installation.cdrom.extra_cdrom_ks.with_scsi_hd.q35,block_iscsi_4kdisk  --platform=x86_64 --guestname=Win10 --driveformat=virtio_scsi --nicmodel=virtio_net --imageformat=qcow2 --machines=q35  --customsparams="vm_mem_limit = 12G\nimage_aio=threads\ncd_format=ide" --firmware=ovmf  --clone=no

(1/2) Host_RHEL.m8.u5.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.block_iscsi_lvm.with_installation.cdrom.extra_cdrom_ks.with_scsi_hd.q35: PASS (1267.16 s)
 (2/2) Host_RHEL.m8.u5.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.block_iscsi_4kdisk.q35: PASS (1010.80 s)

**Comment by qingwangrh** [comment]
@YongxueHong @zhenyzha @peixiu Please help to review ,thanks.

**Comment by zhenyzha** [comment]
Please ignore me, ARM only supports edk2 but not ovmf.

**Review by YongxueHong — APPROVED** [review]

**Comment by peixiu** [comment]
(1/2) Host_RHEL.m.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_iscsi_4kdisk.q35: PASS (1184.86 s)
 (2/2) Host_RHEL.m.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_iscsi_lvm.with_installation.cdrom.extra_cdrom_ks.with_scsi_hd.q35: PASS (1256.34 s)

LTGM~

**Review by YongxueHong — APPROVED** [review]

**Pull request merged**
