### PR TITLE
Add "flexible_nic_index = yes" for multi nics related cases

### PR DESCRIPTION
**Pull request by yanan-fu**
when boot vm with multi nics, sometimes wrong nic index will cause
login guest failed,flexible_nic_index=yes can help avoid this issue

Signed-off-by: Yanan Fu <yfu@redhat.com>

### CODE REVIEW

**Comment by balamuruhans** [comment]
LGTM

**Comment by vivianQizhu** [comment]
@yanan-fu Can you help provide bz id?

**Comment by yanan-fu** [comment]
@vivianQizhu  i didn't filter bz for this issue, this is not related with one specific case.And i think bz id is not must ~    thanks !

**Comment by xutian** [comment]
just a enhancement,  looks good to me. thanks @yanan-fu

**Pull request merged**
