### PR TITLE
qemu.tests: Add virtio_serial_hotplug test case and script.

### PR DESCRIPTION
**Pull request by xutian**
This PR is update for origin PR https://github.com/autotest/tp-qemu/pull/331

Signed-off-by: Feng Yang <fyang@redhat.com>
Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
ID : 1157458 1157436

**Comment by xutian** [comment]
deps on PR https://github.com/autotest/virt-test/pull/2216

**Comment by xutian** [comment]
@CongSmile 
since you review origin PR https://github.com/autotest/tp-qemu/pull/331, would you like to review this one when free. 

Thanks,
Xu

**Comment by CongSmile** [comment]
Test failed. Same problem as #393 

  Traceback (most recent call last):
    File "/home/serial/staf-kvm-devel/autotest-devel/client/shared/test.py", line 823, in _call_test_function
      return func(*args, **dargs)
    File "/home/serial/staf-kvm-devel/autotest-devel/client/shared/test.py", line 291, in execute
      postprocess_profiled_run, args, dargs)
    File "/home/serial/staf-kvm-devel/autotest-devel/client/shared/test.py", line 209, in _call_run_once
      *args, **dargs)
    File "/home/serial/staf-kvm-devel/autotest-devel/client/shared/test.py", line 313, in run_once_profiling
      self.run_once(*args, **dargs)
    File "/home/serial/staf-kvm-devel/autotest-devel/client/tests/virt/virt.py", line 145, in run_once
      params = env_process.preprocess(self, params, env)
    File "/home/serial/staf-kvm-devel/autotest-devel/client/shared/error.py", line 141, in new_fn
      return fn(*args, **kwargs)
    File "/home/serial/staf-kvm-devel/autotest-devel/client/tests/virt/virttest/env_process.py", line 807, in preprocess
      process(test, params, env, preprocess_image, preprocess_vm)
    File "/home/serial/staf-kvm-devel/autotest-devel/client/tests/virt/virttest/env_process.py", line 526, in process
      _call_vm_func()
    File "/home/serial/staf-kvm-devel/autotest-devel/client/tests/virt/virttest/env_process.py", line 495, in _call_vm_func
      vm_func(test, vm_params, env, vm_name)
    File "/home/serial/staf-kvm-devel/autotest-devel/client/tests/virt/virttest/env_process.py", line 175, in preprocess_vm
      migration_exec_cmd=params.get("migration_exec_cmd_dst"))
    File "/home/serial/staf-kvm-devel/autotest-devel/client/shared/error.py", line 141, in new_fn
      return fn(*args, **kwargs)
    File "/home/serial/staf-kvm-devel/autotest-devel/client/tests/virt/virttest/qemu_vm.py", line 2505, in create
      self.create_serial_console()
    File "/home/serial/staf-kvm-devel/autotest-devel/client/tests/virt/virttest/qemu_vm.py", line 1969, in create_serial_console
      raise virt_vm.VMConfigMissingError(self.name, "isa_serial")
  VMConfigMissingError: Missing config 'isa_serial' for VM virt-tests-vm1

**Comment by vipmike007** [comment]
Hotplug w/ file_transfer:
14:42:53 INFO | Update MAC(aa:54:00:11:22:33)<->(10.66.9.165)IP pair into address_cache




14:48:40 WARNI| run process timeout (720) fired on: python /home/test10/autotest-devel/client/tests/virt/shared/deps/serial/serial_host_send_receive.py -s /tmp/virtio_port-vc1-20150731-143559-l15DuWiX -f /home/test10/autotest-devel/client/tmp/tmp/tmpF4matn_virt.qemu.smp_2.8192m.repeat1.run_test.Host_RHEL.7.2.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.virtio_serial_hotplug.port_hotplug.serial_hotplug_with_file_transfer/tmp-mmIUr7S3 -a both
14:48:41 ERROR| Exception in thread Thread-2:
14:48:41 ERROR| Traceback (most recent call last):
14:48:41 ERROR|   File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
14:48:41 ERROR|     self.run()
14:48:41 ERROR|   File "/home/test10/autotest-devel/client/shared/utils.py", line 977, in run
14:48:41 ERROR|     self._retval = self._target(*self._args, **self._kwargs)
14:48:41 ERROR|   File "/home/test10/autotest-devel/client/tests/virt/virttest/utils_test/__init__.py", line 533, in run_host_cmd
14:48:41 ERROR|     return utils.system_output(host_cmd, timeout=timeout)
14:48:41 ERROR|   File "/home/test10/autotest-devel/client/shared/utils.py", line 1268, in system_output
14:48:41 ERROR|     verbose=verbose, args=args).stdout
14:48:41 ERROR|   File "/home/test10/autotest-devel/client/shared/utils.py", line 913, in run
14:48:41 ERROR|     timeout)[0]
14:48:41 ERROR|   File "/home/test10/autotest-devel/client/shared/utils.py", line 1050, in join_bg_jobs
14:48:41 ERROR|     % timeout)
14:48:41 ERROR| CmdError: Command <python /home/test10/autotest-devel/client/tests/virt/shared/deps/serial/serial_host_send_receive.py -s /tmp/virtio_port-vc1-20150731-143559-l15DuWiX -f /home/test10/autotest-devel/client/tmp/tmp/tmpF4matn_virt.qemu.smp_2.8192m.repeat1.run_test.Host_RHEL.7.2.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.virtio_serial_hotplug.port_hotplug.serial_hotplug_with_file_transfer/tmp-mmIUr7S3 -a both> failed, rc=-15, Command(s) did not complete within 720 seconds
14:48:41 ERROR| * Command: 
14:48:41 ERROR|     python /home/test10/autotest-
14:48:41 ERROR|     devel/client/tests/virt/shared/deps/serial/serial_host_send_receive.py -s
14:48:41 ERROR|     /tmp/virtio_port-vc1-20150731-143559-l15DuWiX -f /home/test10/autotest-dev
14:48:41 ERROR|     el/client/tmp/tmp/tmpF4matn_virt.qemu.smp_2.8192m.repeat1.run_test.Host_RH
14:48:41 ERROR|     EL.7.2.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-
14:48:41 ERROR|     qemu.virtio_serial_hotplug.port_hotplug.serial_hotplug_with_file_transfer
14:48:41 ERROR|     /tmp-mmIUr7S3 -a both
14:48:41 ERROR| Exit status: -15
14:48:41 ERROR| Duration: 721.716468096

**Comment by suqinhuang** [comment]
@xutian 
https://github.com/autotest/virt-test/pull/2216 is closed, could you re-send it.

Thanks
Suqin

**Pull request closed without merging**
