### PR TITLE
Update vsock seqpacket test cases

### PR DESCRIPTION
**Pull request by qcheng-redhat**
Update vsock seqpacket test cases in vsock_test.tar.xz

Signed-off-by: qcheng <qcheng@redhat.com>

### CODE REVIEW

**Comment by qcheng-redhat** [comment]
(1/1) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.vsock_test.seqpacket_test.q35: PASS (57.67 s)

**Comment by qcheng-redhat** [comment]
Hi @PaulYuuu , can you help review this patch when you have time. Thanks.

**Review by PaulYuuu — APPROVED** [review]
ACK

**Comment by PaulYuuu** [comment]
@qcheng-redhat Don't forget to add the ID in the description.

**Comment by qcheng-redhat** [comment]
> 

Thanks for reminder, added bug ID.

**Pull request merged**
