### PR TITLE
qemu_guest_agent: refactor case of check 'fsfreeze-hook' script's path

### PR DESCRIPTION
**Pull request by xiagao**
ID: 1764074
Signed-off-by: Xiaoling Gao <xiagao@redhat.com>

### CODE REVIEW

**Comment by xiagao** [comment]
(1/1) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_path_fsfreeze_hook: PASS

**Comment by xiagao** [comment]
@xiangchunfu  Could you help review it? thanks

**Comment by xiangchunfu** [comment]
looks good to me.  

Acked by: Xiangchun Fu xfu@redhat.com

**Comment by xiagao** [comment]
@lolyu  call for review..

**Comment by lolyu** [comment]
Please fill you commit log.

**Comment by xiagao** [comment]
(1/1) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_path_fsfreeze_hook: PASS (73.85 s)

**Comment by xiagao** [comment]
(1/1) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_path_fsfreeze_hook: PASS (73.85 s)

**Comment by xiagao** [comment]
(1/1) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_path_fsfreeze_hook: PASS (73.85 s)

**Pull request merged**
