### PR TITLE
tp-qemu: floppy.py: add glusterfs support.

### PR DESCRIPTION
**Pull request by CongSmile**
Signed-off-by: Cong Li <coli@redhat.com>

id: 1270741

### CODE REVIEW

**Comment by spcui** [comment]
only add glusterfs, how about ceph and iscsi?

**Comment by CongSmile** [comment]
@spcui 

According to the request, there is bug with glusterfs.

Could show me the details of iscsi and ceph and report the bug?

Thanks.

**Comment by suqinhuang** [comment]
Hi coli,

in my opinion, the simplest fix is to put the floppy in local.

**Comment by CongSmile** [comment]
Hi @suqinhuang 

As we talked before, using the gluster for the fix.

If you still think local is better, I can update it, I think both are fine.

Could you help review it ?

Thanks.

**Comment by xutian** [comment]
Mark as closed  because of we need to update framework to make avocado support floppy, cdrom in glusterfs, ceph, iscsi and nfs storage.

**Pull request closed without merging**
