### PR TITLE
cgroup: Fix maxcpus and smp's issues

### PR DESCRIPTION
**Pull request by xiangchunfu**
Fix sockets * dies * cores * threads < smp or maxcpus

id: 1766938

Signed-off-by: Xiangchun Fu <xfu@redhat.com>

### CODE REVIEW

**Comment by xiangchunfu** [comment]
(1/1) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.cgroup.cpu_cfs_util: PASS (640.64 s)

**Comment by xiangchunfu** [comment]
@yanan-fu Could you help review this thanks?

**Comment by xiangchunfu** [comment]
After discussion with yfu,   updated this patch.  Thanks yfu.

smp value is expect in qemu command.
-smp 1,maxcpus=1,cores=1,threads=1,sockets=1 

(1/1) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.cgroup.cpu_cfs_util: PASS (618.27 s)

**Comment by yanan-fu** [comment]
@xiangchunfu `cpu_cfs_util` set in smp to 1 in the script instead of the cfg:
 https://github.com/autotest/tp-qemu/blob/7a26f45df6727398feecc29614af099861929098/qemu/tests/cgroup.py#L673

To be more reliable, update `socket` in the script is ok.

**Comment by xiangchunfu** [comment]
@yanan-fu 
updated,  Add params["vcpu_sockets"] = 1 option to script. 

PASS 1-Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.cgroup.cpu_cfs_util

**Comment by xiangchunfu** [comment]
@vivianQizhu Can you help check it? Thanks.

**Pull request merged**
