### PR TITLE
qemu: Delete transfer_type parameter

### PR DESCRIPTION
**Pull request by FengYang**
Signed-off-by: Feng Yang <fyang@redhat.com>

ID: 1186122

### CODE REVIEW

**Comment by CongSmile** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by ypu** [comment]
LGTM
Acked-by: Yiqiao Pu <ypu@redhat.com>

**Comment by ypu** [comment]
Related pullreqs:
https://github.com/autotest/virt-test/pull/1986

**Comment by ypu** [comment]
LGTM

Acked-by:Yiqiao Pu <ypu@redhat.com>

**Comment by ypu** [comment]
Thanks @FengYang and @CongSmile will merge it.

**Pull request merged**
