### PR TITLE
virtio_aer_opt:Add ats_aer options for block device

### PR DESCRIPTION
**Pull request by qingwangrh**
ID:2031702
Signed-off-by: qingwangrh <qinwang@redhat.com>

### CODE REVIEW

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=virtio_aer_opt --guestname=RHEL.9.0.0 --machines=q35 --clone=no
(1/1) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.virtio_aer_opt.q35: PASS (39.50 s)

**Comment by qingwangrh** [comment]
@YongxueHong @zhenyzha Please help to review,thanks.

**Review by YongxueHong — APPROVED** [review]

**Comment by zhenyzha** [comment]
git am 3137.patch
Applying: virtio_aer_opt:Add ats_aer testing for block device

` (1/1) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_aer_opt.arm64-pci: PASS (173.52 s)`

**Review by zhenyzha — APPROVED** [review]

**Comment by yanan-fu** [comment]
Just noticed this patch, i have some concern about this:
In the original test, to test boot virtio device with ats and aer, both virtio-blk and virtio-scsi are covered, this patch add the hotplug device checking, but only virtio-blk.  Any reason to drop virtio-scsi hotplug test with aer and ats ?

**Comment by qingwangrh** [comment]
> Just noticed this patch, i have some concern about this: In the original test, to test boot virtio device with ats and aer, both virtio-blk and virtio-scsi are covered, this patch add the hotplug device checking, but only virtio-blk. Any reason to drop virtio-scsi hotplug test with aer and ats ?

The boot command line  covered you mentioned, scsi disk no aer and ats , not need to test it.

**Comment by yanan-fu** [comment]
> > Just noticed this patch, i have some concern about this: In the original test, to test boot virtio device with ats and aer, both virtio-blk and virtio-scsi are covered, this patch add the hotplug device checking, but only virtio-blk. Any reason to drop virtio-scsi hotplug test with aer and ats ?
> 
> The boot command line covered you mentioned, scsi disk no aer and ats , not need to test it.

I mean the virtio-scsi-pci controller, but yes, you are right, we can not unplug it. Usually, only one virtio-scsi controller but multiple disks include system disk if run test with virti-scsi, Thanks for your update, no concern now ~

**Pull request merged**
