### PR TITLE
qemu.tests: Update the cleanup_cdrom in cdrom test

### PR DESCRIPTION
**Pull request by ypu**
Update a mistake made in gluster support. And add one line for debug.

### CODE REVIEW

**Comment by ypu** [comment]
ID: 1200245

**Comment by spcui** [comment]
LGTM
Acked-by: @spcui

**Comment by CongSmile** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by ypu** [comment]
Thanks @spcui and @CongSmile will merge it.

**Pull request merged**
