### PR TITLE
Add support for qemu_disk_img on s390x

### PR DESCRIPTION
**Pull request by fbq815**
disk_format: add qemu_disk_img.info.change_block_interface for s390x

ID: 1959818

Signed-off-by: Boqiao Fu <bfu@redhat.com>

### CODE REVIEW

**Comment by fbq815** [comment]
Test result:
JOB ID     : ea5e5e8bd94b9ed7ac410734b965a6233d9d71da
JOB LOG    : /home/bfu/kar/workspace/job-results/job-2021-05-12T05.58-ea5e5e8/job.log
 (1/1) Host_RHEL.m8.u4.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.s390x.io-github-autotest-qemu.qemu_disk_img.info.change_block_interface.s390-virtio: PASS (252.42 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/bfu/kar/workspace/job-results/job-2021-05-12T05.58-ea5e5e8/results.html
JOB TIME   : 253.29 s

**Comment by fbq815** [comment]
@PaulYuuu @ngu-niny please help me review this patch

**Comment by ngu-niny** [comment]
LGTM.

**Comment by PaulYuuu** [comment]
LGTM, but please correct your title to match your change.

**Comment by fbq815** [comment]
@PaulYuuu  Updated the title

**Review by PaulYuuu — APPROVED** [review]

**Pull request merged**
