### PR TITLE
thp_fragment: includes new thp_fragment tool

### PR DESCRIPTION
**Pull request by mcasquer**
thp_fragment: includes new thp_fragment tool

Includes a new packaged tool to be used by THP defrag
test case. This tool basically does defragmentation
(which can be also understood as compaction) on THP allocation.

Signed-off-by: mcasquer <mcasquer@redhat.com>
ID: 1419

### CODE REVIEW

**Comment by mcasquer** [comment]
@luckyh @yanan-fu @zhenyzha please could you review this PR? Thanks !

**Review by luckyh — DISMISSED** [review]
LGTM

**Comment by mcasquer** [comment]
@luckyh @yanan-fu @zhenyzha please could you review again this PR? Thanks !

**Review by yanan-fu — APPROVED** [review]
Ack

**Review by zhenyzha — APPROVED** [review]
Ack

**Comment by yanan-fu** [comment]
Thanks all!

**Pull request merged**
