### PR TITLE
chardev_hotplug: Disable it on ppc since pci-serial is not supported

### PR DESCRIPTION
**Pull request by vivianQizhu**
id: 1404540
Signed-off-by: Qianqian Zhu <qizhu@redhat.com>

### CODE REVIEW

**Comment by vivianQizhu** [comment]
@MiriamDeng Please help review, thanks.

**Comment by MiriamDeng** [comment]
Hotplug spapr-vty isn't supported on ppc so the patch will fail. We just need to remove pci-serial test cases in ppc's loop.
How do you think ? Thanks @vivianQizhu
...
Error: Bus 'spapr-vio' does not support hotplugging

**Comment by vivianQizhu** [comment]
@MiriamDeng Okay, updated and disable this case for ppc, please help check, thanks.

**Comment by vivianQizhu** [comment]
@MiriamDeng Updated, please help check, thanks.

**Comment by MiriamDeng** [comment]
The patch keep hotplug&hot-unplug chardev part, it is acceptable.

**Comment by MiriamDeng** [comment]
LGTM, thanks.
 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.chardev_hotplug: PASS (101.33 s)

**Comment by vivianQizhu** [comment]
Thanks @MiriamDeng

**Pull request merged**
