### PR TITLE
migrate.cfg: fix migrate.between_vhost_novhost cannot run on RHEL7 host

### PR DESCRIPTION
**Pull request by kimi1978wy**
delete "only Host_RHEL.m6" in cfg file

Signed-off-by: Yu Wang <wyu@redhat.com>

id: 1491527

### CODE REVIEW

**Comment by kimi1978wy** [comment]
ran the jobs and checked the logs, it can run normally on RHEL7 host.

 (1/2) smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_blk.up.virtio_net.RHEL.7.4.x86_64.io-github-autotest-qemu.migrate.between_vhost_novhost.tcp: PASS (225.92 s)
 (2/2) smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_blk.up.virtio_net.Win7.x86_64.sp1.io-github-autotest-qemu.migrate.between_vhost_novhost.tcp: PASS (274.77 s)

**Comment by suqinhuang** [comment]
how about rhel5 host

**Comment by kimi1978wy** [comment]
@suqinhuang I asked xuhan, he said, avocado is only supported on rhel6 and rhel7, so no need "no Host_RHEL.m5" .

**Comment by hereischen** [comment]
Acked-by: Haotng Chen hachen@redhat.com

**Comment by balamuruhans** [comment]
@kimi1978wy does migration succeed between vhost and novhost, so if guest in the source uses vhost and destination have vhost=off, I believe migration should fail.

**Comment by kimi1978wy** [comment]
Hi @balamuruhans , I confirmed with others, it is supported "migration between vhost and novhost" on both x86 and ppc.

**Comment by balamuruhans** [comment]
@kimi1978wy okay, Thank you for clarifying.

**Comment by xiagao** [comment]
Acked-by: Xiaoling Gao <xiagao@redhat.com>

**Comment by suqinhuang** [comment]
ack

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
