### PR TITLE
Add netkvm function test after install driver via installer

### PR DESCRIPTION
**Pull request by leidwang**
ID:2114646
Signed-off-by: Leidong Wang <leidwang@redhat.com>

### CODE REVIEW

**Comment by leidwang** [comment]
Hi @vivianQizhu  Could you help to review this patch?Thanks a lot!

**Review by vivianQizhu — APPROVED** [review]
@xiagao Also please help test this one, thanks.

**Comment by xiagao** [comment]
(1/1) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.win_virtio_driver_install_by_installer.driver_install.single_driver.with_netkvm.q35: STARTED
 (1/1) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.win_virtio_driver_install_by_installer.driver_install.single_driver.with_netkvm.q35: PASS (351.60 s)

The resulte is pass.
ACK

**Review by xiagao — APPROVED** [review]

**Comment by vivianQizhu** [comment]
Thanks @xiagao and @leidwang

**Pull request merged**
