### PR TITLE
block_iscsi_format_large_size_disk: install NetFx3 feature

### PR DESCRIPTION
**Pull request by menli820**
For win10(22H2) x86_86, install the NetFx3 feature to keep the right test env.

ID: 2218054
Signed-off-by: Menghuan Li menli@redhat.com

### CODE REVIEW

**Comment by menli820** [comment]
(1/1) Host_RHEL.m9.u3.qcow2.virtio_blk.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.block_iscsi_format_large_size_disk.with_virtio.q35: STARTED
 (1/1) Host_RHEL.m9.u3.qcow2.virtio_blk.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.block_iscsi_format_large_size_disk.with_virtio.q35: PASS (308.74 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by menli820** [comment]
@qingwangrh @peixiu @YongxueHong  please help to review it when you free, thanks

**Comment by YongxueHong** [comment]
Hi @nickzhq 
Would you like to hep review it?
Thanks.

**Comment by menli820** [comment]
@all， after syncing with @qingwangrh ， not only the case was influenced, so we may change the solution. Change the patch status to draft first.

**Pull request closed without merging**
