### PR TITLE
migration: Fix IndexError

### PR DESCRIPTION
**Pull request by luckyh**
Signed-off-by: Xu Han <xuhan@redhat.com>

ID: 1627006

### CODE REVIEW

**Comment by luckyh** [comment]
This a regression of https://github.com/autotest/tp-qemu/pull/1433

**Comment by luckyh** [comment]
@sitoliu please help review this patch, thanks.

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

**Comment by sitoliu** [comment]
Acked-by: Sitong Liu <siliu@redhat.com>

 (1) Host_RHEL.m8.u0.spice.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.x86_64.io-github-autotest-qemu.migrate.tcp: PASS (383.14 s)
 (2) Host_RHEL.m8.u0.spice.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.x86_64.io-github-autotest-qemu.migrate.tcp.with_filter_off.with_post_copy: PASS (162.86 s)
 (3) Host_RHEL.m8.u0.spice.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.x86_64.io-github-autotest-qemu.migrate.tcp.with_filter_off.with_multifd: PASS (221.63 s)
 (4) Host_RHEL.m8.u0.spice.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.x86_64.io-github-autotest-qemu.migrate.mig_cancel: PASS (159.58 s)

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
