### PR TITLE
Update and correct the path referred to time-warp-test.c

### PR DESCRIPTION
**Pull request by sitoliu**
id: 1467300

Signed-off-by: Sitong Liu <siliu@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
Usually, we use:
id: 1467300

**Comment by sitoliu** [comment]
@yanan-fu Update it. Thanks Yanan.

**Comment by yanan-fu** [comment]
Acked-by: Yanan Fu <yfu@redhat.com>

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
