### PR TITLE
Reduce stress and run time, too big stress caused case run ERROR.

### PR DESCRIPTION
**Pull request by weliao**
1.reduce the filesize to 512
2.reduce the scp_para_sessions to 4
3.reduce the stress_timeout to 360

id: 1010795
Signed-off-by: weliao <weliao@redhat.com>

### CODE REVIEW

**Comment by PyLearner** [comment]
Acked-by : Meng Yang meyang@redhat.com

smp_64.32768m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.mq_change_qnum.disable_enable_queues.under_file_transfer.enable_msi: PASS

**Comment by vivianQizhu** [comment]
LGTM, Acked-by: Qianqian Zhu qizhu@redhat.com

**Comment by CongLi** [comment]
Hi @weliao ,

Could you please update the commit log with format like: ***.py : ****?

Thanks.

**Comment by weliao** [comment]
@CongLi ,Hi, already updated it, please review again.

Thanks.

**Comment by CongLi** [comment]
Thanks @weliao @PyLearner @vivianQizhu , merged.

**Pull request merged**
