### PR TITLE
blockdev_mirror_speed: mirror speed test

### PR DESCRIPTION
**Pull request by zhencliu**
Set speed with block-job-set-speed:
  for an invalid speed: check the proper error message
  for a valid speed: check job is still running

Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1896589

### CODE REVIEW

**Comment by zhencliu** [comment]
local fs:
 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_speed.q35: PASS (96.32 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-12T21.32-bc8ab8f/results.html
JOB TIME   : 98.99 s

iscsi direct:
 (1/1) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_speed.q35: PASS (98.89 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-12T21.44-0ee20ca/results.html
JOB TIME   : 101.67 s

nbd:
 (1/1) Host_RHEL.m8.u3.product_av.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_speed: PASS (180.26 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-12T21.58-9a87521/results.html
JOB TIME   : 182.82 s

**Comment by zhencliu** [comment]
gluster direct:
 (1/1) Host_RHEL.m8.u3.product_av.gluster_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_mirror_speed.q35: PASS (140.04 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-13T11.49-0da51b6/results.html
JOB TIME   : 143.50 s

hi @YongxueHong @ngu-niny , can you please help to review the patch? Thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM

**Comment by ngu-niny** [comment]
Test PASS:

 (11/12) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.blockdev_mirror_speed:  PASS (152.15 s)
 (12/12) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_mirror_speed:  PASS (137.26 s)

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
