### PR TITLE
qemu.cfg.qemu_img: Config update

### PR DESCRIPTION
**Pull request by FengYang**
Signed-off-by: Feng Yang <fyang@redhat.com>

### CODE REVIEW

**Comment by FengYang** [comment]
id : 1205078

**Comment by spcui** [comment]
LTGM,
Acked-by: @spcui

**Comment by xutian** [comment]
LGTM,

Acked-by:  Xu Tian <xutian@redhat.com>

**Comment by FengYang** [comment]
Thanks @spcui  and @xutian

**Pull request merged**
