### PR TITLE
hotplug_unplug_during_io_repeat:improve test steps

### PR DESCRIPTION
**Pull request by qingwangrh**
Add cleaning and umount operation for Linux guest
Reduce the number of loop to improve test efficiency.

ID:2052

### CODE REVIEW

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=hotplug_unplug_during_io_repeat.default --guestname=Win2019,RHEL.9.4.0 --firmware=default_bios --clone=no 


(1/2) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hotplug_unplug_during_io_repeat.q35: STARTED
 (1/2) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hotplug_unplug_during_io_repeat.q35: PASS (2547.17 s)
 (2/2) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.hotplug_unplug_during_io_repeat.q35: STARTED
 (2/2) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.hotplug_unplug_during_io_repeat.q35: PASS (2134.65 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by qingwangrh** [comment]
@XueqiangWei @zhenyzha @peixiu Please help to review ,thanks.

**Comment by XueqiangWei** [comment]
Tested rhel guest and windows guest with edk2, all passed.

 (1/2) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hotplug_unplug_during_io_repeat.q35: STARTED
 (1/2) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hotplug_unplug_during_io_repeat.q35: PASS (2595.85 s)
 (2/2) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.hotplug_unplug_during_io_repeat.q35: STARTED
 (2/2) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.hotplug_unplug_during_io_repeat.q35: PASS (2659.52 s)

**Review by XueqiangWei — APPROVED** [review]
LGTM,
Acked-by: xuwei@redhat.com

**Comment by zhenyzha** [comment]
(1/1) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.hotplug_unplug_during_io_repeat.arm64-pci: PASS (2582.68 s)

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Review by zhenyzha — APPROVED** [review]

**Comment by XueqiangWei** [comment]
@peixiu Could you please help take a look at ti? Many thanks.

**Comment by peixiu** [comment]
Looks good to me! Thanks @qingwangrh 

Acked-by: Peixiu Hou phou@redhat.com

**Review by peixiu — APPROVED** [review]

**Pull request merged**
