### PR TITLE
Add virtio serial file transfer basic test.

### PR DESCRIPTION
**Pull request by FengYang**
ID : 1185183

Signed-off-by: Feng Yang <fyang@redhat.com>

### CODE REVIEW

**Comment by FengYang** [comment]
[root@hp-z800-01 qemu]# ../../../../../../tools/scan_results.py 
Test                                                                                                                            Status     Seconds  Info
----                                                                                                                            ------     -------  ----
        (Result file: /usr/code/autotest/client/results/default/status)
virt.qemu.Host_RHEL.7.0.qcow2.virtio_blk.smp2.virtio_net.RHEL.7.0.x86_64.io-github-autotest-qemu.virtio_serial_file_transfer    GOOD       30       completed successfully
----

**Comment by ypu** [comment]
Hi @FengYang can you rebase this pullreq ?

**Comment by ypu** [comment]
related pullreq:

https://github.com/autotest/virt-test/pull/2002

**Comment by ypu** [comment]
LGTM

Acked-by: Yiqiao Pu <ypu@redhat.com>

**Comment by ypu** [comment]
Thanks @FengYang will merge it.

**Pull request merged**
