### PR TITLE
passthrough_fc_with_lun_device:fix no children issue and improve test

### PR DESCRIPTION
**Pull request by qingwangrh**
1.Fix issue if host have no device included in multipath
2.Increase partition size
BZ:2070446,2070443
Signed-off-by: qingwangrh <qinwang@redhat.com>

### CODE REVIEW

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=passthrough_fc_with_lun_device --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=Win2019 --driveformat=virtio_scsi --nicmodel=virtio_net --imageformat=qcow2 --machines=q35  --customsparams="vm_mem_limit = 12G\nimage_aio=threads" --clone=no

 (1/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_block.q35: STARTED
\ (1/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_block.q35: PASS (105.55 s)
 (2/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_generic.q35: STARTED
/ (2/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_generic.q35: PASS (105.06 s)

**Comment by qingwangrh** [comment]
@YongxueHong @XueqiangWei Please help to review,thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by YongxueHong** [comment]
Hi, @qingwangrh 
Your code looks good to me.
And there is a bit of suggestion if we could give a more clear explanation for
the second point`(Increase partition size)` why to do that.
Thanks.

**Comment by XueqiangWei** [comment]
(1/2) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_block.q35: STARTED
- (1/2) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_block.q35: PASS (140.97 s)
 (2/2) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_generic.q35: STARTED
| (2/2) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.passthrough_fc_with_lun_device.with_scsi_generic.q35: PASS (138.39 s)

LGTM,
Acked-by: xuwei@redhat.com

**Pull request merged**
