### PR TITLE
generic.test: update netperf download link and configuration

### PR DESCRIPTION
**Pull request by xutian**
Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
ID: 1304314

**Comment by MiriamDeng** [comment]
After run the following job virt.qemu.smp_2.4096m.repeat1.run_test.Host_RHEL.7.2.qcow2.virtio_scsi.up.virtio_net.RHEL.7.1.ppc64le.io-github-autotest-qemu.netperf.host_guest.From its debug log - I get a different value of netperf_download_link
-netperf_download_link = http://fileshare.englab.nay.redhat.com/pub/section2/kvmauto/test_tools/netperf-2.6.0.tar.bz2 but not the value that the script points out.
Any issues please let me know,thanks a lot.

**Comment by xutian** [comment]
@MiriamDeng  this is a fix for upstream guys who want to run netperf test.  For internal, we subtest-internal.cfg to overwrite this configuration to speed up.

thanks your comments.

**Comment by MiriamDeng** [comment]
Hi,@xutian,
    Remove the internal subtest-internal.cfg and re-test this patch.
    Acked-by:MiriamDeng

**Comment by xutian** [comment]
thanks @MiriamDeng .

**Pull request merged**
