### PR TITLE
IPU: update the installation command of leapp tool

### PR DESCRIPTION
**Pull request by MiriamDeng**
ID：1389
Update installation command of leapp from compose.

### CODE REVIEW

**Comment by MiriamDeng** [comment]
@fbq815 @PaulYuuu could you help to review it when you are free ? Thank U All !

**Comment by fbq815** [comment]
s390x:
JOB ID     : 6d0998f54c87d186f5be6bb7920010a65bafcec6
JOB LOG    : /root/avocado/job-results/job-2023-10-23T03.32-6d0998f/job.log
 (1/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.s390x.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.s390-virtio: STARTED
 (1/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.s390x.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.s390-virtio: PASS (516.41 s)
 (2/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.s390x.io-github-autotest-qemu.in_place_upgrade.without_rhsm_rhel8_to_rhel9.compose_install.s390-virtio: STARTED
 (2/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.s390x.io-github-autotest-qemu.in_place_upgrade.without_rhsm_rhel8_to_rhel9.compose_install.s390-virtio: FAIL: Failed to do yum update in the vm : Shell command failed: 'yum-config-manager --enable rhel-8-for-s390x-appstream-rpms --enable rhel-8-for-s390x-baseos-rpms'    (status: 1,    output: 'Updating Subscription Management repositories.\nUnable to read consume... (38.93 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2023-10-23T03.32-6d0998f/results.html
JOB TIME   : 557.04 s

seems we still have some repo issue

**Comment by fbq815** [comment]
Test result on s390x:
JOB ID     : eda5de6cfe3e0ebfc7b44c1bec7028d067ff17c7
JOB LOG    : /root/avocado/job-results/job-2023-10-24T05.46-eda5de6/job.log
 (1/2) Host_RHEL.m8.u9.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.s390-virtio: STARTED
 (1/2) Host_RHEL.m8.u9.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.s390-virtio: PASS (587.58 s)
 (2/2) Host_RHEL.m8.u9.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.in_place_upgrade_legacy.without_rhsm_rhel7_to_rhel8.compose_install.s390-virtio: STARTED
 (2/2) Host_RHEL.m8.u9.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.in_place_upgrade_legacy.without_rhsm_rhel7_to_rhel8.compose_install.s390-virtio: PASS (1059.24 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2023-10-24T05.46-eda5de6/results.html
JOB TIME   : 1648.58 s

seems the test could PASS from RHEL7 to RHEL8, waiting for the update from RHEL8 to RHEL9

**Comment by MiriamDeng** [comment]
Please have this kar patch before you run test for 8to9 @fbq815, thank you !
Kar Patch's ID:1217

**Review by PaulYuuu — APPROVED** [review]

**Comment by fbq815** [comment]
Test result:
JOB ID     : b0813971c6bcbe414d07538e5b14e2bea7cedd83
JOB LOG    : /root/avocado/job-results/job-2023-10-30T04.17-b081397/job.log
(1/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.s390x.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.s390-virtio: STARTED
(1/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.s390x.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.s390-virtio: PASS (518.68 s)
(2/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.s390x.io-github-autotest-qemu.in_place_upgrade.without_rhsm_rhel8_to_rhel9.compose_install.s390-virtio: STARTED
(2/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.s390x.io-github-autotest-qemu.in_place_upgrade.without_rhsm_rhel8_to_rhel9.compose_install.s390-virtio: PASS (634.65 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2023-10-30T04.17-b081397/results.html
JOB TIME   : 1155.12 s

LGTM

**Pull request merged**
