### PR TITLE
qemu.tests: Add new case of live snapshot during installation.

### PR DESCRIPTION
**Pull request by CongLi**
Signed-off-by: Cong Li <coli@redhat.com>

id: 1321837

### CODE REVIEW

**Comment by CongLi** [comment]
15:04:28 INFO | PASS 1-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.live_snapshot.with_installation

**Comment by suqinhuang** [comment]
what's the pri of this case, can we create an separate cfg file to it if it's low pri

**Comment by CongLi** [comment]
@suqinhuang 

It's high prio.

**Comment by PyLearner** [comment]
HI @CongLi , i runed and it failed ,i paste the error log to the bug.

**Comment by CongLi** [comment]
Thanks @PyLearner .

There is a dependency PR under avocado-vt and some internal cfgs.

**Comment by PyLearner** [comment]
smp_4.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.live_snapshot.with_installation: /
PASS (3396.27 s)

Acked-by : Meng Yang meyang@redhat.com

**Comment by vivianQizhu** [comment]
Acked-by :  Qianqian Zhu qizhu@redhat.com

**Comment by CongLi** [comment]
Thanks @vivianQizhu and @PyLearner , merged.

**Comment by xutian** [comment]
@CongLi  last try except looks useless.

**Pull request merged**
