### PR TITLE
hotplug_mem: Update to support run rhel6 guest

### PR DESCRIPTION
**Pull request by huangyum**
ID: 1630663
Signed-off-by: Yumei Huang <yuhuang@redhat.com>

### CODE REVIEW

**Comment by huangyum** [comment]
@vivianQizhu Yeah, a few bugs were reported recently on rhel6 guest. I don't think it's worth to test from rhel6.0, and no more modification needed, current case works fine.

**Comment by jingzhao84** [comment]
Acked-by: jinzhao@redhat.com

**Comment by jingzhao84** [comment]
@huangyum could you please paste your test result here?
Others is ok for me

**Comment by huangyum** [comment]
Host_RHEL.m7.u6.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.6.10.x86_64.io-github-autotest-qemu.hotplug_memory.after.guest_reboot.hotplug.backend_ram.policy_bind.two: PASS (166.51 s)

**Comment by jingzhao84** [comment]
acked-by jinzhao@redhat.com

**Comment by jingzhao84** [comment]
@MiriamDeng any comments from ppc part?

**Comment by luckyh** [comment]
@MiriamDeng is it work for ppc?

**Comment by huangyum** [comment]
Works well on ppc host.
Host_RHEL.m7.u6.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.6.10.ppc64.io-github-autotest-qemu.hotplug_memory.after.guest_reboot.hotplug.backend_ram.policy_bind.two: PASS (231.25 s)

**Pull request merged**
