### PR TITLE
numa_consistency: include only numa nodes with memory and cpus

### PR DESCRIPTION
**Pull request by mcasquer**
numa_consistency: include only numa nodes with memory and cpus

Changes the numa nodes list to include only the nodes with
memory and cpus assigned

ID: 2070405
Signed-off-by: mcasquer <mcasquer@redhat.com>

### CODE REVIEW

**Comment by mcasquer** [comment]
(1/1) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.numa.numa_consistency.q35: PASS (75.93 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by mcasquer** [comment]
@yanan-fu could you please review this PR? Thanks!

**Comment by yanan-fu** [comment]
@mcasquer Could you shorten the commit title? 
Refer:  https://avocado-framework.readthedocs.io/en/96.0/guides/contributor/chapters/styleguides.html

**Comment by mcasquer** [comment]
> @mcasquer Could you shorten the commit title? Refer: https://avocado-framework.readthedocs.io/en/96.0/guides/contributor/chapters/styleguides.html

Done!

**Comment by yanan-fu** [comment]
@MiriamDeng  Could you help review with ppc side ? Thanks!

**Comment by MiriamDeng** [comment]
LGTM
 (2/2) Host_RHEL.m8.u7.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.ppc64le.io-github-autotest-qemu.numa.numa_consistency: STARTED
| (2/2) Host_RHEL.m8.u7.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.ppc64le.io-github-autotest-qemu.numa.numa_consistency: PASS (120.88 s)

**Review by yanan-fu — APPROVED** [review]
Ack

**Pull request merged**
