### PR TITLE
single_driver_install: install viomem driver

### PR DESCRIPTION
**Pull request by menli820**
Install viomem driver in a preinstalled windows guest.
ID: 1974

Signed-off-by: menli <menli@redhat.com>

### CODE REVIEW

**Comment by menli820** [comment]
No available package to test, lack some necessary information, so change the patch status to draft first.

**Comment by menli820** [comment]
python3 ConfigTest.py --testcase=single_driver_install.with_viomem  --guestname=Win2022 --firmware=ovmf  --driveformat=virtio_blk --platform=x86_64 --customsparams="cdrom_virtio = isos/windows/virtio-win-prewhql-0.1-258.iso"  --machines=q35 --clone=no


(1/1) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.single_driver_install.with_viomem.virtio_win_iso_media.q35: STARTED
 (1/1) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.single_driver_install.with_viomem.virtio_win_iso_media.q35: PASS (368.55 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by menli820** [comment]
@mcasquer please help review this patch  to help  confirm the necessary paramaters are right in the cfg to boot a vm with a virtio-mem device on windows side, thanks

**Comment by mcasquer** [comment]
@menli820 
Test passed on RHEL 9.5 but failed in RHEL 10
**RHEL 9.5**
```
 (1/1) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.single_driver_install.with_viomem.virtio_win_iso_media.q35: STARTED
 (1/1) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.single_driver_install.with_viomem.virtio_win_iso_media.q35: PASS (691.93 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```
**RHEL 10**
```
 (1/1) Host_RHEL.m10.u0.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.single_driver_install.with_viomem.virtio_win_iso_media.q35: STARTED
 (1/1) Host_RHEL.m10.u0.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.single_driver_install.with_viomem.virtio_win_iso_media.q35: FAIL: The expected driver version is '100.95.104.25600', but found '['100.95.104.25700']' (742.20 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```
The code looks good to me

**Comment by menli820** [comment]
> @menli820 Test passed on RHEL 9.5 but failed in RHEL 10 **RHEL 9.5**
> 
> ```
>  (1/1) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.single_driver_install.with_viomem.virtio_win_iso_media.q35: STARTED
>  (1/1) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.single_driver_install.with_viomem.virtio_win_iso_media.q35: PASS (691.93 s)
> RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
> ```
> 
> **RHEL 10**
> 
> ```
>  (1/1) Host_RHEL.m10.u0.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.single_driver_install.with_viomem.virtio_win_iso_media.q35: STARTED
>  (1/1) Host_RHEL.m10.u0.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.single_driver_install.with_viomem.virtio_win_iso_media.q35: FAIL: The expected driver version is '100.95.104.25600', but found '['100.95.104.25700']' (742.20 s)
> RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
> ```
> 
> The code looks good to me

Thanks @mcasquer  I will check the error on rhel10 manually.

**Comment by menli820** [comment]
The lastest result:

```
 (1/2) Host_RHEL.m9.u4.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: STARTED
 (1/2) Host_RHEL.m9.u4.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (811.72 s)
 (2/2) Host_RHEL.m9.u4.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.single_driver_install.with_viomem.virtio_win_iso_media.q35: STARTED
 (2/2) Host_RHEL.m9.u4.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.single_driver_install.with_viomem.virtio_win_iso_media.q35: PASS (364.97 s)
```
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2024-07-11T04.28-40f8cd0/results.html
JOB TIME   : 1178.46 s


```
 (1/2) Host_RHEL.m9.u4.qcow2.virtio_blk.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: STARTED
 (1/2) Host_RHEL.m9.u4.qcow2.virtio_blk.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (1228.46 s)
 (2/2) Host_RHEL.m9.u4.qcow2.virtio_blk.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.single_driver_install.with_viomem.virtio_win_iso_media: STARTED
 (2/2) Host_RHEL.m9.u4.qcow2.virtio_blk.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.single_driver_install.with_viomem.virtio_win_iso_media: PASS (349.46 s)
```
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2024-07-11T05.01-6767338/results.html
JOB TIME   : 1579.79 s

**Comment by menli820** [comment]
@mcasquer could you please help to review it again based on auto bug comment?

**Review by mcasquer — APPROVED** [review]
LGTM

**Comment by menli820** [comment]
@PaulYuuu  could you please help to review it when you free, thanks

**Comment by leidwang** [comment]
Hi @PaulYuuu Would you please help to review this PR, thanks!

**Review by PaulYuuu — APPROVED** [review]

**Pull request merged**
