### PR TITLE
qemu_guest_agent: Use 'mkdir -p' to avoid file exists issue

### PR DESCRIPTION
**Pull request by yanan-fu**
id: 1917804
Signed-off-by: Yanan Fu <yfu@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
@6-dehan  Could you help review ? Thanks!

**Comment by 6-dehan** [comment]
ok, sure.

**Comment by 6-dehan** [comment]
LGTM

Acked by Dehan Meng demeng@redhat.com

**Comment by yanan-fu** [comment]
@vivianQizhu  Could you help review ? Thanks!

**Review by vivianQizhu — APPROVED** [review]

**Pull request merged**
