### PR TITLE
seabios_bootmenu_prompt: Add new case for more than 10 boot devices

### PR DESCRIPTION
**Pull request by ybduan**
Checking boot menu prompts with more than 10 available boot devices

ID: 1743551

Signed-off-by: ybduan <yduan@redhat.com>

### CODE REVIEW

**Comment by ybduan** [comment]
(1/1) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.seabios_bootmenu_prompt: PASS (79.26 s)

**Comment by CongLi** [comment]
@luckyh could you please help review this PR which is an urgent request ?

Thanks.

**Comment by CongLi** [comment]
@XueqiangWei please help review this PR, thanks.

**Comment by XueqiangWei** [comment]
tested with pc and q35, all failed.
(1/2) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.8.x86_64.io-github-autotest-qemu.seabios_bootmenu_prompt: FAIL: Not all boot devices are listed in the boot menu (41.91 s)
 (2/2) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.seabios_bootmenu_prompt: FAIL: Not all boot devices are listed in the boot menu (42.73 s)
 (1/1) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.seabios_bootmenu_prompt.q35: FAIL: Not all boot devices are listed in the boot menu (42.47 s)
 (1/1) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.8.x86_64.io-github-autotest-qemu.seabios_bootmenu_prompt.q35: FAIL: Not all boot devices are listed in the boot menu (41.96 s)

**Comment by ybduan** [comment]
(1/1) Host_RHEL.m8.ux.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.1.x86_64.io-github-autotest-qemu.seabios_bootmenu_prompt: PASS (61.33 s)

**Comment by XueqiangWei** [comment]
tested with pc and q35 on rhel 8.1 fast train, all passed.
 (1/2) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.seabios_bootmenu_prompt: PASS (213.22 s)
 (2/2) Host_RHEL.m8.u1.raw.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.seabios_bootmenu_prompt.q35: PASS (201.34 s)

LGTM,
Acked-by xuwei@redhat.com

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
