### PR TITLE
Use dhcpcd command on rhel 10

### PR DESCRIPTION
**Pull request by yanglei-rh**
Due to dhclient command has been deleted on rhel 10, so using dhcpcd command to replace it

### CODE REVIEW

**Comment by yanglei-rh** [comment]
Hi @PaulYuuu Could you please help me review this patch? Thanks a lot.

**Review by PaulYuuu — APPROVED** [review]

**Comment by yanglei-rh** [comment]
Hi @fbq815 @zhenyzha Could you please help review this patch? Thanks a lot.

**Comment by zhenyzha** [comment]
LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

```
 (1/4) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.aarch64.page_64k.io-github-autotest-qemu.mac_change.down_change.arm64-pci: STARTED
 (1/4) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.aarch64.page_64k.io-github-autotest-qemu.mac_change.down_change.arm64-pci: PASS (195.54 s)
 (2/4) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.aarch64.page_64k.io-github-autotest-qemu.mac_change.arm64-pci: STARTED
 (2/4) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.aarch64.page_64k.io-github-autotest-qemu.mac_change.arm64-pci: PASS (209.27 s)
 (3/4) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.aarch64.page_64k.io-github-autotest-qemu.mac_change.ctrl_mac_addr_off.down_change.arm64-pci: STARTED
 (3/4) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.aarch64.page_64k.io-github-autotest-qemu.mac_change.ctrl_mac_addr_off.down_change.arm64-pci: PASS (197.62 s)
 (4/4) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.aarch64.page_64k.io-github-autotest-qemu.mac_change.ctrl_mac_addr_off.arm64-pci: STARTED
 (4/4) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.aarch64.page_64k.io-github-autotest-qemu.mac_change.ctrl_mac_addr_off.arm64-pci: PASS (152.32 s)
```

**Review by fbq815 — APPROVED** [review]
LGTM:
PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Pull request merged**
