### PR TITLE
viorng_in_use: correct re pattern

### PR DESCRIPTION
**Pull request by ybduan**
ID: 1618557

Signed-off-by: ybduan <yduan@redhat.com>

### CODE REVIEW

**Comment by ybduan** [comment]
(1/1) Host_RHEL.m7.u6.virtio_rng.rng_random.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.io-github-autotest-qemu.viorng_in_use.with_stop_continue.during_bg_test: PASS (153.01 s)

**Comment by ybduan** [comment]
Could you please help review this PR? Thanks! @lijinlijin

**Comment by lijinlijin** [comment]
(1/1) Host_RHEL.m7.u5.virtio_rng.rng_random.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.4.x86_64.io-github-autotest-qemu.viorng_in_use.with_stop_continue.during_bg_test: PASS (140.99 s)

Acked-by: Li Jin lijin@redhat.com

**Comment by vivianQizhu** [comment]
@ybduan Would you describe the issue and why fix it this way in commit log? Thanks.

**Pull request merged**
