### PR TITLE
hello_world:fix bytes string compares error

### PR DESCRIPTION
**Pull request by qingwangrh**
The bytes and string can not auto-convert in
python3. It needs to add decode() to get the string.

ID:2249

### CODE REVIEW

**Comment by qingwangrh** [comment]
(1/1) Host_RHEL.m9.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.hello_world.q35: STARTED
 (1/1) Host_RHEL.m9.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.hello_world.q35: PASS (80.14 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by qingwangrh** [comment]
@zhencliu @zhenyzha Please help to review. Thanks.

**Comment by zhencliu** [comment]
hi @qingwangrh , is line77 the only change(decode added) in your patch? I cannot see the modified part(difference) from this patch as if it is a pretty new py file.

If that's the only change, LGTM

**Comment by qingwangrh** [comment]
> hi @qingwangrh , is line77 the only change(decode added) in your patch? I cannot see the modified part(difference) from this patch as if it is a pretty new py file.
> 
> If that's the only change, LGTM

updated.

**Review by zhencliu — APPROVED** [review]

**Review by zhenyzha — APPROVED** [review]
Pass on the aarch64 platform
LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Pull request merged**
