### PR TITLE
numa:Corrected CPU-NUMA association version restrictions

### PR DESCRIPTION
**Pull request by zhenyzha**
Corrected CPU-NUMA association version restrictions on arm

ID: 2101650
Signed-off-by: zhenyzha <zhenyzha@redhat.com>

### CODE REVIEW

**Comment by zhenyzha** [comment]
(1/2) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.balloon_memhp.backend_ram.arm64-pci: STARTED
 (1/2) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.balloon_memhp.backend_ram.arm64-pci: PASS (141.83 s)
 (2/2) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.balloon_memhp.backend_ram.arm64-pci: STARTED
 (2/2) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.balloon_memhp.backend_ram.arm64-pci: PASS (146.24 s)


@PaulYuuu Sorry for the inconvenience.
Could you pls help review when you are free. thanks.

**Comment by PaulYuuu** [comment]
> (1/2) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.balloon_memhp.backend_ram.arm64-pci: STARTED (1/2) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.balloon_memhp.backend_ram.arm64-pci: PASS (141.83 s) (2/2) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.balloon_memhp.backend_ram.arm64-pci: STARTED (2/2) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.balloon_memhp.backend_ram.arm64-pci: PASS (146.24 s)
> 
> @PaulYuuu Sorry for the inconvenience. Could you pls help review when you are free. thanks.

What's the status on RHEL8

**Comment by zhenyzha** [comment]
> What's the status on RHEL8
@PaulYuuu Hello 
RHEL8 does not need such allocations, since cpu topology descriptions on arm started on RHEL9.
Below is the test result on RHEL8.

```
 (1/3) Host_RHEL.m8.u7.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.aarch64.io-github-autotest-qemu.balloon_memhp.backend_ram.arm64-pci: STARTED
 (1/3) Host_RHEL.m8.u7.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.aarch64.io-github-autotest-qemu.balloon_memhp.backend_ram.arm64-pci: PASS (163.57 s)
 (2/3) Host_RHEL.m8.u7.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.aarch64.io-github-autotest-qemu.balloon_memhp.backend_file.arm64-pci: STARTED
 (2/3) Host_RHEL.m8.u7.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.aarch64.io-github-autotest-qemu.balloon_memhp.backend_file.arm64-pci: PASS (165.06 s)
 (3/3) Host_RHEL.m8.u7.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.aarch64.io-github-autotest-qemu.migration_with_numa.arm64-pci: STARTED
 (3/3) Host_RHEL.m8.u7.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.aarch64.io-github-autotest-qemu.migration_with_numa.arm64-pci: PASS (100.08 s)
```

**Comment by zhenyzha** [comment]
@PaulYuuu Could you pls help review again when you are free. thanks.

**Review by PaulYuuu — APPROVED** [review]
ACK

**Pull request merged**
