### PR TITLE
qemu.tests: Add qemu_disk_img_commit test case

### PR DESCRIPTION
**Pull request by Chenditang**
test cache mode for qemu-img commit

### CODE REVIEW

**Comment by Chenditang** [comment]
The test result onlibvirt-1.2.13 fc20.x86_64

\# ./run -t qemu --no-downloads -k --tests qemu_disk_img.commit
SETUP: PASS (0.30 s)
DATA DIR: /var/lib/virt_test
DEBUG LOG: /root/autotest/client/tests/virt/logs/run-2015-06-24-08.57.23/debug.log
TESTS: 6
(1/6) type_specific.io-github-autotest-qemu.qemu_disk_img.commit.default: PASS (185.66 s)
(2/6) type_specific.io-github-autotest-qemu.qemu_disk_img.commit.cache_mode.none: PASS (193.56 s)
(3/6) type_specific.io-github-autotest-qemu.qemu_disk_img.commit.cache_mode.wirteback: PASS (180.48 s)
(4/6) type_specific.io-github-autotest-qemu.qemu_disk_img.commit.cache_mode.unsafe: PASS (183.20 s)
(5/6) type_specific.io-github-autotest-qemu.qemu_disk_img.commit.cache_mode.directsync: PASS (183.12 s)
(6/6) type_specific.io-github-autotest-qemu.qemu_disk_img.commit.cache_mode.writethrough: PASS (195.85 s)
TOTAL TIME: 1128.45 s (18:48)
TESTS PASSED: 6
TESTS FAILED: 0
SUCCESS RATE: 100.00 %

**Comment by xutian** [comment]
LGTM,

Acked-by: Xu Tian <xutian@redhat.com>

**Comment by xiagao** [comment]
Acked-by: <xiagao@redhat.com>

**Comment by xutian** [comment]
Merged. thanks @Chenditang  and @xiagao

**Pull request merged**
