### PR TITLE
tp-qemu: netstress_kill_guest.driver: disable windows test.

### PR DESCRIPTION
**Pull request by CongSmile**
We have not implemented the windows support yet, disable the
test for windows, will make windows support in the future.

Signed-off-by: Cong Li <coli@redhat.com>

### CODE REVIEW

**Comment by CongSmile** [comment]
id: 1204652

**Comment by xutian** [comment]
LGTM,

Acked-by: Xu Tian <xutian@redhat.com>

**Comment by suqinhuang** [comment]
LGTM
Acked-by: Suqin Huang

**Comment by xutian** [comment]
thanks @CongSmile  @suqinhuang

**Pull request merged**
