### PR TITLE
blockdev_stream_with_ioerror:80M file is too large for 100M backend space

### PR DESCRIPTION
**Pull request by aliang123**
For rhel7.9, dd 80M file is too large for this test, so change
the dd file size to 60M

Signed-off-by: Aihua Liang <aliang@redhat.com>
id:2079666

### CODE REVIEW

**Comment by aliang123** [comment]
(1/5) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.x86_64.io-github-autotest-qemu.blockdev_stream_with_ioerror: PASS (97.13 s)
(2/5) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.x86_64.io-github-autotest-qemu.blockdev_stream_with_ioerror.q35: PASS (91.11 s)
(3/5) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_with_ioerror.q35: PASS (81.94 s)
(4/5) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.x86_64.io-github-autotest-qemu.blockdev_stream_with_ioerror.q35: PASS (84.46 s)
(5/5) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.x86_64.io-github-autotest-qemu.blockdev_stream_with_ioerror: PASS (77.84 s)

**Comment by aliang123** [comment]
@zhencliu @MiriamDeng, please help to review, thanks.

**Comment by zhencliu** [comment]
LGTM

**Comment by MiriamDeng** [comment]
(4/6) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_stream_with_ioerror: PASS (147.52 s)
ACK

**Pull request merged**
