### PR TITLE
qemu.tests: Unify usage of "source_image" in block_stream and drive_mirror related cases.

### PR DESCRIPTION
**Pull request by CongLi**
Signed-off-by: Cong Li <coli@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
Why do this change, it's a image tag not tag list. so Nack it.

**Comment by CongLi** [comment]
In block_stream case, it get "source_images" from the param.
./qemu/tests/block_stream.py:34:    tag = params.get("source_images", "image1")
But in the cfg, it uses "source_image".
./qemu/tests/cfg/block_stream.cfg:9:    source_image = image1

Need unify the param usage.

**Comment by xutian** [comment]
if so, I think here should be tag = params.objects("source_images")[0] , not params.get("source_images")

**Comment by xutian** [comment]
checked code, may place used source_images, I think source_image looks more good, because tag only used for a image not a image lists.

**Comment by CongLi** [comment]
@xutian 

That's fair enough.
And code has been updated, could you help review it again?

Thanks.

**Comment by xutian** [comment]
Looks good to me,  could you show me your test results?

**Comment by CongLi** [comment]
11:36:06 INFO | PASS 01-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.block_stream.simple_test.start_stream
11:45:49 INFO | PASS 02-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.block_stream.simple_test.set_speed
11:55:33 INFO | PASS 03-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.block_stream.simple_test.reset_speed
11:55:49 INFO | PASS 04-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.block_stream.simple_test.cancel_sync
11:56:05 INFO | PASS 05-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.block_stream.simple_test.cancel_async
11:56:37 INFO | PASS 06-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.block_stream.simple_test.query
12:00:55 INFO | PASS 07-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.block_stream.when_reboot
12:05:10 INFO | PASS 08-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.block_stream.drop_backingfile
12:08:09 INFO | PASS 09-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.block_stream.check_backingfile
12:14:17 INFO | PASS 10-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.block_stream.with_stress

**Comment by xutian** [comment]
fine, thanks @CongLi . Merged

**Pull request merged**
