### PR TITLE
qemu_disk: create snapshot by specifying backing_file using ssh/https driver(cfg file)

### PR DESCRIPTION
**Pull request by PyLearner**
ID: 1374200, 1374201

Signed-off-by: Meng Yang meyang@redhat.com

### CODE REVIEW

**Comment by huangyum** [comment]
SKIP 1-smp_16.4096m.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.3.x86_64.providers.qemu_disk_img_snapshot.protocol_ssh -> ParamNotFound: Mandatory parameter 'guest_file_name' is missing. Check your cfg files for typos/mistakes

SKIP 2-smp_16.4096m.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.3.x86_64.providers.qemu_disk_img_snapshot.protocol_https -> ParamNotFound: Mandatory parameter 'guest_file_name' is missing. Check your cfg files for typos/mistakes

**Comment by suqinhuang** [comment]
id?

**Comment by suqinhuang** [comment]
where is the .py file?

**Comment by PyLearner** [comment]
@suqinhuang , hi , @pingl2016 talked to me and we will use the same cfg file ,so just send the cfg first, i will send another patch to contain the .py file, sorry for the inconvinience.

**Pull request closed without merging**
