### PR TITLE
blockdev_stream_multiple_blocks: add stream test with several blocks

### PR DESCRIPTION
**Pull request by zhencliu**
Do block-stream for at least two images in parallel

Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1882251

### CODE REVIEW

**Comment by zhencliu** [comment]
local fs:
 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_multiple_blocks: PASS (269.87 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-26T02.03-9270d61/results.html
JOB TIME   : 275.43 s

gluster direct:
 (1/1) Host_RHEL.m8.u3.product_av.gluster_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_multiple_blocks: PASS (439.71 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2020-09-27T08.25-e7b2648/results.html
JOB TIME   : 443.58 s

iscsi direct:
 (1/1) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_multiple_blocks: PASS (279.31 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-26T20.35-dca4214/results.html
JOB TIME   : 285.03 s

nbd:
 (1/1) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_multiple_blocks: PASS (311.42 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-26T20.44-93efa0f/results.html
JOB TIME   : 317.26 s

hi @YongxueHong @aliang123 , can you please help to review this patch? Thanks.
it deps on #2418, so please ignore the CI check error

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_multiple_blocks.q35: PASS (487.04 s)

Acked-by: Aihua Liang <aliang@redhat.com>

**Comment by zhencliu** [comment]
hi @ngu-niny  , can you please help to review this patch? Thanks.
it deps on #2418, so please ignore the CI check error

**Comment by ngu-niny** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.blockdev_stream_multiple_blocks:  PASS (382.26 s)

Acked-by: Nini Gu <ngu@redhat.com>

**Review by YongxueHong — APPROVED** [review]
LGTM

**Pull request merged**
