### PR TITLE
qemu_guest_agent.py: Fix some minor issues

### PR DESCRIPTION
**Pull request by 6-dehan**
1. change the parameter name 'qga_ver_guest' for windows
2. add condition 'main_qga_ver >= 102' for windows

ID: 1988830
Signed-off-by: Dehan Meng <demeng@redhat.com>

### CODE REVIEW

**Comment by 6-dehan** [comment]
@YongxueHong Could you please have a reivew ? 
(1/3) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.x86_64.1.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_guest_info.q35: PASS (42.53 s)
(2/3) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.x86_64.1.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_virtio_device.default.q35: PASS (42.53 s)
(3/3) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.x86_64.1.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_virtio_device.with_input_device.q35: PASS (42.53 s)

**Comment by YongxueHong** [comment]
Hi @6-dehan 
Could you explain the reason to fix those errors in the commit message?
Thanks.

**Comment by 6-dehan** [comment]
> Hi @6-dehan
> Could you explain the reason to fix those errors in the commit message?
> Thanks.
@YongxueHong you mean explain more in commit info right?

**Comment by YongxueHong** [comment]
> > Hi @6-dehan
> > Could you explain the reason to fix those errors in the commit message?
> > Thanks.
> > @YongxueHong you mean explain more in commit info right?

Yes, your explanation may be less detailed, so hope you could provide more info for reviewers to let them know of this issue well and your patch.

**Comment by 6-dehan** [comment]
> > > Hi @6-dehan
> > > Could you explain the reason to fix those errors in the commit message?
> > > Thanks.
> > > @YongxueHong you mean explain more in commit info right?
> 
> Yes, your explanation may be less detailed, so hope you could provide more info for reviewers to let them know of this issue well and your patch.
okay got it.

**Comment by 6-dehan** [comment]
> > > > Hi @6-dehan
> > > > Could you explain the reason to fix those errors in the commit message?
> > > > Thanks.
> > > > @YongxueHong you mean explain more in commit info right?
> > 
> > 
> > Yes, your explanation may be less detailed, so hope you could provide more info for reviewers to let them know of this issue well and your patch.
> > okay got it.

okay, done with it, you can have a re-review with that.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
