### PR TITLE
Add  vhost-vdpa read-only and detect_zeroes options test

### PR DESCRIPTION
**Pull request by qingwangrh**
ID:1918,1919 

Signed-off-by: qingwangrh <qinwang@redhat.com>

### CODE REVIEW

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=block_vhost_vdpa_test.with_read_only --iothread_scheme=roundrobin --nr_iothreads=2 --guestname=Win2019 --firmware=default_bios  --clone=no --driveformat=virtio_blk,virtio_scsi

python ConfigTest.py --testcase=block_vhost_vdpa_test.with_detect_zeroes --iothread_scheme=roundrobin --nr_iothreads=2 --guestname=Win2019 --firmware=default_bios  --clone=no --driveformat=virtio_blk,virtio_scsi

**Comment by qingwangrh** [comment]
@XueqiangWei @peixiu Please help to review.thanks.

**Comment by peixiu** [comment]
(1/8) Host_RHEL.m9.u4.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: STARTED
 (1/8) Host_RHEL.m9.u4.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (1131.83 s)
 (2/8) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: STARTED
 (2/8) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (1148.43 s)
 (3/8) Host_RHEL.m9.u4.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_detect_zeroes.with_discard_unmap.q35: STARTED
 (3/8) Host_RHEL.m9.u4.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_detect_zeroes.with_discard_unmap.q35: PASS (153.93 s)
 (4/8) Host_RHEL.m9.u4.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_detect_zeroes.with_discard_ignore.q35: STARTED
 (4/8) Host_RHEL.m9.u4.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_detect_zeroes.with_discard_ignore.q35: PASS (162.37 s)
 (5/8) Host_RHEL.m9.u4.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: STARTED
 (5/8) Host_RHEL.m9.u4.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: PASS (142.53 s)
 (6/8) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_detect_zeroes.with_discard_unmap.q35: STARTED
 (6/8) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_detect_zeroes.with_discard_unmap.q35: PASS (143.84 s)
 (7/8) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_detect_zeroes.with_discard_ignore.q35: STARTED
 (7/8) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_detect_zeroes.with_discard_ignore.q35: PASS (161.47 s)
 (8/8) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: STARTED
 (8/8) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: PASS (140.75 s)

**Review by peixiu — APPROVED** [review]
LGTM, thanks~

Acked-by: Peixiu Hou phou@redhat.com

**Comment by XueqiangWei** [comment]
Separate two IDs with ","  I.E. ID:1918, 1919

**Comment by XueqiangWei** [comment]
Tested with seabios and ovmf, all passed.

 (1/2) Host_RHEL.m9.u4.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: STARTED
 (1/2) Host_RHEL.m9.u4.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: PASS (120.01 s)
 (2/2) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: STARTED
 (2/2) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: PASS (111.59 s)

 (1/2) Host_RHEL.m9.u4.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: STARTED
 (1/2) Host_RHEL.m9.u4.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: PASS (99.68 s)
 (2/2) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: STARTED
 (2/2) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: PASS (97.75 s)

 (1/2) Host_RHEL.m9.u4.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.10.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: STARTED
 (1/2) Host_RHEL.m9.u4.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.10.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: PASS (99.60 s)
 (2/2) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: STARTED
 (2/2) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_read_only.q35: PASS (95.72 s)

**Review by XueqiangWei — APPROVED** [review]
LGTM,
Acked-by: xuwei@redhat.com

**Pull request merged**
