### PR TITLE
timerdevice:modify host cpu checking way

### PR DESCRIPTION
**Pull request by maxujun**
ID:1922121
Signed-off-by: Xujun Ma <xuma@redhat.com>

### CODE REVIEW

**Comment by maxujun** [comment]
@MiriamDeng @YanhuiMa Could you help review？

**Comment by YanhuiMa** [comment]
LGTM
(1/1) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.myprovider.timerdevice.measure_time_jump.q35: PASS (65.85 s)

**Comment by MiriamDeng** [comment]
Could you please to check it ?
# git am 2654.patch
Applying: timerdevice:modify host cpu checking way
error: patch failed: qemu/tests/timerdevice_time_jump_check.py:30
error: qemu/tests/timerdevice_time_jump_check.py: patch does not apply
Patch failed at 0001 timerdevice:modify host cpu checking way
hint: Use 'git am --show-current-patch=diff' to see the failed patch
When you have resolved this problem, run "git am --continue".

**Comment by maxujun** [comment]
> 
> 
> Could you please to check it ?
> git am 2654.patch
> Applying: timerdevice:modify host cpu checking way
> error: patch failed: qemu/tests/timerdevice_time_jump_check.py:30
> error: qemu/tests/timerdevice_time_jump_check.py: patch does not apply
> Patch failed at 0001 timerdevice:modify host cpu checking way
> hint: Use 'git am --show-current-patch=diff' to see the failed patch
> When you have resolved this problem, run "git am --continue".

Updated

**Comment by maxujun** [comment]
@yanan-fu Hi,Could you help review this patch?

**Comment by yanan-fu** [comment]
Ack

**Comment by yanan-fu** [comment]
@MiriamDeng  Do you have any more comments ? Thanks!

**Comment by MiriamDeng** [comment]
LGTM
 (1/1) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.timerdevice.measure_time_jump: PASS (93.57 s)

**Comment by yanan-fu** [comment]
Thanks all!

**Pull request merged**
