### PR TITLE
commit_with_backing: add rate_limit support to commit test

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>
ID: 1909761, 1909763, 1909764

### CODE REVIEW

**Comment by XueqiangWei** [comment]
depends on avocado-framework/avocado-vt/pull/2869

**Comment by XueqiangWei** [comment]
(1/4) Host_RHEL.m8.u4.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.commit_with_backing: PASS (195.11 s)
 (2/4) Host_RHEL.m8.u4.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.commit_with_backing.rate_limit.with_rate_limit_0: PASS (184.37 s)
 (3/4) Host_RHEL.m8.u4.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.commit_with_backing.rate_limit.with_rate_limit_4611686018427387400: PASS (174.60 s)
 (4/4) Host_RHEL.m8.u4.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.commit_with_backing.rate_limit.with_rate_limit_9223372036854775295: PASS (171.98 s)

 (1/8) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.commit_with_backing: PASS (160.17 s)
 (2/8) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.commit_with_backing.rate_limit.with_rate_limit_0: PASS (151.02 s)
 (3/8) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.commit_with_backing.rate_limit.with_rate_limit_4611686018427387400: PASS (154.12 s)
 (4/8) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.commit_with_backing.rate_limit.with_rate_limit_9223372036854775295: PASS (154.53 s)
 (5/8) Host_RHEL.m8.u4.product_av.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.commit_with_backing: PASS (207.02 s)
 (6/8) Host_RHEL.m8.u4.product_av.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.commit_with_backing.rate_limit.with_rate_limit_0: PASS (194.62 s)
 (7/8) Host_RHEL.m8.u4.product_av.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.commit_with_backing.rate_limit.with_rate_limit_4611686018427387400: PASS (165.45 s)
 (8/8) Host_RHEL.m8.u4.product_av.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.commit_with_backing.rate_limit.with_rate_limit_9223372036854775295: PASS (169.16 s)

 (1/4) Host_RHEL.m8.u4.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.commit_with_backing.q35: PASS (431.99 s)
 (2/4) Host_RHEL.m8.u4.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.commit_with_backing.rate_limit.with_rate_limit_0.q35: PASS (401.88 s)
 (3/4) Host_RHEL.m8.u4.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.commit_with_backing.rate_limit.with_rate_limit_4611686018427387400.q35: PASS (393.51 s)
 (4/4) Host_RHEL.m8.u4.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.commit_with_backing.rate_limit.with_rate_limit_9223372036854775295.q35: PASS (393.67 s)

**Comment by XueqiangWei** [comment]
@zhencliu Please help review it. Many thanks.

**Comment by zhencliu** [comment]
LGTM
wait till vt patch patch merged

**Pull request merged**
