### PR TITLE
remote_image_snapshot: Support curl storage backend

### PR DESCRIPTION
**Pull request by zhencliu**
ID: 1851661

### CODE REVIEW

**Comment by zhencliu** [comment]
(1/1) Host_RHEL.m8.u3.product_av.curl.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_snapshot.to_local: PASS (111.74 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-06-15T23.00-4f8ea0e/results.html
JOB TIME   : 116.16 s

**Comment by zhencliu** [comment]
(1/3) Host_RHEL.m8.u3.product_av.curl.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_snapshot.to_local: PASS (102.02 s)
 (2/3) Host_RHEL.m8.u3.product_av.curl.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_readonly_storage.boot_with_readonly_image: PASS (288.68 s)
 (3/3) Host_RHEL.m8.u3.product_av.curl.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_readonly_storage.access_with_qemu_info: PASS (7.62 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by zhencliu** [comment]
hi @zixi-chen, can you please help to review it, thanks.

**Comment by zhencliu** [comment]
hi @YongxueHong , can you please help on code review, thanks.

**Comment by zixi-chen** [comment]
(3/3) Host_RHEL.m8.u3.product_av.curl.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_snapshot.to_local: PASS (93.87 s)
 
LGTM
ACK

**Pull request merged**
