### PR TITLE
qemu.tests.watchdog: Typo fix

### PR DESCRIPTION
**Pull request by FengYang**
Signed-off-by: Feng Yang <fyang@redhat.com>

### CODE REVIEW

**Comment by FengYang** [comment]
id : 1127512

**Comment by spcui** [comment]
Acked-by: @spcui

**Comment by ypu** [comment]
@FengYang Hi seems we also need set the parameters for the watchdog to let it can be triggered and last during the operations like migration finished.

**Comment by spcui** [comment]
Agreed @ypu 's comment, still need the parameter to trigger when migration finished.
But this patch is fixed the typo error, so acked it.

**Comment by ypu** [comment]
OK will have an other pullreqs to handling the parameter update. So thanks @FengYang and @spcui will merge it.

**Pull request merged**
