### PR TITLE
blockdev_commit: add nbd support for live commit

### PR DESCRIPTION
**Pull request by aliang123**
Add backend:nbd support for live commit
    
Signed-off-by: Aihua Liang <aliang@redhat.com>
id:2068346

### CODE REVIEW

**Comment by aliang123** [comment]
(01/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_hotunplug.q35: PASS (48.25 s)
(02/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_powerdown.q35: PASS (95.26 s)
(03/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_filter_node_name.q35: PASS (52.70 s)
(04/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_specify_node.base_same_with_top.q35: PASS (55.24 s)
 (05/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_specify_node.parent_as_top_child_as_base.q35: PASS (52.75 s)
(06/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_auto_readonly.q35: PASS (44.71 s)
(07/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_stop_cont.q35: PASS (53.13 s)
(08/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_top.q35: PASS (64.77 s)
(09/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_non_existed_node.none_existed_base.q35: PASS (52.48 s)
(10/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_non_existed_node.none_existed_top.q35: PASS (42.34 s)
(11/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_forbidden_actions.q35: PASS (50.88 s)
(12/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_general_operation.all_enable.q35: PASS (51.05 s)
(13/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_general_operation.all_disable.q35: PASS (51.05 s)
(14/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_general_operation.finalize_enable_dismiss_disable.q35: PASS (49.52 s)
(15/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_install.q35: PASS (594.44 s)
(16/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_throttle.q35: PASS (69.17 s)
(17/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_cor.q35: PASS (49.35 s)
(18/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_with_ioerror.q35: PASS (91.61 s)
(19/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit.q35: PASS (65.12 s)
(20/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit.multi_data_disks.q35: PASS (90.77 s)
(21/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_speed_limit.negative_int.q35: PASS (48.47 s)
(22/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_speed_limit.small_int.q35: PASS (49.04 s)
(23/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_speed_limit.random_int.q35: PASS (49.22 s)
(24/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_speed_limit.large_int.q35: PASS (48.49 s)
(25/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_speed_limit.charactor.q35: PASS (47.87 s)
(26/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_reboot.q35: PASS (79.25 s)
(27/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_backing_file.q35: PASS (44.18 s)
(28/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_query_named_block_nodes.q35: PASS (63.55 s)
(29/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_standby.q35: PASS (104.51 s)
(30/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_stress.q35: PASS (74.74 s)
(31/31) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_fio.q35: ERROR: Test reported status but did not finish (2431.90 s)

Block_commiit_fio error not related to backend:nbd.

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit.multi_data_disks.q35: PASS (89.40 s)

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m9.u1.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_commit_top.q35: PASS (64.82 s)

**Comment by aliang123** [comment]
@zhencliu @MiriamDeng or @ngu-niny, please help to review, thanks.

**Comment by zhencliu** [comment]
LGTM

**Comment by MiriamDeng** [comment]
Tests started on ppc and will update it later.

**Comment by MiriamDeng** [comment]
Run the relevant test on ppc, tests pased. 
LGTM

**Pull request merged**
