### PR TITLE
blockdev_inc_backup_disabled_persistent_bitmap: Disabled bitmap testing

### PR DESCRIPTION
**Pull request by zhencliu**
Disabled bitmap keeps disabled after reload

Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1907291

### CODE REVIEW

**Comment by zhencliu** [comment]
local fs:
 (1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_disabled_persistent_bitmap: PASS (113.17 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-14T04.33-f7a516a/results.html
JOB TIME   : 115.81 s
iscsi-direct + virtio-blk:
 (1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_disabled_persistent_bitmap: PASS (138.16 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-14T04.45-27d9f4d/results.html
JOB TIME   : 140.79 s

ceph:
(1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_disabled_persistent_bitmap: PASS (184.03 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-14T04.52-ae4e2b1/results.html
JOB TIME   : 187.01 s

**Comment by zhencliu** [comment]
hi @YongxueHong @ngu-niny ,  can you please help to review this patch? Thanks.
it deps on #2547

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by ngu-niny** [comment]
LGTM and test PASS:

PASS 23-Host_RHEL.m8.u4.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_disabled_persistent_bitmap
PASS 39-Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_disabled_persistent_bitmap

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
