### PR TITLE
Fix download failure about wget type

### PR DESCRIPTION
**Pull request by yiqianwei**
Change progress type to bar because
invalid progress type 'none' in qemu-kvm-9.1

ID: 2900

### CODE REVIEW

**Comment by yiqianwei** [comment]
Test results:
 (1/1) Host_RHEL.mxx.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.xx.0.x86_64.io-github-autotest-qemu.stress_kernel_compile.multi_guests.q35:  PASS (2059.89 s)

**Comment by yiqianwei** [comment]
@yanan-fu , Could you help to review this patch? thanks

**Comment by yanan-fu** [comment]
What's the current status with the issue we discussed in https://github.com/autotest/tp-qemu/pull/4119#issuecomment-2255110854

**Comment by yiqianwei** [comment]
> What's the current status with the issue we discussed in [#4119 (comment)](https://github.com/autotest/tp-qemu/pull/4119#issuecomment-2255110854)

Yes, but it 's invalid progress type for none now 
 wget https://www.kernel.org/pub/linux/kernel/v2.6/linux-2.6.32.tar.bz2 --progress=none
wget: --progress: Invalid progress type ‘none’.

**Comment by yanan-fu** [comment]
> > What's the current status with the issue we discussed in [#4119 (comment)](https://github.com/autotest/tp-qemu/pull/4119#issuecomment-2255110854)
> 
> Yes, but it 's invalid progress type for none now wget xxx --progress=none wget: --progress: Invalid progress type ‘none’.

This issue has nothing to do with qemu-kvm version, it is the wget version in different release.
Please check the capabilities for different releases.

**Comment by yiqianwei** [comment]
> > > What's the current status with the issue we discussed in [#4119 (comment)](https://github.com/autotest/tp-qemu/pull/4119#issuecomment-2255110854)
> > 
> > 
> > Yes, but it 's invalid progress type for none now wget xxx --progress=none wget: --progress: Invalid progress type ‘none’.
> 
> This issue has nothing to do with qemu-kvm version, it is the wget version in different release. Please check the capabilities for different releases.

@yanan-fu , I was try  wget version in host as follows:

wget-1.24.5-1.el10.x86_64 
wget-1.24.5-5.el10.x86_64
wget-1.21.1-8.el9_4.x86_64

Prompt the same error:
wget https://www.kernel.org/pub/linux/kernel/v2.6/linux-2.6.32.tar.bz2 --progress=none
wget: --progress: Invalid progress type ‘none’.

**Comment by yiqianwei** [comment]
@yanan-fu ,  I have changed progress type to bar.
Test results:
For rhel10-beta:
 (1/1) Host_RHEL.m10.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.stress_kernel_compile.multi_guests.q35: PASS (369.08 s) 

For rhel10:
 (1/1) Host_RHEL.m10.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.stress_kernel_compile.multi_guests.q35: PASS (785.68 s)

**Comment by yanan-fu** [comment]
> @yanan-fu , I have changed progress type to bar. Test results: For rhel10-beta: (1/1) Host_RHEL.m10.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.stress_kernel_compile.multi_guests.q35: PASS (369.08 s)
> 
> For rhel10: (1/1) Host_RHEL.m10.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.stress_kernel_compile.multi_guests.q35: PASS (785.68 s)

It can not explain the status of https://github.com/autotest/tp-qemu/pull/4119.
If we handle the status in https://github.com/autotest/tp-qemu/pull/4119 as a temporary status in the middle of a release and will not hit it again with the latest version of the same release,  it sound a bit make sense.

For the latest RHEL10 version,  wget use `bar` as the default progress,  it is not necessary to write it down.
Suggest revert the change of `--progress=***` which be introduced with https://github.com/autotest/tp-qemu/pull/4119.

**Comment by yiqianwei** [comment]
Test results:
For rhel10-beta:
(1/1) Host_RHEL.m10.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.stress_kernel_compile.multi_guests.q35: PASS (326.19 s)

For rhel10:
(1/1) Host_RHEL.m10.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.stress_kernel_compile.multi_guests.q35: PASS (372.36 s)

**Review by yanan-fu — APPROVED** [review]
Ack

**Pull request merged**
