### PR TITLE
blockdev_mirror_ready_vm_down:block job cancelled after vm down

### PR DESCRIPTION
**Pull request by aliang123**
id:2034462

### CODE REVIEW

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_mirror_ready_vm_down.q35: PASS (51.12 s)

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_mirror_ready_vm_down.q35: PASS (50.61 s)

**Comment by aliang123** [comment]
qemu6.0.0:
  (1/1) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_mirror_ready_vm_down.q35: PASS (39.21 s)

**Comment by aliang123** [comment]
@ngu-niny @zhencliu, please help to review, thanks.

**Comment by zhencliu** [comment]
LGTM

**Comment by ngu-niny** [comment]
Test PASS on both old and new qemu versions:

(1/1) Host_RHEL.m9.u0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.blockdev_mirror_ready_vm_down.s390-virtio: PASS (28.75 s)
(1/1) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_mirror_ready_vm_down: PASS (116.36 s)

Acked-by: Nini Gu ngu@redhat.com

**Pull request merged**
