### PR TITLE
add bockdev full mirror test

### PR DESCRIPTION
**Pull request by xutian**
ID: 1787985

Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
JOB ID     : ddb3dc1cb6fa173f0496db1e11af7e559046efa2
JOB LOG    : /root/avocado/job-results/job-2019-12-24T22.40-ddb3dc1/job.log
 (1/2) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_full_mirror.simple_test.dst_cluster_size_2M.with_data_plane: PASS (112.12 s)
 (2/2) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_full_mirror.simple_test.dst_cluster_size_2M: PASS (52.11 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 165.71 s
JOB HTML   : /root/avocado/job-results/job-2019-12-24T22.40-ddb3dc1/results.html

**Comment by xutian** [comment]
@aliang123 @ngu-niny  would you like to help review this patch, thanks

**Comment by aliang123** [comment]
Have tested, lack steps of:
  5). boot guest with target disk
  6). verify data md5sum in data disk

**Comment by xutian** [comment]
@aliang123  updated call verify_target_disk() to verify target disk data.

**Comment by aliang123** [comment]
(1/8) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_full_mirror.simple_test.with_data_plane.q35: PASS (105.61 s)
 (2/8) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_full_mirror.simple_test.q35: PASS (104.85 s)
 (3/8) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_full_mirror.simple_test.dst_cluster_size_512.with_data_plane.q35: PASS (109.72 s)
 (4/8) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_full_mirror.simple_test.dst_cluster_size_512.q35: PASS (108.29 s)
 (5/8) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_full_mirror.simple_test.dst_cluster_size_2M.with_data_plane.q35: PASS (109.46 s)
 (6/8) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_full_mirror.simple_test.dst_cluster_size_2M.q35: PASS (109.47 s)
 (7/8) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_full_mirror.simple_test.dst_random_cluster_size.with_data_plane.q35: PASS (105.82 s)
 (8/8) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_full_mirror.simple_test.dst_random_cluster_size.q35: PASS (102.95 s)

Acked-by: Aihua Liang <aliang@redhat.com>

@ngu-niny , please help to review on ppcle64.

**Comment by ngu-niny** [comment]
Test PASS:

(1/8) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_full_mirror.simple_test.with_data_plane: PASS (211.41 s)
 (2/8) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_full_mirror.simple_test: PASS (419.09 s)
 (3/8) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_full_mirror.simple_test.dst_cluster_size_512.with_data_plane: PASS (350.33 s)
 (4/8) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_full_mirror.simple_test.dst_cluster_size_512: PASS (428.29 s)
 (5/8) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_full_mirror.simple_test.dst_cluster_size_2M.with_data_plane: PASS (403.56 s)
 (6/8) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_full_mirror.simple_test.dst_cluster_size_2M: PASS (398.63 s)

 (1/4) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_full_mirror.simple_test.dst_cluster_size_512.with_data_plane: PASS (392.57 s)
 (2/4) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_full_mirror.simple_test.dst_cluster_size_512: PASS (750.61 s)
 (3/4) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_full_mirror.simple_test.dst_random_cluster_size.with_data_plane: PASS (596.79 s)
 (4/4) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_full_mirror.simple_test.dst_random_cluster_size: PASS (416.94 s)

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
