### PR TITLE
block_hotplug_check:fix miss pci_id_pattern in cfg

### PR DESCRIPTION
**Pull request by qingwangrh**
fix pci_id_pattern is miss for windows

ID:1708

### CODE REVIEW

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=block_hotplug_check --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=Win2019 --driveformat=virtio_blk --imageformat=qcow2 --machines=i440fx --customsparams="vm_mem_limit = 12G\nimage_aio=native\ncd_format=ide"  --firmware=default_bios --netdst=virbr0 --clone=no 

(1/1) Host_RHEL.m9.u5.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_hotplug_check: STARTED
 (1/1) Host_RHEL.m9.u5.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_hotplug_check: PASS (945.89 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by qingwangrh** [comment]
@XueqiangWei @menli820 Please help to review, thanks.

**Comment by menli820** [comment]
LGTM

 (1/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: STARTED
 (1/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (874.31 s)
 (2/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.block_hotplug_check.q35: STARTED
 (2/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.block_hotplug_check.q35: PASS (904.52 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2024-05-17T17.07-117a782/results.html

**Review by menli820 — APPROVED** [review]

**Comment by XueqiangWei** [comment]
(1/1) Host_RHEL.m9.u4.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.block_hotplug_check.q35: PASS (981.86 s)

**Review by XueqiangWei — APPROVED** [review]
LGTM,
Acked-by: xuwei@redhat.com

**Pull request merged**
