### PR TITLE
qemu.test: migration codes updated in framework, so update import statement

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei xuwei@redhat.com

### CODE REVIEW

**Comment by XueqiangWei** [comment]
depends on #727

**Comment by XueqiangWei** [comment]
ID 1342353

**Comment by suqinhuang** [comment]
https://github.com/avocado-framework/avocado-vt/pull/727

**Comment by dinghuiqing** [comment]
ACK.

Test test cases: with_file_transfer, early_boot_vm, after_login_vm, set_downtime, all cases are passed.
GOOD virt.case3.remote_nfs.raw.virtio_scsi.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.multi_host.migrate_multi_host.early_boot_vm.vhost_src_yes_dst_yes.mig_online.tcp	virt.case3.remote_nfs.raw.virtio_scsi.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.multi_host.migrate_multi_host.early_boot_vm.vhost_src_yes_dst_yes.mig_online.tcp	timestamp=1477557664	localtime=Oct 27 08:41:04	completed successfully

GOOD	virt.case5.remote_nfs.raw.virtio_scsi.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.multi_host.migrate_multi_host.after_login_vm.vhost_src_yes_dst_yes.mig_online.tcp	virt.case5.remote_nfs.raw.virtio_scsi.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.multi_host.migrate_multi_host.after_login_vm.vhost_src_yes_dst_yes.mig_online.tcp	timestamp=1477557806	localtime=Oct 27 08:43:26	completed successfully

GOOD	virt.case2.remote_nfs.raw.virtio_scsi.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.multi_host.migrate_multi_host.with_file_transfer.vhost_src_yes_dst_yes.mig_online.tcp	virt.case2.remote_nfs.raw.virtio_scsi.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.multi_host.migrate_multi_host.with_file_transfer.vhost_src_yes_dst_yes.mig_online.tcp	timestamp=1477557471	localtime=Oct 27 08:37:51	completed successfully

	GOOD	virt.case2.remote_nfs.raw.virtio_scsi.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.multi_host.migrate_multi_host.set_downtime.after_migrate.vhost_src_yes_dst_yes.mig_online.tcp	virt.case2.remote_nfs.raw.virtio_scsi.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.multi_host.migrate_multi_host.set_downtime.after_migrate.vhost_src_yes_dst_yes.mig_online.tcp	timestamp=1477559059	localtime=Oct 27 09:04:19	completed successfully

**Comment by CongLi** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by CongLi** [comment]
Thanks @XueqiangWei @dinghuiqing .

**Pull request merged**
