### PR TITLE
qemu_img_convert:sync host data after convert

### PR DESCRIPTION
**Pull request by maxujun**
ID:1673

Signed-off-by: Xujun Ma <xuma@redhat.com>

### CODE REVIEW

**Comment by maxujun** [comment]
@XueqiangWei @PaulYuuu Could you help review?

**Comment by XueqiangWei** [comment]
@maxujun Please help add your results.

**Comment by XueqiangWei** [comment]
@hellohellenmao Could you please take a look at it? Thanks.

**Comment by hellohellenmao** [comment]
@maxujun Could I know why we need this fix here?

**Comment by maxujun** [comment]
> @maxujun Could I know why we need this fix here?
Guest with raw and lusk disk failed to boot with converted image on large memory host. Need to sync converted image to host disk first.

**Comment by hellohellenmao** [comment]
> > @maxujun Could I know why we need this fix here?
> > Guest with raw and lusk disk failed to boot with converted image on large memory host. Need to sync converted image to host disk first.

Is there a bug/jira issue for the issue here? Could you please share me at first? Thanks.

**Comment by maxujun** [comment]
> @maxujun Could I know why we need this fix here?
Guest with raw and lusk disk failed to boot with converted image on large memory host. Need to sync converted image to host disk first.

> @maxujun Please help add your results.

 (1/8) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: STARTED
 (1/8) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads:  PASS (1323.67 s)
 (2/8) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.qemu_img_convert_with_target_is_zero.to_raw: STARTED
 (2/8) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.qemu_img_convert_with_target_is_zero.to_raw:  PASS (296.18 s)
 (3/8) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.qemu_img_convert_with_rate_limit.to_raw.rate_limit.with_rate_limit_0: STARTED
 (3/8) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.qemu_img_convert_with_rate_limit.to_raw.rate_limit.with_rate_limit_0:  PASS (261.66 s)
 (4/8) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.qemu_img_convert_with_rate_limit.to_raw.rate_limit.with_rate_limit_4611686018427387400: STARTED
 (4/8) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.qemu_img_convert_with_rate_limit.to_raw.rate_limit.with_rate_limit_4611686018427387400:  PASS (258.25 s)
 (5/8) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.qemu_img_convert_with_rate_limit.to_raw.rate_limit.with_rate_limit_9223372036854775295: STARTED
 (5/8) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.qemu_img_convert_with_rate_limit.to_raw.rate_limit.with_rate_limit_9223372036854775295:  PASS (249.51 s)
 (6/8) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.qemu_img_convert_with_rate_limit.to_luks.rate_limit.with_rate_limit_0: STARTED
 (6/8) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.qemu_img_convert_with_rate_limit.to_luks.rate_limit.with_rate_limit_0:  PASS (340.26 s)
 (7/8) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.qemu_img_convert_with_rate_limit.to_luks.rate_limit.with_rate_limit_4611686018427387400: STARTED
 (7/8) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.qemu_img_convert_with_rate_limit.to_luks.rate_limit.with_rate_limit_4611686018427387400:  PASS (343.59 s)
 (8/8) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.qemu_img_convert_with_rate_limit.to_luks.rate_limit.with_rate_limit_9223372036854775295: STARTED
 (8/8) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.qemu_img_convert_with_rate_limit.to_luks.rate_limit.with_rate_limit_9223372036854775295:  PASS (340.77 s)

**Comment by maxujun** [comment]
> > > @maxujun Could I know why we need this fix here?
> > > Guest with raw and lusk disk failed to boot with converted image on large memory host. Need to sync converted image to host disk first.
> 
> Is there a bug/jira issue for the issue here? Could you please share me at first? Thanks.

ID:1673

**Review by PaulYuuu — APPROVED** [review]

**Comment by XueqiangWei** [comment]
Thank you all.

**Pull request merged**
