### PR TITLE
win_irq_check: Add a case disable msi by setting vectors

### PR DESCRIPTION
**Pull request by peixiu**
Add disable MSI test case by vectors for vioscsi, viostor, netkvm drivers.

id: 1566853
Signed-off-by: Peixiu Hou <phou@redhat.com>

### CODE REVIEW

**Comment by peixiu** [comment]
(01/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.with_balloon.q35: PASS (24.52 s)
 (02/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.with_viorng.q35: PASS (23.77 s)
 (03/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.with_viostor.q35: PASS (24.22 s)
 (04/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.with_vioscsi.q35: PASS (24.09 s)
 (05/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.with_vioserial.q35: PASS (23.89 s)
 (06/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.with_netkvm.q35: PASS (23.61 s)
 (07/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.with_vioinput.device_mouse.q35: PASS (23.64 s)
 (08/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.with_vioinput.device_keyboard.q35: PASS (23.81 s)
 (09/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.with_vioinput.device_tablet.q35: PASS (23.67 s)
 (10/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.msi_disable_fguest.with_viostor.q35: PASS (40.13 s)
 (11/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.msi_disable_fguest.with_vioscsi.q35: PASS (39.25 s)
 (12/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.msi_disable_fguest.with_vioserial.q35: PASS (39.01 s)
 (13/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.msi_disable_fguest.with_netkvm.q35: PASS (39.33 s)
 (14/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.msi_disable_fguest.with_vioinput.device_mouse.q35: PASS (39.46 s)
 (15/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.msi_disable_fguest.with_vioinput.device_keyboard.q35: PASS (39.54 s)
 (16/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.msi_disable_fguest.with_vioinput.device_tablet.q35: PASS (38.90 s)
 (17/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.msi_disable_fhost.with_viostor.q35: PASS (24.42 s)
 (18/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.msi_disable_fhost.with_vioscsi.q35: PASS (23.91 s)
 (19/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.msi_disable_fhost.with_netkvm.q35: PASS (23.65 s)

**Comment by peixiu** [comment]
new cases job are 17, 18, 19, tested on win7-32 guest, all passed.

(17/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.msi_disable_fhost.with_viostor.q35: PASS (24.42 s)
(18/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.msi_disable_fhost.with_vioscsi.q35: PASS (23.91 s)
(19/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.msi_disable_fhost.with_netkvm.q35: PASS (23.65 s)

**Comment by peixiu** [comment]
@kimi1978wy @YongxueHong Could you help to review this patch?
Thanks a lot~

**Comment by YongxueHong** [comment]
how about change the case name like:
```
    variants:
        - @default:
        - msi_disable_fguest:
            variants:
                - by_registry:
                    no with_balloon, with_viorng
                    msi_cmd = "reg add "HKLM\System\CurrentControlSet\Enum\%s\Device Parameters\Interrupt Management\MessageSignaledInterruptProperties" /v MSISupported /d %d /t REG_DWORD /f"
                - by_vectors:
                    only with_vioscsi, with_viostor, with_netkvm
                    vectors = 0
                    with_viostor:
                        virtio_blk:
                            blk_extra_params_image1 += ",vectors=${vectors}"
                        blk_extra_params_stg += ",vectors=${vectors}"
                    with_vioscsi:
                        bus_extra_params_image1 = "vectors=${vectors}"
                        bus_extra_params_stg = "vectors=${vectors}"
```

**Comment by peixiu** [comment]
@YongxueHong Thanks, has updated~ please help review it again, thanks~

**Comment by peixiu** [comment]
with latest code:
 (10/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.msi_disable.by_registry.with_viostor.q35: PASS (42.33 s)
 (11/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.msi_disable.by_registry.with_vioscsi.q35: PASS (39.94 s)
 (12/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.msi_disable.by_registry.with_vioserial.q35: PASS (39.81 s)
 (13/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.msi_disable.by_registry.with_netkvm.q35: PASS (38.85 s)
 (14/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.msi_disable.by_registry.with_vioinput.device_mouse.q35: PASS (38.92 s)
 (15/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.msi_disable.by_registry.with_vioinput.device_keyboard.q35: PASS (38.85 s)
 (16/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.msi_disable.by_registry.with_vioinput.device_tablet.q35: PASS (39.51 s)
 (17/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.msi_disable.by_vectors.with_viostor.q35: PASS (24.36 s)
 (18/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.msi_disable.by_vectors.with_vioscsi.q35: PASS (24.14 s)
 (19/19) Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.win_irq_check.msi_disable.by_vectors.with_netkvm.q35: PASS (23.63 s)

**Comment by kimi1978wy** [comment]
LGTM
Acked by: Yu Wang <wyu@redhat.com>

**Comment by YongxueHong** [comment]
Better to update the commit title:
e.g:
`win_irq_check: Add a case disable msi by setting vectors`

thanks.

**Pull request merged**
