### PR TITLE
hv_tlbflush/trim_support_test:use qemu version to limit the cases

### PR DESCRIPTION
**Pull request by leidwang**
Signed-off-by: Leidong Wang <leidwang@redhat.com>

ID:2006833

### CODE REVIEW

**Comment by leidwang** [comment]
@menli820 Could you help to review this patch? Thanks a lot.

**Comment by menli820** [comment]
Add @qingwangrh  for the  trim_support_test part , thanks

**Comment by menli820** [comment]
Add @qingwangrh  for the  trim_support_test part , thanks

**Comment by menli820** [comment]
LGTM

 (1/2) Host_RHEL.m8.u5.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.trim_support_test.q35: PASS (338.06 s)
 (2/2) Host_RHEL.m8.u5.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.trim_support_test.with_4k_disk.q35: PASS (342.84 s)

 (1/1) Host_RHEL.m8.u5.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.hv_tlbflush.q35: PASS (1138.06 s)

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=hv_tlbflush,trim_support_test --guestname=Win2019 --driveformat=virtio_blk --iothread_scheme=roundrobin --nr_iothreads=2 --machine=q35 --clone=no --customsparams="vm_mem_limit = 12G\ncd_format=ide\nimage_aio=threads" 

(1/3) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.hv_tlbflush.q35: PASS (504.94 s)
 (2/3) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.trim_support_test.q35: PASS (190.83 s)
 (3/3) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.trim_support_test.with_4k_disk.q35: PASS (200.72 s)

LGTM

**Comment by yanan-fu** [comment]
Thanks all!

**Pull request merged**
