### PR TITLE
qmp_command: add command "query-events", "device-list-properties" and "query-command-line-options".

### PR DESCRIPTION
**Pull request by CongLi**
Signed-off-by: Cong Li <coli@redhat.com>

id: 1348792, 1349739, 1349699

### CODE REVIEW

**Comment by CongLi** [comment]
13:58:29 INFO | PASS 1-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.qmp_command.qmp_query-events

**Comment by PyLearner** [comment]
Acked-by : Meng Yang meyang@redhat.com

**Comment by suqinhuang** [comment]
Acked-by: Suqin Huang

**Comment by xutian** [comment]
looks good to me, merged thanks @CongLi @PyLearner and @PyLearner

**Pull request merged**
