### PR TITLE
multi_disk:adjust image size

### PR DESCRIPTION
**Pull request by qingwangrh**
Adjust image size to support the latest XFS
due to it requiring the size to be greater than 300M

ID:2593

### CODE REVIEW

**Comment by qingwangrh** [comment]
Pass test
python ConfigTest.py --testcase=multi_disk.virtio_scsi_variants,multi_disk.all_drive_format_types,multi_disk.with_virtio_scsi_TMF --iothread_scheme=full:3 --nr_iothreads=2 --platform=x86_64 --guestname=RHEL.10.0 --driveformat=virtio_scsi,virtio_blk  --imageformat=raw --machines=q35 --customsparams="enable_vhostfd = no\nvm_mem_limit = 12G\nimage_aio=threads" --firmware=default_bios --netdst=virbr0 --clone=no

**Comment by qingwangrh** [comment]
@XueqiangWei @fbq815 Please help to review, thanks.

**Review by XueqiangWei — APPROVED** [review]
LGTM,
Acked-by: xuwei@redhat.com

**Comment by XueqiangWei** [comment]
@fbq815 Can you help take a look at it? Many thanks.

**Review by fbq815 — APPROVED** [review]
RESULTS    : PASS 5 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
LGTM on s390x

**Pull request merged**
