### PR TITLE
block_performance_test: improve sampling

### PR DESCRIPTION
**Pull request by qingwangrh**
ID:2047662,1930998
Improve sampling and add filter q35 for case

### CODE REVIEW

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=block_performance_test --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=RHEL.9.0.0 --driveformat=virtio_blk --nicmodel=virtio_net --imageformat=qcow2 --machines=i440fx,q35 --customsparams="vm_mem_limit = 12G\nimage_aio=threads" --clone=no

(1/2) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.block_performance_test.with_queue_size.q35: STARTED
| (1/2) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.block_performance_test.with_queue_size.q35: PASS (275.04 s)
 (2/2) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.block_performance_test.with_multi_queue.q35: STARTED
\ (2/2) Host_RHEL.m9.u0.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.block_performance_test.with_multi_queue.q35: PASS (275.51 s)

**Comment by qingwangrh** [comment]
@YongxueHong @zhenyzha Please help to review ,thanks.

**Comment by zhenyzha** [comment]
` (1/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.block_performance_test.with_queue_size.arm64-pci: STARTED                                                                                                   - (1/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.block_performance_test.with_queue_size.arm64-pci: PASS (337.11 s)                                                                                           (2/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.block_performance_test.with_multi_queue.arm64-pci: STARTED                                                                                                  - (2/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.block_performance_test.with_multi_queue.arm64-pci: PASS (328.17 s)  `

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Comment by YongxueHong** [comment]
Hi @peixiu 
Would you like to help review it?
Thanks.

**Comment by peixiu** [comment]
Tested with virtio-blk on Win2019 + seabios, and virtio-scsi on Win2022 + ovmf, all passed.
LGTM~

 (1/4) Host_RHEL.m.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: STARTED
- (1/4) Host_RHEL.m.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (1291.12 s)
 (2/4) Host_RHEL.m.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: STARTED
- (2/4) Host_RHEL.m.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (1169.22 s)
 (3/4) Host_RHEL.m.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_performance_test.with_queue_size.q35: STARTED
| (3/4) Host_RHEL.m.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_performance_test.with_queue_size.q35: PASS (501.80 s)
 (4/4) Host_RHEL.m.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_performance_test.with_multi_queue.q35: STARTED
| (4/4) Host_RHEL.m.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_performance_test.with_multi_queue.q35: PASS (468.13 s)


 (1/2) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.block_performance_test.with_queue_size.q35: STARTED
- (1/2) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.block_performance_test.with_queue_size.q35: PASS (569.58 s)
 (2/2) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.block_performance_test.with_multi_queue.q35: STARTED
- (2/2) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.block_performance_test.with_multi_queue.q35: PASS (512.00 s)

Acked-by: Peixiu Hou phou@redhat.com
Thanks~

**Comment by peixiu** [comment]
Tested with virtio-blk on Win2019 + seabios, and virtio-scsi on Win2022 + ovmf, all passed.
LGTM~

 (1/4) Host_RHEL.m.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: STARTED
- (1/4) Host_RHEL.m.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (1291.12 s)
 (2/4) Host_RHEL.m.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: STARTED
- (2/4) Host_RHEL.m.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (1169.22 s)
 (3/4) Host_RHEL.m.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_performance_test.with_queue_size.q35: STARTED
| (3/4) Host_RHEL.m.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_performance_test.with_queue_size.q35: PASS (501.80 s)
 (4/4) Host_RHEL.m.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_performance_test.with_multi_queue.q35: STARTED
| (4/4) Host_RHEL.m.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_performance_test.with_multi_queue.q35: PASS (468.13 s)


 (1/2) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.block_performance_test.with_queue_size.q35: STARTED
- (1/2) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.block_performance_test.with_queue_size.q35: PASS (569.58 s)
 (2/2) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.block_performance_test.with_multi_queue.q35: STARTED
- (2/2) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.block_performance_test.with_multi_queue.q35: PASS (512.00 s)

Acked-by: Peixiu Hou phou@redhat.com
Thanks~

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
