### PR TITLE
slof: Get multiple SOLF's contents

### PR DESCRIPTION
**Pull request by YongxueHong**
ID: 1684365
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by YongxueHong** [comment]
@wangxianxiang, help me review this patch, thanks.

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

**Comment by wangxianxian** [comment]
ACK

**Comment by YongxueHong** [comment]
Tanks all.

**Pull request merged**
