### PR TITLE
add blockdev incremental backup tests

### PR DESCRIPTION
**Pull request by xutian**
ID: 1804177,  1804180,  1804184, 1804192, 1804199, 1804206

### CODE REVIEW

**Comment by xutian** [comment]
@aliang123  @ngu-niny  would you help to review this patch.

**Comment by xutian** [comment]
JOB ID     : 253d7cfa2bc446a4d849375871e8491740449eb0
JOB LOG    : /root/avocado/job-results/job-2020-02-18T21.02-253d7cf/job.log
 (1/6) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_512: PASS (100.41 s)
 (2/6) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup: PASS (100.36 s)
 (3/6) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_disk_disk: PASS (173.14 s)
 (4/6) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_disk_disk.grouped_complete: PASS (114.69 s)
 (5/6) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_disk_disk.manual_complete: PASS (116.10 s)
 (6/6) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_disk_disk.manual_complete.grouped_complete: PASS (171.35 s)
RESULTS    : PASS 6 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 777.74 s
JOB HTML   : /root/avocado/job-results/job-2020-02-18T21.02-253d7cf/results.html

**Comment by xutian** [comment]
update cfg to support 2G granularity.

 (1/7) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_512: PASS (104.60 s)
 (2/7) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_2G: PASS (102.04 s)
 (3/7) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup: PASS (101.57 s)
 (4/7) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_disk_disk: PASS (113.87 s)
 (5/7) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_disk_disk.grouped_complete: PASS (170.21 s)
 (6/7) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_disk_disk.manual_complete: PASS (113.00 s)
 (7/7) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_disk_disk.manual_complete.grouped_complete: PASS (175.52 s)

**Comment by aliang123** [comment]
Hi, xutian, please update the case for completion mode.

**Comment by aliang123** [comment]
(10/13,11/13) failed for product bug.
(01/13) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_512.q35: PASS (104.53 s)
 (02/13) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_8K.q35: PASS (108.12 s)
 (03/13) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_16M.q35: PASS (108.85 s)
 (04/13) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_64M.q35: PASS (127.68 s)
 (05/13) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_2G.q35: PASS (112.01 s)
 (06/13) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.granularity_random.q35: PASS (1435.78 s)
 (07/13) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.q35: PASS (108.15 s)
 (08/13) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_disk_disk.q35: PASS (122.63 s)
 (09/13) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_disk_disk.grouped_complete.q35: PASS (127.69 s)
 (10/13) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_disk_disk.negative_test.q35: FAIL: MonitorSocketError('Could not receive data from monitor', ConnectionResetError(104, 'Connection reset by peer')) (238.95 s)
 (11/13) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_disk_disk.negative_test.grouped_complete.q35: FAIL: MonitorSocketError('Could not receive data from monitor', ConnectionResetError(104, 'Connection reset by peer')) (260.02 s)
 (12/13) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_disk_disk.manual_complete.q35: PASS (131.63 s)
 (13/13) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup.multi_disk_disk.manual_complete.grouped_complete.q35: PASS (128.30 s)

Acked-by: Aihua Liang <aliang@redhat.com>

**Comment by ngu-niny** [comment]
Test PASS on ppc, the failed cases are for product bug:

'03-Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup.granularity_512' Finshed 2020-02-24 06:31:31 2020-02-24 06:34:39 PASS 188.409016
'04-Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup.granularity_8K' Finshed 2020-02-24 06:34:39 2020-02-24 06:37:40 PASS 180.254373
'05-Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup.granularity_16M' Finshed 2020-02-24 06:37:40 2020-02-24 06:40:37 PASS 177.64013
'06-Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup.granularity_64M' Finshed 2020-02-24 06:40:38 2020-02-24 06:43:51 PASS 193.149943
'07-Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup.granularity_2G' Finshed 2020-02-24 06:43:51 2020-02-24 06:46:49 PASS 178.373655
'08-Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup.granularity_random' Finshed 2020-02-24 06:46:49 2020-02-24 07:15:34 PASS 1724.156337
'09-Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup' Finshed 2020-02-24 07:15:34 2020-02-24 07:18:34 PASS 180.143162
'10-Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup.multi_disk_disk' Finshed 2020-02-24 07:18:34 2020-02-24 07:22:11 PASS 216.601005
'11-Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup.multi_disk_disk.grouped_complete' Finshed 2020-02-24 07:22:11 2020-02-24 07:25:58 PASS 226.940654

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
