### PR TITLE
blockdev_stream_on_error_ignore: stream test with on-error:ignore

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1904389

### CODE REVIEW

**Comment by zhencliu** [comment]
local fs:
 (1/1) type_specific.io-github-autotest-qemu.blockdev_stream_on_error_ignore: PASS (101.69 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-08T21.46-384e86c/results.html
JOB TIME   : 103.71 s

iscsi direct + virtio-blk:
 (1/1) type_specific.io-github-autotest-qemu.blockdev_stream_on_error_ignore: PASS (131.83 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-08T13.04-a87ce26/results.html
JOB TIME   : 134.03 s

ceph:
 (1/1) type_specific.io-github-autotest-qemu.blockdev_stream_on_error_ignore: PASS (200.22 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-08T13.09-33e1f74/results.html
JOB TIME   : 202.51 s

nbd:
 (1/1) type_specific.io-github-autotest-qemu.blockdev_stream_on_error_ignore: PASS (258.55 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-08T01.11-bfa49c6/results.html
JOB TIME   : 260.37 s

**Comment by zhencliu** [comment]
hi @YongxueHong @ngu-niny , can you please help to review it? Thanks.
it deps on https://github.com/avocado-framework/avocado-vt/pull/2850

**Comment by zhencliu** [comment]
Talked with @YongxueHong , we will do the least modification for VT code, so move this patch to 'draft'
Sorry for that.

**Comment by zhencliu** [comment]
Workaround the emulated image creation issue, steps:
create emulated image with size = 2G
lv.resize(1G)
This can avoid more vt code change, and our test case also run without any issue.
Now it's ready for review, thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by zhencliu** [comment]
local fs:
 (1/1) type_specific.io-github-autotest-qemu.blockdev_stream_on_error_ignore: PASS (164.41 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-10T05.27-f0992c1/results.html
JOB TIME   : 166.22 s

nbd:
 (1/1) type_specific.io-github-autotest-qemu.blockdev_stream_on_error_ignore: PASS (144.46 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-10T05.47-1988802/results.html
JOB TIME   : 146.29 s

iscsi direct + virtio-blk:
 (1/1) type_specific.io-github-autotest-qemu.blockdev_stream_on_error_ignore: PASS (140.21 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-10T05.52-4aebcee/results.html
JOB TIME   : 142.02 s

hi @ngu-niny , as we talked this afternoon, I made some code change, and confirmed that we can really get the BLOCK_JOB_ERROR error even after extending lv&fs to the size of source image, please help to make a double check, thanks much

**Comment by ngu-niny** [comment]
LGTM and test PASS:

 (1/1) type_specific.io-github-autotest-qemu.blockdev_stream_on_error_ignore: PASS (217.37 s) 

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
