### PR TITLE
blockdev_inc_backup_sync_bitmap_nobitmap:Do incremental live     backup with sync:bitmap, but no bitmap

### PR DESCRIPTION
**Pull request by aliang123**
backup with sync:bitmap, but no bitmap

Signed-off-by: Aihua Liang <aliang@redhat.com>
id:1983623

### CODE REVIEW

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_sync_bitmap_nobitmap.q35: PASS (42.74 s)

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_sync_bitmap_nobitmap.q35: PASS (42.25 s)

**Comment by aliang123** [comment]
@zhencliu @ngu-niny, please help to review, thanks

**Comment by zhencliu** [comment]
LGTM

**Comment by ngu-niny** [comment]
01-Host_RHEL.m8.u5.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_sync_bitmap_nobitmap Finshed 2021-07-23 09:16:29 2021-07-23 09:18:05 PASS 95.778051

04-Host_RHEL.m8.u5.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_sync_bitmap_nobitmap Finshed 2021-07-23 09:20:53 2021-07-23 09:23:16 PASS 142.856118

07-Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_sync_bitmap_nobitmap Finshed 2021-07-23 09:27:34 2021-07-23 09:29:23 PASS 109.65664

10-Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_sync_bitmap_nobitmap Finshed 2021-07-23 09:32:55 2021-07-23 09:35:19 PASS 143.832756

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
