### PR TITLE
nbd_image_export: Add common block export support

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1911380

### CODE REVIEW

**Comment by zhencliu** [comment]
qemu-nbd regression tests:
(1/7) type_specific.io-github-autotest-qemu.access_with_remote_storage.with_ncat.with_inet: PASS (468.08 s)
 (2/7) type_specific.io-github-autotest-qemu.access_with_remote_storage.with_ncat.with_socket: PASS (465.57 s)
 (3/7) type_specific.io-github-autotest-qemu.access_with_remote_storage.with_unix_socket: PASS (297.81 s)
 (4/7) type_specific.io-github-autotest-qemu.access_with_remote_storage.with_nmap: PASS (5.62 s)
 (5/7) type_specific.io-github-autotest-qemu.access_with_remote_storage.with_qemu_io.drop_connection: PASS (4.93 s)
 (6/7) type_specific.io-github-autotest-qemu.access_with_remote_storage.with_qemu_io.drop_sync: PASS (5.07 s)
 (7/7) type_specific.io-github-autotest-qemu.access_with_remote_storage.with_guestfish: PASS (122.32 s)
RESULTS    : PASS 7 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2021-01-20T08.50-e0c0b14/results.html
JOB TIME   : 1372.11 s

nbd internal server regression tests:
block-export-add/block-export-del (since qemu 5.2)
(1/4) type_specific.io-github-autotest-qemu.blockdev_inc_backup_pull_mode_vm_down: FAIL: qemu hangs (215.03 s)
 (2/4) type_specific.io-github-autotest-qemu.blockdev_inc_backup_pull_mode_diff: PASS (182.43 s)
 (3/4) type_specific.io-github-autotest-qemu.blockdev_inc_backup_pull_mode_vm_reboot: PASS (244.85 s)
 (4/4) type_specific.io-github-autotest-qemu.blockdev_inc_backup_pull_mode: PASS (188.52 s)
nbd-server-add/nbd-server-remove (before qemu 5.2)
 (1/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_pull_mode_diff.q35: PASS (193.60 s)
 (2/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_pull_mode.q35: PASS (191.22 s)
 (3/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_pull_mode_vm_down.q35: FAIL: qemu hangs (296.54 s)
 (4/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_pull_mode_vm_reboot.q35: PASS (348.92 s)

**Comment by zhencliu** [comment]
hi @YongxueHong @ngu-niny , can you please help to review this patch? Thanks.
@ngu-niny , can you please perform regression testing on ppc? you may pick up several cases from the regression tests above. Thank you.

it deps on https://github.com/avocado-framework/avocado-vt/pull/2890

**Comment by ngu-niny** [comment]
LGTM and test PASS:

##nbd internal server regression tests:
#block-export-add/block-export-del (since qemu 5.2):
'11-Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_pull_mode' Finshed 2021-02-07 16:05:45 2021-02-07 16:10:46 PASS 300.757892
'14-Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_pull_mode_vm_reboot' Finshed 2021-02-07 16:16:02 2021-02-07 16:21:59 PASS 356.992385
'18-Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_pull_mode_vm_down' Finshed 2021-02-07 16:28:33 2021-02-07 16:34:39 FAIL 366.402491
'20-Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_pull_mode_diff' Finshed 2021-02-07 16:36:31 2021-02-07 16:40:21 PASS 230.103157"

#block-export-add/block-export-del (before qemu 5.2)
"01-Host_RHEL.m8.u3.v0.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_pull_mode_vm_reboot' Finshed 2021-02-09 04:43:00 2021-02-09 04:47:37 PASS 276.313106
'02-Host_RHEL.m8.u3.v0.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_pull_mode_vm_down' Finshed 2021-02-09 04:47:37 2021-02-09 04:49:37 ERROR 120.838211
'03-Host_RHEL.m8.u3.v0.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_pull_mode' Finshed 2021-02-09 04:49:38 2021-02-09 04:53:14 PASS 216.359916
'04-Host_RHEL.m8.u3.v0.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_pull_mode_diff' Finshed 2021-02-09 04:53:14 2021-02-09 04:56:54 PASS 219.618082


##qemu-nbd regression tests:
'4-Host_RHEL.m8.u4.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.access_with_remote_storage.with_nmap' Finshed 2021-02-09 14:48:44 2021-02-09 14:49:22 PASS 38.453009
'5-Host_RHEL.m8.u4.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.access_with_remote_storage.with_qemu_io.drop_connection' Finshed 2021-02-09 14:49:22 2021-02-09 14:49:32 PASS 9.764875
'6-Host_RHEL.m8.u4.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.access_with_remote_storage.with_qemu_io.drop_sync' Finshed 2021-02-09 14:49:32 2021-02-09 14:49:42 PASS 9.665957

Acked-by: Nini Gu <ngu@redhat.com>

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
