### PR TITLE
blockdev_stream_stress: add stream test with stress

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1881863

### CODE REVIEW

**Comment by zhencliu** [comment]
gluster direct:
 (1/1) Host_RHEL.m8.u3.product_av.gluster_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_stress: PASS (250.32 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2020-09-23T18.47-f60f742/results.html
JOB TIME   : 253.58 s

local fs:
 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_stress: PASS (226.94 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-23T06.45-209d077/results.html
JOB TIME   : 232.61 s

iscsi direct:
 (1/1) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_stress: PASS (228.56 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-23T06.59-3bc4bfb/results.html
JOB TIME   : 234.39 s

nbd:
 (1/1) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_stress: PASS (249.65 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-23T08.30-99af8b5/results.html
JOB TIME   : 255.41 s

hi @aliang123 @YongxueHong , can you please help to review the patch, thanks.
Also this one deps on #2418 , so please ignore the ci check failure

**Comment by aliang123** [comment]
Test logic should be: stress running-> block stream, but current logic is block stream-> stress test

**Comment by zhencliu** [comment]
> Test logic should be: stress running-> block stream, but current logic is block stream-> stress test

hi @aliang123 , you are right, because we need to install stress first, which takes 10+ seconds, but I set the speed to a low value, so the stream takes a very long time, and the stress is running till stream job done, is that OK?

Of course, I can start stress first if you still have concern, thanks.

**Comment by aliang123** [comment]
Start stress test, then do block stream will be better, I think.

**Comment by zhencliu** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_stress: PASS (194.92 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-25T01.07-dac67f7/results.html
JOB TIME   : 200.00 s

hi @aliang123 , this should work fine with your requirement, please make a double check, thanks much for your comments

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_stress.q35: PASS (319.71 s)

Acked-by: Aihua Liang <aliang@redhat.com>

**Comment by zhencliu** [comment]
hi @ngu-niny , can you please help to review this patch? Thanks.
btw: it deps on #2418

**Comment by zhencliu** [comment]
(1/3) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_stress: PASS (317.09 s)
(2/3) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_stop_cont: PASS (291.66 s)
(3/3) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_reboot: PASS (304.83 s)
RESULTS : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML : /home/kar/workspace/job-results/job-2020-09-27T20.47-c1ce6a6/results.html
JOB TIME : 919.88 s

hi @ngu-niny , code updated, can you please help make a double check? Thanks.

**Comment by zhencliu** [comment]
(1/3) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_reboot: PASS (766.92 s)
 (2/3) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_stop_cont: PASS (722.71 s)
 (3/3) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_stress: PASS (738.47 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-27T22.07-87dc65a/results.html
JOB TIME   : 2234.10 s

**Review by YongxueHong — APPROVED** [review]
LGTM

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_stress.q35: PASS (614.62 s)

Acked for test run on system disk

**Comment by ngu-niny** [comment]
LGTM.

Acked-by: Nini Gu ngu@redhat.com

**Pull request merged**
