### PR TITLE
bridge_qinq: Support s390x and fix some problems

### PR DESCRIPTION
**Pull request by PaulYuuu**
1. Failed to set netmask on s390x using socket, so replace with "ip
link" command.
2. Only stop NetworkManager on RHEL7 since it will conflict with
network.service.
3. Use "ip" command to configure network instead of "ifconfig"
4. Delete the private bridge in the final stage regardless of whether
the test passes or not.

ID: 1985163
Signed-off-by: Yihuang Yu <yihyu@redhat.com>

### CODE REVIEW

**Comment by PaulYuuu** [comment]
aarch64:
```
 (1/1) Host_RHEL.m8.u4.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.aarch64.io-github-autotest-qemu.bridge_qinq.arm64-pci: PASS (1177.75 s)
```

s390x:
```
 (1/1) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.bridge_qinq.s390-virtio: PASS (592.21 s)
```

**Comment by PaulYuuu** [comment]
Hello @fbq815 , please help review, thanks.

**Comment by fbq815** [comment]
Test result:
JOB ID     : 5ef227748893da8fd86de6f6612881388601beef
JOB LOG    : /root/avocado/job-results/job-2021-07-27T06.15-5ef2277/job.log
 (1/1) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.bridge_qinq.s390-virtio: PASS (564.32 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2021-07-27T06.15-5ef2277/results.html
JOB TIME   : 567.62 s

As the result, this pr LGTM

**Review by fbq815 — APPROVED** [review]

**Comment by PaulYuuu** [comment]
Hello @yanglei-rh , could you help to review and test it on x86 platform? Thanks.

**Comment by yanglei-rh** [comment]
Test Pass:
(2/2) Host_RHEL.m8.u5.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.bridge_qinq.q35: PASS (819.21 s)

LGTM

**Pull request merged**
