### PR TITLE
disable the usb controler piix3 piix4 and ich9-uhci for powerpc platf…

### PR DESCRIPTION
**Pull request by maxujun**
…orm vm
ID:1288368

### CODE REVIEW

**Comment by CongSmile** [comment]
Hi @maxujun 

1. does ppc only test ohci?

2. in the machines.cfg, has already set usb type, does not work?
    - @pseries:
        only ppc64, ppc64le
        machine_type = pseries
        # Currently only supports standard VGA
        vga = std
        # No support for USB-uhci
        usb_type = pci-ohci
        usb_type_usb1 = pci-ohci

Thanks.
        usb_controller_tablet1 = ohci
        del rtc_drift

**Comment by maxujun** [comment]
Hi @CongSmile 
1.ppc only supports ochi as usb1.0 controler,so disabled the uhci
2.yes, it still appears uhci controler in cases on ppc,and the device tablet1 can't found ochi bus,it's a another bug.
you can see the test result in bug 1288377.

**Comment by CongSmile** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by suqinhuang** [comment]
Acked-by: Suqin Huang

**Comment by xutian** [comment]
Why update set_link configuration in this patch?

**Comment by maxujun** [comment]
sorry,I have moved the invalid patch

**Comment by xutian** [comment]
Merged, thanks @maxujun

**Pull request merged**
