### PR TITLE
qemu.test: enforce_quit.unknow_flag: disable this case on RHEL.6 host

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>
id: 1409193

### CODE REVIEW

**Comment by suqinhuang** [comment]
could you add the description

**Comment by suqinhuang** [comment]
need to disable in qemu-rhel for 7 as well

**Comment by CongLi** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by PyLearner** [comment]
LGTM
Acked-by: Meng Yang meyang@redhat.com

**Comment by CongLi** [comment]
Commit log has been updated.

Thanks @XueqiangWei @suqinhuang @PyLearner

**Pull request merged**
