### PR TITLE
qemu.tests: Update the monitor_dir in softlockup

### PR DESCRIPTION
**Pull request by ypu**
Autotest test structure already changed, so update the code to fit it.

### CODE REVIEW

**Comment by ypu** [comment]
ID: 1146841

**Comment by xutian** [comment]
Hi @ypu 

Is this pullreq deps on https://github.com/autotest/virt-test/pull/2125

thanks,
Xu

**Comment by ypu** [comment]
@xutian no they not not related. Just both of them are related with the same function.

**Comment by CongSmile** [comment]
Acked-by: Cong Li <coli@edhat.com>

**Comment by ypu** [comment]
Thanks @CongSmile will merge it.

**Pull request merged**
