### PR TITLE
Do incremental live backup with bitmap after migrated on shared storage

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1870461

### CODE REVIEW

**Comment by zhencliu** [comment]
local fs:
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_with_migration: PASS (296.68 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-08-21T10.12-f7f3b67/results.html
JOB TIME   : 301.91 s
iscsi:
 (1/1) Host_RHEL.m8.u3.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_with_migration: PASS (255.12 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-08-21T11.04-3ae09d4/results.html
JOB TIME   : 260.29 s

nbd:
 (1/1) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_with_migration: PASS (564.45 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-08-23T22.04-45fdb0e/results.html
JOB TIME   : 570.07 s

gluster:
 (1/1) Host_RHEL.m8.u2.product_av.gluster_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_with_migration: PASS (351.81 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2020-08-24T10.16-978f4a8/results.html
JOB TIME   : 355.77 s

**Comment by zhencliu** [comment]
hi @YongxueHong @aliang123 can you please help to review the code, thanks.

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_with_migration.q35: PASS (405.35 s)

Acked-by: Aihua Liang<aliang@redhat.com>

**Review by YongxueHong — APPROVED** [review]
LGTM

**Comment by zhencliu** [comment]
hi @ngu-niny , can you please help to verify this on ppc? Thank you.
please be noted that we rebased the inc image onto the base image with qemu-img utility, instead of creating the inc image with its backing 'base' image after migration, @aliang123 confirmed that this is valid, just FYI (as it's different from the polarion case).

**Comment by ngu-niny** [comment]
LGTM and test PASS on ppc:

 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_with_migration: PASS (440.22 s)

Acked-by: Nini Gu <ngu@redhat.com>

**Review by YongxueHong — APPROVED** [review]
LGTM

**Comment by zhencliu** [comment]
hi @YongxueHong , can you please help to merge this patch, all acked, thanks much.

**Pull request merged**
