### PR TITLE
Change the clone guest method

### PR DESCRIPTION
**Pull request by yanglei-rh**
1.Delete parameters "image_snapshot = yes"
2.Add other parameters to clone the guest

ID:1860733
Signed-off-by: Lei Yang <leiyang@redhat.com>

### CODE REVIEW

**Comment by yanglei-rh** [comment]
@PaulYuuu Please help me review it,thanks.

**Comment by PaulYuuu** [comment]
Should we remove it together?
https://github.com/autotest/tp-qemu/blob/ed41b49eb73f77ed67906e4a65172ee36e951a89/qemu/tests/cfg/mq_change_qnum.cfg#L39

**Comment by yanglei-rh** [comment]
@PaulYuuu Thanks for your reminder, I have deleted it.

**Comment by PaulYuuu** [comment]
@yanglei-rh Can you provide the test result?

**Comment by yanglei-rh** [comment]
Test Pass:
(1/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.mq_change_qnum.disable_enable_queues.under_migrate.enable_msi.q35: PASS (143.44 s)
 (2/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.mq_change_qnum.disable_enable_queues.under_migrate.disable_msi.q35: PASS (82.09 s)

**Comment by PaulYuuu** [comment]
Ack.

**Pull request merged**
