### PR TITLE
virtio_fs: enable packed for vhost-user-fs-pci device

### PR DESCRIPTION
**Pull request by xiagao**
ID: 2069995
Signed-off-by: Xiaoling Gao <xiagao@redhat.com>

### CODE REVIEW

**Comment by xiagao** [comment]
(1/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.with_packed_on.q35: PASS (84.18 s)

**Comment by xiagao** [comment]
@zhenyzha @YongxueHong  Could you help review it, it's a bit simple change,thanks you.

**Review by YongxueHong — COMMENTED** [review]
Please delete the file `vcs.xml`, looks like it is not related to this PR.

**Comment by xiagao** [comment]
Sorry,I will close it as some wrong operation.

**Pull request closed without merging**
