### PR TITLE
migration: Update migration cases to support migration parameters

### PR DESCRIPTION
**Pull request by YongxueHong**
ID: 1910465
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by YongxueHong** [comment]
Depends on https://github.com/avocado-framework/avocado-vt/pull/2744

**Comment by YongxueHong** [comment]
Hi @wangxianxian @leexiaohui32 
please help me to review, thanks.

**Comment by YongxueHong** [comment]
Hi @wangxianxian @leexiaohui32
please help me to review, thanks.

**Comment by wangxianxian** [comment]
Test pass on ppc platform
(1/3) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.migrate.with_set_speed.tcp: PASS (93.80 s)
(2/3) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.migrate.with_set_speed.tcp.with_filter_off.with_post_copy: PASS (87.95 s)
(3/3) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.migrate.with_set_speed.tcp.with_filter_off.with_multifd: PASS (90.78 s)

22:59:19 DEBUG| Send command: {'execute': 'migrate-set-parameters', 'arguments': {'max-bandwidth': 1073741824}, 'id': 'z79Ksox7'}
23:02:25 DEBUG| Send command: {'execute': 'migrate-set-parameters', 'arguments': {'multifd-channels': 8}, 'id': 'LDX4ecjq'}

ACK

**Comment by leexiaohui32** [comment]
Ack after test on x86 with qemu-kvm-4.2 and qemu-kvm-5.2.0 when test following cases, the migration parameters are used correctly:
 (1/4) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.migrate.with_speed_measurement.tcp: PASS (145.09 s)
 (2/4) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.migrate.with_set_speed.tcp: PASS (98.23 s)
 (3/4) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.migrate.with_set_speed.tcp.with_filter_off.with_post_copy: PASS (89.06 s)
 (4/4) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.migrate.with_set_speed.tcp.with_filter_off.with_multifd: PASS (89.47 s)

**Comment by YongxueHong** [comment]
Thanks all. Let's merge it.

**Pull request merged**
