### PR TITLE
qemu.tests.flow_caches_stress_test: fixed escape character issue

### PR DESCRIPTION
**Pull request by Zhengtong**
ID: 1477902
Signed-off-by: Zhengtong <zhengtli@redhat.com>

### CODE REVIEW

**Comment by CongLi** [comment]
typo:
s/charator/charater

**Comment by Zhengtong** [comment]
updated, thanks @CongLi

**Comment by CongLi** [comment]
Ack.

**Comment by CongLi** [comment]
Thanks @Zhengtong

**Comment by Zhengtong** [comment]
(workspace)[root@dhcp-9-122 staf-kvm-devel]# avocado run --vt-config workspace/var/lib/avocado/data/avocado-vt/backends/qemu/cfg/tests-example.cfg
JOB ID     : a81cc2c708a6c509f2351f8bf27e1634c9e2d5c3
JOB LOG    : /home/staf-kvm-devel/workspace/job-results/job-2017-08-16T16.25-a81cc2c/job.log
 (1/1) smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.RHEL.7.4.x86_64.io-github-autotest-qemu.flow_caches_stress_test.no_multi_queues: PASS (1439.88 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 1452.49 s
JOB HTML   : /home/staf-kvm-devel/workspace/job-results/job-2017-08-16T16.25-a81cc2c/results.html

**Comment by hereischen** [comment]
Ack.

**Comment by CongLi** [comment]
Thanks all.

**Pull request merged**
