### PR TITLE
Add more scenerios for netkvm driver test

### PR DESCRIPTION
**Pull request by suqinhuang**
reboot/stop/shutdown guest during file transfer test

Signed-off-by: Suqin Huang <shuang@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
ID please !!

**Comment by suqinhuang** [comment]
ID: 1230682 1231003 1231023

**Comment by CongSmile** [comment]
From the requests, those cases should use serial to achieve.

Could you help double check it?

Thanks.

**Comment by MiriamDeng** [comment]
The attached bugs describe scenarios are for virtio serial driver but not netkvm driver.Please double check,thanks.

**Pull request closed without merging**
