### PR TITLE
seabioa_scsi_lun: correct data image name

### PR DESCRIPTION
**Pull request by XueqiangWei**
1. correct it in order to avoid removing system image

ID: 1762276

Signed-off-by: Xueqiang Wei <xuwei@redhat.com>

### CODE REVIEW

**Comment by XueqiangWei** [comment]
(1/2) Host_RHEL.m7.u8.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.8.x86_64.io-github-autotest-qemu.seabios_scsi_lun.q35: PASS (12.09 s)
 (2/2) Host_RHEL.m7.u8.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.seabios_scsi_lun.q35: PASS (11.13 s)

**Comment by XueqiangWei** [comment]
@yanan-fu @ybduan please help review it. Many thanks.

**Comment by yanan-fu** [comment]
Acked-by: Yanan Fu <yfu@redhat.com>

**Comment by ybduan** [comment]
Acked-by: Yanbin Duan yduan@redhat.com

**Pull request merged**
