### PR TITLE
Some updates for windows driver installation.

### PR DESCRIPTION
**Pull request by CongLi**
output is blank line if the driver uninstalled when
 get current driver version.

Signed-off-by: Cong Li <coli@redhat.com>

id: 1335030

### CODE REVIEW

**Comment by XueqiangWei** [comment]
LGTM,
Acked by XueqiangWei <xuwei@redhat.com>

**Comment by XueqiangWei** [comment]
@CongLi Is it necessary to make it work under both autotest-framework and avocado-framework.
for modual "aexpect" as below:
try:
    from aexpect import ShellCmdError
except ImportError:
    from virttest.aexpect import ShellCmdError

**Comment by XueqiangWei** [comment]
LGTM,
Acked by XueqiangWei xuwei@redhat.com

**Comment by PandaWei** [comment]
@CongLi 
window is not my focus, And the PR looks good for me.

And In my opinion,
tp-qemu as a independent repo, It's no need to take  'tp-qmeu' as the prefix of commit's head line.
\<test module name\>  is enough.
Only when,
Several files is modified and It's hard to change one the them as title.

That's my personal preferences.
Reference merely....  ^_^

**Comment by CongLi** [comment]
@PandaWei 
Thanks for your suggestions, which make sense.
I will update the commit info and PR title, and pay attention to those you mentioned. :)

**Comment by suqinhuang** [comment]
LGTM

Acked-by: Suqin Huang

**Comment by Zhengtong** [comment]
Acked-by: Zhengtong zhengtli@redhat.com
LGTM. and run passed:
 (1/7) smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win2012.x86_64.r2.io-github-autotest-qemu.single_driver_install.with_netkvm: PASS (206.03 s)
 (2/7) smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win2012.x86_64.r2.io-github-autotest-qemu.single_driver_install.with_viorng: PASS (175.43 s)
 (3/7) smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win2012.x86_64.r2.io-github-autotest-qemu.single_driver_install.with_viostor: PASS (209.73 s)
 (4/7) smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win2012.x86_64.r2.io-github-autotest-qemu.single_driver_install.with_vioscsi: PASS (203.35 s)
 (5/7) smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win2012.x86_64.r2.io-github-autotest-qemu.single_driver_install.with_vioserial: PASS (161.78 s)
 (6/7) smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win2012.x86_64.r2.io-github-autotest-qemu.single_driver_install.with_balloon: PASS (173.17 s)
 (7/7) smp_2.4096m.repeat1.post_check.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.Win2012.x86_64.r2.io-github-autotest-qemu.check_coredump: PASS (45.58 s)

**Comment by xutian** [comment]
thanks @CongLi, merged.

**Pull request merged**
