### PR TITLE
blockdev_full_backup_with_bitmap: Full backup with bitmap

### PR DESCRIPTION
**Pull request by aliang123**
Signed-off-by: Aihua Liang <aliang@redhat.com>
id:1982926

### CODE REVIEW

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.blockdev_full_backup_with_bitmap.q35: PASS (40.15 s)

**Comment by aliang123** [comment]
@zhencliu @ngu-niny, please help to review, thanks

**Comment by zhencliu** [comment]
LGTM

**Comment by ngu-niny** [comment]
(1/2) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.blockdev_full_backup_with_bitmap:  PASS (98.86 s)
 (2/2) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_full_backup_with_bitmap:  PASS (130.73 s)

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
