### PR TITLE
tp-qemu:  some updates for nic_hotplug.migrate

### PR DESCRIPTION
**Pull request by CongSmile**
Update the migration part as a subtest in case nic_hotplug,
which can reduce the code maintenance.

Signed-off-by: Cong Li <coli@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
Works for me,  but I suggest to renew IP for hotplug nic, then disable other nics in guest, then check is the nic works  for us, so that this case can works weather guest has NetworkManager  service enable.

Thanks,
Xu

**Comment by xutian** [comment]
Comment ID here, please!!

**Comment by CongSmile** [comment]
id: 1204011

**Comment by CongSmile** [comment]
Hi @xutian 

Thanks for the review.
Will update the code later.

Thanks.

**Comment by CongSmile** [comment]
Hi @xutian 

I have updated the code,
could you help review again?

Thanks a lot.

**Comment by xutian** [comment]
LGTM,

Acked-by: Xu Tian <xutian@redhat.com>

**Comment by ypu** [comment]
Hi @CongSmile This pullreq didn't remove the code of migration_after_nichotplug. And seems the migration_* related cases can be redesigned. As migration and nichotplug all have some framework support, let's discuss how to improve this part before we merged this pullreq.

**Comment by CongSmile** [comment]
According to @ypu suggestions, let's redesign the migraion related code in the server side.

Then close this pullreq.

Thanks.

**Pull request closed without merging**
