### PR TITLE
blockdev_mirror_firewall: block mirror with firewall test

### PR DESCRIPTION
**Pull request by zhencliu**
Break connection by inserting a rule by iptables when doing
  blockdev-mirror, remove the rule, blockdev-mirror should succeed

Signed-off-by: zhencliu <zhencliu@redhat.com>

ID: 1893930

### CODE REVIEW

**Comment by zhencliu** [comment]
local fs:
 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_firewall.q35: PASS (338.04 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-05T05.02-c8b81e9/results.html
JOB TIME   : 340.81 s

nbd:
 (1/1) Host_RHEL.m8.u3.product_av.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_firewall: PASS (426.00 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-05T05.10-5854598/results.html
JOB TIME   : 429.06 s

iscsi direct:
 (1/1) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_firewall.q35: PASS (352.45 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-05T05.22-d1cbf77/results.html
JOB TIME   : 355.57 s

gluster direct:
 (1/1) Host_RHEL.m8.u3.product_av.gluster_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_mirror_firewall.q35: PASS (442.43 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-05T18.42-53e4b96/results.html
JOB TIME   : 446.36 s

hi @YongxueHong @ngu-niny , can you please help to review this patch? Thanks.

**Comment by ngu-niny** [comment]
LGTM and test PASS:

 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.blockdev_mirror_firewall: PASS (413.83 s)

Acked-by: Nini Gu <ngu@redhat.com>

**Comment by zhencliu** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_firewall.q35: PASS (344.52 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-08T05.51-8278e33/results.html
JOB TIME   : 347.54 s

**Comment by ngu-niny** [comment]
Test PASS:

(3/3) Host_RHEL.m8.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_mirror_firewall: PASS (500.81 s)

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
