### PR TITLE
hotplug_mem_repeat: instead hotplug mem in turn with in loop

### PR DESCRIPTION
**Pull request by xutian**
Signed-off-by: Xu Tian xutian@redhat.com

### CODE REVIEW

**Comment by xutian** [comment]
ID: 1320071

**Comment by xutian** [comment]
@suqinhuang  thanks your comments, fixed issue in commit and PR has updated, would you like to help review it.

Thanks,
Xu

**Comment by XueqiangWei** [comment]
tested with guest RHEL7.2/REHL7.3, all occur error, but run the cmd in below manually, it is good.
ShellCmdError: Shell command failed: "echo 'offline' > /sys/devices/system/memory/memory32/state"    (status: 1,    output: "echo 'offline' > /sys/devices/system/memory/memory32/sta<offline' > /sys/devices/system/memory/memory32/stat                         \x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08e\n-bash: echo: write error: Device or resource busy\n")

**Comment by xutian** [comment]
@XueqiangWei  It looks a kernel bug#1374114, can you try latest kernel.

**Comment by XueqiangWei** [comment]
@xutian retest on the latest kernel (kernel-3.10.0-511.el7.x86_64), also hit this issue.

**Comment by xutian** [comment]
still failed, please redhat bug#1314306

**Pull request closed without merging**
