### PR TITLE
verify_panic_status_with_pvpanic: Restrict to linux

### PR DESCRIPTION
**Pull request by ybduan**
Restrict this case only for Linux guest
ID: 1951410
Signed-off-by: ybduan <yduan@redhat.com>

### CODE REVIEW

**Comment by XueqiangWei** [comment]
@vivianQizhu Please help review it. Many thanks.

**Comment by vivianQizhu** [comment]
The commit title seems not proper, recommend: `verify_panic_status_with_pvpanic: Restrict to linux`

**Comment by XueqiangWei** [comment]
@ybduan  Please update the commit message, thanks.

**Comment by ybduan** [comment]
Updated.

**Comment by vivianQizhu** [comment]
Thanks @ybduan @XueqiangWei

**Pull request merged**
