### PR TITLE
netkvm_change_param_value_test:change ping prams for host to guest

### PR DESCRIPTION
**Pull request by kimi1978wy**
The command of ping is not correct, it using "-i" params, should
be deleted.

id:1801492

Signed-off-by: Yu Wang <wyu@redhat.com>

### CODE REVIEW

**Comment by kimi1978wy** [comment]
(1/3) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.r2.io-github-autotest-qemu.netkvm_change_param_value_test.enable_disable.q35: PASS (691.40 s)
 (2/3) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.r2.io-github-autotest-qemu.netkvm_change_param_value_test.multi_options.q35: PASS (2254.82 s)
 (3/3) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.r2.io-github-autotest-qemu.netkvm_change_param_value_test.modify_directly.q35: PASS (166.35 s)

**Comment by kimi1978wy** [comment]
@yanglei-rh could you help to review this ? Thanks~

**Comment by yanglei-rh** [comment]
Test Pass
 (1/3) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.netkvm_change_param_value_test.enable_disable.q35: PASS (681.28 s)
 (2/3) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.netkvm_change_param_value_test.multi_options.q35: PASS (2268.81 s)
 (3/3) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.netkvm_change_param_value_test.modify_directly.q35: PASS (180.52 s)

**Comment by kimi1978wy** [comment]
Hi @xutian  , could you help to review it? Thanks a lot

**Comment by xutian** [comment]
LGTM

**Pull request merged**
