### PR TITLE
virtio_fs_supp_group_transfer: limit guest version

### PR DESCRIPTION
**Pull request by hellohellenmao**
limit guest version for the case is supported sync rhel9.3

ID: 2020

### CODE REVIEW

**Comment by hellohellenmao** [comment]
@xiagao @YongxueHong  Could you please help to take a review? Thanks.

**Comment by hellohellenmao** [comment]
Tried the guest in the list, will hit "Test Suite could not be created. No test references provided nor any other arguments resolved into tests"

#python3 ConfigTest.py --testcase=virtio_fs_supp_group_transfer --imageformat=qcow2 --guestname=RHEL.9.2.0 --driveformat=virtio_blk --machines=q35 --clone=no

**Comment by YongxueHong** [comment]
Hi @hellohellenmao 
Could you provide further details on this issue? I would like to know the reason for this limitation.
Thanks.

**Comment by hellohellenmao** [comment]
> 2020

Sure, the case here is from a production bug(https://bugzilla.redhat.com/show_bug.cgi?id=2134128), which is fixed in rhel9.3. 
So from my previous testing, I tried rhel9.2, 9.1 and so, the automation tests all failed. Which is because we did not limit the guest version.

**Comment by YongxueHong** [comment]
> > 2020
> 
> Sure, the case here is from a production bug(https://bugzilla.redhat.com/show_bug.cgi?id=2134128), which is fixed in rhel9.3. So from my previous testing, I tried rhel9.2, 9.1 and so, the automation tests all failed. Which is because we did not limit the guest version.

Okay, got it, thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by YongxueHong** [comment]
Hi @fbq815 
Would you like to review it from the considering of the s390 platform?
Thanks.

**Comment by xiagao** [comment]
LGTM

**Comment by fbq815** [comment]
LGTM

**Review by fbq815 — APPROVED** [review]

**Pull request merged**
