### PR TITLE
qmp_command: add command "query-pci".

### PR DESCRIPTION
**Pull request by CongLi**
Signed-off-by: Cong Li <coli@redhat.com>

id: 1346109

### CODE REVIEW

**Comment by CongLi** [comment]
11:02:47 INFO | PASS 1-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.qmp_command.qmp_query-pci

**Comment by suqinhuang** [comment]
Acked-by: Suqin Huang

**Comment by mazhang** [comment]
Acked-by: Mazhang <mazhang@redhat.com>

**Comment by xutian** [comment]
merged, thanks @CongLi

**Pull request merged**
