### PR TITLE
virtio_fs_readonly: New case to test virtio-fs with read-only

### PR DESCRIPTION
**Pull request by YongxueHong**
New case to test virtio-fs with mounting by read-only options.

ID: 1809584
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by YongxueHong** [comment]
Depends on https://github.com/avocado-framework/avocado-vt/pull/2460

**Comment by YongxueHong** [comment]
python3 ConfigTest.py --clone=no --nrepeat=1 --platform=x86_64 --guestname=RHEL.8.2.0 --testcase=virtio_fs_readonly --driveformat=virtio_scsi --machine=q35
` (1/1) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.virtio_fs_readonly.q35: PASS (68.08 s)`

**Comment by YongxueHong** [comment]
@zhenyzha help me to review, thanks.

**Comment by zhenyzha** [comment]
on power8 and power9 pass, aarch64 results will be updated later.
 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.virtio_fs_readonly:PASS (93.42 s)

 (3/3) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.virtio_fs_readonly:PASS (109.67 s)

**Comment by zhenyzha** [comment]
on aarch64:
 (3/3) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.aarch64.io-github-autotest-qemu.virtio_fs_readonly.arm64-pci: PASS (48.86 s)

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Comment by YongxueHong** [comment]
Hi @zhenyzha  I have updated by your comment from JIRA.
please help me to review it again.thanks.

**Comment by zhenyzha** [comment]
ok for me , ack.

**Comment by YongxueHong** [comment]
Hi, @rajashreer7 @sathnaga @iranna-IBM
Please help me to review, thanks.

**Comment by YongxueHong** [comment]
Hi,  @sathnaga
Please help me to review, thanks.
cc @rajashreer7

**Comment by YongxueHong** [comment]
Hi, @sathnaga
Please help me to review, thanks.
cc @rajashreer7 @qunfang

**Comment by YongxueHong** [comment]
Hi @iranna-IBM
Please help me to review, thanks.

**Comment by YongxueHong** [comment]
` (1/1) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.virtio_fs_readonly.q35: PASS (65.01 s)`

**Comment by YongxueHong** [comment]
(1/1) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.virtio_fs_readonly.q35: PASS (78.30 s)

**Comment by YongxueHong** [comment]
Hi, @sathnaga
Please help me to review, thanks.

**Comment by YongxueHong** [comment]
Hi, @sathnaga
Please help me to review, thanks.
cc @iranna-IBM

**Pull request merged**
