### PR TITLE
tp-qemu: backup image chain when boot guest failed

### PR DESCRIPTION
**Pull request by xutian**
Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
ID: 1226137

**Comment by suqinhuang** [comment]
Hi xutian,

Confused that fix image backup in qemu_img.py test case.

guest crash may happen in any case.

**Comment by xutian** [comment]
@suqinhuang  just a enhancement for qemu_img  test, check bug to see more information.

Thanks

**Comment by CongSmile** [comment]
Also need judge enable_ceph condition, right?

Thanks.

**Comment by xutian** [comment]
@suqinhuang  and @CongSmile 
We will not  add more backend support in qemu_img case, because this case use private method to do image operation, and it hard to maintenance. we just need to ensure exists test case works well is enough. 
And qemu_disk_image case use framework method to do image operation, more and more new feature implemented base on qemu_disk_image test now, and I will add RDB device in that case in future.

Thanks your comments.

**Comment by xutian** [comment]
@suqinhuang  and @CongSmile  Any other comments about this fix?

**Comment by CongSmile** [comment]
LGTM,
Acked-by: Cong Li <coli@redhat.com>

**Comment by xutian** [comment]
Merged.  thanks @CongSmile  and @suqinhuang .

**Pull request merged**
