### PR TITLE
qemu_disk_img: new case for data integrity check with cache=writethrough & lazy_refcounts=on

### PR DESCRIPTION
**Pull request by hellohellenmao**
Signed-off-by: Tingting Mao <timao@redhat.com>

ID: 2074759

### CODE REVIEW

**Comment by hellohellenmao** [comment]
Passed for local file:
`$ python3 ConfigTest.py --testcase=qemu_img_check_data_integrity_with_lazy_refcounts --guestname=RHEL.8.7.0 --machines=q35 --driveformat=virtio_scsi --imageformat=qcow2 --clone=no`
 (1/1) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.x86_64.io-github-autotest-qemu.qemu_img_check_data_integrity_with_lazy_refcounts.q35: PASS (113.63 s)

**Comment by hellohellenmao** [comment]
Also passed for LVM image:
2-Host_RHEL.m9.u1.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.qemu_img_check_data_integrity_with_lazy_refcounts.q35 Finshed 2022-07-21 07:35:05 2022-07-21 07:45:28 PASS 623.560085

**Comment by hellohellenmao** [comment]
@XueqiangWei @zhencliu Could you please help to take a review? Thanks.

**Comment by zhencliu** [comment]
@hellohellenmao , it's better to run a test with windows guest, for I saw you add windows guest support in this case, thanks.

**Comment by zhencliu** [comment]
Sorry for closing this PR by mistake, reopen it now

**Comment by hellohellenmao** [comment]
@zhencliu Also tried with win2019, it works. Thanks.

Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.qemu_img_check_data_integrity_with_lazy_refcounts.q35: PASS (323.87 s)

**Comment by hellohellenmao** [comment]
@XueqiangWei @zhencliu Could you please help to take a review again? Thanks.

**Comment by XueqiangWei** [comment]
tested with rhel8.6, it works.

(1/1) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.qemu_img_check_data_integrity_with_lazy_refcounts.q35: PASS (514.17 s)

**Comment by XueqiangWei** [comment]
LGTM,
Acked-by: xuwei@redhat.com

**Comment by zhencliu** [comment]
LGTM

**Pull request merged**
