### PR TITLE
tp-qemu: driver_load_stress: Add scenario for netkvm and balloon.

### PR DESCRIPTION
**Pull request by CongSmile**
Signed-off-by: Cong Li <coli@redhat.com>

id: 1231108 1231041

### CODE REVIEW

**Comment by CongSmile** [comment]
For netkvm test, based on: https://github.com/avocado-framework/avocado-vt/pull/380

**Comment by CongSmile** [comment]
netkvm:
14:54:43 INFO | PASS smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u1.qcow2.virtio_blk.up.virtio_net.Win8.x86_64.1.io-github-autotest-qemu.driver_load_stress.with_netkvm.before_bg_test
14:56:53 INFO | PASS smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u1.qcow2.virtio_blk.up.virtio_net.Win8.x86_64.1.io-github-autotest-qemu.driver_load_stress.with_netkvm.during_bg_test
14:59:19 INFO | PASS smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u1.qcow2.virtio_blk.up.virtio_net.Win8.x86_64.1.io-github-autotest-qemu.driver_load_stress.with_netkvm.after_bg_test

balloon:
15:13:20 INFO | PASS smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u1.qcow2.virtio_blk.up.virtio_net.Win8.x86_64.1.io-github-autotest-qemu.driver_load_stress.with_balloon.before_bg_test
16:49:37 INFO | PASS smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u1.qcow2.virtio_blk.up.virtio_net.Win8.x86_64.1.io-github-autotest-qemu.driver_load_stress.with_balloon.during_bg_test
15:19:34 INFO | PASS smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u1.qcow2.virtio_blk.up.virtio_net.Win8.x86_64.1.io-github-autotest-qemu.driver_load_stress.with_balloon.after_bg_test

**Comment by suqinhuang** [comment]
Acked-by: Suqin Huang

**Comment by xutian** [comment]
Looks good to me, merged. thanks @CongSmile  and @suqinhuang

**Pull request merged**
