### PR TITLE
blockdev_inc_backup_add_disabled_bitmap: Add disabled bitmap test

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1908174

### CODE REVIEW

**Comment by zhencliu** [comment]
local fs:
 (1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_add_disabled_bitmap: PASS (83.68 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-16T01.37-6e3ad27/results.html
JOB TIME   : 86.45 s

iscsi-direct+virtio-blk:
 (1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_add_disabled_bitmap: PASS (88.96 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-16T02.02-0293d8c/results.html
JOB TIME   : 91.85 s

nbd:
 (1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_add_disabled_bitmap: PASS (274.80 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-16T02.07-96a61f4/results.html
JOB TIME   : 277.68 s

ceph:
 (1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_add_disabled_bitmap: PASS (243.30 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-16T02.15-0d27b78/results.html
JOB TIME   : 245.95 s

**Comment by zhencliu** [comment]
hi @yhong and @ngu-niny , can you please help to review this patch? Thanks.
it also deps on #2547

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by ngu-niny** [comment]
Test PASS:

12:14:04 INFO | PASS 16-Host_RHEL.m8.u4.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_add_disabled_bitmap
12:32:57 INFO | PASS 24-Host_RHEL.m8.u4.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_add_disabled_bitmap

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
