### PR TITLE
Remove 'oflag=direct' to avoid create data under tmpfs failed

### PR DESCRIPTION
**Pull request by yanglei-rh**
ID: 1917843

Signed-off-by: Lei Yang <leiayang@redhat.com>

### CODE REVIEW

**Comment by yanglei-rh** [comment]
@yanan-fu @PaulYuuu  Please help me review it, thanks a lot.

**Comment by yanan-fu** [comment]
@yanglei-rh  Could you provide the test result ?

**Review by PaulYuuu — APPROVED** [review]

**Comment by yanglei-rh** [comment]
Test Pass:
(1/7) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.msi_change_flag.vhostforce_on.disable_pci_msi.q35: PASS (164.89 s)
 (2/7) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.msi_change_flag.vhostforce_off.disable_pci_msi.q35: PASS (163.69 s)
 (3/7) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.virtual_nic.private.q35: PASS (80.23 s)
 (4/7) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.virtual_nic.send_buffer.zero_buf.q35: PASS (228.32 s)
 (5/7) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.virtual_nic.send_buffer.opt_buf.q35: PASS (228.14 s)
 (6/7) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.virtual_nic.send_buffer.default_buf.q35: PASS (225.05 s)
 (7/7) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.virtual_nic.with_stress.q35: PASS (1641.76 s)
(1/1) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.win_nics_teaming.q35: ERROR: Could not verify DHCP lease: 9a:2d:57:22:9c:41 --> 10.73.225.237 (It failed because of other problems, not related to the content of patch changes)

**Comment by yanan-fu** [comment]
Thanks @yanglei-rh @PaulYuuu

**Pull request merged**
