### PR TITLE
rfe: Introduce ruff-pre-commit

### PR DESCRIPTION
**Pull request by PaulYuuu**
rfe: Introduce ruff-pre-commit

Ruff is a fast, extensible Python linter designed to catch common issues
in Python code, such as syntax errors, stylistic inconsistencies, and
potential bugs.

ID: 2802
Depends on: #4077

### CODE REVIEW

**Review by yanan-fu — APPROVED** [review]
Ack

**Review by YongxueHong — DISMISSED** [review]
LGTM.

**Comment by XueqiangWei** [comment]
LGTM,
Acked-by: xuwei@redhat.com

**Review by XueqiangWei — DISMISSED** [review]

**Review by zhencliu — APPROVED** [review]

**Comment by PaulYuuu** [comment]
Update the branch to resolve all conflicts. Thanks all.

**Pull request merged**
