### PR TITLE
savevm_loadvm:continue vm if it's paused after loadvm for qemu6.0

### PR DESCRIPTION
**Pull request by maxujun**
ID:1976017
Signed-off-by: Xujun Ma <xuma@redhat.com>

### CODE REVIEW

**Comment by maxujun** [comment]
@MiriamDeng Could you help review?

**Comment by MiriamDeng** [comment]
git am 2898.patch
Applying: savevm_loadvm:continue vm if it's paused after loadvm for qemu6.0

**Comment by MiriamDeng** [comment]
ACK

**Comment by XueqiangWei** [comment]
@maxujun It's a product bug, It has been fixed by Kevin in upstream, the patch will be included in downstream soon. So no need this pullreq.
[PATCH] hmp: Fix loadvm to resume the VM on success instead of failure

**Comment by maxujun** [comment]
> 
> 
> NACK
> @maxujun It's a product bug, It has been fixed by Kevin in upstream, the patch will be included in downstream soon. So no need this pullreq.
> [PATCH] hmp: Fix loadvm to resume the VM on success instead of failure

Thanks for your information. close this patch.

**Pull request closed without merging**
