### PR TITLE
cgroup:Fix cpu topology issue

### PR DESCRIPTION
**Pull request by xiangchunfu**
Fix sockets * dies * cores * threads < smp_cpus

id: 1245899

Signed-off-by: Xiangchun Fu <xfu@redhat.com>

### CODE REVIEW

**Comment by xiangchunfu** [comment]
＠yfu please help reivew it when you have time.  it only affects cgroup 2 fail cases.  Thanks.

**Comment by xiangchunfu** [comment]
@yiqianwei please help reivew it when you have time. Thanks.

**Comment by vivianQizhu** [comment]
> Fix sockets * dies * cores * threads < smp_cpus
> 
> id: 1866783

Update id please.

**Comment by xiangchunfu** [comment]
updated new id:1245899  Thanks.

**Comment by yanan-fu** [comment]
For case `cpu_cfs_util`, the root cause is related with:
https://github.com/autotest/tp-qemu/blob/67c4dfbe69c337b72cf8ccbe32e9f5a9103d5f0e/qemu/tests/cgroup.py#L707

```
            smp = min(2 * smp, 2 * host_cpus - vm_cpus)
            _params['smp'] = smp
```

`smp` progressive increase while the `vcpu_maxcpus` is a constant once test start, such as:
```
-smp 1,maxcpus=16,cores=16,threads=1,dies=1,sockets=1  \
-smp 2,maxcpus=16,cores=16,threads=1,dies=1,sockets=1  \
-smp 4,maxcpus=16,cores=16,threads=1,dies=1,sockets=1  \
-smp 8,maxcpus=16,cores=16,threads=1,dies=1,sockets=1  \
-smp 16,maxcpus=16,cores=16,threads=1,dies=1,sockets=1  \
-smp 32,maxcpus=16,cores=16,threads=1,dies=1,sockets=1  \   ---> test fail
```

Then, we can update the `vcpus_maxcpus` for this test case, do not use the default one that generated  by framework(50% host cpus) automatically.

**Comment by yanan-fu** [comment]
For case `cpu_share`, it is related with:
https://github.com/autotest/tp-qemu/blob/67c4dfbe69c337b72cf8ccbe32e9f5a9103d5f0e/qemu/tests/cgroup.py#L842

```
params['smp'] = host_cpus
```

Same with `cpu_cfs_util`, `smp` be updated while `vcpu_maxcpus` remain unchanged, update with `vcpu_maxcpus = host_cpus` can fix this issue.

**Comment by yanan-fu** [comment]
By the way, use `params["vcpu_sockets"] = 1` when `smp = 1` is not must after introduce `vcpu_maxcpus` now.
It is not the key point of this issue, just wonder may be we can update it togeter, make it more like the actual topology.

**Comment by xiangchunfu** [comment]
@yanan-fu vcpu_maxcpus = host_cpus  make sense,  case works.

**Comment by yanan-fu** [comment]
Ack

Test result:
```
 (1/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.cgroup.cpu_cfs_util.q35: PASS (756.20 s)
 (2/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.cgroup.cpu_share.q35: FAIL: [3] parts broke their limits (243.64 s)
```
The failing is not related with this patch.

**Pull request merged**
