### PR TITLE
block_resize_unplug: New case to resize disk then reboot VM and unplug

### PR DESCRIPTION
**Pull request by YongxueHong**
New a case that resizes a disk then reboot VM and unplug this disk
at last.

ID: 1731614
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by YongxueHong** [comment]
@lolyu  @zhenyzha  @peixiu @kimi1978wy  @qingwangrh 
pls help me to review, thanks.

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=block_resize_unplug --guestname=RHEL.8.2 --clone=no

(1/4) Host_RHEL.m7.u8.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.block_resize_unplug.enlarge_disk.send_qmp.reboot_vm: PASS (120.07 s)
 (2/4) Host_RHEL.m7.u8.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.block_resize_unplug.enlarge_disk.send_shell.reboot_vm: PASS (117.76 s)
 (3/4) Host_RHEL.m7.u8.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.block_resize_unplug.shrink_disk.send_qmp.reboot_vm: PASS (116.40 s)
 (4/4) Host_RHEL.m7.u8.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.block_resize_unplug.shrink_disk.send_shell.reboot_vm: PASS (126.89 s)

**Comment by zhenyzha** [comment]
python3  -blockdev
 (1/4) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.block_resize_unplug.enlarge_disk.send_qmp.reboot_vm: PASS (166.06 s)
 (2/4) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.block_resize_unplug.enlarge_disk.send_shell.reboot_vm: PASS (204.12 s)
 (3/4) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.block_resize_unplug.shrink_disk.send_qmp.reboot_vm: PASS (166.20 s)
 (4/4) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.block_resize_unplug.shrink_disk.send_shell.reboot_vm: PASS (205.13 s)

python2  -drive testing

**Comment by zhenyzha** [comment]
python2 -drive testing
 (1/4) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.block_resize_unplug.enlarge_disk.send_qmp.reboot_vm: PASS (164.12 s)
 (2/4) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.block_resize_unplug.enlarge_disk.send_shell.reboot_vm: PASS (180.38 s)
 (3/4) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.block_resize_unplug.shrink_disk.send_qmp.reboot_vm: PASS (169.17 s)
 (4/4) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.block_resize_unplug.shrink_disk.send_shell.reboot_vm: PASS (216.10 s)

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Comment by kimi1978wy** [comment]
blockdev+pc+virtio_blk Pass
blockdev+q35+virtio_blk product bug (no delete event) Fail

 (01/10) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (818.31 s)
 (02/10) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win8.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (1031.70 s)
 (03/10) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.block_resize_unplug.enlarge_disk.send_qmp.reboot_vm: PASS (128.14 s)
 (04/10) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.block_resize_unplug.enlarge_disk.send_shell.reboot_vm: PASS (68.25 s)
 (05/10) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.block_resize_unplug.shrink_disk.send_qmp.reboot_vm: PASS (63.17 s)
 (06/10) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.block_resize_unplug.shrink_disk.send_shell.reboot_vm: PASS (64.92 s)
 (07/10) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win8.x86_64.io-github-autotest-qemu.block_resize_unplug.enlarge_disk.send_qmp.reboot_vm: PASS (99.04 s)
 (08/10) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win8.x86_64.io-github-autotest-qemu.block_resize_unplug.enlarge_disk.send_shell.reboot_vm: PASS (64.83 s)
 (09/10) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win8.x86_64.io-github-autotest-qemu.block_resize_unplug.shrink_disk.send_qmp.reboot_vm: PASS (60.61 s)
 (10/10) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win8.x86_64.io-github-autotest-qemu.block_resize_unplug.shrink_disk.send_shell.reboot_vm: PASS (59.87 s)

LGTM.Acked-by: Yu Wang <wyu@redhat.com>

**Comment by peixiu** [comment]
Tested with -drive format on win8-32 guest, all passed.

 (1/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.i386.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (737.17 s)
 (2/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.i386.io-github-autotest-qemu.block_resize_unplug.enlarge_disk.send_qmp.reboot_vm.q35: PASS (87.69 s)
 (3/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.i386.io-github-autotest-qemu.block_resize_unplug.enlarge_disk.send_shell.reboot_vm.q35: PASS (61.00 s)
 (4/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.i386.io-github-autotest-qemu.block_resize_unplug.shrink_disk.send_qmp.reboot_vm.q35: PASS (58.36 s)
 (5/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.i386.io-github-autotest-qemu.block_resize_unplug.shrink_disk.send_shell.reboot_vm.q35: PASS (60.53 s)

with -blockdev format on windows guest, all jobs failed due to bsod product bug  1708490 - Hotplug/unplug a scsi-hd/scsi-cd via blockdev hits bsod in windows guest. 
if also hit the problem after this bsod product bug fixed, will report a new auto bug~ 
currently LGTM for drive format~

Acked-by: Peixiu Hou phou@redhat.com

**Comment by YongxueHong** [comment]
> Tested with -drive format on win8-32 guest, all passed.
> 
> (1/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.i386.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (737.17 s)
> (2/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.i386.io-github-autotest-qemu.block_resize_unplug.enlarge_disk.send_qmp.reboot_vm.q35: PASS (87.69 s)
> (3/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.i386.io-github-autotest-qemu.block_resize_unplug.enlarge_disk.send_shell.reboot_vm.q35: PASS (61.00 s)
> (4/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.i386.io-github-autotest-qemu.block_resize_unplug.shrink_disk.send_qmp.reboot_vm.q35: PASS (58.36 s)
> (5/5) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.i386.io-github-autotest-qemu.block_resize_unplug.shrink_disk.send_shell.reboot_vm.q35: PASS (60.53 s)
> 
> with -blockdev format on windows guest, all jobs failed due to bsod product bug 1708490 - Hotplug/unplug a scsi-hd/scsi-cd via blockdev hits bsod in windows guest.
> if also hit the problem after this bsod product bug fixed, will report a new auto bug~
> currently LGTM for drive format~
> 
> Acked-by: Peixiu Hou [phou@redhat.com](mailto:phou@redhat.com)

Thanks, let's merge it firstly, when the bug is fixed, pls submit a new auto bug then assign it to me.

**Comment by YongxueHong** [comment]
Thanks all , let's merge it.

**Pull request merged**
