### PR TITLE
tp-qemu: update netperf test configuration

### PR DESCRIPTION
**Pull request by mazhang**
ID: 1326204

Signed-off-by: Maosheng Zhang <mazhang@redhat.com>

### CODE REVIEW

**Comment by spcui** [comment]
Hi @mazhang the commit message not clear for me, should be updated.

**Comment by spcui** [comment]
OK, LGTM
Acked-by: scui@redhat.com

**Comment by MiriamDeng** [comment]
Acked-by: mdeng@redhat.com

**Comment by maxujun** [comment]
Acked-by: xuma@redhat.com
LGTM

**Pull request merged**
