### PR TITLE
check_link_speed_duplex: change/delete default speed for guests

### PR DESCRIPTION
**Pull request by kimi1978wy**
1 Change default speed for windows according to product change
2 Delete default speed check for linux guest

id:1789673

Signed-off-by: Yu Wang <wyu@redhat.com>

### CODE REVIEW

**Comment by kimi1978wy** [comment]
(1/2) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.check_link_speed_duplex.q35: PASS (485.86 s)
 (2/2) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.check_link_speed_duplex.q35: PASS (73.84 s)

**Comment by kimi1978wy** [comment]
@yanglei-rh could you help to review this patch, thanks a lot~

**Comment by yanglei-rh** [comment]
Test pass
(1/1) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.check_link_speed_duplex.q35: PASS (373.79 s)
(1/1) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.check_link_speed_duplex.q35: PASS (90.37 s)

**Comment by kimi1978wy** [comment]
@xutian could you help to review it? Thanks a lot

**Pull request merged**
