### PR TITLE
Remove 'singlestep' member of StatusInfo in rhel9.5

### PR DESCRIPTION
**Pull request by yiqianwei**
ID: 2341

### CODE REVIEW

**Comment by yiqianwei** [comment]
Test results:
 (1/3) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.qmp_command.qmp_query-status.q35: PASS (90.47 s)
 (2/3) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.qmp_command.qmp_cont.q35: PASS (86.33 s)
 (3/3) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.qmp_command.qmp_stop.q35: PASS (100.98 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2024-05-06T21.03-0ecd9db/results.html
JOB TIME   : 281.87 s

**Comment by yiqianwei** [comment]
@yanan-fu  and @jingzhao84 , Could you help to review this patch? thanks

**Comment by yiqianwei** [comment]
@yanan-fu , thanks, I have updated it , please check it.

Test results:

 (1/3) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.qmp_command.qmp_query-status.q35: PASS (88.11 s)

 (2/3) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.qmp_command.qmp_cont.q35: PASS (86.56 s)

 (3/3) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.qmp_command.qmp_stop.q35: PASS (100.68 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2024-05-12T21.53-c14f309/results.html
JOB TIME   : 279.47 s

**Review by yanan-fu — APPROVED** [review]
Ack

**Comment by jingzhao84** [comment]
Ack: jinzhao@redhat.com

**Pull request merged**
