### PR TITLE
pci_devices: fix test name

### PR DESCRIPTION
**Pull request by rayx**
Signed-off-by: Huan Xiong <huan.xiong@hxt-semitech.com>

### CODE REVIEW

**Comment by rayx** [comment]
A bit off-topic... I actually don't quite understand why the test author wanted to test the configurations defined in pci_devices.cfg. Many configurations are about connecting a PCIE switch to a PCIE-to-PCI bridge. Is this a typical scenario? Why would someone want to do this? On the other hand, the test doesn't even cover a configuration like root->switch->devices, which I think is a basic and typical configuration that should be tested.

**Comment by vivianQizhu** [comment]
Right, as I mentioned in https://github.com/autotest/tp-qemu/issues/1557, this test is out of date, that's an old configuration used to exist. I am working on adding pcie-pci-bridge, hopefully post it this week. Thanks.

**Comment by vivianQizhu** [comment]
@ybduan Request for your ack.

**Comment by ybduan** [comment]
Acked-by: Yanbin Duan yduan@redhat.com

Name changing doesn't interfere with functionality, but considering it's about q35, needs ACK from @jingzhao84

**Comment by jingzhao84** [comment]
ok for name changing
acked-by: jinzhao@redhat.com

**Comment by vivianQizhu** [comment]
Thanks all.

**Pull request merged**
