### PR TITLE
timedrift:Add timebase clock source

### PR DESCRIPTION
**Pull request by maxujun**
ID:1989784
Signed-off-by: Xujun Ma <xuma@redhat.com>

### CODE REVIEW

**Comment by maxujun** [comment]
@MiriamDeng Could you help review?

**Comment by maxujun** [comment]
(01/10) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.timedrift_with_multi_vms.same_cpu: PASS (419.19 s)
 (02/10) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.timedrift_with_multi_vms.diff_cpu: PASS (543.73 s)
 (03/10) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.timedrift_adjust_time.guest_pause_resume.clock_vm.no_adjust_clock: PASS (1976.58 s)
 (04/10) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.timedrift_adjust_time.guest_pause_resume.clock_vm.adjust_host_clock: PASS (1933.56 s)
 (05/10) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.timedrift_adjust_time.guest_pause_resume.clock_host.no_adjust_clock: PASS (1959.65 s)
 (06/10) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.timedrift_adjust_time.guest_pause_resume.clock_host.adjust_host_clock: PASS (1937.24 s)
 (07/10) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.timedrift_adjust_time.guest_reboot.clock_vm.adjust_host_clock: PASS (161.72 s)
 (08/10) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.timedrift_adjust_time.guest_reboot.clock_vm.adjust_guest_clock: PASS (194.52 s)
 (09/10) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.timedrift_adjust_time.guest_reboot.clock_host.adjust_host_clock: PASS (194.59 s)
 (10/10) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.timedrift_adjust_time.guest_reboot.clock_host.adjust_guest_clock: PASS (179.28 s)

**Comment by MiriamDeng** [comment]
LGTM
JOB LOG    : /root/avocado/job-results/job-2021-08-06T03.30-28fa362/job.log
 (01/10) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.timedrift_adjust_time.guest_pause_resume.clock_vm.no_adjust_clock: PASS (1927.00 s)
 (02/10) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.timedrift_adjust_time.guest_pause_resume.clock_vm.adjust_host_clock: PASS (1944.05 s)
 (03/10) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.timedrift_adjust_time.guest_pause_resume.clock_host.no_adjust_clock: PASS (1940.72 s)
 (04/10) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.timedrift_adjust_time.guest_pause_resume.clock_host.adjust_host_clock: PASS (1939.45 s)
 (05/10) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.timedrift_adjust_time.guest_reboot.clock_vm.adjust_host_clock: PASS (144.15 s)
 (06/10) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.timedrift_adjust_time.guest_reboot.clock_vm.adjust_guest_clock: PASS (164.55 s)
 (07/10) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.timedrift_adjust_time.guest_reboot.clock_host.adjust_host_clock: PASS (143.16 s)
 (08/10) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.timedrift_adjust_time.guest_reboot.clock_host.adjust_guest_clock: PASS (143.85 s)
 (09/10) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.timedrift_with_multi_vms.same_cpu: PASS (408.61 s)
 (10/10) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.timedrift_with_multi_vms.diff_cpu: PASS (429.52 s)

**Review by yanan-fu — APPROVED** [review]
Ack

**Pull request merged**
