### PR TITLE
Virtual nic send buffer

### PR DESCRIPTION
**Pull request by FengYang**
ID: 951041

### CODE REVIEW

**Comment by CongSmile** [comment]
Hi @FengYang 

Dont we test subcase netperf_udp ?

Thanks.

**Comment by FengYang** [comment]
On 01/04/2015 05:07 PM, CongSmile wrote:
>
> Hi @FengYang <https://github.com/FengYang>
>
> Dont we test subcase netperf_udp ?
>
We need not test netperf_udp sub case in this cae.

netperf_udp designed to check outhrough for different package size.
It is only meaningful when setup netserver in ext_host.

**Comment by CongSmile** [comment]
Thanks @FengYang explanation.

Acked-by: Cong Li <coli@redhat.com>

**Comment by FengYang** [comment]
Thanks @CongSmile

**Pull request merged**
