### PR TITLE
virtio_fs: support writeback option on virtiofsd

### PR DESCRIPTION
**Pull request by xiagao**
Default is no_writeback, so add test scenario with writeback.
ID: 2035203
Signed-off-by: Xiaoling Gao <xiagao@redhat.com>

### CODE REVIEW

**Comment by xiagao** [comment]
(1/6) Host_RHEL.mx.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.x.0.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.with_writeback.q35: PASS (88.74 s)

**Comment by xiagao** [comment]
@zhenyzha @YongxueHong Also need your review of this patch,thank you.

**Comment by zhenyzha** [comment]
(1/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.with_writeback.arm64-pci: STARTED
| (1/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.with_writeback.arm64-pci: PASS (113.44 s)
 (2/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.always.with_writeback.arm64-pci: STARTED
\ (2/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.always.with_writeback.arm64-pci: PASS (97.87 s)
 (3/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.none.with_writeback.arm64-pci: STARTED
- (3/3) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.none.with_writeback.arm64-pci: PASS (98.13 s)

LGTM.Acked-by: Zhenyu Zhang <[zhenyzha@redhat.com](mailto:zhenyzha@redhat.com)>

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
