### PR TITLE
qemu.tests.multi_nics_verify: fix the escape character issue to let the second one work

### PR DESCRIPTION
**Pull request by Zhengtong**
ID: 1477450
Signed-off-by: Zhengtong <zhengtli@redhat.com>

### CODE REVIEW

**Comment by CongLi** [comment]
ack.

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

**Comment by hereischen** [comment]
Can you please paste the test result here？ @Zhengtong Thanks

**Comment by Zhengtong** [comment]
Testing was blocked by ID: 1395115.  Passed while do a workaround for ID: 1395115.

**Comment by CongLi** [comment]
Thanks all.

**Pull request merged**
