### PR TITLE
cdrom_test:change checking condition to change media

### PR DESCRIPTION
**Pull request by maxujun**
ID:2235575

### CODE REVIEW

**Review by hereischen — APPROVED** [review]

**Comment by maxujun** [comment]
Change media via DEVICE_TRAY_MOVED event directly because cdrom will be closed quickly after opening some times.

**Comment by maxujun** [comment]
@PaulYuuu @qingwangrh @MiriamDeng 
Could you help review?

**Review by PaulYuuu — APPROVED** [review]

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=cdrom_block_size_check --guestname=RHEL.9.3.0 --firmware=default_bios --clone=no
(1/2) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.cdrom_block_size_check.unlimited_iothread.q35: STARTED
 (1/2) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.cdrom_block_size_check.unlimited_iothread.q35: PASS (114.91 s)
 (2/2) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.cdrom_block_size_check.no_iothread.q35: STARTED
 (2/2) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.cdrom_block_size_check.no_iothread.q35: CANCEL: Got host qemu version:8.1.0-1, which is not in (,7.0.0-3] (3.05 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 1


LGTM

**Comment by PaulYuuu** [comment]
@maxujun, please remove the merge commit, keep only one commit in this PR.

**Comment by maxujun** [comment]
> @maxujun, please remove the merge commit, keep only one commit in this PR.

Updated

**Pull request merged**
