### PR TITLE
tp-qemu: update unplug disk test steps

### PR DESCRIPTION
**Pull request by xutian**
Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
ID: 1311834

**Comment by qunfang** [comment]
@xutian  Hi, xu, why not fix the block bug 1303513 first?

**Comment by xutian** [comment]
@qunfang  will looks at that bug.

**Comment by xutian** [comment]
@qunfang  checked the bug, it looks a qemu version related bug, need to fix in another PR. Any question  for this PR.

Thanks,
Xu

**Comment by suqinhuang** [comment]
LGTM

Acked-by: Suqin Huang

**Comment by qunfang** [comment]
@xutian get it, I have no question about this PR.

**Comment by spcui** [comment]
Acked-by: scui@redhat.com

**Pull request merged**
