### PR TITLE
libblkio_release_test:fix untar error

### PR DESCRIPTION
**Pull request by qingwangrh**
There are multi packages for libblkio since version 1.5.

ID:2860

### CODE REVIEW

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=block_libblkio_release --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=RHEL.9.5.0 --driveformat=virtio_scsi  --imageformat=qcow2 --machines=q35 --customsparams="vm_mem_limit = 12G\nimage_aio=threads" --firmware=default_bios --netdst=virbr0 --clone=no


(1/1) Host_RHEL.m9.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: STARTED
 (1/1) Host_RHEL.m9.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: PASS (189.51 s)

**Comment by qingwangrh** [comment]
@XueqiangWei @zhenyzha Please help to review

**Comment by XueqiangWei** [comment]
@zhenyzha Can you help take a look at it? Many thanks.

**Comment by zhenyzha** [comment]
This case is x86 only, so please ignore me, thanks :)

```
- block_libblkio_release:
    only Linux
    no aarch64 s390 s390x
```

**Pull request merged**
