### PR TITLE
multi_nics_verify: boot with 8 nics with mq on windows 32bit guest

### PR DESCRIPTION
**Pull request by kimi1978wy**
Add multique variant and limit 8 mq for windows 32 bit

Signed-off-by: Yu Wang <wyu@redhat.com>

id: 1688109

### CODE REVIEW

**Comment by kimi1978wy** [comment]
(1/2) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.multi_nics_verify.q35: PASS (422.53 s)
 (2/2) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.multi_nics_verify.with_multiqueue.q35: PASS (229.74 s)
 (1/2) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.multi_nics_verify.q35: PASS (139.85 s)
 (2/2) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.multi_nics_verify.with_multiqueue.q35: PASS (211.23 s)

**Comment by ybduan** [comment]
Please update the commit log.
Acked-by: Yanbin Duan yduan@redhat.com

**Comment by kimi1978wy** [comment]
@xiagao  could you help to review this patch?

**Comment by xiagao** [comment]
Acked-by: XIaoling Gao <xiagao@redhat.com>

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

**Pull request merged**
