### PR TITLE
Update vsock_test suite

### PR DESCRIPTION
**Pull request by qcheng-redhat**
Update vsock_test test suite
Rename test case vsock_seqpacket_test to vsock_test_suite

ID: 2167555

Signed-off-by: qcheng <qcheng@redhat.com>

### CODE REVIEW

**Comment by qcheng-redhat** [comment]
(1/1) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.vsock_test.vsock_test_suite.q35: PASS (109.22 s)

**Comment by qcheng-redhat** [comment]
Hi @PaulYuuu , could you please review this patch when you have time. Thanks.

**Comment by qcheng-redhat** [comment]
Add @XueqiangWei as well. Thanks.

**Review by PaulYuuu — DISMISSED** [review]

**Comment by XueqiangWei** [comment]
I found two of your accounts in commit log. Not sure why you use two accounts. Others LGTM.

Signed-off-by: qcheng <qcheng@redhat.com>
Signed-off-by: qcheng-redhat <qcheng@redhat.com>

**Comment by qcheng-redhat** [comment]
Update signed off information in commit message.

**Review by XueqiangWei — APPROVED** [review]

**Review by PaulYuuu — APPROVED** [review]

**Pull request merged**
