### PR TITLE
block_hotplug:change max_size case disk size to 100T

### PR DESCRIPTION
**Pull request by qingwangrh**
ID:2189768

Signed-off-by: qingwangrh <qinwang@redhat.com>

### CODE REVIEW

**Comment by qingwangrh** [comment]
@YongxueHong @XueqiangWei @peixiu Please help to review, thanks.

**Comment by YongxueHong** [comment]
Hi @qingwangrh 
Would you like to explain the reason for this change in the commit message?
Thanks.

**Comment by qingwangrh** [comment]
> Hi @qingwangrh Would you like to explain the reason for this change in the commit message? Thanks.

updated, thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by XueqiangWei** [comment]
Tested with ovmf and rhel9, win11 guests, the results were passed.

(01/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autot
est-qemu.block_hotplug.block_virtio.fmt_qcow2.max_size.with_plug.one_pci.q35: STARTED
 (01/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autot
est-qemu.block_hotplug.block_virtio.fmt_qcow2.max_size.with_plug.one_pci.q35: PASS (65.64 s)
 (02/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autot
est-qemu.block_hotplug.block_virtio.fmt_raw.max_size.with_plug.one_pci.q35: STARTED
 (02/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autot
est-qemu.block_hotplug.block_virtio.fmt_raw.max_size.with_plug.one_pci.q35: PASS (66.12 s)
 (03/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autot
est-qemu.block_hotplug.block_scsi.fmt_qcow2.max_size.with_plug.one_pci.q35: STARTED
 (03/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autot
est-qemu.block_hotplug.block_scsi.fmt_qcow2.max_size.with_plug.one_pci.q35: PASS (67.15 s)
 (04/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autot
est-qemu.block_hotplug.block_scsi.fmt_raw.max_size.with_plug.one_pci.q35: STARTED
 (04/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autot
est-qemu.block_hotplug.block_scsi.fmt_raw.max_size.with_plug.one_pci.q35: PASS (67.14 s)
 (05/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-q
emu.block_hotplug.block_virtio.fmt_qcow2.max_size.with_plug.one_pci.q35: STARTED
 (05/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-q
emu.block_hotplug.block_virtio.fmt_qcow2.max_size.with_plug.one_pci.q35: PASS (144.52 s)
(06/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-q
emu.block_hotplug.block_virtio.fmt_raw.max_size.with_plug.one_pci.q35: STARTED
 (06/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_hotplug.block_virtio.fmt_raw.max_size.with_plug.one_pci.q35: PASS (166.92 s)
 (07/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_hotplug.block_scsi.fmt_qcow2.max_size.with_plug.one_pci.q35: STARTED
 (07/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_hotplug.block_scsi.fmt_qcow2.max_size.with_plug.one_pci.q35: PASS (170.30 s)
 (08/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_hotplug.block_scsi.fmt_raw.max_size.with_plug.one_pci.q35: STARTED
 (08/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_hotplug.block_scsi.fmt_raw.max_size.with_plug.one_pci.q35: PASS (171.05 s)
 (09/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.block_hotplug.block_virtio.fmt_qcow2.max_size.with_plug.one_pci.q35: STARTED
 (09/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.block_hotplug.block_virtio.fmt_qcow2.max_size.with_plug.one_pci.q35: PASS (67.66 s)
 (10/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.block_hotplug.block_virtio.fmt_raw.max_size.with_plug.one_pci.q35: STARTED
 (10/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.block_hotplug.block_virtio.fmt_raw.max_size.with_plug.one_pci.q35: PASS (66.87 s)
(11/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-auto
test-qemu.block_hotplug.block_scsi.fmt_qcow2.max_size.with_plug.one_pci.q35: STARTED
 (11/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-auto
test-qemu.block_hotplug.block_scsi.fmt_qcow2.max_size.with_plug.one_pci.q35: PASS (67.90 s)
 (12/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-auto
test-qemu.block_hotplug.block_scsi.fmt_raw.max_size.with_plug.one_pci.q35: STARTED
 (12/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.block_hotplug.block_scsi.fmt_raw.max_size.with_plug.one_pci.q35: PASS (67.57 s)
 (13/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_hotplug.block_virtio.fmt_qcow2.max_size.with_plug.one_pci.q35: STARTED
 (13/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_hotplug.block_virtio.fmt_qcow2.max_size.with_plug.one_pci.q35: PASS (142.42 s)
 (14/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_hotplug.block_virtio.fmt_raw.max_size.with_plug.one_pci.q35: STARTED
 (14/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_hotplug.block_virtio.fmt_raw.max_size.with_plug.one_pci.q35: PASS (164.70 s)
 (15/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_hotplug.block_scsi.fmt_qcow2.max_size.with_plug.one_pci.q35: STARTED
 (15/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_hotplug.block_scsi.fmt_qcow2.max_size.with_plug.one_pci.q35: PASS (170.11 s)
 (16/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_hotplug.block_scsi.fmt_raw.max_size.with_plug.one_pci.q35: STARTED
 (16/16) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_hotplug.block_scsi.fmt_raw.max_size.with_plug.one_pci.q35: PASS (171.67 s)

**Review by XueqiangWei — APPROVED** [review]

**Review by YongxueHong — APPROVED** [review]

**Pull request merged**
