### PR TITLE
nic_opt: Remove architecture restrictions

### PR DESCRIPTION
**Pull request by PaulYuuu**
ID: 1985226
Signed-off-by: Yihuang Yu <yihyu@redhat.com>

### CODE REVIEW

**Comment by PaulYuuu** [comment]
aarch64:
```
 (01/12) Host_RHEL.m8.u4.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.aarch64.io-github-autotest-qemu.nic_opt.opt_test_netperf.indirect_desc.opt_on.arm64-pci: PASS (369.65 s)
 (02/12) Host_RHEL.m8.u4.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.aarch64.io-github-autotest-qemu.nic_opt.opt_test_netperf.indirect_desc.opt_off.arm64-pci: PASS (350.61 s)
 (03/12) Host_RHEL.m8.u4.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.aarch64.io-github-autotest-qemu.nic_opt.opt_test_netperf.mrg_rxbuf.opt_on.arm64-pci: PASS (341.40 s)
 (04/12) Host_RHEL.m8.u4.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.aarch64.io-github-autotest-qemu.nic_opt.opt_test_netperf.mrg_rxbuf.opt_off.arm64-pci: PASS (346.60 s)
 (05/12) Host_RHEL.m8.u4.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.aarch64.io-github-autotest-qemu.nic_opt.opt_test_ping.poll-us.opt_30.arm64-pci: PASS (216.42 s)
 (06/12) Host_RHEL.m8.u4.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.aarch64.io-github-autotest-qemu.nic_opt.opt_test_ping.poll-us.opt_50.arm64-pci: PASS (219.39 s)
 (07/12) Host_RHEL.m8.u4.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.aarch64.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_1.ctrl_vq_on.mq_opt_on.arm64-pci: PASS (228.50 s)
 (08/12) Host_RHEL.m8.u4.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.aarch64.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_1.ctrl_vq_on.mq_opt_off.arm64-pci: PASS (225.23 s)
 (09/12) Host_RHEL.m8.u4.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.aarch64.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_4.ctrl_vq_on.mq_opt_on.arm64-pci: PASS (223.52 s)
 (10/12) Host_RHEL.m8.u4.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.aarch64.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_4.ctrl_vq_on.mq_opt_off.arm64-pci: PASS (218.84 s)
 (11/12) Host_RHEL.m8.u4.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.aarch64.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_8.ctrl_vq_on.mq_opt_on.arm64-pci: CANCEL: The number of smp counts in this host is not big enough (31.81 s)
 (12/12) Host_RHEL.m8.u4.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.aarch64.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_8.ctrl_vq_on.mq_opt_off.arm64-pci: CANCEL: The number of smp counts in this host is not big enough (74.53 s)
```

s390:
```
 (01/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_netperf.indirect_desc.opt_on.s390-virtio: PASS (280.63 s)
 (02/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_netperf.indirect_desc.opt_off.s390-virtio: PASS (264.21 s)
 (03/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_netperf.mrg_rxbuf.opt_on.s390-virtio: PASS (264.09 s)
 (04/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_netperf.mrg_rxbuf.opt_off.s390-virtio: PASS (265.22 s)
 (05/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_ping.poll-us.opt_30.s390-virtio: PASS (170.69 s)
 (06/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_ping.poll-us.opt_50.s390-virtio: PASS (169.49 s)
 (07/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_1.ctrl_vq_on.mq_opt_on.s390-virtio: PASS (170.57 s)
 (08/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_1.ctrl_vq_on.mq_opt_off.s390-virtio: PASS (169.93 s)
 (09/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_4.ctrl_vq_on.mq_opt_on.s390-virtio: CANCEL: The number of smp counts in this host is not big enough (18.77 s)
 (10/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_4.ctrl_vq_on.mq_opt_off.s390-virtio: CANCEL: The number of smp counts in this host is not big enough (18.63 s)
 (11/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_8.ctrl_vq_on.mq_opt_on.s390-virtio: CANCEL: The number of smp counts in this host is not big enough (20.65 s)
 (12/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_8.ctrl_vq_on.mq_opt_off.s390-virtio: CANCEL: The number of smp counts in this host is not big enough (18.62 s)
```

**Comment by PaulYuuu** [comment]
Hello @fbq815 , please help review, thanks.

**Comment by fbq815** [comment]
Test result:
JOB ID     : 0de34d7a427d2eb3027417e4a6c14da46d916c44
JOB LOG    : /root/avocado/job-results/job-2021-07-27T06.42-0de34d7/job.log
 (01/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_netperf.indirect_desc.opt_on.s390-virtio: PASS (278.38 s)
 (02/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_netperf.indirect_desc.opt_off.s390-virtio: PASS (271.23 s)
 (03/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_netperf.mrg_rxbuf.opt_on.s390-virtio: PASS (271.96 s)
 (04/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_netperf.mrg_rxbuf.opt_off.s390-virtio: PASS (271.97 s)
 (05/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_ping.poll-us.opt_30.s390-virtio: PASS (172.66 s)
 (06/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_ping.poll-us.opt_50.s390-virtio: PASS (172.07 s)
 (07/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_1.ctrl_vq_on.mq_opt_on.s390-virtio: PASS (175.43 s)
 (08/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_1.ctrl_vq_on.mq_opt_off.s390-virtio: PASS (175.99 s)
 (09/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_4.ctrl_vq_on.mq_opt_on.s390-virtio: PASS (172.39 s)
 (10/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_4.ctrl_vq_on.mq_opt_off.s390-virtio: PASS (172.19 s)
 (11/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_8.ctrl_vq_on.mq_opt_on.s390-virtio: CANCEL: The number of smp counts in this host is not big enough (21.85 s)
 (12/12) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.nic_opt.opt_test_ping.mqcontrol.smp_8.ctrl_vq_on.mq_opt_off.s390-virtio: CANCEL: The number of smp counts in this host is not big enough (21.91 s)
RESULTS    : PASS 10 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 2
JOB HTML   : /root/avocado/job-results/job-2021-07-27T06.42-0de34d7/results.html
JOB TIME   : 2180.65 s

As the test result I think we need to limit the smp value on s390x

**Comment by fbq815** [comment]
Since most of LPAR only have 12 CPUs for maximum on the host, I think we could add "no s390x" under "-smp_8"

**Comment by PaulYuuu** [comment]
> Since most of LPAR only have 12 CPUs for maximum on the host, I think we could add "no s390x" under "-smp_8"

That is the limitation of the host resources, so you need to filter it out when you want to run.

**Review by fbq815 — APPROVED** [review]

**Pull request merged**
