### PR TITLE
win_virtio_driver_install_from_update: Add viomem support

### PR DESCRIPTION
**Pull request by menli820**
Add viomem support to test driver install
from windows update server.
ID: 2504

Signed-off-by: menli <menli@redhat.com>

### CODE REVIEW

**Comment by menli820** [comment]
related log:
tdlog] MALLOC_PERTURB_=1  /usr/libexec/qemu-kvm \
[stdlog]     -S  \
[stdlog]     -name 'avocado-vt-vm1'  \
[stdlog]     -sandbox on,elevateprivileges=deny,obsolete=deny,resourcecontrol=deny,spawn=deny \
[stdlog]     -machine q35,memory-backend=mem-machine_mem \
[stdlog]     -device '{"id": "pcie-root-port-0", "driver": "pcie-root-port", "multifunction": true, "bus": "pcie.0", "addr": "0x1", "chassis": 1}' \
[stdlog]     -device '{"id": "pcie-pci-bridge-0", "driver": "pcie-pci-bridge", "addr": "0x0", "bus": "pcie-root-port-0"}'  \
[stdlog]     -nodefaults \
[stdlog]     -device '{"driver": "VGA", "bus": "pcie.0", "addr": "0x2"}' \
[stdlog]     -m 4096,maxmem=20G \
[stdlog]     -object '{"size": 8589934592, "id": "mem-vmem0", "qom-type": "memory-backend-ram"}' \
[stdlog]     -device '{"id": "pcie-root-port-1", "port": 1, "driver": "pcie-root-port", "addr": "0x1.0x1", "bus": "pcie.0", "chassis": 2}' \
[stdlog]     -device '{"memdev": "mem-vmem0", "driver": "virtio-mem-pci", "id": "virtio_mem-vmem0", "bus": "pcie-root-port-1", "addr": "0x0"}' \
[stdlog]     -object '{"size": 4294967296, "id": "mem-machine_mem", "qom-type": "memory-backend-ram"}'  \
[stdlog]     -smp 24,maxcpus=24,cores=12,threads=1,dies=1,sockets=2  \


JOB LOG    : /root/avocado/job-results/job-2024-10-29T00.40-349b657/job.log
 (1/1) Host_RHEL.m9.u6.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.win_virtio_driver_install_from_update.with_viomem.q35: STARTED
 (1/1) Host_RHEL.m9.u6.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.win_virtio_driver_install_from_update.with_viomem.q35: FAIL: viomem Driver can not be installed correctly from windows update (533.40 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2024-10-29T00.40-349b657/results.html
JOB TIME   : 534.82 s

Test summary:
1-Host_RHEL.m9.u6.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.win_virtio_driver_install_from_update.with_viomem.q35: FAIL

The fail is expected as I run it on rhel960 host, it will pass on rhel950 host.

**Comment by menli820** [comment]
@leidwang please help to review it when you free, thanks

**Review by leidwang — APPROVED** [review]
LGTM.

**Comment by menli820** [comment]
@PaulYuuu  please help to review it when you free, thanks

**Comment by menli820** [comment]
@PaulYuuu  kindly reminder, please help to review it when you free, thanks

**Comment by leidwang** [comment]
Hi @menli820 Please sign the commit, same as this MR https://github.com/autotest/tp-qemu/pull/4210/commits

**Review by PaulYuuu — APPROVED** [review]

**Pull request merged**
