### PR TITLE
watchdog:Disable Hot-plug/hot-unplug i6300esb test case in q35

### PR DESCRIPTION
**Pull request by yiqianwei**
ID: 2187941

### CODE REVIEW

**Comment by yiqianwei** [comment]
Test results: No find Hot-plug/hot-unplug i6300esb test case

 (01/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (02/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.rh_kernel_update.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (03/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.system_powerdown.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (04/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.system_reset_bootable.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (05/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.system_reset_during_boot.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (06/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.boot.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (07/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.reboot.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (08/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.stop_continue.stop_cont_only.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (09/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.shutdown.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (10/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.boot_with_watchdog.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 
 (11/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.magic_close.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (12/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_action.reboot_guest.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (13/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_action.shutdown_guest.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (14/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_action.pause_guest.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (15/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_action.noaction.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (16/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_action.debug.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (17/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_action.poweroff.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (18/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_action.inject_nmi.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (19/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.migration_when_wdt_timeout.reboot_guest.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (20/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.migration_when_wdt_timeout.pause.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (21/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.stop_cont_test.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (22/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_test_suit.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (23/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.heartbeat_test.valid.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (24/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.heartbeat_test.invalid_1.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (25/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.heartbeat_test.invalid_0.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (26/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.heartbeat_test.invalid_min.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (27/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.heartbeat_test.invalid_max.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

 (28/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.heartbeat_test.invalid_excp.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 28
JOB HTML   : /var/tmp/avocado-dry-run-wmsxtvfi/job-2023-04-19T03.11-88d709d/results.html
JOB TIME   : 23.46 s

**Comment by yanan-fu** [comment]
@MiriamDeng @bfu @BohdanMar  Could you please check with multi-arch side ? Thanks

**Comment by jingzhao84** [comment]
@yiqianwei  generally I agree with yanan's point, we are not sure multi-arch side. so I think we can change to no q35, that can not block multi-arch side, if they are using it as well.
 At least, seems ppc should be use the case.

Thanks
Jing

**Comment by MiriamDeng** [comment]
Hi @yiqianwei @yanan-fu @jingzhao84 
I agree with yfu's comment, it's better to keep it on multi-arch side.
Thanks all.

**Comment by yiqianwei** [comment]
@yanan-fu , I have updated this patch, please check it. thanks a lot

**Comment by jingzhao84** [comment]
@yiqianwei  could you also paste the test result? 
Thanks
Jing

**Comment by yiqianwei** [comment]
Test results:
 (01/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (02/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.rh_kernel_update.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (03/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.system_reset_bootable.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (04/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.system_reset_during_boot.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (05/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.system_powerdown.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (06/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.stop_continue.stop_cont_only.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (07/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.reboot.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (08/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.boot.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (09/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.shutdown.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (10/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.boot_with_watchdog.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (11/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.magic_close.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (12/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_action.reboot_guest.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (13/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_action.shutdown_guest.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (14/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_action.pause_guest.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (15/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_action.noaction.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (16/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_action.debug.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (17/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_action.poweroff.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (18/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_action.inject_nmi.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (19/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.migration_when_wdt_timeout.reboot_guest.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (20/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.migration_when_wdt_timeout.pause.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (21/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.stop_cont_test.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (22/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_test_suit.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (23/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.heartbeat_test.valid.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (24/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.heartbeat_test.invalid_1.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (25/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.heartbeat_test.invalid_0.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (26/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.heartbeat_test.invalid_min.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (27/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.heartbeat_test.invalid_max.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (28/28) Host_RHEL.m8.u8.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.watchdog.heartbeat_test.invalid_excp.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 28
JOB HTML   : /var/tmp/avocado-dry-run-ad3xfe4g/job-2023-04-23T23.12-996f6c6/results.html
JOB TIME   : 22.20 s

**Comment by jingzhao84** [comment]
Ack jinzhao (jinzhao@redhat.com)

**Review by yanan-fu — APPROVED** [review]

**Pull request merged**
