### PR TITLE
x86_cpu_model: add case to test EPYC-Rome cpu model

### PR DESCRIPTION
**Pull request by huangyum**
ID: 1838411
Signed-off-by: Yumei Huang <yuhuang@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
@huangyum  In fact, i am not very familiar with `flags`, but the change looks good, could you please provide the test result ? thanks!

**Comment by huangyum** [comment]
@yanan-fu The flags are added based on the product bug. Test would fail now due to bug1835390.

**Comment by vivianQizhu** [comment]
@yanan-fu Any more comments?

**Comment by yanan-fu** [comment]
> @yanan-fu Any more comments?

No more comments, just can not verify it as product bz now.
But no risk i think, Ack.

**Comment by vivianQizhu** [comment]
Thanks @yanan-fu @huangyum

**Pull request merged**
