### PR TITLE
Delete the format limit for some cases

### PR DESCRIPTION
**Pull request by hellohellenmao**
Support some cases both for luks and luks-inside-qcow2.

ID:1818734
Signed-off-by: Tingting Mao <timao@redhat.com>

### CODE REVIEW

**Comment by hellohellenmao** [comment]
@lolyu @YongxueHong Help to review, please.

**Comment by lolyu** [comment]
for the case named with `luks` in it, I believe it is better to change the case name to indicate the removal of limitation.

**Comment by hellohellenmao** [comment]
@lolyu Agree, and have updated. Review again, please.

**Comment by lolyu** [comment]
I believe there should is a need to update the related loops, please take this into consideration.

**Comment by hellohellenmao** [comment]
> I believe there is a need to update related loops, please take this into consideration.

Yes, you're right. For luks-inside-qcow2, I have updated. And for luks, I will file a new auto bug to update. Thanks for reminding.

**Comment by lolyu** [comment]
test result, please.

**Comment by hellohellenmao** [comment]
(1/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.8.x86_64.io-github-autotest-qemu.qemu_img_compare.q35: PASS (326.41 s)
 (2/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.8.x86_64.io-github-autotest-qemu.qemu_img_compare.cache_mode.none.q35: PASS (485.97 s)
 (3/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.8.x86_64.io-github-autotest-qemu.qemu_img_compare.cache_mode.writeback.q35: PASS (403.11 s)
 (4/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.8.x86_64.io-github-autotest-qemu.qemu_img_compare.cache_mode.unsafe.q35: PASS (363.32 s)
 (5/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.8.x86_64.io-github-autotest-qemu.qemu_img_compare.cache_mode.directsync.q35: PASS (491.59 s)
 (6/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.8.x86_64.io-github-autotest-qemu.qemu_img_compare.cache_mode.writethrough.q35: PASS (407.36 s)

**Comment by hellohellenmao** [comment]
(1/1) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.8.x86_64.io-github-autotest-qemu.rebase_second_snapshot_to_base.compat_level.compat_default.q35:  PASS (312.62 s)

**Comment by hellohellenmao** [comment]
The result for luks:

 (3/4) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.8.x86_64.io-github-autotest-qemu.rebase_second_snapshot_to_base.compat_level.compat_default.q35: PASS (1110.20 s)
 (4/4) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.8.x86_64.io-github-autotest-qemu.qemu_img_compare.q35: PASS (830.86 s)

**Comment by hellohellenmao** [comment]
@lolyu Help to merge if everything is okay to you, please.

**Pull request merged**
