### PR TITLE
block_multifunction:add time delay after boot

### PR DESCRIPTION
**Pull request by qingwangrh**
ID:2115740

### CODE REVIEW

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=block_multifunction.default.q35 --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=RHEL.9.0.0 --platform=x86_64 --driveformat=virtio_scsi --imageformat=qcow2 --machines=q35   --nrepeat=1  --firmware=default_bios

(01/1) repeat1.Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.block_multifunction.q35: STARTED
 (01/1) repeat1.Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.block_multifunction.q35: PASS (194.51 s)

**Comment by qingwangrh** [comment]
@YongxueHong @phou Please help to review,thanks

**Comment by YongxueHong** [comment]
Hi @qingwangrh 
Could you please add more details about why to do that in the commit message?
Thanks.

**Comment by XueqiangWei** [comment]
@YongxueHong @phou Please help to review it. Many thanks.

**Comment by peixiu** [comment]
oo, I'm so sorry, I missed this message~
Looks good to me, thanks~

python ConfigTest.py --testcase=block_multifunction.default.q35 --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=Win10 --platform=x86_64 --driveformat=virtio_scsi --imageformat=qcow2 --machines=q35 --nrepeat=1 --firmware=default_bios --clone=no

 (1/1) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.block_multifunction.q35: STARTED
 (1/1) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.block_multifunction.q35: PASS (767.92 s)

Acked-by: Peixiu Hou phou@redhat.com

**Review by peixiu — APPROVED** [review]

**Review by YongxueHong — APPROVED** [review]

**Pull request merged**
