### PR TITLE
live_snapshot:add iscsi_direct backend support

### PR DESCRIPTION
**Pull request by aliang123**
Add iscsi_direct support for live snapshot

Signed-off-by: Aihua Liang <aliang@redhat.com>
id:2052903

### CODE REVIEW

**Comment by aliang123** [comment]
Test cmd:
  python3 ConfigTest.py --guestname=RHEL.x.x.x --platform=x86_64 --category=storage_vm_migration_blockdev_snapshot --storage-backend-conf=/home/iscsi.cfg

Test Result:
(01/14) Host_RHEL.m8.u6.product_rhel.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_merge.q35: PASS (98.47 s)
 (02/14) Host_RHEL.m8.u6.product_rhel.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_guest_agent.q35: PASS (145.24 s)
 (03/14) Host_RHEL.m8.u6.product_rhel.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_nonexist_target.q35: PASS (30.47 s)
 (04/14) Host_RHEL.m8.u6.product_rhel.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_install.q35: PASS (807.54 s)
 (05/14) Host_RHEL.m8.u6.product_rhel.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_readonly.q35: PASS (116.43 s)
 (06/14) Host_RHEL.m8.u6.product_rhel.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot.q35: PASS (81.56 s)
 (07/14) Host_RHEL.m8.u6.product_rhel.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot.dst_cluster_size_512.q35: PASS (81.71 s)
 (08/14) Host_RHEL.m8.u6.product_rhel.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot.dst_cluster_size_2M.q35: PASS (81.25 s)
 (09/14) Host_RHEL.m8.u6.product_rhel.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_stress.q35: PASS (74.68 s)
 (10/14) Host_RHEL.m8.u6.product_rhel.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_stop_cont.q35: PASS (61.79 s)
 (11/14) Host_RHEL.m8.u6.product_rhel.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_data_file.q35: PASS (76.90 s)
 (12/14) Host_RHEL.m8.u6.product_rhel.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_chains.q35: PASS (164.35 s)
 (13/14) Host_RHEL.m8.u6.product_rhel.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_multi_disks.q35: PASS (97.41 s)
 (14/14) Host_RHEL.m8.u6.product_rhel.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.blockdev_snapshot_reboot.q35: PASS (68.00 s)

**Comment by aliang123** [comment]
For test with localfs test, pass.

**Comment by aliang123** [comment]
@zhencliu @ngu-niny @MiriamDeng , please help to review, thanks.

**Comment by ngu-niny** [comment]
LGTM.

Test pass:

01-Host_RHEL.m8.u6.product_rhel.nographic.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.s390-virtio Finshed 2022-02-14 05:57:12 2022-02-14 06:13:05 PASS 952.651302
02-Host_RHEL.m8.u6.product_rhel.nographic.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.blockdev_snapshot_stress.s390-virtio Finshed 2022-02-14 06:13:05 2022-02-14 06:14:11 PASS 66.28109
03-Host_RHEL.m8.u6.product_rhel.nographic.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.blockdev_snapshot_readonly.s390-virtio Finshed 2022-02-14 06:14:11 2022-02-14 06:15:00 PASS 49.067174
04-Host_RHEL.m8.u6.product_rhel.nographic.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.blockdev_snapshot_stop_cont.s390-virtio Finshed 2022-02-14 06:15:00 2022-02-14 06:15:41 PASS 40.432967
05-Host_RHEL.m8.u6.product_rhel.nographic.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.blockdev_snapshot_reboot.s390-virtio Finshed 2022-02-14 06:15:41 2022-02-14 06:16:24 PASS 43.353155
06-Host_RHEL.m8.u6.product_rhel.nographic.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.blockdev_snapshot_nonexist_target.s390-virtio Finshed 2022-02-14 06:16:24 2022-02-14 06:16:46 PASS 21.647072
07-Host_RHEL.m8.u6.product_rhel.nographic.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.blockdev_snapshot_install.s390-virtio Finshed 2022-02-14 06:16:46 2022-02-14 06:28:37 PASS 711.134735
08-Host_RHEL.m8.u6.product_rhel.nographic.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.blockdev_snapshot_chains.s390-virtio Finshed 2022-02-14 06:28:37 2022-02-14 06:30:54 PASS 136.888733
09-Host_RHEL.m8.u6.product_rhel.nographic.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.blockdev_snapshot_guest_agent.s390-virtio Finshed 2022-02-14 06:30:54 2022-02-14 06:32:52 PASS 117.864716
10-Host_RHEL.m8.u6.product_rhel.nographic.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.blockdev_snapshot.s390-virtio Finshed 2022-02-14 06:32:52 2022-02-14 06:33:45 PASS 53.029784
11-Host_RHEL.m8.u6.product_rhel.nographic.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.blockdev_snapshot.dst_cluster_size_512.s390-virtio Finshed 2022-02-14 06:33:45 2022-02-14 06:34:39 PASS 53.836794
12-Host_RHEL.m8.u6.product_rhel.nographic.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.blockdev_snapshot.dst_cluster_size_2M.s390-virtio Finshed 2022-02-14 06:34:39 2022-02-14 06:35:33 PASS 54.376907
13-Host_RHEL.m8.u6.product_rhel.nographic.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.blockdev_snapshot_data_file.s390-virtio Finshed 2022-02-14 06:35:33 2022-02-14 06:36:26 PASS 53.473875
14-Host_RHEL.m8.u6.product_rhel.nographic.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.blockdev_snapshot_merge.s390-virtio Finshed 2022-02-14 06:36:27 2022-02-14 06:37:36 PASS 69.148112
15-Host_RHEL.m8.u6.product_rhel.nographic.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.s390x.io-github-autotest-qemu.blockdev_snapshot_multi_disks.s390-virtio Finshed 2022-02-14 06:37:36 2022-02-14 06:38:46 PASS 70.669868

Acked-by: Nini Gu <ngu@redhat.com>

**Comment by zhencliu** [comment]
LGTM

**Comment by MiriamDeng** [comment]
It's running now and I will update ppc's results later.

**Comment by MiriamDeng** [comment]
LGTM 
Test from PPC, an error dues to env problem. 
(01/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: STARTED
| (01/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (1345.85 s)
 (02/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_merge: STARTED
\ (02/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_merge: PASS (214.94 s)
 (03/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_data_file: STARTED
/ (03/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_data_file: PASS (169.68 s)
 (04/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_readonly: STARTED
| (04/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_readonly: PASS (158.13 s)
 (05/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_multi_disks: STARTED
- (05/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_multi_disks: PASS (185.32 s)
 (06/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_stress: STARTED
\ (06/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_stress: ERROR: Installation failed with output:\n checking for a BSD-compatible install... /usr/bin/install -c\nchecking whether build environment is sane... yes\nchecking for a thread-safe mkdir -p... /usr/bin/mkdir -p\nchecking for gawk... gawk\nchecking whether make sets ... (79.89 s)
 (07/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_install: STARTED
/ (07/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_install: PASS (1166.94 s)
 (08/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_stop_cont: STARTED
\ (08/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_stop_cont: PASS (64.47 s)
 (09/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_nonexist_target: STARTED
- (09/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_nonexist_target: PASS (69.80 s)
 (10/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_reboot: STARTED
/ (10/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_reboot: PASS (142.29 s)
 (11/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_chains: STARTED
- (11/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_chains: PASS (220.58 s)
 (12/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_guest_agent: STARTED
/ (12/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_guest_agent: PASS (235.16 s)
 (13/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot: STARTED
| (13/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot: PASS (149.93 s)
 (14/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot.dst_cluster_size_512: STARTED
\ (14/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot.dst_cluster_size_512: PASS (162.72 s)
 (15/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot.dst_cluster_size_2M: STARTED
\ (15/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot.dst_cluster_size_2M: PASS (151.16 s)

**Comment by MiriamDeng** [comment]
LGTM 
Just one error dues to env issue.
(01/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: STARTED
| (01/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (1345.85 s)
 (02/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_merge: STARTED
\ (02/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_merge: PASS (214.94 s)
 (03/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_data_file: STARTED
/ (03/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_data_file: PASS (169.68 s)
 (04/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_readonly: STARTED
| (04/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_readonly: PASS (158.13 s)
 (05/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_multi_disks: STARTED
- (05/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_multi_disks: PASS (185.32 s)
 (06/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_stress: STARTED
\ (06/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_stress: ERROR: Installation failed with output:\n checking for a BSD-compatible install... /usr/bin/install -c\nchecking whether build environment is sane... yes\nchecking for a thread-safe mkdir -p... /usr/bin/mkdir -p\nchecking for gawk... gawk\nchecking whether make sets ... (79.89 s)
 (07/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_install: STARTED
/ (07/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_install: PASS (1166.94 s)
 (08/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_stop_cont: STARTED
\ (08/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_stop_cont: PASS (64.47 s)
 (09/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_nonexist_target: STARTED
- (09/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_nonexist_target: PASS (69.80 s)
 (10/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_reboot: STARTED
/ (10/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_reboot: PASS (142.29 s)
 (11/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_chains: STARTED
- (11/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_chains: PASS (220.58 s)
 (12/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_guest_agent: STARTED
/ (12/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot_guest_agent: PASS (235.16 s)
 (13/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot: STARTED
| (13/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot: PASS (149.93 s)
 (14/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot.dst_cluster_size_512: STARTED
\ (14/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot.dst_cluster_size_512: PASS (162.72 s)
 (15/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot.dst_cluster_size_2M: STARTED
\ (15/15) Host_RHEL.m8.u6.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot.dst_cluster_size_2M: PASS (151.16 s)

**Pull request merged**
