### PR TITLE
tp-qemu: block_hotplug: disable ide for block hotplug.

### PR DESCRIPTION
**Pull request by CongSmile**
Signed-off-by: Cong Li <coli@redhat.com>

### CODE REVIEW

**Comment by CongSmile** [comment]
id: 1212308

**Comment by XueqiangWei** [comment]
Works for me

Thanks,
Xueqiang

**Comment by xutian** [comment]
LGTM,

Acked-by: Xu Tian <xutian@redhat.com>

**Comment by xutian** [comment]
merged it, thanks for @CongSmile  and @XueqiangWei.


Xu

**Pull request merged**
