### PR TITLE
Modify function name to match the function in utils_net.py

### PR DESCRIPTION
**Pull request by kimi1978wy**
modified "boot_with_multiqueue.py" and "netkvm_cpu_mapping.py"

Signed-off-by: Yu Wang <wyu@redhat.com>

id:1722511

### CODE REVIEW

**Comment by kimi1978wy** [comment]
depends on https://github.com/avocado-framework/avocado-vt/pull/2107

**Comment by kimi1978wy** [comment]
(1/3) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.mq_enabled_chk.q35: PASS (355.69 s)
 (2/3) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.boot_with_max_queues.q35: PASS (382.79 s)
 (3/3) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.netkvm_cpu_mapping.q35: PASS (158.91 s)

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

**Comment by kimi1978wy** [comment]
(04/12) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win7.x86_64.sp1.io-github-autotest-qemu.netkvm_cpu_mapping.q35: PASS (426.84 s)
 (05/12) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win7.x86_64.sp1.io-github-autotest-qemu.mq_enabled_chk.q35: PASS (441.80 s)
 (06/12) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win7.x86_64.sp1.io-github-autotest-qemu.boot_with_max_queues.q35: PASS (514.99 s)
 (07/12) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.x86_64.io-github-autotest-qemu.netkvm_cpu_mapping.q35: PASS (188.29 s)
 (08/12) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.x86_64.io-github-autotest-qemu.mq_enabled_chk.q35: PASS (393.78 s)
 (09/12) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.x86_64.io-github-autotest-qemu.boot_with_max_queues.q35: PASS (437.73 s)
 (10/12) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.x86_64.1.io-github-autotest-qemu.netkvm_cpu_mapping.q35: PASS (181.28 s)
 (11/12) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.x86_64.1.io-github-autotest-qemu.mq_enabled_chk.q35: PASS (376.02 s)
 (12/12) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.x86_64.1.io-github-autotest-qemu.boot_with_max_queues.q35: PASS (411.85 s)

**Pull request merged**
