### PR TITLE
qemu.tests.format_disk: make parameters safer for windows guests

### PR DESCRIPTION
**Pull request by luckyh**
ID: 1299817

### CODE REVIEW

**Comment by luckyh** [comment]
@CongSmile would you please help me review it?

**Comment by CongSmile** [comment]
@luckyh 

Need from virttest import aexpect, or it would be failed  due to no module.

Others are fine for me.

**Comment by luckyh** [comment]
@CongSmile 
You need to install the aexpect package as avocado-vt no longer contain it.
https://github.com/autotest/tp-qemu/commit/173d35218412b57805ec7c3f5848ac8ac32ab3cc#diff-16

**Comment by spcui** [comment]
Acked-by: scui@redhat.com

**Comment by xutian** [comment]
Merged, thanks @luckyh @CongSmile  and @spcui

**Pull request merged**
