### PR TITLE
block_during_io.iozone_stress, enlarge iozone_timeout to 7200 seconds

### PR DESCRIPTION
**Pull request by XueqiangWei**
ID: 1745849

Signed-off-by: Xueqiang Wei <xuwei@redhat.com>

### CODE REVIEW

**Comment by XueqiangWei** [comment]
Tests: 
block_during_io.iozone_stress.system_disk.send_qmp.with_system_reset
block_during_io.iozone_stress.system_disk.send_shell.with_reboot

(08/42) repeat3.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.block_during_io.iozone_stress.system_disk.send_shell.with_reboot.q35: PASS (3604.77 s)
 (09/42) repeat4.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.block_during_io.iozone_stress.system_disk.send_qmp.with_system_reset.q35: PASS (3652.16 s)
 (10/42) repeat4.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.block_during_io.iozone_stress.system_disk.send_shell.with_reboot.q35: PASS (3619.91 s)
 (11/42) repeat5.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.block_during_io.iozone_stress.system_disk.send_qmp.with_system_reset.q35: PASS (3640.99 s)
1-Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_during_io.iozone_stress.system_disk.send_shell.with_reboot.q35: PASS (1169s)
2-Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_during_io.iozone_stress.system_disk.send_qmp.with_system_reset.q35 : PASS (1466s)

**Comment by XueqiangWei** [comment]
@kimi1978wy @peixiu @YongxueHong please help review it. Many thanks.

**Comment by YongxueHong** [comment]
The title of the commit is over 72 characters.
Suggestion:
```
block_during_io: Enlarge the value of iozone timeout

Enlarge the value of iozone timeout to 7200 sec, in order to run 
on the low performance host.
```

**Comment by XueqiangWei** [comment]
@YongxueHong update, thanks

**Comment by YongxueHong** [comment]
LGTM

**Comment by peixiu** [comment]
LGTM

Acked-by: Peixiu Hou phou@redhat.com

**Pull request merged**
