### PR TITLE
blockdev_inc_backup_remove_bitmap: Add test for removing bitmaps

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1908700

### CODE REVIEW

**Comment by zhencliu** [comment]
local fs:
 (1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_remove_bitmap: PASS (81.37 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-17T06.38-4ce54b1/results.html
JOB TIME   : 84.26 s
iscsi-direct+virtio-blk:
 (1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_remove_bitmap: PASS (92.82 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-17T06.43-c5d6b02/results.html
JOB TIME   : 95.67 s

ceph:
 (1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_remove_bitmap: PASS (177.50 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-17T06.47-3e2473c/results.html
JOB TIME   : 180.29 s

nbd:
(1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_remove_bitmap: PASS (213.02 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-17T06.52-dac3d68/results.html
JOB TIME   : 215.79 s

**Comment by zhencliu** [comment]
hi @YongxueHong  and @ngu-niny , can you please help to review this patch? Thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by ngu-niny** [comment]
Test PASS:

12:16:27 INFO | PASS 17-Host_RHEL.m8.u4.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_remove_bitmap
12:55:49 INFO | PASS 33-Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_remove_bitmap

Acked-by: Nini Gu ngu@redhat.com

**Pull request merged**
