### PR TITLE
block_multifunction:fix syntax error for 'or'

### PR DESCRIPTION
**Pull request by maxujun**
Add separate 'in' item for both condition
ID：2141378
Signed-off-by: Xujun Ma <xuma@redhat.com>

### CODE REVIEW

**Comment by maxujun** [comment]
@qingwangrh @MiriamDeng Could you help review?

**Comment by MiriamDeng** [comment]
can you give a test result or test case name ?

**Comment by maxujun** [comment]
(1/1) Host_RHEL.m8.u7.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.ppc64le.io-github-autotest-qemu.block_multifunction: STARTED
 (1/1) Host_RHEL.m8.u7.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.ppc64le.io-github-autotest-qemu.block_multifunction: PASS (451.27 s)

**Review by hereischen — APPROVED** [review]

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=block_multifunction --guestname=RHEL.8.8.0 --clone=no --firmware=default_bios
(1/1) Host_RHEL.m9.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.block_multifunction.q35: STARTED
 (1/1) Host_RHEL.m9.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.x86_64.io-github-autotest-qemu.block_multifunction.q35: PASS (200.00 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0


LGTM

**Comment by MiriamDeng** [comment]
LGTM
 (1/1) Host_RHEL.m8.u8.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.ppc64le.io-github-autotest-qemu.block_multifunction: STARTED
 (1/1) Host_RHEL.m8.u8.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.ppc64le.io-github-autotest-qemu.block_multifunction: PASS (379.71 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by maxujun** [comment]
@PaulYuuu Any comment?Could you help merge it?

**Comment by PaulYuuu** [comment]
@zhenyzha, can you also have a look?

**Review by PaulYuuu — APPROVED** [review]

**Comment by zhenyzha** [comment]
Applying: block_multifunction:fix syntax error for 'or'

 (1/1) Host_RHEL.m9.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.aarch64.io-github-autotest-qemu.block_multifunction.arm64-pci: PASS (377.01 s)

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Review by zhenyzha — APPROVED** [review]

**Pull request merged**
