### PR TITLE
qemu_guest_agent: support isa-serial method for windows guest

### PR DESCRIPTION
**Pull request by xiagao**
start guest agent inside windows guest with isa-serial port
ID: 1457067
Signed-off-by: Xiaoling Gao <xiagao@redhat.com>

### CODE REVIEW

**Comment by xiagao** [comment]
@xiangchunfu @yanan-fu  Could you help review this patch? Thank you.

**Comment by vivianQizhu** [comment]
@xiagao Code looks good to me, would you provide test result?

**Comment by xiagao** [comment]
@vivianQizhu  
(1/2) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.check_sync.q35: PASS (44.74 s)
 (2/2) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.check_sync.q35: PASS (42.82 s)

**Comment by vivianQizhu** [comment]
@xiagao Seems you also modified `gagent_stop_start`, would you provide test result for that one too? Thanks.

**Comment by xiagao** [comment]
@vivianQizhu  
 (1/2) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.gagent_stop_start.q35: PASS (290.46 s)
 (2/2) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.gagent_stop_start.q35: PASS (743.47 s)

**Pull request merged**
