### PR TITLE
blockdev_inc_backup_clear_bitmap: Add test for clearing bitmap

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1908999

### CODE REVIEW

**Comment by zhencliu** [comment]
iscsi-direct+virtio-blk:
(1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_clear_bitmap: PASS (91.32 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-18T03.41-2941eaf/results.html
JOB TIME   : 94.31 s

local fs:
 (1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_clear_bitmap: PASS (93.92 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-18T04.08-856539d/results.html
JOB TIME   : 96.67 s

nbd:
(1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_clear_bitmap: PASS (216.44 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-18T04.14-1d98696/results.html
JOB TIME   : 219.38 s

ceph:
 (1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_clear_bitmap: PASS (245.57 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-18T04.20-ab9e83a/results.html
JOB TIME   : 248.28 s

**Comment by zhencliu** [comment]
hi @YongxueHong @ngu-niny , can you please help to review this patch? Thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by ngu-niny** [comment]
LGTM and test PASS:

 (1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_clear_bitmap: PASS (107.80 s)

Acked-by: Nini Gu ngu@redhat.com

**Pull request merged**
