### PR TITLE
generic.tests.lvm: don't remove image_stg1 and image_stg2 before lvm clean

### PR DESCRIPTION
**Pull request by XueqiangWei**
ID: 1542384
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>

### CODE REVIEW

**Comment by XueqiangWei** [comment]
(1/4) smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.lvm.lvm_create: PASS (55.29 s)
 (2/4) smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.lvm.lvm_fill: PASS (88.20 s)
 (3/4) smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.lvm.lvm_ioquit: PASS (79.10 s)
 (4/4) smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.lvm.lvm_clean: PASS (43.59 s)

(1/4) smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u5.raw.virtio_scsi.up.virtio_net.Guest.RHEL.6.9.i386.io-github-autotest-qemu.lvm.lvm_create: PASS (73.02 s)
 (2/4) smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u5.raw.virtio_scsi.up.virtio_net.Guest.RHEL.6.9.i386.io-github-autotest-qemu.lvm.lvm_fill: PASS (87.51 s)
 (3/4) smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u5.raw.virtio_scsi.up.virtio_net.Guest.RHEL.6.9.i386.io-github-autotest-qemu.lvm.lvm_ioquit: PASS (82.91 s)
 (4/4) smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u5.raw.virtio_scsi.up.virtio_net.Guest.RHEL.6.9.i386.io-github-autotest-qemu.lvm.lvm_clean: PASS (57.84 s)

**Comment by CongLi** [comment]
1. Could you please update the commit log like 'generic.tests.lvm: ***' ?
2. I'm wondering why not set force_create_image = yes?
        - lvm_fill: lvm_create
            sub_type = fillup_disk
            force_create_image_stg1 = no
            force_create_image_stg2 = no

**Comment by XueqiangWei** [comment]
@CongLi lvm_fill, lvm_ioquit, lvm_clean are dependent on lvm_create. image_stg1 and image_stg2 are created in lvm_create, and used in lvm_fill, lvm_ioquit, lvm_clean. So do not create stg1 and stg2 in lvm_fill, lvm_ioquit, lvm_clean.

**Comment by XueqiangWei** [comment]
@CongLi @aliang123 updated, please help review again. Many thanks.

**Comment by CongLi** [comment]
Ack.

**Pull request merged**
