### PR TITLE
Merge 'qemu.lib' into 'provider'

### PR DESCRIPTION
**Pull request by luckyh**
The following error would occur during runing the test 'cdrom_test'

    ValueError: Missing test entry point

that because the VT framework wrongly loaded the test module from
'qemu.lib' instead of 'qemu.tests'.

To avoid the this and the potential issue, we can merge 'qemu.lib'
into 'provider' as the two directories are used in the same way.

Signed-off-by: Xu Han <xuhan@redhat.com>

ID: 1638700

### CODE REVIEW

**Comment by luckyh** [comment]
```
PASS 1-Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.x86_64.io-github-autotest-qemu.cdrom_test.cdrom_default
PASS 2-Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.x86_64.io-github-autotest-qemu.eject_media.eject
```

**Comment by luckyh** [comment]
@liaolucy @hereischen please help review this patch, thanks!

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

**Comment by luckyh** [comment]
@lolyu request for your review, thanks!

**Comment by liaolucy** [comment]
1.Host_RHEL.m8.u0.spice.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.x86_64.io-github-autotest-qemu.cdrom_test.cdrom_default: PASS (345.76 s)
2.Host_RHEL.m8.u0.spice.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.0.x86_64.io-github-autotest-qemu.cdrom_test.cdrom_default: PASS (343.93 s)

ACK

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
