### PR TITLE
usb_device_check: add windows test support

### PR DESCRIPTION
**Pull request by hereischen**
Make all current usb device check cases support for Windows.

id: 1504516
Signed-off-by: Haotong Chen <hachen@redhat.com>

### CODE REVIEW

**Comment by hereischen** [comment]
7.5：
 (01/10) smp_4.8192m.repeat1.pre_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_native: PASS (1563.20 s)
 (02/10) smp_4.8192m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.usb_device_check.multi_hubs_in_series.5_layer.nec-xhci: PASS (391.33 s)
 (03/10) smp_4.8192m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.usb_device_check.multi_hubs_in_series.6_layer.nec-xhci: PASS (4.62 s)
 (04/10) smp_4.8192m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.usb_device_check.multi_hubs_in_parallel.nec-xhci: PASS (90.63 s)
 (05/10) smp_4.8192m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.usb_device_check.input_devices_under_one_hub.nec-xhci: PASS (91.74 s)
 (06/10) smp_4.8192m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.usb_device_check.input_devices_under_two_tier_hub.nec-xhci: PASS (90.08 s)
 (07/10) smp_4.8192m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.usb_device_check.max_devices_under_one_hub.nec-xhci: PASS (93.42 s)
 (08/10) smp_4.8192m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.usb_device_check.usb_mouse.nec-xhci: PASS (91.37 s)
 (09/10) smp_4.8192m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.usb_device_check.usb_mouse_and_tablet.nec-xhci: PASS (90.83 s)
 (10/10) smp_4.8192m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.usb_device_check.usb_kbd.nec-xhci: PASS (91.24 s)

@ngu-niny Please help review when you have time， thanks

**Comment by ngu-niny** [comment]
Tesst PASS:

CaseName                                 Status          StartTime       EndTime         Result     TimeElapsed
'1-smp_8.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Win10.i386.io-github-autotest-qemu.usb_device_check.multi_hubs_in_series.5_layer.nec-xhci' Finshed 2017-11-05 21:41:40 2017-11-05 21:48:55 PASS 435.341152
'2-smp_8.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Win10.i386.io-github-autotest-qemu.usb_device_check.multi_hubs_in_series.6_layer.nec-xhci' Finshed 2017-11-05 21:48:55 2017-11-05 21:49:03 PASS 8.30228
'3-smp_8.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Win10.i386.io-github-autotest-qemu.usb_device_check.multi_hubs_in_parallel.nec-xhci' Finshed 2017-11-05 21:49:04 2017-11-05 21:50:44 PASS 100.751136
'4-smp_8.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Win10.i386.io-github-autotest-qemu.usb_device_check.input_devices_under_one_hub.nec-xhci' Finshed 2017-11-05 21:50:44 2017-11-05 21:52:31 PASS 106.685702
'5-smp_8.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Win10.i386.io-github-autotest-qemu.usb_device_check.input_devices_under_two_tier_hub.nec-xhci' Finshed 2017-11-05 21:52:31 2017-11-05 21:54:22 PASS 110.794497
'6-smp_8.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Win10.i386.io-github-autotest-qemu.usb_device_check.max_devices_under_one_hub.nec-xhci' Finshed 2017-11-05 21:54:22 2017-11-05 21:56:02 PASS 99.663264
'7-smp_8.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Win10.i386.io-github-autotest-qemu.usb_device_check.usb_mouse.nec-xhci' Finshed 2017-11-05 21:56:02 2017-11-05 21:57:28 PASS 86.152777
'8-smp_8.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Win10.i386.io-github-autotest-qemu.usb_device_check.usb_mouse_and_tablet.nec-xhci' Finshed 2017-11-05 21:57:28 2017-11-05 21:58:56 PASS 87.695178
'9-smp_8.4096m.repeat1.run_test.Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Win10.i386.io-github-autotest-qemu.usb_device_check.usb_kbd.nec-xhci' Finshed 2017-11-05 21:58:56 2017-11-05 22:00:24 PASS 87.611148

Acked-by: Nini Gu <ngu@redhat.com>

**Comment by hereischen** [comment]
@luckyh  Could you help review? Thanks.

**Comment by hereischen** [comment]
PASS 1-smp_4.8192m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Win2016.x86_64.io-github-autotest-qemu.usb_device_check.input_devices_under_one_hub.nec-xhci

**Pull request merged**
