### PR TITLE
qemu_io_blkdebug: fix qemu-io cases timeout issue

### PR DESCRIPTION
**Pull request by pingl2016**
As differnt errno are usually treated as the same code branch, test
one errno is good enough.

Signed-off-by: Ping Li pingl@redhat.com

### CODE REVIEW

**Comment by pingl2016** [comment]
ID: 1288066

**Comment by xutian** [comment]
why remove other error number, if you want to decrease test time, I think modify image size will very helpful.

**Comment by pingl2016** [comment]
@xutian according to test plan, most case is executed one time. I also think there is no need to executed so many times. If we modify the size of image, auto cases will not match the cases in polarion

**Comment by xutian** [comment]
Only one time is OK for me, but your case should covert all error number. not only 1 and 2.

**Comment by pingl2016** [comment]
After sync the issue with kevin, he thinks errno are usually treated as the same code branch and test one errno is good enough.

**Comment by CongLi** [comment]
Confirmed with @pingl2016 , no need to test all error number, as code is same.

Acked-by: Cong Li <coli@redhat.com>

**Comment by xutian** [comment]
looks ok for me. thanks @pingl2016 and @CongLi

**Pull request merged**
