### PR TITLE
boot_option.splash_time*: it was supported from rhel8.3, add the constraints

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>
ID: 2189723

### CODE REVIEW

**Comment by XueqiangWei** [comment]
1. Tested it on rhel8.2.0, no case was listed.
\# python ConfigTest.py --testcase=uefi_check_log_info.boot_option.splash_time_10,uefi_check_log_info.boot_option.splash_time_12  --guestname=RHEL.8.2.0 --firmware=ovmf --driveformat=virtio_scsi --clone=no --hostname=RHEL-8.2.0 --dryrun

2. Tested it on rhel9, the results were passed.
(1/2) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.uefi_check_log_info.boot_option.splash_time_10.q35: STARTED
 (1/2) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.uefi_check_log_info.boot_option.splash_time_10.q35: PASS (34.58 s)
 (2/2) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.uefi_check_log_info.boot_option.splash_time_12.q35: STARTED
 (2/2) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.uefi_check_log_info.boot_option.splash_time_12.q35: PASS (34.61 s)

**Comment by zhencliu** [comment]
hi @XueqiangWei , please shorten the commit header to max of 69 chars.

**Comment by XueqiangWei** [comment]
@zhencliu Thank you Zhenchao for pointing out it, I have updated it. Could you please help review it again. Many thanks.

**Comment by zhencliu** [comment]
Another thing is we may use splash_time as the virants name, under it we introduce two sub-variants, e.g. - 10s, - 12s, just like what you did for bootindex variants, if there are too many dup settings for both splash_time_* in future, we may consider this.

But it's OK for the current.

**Review by zhencliu — APPROVED** [review]

**Comment by XueqiangWei** [comment]
> Another thing is we may use splash_time as the virants name, under it we introduce two sub-variants, e.g. - 10s, - 12s, just like what you did for bootindex variants, if there are too many dup settings for both splash_time_* in future, we may consider this.
> 
> But it's OK for the current.

Make sense, I will pay attention to it in the future. Many thanks.

**Pull request merged**
