### PR TITLE
make block stream tests works in blockdev mode

### PR DESCRIPTION
**Pull request by xutian**
Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
deps on https://github.com/avocado-framework/avocado-vt/pull/2200

**Comment by aliang123** [comment]
For blockdev, the block stream should be: {'execute': 'block-stream', 'arguments': { 'device': 'sn1','job-id':'j1'}}
Acutal: {"execute": "block-stream", "arguments": {"device": "drive_image1"}, "id": "jfrjyILx"}

**Comment by aliang123** [comment]
For block commit failed with error:
   22:57:25 ERROR| ERROR 1-Host_RHEL.m7.u7.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.block_commit.with_payload.with_stress -> QMPCmdError: QMP command 'blockdev-snapshot-sync' failed    (arguments: {'device': '/home/kvm_autotest_root/images/rhel77-64-virtio-scsi.qcow2', 'snapshot-file': 'qcow2', 'mode': 'absolute-paths', 'format': 'qcow2'},    error message: {u'class': u'GenericError', u'desc': u'Cannot find device=/home/kvm_autotest_root/images/rhel77-64-virtio-scsi.qcow2 nor node_name='})

It meant to create snapshots:
   create live snapshots ['images/sn1', 'images/sn2', 'images/sn3', 'images/sn4']
But in fact, the cmd is:
   {'execute': 'blockdev-snapshot-sync', 'arguments': {'device': '/home/kvm_autotest_root/images/rhel77-64-virtio-scsi.qcow2', 'snapshot-file': 'qcow2', 'mode': 'absolute-paths', 'format': 'qcow2'}, 'id': '65215NWx'}

**Comment by xutian** [comment]
do you really apply  patch avocado-framework/avocado-vt#2200?

**Pull request closed without merging**
