### PR TITLE
New case: Add iommu support for virtio input driver

### PR DESCRIPTION
**Pull request by lijinlijin**
Check virtio-input driver functions well with iommu_platform=on
ID: 1783824
Signed-off-by: Li Jin <lijin@redhat.com>

### CODE REVIEW

**Comment by lijinlijin** [comment]
(1/6) Host_RHEL.m8.u1.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.vioinput_keyboard.q35: PASS (113.61 s)
 (2/6) Host_RHEL.m8.u1.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.vioinput_keyboard.iommu_enabled.q35: PASS (123.29 s)
 (3/6) Host_RHEL.m8.u1.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.vioinput_mice.device_mouse.q35: PASS (103.86 s)
 (4/6) Host_RHEL.m8.u1.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.vioinput_mice.device_tablet.q35: PASS (105.12 s)
 (5/6) Host_RHEL.m8.u1.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.vioinput_mice.iommu_enabled.device_mouse.q35: PASS (112.99 s)
 (6/6) Host_RHEL.m8.u1.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.vioinput_mice.iommu_enabled.device_tablet.q35: PASS (112.87 s)

**Comment by peixiu** [comment]
Hi @lijinlijin,

On our polarion case, steps has "iommu_platform=on,ats=on" behind the input device,
But I found none "iommu_platform=on,ats=on"  behind the input device,  both have "iommu_platform=on,ats=on" behind the virtio-scsi-pci and virtio-net-pci device.

Currently command as:
-device pcie-root-port,id=pcie-root-port-4,port=0x4,addr=0x1.0x4,bus=pcie.0,chassis=5 \
-device virtio-keyboard-pci,id=input_input1,bus=pcie-root-port-4,addr=0x0 \

And I remembered if vioinput driver have problem, the driver install will failed at case step2, need we to do single input driver install after vm booted up?

**Comment by lijinlijin** [comment]
@peixiu 
1. the command is not as expected, I will check what's wrong, thanks.
2. about driver install, no, we don't need to install driver again. if driver has problem, then input test case will fail, we will catch it there.

**Comment by lijinlijin** [comment]
@peixiu Need to modify avocado-vt part, pending on https://github.com/avocado-framework/avocado-vt/pull/2464

**Comment by peixiu** [comment]
Tested with patch 2463 on win10-64 guest, all passed, and  the command as expected, all input device has added "iommu_platform=on,ats=on "

PASS 1-Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.vioinput_keyboard.iommu_enabled.q35
PASS 1-Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.vioinput_mice.iommu_enabled.device_mouse.q35
PASS 2-Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.vioinput_mice.iommu_enabled.device_tablet.q35

Acked-By: Peixiu Hou phou@redhat.com

**Comment by yanan-fu** [comment]
Acked-by: Yanan Fu <yfu@redhat.com>

**Pull request merged**
