### PR TITLE
Enable autopep8 style check in travis CI

### PR DESCRIPTION
**Pull request by PaulYuuu**
Inspektor has the ability to use autopep8 transparently (if installed),
add autopep8 in requirements-travis.txt to enable this ability.

Refer to: avocado-framework/avocado#4394
ID: 1921754
Signed-off-by: Yihuang Yu <yihyu@redhat.com>

### CODE REVIEW

**Comment by PaulYuuu** [comment]
Hello @luckyh , another topic, I wanna enable [W1201](https://vald-phoenix.github.io/pylint-errors/plerr/errors/logging/W1201.html) and [W1202](https://vald-phoenix.github.io/pylint-errors/plerr/errors/logging/W1202.html) style check, what's your opinion on this?

**Comment by PaulYuuu** [comment]
@luckyh I did research, the `Inspektor` will check the code with `pylint` and `pycodestyle`, and a week pep8 check without autopep8 installed.

The pep8 style we disabled are `E501,E265,W601,E402,E722,E741`, and they can indeed be disabled.
| code | sample message |
| :---- | :---- |
| E265 | block comment should start with ‘# ‘ |
| E402 | module level import not at top of file |
| E501 (^) | line too long (82 > 79 characters) |
| E722 | do not use bare except, specify exception instead |
| E741 | do not use variables named ‘l’, ‘O’, or ‘I’ |
| W601 | .has_key() is deprecated, use ‘in’ |

autopep8 will fix issues reported by pycodestyle: https://pypi.org/project/autopep8/#features
After enabled autopep8 in CI, 3 issues (E128, E301, E303) lead to the failure of travis CI.
| code | sample message |
| :---- | :---- |
| E128 (^) | continuation line under-indented for visual indent |
| E301 | expected 1 blank line, found 0 |
| E303 | too many blank lines (3) |

I can ensure that `E301` and `E303` are what we need, but `E128` is a plus after we discussed it.

So there I have a concern, **install autopep8 but disable E128** or **disable autopep8 and keep it as it is**.

**Comment by PaulYuuu** [comment]
Failed item after installed autopep8:
```
PEP8 disabled: E501,E265,W601,E402,E722,E741
Pylint disabled: W,R,C,E1002,E1101,E1103,E1120,F0401,I0011
Pylint enabled : W0611
License check: disabled
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/generic/tests/shutdown.py:35:36: E128 67
Style: /var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/generic/tests/shutdown.py FAIL 
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/generic/tests/whql_hck_client_install.py:51:27: E128 27
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/generic/tests/whql_hck_client_install.py:69:27: E128 27
Style: /var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/generic/tests/whql_hck_client_install.py FAIL 
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/provider/cpu_utils.py:14:5: E301 expected 1 blank line, found 0
Style: /var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/provider/cpu_utils.py FAIL 
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/balloon_check.py:406:5: E301 expected 1 blank line, found 0
Style: /var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/balloon_check.py FAIL 
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/block_hotplug_in_pause.py:167:38: E128 71
Style: /var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/block_hotplug_in_pause.py FAIL 
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/block_resize.py:93:37: E128 45
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/block_resize.py:172:30: E128 54
Style: /var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/block_resize.py FAIL 
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/dump_guest_memory.py:193:29: E128 52
Style: /var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/dump_guest_memory.py FAIL 
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/fio_perf.py:259:34: E128 67
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/fio_perf.py:269:45: E128 78
Style: /var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/fio_perf.py FAIL 
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/mlock_basic.py:13:5: E301 expected 1 blank line, found 0
Style: /var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/mlock_basic.py FAIL 
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/qemu_guest_agent.py:534:9: E301 expected 1 blank line, found 0
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/qemu_guest_agent.py:550:46: E128 68
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/qemu_guest_agent.py:2398:49: E128 69
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/qemu_guest_agent.py:3507:5: E301 expected 1 blank line, found 0
Style: /var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/qemu_guest_agent.py FAIL 
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/qemu_guest_agent_hotplug.py:12:5: E303 too many blank lines (1)
Style: /var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/qemu_guest_agent_hotplug.py FAIL 
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/qemu_img_map_unaligned_image.py:33:21: E128 21
Style: /var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/qemu_img_map_unaligned_image.py FAIL 
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/remote_block_resize.py:70:37: E128 45
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/remote_block_resize.py:93:30: E128 54
Style: /var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/remote_block_resize.py FAIL 
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/usb_device_check_negative.py:26:27: E128 27
Style: /var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/usb_device_check_negative.py FAIL 
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/usb_redir.py:99:38: E128 38
Style: /var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/usb_redir.py FAIL 
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/vioser_in_use.py:104:32: E128 70
Style: /var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/vioser_in_use.py FAIL 
/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/win_sigverif.py:46:32: E128 58
Style: /var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/win_sigverif.py FAIL 
Global check FAIL
```

**Comment by luckyh** [comment]
Thanks @PaulYuuu ! Let's fix `E301` and `E303` first. I'll go check each `E128` issue one by one.

**Comment by luckyh** [comment]
@PaulYuuu let's use `autopep8` to fix `E128` issues as well, thanks.
```
$ ~/.local/bin/autopep8 -i -v --select=E128 generic/tests/whql_hck_client_install.py
[file:generic/tests/whql_hck_client_install.py]
--->  2 issue(s) to fix {'E128': {51, 69}}
--->  0 issue(s) to fix {}
```
```diff
diff --git a/generic/tests/whql_hck_client_install.py b/generic/tests/whql_hck_client_install.py
index 0b4376e5..b801ae5e 100644
--- a/generic/tests/whql_hck_client_install.py
+++ b/generic/tests/whql_hck_client_install.py
@@ -48,7 +48,7 @@ def run_whql_hck_client_install(test, params, env):
         session.cmd(cmd, timeout=600)
 
     error_context.context(("Setting up auto logon for user '%s'" %
-                          client_username), logging.info)
+                           client_username), logging.info)
     cmd = ('reg add '
            '"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\winlogon"'
            ' /v "%s" /d "%s" /t REG_SZ /f')
@@ -66,7 +66,7 @@ def run_whql_hck_client_install(test, params, env):
 
     install_cmd = params["install_cmd"]
     error_context.context(("Installing HCK client (timeout=%ds)" %
-                          install_timeout), logging.info)
+                           install_timeout), logging.info)
     session.cmd(install_cmd, timeout=install_timeout)
     reboot_timeout = login_timeout + 1500
     session = vm.reboot(session, timeout=reboot_timeout)
```

**Comment by PaulYuuu** [comment]
> @PaulYuuu let's use `autopep8` to fix `E128` issues as well, thanks.
> 
> ```
> $ ~/.local/bin/autopep8 -i -v --select=E128 generic/tests/whql_hck_client_install.py
> [file:generic/tests/whql_hck_client_install.py]
> --->  2 issue(s) to fix {'E128': {51, 69}}
> --->  0 issue(s) to fix {}
> ```
> 
> ```diff
> diff --git a/generic/tests/whql_hck_client_install.py b/generic/tests/whql_hck_client_install.py
> index 0b4376e5..b801ae5e 100644
> --- a/generic/tests/whql_hck_client_install.py
> +++ b/generic/tests/whql_hck_client_install.py
> @@ -48,7 +48,7 @@ def run_whql_hck_client_install(test, params, env):
>          session.cmd(cmd, timeout=600)
>  
>      error_context.context(("Setting up auto logon for user '%s'" %
> -                          client_username), logging.info)
> +                           client_username), logging.info)
>      cmd = ('reg add '
>             '"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\winlogon"'
>             ' /v "%s" /d "%s" /t REG_SZ /f')
> @@ -66,7 +66,7 @@ def run_whql_hck_client_install(test, params, env):
>  
>      install_cmd = params["install_cmd"]
>      error_context.context(("Installing HCK client (timeout=%ds)" %
> -                          install_timeout), logging.info)
> +                           install_timeout), logging.info)
>      session.cmd(install_cmd, timeout=install_timeout)
>      reboot_timeout = login_timeout + 1500
>      session = vm.reboot(session, timeout=reboot_timeout)
> ```

Okay, @luckyh . So it seems that I don’t need to modify again?

**Review by luckyh — APPROVED** [review]
Thanks.

**Pull request merged**
