### PR TITLE
expose_host_mtu: Change get_mtu/set_mtu methods to support s390

### PR DESCRIPTION
**Pull request by PaulYuuu**
Unfortunately, s390 will always return 0 when get_mtu on utils_net, this
should be a problem of s390 via using socket connection. Change methods
of then to support s390.

ID: 1982918
Signed-off-by: Yihuang Yu <yihyu@redhat.com>

### CODE REVIEW

**Comment by PaulYuuu** [comment]
Hello @fbq815, please help to review, thanks.

**Comment by fbq815** [comment]
Test result:
JOB ID     : 4a7a03e445029e97e5ce4c18a54ecba8cde49789
JOB LOG    : /root/avocado/job-results/job-2021-07-26T09.23-4a7a03e/job.log
 (1/1) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.expose_host_mtu.s390-virtio: PASS (37.72 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2021-07-26T09.23-4a7a03e/results.html
JOB TIME   : 38.53 s

According to the test result, this LGTM

**Comment by PaulYuuu** [comment]
Hello @yanglei-rh , could you help to review and test it on x86 platform? Thanks.

**Comment by yanglei-rh** [comment]
Hi @PaulYuuu This change is not friendly to x86, and the test result is a failed.
(3/3) Host_RHEL.m8.u5.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.expose_host_mtu.q35: ERROR: Could not get MUT value. (46.07 s)

**Comment by PaulYuuu** [comment]
> Hi @PaulYuuu This change is not friendly to x86, and the test result is a failed.
> (3/3) Host_RHEL.m8.u5.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.expose_host_mtu.q35: ERROR: Could not get MUT value. (46.07 s)

Thank you @yanglei-rh , this should be a problem in avocado.
```
$ ip -4 -j address show enP4p1s0f0
[]
```

If the interface does not set IP address, the `ip` command will return an empty list, I will try to fix it in avocado.

**Comment by yanglei-rh** [comment]
> > Hi @PaulYuuu This change is not friendly to x86, and the test result is a failed.
> > (3/3) Host_RHEL.m8.u5.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.expose_host_mtu.q35: ERROR: Could not get MUT value. (46.07 s)
> 
> Thank you @yanglei-rh , this should be a problem in avocado.
> 
> ```
> $ ip -4 -j address show enP4p1s0f0
> []
> ```
> 
> If the interface does not set IP address, the `ip` command will return an empty list, I will try to fix it in avocado.

@PaulYuuu Thanks for your update, if so, it's works for me.
LGTM

**Comment by PaulYuuu** [comment]
Since https://github.com/avocado-framework/avocado/pull/4815 has been merged, and I tested again at aarch64, let's merge it accordingly.
```
1-Host_RHEL.m8.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.aarch64.io-github-autotest-qemu.expose_host_mtu.arm64-pci Finshed 2021-08-02 10:40:33 2021-08-02 10:42:17 PASS 104.175264
```

**Pull request merged**
