### PR TITLE
Stream to an image without enough space

### PR DESCRIPTION
**Pull request by zhencliu**
blockdev_stream_no_space: stream to an image without enough space
    
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1898421

### CODE REVIEW

**Comment by zhencliu** [comment]
local fs:
 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_no_space.q35: PASS (53.86 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-23T09.46-b4ba86e/results.html
JOB TIME   : 55.68 s

nbd:
 (1/1) Host_RHEL.m8.u3.product_av.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_no_space: PASS (60.75 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-23T20.37-f6f2f91/results.html
JOB TIME   : 62.60 s

ceph:
 (1/1) Host_RHEL.m8.u3.product_av.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_stream_no_space.q35: PASS (61.89 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-23T22.17-c4adac3/results.html
JOB TIME   : 63.64 s

local fs + virtio blk
 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream_no_space.q35: PASS (55.81 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-23T22.13-88a9825/results.html
JOB TIME   : 57.60 s

**Comment by zhencliu** [comment]
hi @YongxueHong @ngu-niny , can you please help to review this patch? Thanks.

**Comment by zhencliu** [comment]
regression test:
 (1/7) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream_stress.q35: PASS (339.66 s)
 (2/7) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream_no_space.q35: PASS (163.21 s)
 (3/7) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_stop_cont.q35: PASS (328.91 s)
 (4/7) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream_subchain.q35: PASS (201.06 s)
 (5/7) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_reboot.q35: PASS (336.15 s)
 (6/7) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream_multiple_blocks.q35: PASS (275.82 s)
 (7/7) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream.q35: PASS (177.11 s)
RESULTS    : PASS 7 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-27T01.08-e4314b7/results.html
JOB TIME   : 1825.08 s

 (1/7) Host_RHEL.m8.u3.product_av.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_stream_no_space.q35: PASS (41.00 s)
 (2/7) Host_RHEL.m8.u3.product_av.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_stream_subchain.q35: PASS (368.39 s)
 (3/7) Host_RHEL.m8.u3.product_av.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_reboot.q35: PASS (324.36 s)
 (4/7) Host_RHEL.m8.u3.product_av.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_stop_cont.q35: PASS (315.38 s)
 (5/7) Host_RHEL.m8.u3.product_av.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_stream_stress.q35: PASS (325.65 s)
 (6/7) Host_RHEL.m8.u3.product_av.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_stream_multiple_blocks.q35: PASS (1183.84 s)
 (7/7) Host_RHEL.m8.u3.product_av.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_stream_none_existed_overlay.q35: PASS (110.47 s)
RESULTS    : PASS 7 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-27T01.55-d1eacc3/results.html
JOB TIME   : 2672.24 s

 (1/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_mirror_filternode.q35: PASS (167.24 s)
 (2/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_mirror_hotunplug.q35: PASS (243.99 s)
 (3/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_mirror_speed.q35: PASS (110.28 s)
 (4/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_mirror_firewall.q35: PASS (351.27 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-26T23.20-25e650d/results.html
JOB TIME   : 876.30 s

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by ngu-niny** [comment]
LGTM and test PASS:

(6/6) type_specific.io-github-autotest-qemu.blockdev_stream_no_space:  PASS (44.56 s)

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
