### PR TITLE
qemu.tests: add virtio port login test rhel-only

### PR DESCRIPTION
**Pull request by xutian**
Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
ID: 1156312 1157474

**Comment by xutian** [comment]
deps on https://github.com/autotest/virt-test/pull/2005

**Comment by CongSmile** [comment]
Hi xu, 

I met such error when run case virtio_port_login.virtio_console.

Could you help check it?

Thanks.

  File "/root/serial/staf-kvm-devel/autotest-devel/client/tests/virt/test-providers.d/downloads/io-github-autotest-qemu/generic/tests/virtio_port_login.py", line 101, in run
    session = getattr(console_test, login_func)(login_console)
  File "/root/serial/staf-kvm-devel/autotest-devel/client/shared/error.py", line 141, in new_fn
    return fn(*args, **kwargs)
  File "/root/serial/staf-kvm-devel/autotest-devel/client/tests/virt/test-providers.d/downloads/io-github-autotest-qemu/generic/tests/virtio_port_login.py", line 32, in virtio_console_login
    session = self.vm.wait_for_serial_login(timeout=180, virtio=port)
TypeError: wait_for_serial_login() got an unexpected keyword argument 'virtio'

**Comment by xutian** [comment]
Please apply autotest/virt-test#2005 
<https://github.com/autotest/virt-test/pull/2005> before test this case

Thanks,
Xu

**Comment by CongSmile** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by ypu** [comment]
LGTM

Acked-by: Yiqiao Pu <ypu@redhat.com>

**Comment by ypu** [comment]
Thanks @xutian and @CongSmile will merge it.

**Pull request merged**
