### PR TITLE
hotplug_mem_migration:enable dirty ring test

### PR DESCRIPTION
**Pull request by zhenyzha**
Enable dirty ring test on x86_64 and aarch64

ID: 1474
Signed-off-by: Zhenyu Zhang <zhenyzha@redhat.com>

### CODE REVIEW

**Comment by zhenyzha** [comment]
@mcasquer @YongxueHong Could you pls help review when you are free. thanks.

 --testcase=hotplug_mem_migration..with_multi_numa_nodes
```
 (1/6) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.hotplug_mem_migration.enable_dirty_ring.backend_ram.with_multi_numa_nodes.arm64-pci: STARTED
 (1/6) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.hotplug_mem_migration.enable_dirty_ring.backend_ram.with_multi_numa_nodes.arm64-pci: PASS (317.61 s)
 (2/6) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.hotplug_mem_migration.enable_dirty_ring.backend_file.with_multi_numa_nodes.arm64-pci: STARTED
 (2/6) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.hotplug_mem_migration.enable_dirty_ring.backend_file.with_multi_numa_nodes.arm64-pci: PASS (333.04 s)
 (3/6) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.hotplug_mem_migration.enable_dirty_ring.backend_memfd.with_multi_numa_nodes.arm64-pci: STARTED
 (3/6) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.hotplug_mem_migration.enable_dirty_ring.backend_memfd.with_multi_numa_nodes.arm64-pci: PASS (341.21 s)
 (4/6) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.hotplug_mem_migration.backend_ram.with_multi_numa_nodes.arm64-pci: STARTED
 (4/6) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.hotplug_mem_migration.backend_ram.with_multi_numa_nodes.arm64-pci: PASS (323.10 s)
 (5/6) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.hotplug_mem_migration.backend_file.with_multi_numa_nodes.arm64-pci: STARTED
 (5/6) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.hotplug_mem_migration.backend_file.with_multi_numa_nodes.arm64-pci: PASS (329.68 s)
 (6/6) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.hotplug_mem_migration.backend_memfd.with_multi_numa_nodes.arm64-pci: STARTED
 (6/6) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.hotplug_mem_migration.backend_memfd.with_multi_numa_nodes.arm64-pci: PASS (336.97 s)
```

**Comment by mcasquer** [comment]
All test cases passed as expected
```
JOB LOG    : /root/avocado/job-results/job-2023-11-02T04.20-ae1dc25/job.log
 (1/6) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hotplug_mem_migration.enable_dirty_ring.backend_ram.with_multi_numa_nodes.q35: STARTED
 (1/6) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hotplug_mem_migration.enable_dirty_ring.backend_ram.with_multi_numa_nodes.q35: PASS (461.21 s)
 (2/6) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hotplug_mem_migration.enable_dirty_ring.backend_file.with_multi_numa_nodes.q35: STARTED
 (2/6) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hotplug_mem_migration.enable_dirty_ring.backend_file.with_multi_numa_nodes.q35: PASS (407.10 s)
 (3/6) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hotplug_mem_migration.enable_dirty_ring.backend_memfd.with_multi_numa_nodes.q35: STARTED
 (3/6) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hotplug_mem_migration.enable_dirty_ring.backend_memfd.with_multi_numa_nodes.q35: PASS (406.00 s)
 (4/6) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hotplug_mem_migration.backend_ram.with_multi_numa_nodes.q35: STARTED
 (4/6) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hotplug_mem_migration.backend_ram.with_multi_numa_nodes.q35: PASS (398.90 s)
 (5/6) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hotplug_mem_migration.backend_file.with_multi_numa_nodes.q35: STARTED
 (5/6) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hotplug_mem_migration.backend_file.with_multi_numa_nodes.q35: PASS (404.10 s)
 (6/6) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hotplug_mem_migration.backend_memfd.with_multi_numa_nodes.q35: STARTED
 (6/6) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hotplug_mem_migration.backend_memfd.with_multi_numa_nodes.q35: PASS (401.59 s)
RESULTS    : PASS 6 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```

**Review by mcasquer — APPROVED** [review]
LGTM

**Review by hereischen — DISMISSED** [review]

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
