### PR TITLE
tp-qemu: qemu_guest_agent_snapshot.py: Update case steps.

### PR DESCRIPTION
**Pull request by CongLi**
1. Update case steps.
2. add windows support.

Signed-off-by: Cong Li <coli@redhat.com>

id: 1321832

Based on: https://github.com/autotest/tp-qemu/pull/592
https://github.com/avocado-framework/avocado-vt/pull/448

### CODE REVIEW

**Comment by CongLi** [comment]
17:10:57 INFO | PASS 1-smp_8.2048m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.Win2012.x86_64.r2.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_snapshot
17:27:31 INFO | PASS 1-smp_8.2048m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_snapshot

**Comment by XueqiangWei** [comment]
smp_16.16384m.repeat1.run_test.Host_RHEL.m7.u2.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_snapshot: PASS (157.57 s)
smp_16.16384m.repeat1.run_test.Host_RHEL.m7.u2.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.check_snapshot: PASS (170.21 s)
14:46:03 INFO | PASS 1-smp_8.2048m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.Win2012.x86_64.r2.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_snapshot

if the guest is windows platform, make sure the guest agent install successfully first.

**Comment by XueqiangWei** [comment]
LGTM,
Acked-by XueqiangWei <xuwei@redhat.com>

**Comment by MiriamDeng** [comment]
Test it pass
 (09/17) smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_snapshot: PASS (84.15 s)
  (16/17) smp_2.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.check_snapshot: PASS (77.48 s)

**Comment by MiriamDeng** [comment]
Acked-by Miriam Deng mdeng@redhat.com

**Comment by pingl2016** [comment]
It's ok for me.
Acked-by Ping Li ping@redhat.com

**Pull request merged**
