### PR TITLE
remote_image_convert: support nbd storage backend

### PR DESCRIPTION
**Pull request by zhencliu**
Convert remote image to local image
Convert local image to remote image
Convert remote image to remote image

Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1845050, 1845053

### CODE REVIEW

**Comment by zhencliu** [comment]
(01/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (2752.47 s)
 (02/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.rh_kernel_update: ERROR: 'list' object has no attribute 'splitlines' (327.44 s)
 (03/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert: PASS (1138.37 s)
 (04/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert.cache_mode.none: PASS (1237.35 s)
 (05/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert.cache_mode.writeback: PASS (1207.23 s)
 (06/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert.cache_mode.unsafe: PASS (1147.72 s)
 (07/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert.cache_mode.directsync: PASS (1200.02 s)
 (08/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert.cache_mode.writethrough: PASS (1171.06 s)
 (09/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_qcow2_convert: PASS (1133.31 s)
 (10/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_luks_convert: PASS (1434.31 s)
 (11/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_qcow2_remote.fmt_raw_convert: PASS (941.77 s)
 (12/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_qcow2_remote.fmt_qcow2_convert: PASS (791.91 s)
 (13/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_qcow2_remote.fmt_luks_convert: PASS (1080.21 s)
 (14/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_luks_remote.fmt_raw_convert: PASS (2329.93 s)
 (15/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_luks_remote.fmt_qcow2_convert: PASS (1158.84 s)
 (16/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_luks_remote.fmt_luks_convert: PASS (2462.04 s)
 (17/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert: PASS (1125.16 s)
 (18/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert.cache_mode.none: PASS (1010.25 s)
 (19/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert.cache_mode.writeback: PASS (1048.87 s)
 (20/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert.cache_mode.unsafe: PASS (1041.00 s)
 (21/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert.cache_mode.directsync: PASS (1011.68 s)
 (22/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert.cache_mode.writethrough: PASS (1007.58 s)
 (23/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_qcow2_convert: PASS (672.89 s)
 (24/24) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_luks_convert: PASS (1060.57 s)
RESULTS    : PASS 23 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-06-09T12.14-b385ee1/results.html
JOB TIME   : 29499.42 s

**Comment by zhencliu** [comment]
@XueqiangWei @YongxueHong Can you please help to review the case, thanks.
--testcase=remote_image_convert

**Comment by zixi-chen** [comment]
'03-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert' Finshed 2020-07-01 08:34:05 2020-07-01 08:36:44 PASS 158.777637
'04-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert.cache_mode.none' Finshed 2020-07-01 08:36:44 2020-07-01 08:39:25 PASS 161.317486
'05-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert.cache_mode.writeback' Finshed 2020-07-01 08:39:25 2020-07-01 08:42:05 PASS 160.170871
'06-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert.cache_mode.unsafe' Finshed 2020-07-01 08:42:05 2020-07-01 08:44:39 PASS 153.624952
'07-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert.cache_mode.directsync' Finshed 2020-07-01 08:44:39 2020-07-01 08:47:26 PASS 167.191916
'08-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert.cache_mode.writethrough' Finshed 2020-07-01 08:47:26 2020-07-01 08:50:04 PASS 157.641321
'09-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_qcow2_convert' Finshed 2020-07-01 08:50:04 2020-07-01 08:52:41 PASS 157.787814
'10-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_luks_convert' Finshed 2020-07-01 08:52:41 2020-07-01 08:56:01 PASS 199.601078
'11-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_qcow2_remote.fmt_raw_convert' Finshed 2020-07-01 08:56:01 2020-07-01 08:58:30 PASS 149.380094
'12-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_qcow2_remote.fmt_qcow2_convert' Finshed 2020-07-01 08:58:30 2020-07-01 09:01:04 PASS 153.74747
'13-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_qcow2_remote.fmt_luks_convert' Finshed 2020-07-01 09:01:04 2020-07-01 09:04:22 PASS 198.292174
'14-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_luks_remote.fmt_raw_convert' Finshed 2020-07-01 09:04:22 2020-07-01 09:07:53 PASS 210.325526
'15-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_luks_remote.fmt_qcow2_convert' Finshed 2020-07-01 09:07:53 2020-07-01 09:11:30 PASS 216.894188
'16-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_luks_remote.fmt_luks_convert' Finshed 2020-07-01 09:11:30 2020-07-01 09:15:35 PASS 245.547977
'17-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert' Finshed 2020-07-01 09:15:35 2020-07-01 09:17:18 PASS 103.279143
'18-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert.cache_mode.none' Finshed 2020-07-01 09:17:19 2020-07-01 09:19:13 PASS 114.693722
'19-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert.cache_mode.writeback' Finshed 2020-07-01 09:19:13 2020-07-01 09:20:58 PASS 104.532629
'20-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert.cache_mode.unsafe' Finshed 2020-07-01 09:20:58 2020-07-01 09:22:42 PASS 104.35737
'21-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert.cache_mode.directsync' Finshed 2020-07-01 09:22:42 2020-07-01 09:24:23 PASS 100.674479
'22-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert.cache_mode.writethrough' Finshed 2020-07-01 09:24:23 2020-07-01 09:26:14 PASS 110.755192
'23-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_qcow2_convert' Finshed 2020-07-01 09:26:14 2020-07-01 09:27:56 PASS 102.864128
'24-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_luks_convert' Finshed 2020-07-01 09:27:56 2020-07-01 09:30:38 PASS 162.071785

LGTM
ACK

**Comment by zhencliu** [comment]
(01/22) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert: PASS (1180.88 s)
 (02/22) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert.cache_mode.none: PASS (1728.06 s)
 (03/22) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert.cache_mode.writeback: PASS (1615.56 s)
 (04/22) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert.cache_mode.unsafe: PASS (1557.02 s)
 (05/22) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert.cache_mode.directsync: PASS (1820.53 s)
 (06/22) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_raw_convert.cache_mode.writethrough: PASS (1845.78 s)
 (07/22) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_qcow2_convert: PASS (1629.54 s)
 (08/22) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_raw_remote.fmt_luks_convert: PASS (1607.54 s)
 (09/22) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_qcow2_remote.fmt_raw_convert: PASS (1444.57 s)
 (10/22) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_qcow2_remote.fmt_qcow2_convert: PASS (850.53 s)
 (11/22) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_qcow2_remote.fmt_luks_convert: PASS (989.39 s)
 (12/22) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_luks_remote.fmt_raw_convert: PASS (1733.54 s)
 (13/22) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_luks_remote.fmt_qcow2_convert: PASS (1029.75 s)
 (14/22) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_local_to_remote.fmt_luks_remote.fmt_luks_convert: PASS (1157.79 s)
 (15/22) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert: PASS (1420.17 s)
 (16/22) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert.cache_mode.none: PASS (1433.81 s)
 (17/22) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert.cache_mode.writeback: PASS (1443.89 s)
 (18/22) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert.cache_mode.unsafe: PASS (1447.33 s)
 (19/22) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert.cache_mode.directsync: PASS (1458.28 s)
 (20/22) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_raw_convert.cache_mode.writethrough: PASS (1459.77 s)
 (21/22) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_qcow2_convert: PASS (808.87 s)
 (22/22) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_convert.remote_to_remote.fmt_luks_convert: PASS (995.60 s)
RESULTS    : PASS 22 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0


hi @YongxueHong ,can you please help to merge it, thanks.

**Pull request merged**
