### PR TITLE
Remove images after testing to avoid space occupation

### PR DESCRIPTION
**Pull request by maxujun**
Signed-off-by: Xujun Ma <xuma@redhat.com>
ID:2054920

### CODE REVIEW

**Comment by yanan-fu** [comment]
@lkotek  FYI, we hit the same issue in our testing too.

**Comment by maxujun** [comment]
@hellohellenmao @zhencliu Could you help review?

**Comment by zhencliu** [comment]
LGTM

**Comment by maxujun** [comment]
(01/10) Host_RHEL.m8.u6.product_av.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.convert_image_from_raw.to_raw: PASS (290.54 s)
 (02/10) Host_RHEL.m8.u6.product_av.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.convert_image_from_raw.to_qcow2: PASS (262.48 s)
 (03/10) Host_RHEL.m8.u6.product_av.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.convert_image_from_raw.to_qcow2.cache_mode.writethrough: PASS (830.36 s)
 (04/10) Host_RHEL.m8.u6.product_av.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.convert_image_from_raw.to_qcow2.cache_mode.writeback: PASS (240.47 s)
 (05/10) Host_RHEL.m8.u6.product_av.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.convert_image_from_raw.to_qcow2.cache_mode.none: PASS (242.78 s)
 (06/10) Host_RHEL.m8.u6.product_av.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.convert_image_from_raw.to_qcow2.cache_mode.unsafe: PASS (245.84 s)
 (07/10) Host_RHEL.m8.u6.product_av.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.convert_image_from_raw.to_qcow2.cache_mode.directsync: PASS (768.97 s)
 (08/10) Host_RHEL.m8.u6.product_av.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.convert_image_from_raw.to_qcow2.compat_level.compat_0.10: PASS (230.41 s)
 (09/10) Host_RHEL.m8.u6.product_av.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.convert_image_from_raw.to_qcow2.compat_level.compat_default: PASS (240.03 s)
 (10/10) Host_RHEL.m8.u6.product_av.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.convert_image_from_raw.to_luks: PASS (378.00 s)
RESULTS    : PASS 10 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by hellohellenmao** [comment]
LGTM. Thanks.

**Comment by zhencliu** [comment]
@yanan-fu @lkotek would you like a double check? I'll merge it if you don't have comments

**Comment by yanan-fu** [comment]
@zhencliu LGTM, thanks!

**Review by yanan-fu — APPROVED** [review]
Acked-by: Yanan Fu <yfu@redhat.com>

**Comment by lkotek** [comment]
@zhencliu I see no issues here, thanks for fixing this.

**Comment by zhencliu** [comment]
> @zhencliu I see no issues here, thanks for fixing this.

Thanks.

**Pull request merged**
