### PR TITLE
transfer_file_over_ipv6: Add IPv6 address type

### PR DESCRIPTION
**Pull request by yanglei-rh**
1.Add linklocal and remote IPv6 addr for windows and linux

ID:2074848

Signed-off-by: Lei Yang <leiayang@redhat.com>

### CODE REVIEW

**Comment by yanglei-rh** [comment]
Test Pass
(1/1) Host_RHEL.m8.u7.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.bigfile_transfer_over_ipv6.link_local_addr.q35: PASS 
(2/3) Host_RHEL.m8.u7.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.x86_64.io-github-autotest-qemu.bigfile_transfer_over_ipv6.remote_addr.q35: PASS (423.61 s)
(3/3) Host_RHEL.m8.u7.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.x86_64.io-github-autotest-qemu.bigfile_transfer_over_ipv6.link_local_addr.q35: PASS (412.68 s)

**Comment by yanglei-rh** [comment]
Hello @PaulYuuu Please help me review this patch, thanks a lot.

**Comment by PaulYuuu** [comment]
> 1.Configure different ipv6 address types for windows and linux
Will, maybe windows disabled the DHCPv6 service? I am not sure, you can login the guest for checking.

And this will introduce a new variant, so @yanan-fu @lkotek, I think you guys need to know about this change as well.

> 
> ID:2074848
> 
> Signed-off-by: Lei Yang [leiayang@redhat.com](mailto:leiayang@redhat.com)

**Comment by yanan-fu** [comment]
> > 1.Configure different ipv6 address types for windows and linux
> > Will, maybe windows disabled the DHCPv6 service? I am not sure, you can login the guest for checking.
> 
> And this will introduce a new variant, so @yanan-fu @lkotek, I think you guys need to know about this change as well.

@PaulYuuu Thanks for your reminder.  Yes, it is. There are some discussion in the issue, you can have a look too.

**Comment by yanglei-rh** [comment]
> > 1.Configure different ipv6 address types for windows and linux
> > Will, maybe windows disabled the DHCPv6 service? I am not sure, you can login the guest for checking.
I will check this problem, then update result.
> 
> And this will introduce a new variant, so @yanan-fu @lkotek, I think you guys need to know about this change as well.
> 
> > ID:2074848
> > Signed-off-by: Lei Yang [leiayang@redhat.com](mailto:leiayang@redhat.com)

**Comment by yanglei-rh** [comment]
> > > 1.Configure different ipv6 address types for windows and linux
> > > Will, maybe windows disabled the DHCPv6 service? I am not sure, you can login the guest for checking.
> > > I will check this problem, then update result.
> > 
> > 
> > And this will introduce a new variant, so @yanan-fu @lkotek, I think you guys need to know about this change as well.
> > > ID:2074848
> > > Signed-off-by: Lei Yang [leiayang@redhat.com](mailto:leiayang@redhat.com)
@PaulYuuu  @yanan-fu  @lkotek I didn't find` DHCPv6 Service` in Guest, but IPv6 protocols in the network properties are open status.

**Comment by yanglei-rh** [comment]
(1/2) Host_RHEL.m8.u7.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.bigfile_transfer_over_ipv6.remote_addr.q35: PASS (582.05 s)
 (2/2) Host_RHEL.m8.u7.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.bigfile_transfer_over_ipv6.link_local_addr.q35: PASS (627.42 s)
(1/2) Host_RHEL.m8.u7.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.x86_64.io-github-autotest-qemu.bigfile_transfer_over_ipv6.remote_addr.q35: PASS (580.48 s)
 (2/2) Host_RHEL.m8.u7.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.x86_64.io-github-autotest-qemu.bigfile_transfer_over_ipv6.link_local_addr.q35: PASS (673.96 s)

**Comment by yanglei-rh** [comment]
@PaulYuuu Please help me review it again, thanks a lot.

**Review by PaulYuuu — APPROVED** [review]

**Pull request merged**
