### PR TITLE
blockdev_inc_backup_expose_active_bitmap: Expose an active bitmap

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1937633

### CODE REVIEW

**Comment by zhencliu** [comment]
local fs:
 (1/1) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_expose_active_bitmap.q35: PASS (121.53 s)

iscsi direct + virtio blk:
 (1/1) Host_RHEL.m8.u3.iscsi_direct.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_expose_active_bitmap.q35: PASS (79.37 s)

nbd:
 (1/1) Host_RHEL.m9.u0.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_expose_active_bitmap: PASS (58.54 s)

ceph:
 (1/1) Host_RHEL.m8.u3.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_expose_active_bitmap.q35: PASS (94.80 s)

**Comment by zhencliu** [comment]
hi @ngu-niny @YongxueHong , can you please help to review this  patch? Thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by ngu-niny** [comment]
Test PASS:

(5/6) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_expose_active_bitmap:  PASS (141.62 s)

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
