### PR TITLE
Remove Win11 guest support for some hotplug cases

### PR DESCRIPTION
**Pull request by huangyum**
Signed-off-by: Yumei Huang <yuhuang@redhat.com>
ID: 1999356

### CODE REVIEW

**Comment by huangyum** [comment]
@yanan-fu Would you pls help review, thanks.

**Comment by yanan-fu** [comment]
LGTM

Acked-by: Yanan Fu <yfu@redhat.com>

**Comment by yanan-fu** [comment]
Call for dryrun test result with the patch, thanks!

**Comment by huangyum** [comment]
Ran the case with Win11 guest, no test suite created.
python3 ConfigTest.py --testcase=balloon_memhp,invalid_cpu_device_hotplug,cpu_device_hotpluggable --guestname=Win11 --clone=no --dryrun
...
INFO:root:Config provided, ignoring config vt.qemu.nettype
INFO:root:Config provided, ignoring monitor setting
INFO:root:Config provided, ignoring config vt.qemu.smp
INFO:root:Config provided, ignoring config vt.qemu.image_type
INFO:root:Config provided, ignoring config vt.qemu.nic_model
INFO:root:Config provided, ignoring config vt.qemu.disk_bus
INFO:root:Config provided, ignoring config vt.qemu.vhost
INFO:root:Config provided, ignoring config vt.qemu.sandbox
Test Suite could not be created. No test references provided nor any other arguments resolved into tests

While with same cmd with Win2019 guest, 19 test cases displayed.

**Review by yanan-fu — APPROVED** [review]

**Pull request merged**
