### PR TITLE
qemu_guest_gent: change test logic for case 'guest-fstrim'

### PR DESCRIPTION
**Pull request by 6-dehan**
1. disable 'quick format' when format storage.qcow2 inside VM
2. change the times of loop of creating fragment to match  test logic and strategy.
3. delete a checkpoint that query original BLOCK data after formatting disk.

ID: 2209261
Signed-off-by: demeng <demeng@redhat.com>

### CODE REVIEW

**Comment by vivianQizhu** [comment]
@peixiu Would you please help confirm if the checkpoint all make sense from storage perspective? Thanks.

**Comment by peixiu** [comment]
> @peixiu Would you please help confirm if the checkpoint all make sense from storage perspective? Thanks.



> @peixiu Would you please help confirm if the checkpoint all make sense from storage perspective? Thanks.

Sure～

Hi @6-dehan , 

All looks good, just one thing want to ask: 
Do you need "discard_granularity" : 33554432  as well? I'm not sure if you also hit the fstrim slowly problem if without this.

BR~
Peixiu

**Comment by 6-dehan** [comment]
> > @peixiu Would you please help confirm if the checkpoint all make sense from storage perspective? Thanks.
> 
> Sure～
> 
> Hi @6-dehan ,
> 
> All looks good, just one thing want to ask: Do you need "discard_granularity" : 33554432 as well? I'm not sure if you also hit the fstrim slowly problem if without this.
> 
> BR~ Peixiu

That has been merged already. no worries.

**Comment by peixiu** [comment]
OK, LGTM~ 

Thanks~
Peixiu

**Review by peixiu — APPROVED** [review]

**Review by vivianQizhu — APPROVED** [review]

**Comment by vivianQizhu** [comment]
Thanks @6-dehan @peixiu

**Pull request merged**
