### PR TITLE
add block device snapshot test

### PR DESCRIPTION
**Pull request by xutian**
ID: 1786051

Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
INFO | Start to run test
JOB ID     : 0c4550d3ffa8e0f383b0296d340a3385d6b9afb1
JOB LOG    : /root/avocado/job-results/job-2019-12-19T16.31-0c4550d/job.log
 (1/1) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_snapshot.luks_to_luks: PASS (2.04 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 3.42 s
JOB HTML   : /root/avocado/job-results/job-2019-12-19T16.31-0c4550d/results.html

**Comment by xutian** [comment]
@aliang123 , @ngu-niny  Would you like to help review this pull request, thanks.

**Comment by aliang123** [comment]
I thinks the case is not what i want:
Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_snapshot.refblock_update_part.q35: PASS

**Comment by xutian** [comment]
@aliang123   no such case in my side.

**Comment by xutian** [comment]
@aliang123   no such case in my side.

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_snapshot.q35: PASS

Acked-by: Aihua Liang<aliang@redhat.com>

**Comment by ngu-niny** [comment]
Test PASS on ppc:

'1-Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_snapshot' Finshed 2019-12-23 01:00:21 2019-12-23 01:03:41 PASS 199.987627

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
