### PR TITLE
block_libblkio_release:change repo of source code

### PR DESCRIPTION
**Pull request by qingwangrh**
It should use corresponding build code
instead of public repo.

ID：2100

### CODE REVIEW

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=block_libblkio_release --guestname=RHEL.9.4.0 --firmware=default_bios --nrepeat=10 --clone=no
(01/10) repeat1.Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: STARTED
 (01/10) repeat1.Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: PASS (195.94 s)
 (02/10) repeat2.Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: STARTED
 (02/10) repeat2.Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: PASS (88.72 s)
 (03/10) repeat3.Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: STARTED
 (03/10) repeat3.Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: PASS (129.66 s)
 (04/10) repeat4.Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: STARTED
 (04/10) repeat4.Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: PASS (94.23 s)
 (05/10) repeat5.Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: STARTED
 (05/10) repeat5.Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: PASS (92.24 s)
 (06/10) repeat6.Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: STARTED
 (06/10) repeat6.Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: PASS (80.04 s)
 (07/10) repeat7.Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: STARTED
 (07/10) repeat7.Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: PASS (81.75 s)
 (08/10) repeat8.Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: STARTED
 (08/10) repeat8.Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: PASS (81.11 s)
 (09/10) repeat9.Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: STARTED
 (09/10) repeat9.Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: PASS (80.15 s)
 (10/10) repeat10.Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: STARTED
 (10/10) repeat10.Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: PASS (89.46 s)
RESULTS    : PASS 10 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by qingwangrh** [comment]
@XueqiangWei @zhenyzha please help to review. thanks

**Comment by zhenyzha** [comment]
git am 3992.patch
Applying: block_libblkio_release:change repo of source code
.git/rebase-apply/patch:32: trailing whitespace.
wget ${libblkio_url} || tests_failed "Download libblkio package failed"
warning: 1 line adds whitespace errors.

**Comment by qingwangrh** [comment]
> git am 3992.patch Applying: block_libblkio_release:change repo of source code .git/rebase-apply/patch:32: trailing whitespace. wget ${libblkio_url} || tests_failed "Download libblkio package failed" warning: 1 line adds whitespace errors.

updated

**Comment by XueqiangWei** [comment]
Tested with edk2, the results were passed.
(01/10) repeat1.Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9
.5.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: STARTED
 (01/10) repeat1.Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9
.5.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: PASS (98.66 s)
 (02/10) repeat2.Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9
.5.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: STARTED
 (02/10) repeat2.Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9
.5.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: PASS (75.72 s)
 (03/10) repeat3.Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9
.5.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: STARTED
 (03/10) repeat3.Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9
.5.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: PASS (86.54 s)
 (04/10) repeat4.Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9
.5.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: STARTED
 (04/10) repeat4.Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: PASS (78.65 s)
 (05/10) repeat5.Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: STARTED
 (05/10) repeat5.Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: PASS (81.32 s)
(06/10) repeat6.Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9
.5.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: STARTED
 (06/10) repeat6.Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: PASS (78.27 s)
 (07/10) repeat7.Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: STARTED
 (07/10) repeat7.Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: PASS (78.09 s)
 (08/10) repeat8.Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: STARTED
 (08/10) repeat8.Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: PASS (77.34 s)
 (09/10) repeat9.Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: STARTED
 (09/10) repeat9.Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: PASS (77.08 s)
 (10/10) repeat10.Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: STARTED
 (10/10) repeat10.Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.block_libblkio_release.q35: PASS (77.65 s)

**Review by XueqiangWei — APPROVED** [review]
LGTM,
Acked-by: xuwei@redhat.com

**Comment by zhenyzha** [comment]
git am 3992.patch
Applying: block_libblkio_release:change repo of source code

This test no aarch64, so please ignore me

**Pull request merged**
