### PR TITLE
Migration:Update unstable command "x-multifd" to "multifd" 

### PR DESCRIPTION
**Pull request by wangxianxian**
Drop unstable command "x-multifd", update it to formal
command "multifd".

ID:1720112
Signed-off-by: Xianwang <xianwang@redhat.com>

### CODE REVIEW

**Comment by wangxianxian** [comment]
After confirming with feature developers(Dave and quintela), we just need to test "multifd" and don't need to test "x-multifd", the latter is unstable, so, update command "x-multifd" to "multifd"

**Comment by wangxianxian** [comment]
Test result PASS.
@leexiaohui32 @zhenyzha 
please help to review it, thanks

**Comment by zhenyzha** [comment]
with tcp:
 (1/4) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.extra_c
drom_ks.default_install.aio_threads: PASS (1518.13 s)
 (2/4) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.rh_kernel_update: PASS (273.67 s
)
 (3/4) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.migrate.tcp.with_filter_off.with
_post_copy: PASS (99.80 s)
 (4/4) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.migrate.tcp.with_filter_off.with
_multifd: PASS (96.00 s)

with unix:
 (1/3) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.extra_c
drom_ks.default_install.aio_threads: PASS (1481.74 s)
 (2/3) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.rh_kernel_update: PASS (248.31 s
)
 (3/3) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.migrate.unix.with_filter_off.wit
h_multifd: PASS (94.71 s)

Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Comment by huangyum** [comment]
Do you have a test result on older version qemu, like 2.12?

**Comment by zhenyzha** [comment]
> Do you have a test result on older version qemu, like 2.12?

Yes ,It will skip the test, I think it's in line with expectations.
with tcp:
(1/1) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.migrate.tcp.with_filter_off.with_multifd: CANCEL: Got host qemu version:2.12.0-81, which is not in [4.0.0,) (2.34 s)

with unix:
 (1/1) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.migrate.unix.with_filter_off.wit
h_multifd: CANCEL: Got host qemu version:2.12.0-81, which is not in [4.0.0,) (2.34 s)

**Comment by YongxueHong** [comment]
Acked-by: Yongxue Hong <yhong@redhat.com>

**Comment by ldoktor** [comment]
Hello guys, this patch was not really necessary as there is a systematic solution to allow both: https://github.com/avocado-framework/avocado-vt/pull/2022 as multifd migration works even with 2.x versions... Not sure whether we want to stop testing there.

PS: Does multifd migration works on latest master for you? It used to work like a charm on <4 and now with 4.x it's failing all the times for me. I mean it usually works well for single migration, but with `ping_pong=10` it always fails (unlike with <4.0).

**Comment by ldoktor** [comment]
Btw I'm not sure whether to revert this patch, or maybe just propose the `x_multifd` variant that would require qemu `<4.0`. What do you prefer?

**Pull request merged**
