### PR TITLE
netperf_udp_perf: remove nic_index=1 in vm.copy_files_to

### PR DESCRIPTION
**Pull request by quanwenli**
Signed-off-by: Wenli Quan <wquan@redhat.com>

id: 1952373

### CODE REVIEW

**Comment by quanwenli** [comment]
JOB LOG    : /root/avocado/job-results/job-2021-04-22T03.36-6b9be5d/job.log
 (1/5) 82599.bridge_test.1q.acceptance.repeat1.Host_RHEL.m8.u4.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.netperf_udp_perf.q35: PASS (204.81 s)
 (2/5) 82599.bridge_test.1q.acceptance.repeat2.Host_RHEL.m8.u4.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.netperf_udp_perf.q35: PASS (198.22 s)
 (3/5) 82599.bridge_test.1q.acceptance.repeat3.Host_RHEL.m8.u4.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.netperf_udp_perf.q35: PASS (197.35 s)
 (4/5) 82599.bridge_test.1q.acceptance.repeat4.Host_RHEL.m8.u4.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.netperf_udp_perf.q35: PASS (197.80 s)
 (5/5) 82599.bridge_test.1q.acceptance.repeat5.Host_RHEL.m8.u4.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.netperf_udp_perf.q35: PASS (197.37 s)
RESULTS    : PASS 5 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2021-04-22T03.36-6b9be5d/results.html
JOB TIME   : 997.17 s

**Comment by quanwenli** [comment]
@vivianQizhu , could you help review it. Thanks.

**Comment by vivianQizhu** [comment]
@quanwenli Would you help introduce why we have `nic_index=1` previously and why it passed before but now it does not?

**Comment by quanwenli** [comment]
> @quanwenli Would you help introduce why we have `nic_index=1` previously and why it passed before but now it does not?

Default two nics boot up, so it will be nic_index=1, but once, I tried one nic in my test loop, then it failed with nic_index=1.

**Comment by vivianQizhu** [comment]
> > @quanwenli Would you help introduce why we have `nic_index=1` previously and why it passed before but now it does not?
> 
> Default two nics boot up, so it will be nic_index=1, but once, I tried one nic in my test loop, then it failed with nic_index=1.

I mean, why it previously specified it to the second nic, there should be some benefit, right? Directly remove it might loss this benefit?

**Comment by quanwenli** [comment]
> > > @quanwenli Would you help introduce why we have `nic_index=1` previously and why it passed before but now it does not?
> > 
> > 
> > Default two nics boot up, so it will be nic_index=1, but once, I tried one nic in my test loop, then it failed with nic_index=1.
> 
> I mean, why it previously specified it to the second nic, there should be some benefit, right? Directly remove it might loss this benefit?

it inherits from netperf case, the second card is for data transfer and first card is for test. but for case netperf_udp_perf, one or two nics both are ok.

**Comment by vivianQizhu** [comment]
@quanwenli Thanks for the demonstration, it looks good to me now.

**Review by vivianQizhu — APPROVED** [review]

**Pull request merged**
