### PR TITLE
win_driver_utils: update cmd based on guest os version

### PR DESCRIPTION
**Pull request by xiagao**
Get windows os release build version, if version is bigger than 14393, the new pnputil flag will be used.
ID: 2511

### CODE REVIEW

**Comment by xiagao** [comment]
@leidwang Could you help review this patch? thx.

**Review by leidwang — APPROVED** [review]
LGTM, please add test results to the PR,thanks.

**Comment by xiagao** [comment]
(1/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.win_virtio_driver_install_by_installer.driver_uninstall.by_installer.q35: STARTED
 (1/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.win_virtio_driver_install_by_installer.driver_uninstall.by_installer.q35: PASS (599.68 s)
 (2/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.win_virtio_driver_install_by_installer.driver_uninstall.by_installer.q35: STARTED
 (2/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.win_virtio_driver_install_by_installer.driver_uninstall.by_installer.q35: PASS (960.71 s)

**Comment by xiagao** [comment]
@vivianQizhu Call for your review,thanks.

**Review by vivianQizhu — APPROVED** [review]

**Pull request merged**
