### PR TITLE
snapshot test on nbd

### PR DESCRIPTION
**Pull request by zhencliu**
ID: 1845057

### CODE REVIEW

**Comment by zhencliu** [comment]
@XueqiangWei @YongxueHong Can you please help to review the case, thanks.
--testcase=remote_image_snapshot


 (1/1) Host_RHEL.m8.u2.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.remote_image_snapshot.to_local: PASS (120.56 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 123.96 s
JOB HTML   : /root/avocado/job-results/job-2020-06-15T16.16-2df8a97/results.html

**Comment by zixi-chen** [comment]
'3-Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_snapshot.to_local' Finshed 2020-07-01 04:36:36 2020-07-01 04:38:15 PASS 99.273428

LGTM
ACK

**Comment by zhencliu** [comment]
with latest vt patch
 (1/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.migration_with_remote_storage: PASS (302.79 s)
 (2/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.migration_with_remote_storage.with_post_copy: PASS (118.14 s)
 (3/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_snapshot.to_local: PASS (208.71 s)
 (4/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_qcow2: PASS (144.16 s)
 (5/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_raw: PASS (147.89 s)
 (6/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_luks: PASS (173.43 s)
 (7/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_qcow2: PASS (169.89 s)
 (8/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_raw: PASS (158.17 s)
 (9/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_luks: PASS (151.73 s)
RESULTS    : PASS 9 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by zhencliu** [comment]
(1/1) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_snapshot.to_local: PASS (215.95 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

hi @YongxueHong ,can you please help to merge it, thanks

**Pull request merged**
