### PR TITLE
nic_bonding: Use 'ip link' instead of 'set_link'

### PR DESCRIPTION
**Pull request by PaulYuuu**
All devices will loss some packets during set_link loop, Since we are
testing the bonding function of the guest, we should send the "ip link
set dev {iface} up/down" command inside the guest instead of sending the
"set_link" via qemu.

ID: 1698838

Signed-off-by: Yihuang Yu <yihyu@redhat.com>

### CODE REVIEW

**Comment by PaulYuuu** [comment]
@xiywang @YongxueHong Please help to review, thanks!

**Comment by PaulYuuu** [comment]
@pezhang I just test the spapr-vlan device, not sure if e1000e or other device have the same problem, please have a check.

**Comment by PaulYuuu** [comment]
(1/2) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.1.ppc64le.io-github-autotest-qemu.nic_bonding: PASS (342.58 s)
(2/2) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.spapr-vlan.Guest.RHEL.8.0.1.ppc64le.io-github-autotest-qemu.nic_bonding: PASS (702.18 s)

**Comment by PaulYuuu** [comment]
@YongxueHong Updated codes with your suggestion.

**Comment by PaulYuuu** [comment]
> LGTM.
> 
> Remember to modify conversation 1 since you moved step 2 into seperate PR.
> 
> Acked-by: Xiyue Wang [xiywang@redhat.com](mailto:xiywang@redhat.com)

@xiywang Thanks for your reminder, updated.

**Comment by PaulYuuu** [comment]
Okay, I did a bit investigation, it seems other virtual network devices also hit this problem except virtio-net-pci. I suggest only virtio device uses `set_link`, other devices use `ip link`.

During set_link loop:
- rtl8139
88 packets transmitted, 15 received, +4 errors, 82% packet loss, time 87000ms
- e1000
224 packets transmitted, 40 received, 82% packet loss, time 223018ms


@pezhang  @xiywang Also need to you reconfirm.

**Comment by pezhang** [comment]
@PaulYuuu Following test case steps and considering your testing results in above Comment, I think it's better to replace "set_link" with "ip link" for x86_64 too.  Thank you.

**Comment by pezhang** [comment]
A tiny update might be needed: 
In line 19 ofnic_bonding.py, "4) Repeatedly put down/up interfaces by set_link"  need to be changed as "... by 'ip link' ".

Test PASS.

 (1/1) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.nic_bonding: PASS (379.44 s)

**Comment by PaulYuuu** [comment]
@pezhang Updated.

**Comment by pezhang** [comment]
Test PASS.
 (1/1) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.nic_bonding: PASS (345.71 s)

Looks good to me.
Acked by: Pei Zhang pezhang@redhat.com

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

**Comment by vivianQizhu** [comment]
Thanks @PaulYuuu for the fix, and thanks all for the reviewing, merging.

**Pull request merged**
