### PR TITLE
storage_benchmark: Update the command of making iozone

### PR DESCRIPTION
**Pull request by YongxueHong**
Make sure that the environment of making iozone is clean.

ID: 1753139
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by YongxueHong** [comment]
@XueqiangWei  @lolyu  @zhenyzha  pls help review, thanks.

**Comment by lolyu** [comment]
LGTM

**Comment by XueqiangWei** [comment]
LGTM,
Acked-by xuwei@redhat.com

**Comment by zhenyzha** [comment]
(01/11) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (2457.03 s)
 (02/11) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.rh_kernel_update: PASS (202.82 s)
 (03/11) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.migration_with_block.with_scsi_on2off.send_qmp.shutdown_vm: PASS (334.51 s)
 (04/11) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.migration_with_block.with_scsi_on2off.send_qmp.reboot_vm: PASS (350.16 s)
 (05/11) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.migration_with_block.with_scsi_on2off.send_shell.shutdown_vm: PASS (289.99 s)
 (06/11) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.migration_with_block.with_scsi_on2off.send_shell.reboot_vm: PASS (358.50 s)
 (07/11) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.migration_with_block.with_dataplane_on2off.send_qmp.shutdown_vm: PASS (298.78 s)
 (08/11) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.migration_with_block.with_dataplane_on2off.send_qmp.reboot_vm: PASS (364.53 s)
 (09/11) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.migration_with_block.with_dataplane_on2off.send_shell.shutdown_vm: PASS (302.75 s)
 (10/11) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.migration_with_block.with_dataplane_on2off.send_shell.reboot_vm: PASS (372.13 s)
 (11/11) Host_RHEL.m8.u1.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.1.0.ppc64le.io-github-autotest-qemu.migration_with_block.with_post_copy.with_mem_stress: PASS (447.92 s)

LGTM.
Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Comment by YongxueHong** [comment]
Thanks all.

**Pull request merged**
