### PR TITLE
blockdev_inc_backup_bitmap_size: Estimate bitmap size

### PR DESCRIPTION
**Pull request by zhencliu**
Add bitmap with the default granularity
Add bitmap with different granularities
Estimate space utilization for bitmaps

Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1939307, 1939308

### CODE REVIEW

**Comment by zhencliu** [comment]
(1/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_bitmap_size.with_default_granularity.q35: PASS (34.45 s)
 (2/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_bitmap_size.with_different_granularity.q35: PASS (36.75 s)

**Comment by zhencliu** [comment]
hi @ngu-niny @YongxueHong , can you please help to review this path? Thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by ngu-niny** [comment]
(1/3) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_bitmap_size.with_default_granularity: PASS (38.87 s)
 (2/3) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_bitmap_size.with_different_granularity: PASS (48.42 s)

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
