### PR TITLE
Spapr: remove image_snapshot from the cfg

### PR DESCRIPTION
**Pull request by MiriamDeng**
ID:2187127
Signed-off-by: Miriam Deng <mdeng@redhat.com>

### CODE REVIEW

**Comment by MiriamDeng** [comment]
@maxujun @PaulYuuu Could you help to review it ? Thanks !

**Comment by MiriamDeng** [comment]
(1/5) Host_RHEL.m8.u8.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: STARTED
 (1/5) Host_RHEL.m8.u8.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (1503.46 s)
 (2/5) Host_RHEL.m8.u8.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.ppc64le.io-github-autotest-qemu.spapr_vty_multi_backends.all_current_backend: STARTED
 (2/5) Host_RHEL.m8.u8.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.ppc64le.io-github-autotest-qemu.spapr_vty_multi_backends.all_current_backend: PASS (412.80 s)
 (3/5) Host_RHEL.m8.u8.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.ppc64le.io-github-autotest-qemu.spapr_vty_multi_backends.max_backend: STARTED
 (3/5) Host_RHEL.m8.u8.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.ppc64le.io-github-autotest-qemu.spapr_vty_multi_backends.max_backend: PASS (633.80 s)
 (4/5) Host_RHEL.m8.u8.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.ppc64le.io-github-autotest-qemu.spapr_vty_multi_backends.negative_test: STARTED
 (4/5) Host_RHEL.m8.u8.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.ppc64le.io-github-autotest-qemu.spapr_vty_multi_backends.negative_test: PASS (623.54 s)
 (5/5) Host_RHEL.m8.u8.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.ppc64le.io-github-autotest-qemu.spapr_vty_multi_backends.migration: STARTED
 (5/5) Host_RHEL.m8.u8.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.ppc64le.io-github-autotest-qemu.spapr_vty_multi_backends.migration: PASS (420.71 s)

**Comment by maxujun** [comment]
Spelling mistake for imgage_snapshot

**Comment by MiriamDeng** [comment]
> Spelling mistake for imgage_snapshot

Updated, thanks ! Please help to review it again @maxujun

**Comment by maxujun** [comment]
LGTM，Acked.

**Review by PaulYuuu — APPROVED** [review]

**Pull request merged**
