### PR TITLE
blockdev_stream_general: Add general block stream test

### PR DESCRIPTION
**Pull request by zhencliu**
job-cancel/job-resume/job-pause/auto-finalize/auto-dismiss

Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1902534

### CODE REVIEW

**Comment by zhencliu** [comment]
local fs:
 (1/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_on.auto_finalize_on.q35: PASS (196.36 s)
 (2/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_on.auto_finalize_off.q35: PASS (207.99 s)
 (3/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_off.auto_finalize_on.q35: PASS (204.26 s)
 (4/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_off.auto_finalize_off.q35: PASS (202.18 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-01T02.02-392e6dd/results.html
JOB TIME   : 813.80 s

nbd:
 (1/4) Host_RHEL.m8.u3.product_av.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_on.auto_finalize_on: PASS (241.14 s)
 (2/4) Host_RHEL.m8.u3.product_av.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_on.auto_finalize_off: PASS (241.96 s)
 (3/4) Host_RHEL.m8.u3.product_av.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_off.auto_finalize_on: PASS (241.07 s)
 (4/4) Host_RHEL.m8.u3.product_av.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_off.auto_finalize_off: PASS (242.78 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-01T03.43-6bf442c/results.html
JOB TIME   : 969.90 s

ceph:
 (1/4) Host_RHEL.m8.u3.product_av.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_on.auto_finalize_on.q35: PASS (192.25 s)
 (2/4) Host_RHEL.m8.u3.product_av.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_on.auto_finalize_off.q35: PASS (186.52 s)
 (3/4) Host_RHEL.m8.u3.product_av.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_off.auto_finalize_on.q35: PASS (186.71 s)
 (4/4) Host_RHEL.m8.u3.product_av.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_off.auto_finalize_off.q35: PASS (186.61 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-01T16.47-2f87647/results.html
JOB TIME   : 757.89 s

iscsi direct + virtio-blk:
 (1/4) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_on.auto_finalize_on.q35: PASS (156.91 s)
 (2/4) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_on.auto_finalize_off.q35: PASS (157.01 s)
 (3/4) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_off.auto_finalize_on.q35: PASS (153.56 s)
 (4/4) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_off.auto_finalize_off.q35: PASS (157.23 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-01T18.23-c4e9f9a/results.html
JOB TIME   : 628.98 s

**Comment by zhencliu** [comment]
hi @YongxueHong @ngu-niny , can you please help to review this patch? Thanks

**Comment by ngu-niny** [comment]
Test PASS:

 (1/4) type_specific.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_on.auto_finalize_on: PASS (261.26 s)
 (2/4) type_specific.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_on.auto_finalize_off: PASS (277.83 s)
 (3/4) type_specific.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_off.auto_finalize_on: PASS (271.93 s)
 (4/4) type_specific.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_off.auto_finalize_off: PASS (278.45 s)

Acked-by: Nini Gu <ngu@redhat.com>

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
