### PR TITLE
virtio_fs: some optimization and bug fix

### PR DESCRIPTION
**Pull request by xiagao**
1. virtio_fs: use session.cmd to instead of session.sendline
 Using "cd /d c:\" to instead of "C:", because the previous one
    has exit code. So can use session.cmd() directory which
    is more usable than session.sendline().

2.  virtio_fs: some update of virtio_servic_stop_start
 This viofs_sc_stop_cmd is only for viofs_service_stop_start test
    case, we should limit it to it's work scope to avoid
    other cases' error. And for stop/start steps, use a more resonable way to check
    the service status.

ID: 2112744,  2112791
Signed-off-by: Xiaoling Gao <xiagao@redhat.com>

### CODE REVIEW

**Comment by xiagao** [comment]
@leidwang Could you help review?thx

**Comment by leidwang** [comment]
Hi @xiagao Could you provide all related cases test results here?

**Comment by xiagao** [comment]
--testcase=virtio_fs_share_data..git_init,virtio_fs_share_data..viofs_service_stop_start,virtio_fs_share_data_multi_backend.default.with_folder.with_cache.auto..default.with_nfs_source,virtio_fs_share_data.default.default.with_cache.always.default --guestname=Win2022

(1/5) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: STARTED
 (1/5) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (1427.67 s)
 (2/5) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_folder.with_cache.auto.with_nfs_source.q35: STARTED
 (2/5) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_folder.with_cache.auto.with_nfs_source.q35: FAIL: The folder are not deleted. (378.62 s)
 (3/5) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.git_init.q35: STARTED
 (3/5) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.git_init.q35: PASS (135.76 s)
 (4/5) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.viofs_service_stop_start.q35: STARTED
 (4/5) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.viofs_service_stop_start.q35: PASS (141.12 s)
 (5/5) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.always.q35: STARTED
 (5/5) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.always.q35: PASS (129.76 s)

**Comment by xiagao** [comment]
@leidwang update.
@YongxueHong Also call your review,thx.

**Comment by leidwang** [comment]
LGTM.

**Review by leidwang — APPROVED** [review]

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
