### PR TITLE
x86_cpu_model: Add '-cpu host' test case

### PR DESCRIPTION
**Pull request by huangyum**
ID: 1817836
Signed-off-by: Yumei Huang <yuhuang@redhat.com>

### CODE REVIEW

**Comment by huangyum** [comment]
Host_RHEL.m7.u9.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.8.x86_64.io-github-autotest-qemu.x86_cpu_model.host: PASS (84.27 s)

**Comment by yanan-fu** [comment]
@huangyum  The internal cfg may add some other flags together with `enforce,check`, such as "kvm_pv_unhalt",  is this acceptable ?

**Comment by huangyum** [comment]
@yanan-fu Yes, it's fine. The other flags are to improve guest performance, should not affect the cpu flags passthrough.

**Comment by yanan-fu** [comment]
> @yanan-fu Yes, it's fine. The other flags are to improve guest performance, should not affect the cpu flags passthrough.

Ok, thanks !

**Comment by yanan-fu** [comment]
Ack

**Pull request merged**
