### PR TITLE
multi_disk: Add cache option for testing scsi-generic

### PR DESCRIPTION
**Pull request by YongxueHong**
Add cache options "writethrough" and "writeback" for
testing scsi-generic.

ID: 1731613
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by XueqiangWei** [comment]
LGTM,
Acked-by xuwei@redhat.com

**Comment by YongxueHong** [comment]
@peixiu  @qingwangrh  @zhenyzha @lolyu  pls help me to review it, thanks.

**Comment by zhenyzha** [comment]
Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.multi_disk.virtio_scs
i_variants.generic.with_cache_writethrough: PASS (260.91 s)
Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.multi_disk.virtio_scs
i_variants.generic.with_cache_writeback: PASS (236.03 s)


 Host_RHEL.m8.u2.product_av.qcow2.spapr_vscsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.multi_disk.spapr_vscsi_variants.generic.with_cache_writethrough: PASS (235.92 s)
Host_RHEL.m8.u2.product_av.qcow2.spapr_vscsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.multi_disk.spapr_vscsi_variants.generic.with_cache_writeback: PASS (228.47 s)

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=multi_disk --guestname=RHEL.8.2 --clone=no 
(1/9) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.multi_disk.one_disk_repeat: PASS (72.99 s)
 (2/9) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.multi_disk.max_disk: PASS (384.82 s)
 (3/9) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.multi_disk.all_drive_format_types: PASS (49.49 s)
 (4/9) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.block: PASS (88.51 s)
 (5/9) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writethrough: PASS (88.37 s)
 (6/9) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writeback: PASS (87.35 s)
 (7/9) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_lun: PASS (1133.65 s)
 (8/9) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_scsiid_lun: PASS (5513.20 s)
 (9/9) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun: PASS (544.68 s)


LGTM

**Comment by peixiu** [comment]
Tested with drive format on win2012 guest, passed. 
(1/2) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writethrough.q35: PASS (187.70 s)
 (2/2) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writeback.q35: PASS (186.35 s)
Tested with blockdev format on win2012 guest, passed.
 (3/7) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writethrough.q35: PASS (182.68 s)
 (4/7) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writeback.q35: PASS (182.06 s)

**But boot command line with blockdev format hasn't diff between with_cache_writeback and with_cache_writethrough, both case boot command with cache.direct=off,cache.no-flush=off.
@YongxueHong @XueqiangWei @qingwangrh could you help to confirm if it's correct? the polarion case only have with cache=writeback command, have not with cache=writethrough.**
Thanks~

**Comment by YongxueHong** [comment]
> ** @YongxueHong @XueqiangWei @qingwangrh could you help to confirm if it's correct? the polarion case only have with cache=writeback command, have not with cache=writethrough.**

Hi, @peixiu @qingwangrh 
It up to you, if you thought don't need to cover the` cache=writethrough`, I could delete it.
Thanks.

**Comment by qingwangrh** [comment]
> **Tested with drive format on win2012 guest, passed.**
> (1/2) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writethrough.q35: PASS (187.70 s)
> (2/2) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writeback.q35: PASS (186.35 s)
> 
> **Tested with blockdev format on win2012 guest, passed.**
> (3/7) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writethrough.q35: PASS (182.68 s)
> (4/7) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writeback.q35: PASS (182.06 s)
> 
> **But boot command line with blockdev format hasn't diff between with_cache_writeback and with_cache_writethrough, both case boot command with cache.direct=off,cache.no-flush=off. @YongxueHong @XueqiangWei @qingwangrh could you help to confirm if it's correct? the polarion case only have with cache=writeback command, have not with cache=writethrough.**
> Thanks~

writeback: cache.writeback=on  cache.direct=off,cache.no-flush=off. 
writethrough:cache.writeback=off cache.direct=off,cache.no-flush=off. 

keep writethrough testing is ok for me.

**Comment by peixiu** [comment]
> > **Tested with drive format on win2012 guest, passed.**
> > (1/2) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writethrough.q35: PASS (187.70 s)
> > (2/2) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writeback.q35: PASS (186.35 s)
> > **Tested with blockdev format on win2012 guest, passed.**
> > (3/7) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writethrough.q35: PASS (182.68 s)
> > (4/7) Host_RHEL.m8.u2.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2012.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writeback.q35: PASS (182.06 s)
> > **But boot command line with blockdev format hasn't diff between with_cache_writeback and with_cache_writethrough, both case boot command with cache.direct=off,cache.no-flush=off. @YongxueHong @XueqiangWei @qingwangrh could you help to confirm if it's correct? the polarion case only have with cache=writeback command, have not with cache=writethrough.**
> > Thanks~
> 
> writeback: cache.writeback=on cache.direct=off,cache.no-flush=off.
> writethrough:cache.writeback=off cache.direct=off,cache.no-flush=off.
> 
> keep writethrough testing is ok for me.

Thanks qinwang, and @YongxueHong, I agree with qinwang, keep writethrough testing for blockdev format as well, so please help to update the code match with qinwang provide  commands, thanks~

**Pull request merged**
