### PR TITLE
Add enabling port mirror with bridge backend

### PR DESCRIPTION
**Pull request by pezhang**
ID: 1634361
Signed-off-by: Pei Zhang <pezhang@redhat.com>

### CODE REVIEW

**Comment by pezhang** [comment]
@sitoliu Thanks for review. Updated.

**Comment by sitoliu** [comment]
Test pass.
Acked-by: Sitong Liu <siliu@redhat.com>

**Comment by vivianQizhu** [comment]
Just confirm, do we need to clean up those set up besides `ip link delete brname`? Will it impact later on test if put this test case in a test loop?

**Comment by pezhang** [comment]
@vivianQizhu Thanks for review. Adding deleting entrance by "/sbin/tc qdisc".

Add a detail explain: "promisc", "/sbin/tc qdisc" and "/sbin/tc filter" are all setup with private bridge, so after deleting this bridge, it'll not affect the next test cases.

Updated and test pass. Please help to review again. Thanks.

**Pull request merged**
