### PR TITLE
Update ovmf restriction for cpu hotplug test cases

### PR DESCRIPTION
**Pull request by huangyum**
Signed-off-by: Yumei Huang <yuhuang@redhat.com>
ID: 1898426

### CODE REVIEW

**Comment by huangyum** [comment]
@yanan-fu Pls help review, thanks.

**Comment by yanan-fu** [comment]
@huangyum  How about `hv_cpu_hotplug` ?

**Comment by huangyum** [comment]
@yanan-fu Updated this one too, thanks.

**Comment by yanan-fu** [comment]
Ack

**Pull request merged**
