### PR TITLE
Fix tpm information in ovmf log change issue on rhel9

### PR DESCRIPTION
**Pull request by qcheng-redhat**
Fix tpm information in ovmf log change issue on rhel9

ID: 1967501

Signed-off-by: Qinghua Cheng <qcheng@redhat.com>

### CODE REVIEW

**Comment by qcheng-redhat** [comment]
Test result:
RHEL9:
python3 ConfigTest.py --testcase=tpm_verify_device.with_emulator.default.with_check_ovmf --guestname=Win10,Win2019 --machine=q35 --firmware=ovmf --clone=no
 (1/2) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.tpm_verify_device.with_emulator.with_check_ovmf.q35: PASS (135.96 s)
 (2/2) Host_RHEL.m9.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.tpm_verify_device.with_emulator.with_check_ovmf.q35: PASS (129.24 s)

RHEL 8.5:
(1/1) Host_RHEL.m8.u5.product_av.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.tpm_verify_device.with_emulator.with_check_ovmf.q35: PASS (115.56 s)

**Comment by qcheng-redhat** [comment]
Hi @YongxueHong , can you help review this patch when you have time ? Thanks.

**Comment by YongxueHong** [comment]
Hi, you commit message format maybe issue:
```
Fix tpm information in ovmf log change issue on rhel9.

ID: 1967501
```
Can not add a period at the end of the header and please delete `ID: 1967501`

Suggestion:
```
tpm_verify_device: Fix tpm information in ovmf log change issue
Add filter for rhel8 since `pattern_check_log` is different between rhel8
and others.
```

**Comment by qcheng-redhat** [comment]
Updated, thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM

**Pull request merged**
