### PR TITLE
add case to test 65536 persistent bitmaps

### PR DESCRIPTION
**Pull request by xutian**
ID: 1784687

Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
@aliang123  @ngu-niny  this case will fail because of product bugs, eg: 1712636

**Comment by xutian** [comment]
@aliang123  and @ngu-niny  can you help to review this pull request, thanks

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_stream.q35: FAIL: AttributeError("'NoneType' object has no attribute 'get_output'",)

**Comment by aliang123** [comment]
ERROR 2-Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.bitmap_boundary_test.q35 -> AttributeError: 'VirtTest' object has no attribute 'failed'

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.bitmap_boundary_test.q35: FAIL: device 'drive_src1' not found!

**Comment by xutian** [comment]
INFO | Start to run test
JOB ID     : 51ca2c21e4bebd7d3705bb7f61bb6d939948ab73
JOB LOG    : /root/avocado/job-results/job-2019-12-24T23.42-51ca2c2/job.log
 (1/1) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.bitmap_boundary_test: PASS (54.19 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 55.64 s
JOB HTML   : /root/avocado/job-results/job-2019-12-24T23.42-51ca2c2/results.html

**Comment by xutian** [comment]
@aliang123 @ngu-niny  updated, and it works in my side, please help to review.

**Comment by xutian** [comment]
@yanan-fu  @aliang123 @ngu-niny  @lolyu would you like to help review this pull request.

**Comment by aliang123** [comment]
ERROR 1-Host_RHEL.m8.u2.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.bitmap_boundary_test.with_data_plane.q35 -> MonitorSocketError: Could not receive data from monitor    ([Errno 104] Connection reset by peer)
PASS 2-Host_RHEL.m8.u2.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.bitmap_boundary_test.q35

case: bitmap_boundary_test.with_data_plane.q35 failed for product bug.
Acked-by: Aihua Liang<aliang@redhat.com>

@ngu-niny , please help to review from ppcle64 side.

**Comment by ngu-niny** [comment]
Test PASS on ppc64le with 65 bitmaps, while the data plane test case failed for product bug:

(1/2) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.bitmap_boundary_test.with_data_plane: ERROR: Could not receive data from monitor    ([Errno 104] Connection reset by peer) (13.72 s)
 (2/2) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.bitmap_boundary_test: PASS (65.24 s)
RESULTS    : PASS 1 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 85.38 s

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
