### PR TITLE
blockdev_inc_backup_merge_external_bitmaps: Merge external bitmaps

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: zhencliu <zhencliu@redhat.com>

ID: 1911582

### CODE REVIEW

**Comment by zhencliu** [comment]
local fs:
 (1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_merge_external_bitmaps: PASS (176.84 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-30T10.40-b2498b4/results.html
JOB TIME   : 179.76 s

iscsi-direct + virtio-blk:
 (1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_merge_external_bitmaps: PASS (177.89 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-30T20.10-cfebedf/results.html
JOB TIME   : 180.84 s

nbd:
 (1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_merge_external_bitmaps: PASS (326.63 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-30T20.19-8d77171/results.html
JOB TIME   : 329.53 s

ceph:
 (1/1) type_specific.io-github-autotest-qemu.blockdev_inc_backup_merge_external_bitmaps: PASS (266.57 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-30T20.27-93755df/results.html
JOB TIME   : 269.13 s

**Comment by zhencliu** [comment]
hi @YongxueHong @ngu-niny , can you please help to review this patch? Thank you.

**Comment by ngu-niny** [comment]
LGTM and test PASS:

 (1/2) Host_RHEL.m8.u4.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_merge_external_bitmaps:  PASS (264.91 s)
 (2/2) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_merge_external_bitmaps:  PASS (289.77 s)


Acked-by: Nini Gu <ngu@redhat.com>

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
