### PR TITLE
blockdev_snapshot: add support for linux only

### PR DESCRIPTION
**Pull request by aliang123**
Add support for linux only on snapshot and stream cases

Signed-off-by: Aihua Liang <aliang@redhat.com>

id: 1825076

### CODE REVIEW

**Comment by yanan-fu** [comment]
Ack

**Comment by yanan-fu** [comment]
@aliang123  How about `blockdev_snapshot_multi_disks.cfg` ?

**Comment by zhencliu** [comment]
ACK

**Comment by aliang123** [comment]
Block jobs won't care which os is running in guest, it just do operation on backend layer(-drive/-blockdev layer). For convenience, just run block jobs on Linux guest.

**Comment by aliang123** [comment]
@yanan-fu , have added "only Linux" for blockdev_snapshot_multi_disks.cfg, please check the second file.

**Comment by yanan-fu** [comment]
@aliang123 yes, you are right, it is my mistake, it is  `blockdev_snapshot_chains.cfg` that not in this patch, but just checked, it already include 'only Linux'. Thanks!


Ack

**Comment by ngu-niny** [comment]
Acked-by: Nini Gu <ngu@redhat.com>

**Comment by aliang123** [comment]
thanks, @ngu-niny, @yanan-fu  and @zhencliu

**Pull request merged**
