### PR TITLE
backup_utils: Added backing-mask-protocol support

### PR DESCRIPTION
**Pull request by zhencliu**
ID: 2677

### CODE REVIEW

**Comment by aliang123** [comment]
blockdev_stream_cor_base and blockdev_stream_subchain can't work well, other cases work fine.

**Review by aliang123 — APPROVED** [review]
Acked the patch.

**Comment by zhencliu** [comment]
hi @XueqiangWei , would you please verify this patch? Thanks.

**Review by XueqiangWei — APPROVED** [review]
LGTM,
Acked-by: xuwei@redhat.com

**Comment by zhencliu** [comment]
Thanks for reviewing this patch, merged.

**Pull request merged**
