### PR TITLE
virtio_serial_empty_line:fix error params format

### PR DESCRIPTION
**Pull request by nanliu-r**
fix cfg file parameters format.

id:1728934
Signed-off-by: Nana Liu <nanliu@redhat.com>

### CODE REVIEW

**Comment by nanliu-r** [comment]
Command:
python3 ConfigTest.py --guestname=RHEL.8.1 --clone=no --testcase=virtio_serial_empty_line --nrepeat=10

Test results:
 (16/20) repeat8.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.host_to_guest: PASS (49.26 s)
 (17/20) repeat9.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.guest_to_host: PASS (49.18 s)
 (18/20) repeat9.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.host_to_guest: PASS (49.47 s)
 (19/20) repeat10.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.guest_to_host: PASS (48.86 s)
 (20/20) repeat10.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.host_to_guest: PASS (49.28 s)
RESULTS    : PASS 20 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 1107.72 s
JOB HTML   : /root/avocado/job-results/job-2019-08-01T14.38-78150a1/results.html

**Comment by nanliu-r** [comment]
@yfu, please help to review this when you are free, thanks.

**Comment by yanan-fu** [comment]
It is my fault that i did not notice the `s` when review the last patch, but why the test are all pass in
https://github.com/autotest/tp-qemu/pull/1823  ?

**Comment by yanan-fu** [comment]
I guess it all use isa-serial

**Comment by yanan-fu** [comment]
Ack

**Comment by nanliu-r** [comment]
> It is my fault that i did not notice the `s` when review the last patch, but why the test are all pass in
> #1823 ?

It's my fault, I mistake the process and when I test change code I didn't use the patch instead of changing the code manually in my test environments.

**Comment by nanliu-r** [comment]
> Ack

Thanks.

**Comment by nanliu-r** [comment]
> I guess it all use isa-serial

yes

**Pull request merged**
