### PR TITLE
tp-qemu: watchdog: Setup the runlevel for "shutdown" scenario before test.

### PR DESCRIPTION
**Pull request by CongSmile**
Signed-off-by: Cong Li <coli@redhat.com>

Based on: avocado-framework/avocado-vt#122
id: 1261771

### CODE REVIEW

**Comment by xutian** [comment]
Acked-by: Xu Tian

**Comment by spcui** [comment]
Acked-by: scui@redhat.com

**Comment by CongSmile** [comment]
Hi @xutian 

I have rebase this PR.
Could you help review it?

Thanks.

**Comment by xutian** [comment]
Merged. thanks @CongSmile

**Pull request merged**
