### PR TITLE
thp_fragment: add compatibility with RHEL 8

### PR DESCRIPTION
**Pull request by mcasquer**
thp_fragment: add compatibility with RHEL 8

Makes the tool compatible with RHEL 8, so MADV_COLD
is now defined in the headers.

Signed-off-by: mcasquer <mcasquer@redhat.com>
ID: 2015

### CODE REVIEW

**Comment by mcasquer** [comment]
Test case passed successfully
```
 (1/1) Host_RHEL.m8.u10.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.x86_64.io-github-autotest-qemu.trans_hugepage.defrag.q35: STARTED
 (1/1) Host_RHEL.m8.u10.product_rhel.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.x86_64.io-github-autotest-qemu.trans_hugepage.defrag.q35: PASS (191.07 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```

**Comment by mcasquer** [comment]
@luckyh @yanan-fu @zhenyzha could you review this PR? Thanks !

**Comment by YongxueHong** [comment]
Hi @mcasquer 
Please help to run the relate cases with RHEL9 and **RHEL7** host(if we still want to cover it), Thanks.

**Comment by yanan-fu** [comment]
Checked the code change within the binary tar file.
```
#ifndef MADV_COLD                                                                           
#define MADV_COLD 20                                                                        
#endif 
```
 LGTM

And +1 with who @YongxueHong mentioned above,  call for a RHEL9 test result please (IMO,  we can ignore RHEL7 as our test framework does not support it officially now)

**Comment by mcasquer** [comment]
Test passed with the current defrag tool on RHEL 9 host + guest
```
# git am 3971.patch
Applying: thp_fragment: add compatibility with RHEL 8
```

```
 (1/1) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.trans_hugepage.defrag.q35: STARTED
 (1/1) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.trans_hugepage.defrag.q35: PASS (429.94 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```

**Review by zhenyzha — APPROVED** [review]
Pass on the arm platform

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
