### PR TITLE
block stream test with vm reboot

### PR DESCRIPTION
**Pull request by zhencliu**
ID: 1881491

### CODE REVIEW

**Comment by zhencliu** [comment]
gluster direct:
 (1/1) Host_RHEL.m8.u3.product_av.gluster_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_reboot: PASS (284.72 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2020-09-22T20.27-b41a732/results.html
JOB TIME   : 288.15 s

local fs:
 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_reboot: PASS (200.95 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-22T07.33-c41c0d4/results.html
JOB TIME   : 206.52 s

iscsi direct:
 (3/3) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_reboot: PASS (190.95 s)
RESULTS    : PASS 2 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-22T08.27-5c6e8dc/results.html
JOB TIME   : 2129.28 s

nbd:
 (1/1) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_reboot: PASS (275.24 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-22T09.39-f503c3a/results.html
JOB TIME   : 280.77 s

hi @aliang123 @YongxueHong , can you please help to review the patch? Thanks.

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_reboot.q35: PASS (333.38 s)

Acked for vm_reboot part firstly.

**Comment by aliang123** [comment]
Have run test with vm_reboot,vm_stop_cont, vm_stress,vm_installtion, all passed.

Acked0-by: Aihua Liang <aliang@redhat.com>

**Comment by zhencliu** [comment]
hi @ngu-niny , can you please help to review this patch? Thanks.

**Comment by ngu-niny** [comment]
@aliang123 @zhencliu Since it's to test the guest reboot scenario, can we test the system disk?

**Comment by zhencliu** [comment]
> @aliang123 @zhencliu Since it's to test the guest reboot scenario, can we test the system disk?

Hi @ngu-niny , you might consider that when VM reboots, some temp files generated/removed, memory flushed, which might cause some issues, from my side, I think #2423 can cover this, i.e. installation and block-stream on the same system disk are running in parallel. 
For this patch, the files has already been created, it might not need to consider where the files locate, please @aliang123 add more comments, thanks.

**Comment by ngu-niny** [comment]
I have talked with @zhencliu, he will update this patch, and also following patches scenarios to system disks. Thanks in advance.

https://github.com/autotest/tp-qemu/pull/2421
https://github.com/autotest/tp-qemu/pull/2422

**Comment by zhencliu** [comment]
> I have talked with @zhencliu, he will update this patch, and also following patches scenarios to system disks. Thanks in advance.
> 
> #2421
> #2422

Thank you @ngu-niny , let's keep the same testing strategy with mirror/commit, I will make some code changes later.

**Comment by zhencliu** [comment]
updated
 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_reboot: PASS (296.01 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-27T11.55-4da89b9/results.html
JOB TIME   : 301.96 s

(1/1) Host_RHEL.m8.u3.product_av.gluster_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_reboot: PASS (688.92 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2020-09-27T23.56-f0888ed/results.html
JOB TIME   : 692.40 s

**Comment by zhencliu** [comment]
(1/3) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_stress: PASS (317.09 s)
 (2/3) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_stop_cont: PASS (291.66 s)
 (3/3) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_reboot: PASS (304.83 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-27T20.47-c1ce6a6/results.html
JOB TIME   : 919.88 s

 (1/3) Host_RHEL.m8.u3.product_av.gluster_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_stop_cont: PASS (672.78 s)
 (2/3) Host_RHEL.m8.u3.product_av.gluster_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_reboot: PASS (696.63 s)
 (3/3) Host_RHEL.m8.u3.product_av.gluster_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_stream_stress: PASS (766.60 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2020-09-28T08.58-9046dce/results.html
JOB TIME   : 2140.55 s

hi @ngu-niny , code updated, can you please help make a double check? Thanks.
hi @YongxueHong , this patch is the 'root' patch, can you please help to review this one first? Thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_reboot.q35: PASS (573.33 s)

acked for test on system disk.

Acked-by: Aihua Liang <aliang@redhat.com>

**Comment by zhencliu** [comment]
(1/3) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_reboot: PASS (766.92 s)
 (2/3) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_stop_cont: PASS (722.71 s)
 (3/3) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_stress: PASS (738.47 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-27T22.07-87dc65a/results.html
JOB TIME   : 2234.10 s

**Comment by ngu-niny** [comment]
Test PASS on PPC and LGTM:

'1-Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.blockdev_stream_vm_stop_cont' Finshed 2020-09-27 22:33:05 2020-09-27 22:40:51 PASS 465.682217
'2-Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.blockdev_stream_vm_reboot' Finshed 2020-09-27 22:40:51 2020-09-27 22:50:04 PASS 552.897328
'3-Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.blockdev_stream_stress' Finshed 2020-09-27 22:50:04 2020-09-27 22:58:16 PASS 492.018477

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
