### PR TITLE
qemu.tests.rh_kernel_update: upgrade package qemu-guest-agent

### PR DESCRIPTION
**Pull request by xutian**
Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
ID: 1386087

**Comment by qunfang** [comment]
LGTM.  Ack'ed.

02:03:25 DEBUG| Running 'brew latest-pkg rhel-7.2-z-candidate qemu-guest-agent --arch=ppc64 --paths'
02:03:25 DEBUG| Brew URL is http://download.devel.redhat.com/brewroot/packages/qemu-guest-agent/2.3.0/4.el7/ppc64/qemu-guest-agent-2.3.0-4.el7.ppc64.rpm
02:03:25 DEBUG| Brew URL is http://download.devel.redhat.com/brewroot/packages/qemu-guest-agent/2.3.0/4.el7/ppc64/qemu-guest-agent-debuginfo-2.3.0-4.el7.ppc64.rpm
02:03:25 INFO | Install packages from: http://download.devel.redhat.com/brewroot/packages/qemu-guest-agent/2.3.0/4.el7/ppc64/qemu-guest-agent-2.3.0-4.el7.ppc64.rpm
02:03:25 DEBUG| Sending command: rpm -Uvhf http://download.devel.redhat.com/brewroot/packages/qemu-guest-agent/2.3.0/4.el7/ppc64/qemu-guest-agent-2.3.0-4.el7.ppc64.rpm --nodeps
02:03:26 DEBUG| Sending command: echo $?
02:03:26 DEBUG| Sending command: rpm -q qemu-guest-agent
02:03:26 INFO | Upgrade 'qemu-guest-agent' from 'qemu-guest-agent-2.3.0-4.el7.ppc64
'  to 'qemu-guest-agent-2.3.0-4.el7.ppc64

**Comment by qunfang** [comment]
LGTM.  Ack'ed.

**Comment by XueqiangWei** [comment]
LGTM,
Acked-by Xueqiang Wei <xuwei@redhat.com>

**Pull request merged**
