### PR TITLE
qemu.test: qemu_img_luks_inside_qcow2_key_management

### PR DESCRIPTION
**Pull request by XueqiangWei**
1. add a new passowrd to free keyslot
2. erase password from keyslot

Signed-off-by: Xueqiang Wei <xuwei@redhat.com>
ID: 1945876

### CODE REVIEW

**Comment by XueqiangWei** [comment]
depends on avocado-framework/avocado-vt/pull/2989

**Comment by XueqiangWei** [comment]
depends on autotest/tp-qemu/pull/2736

**Comment by XueqiangWei** [comment]
(1/7) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img_luks_inside_qcow2_key_management.add_new_password_to_keyslot.with_specified_index.q35: PASS (18.31 s)
 (2/7) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img_luks_inside_qcow2_key_management.add_new_password_to_keyslot.without_index.q35: PASS (18.09 s)
 (3/7) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img_luks_inside_qcow2_key_management.add_new_password_to_keyslot.with_active_keyslot.q35: PASS (12.23 s)
 (4/7) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img_luks_inside_qcow2_key_management.add_new_password_to_keyslot.with_invalid_keyslot.q35: PASS (12.32 s)
 (5/7) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img_luks_inside_qcow2_key_management.erase_password_from_keyslot.with_specified_index.q35: PASS (20.53 s)
 (6/7) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img_luks_inside_qcow2_key_management.erase_password_from_keyslot.with_specified_password.q35: PASS (25.01 s)
 (7/7) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img_luks_inside_qcow2_key_management.erase_password_from_keyslot.with_only_active_keyslot.q35: PASS (12.23 s)

**Comment by XueqiangWei** [comment]
@zhencliu Please help review it. Many thanks.

**Comment by zhencliu** [comment]
LGTM

Let's wait till vt patch is available

**Comment by XueqiangWei** [comment]
(1/7) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img_luks_inside_qcow2_key_management.add_new_password_to_keyslot.with_specified_index.q35: PASS (18.62 s)
 (2/7) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img_luks_inside_qcow2_key_management.add_new_password_to_keyslot.without_index.q35: PASS (18.02 s)
 (3/7) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img_luks_inside_qcow2_key_management.add_new_password_to_keyslot.with_active_keyslot.q35: PASS (12.24 s)
 (4/7) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img_luks_inside_qcow2_key_management.add_new_password_to_keyslot.with_invalid_keyslot.q35: PASS (12.30 s)
 (5/7) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img_luks_inside_qcow2_key_management.erase_password_from_keyslot.with_specified_index.q35: PASS (20.53 s)
 (6/7) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img_luks_inside_qcow2_key_management.erase_password_from_keyslot.with_specified_password.q35: PASS (25.07 s)
 (7/7) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img_luks_inside_qcow2_key_management.erase_password_from_keyslot.with_only_active_keyslot.q35: PASS (12.23 s)

**Comment by XueqiangWei** [comment]
@zhencliu Added the prefix to secret_id and secret_data. Please help review it again. Many thanks.

**Comment by zhencliu** [comment]
VT patch 2736 is to be merged soon, so merge this patch

**Pull request merged**
