### PR TITLE
multi_nics_verify: fix no file of lock-server-running

### PR DESCRIPTION
**Pull request by xiywang**
id: 1641463

Signed-off-by: Xiyue Wang <xiywang@redhat.com>

### CODE REVIEW

**Comment by xiywang** [comment]
(1/1) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.my.multi_nics_verify: PASS (196.91 s)

**Comment by vivianQizhu** [comment]
Looks the error is caused by the previous `session` is closed, so either we do not close it, or do not pass the closed session to `vm.reboot()`, let `vm.reboot()` open another session for the rebooting.

**Comment by vivianQizhu** [comment]
> I can't recall why I need a new_session so I removed it and use session instead.

That doesn't matter, pass a closed session to `vm.reboot()` does not make sense anyway. If you check  the implementation of `vm.reboot()`, you will notice that the `session` pass to it should be `None` or should be available.

**Comment by xiywang** [comment]
Updated.

**Comment by ldoktor** [comment]
Yep, closed session can lead to double cleanups that fails. @xiywang next time please include the description in commit message so people can understand what are you fixing even after a certain period of time (eg. when bisecting some other issue).

Acked-by: Lukáš Doktor <ldoktor@redhat.com>

**Pull request merged**
