### PR TITLE
rebase and commit: clean snapshot after test finish

### PR DESCRIPTION
**Pull request by yanan-fu**
id: 2013899
Signed-off-by: Yanan Fu <yfu@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
@zhencliu @YongxueHong  Could you help review ? Thanks!

**Comment by zhencliu** [comment]
LGTM

**Comment by yanan-fu** [comment]
Thanks @hellohellenmao  Updated, remove the parameter and clean snapshot after test finish. Could you help re-review?  Thanks

@zhencliu Could you help review the latest change, thanks!

**Comment by zhencliu** [comment]
LGTM

@yanan-fu , would you pls re-run the tests and make a double check if these snapshot images are removed?

**Comment by yanan-fu** [comment]
Thanks all!

**Pull request merged**
