### PR TITLE
qemu_guest_agent: fix issue of isa-serial backend

### PR DESCRIPTION
**Pull request by xiagao**
Fail to issue qga command after qga is started up.
ID: 1670248
Signed-off-by: Xiaoling Gao <xiagao@redhat.com>

### CODE REVIEW

**Comment by xiagao** [comment]
@xiangchunfu @lolyu 
Call for your review..

**Comment by xiangchunfu** [comment]
@xiagao 
The reason of failure is not fully booted up for agent service, right? so you add sleep(5).

**Comment by xiagao** [comment]
> @xiagao
> The reason of failure is not fully booted up for agent service, right? so you add sleep(5).

it's isa-serial, maybe I need to add if condition.

**Comment by xiangchunfu** [comment]
Acked by: Xiangchun Fu xfu@redhat.com

**Pull request merged**
