### PR TITLE
Change iperf-2 to latest version

### PR DESCRIPTION
**Pull request by yanglei-rh**
1. Due to the old version can not support the new test case's test requirement, so update iperf-2 to latest version.
2. Since the framework's iperf-2 version has been update to the latest version,the current case is affected, so change to the corresponding version in the configure file.

ID:2034
Signed-off-by: Lei Yang leiyang@redhat.com

### CODE REVIEW

**Comment by yanglei-rh** [comment]
Test pass:
(1/1) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.iperf_test.with_multicast.q35: PASS (131.52 s)

**Comment by yanglei-rh** [comment]
Hello @PaulYuuu Could you please help me review this patch? Thanks a lot.

**Review by PaulYuuu — DISMISSED** [review]

**Comment by PaulYuuu** [comment]
Oh, I think you should also consider the Windows iperf binary.

**Comment by yanglei-rh** [comment]
> Oh, I think you should also consider the Windows iperf binary.

Good point, I will update it after testing.

**Review by PaulYuuu — APPROVED** [review]

**Pull request merged**
