### PR TITLE
x86_cpu_L3_cache:update the checkpoint

### PR DESCRIPTION
**Pull request by nanliu-r**
ID: 1981241

Signed-off-by: Nana Liu <nanliu@redhat.com>

### CODE REVIEW

**Comment by nanliu-r** [comment]
(1/1) Host_RHEL.m8.u5.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.x86_cpu_L3_cache: PASS (444.53 s)

**Comment by nanliu-r** [comment]
@huangyum @yanan-fu  Could you please help to review this? thanks.

**Comment by huangyum** [comment]
Please describe the reason of this change in commit message.

**Comment by yanan-fu** [comment]
Suggest remove `.py` in the commit title~

**Comment by nanliu-r** [comment]
> Suggest remove `.py` in the commit title~

Thanks and update.

**Review by huangyum — COMMENTED** [review]
ACK

**Comment by yanan-fu** [comment]
Ack

**Pull request merged**
