### PR TITLE
live_snapshot: live_snapshot() interface is changed in qemu_monitor.py, update cases to match it.

### PR DESCRIPTION
**Pull request by CongLi**
Signed-off-by: Cong Li <coli@redhat.com>

id: 1344878

### CODE REVIEW

**Comment by CongLi** [comment]
14:33:04 INFO | PASS 1-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.live_snapshot.with_reboot

**Comment by xutian** [comment]
@CongLi  please update all test which call livesnapshot function:
```
[xutian@xutian-dev]$ (master) find ./ -name "*.py" -exec grep live_snapshot  -H -n {} \;
./qemu/tests/block_stream_drop_backingfile.py:73:            device_id = vm.live_snapshot(base_file, snapshot)
./qemu/tests/live_snapshot.py:11:    live_snapshot test:
./qemu/tests/live_snapshot.py:38:        vm.monitor.live_snapshot(device, snapshot_name, format)
./qemu/tests/live_snapshot_base.py:14:    live_snapshot_base test:
./qemu/tests/live_snapshot_base.py:50:        if vm.live_snapshot(base_file, snapshot_file,
./qemu/tests/live_snapshot_chain.py:15:    live_snapshot chain test:
./qemu/tests/live_snapshot_chain.py:88:            vm.live_snapshot(base_file, snapshot_file, snapshot_format)
./qemu/tests/blk_stream.py:56:            device = self.vm.live_snapshot(image_file, snapshot, image_format)
./qemu/tests/qemu_guest_agent_snapshot.py:34:        self.vm.live_snapshot(base_file, sn_file, snapshot_format)
./qemu/tests/live_snapshot_basic.py:78:        self.vm.monitor.live_snapshot(device, self.snapshot_file,
```

**Comment by CongLi** [comment]
@xutian 

1. Only need update those cases which call vm.monitor.live_snapshot() directly.
grep -nr "vm.monitor.live_snapshot"
qemu/tests/live_snapshot.py:38:        vm.monitor.live_snapshot(device, snapshot_name, format)
qemu/tests/live_snapshot_basic.py:78:        self.vm.monitor.live_snapshot(device, self.snapshot_file, **snapshot_args)

2. For those case which call vm.live_snapshot(), no need to update them as interface live_snapshot() in qemu_vm.py has already been updated.
In qemu_vm.py:
    def live_snapshot(self, base_file, snapshot_file, snapshot_format="qcow2"):

**Comment by xutian** [comment]
Ok, just a reminder, hope block nothing.

**Comment by CongLi** [comment]
@xutian 

Thanks for your kindly reminder.
I will paste all related cases results here later.

**Comment by CongLi** [comment]
14:46:45 INFO | PASS 1-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.live_snapshot.with_reboot
14:48:50 INFO | PASS 2-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.live_snapshot.with_runtime
14:51:33 INFO | PASS 3-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.live_snapshot.with_file_transfer
14:57:10 INFO | PASS 1-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.live_snapshot_chain.pause
15:00:40 INFO | PASS 3-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.live_snapshot_chain.long_chain
15:04:13 INFO | PASS 4-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.live_snapshot_chain.check
15:07:04 INFO | PASS 5-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.live_snapshot_chain.oops
15:28:17 INFO | PASS 1-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.live_snapshot.base
15:34:42 INFO | PASS 1-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_snapshot

**Comment by xutian** [comment]
better to test blk_stream test. in my mind, blk_stream test used live_snapshot too.

**Comment by CongLi** [comment]
Here are the block stream related test results:

18:02:53 INFO | PASS 01-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.block_stream.simple_test.start_stream
18:16:14 INFO | PASS 02-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.block_stream.simple_test.set_speed
18:29:23 INFO | PASS 03-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.block_stream.simple_test.reset_speed
18:30:08 INFO | PASS 04-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.block_stream.simple_test.cancel_sync
18:31:18 INFO | PASS 05-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.block_stream.simple_test.cancel_async
18:32:12 INFO | PASS 06-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.block_stream.simple_test.query
18:37:26 INFO | PASS 07-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.block_stream.when_reboot
18:42:20 INFO | PASS 08-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.block_stream.drop_backingfile
18:46:06 INFO | PASS 09-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.block_stream.check_backingfile
18:51:24 INFO | PASS 10-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_scsi.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.block_stream.with_stress

Thanks.

**Comment by xutian** [comment]
looks good to me, thanks @CongLi

**Pull request merged**
