### PR TITLE
qemu.tests.cgroup: Use disk serial number instead of name

### PR DESCRIPTION
**Pull request by ldoktor**
Disks might not be enumerated by kernel in the same order as added on
command line. This patch uses device serial number instead.

Signed-off-by: Lukáš Doktor <ldoktor@redhat.com>

### CODE REVIEW

**Comment by ldoktor** [comment]
Hello @lmr, this one is also related to arm64, which is enumerating the disks in reverse order (thus it's overwriting the OS disk...). I tested it with virtio_scsi on x86 and with virtio-block-device on aarch64.

**Comment by ldoktor** [comment]
it might be better, but not really required. This is easier on implementation + you can rely on the name. (I'm using multiple VMs but always only single disk.

PS: 3,3,3,3,3,3,3,3,... is also a valid random generator, maybe not the best one, but valid...

**Comment by lmr** [comment]
:)

**Comment by lmr** [comment]
Thanks @ldoktor !

**Comment by ldoktor** [comment]
yes, x86_64 Fedora and arm64 RHEL7.

**Pull request merged**
