### PR TITLE
PPC:update some parameter for guest_agent test cases

### PR DESCRIPTION
**Pull request by MiriamDeng**
ID:2230771
Signed-off-by: Miriam Deng <mdeng@redhat.com>

### CODE REVIEW

**Comment by MiriamDeng** [comment]
1-Host_RHEL.m8.u9.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.ppc64le.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_set_user_password.no_crypto Finshed 2023-08-23 04:27:29 2023-08-23 04:29:01 PASS 91.501397
2-Host_RHEL.m8.u9.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.ppc64le.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_set_user_password.crypto Finshed 2023-08-23 04:29:02 2023-08-23 04:30:46 PASS 104.461458
3-Host_RHEL.m8.u9.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.ppc64le.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_get_interfaces Finshed 2023-08-23 04:30:47 2023-08-23 04:32:56 PASS 128.780587

**Comment by MiriamDeng** [comment]
Can you help to review this patch ? @maxujun @PaulYuuu

**Comment by PaulYuuu** [comment]
@MiriamDeng Can you provide some details?

**Comment by maxujun** [comment]
LGTM, Acked.

 (1/5) Host_RHEL.m8.u9.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.ppc64le.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_set_user_password.no_crypto: STARTED
 (1/5) Host_RHEL.m8.u9.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.ppc64le.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_set_user_password.no_crypto: PASS (59.72 s)
 (2/5) Host_RHEL.m8.u9.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.ppc64le.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_set_user_password.crypto: STARTED
 (2/5) Host_RHEL.m8.u9.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.ppc64le.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_set_user_password.crypto: PASS (69.67 s)
 (3/5) Host_RHEL.m8.u9.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.ppc64le.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_set_time: STARTED
 (3/5) Host_RHEL.m8.u9.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.ppc64le.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_set_time: PASS (91.32 s)
 (4/5) Host_RHEL.m8.u9.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.ppc64le.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_set_time.invalid_time: STARTED
 (4/5) Host_RHEL.m8.u9.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.ppc64le.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_set_time.invalid_time: PASS (69.83 s)
 (5/5) Host_RHEL.m8.u9.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.ppc64le.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_get_interfaces: STARTED
 (5/5) Host_RHEL.m8.u9.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.ppc64le.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_get_interfaces: PASS (115.03 s)

**Comment by MiriamDeng** [comment]
> @MiriamDeng Can you provide some details?

Hi PaulYuuu,
The it seems the image_snapshot=yes is not supported for some scenarios on ppc, I confirmed it with xuma before. Thank you  !

**Comment by PaulYuuu** [comment]
> > @MiriamDeng Can you provide some details?
> 
> Hi PaulYuuu, The it seems the image_snapshot=yes is not supported for some scenarios on ppc, I confirmed it with xuma before. Thank you !

I mean when the parameter is set to `yes`, what will happen? Because I cannot see any risk of it. The info is too little.

**Comment by MiriamDeng** [comment]
> > > @MiriamDeng Can you provide some details?
> > 
> > 
> > Hi PaulYuuu, The it seems the image_snapshot=yes is not supported for some scenarios on ppc, I confirmed it with xuma before. Thank you !
> 
> I mean when the parameter is set to `yes`, what will happen? Because I cannot see any risk of it. The info is too little.

The guest can't boot up and the test case can't proceed. Thanks

**Pull request merged**
