### PR TITLE
software_manager: align tp-qemu with changes in avocado

### PR DESCRIPTION
**Pull request by lkotek**
PR alignes tp-qemu with software_manager changes in avocado

See: https://github.com/avocado-framework/avocado/pull/5225

id: 2040126

Signed-off-by: Lukas Kotek <lkotek@redhat.com>

### CODE REVIEW

**Review by yanan-fu — APPROVED** [review]
Ack

**Comment by yanan-fu** [comment]
@qcheng-redhat  Could you please help review ? A test with `nested_test` is needed, thanks!

**Comment by qcheng-redhat** [comment]
LGTM.

Copy relevant log here:

05:40:09 INFO | Running 'rpm -q ansible'
05:40:09 DEBUG| [stdout] package ansible is not installed
05:40:09 INFO | Command 'rpm -q ansible' finished with 1 after 0.005365815s
05:40:09 INFO | Running '/usr/bin/dnf -y install ansible'
05:40:10 DEBUG| [stdout] Updating Subscription Management repositories.
05:40:10 DEBUG| [stdout] Unable to read consumer identity
05:40:10 DEBUG| [stdout]
05:40:10 DEBUG| [stdout] This system is not registered with an entitlement server. You can use subscription-manager to register.
05:40:10 DEBUG| [stdout]
05:40:10 DEBUG| [stderr] Repository rcm-tools-rhel-8-baseos-rpms is listed more than once in the configuration
05:40:10 DEBUG| [stderr] Repository rcm-tools-rhel-8-baseos-source-rpms is listed more than once in the configuration
05:40:10 DEBUG| [stderr] Repository rcm-tools-rhel-8-server-optional-rpms is listed more than once in the configuration
05:40:10 DEBUG| [stderr] Repository rcm-tools-rhel-8-server-optional-source-rpms is listed more than once in the configuration
05:40:10 DEBUG| [stdout] Last metadata expiration check: 2:09:25 ago on Thu Jan 13 03:30:45 2022.
05:40:10 DEBUG| [stdout] Dependencies resolved.
05:40:10 DEBUG| [stdout] ================================================================================
05:40:10 DEBUG| [stdout]  Package           Architecture     Version                Repository      Size
05:40:10 DEBUG| [stdout] ================================================================================
05:40:10 DEBUG| [stdout] Installing:
05:40:10 DEBUG| [stdout]  ansible           noarch           2.9.27-1.el8           epel            17 M
05:40:10 DEBUG| [stdout]
05:40:10 DEBUG| [stdout] Transaction Summary
05:40:10 DEBUG| [stdout] ================================================================================
05:40:10 DEBUG| [stdout] Install  1 Package
05:40:10 DEBUG| [stdout]
05:40:10 DEBUG| [stdout] Total download size: 17 M
05:40:10 DEBUG| [stdout] Installed size: 96 M
05:40:10 DEBUG| [stdout] Downloading Packages:
05:40:14 DEBUG| [stdout] ansible-2.9.27-1.el8.noarch.rpm                 9.3 MB/s |  17 MB     00:01
05:40:14 DEBUG| [stdout] --------------------------------------------------------------------------------
05:40:14 DEBUG| [stdout] Total                                           5.3 MB/s |  17 MB     00:03
05:40:14 DEBUG| [stdout] Running transaction check
05:40:14 DEBUG| [stdout] Transaction check succeeded.
05:40:14 DEBUG| [stdout] Running transaction test
05:40:14 DEBUG| [stdout] Transaction test succeeded.
05:40:14 DEBUG| [stdout] Running transaction
05:40:14 DEBUG| [stdout]   Preparing        :                                                        1/1
05:40:20 DEBUG| [stdout]
05:40:20 DEBUG| [stdout]   Installing       : ansible-2.9.27-1.el8.noarch                            1/1
05:40:21 DEBUG| [stdout]
05:40:21 DEBUG| [stdout]   Running scriptlet: ansible-2.9.27-1.el8.noarch                            1/1
05:40:21 DEBUG| [stdout]
05:40:21 DEBUG| [stdout]   Verifying        : ansible-2.9.27-1.el8.noarch                            1/1
05:40:22 DEBUG| [stdout]
05:40:22 DEBUG| [stdout] Installed products updated.
05:40:22 DEBUG| [stdout]
05:40:22 DEBUG| [stdout] Installed:
05:40:22 DEBUG| [stdout]   ansible-2.9.27-1.el8.noarch
05:40:22 DEBUG| [stdout]
05:40:22 DEBUG| [stdout] Complete!
05:40:22 INFO | Command '/usr/bin/dnf -y install ansible' finished with 0 after 12.426479584s

**Comment by yanan-fu** [comment]
Thanks all!

**Comment by lkotek** [comment]
Great, thank you!

**Pull request merged**
