### PR TITLE
qemu.tests.cfg: update memory hotplug with stress tests cfg

### PR DESCRIPTION
**Pull request by xutian**
ID: 1285323
Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
deps on https://github.com/avocado-framework/avocado-vt/pull/618

**Comment by CongLi** [comment]
IMHO, there is no difference in this fix indeed.
Could you help explain what's the difference?

**Comment by xutian** [comment]
@CongLi  see 1285323 comments#3.

**Comment by CongLi** [comment]
@xutian 

Yes, I saw it.
But I used the previous cfg, test pass.
16:19:07 INFO | PASS 1-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.hotplug_memory.before.stress.hotplug.backend_ram.policy_default.two

        - pause_vm:
            sub_type = stop_continue
            pause_time = 120
            wait_resume_timeout = "${pause_time}"
        - stress:
    variants stage:
        - before:
        - after:
        - during:

**Comment by xutian** [comment]
@CongLi previous  cfg suppose stress really installed via ks file,  now we use autotest.stress, stress will be build in  host.

Thanks,
Xu

**Comment by xutian** [comment]
@CongLi previous  cfg suppose stress really installed via ks file,  now we use autotest.stress, stress will be build in  host.
And advantage of current cfg is we are not need to update guest cfg if hotplug_memory test rename.
Thanks,
Xu

**Comment by suqinhuang** [comment]
The some confuse with coli, they are totally the same,  just diff cfg file.
seems we have discuss about the issue where to put the cfg before, it's better to make a rule. anyway, it's ok to me.

Thanks
Suqin

**Comment by xutian** [comment]
@suqinhuang  has explain in above post.

**Comment by CongLi** [comment]
1. For "And advantage of current cfg is we are not need to update guest cfg if hotplug_memory test rename.", it's ok for me.
2. I'm confused about  "previous cfg suppose stress really installed via ks file, now we use autotest.stress, stress will be build in host.", previous cfg and current cfg are same.

**Comment by xutian** [comment]
@CongLi let me double check, I my mind,  original cfg use stress installed via ks.

**Comment by xutian** [comment]
thanks, @CongLi and @suqinhuang 's comments. Merged.

**Pull request merged**
