### PR TITLE
blockdev_stream: remove backend limitations on cases

### PR DESCRIPTION
**Pull request by aliang123**
Remove backend limitations on cases, exclude cases that
based on specific backend

Signed-off-by: Aihua Liang <aliang@redhat.com>
id:2097601

### CODE REVIEW

**Comment by aliang123** [comment]
(01/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_stress.q35: STARTED
 (01/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_stress.q35: PASS (505.00 s)
 (02/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_none_existed_overlay.q35: STARTED
 (02/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_none_existed_overlay.q35: PASS (31.25 s)
 (03/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_stop_cont.q35: STARTED
 (03/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_stop_cont.q35: PASS (387.26 s)
 (04/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_subchain.q35: STARTED
 (04/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_subchain.q35: PASS (142.46 s)
 (05/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_cor.q35: STARTED
 (05/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_cor.q35: PASS (100.13 s)
 (06/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_filter_nodename.q35: STARTED
 (06/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_filter_nodename.q35: PASS (64.97 s)
 (07/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream.q35: STARTED
 (07/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream.q35: PASS (101.68 s)
 (08/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_on_error_ignore.q35: STARTED
 (08/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_on_error_ignore.q35: PASS (98.32 s)
 (09/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_cor_base.q35: STARTED
 (09/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_cor_base.q35: PASS (39.74 s)
 (10/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_forbidden_actions.q35: STARTED
 (10/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_forbidden_actions.q35: PASS (47.30 s)
 (11/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_install.q35: STARTED
 (11/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_install.q35: PASS (826.60 s)
 (12/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_reboot.q35: STARTED
 (12/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_reboot.q35: PASS (385.58 s)
 (13/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_powerdown.q35: STARTED
 (13/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_powerdown.q35: PASS (130.54 s)
 (14/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_no_backing.q35: STARTED
 (14/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_no_backing.q35: PASS (29.14 s)
 (15/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: STARTED
 (15/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_speed.q35: PASS (236.95 s)
 (16/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_base_itself.q35: STARTED
 (16/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_base_itself.q35: PASS (90.98 s)
 (17/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_hotunplug.q35: STARTED
 (17/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_hotunplug.q35: PASS (98.82 s)
 (18/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_to_invalid_node.q35: STARTED
 (18/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_to_invalid_node.q35: PASS (47.77 s)
 (19/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_multiple_blocks.q35: STARTED
 (19/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_multiple_blocks.q35: PASS (146.75 s)
 (20/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_on.auto_finalize_on.q35: STARTED
 (20/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_on.auto_finalize_on.q35: PASS (90.31 s)
 (21/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_on.auto_finalize_off.q35: STARTED
 (21/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_on.auto_finalize_off.q35: PASS (89.63 s)
 (22/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_off.auto_finalize_on.q35: STARTED
 (22/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_off.auto_finalize_on.q35: PASS (90.86 s)
 (23/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_off.auto_finalize_off.q35: STARTED
 (23/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_general.auto_dismiss_off.auto_finalize_off.q35: PASS (106.31 s)
 (24/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_no_space.q35: STARTED
 (24/24) Host_RHEL.m9.u1.remote_nfs.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.blockdev_stream_no_space.q35: PASS (32.23 s)

**Comment by aliang123** [comment]
@zhencliu @MiriamDeng  please help to review, thanks.

**Comment by MiriamDeng** [comment]
Will update the result soon.

**Comment by zhencliu** [comment]
LGTM

**Pull request merged**
