### PR TITLE
ping.ext_host: Add compatibility for python3

### PR DESCRIPTION
**Pull request by ybduan**
Add additional explicit decode from bytes to str for python3

ID: 1609656

Signed-off-by: ybduan <yduan@redhat.com>

### CODE REVIEW

**Comment by ybduan** [comment]
python3 ConfigTest.py --testcase=ping.ext_host --guestname=RHEL.8.0 --platform=x86_64 --nicmodel=virtio_net --driveformat=virtio_blk
'19-Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.0.x86_64.io-github-autotest-qemu.ping.ext_host' Finshed 2018-07-27 04:06:09 2018-07-27 04:18:31 PASS 741.796919

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

**Comment by hereischen** [comment]
Please try to fix this kind of issue in one patch as https://github.com/autotest/tp-qemu/pull/1455 did. Thanks.

**Comment by ybduan** [comment]
I met this problem when running syscall filter test loop (only ping.ext_host is included). Thanks! @hereischen

**Pull request merged**
