### PR TITLE
hotplug_memory: Add option test for hotplug cases

### PR DESCRIPTION
**Pull request by huangyum**
Signed-off-by: Yumei Huang <yuhuang@redhat.com>
ID: 1903081

### CODE REVIEW

**Comment by huangyum** [comment]
(1/2) type_specific.io-github-autotest-qemu.hotplug_memory.after.guest_reboot.hotplug.backend_ram.no_policy.two.op_on: PASS (201.70 s)
 (2/2) type_specific.io-github-autotest-qemu.hotplug_memory.after.guest_reboot.hotplug.backend_file.no_policy.two.op_on: PASS (201.49 s)
@yanan-fu Would you pls help review, thanks.

**Comment by yanan-fu** [comment]
@huangyum  So for linux guest, it will cover both hotplug and unplug ? 
Could you explain more why it restrict to `only pluged_memory` for linux guest before ?
I wonder if it is possible to remove `pluged_memory` and use `hotplug` to cover `op_on` and `op_off`  for both linux and window.

**Comment by huangyum** [comment]
@yanan-fu I made the restriction before to to avoid generating too many test cases. I thought running pluged_memory would cover the basic hotplug and unplug scenario, but forgot it only works for linux guest. So add `hotplug` to cover windows guest. I guess it's better to cover both hotplug and unplug scenario, we don't know if and when it can go wrong.

**Comment by yanan-fu** [comment]
> @yanan-fu I made the restriction before to to avoid generating too many test cases. I thought running pluged_memory would cover the basic hotplug and unplug scenario, but forgot it only works for linux guest. So add `hotplug` to cover windows guest. I guess it's better to cover both hotplug and unplug scenario, we don't know if and when it can go wrong.

Ok~   thanks for your explanation.

**Review by yanan-fu — APPROVED** [review]
Acked-by: Yanan Fu <yfu@redhat.com>

**Pull request merged**
