### PR TITLE
fio: Update the version of fio

### PR DESCRIPTION
**Pull request by YongxueHong**
Update the version of fio to the latest one.

ID: 1706741
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by YongxueHong** [comment]
@phou @kimi1978wy  @lijinlijin  pls help review. thanks.

**Comment by YongxueHong** [comment]
@XueqiangWei  @CongLi  pls help review, thanks.

**Comment by CongLi** [comment]
Ack.

**Comment by lijinlijin** [comment]
LGTM
Acked-by: Li Jin lijin@redhat.com

**Comment by YongxueHong** [comment]
@hereischen  help review, thanks

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

**Comment by kimi1978wy** [comment]
Test Passed

Acked-by: Yu Wang <wyu@redhat.com>

**Comment by peixiu** [comment]
Tested 20 times on win2008-r2 guest, all passed.

Acked-by: Peixiu Hou phou@redhat.com

**Comment by CongLi** [comment]
Ack.

**Comment by YongxueHong** [comment]
Thanks all.

**Pull request merged**
