### PR TITLE
add windows support for remote_block_resize

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>
ID: 2125793

### CODE REVIEW

**Comment by XueqiangWei** [comment]
Tested with windows and llinux, all passed.
(1/1) Host_RHEL.m9.u1.ovmf.ceph.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_resize_with_remote_storage.q35: PASS (351.16 s)
(1/1) Host_RHEL.m9.u1.ovmf.ceph.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.x86_64.io-github-autotest-qemu.block_resize_with_remote_storage.q35: PASS (84.91 s)

**Comment by XueqiangWei** [comment]
@zhencliu @hellohellenmao Please help review it. Many thanks.

**Comment by zhencliu** [comment]
LGTM

Also suggest commit header: remote_block_resize: add windows guest support

**Comment by XueqiangWei** [comment]
Updated, thanks Zhenchao.

**Comment by hellohellenmao** [comment]
Tried with raw, qcow2 and luks, all passed.

Ack.

**Pull request merged**
