### PR TITLE
tp-qemu: Add cfg file for a SLOF(ppc only) case to boot with maxmem p…

### PR DESCRIPTION
**Pull request by qunfang**
Add a cfg file for SLOF(ppc only) case to boot vm with maxmem parameter.

ID: 1324358

### CODE REVIEW

**Comment by qunfang** [comment]
02:37:05 INFO | PASS 1-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.ppc64le.io-github-autotest-qemu.slof_with_maxmem.512G

02:38:23 INFO | PASS 2-smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.ppc64le.io-github-autotest-qemu.slof_with_maxmem.1024G

**Comment by MiriamDeng** [comment]
Confiure file looks well.
I tried it on host in my hand but get failure info.I guess,only enough large host can verify the PR.
VMCreateError: VM creation command failed:    "MALLOC_PERTURB_=1  /usr/libexec/qemu-kvm -S  -name 'avocado-vt-vm1'  -sandbox off  -machine pseries  -nodefaults  -vga std  -chardev socket,id=qmp_id_qmpmonitor1,path=/var/tmp/avocado_j57r34/monitor-qmpmonitor1-20160619-095800-wRjFZQFH,server,nowait -mon chardev=qmp_id_qmpmonitor1,mode=control  -chardev socket,id=qmp_id_catch_monitor,path=/var/tmp/avocado_j57r34/monitor-catch_monitor-20160619-095800-wRjFZQFH,server,nowait -mon chardev=qmp_id_catch_monitor,mode=control  -chardev socket,id=serial_id_serial0,path=/var/tmp/avocado_j57r34/serial-serial0-20160619-095800-wRjFZQFH,server,nowait -device spapr-vty,reg=0x30000000,chardev=serial_id_serial0 -device pci-ohci,id=usb1,bus=pci.0,addr=03 -device virtio-scsi-pci,id=virtio_scsi_pci0,bus=pci.0,addr=04,disable-legacy=off,disable-modern=on -drive id=drive_image1,if=none,cache=none,snapshot=off,aio=native,format=qcow2,file=/home/staf-kvm-devel/workspace/usr/share/avocado/data/avocado-vt/images/RHEL-Server-7.3-ppc64le-virtio-scsi.qcow2 -device scsi-hd,id=image1,drive=drive_image1 -device virtio-net-pci,mac=9a:47:48:49:4a:4b,id=iddHjlLH,vectors=4,netdev=id6v2IFX,bus=pci.0,addr=05,disable-legacy=off,disable-modern=on  -netdev tap,id=id6v2IFX,vhost=on,vhostfd=20,fd=19 -m 4096,slots=4,maxmem=1024G  -smp 8,maxcpus=8,cores=4,threads=1,sockets=2 -device usb-tablet,id=usb-tablet1,bus=usb1.0,port=1  -vnc :1  -rtc base=utc,clock=host  -boot order=cdn,once=c,menu=off,strict=off -enable-kvm"    (status: 1,    output: 'qemu-kvm: Failed to allocate KVM HPT of order 33 (try smaller maxmem?): Cannot allocate memory')

**Comment by suqinhuang** [comment]
Hi @qunfang 
could you share the cmd, is the cmd correct? 
I find there is slots requirement.
,slots=4,maxmem=512G

and I think the login_timeout is a little short as the mem is large

**Comment by qunfang** [comment]
@suqinhuang
CML:
  /usr/libexec/qemu-kvm \
    -S  \
    -name 'avocado-vt-vm1'  \
    -sandbox off  \
    -machine pseries  \
    -nodefaults  \
    -vga std  \
    -chardev socket,id=qmp_id_qmpmonitor1,path=/var/tmp/avocado__HLuRM/monitor-qmpmonitor1-20160712-042401-dbHKbgfx,server,nowait \
    -mon chardev=qmp_id_qmpmonitor1,mode=control  \
    -chardev socket,id=qmp_id_catch_monitor,path=/var/tmp/avocado__HLuRM/monitor-catch_monitor-20160712-042401-dbHKbgfx,server,nowait \
    -mon chardev=qmp_id_catch_monitor,mode=control  \
    -chardev socket,id=serial_id_serial0,path=/var/tmp/avocado__HLuRM/serial-serial0-20160712-042401-dbHKbgfx,server,nowait \
    -device spapr-vty,reg=0x30000000,chardev=serial_id_serial0 \
    -device pci-ohci,id=usb1,bus=pci.0,addr=03 \
    -device virtio-scsi-pci,id=virtio_scsi_pci0,bus=pci.0,addr=04,disable-legacy=off,disable-modern=on \
    -drive id=drive_image1,if=none,snapshot=off,aio=native,cache=none,format=qcow2,file=/root/test_home/qzhang/staf-kvm-devel/workspace/usr/share/avocado/data/avocado-vt/images/RHEL-Server-7.3-ppc64le-virtio-scsi.qcow2 \
    -device scsi-hd,id=image1,drive=drive_image1 \
    -device virtio-net-pci,mac=9a:f8:f9:fa:fb:fc,id=idMInveF,vectors=4,netdev=idVXP4Dt,bus=pci.0,addr=05,disable-legacy=off,disable-modern=on  \
    -netdev tap,id=idVXP4Dt,vhost=on,vhostfd=18,fd=17 \
    -m 131072,slots=4,maxmem=512G  \
    -smp 16,maxcpus=16,cores=8,threads=1,sockets=2 \
    -device usb-tablet,id=usb-tablet1,bus=usb1.0,port=1  \
    -vnc :0  \
    -rtc base=utc,clock=host  \
    -boot order=cdn,once=c,menu=off,strict=off \
    -enable-kvm

And for the login_timeout, i think it should be okay, guest image boots up very quick on power host, and I re-test many times, no timeout issue.

**Comment by CongLi** [comment]
Agree with @suqinhuang , login_timeout is short for big machine,
it's better to set a bigger value.

Others are good to me.

**Comment by qunfang** [comment]
@CongLi Thanks for suggestion, already updated. Could you please give a double confirmation?

**Comment by CongLi** [comment]
Ack.

**Comment by CongLi** [comment]
Thanks @qunfang , merged.

**Pull request merged**
