### PR TITLE
qemu.tests.pktgen: fix syntax issue

### PR DESCRIPTION
**Pull request by xutian**
Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
ID:  1128026

**Comment by xutian** [comment]
@pezhang  can you help review this PR, thanks Xu

**Comment by CongSmile** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by pezhang** [comment]
@xutian 
Acked-by: Pei Zhang pezhang@redhat.com

smp_4.4096m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.pktgen.guest_guest: PASS
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
JOB HTML   : /root/avocado/job-results/job-2016-05-04T17.33-4f3c473/html/results.html
TIME       : 230.28 s

**Comment by xutian** [comment]
merged, thanks @CongSmile and @pezhang

**Pull request merged**
