### PR TITLE
migrate:Delete the check of ksmtuned for migration scenarios

### PR DESCRIPTION
**Pull request by yanglei-rh**
After confirm with developer,ksmtuned package not a strong dependency for migration scenarios, so delete the check of ksmtuned for migration scenarios.

ID:2134053
Signed-off-by: Lei Yang <leiayang@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
Actually, this patch revert 2 commits:  4e2baed1e7890d3ad15244bec268d295fef3b74b and fc36f999622123afee38f8176715a08f9e847e98.  I prefer use git revert to show the history more clearly.

**Comment by zhenyzha** [comment]
@yanglei-rh And since the current version has been around for a while, could you post the test results after removal? 
Maybe we can look into the bug if the result is too long.
Test results with and without the ksmtuned package in the environment.

**Comment by yanglei-rh** [comment]
> Actually, this patch revert 2 commits: [4e2baed](https://github.com/autotest/tp-qemu/commit/4e2baed1e7890d3ad15244bec268d295fef3b74b) and [fc36f99](https://github.com/autotest/tp-qemu/commit/fc36f999622123afee38f8176715a08f9e847e98). I prefer use git revert to show the history more clearly.

Done

**Comment by yanan-fu** [comment]
Could you provide the test results with and without `ksmtuned`, thanks!

**Comment by PaulYuuu** [comment]
Just so confusing why ksmtuned will be introduced in the past.

But the patch LGTM.

**Comment by yanglei-rh** [comment]
Without ksmtuned test pass:
 (01/12) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.migrate.with_file_transfer.tcp.q35: PASS (139.35 s)
 (02/12) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.migrate.with_file_transfer.unix.q35: PASS (139.52 s)
 (03/12) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.migrate.with_file_transfer.exec.gzip_exec.q35: PASS (148.48 s)
 (04/12) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.migrate.with_file_transfer.mig_cancel.q35: PASS (107.25 s)
 (05/12) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.migrate.between_vhost_novhost.tcp.q35: PASS (146.69 s)
 (06/12) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.migrate.between_vhost_novhost.unix.q35: PASS (148.75 s)
 (07/12) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.migrate.between_vhost_novhost.exec.gzip_exec.q35: PASS (144.20 s)
 (08/12) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.migrate.between_vhost_novhost.mig_cancel.q35: PASS (106.54 s)
 (09/12) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.migrate.with_netperf.tcp.q35: PASS (1203.86 s)
 (10/12) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.migrate.with_netperf.unix.q35: PASS (1193.62 s)
 (11/12) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.migrate.with_netperf.exec.gzip_exec.q35: PASS (1202.94 s)
 (12/12) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.migrate.with_netperf.mig_cancel.q35: PASS (1171.12 s)

**Comment by yanglei-rh** [comment]
> Could you provide the test results with and without `ksmtuned`, thanks!

Done

**Comment by yanan-fu** [comment]
> Just so confusing why ksmtuned will be introduced in the past.
> 

Me too!   Go through the whole auto related code, i did not find any other place to enable the checking of ksmtuned except the one in the case cfg that be introduced with issue 2101703.

IMO, logically, issue 2101703 is impossible but it do happen then, but can not be reproduced now.

cc @YongxueHong for more opinion in case anything be missed, thanks!

> But the patch LGTM.

**Comment by zhenyzha** [comment]
> ksmtuned

Strange indeed, but I think I need to borrow a host to reproduce the original problem. 
Update later.

**Comment by YongxueHong** [comment]
Hi @leexiaohui32 
Would you like to help review it, thanks in advance.

**Comment by zhenyzha** [comment]
Sorry I didn't find the original reason either, but the patch LGTM.

```
 (61/67) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.migrate.between_vhost_novhost.unix.arm64-pci: STARTED
 (61/67) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.migrate.between_vhost_novhost.unix.arm64-pci: PASS (102.05 s)
 (62/67) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.migrate.between_vhost_novhost.exec.gzip_exec.arm64-pci: STARTED
 (62/67) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.migrate.between_vhost_novhost.exec.gzip_exec.arm64-pci: PASS (102.78 s)
 (63/67) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.migrate.between_vhost_novhost.mig_cancel.arm64-pci: STARTED
 (63/67) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.migrate.between_vhost_novhost.mig_cancel.arm64-pci: PASS (65.16 s)
 (64/67) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.migrate.with_netperf.tcp.arm64-pci: STARTED
 (64/67) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.migrate.with_netperf.tcp.arm64-pci: PASS (1146.13 s)
 (65/67) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.migrate.with_netperf.unix.arm64-pci: STARTED
 (65/67) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.migrate.with_netperf.unix.arm64-pci: PASS (1156.86 s)
 (66/67) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.migrate.with_netperf.exec.gzip_exec.arm64-pci: STARTED
 (66/67) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.migrate.with_netperf.exec.gzip_exec.arm64-pci: PASS (1157.88 s)
 (67/67) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.migrate.with_netperf.mig_cancel.arm64-pci: STARTED
 (67/67) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.migrate.with_netperf.mig_cancel.arm64-pci: PASS (1120.58 s)
```

**Comment by leexiaohui32** [comment]
LGTM

**Comment by yanglei-rh** [comment]
Hello @yanan-fu Please help me review it again, thanks  a lot.

**Review by PaulYuuu — APPROVED** [review]

**Review by yanan-fu — APPROVED** [review]

**Pull request merged**
