### PR TITLE
Chardev: fix UnicodeDecodeError issue

### PR DESCRIPTION
**Pull request by nanliu-r**
ID: 2212249

Add one parameter to avoid irrelevant messages.

### CODE REVIEW

**Comment by nanliu-r** [comment]
Test pass: 
 (1/1) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.chardev_pci_serial_login.q35: PASS (411.21 s)

@yanan-fu Please help to review this patch, thanks.

**Review by yanan-fu — APPROVED** [review]
Ack

**Comment by yanan-fu** [comment]
@nanliu-r   IMO, it is not suitable to use `x86` as the prefix for the commit title,   could you please update it ? Thanks!

**Comment by nanliu-r** [comment]
> @nanliu-r IMO, it is not suitable to use `x86` as the prefix for the commit title, could you please update it ? Thanks!

@yanan-fu Thanks and updated.

**Review by yanan-fu — APPROVED** [review]

**Pull request merged**
