### PR TITLE
virtio_fs_hotplug.py: keep the "session" variable up to date

### PR DESCRIPTION
**Pull request by nickzhq**
virtio_fs_hotplug.py: keep the "session" variable up to date

ID: 2074459

Signed-off-by: Houqi (Nick) Zuo hzuo@redhat.com

### CODE REVIEW

**Comment by nickzhq** [comment]
@xiagao @zhencliu  Please take a look, thanks!

**Comment by zhencliu** [comment]
hi @nickzhq , suggest to update your commit header to:
virtio_fs_hotplug: keep the "session" variable up to date

**Comment by zhencliu** [comment]
add @YongxueHong

**Comment by zhencliu** [comment]
LGTM

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by xiagao** [comment]
(1/2) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: STARTED
 (1/2) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (1691.67 s)
 (2/2) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.virtio_fs_hotplug.plug.one_fs_source.q35: STARTED
 (2/2) Host_RHEL.m9.u1.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.virtio_fs_hotplug.plug.one_fs_source.q35: PASS (512.88 s)
LGTM

**Pull request merged**
