### PR TITLE
block_vhost_vdpa_test:add new case

### PR DESCRIPTION
**Pull request by qingwangrh**
1. Add discard option test
2. Add cache option test

ID:1745,1746

### CODE REVIEW

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=block_vhost_vdpa_test.with_cache,block_vhost_vdpa_test.with_discard --guestname=RHEL.9.4.0 --firmware=default_bios --clone=no
 (1/3) repeat1.Host_RHEL.m8.u10.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.system_reset_during_boot.q35: STARTED
 (1/3) repeat1.Host_RHEL.m8.u10.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.system_reset_during_boot.q35: PASS (503.00 s)
 (2/3) repeat2.Host_RHEL.m8.u10.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.system_reset_during_boot.q35: STARTED
 (2/3) repeat2.Host_RHEL.m8.u10.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.system_reset_during_boot.q35: PASS (790.13 s)
 (3/3) repeat3.Host_RHEL.m8.u10.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.system_reset_during_boot.q35: STARTED
 (3/3) repeat3.Host_RHEL.m8.u10.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.system_reset_during_boot.q35: PASS (570.80 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by qingwangrh** [comment]
@XueqiangWei @zhenyzha @menli820 @peixiu Please help to review,thanks.

**Comment by zhenyzha** [comment]
Currently, this case is only x86_64 i386, so multiarch platforms are not affected.

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Review by zhenyzha — APPROVED** [review]

**Comment by menli820** [comment]
LGTM

 (1/3) Host_RHEL.m9.u4.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_discard.q35: STARTED
 (1/3) Host_RHEL.m9.u4.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_discard.q35: PASS (135.80 s)
 (2/3) Host_RHEL.m9.u4.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_cache.with_direct_on.q35: STARTED
 (2/3) Host_RHEL.m9.u4.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_cache.with_direct_on.q35: PASS (162.22 s)
 (3/3) Host_RHEL.m9.u4.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_cache.with_direct_off.q35: STARTED
 (3/3) Host_RHEL.m9.u4.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win11.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_cache.with_direct_off.q35: PASS (17.63 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2023-12-15T14.39-85d1e8a/results.html
JOB TIME   : 318.26 s

**Review by menli820 — APPROVED** [review]

**Comment by peixiu** [comment]
python ConfigTest.py --testcase=block_vhost_vdpa_test.with_cache,block_vhost_vdpa_test.with_discard --guestname=Win2019 --firmware=default_bios --clone=yes

 (1/4) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: STARTED
 (1/4) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (1105.57 s)
 (2/4) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_discard.q35: STARTED
 (2/4) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_discard.q35: PASS (286.85 s)
 (3/4) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_cache.with_direct_on.q35: STARTED
 (3/4) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_cache.with_direct_on.q35: PASS (185.71 s)
 (4/4) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_cache.with_direct_off.q35: STARTED
 (4/4) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_cache.with_direct_off.q35: PASS (10.47 s)

**Review by peixiu — APPROVED** [review]
LGTM and thanks~

**Comment by XueqiangWei** [comment]
Tested with ovmf and seabios, all passed.

 (1/6) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-
github-autotest-qemu.block_vhost_vdpa_test.with_discard.q35: STARTED
 (1/6) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-
github-autotest-qemu.block_vhost_vdpa_test.with_discard.q35: PASS (38.97 s)
 (2/6) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-
github-autotest-qemu.block_vhost_vdpa_test.with_cache.with_direct_on.q35: STARTED
 (2/6) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-
github-autotest-qemu.block_vhost_vdpa_test.with_cache.with_direct_on.q35: PASS (42
.50 s)
 (3/6) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-
github-autotest-qemu.block_vhost_vdpa_test.with_cache.with_direct_off.q35: STARTED
 (3/6) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-
github-autotest-qemu.block_vhost_vdpa_test.with_cache.with_direct_off.q35: PASS (1
0.39 s)
 (4/6) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_discard.q35: STARTED
 (4/6) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_discard.q35: PASS (56.42 s)
 (5/6) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_cache.with_direct_on.q35: STARTED
 (5/6) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_cache.with_direct_on.q35: PASS (58.78 s)
 (6/6) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_cache.with_direct_off.q35: STARTED
 (6/6) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.block_vhost_vdpa_test.with_cache.with_direct_off.q35: PASS (15.94 s)

**Comment by XueqiangWei** [comment]
@qingwangrh Suggest to add the new tests to docstring. Thanks.

**Comment by qingwangrh** [comment]
> @qingwangrh Suggest to add the new tests to docstring. Thanks.

done,thanks

**Review by XueqiangWei — APPROVED** [review]

**Pull request merged**
