### PR TITLE
qemu.tests.pci_hotplug: Add default value of "wait_secs_for_hook_up".

### PR DESCRIPTION
**Pull request by CongLi**
Signed-off-by: Cong Li coli@redhat.com

id: 1231126

### CODE REVIEW

**Comment by CongLi** [comment]
@suqinhuang 

Could you help review this one?

Thanks.

**Comment by suqinhuang** [comment]
LGTM

**Comment by XueqiangWei** [comment]
LGTM,
Acked-by Xueqiang Wei <xuwei@redhat.com>

**Comment by CongLi** [comment]
Thanks @suqinhuang @XueqiangWei

**Pull request merged**
