### PR TITLE
qemu_guest_agent: Delete virtio_blk test for check_hotplug_frozen

### PR DESCRIPTION
**Pull request by ngu-niny**
Delete virtio_blk test for check_hotplug_frozen on ppc64le.

ID: 2023230
Signed-off-by: Nini Gu <ngu@redhat.com>

### CODE REVIEW

**Comment by BohdanMar** [comment]
After applying this patch -  loop run without virtio_blk testcase:

(1/1) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.6.0.ppc64le.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_hotplug_frozen: CANCEL: Test cancelled due to --dry-run (0.00 s)

Acked-by: Bogdan Marcynkov bmarcynk@redhat.com

**Comment by ngu-niny** [comment]
@PaulYuuu Yihuang, could you help to review the patch? Thank you.

**Comment by PaulYuuu** [comment]
@ngu-niny I think should explain the reason in the commit.

**Comment by ngu-niny** [comment]
@PaulYuuu Updated. Thanks.

**Pull request merged**
