### PR TITLE
tp-qemu: add cpuid dump files for rhel6.5.0, delete stdout and stderr files

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>

### CODE REVIEW

**Comment by XueqiangWei** [comment]
ID: 1214547

**Comment by suqinhuang** [comment]
Acked-by: Suqin Huang

**Comment by CongSmile** [comment]
Hi xuwei,

I'm a little confused that why only add rhel.6.5 cfg ?
How about others? e.g. rhel.6.6

Could you help confirm it?

Thanks.

**Comment by XueqiangWei** [comment]
Hi CongSmile,

added rhel.6.5 cfg was based on bug 1214547
others, e.g. rhel.6.6 also need to add. Will add later.

**Comment by XueqiangWei** [comment]
LGTM,
Acked by Xueqiang Wei <xuwei@redhat.com>

**Comment by suqinhuang** [comment]
rhel6.5.0 dump file is added, because of -M rhel6.5.0 machine type is added but no related dump file, which will fail the test.

**Comment by CongSmile** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by ypu** [comment]
Hi @XueqiangWei can you help to check if https://github.com/autotest/tp-qemu/pull/398 can fix this problem? Seems there is something duplicate with that pullreqs. 

If so please close this one directly. Thanks a lot.

**Comment by XueqiangWei** [comment]
Hi @ypu  has checked #398, it can fix this problem, close this one.

**Pull request closed without merging**
