### PR TITLE
Based on test case design, ignore ruff policy

### PR DESCRIPTION
**Pull request by fbq815**
CPU: ignore ruff policy for the funtiona of sub_migrate
 
ID: 3002

Signed-off-by: Boqiao Fu <bfu@redhat.com>

### CODE REVIEW

**Comment by fbq815** [comment]
Test result:
cpu_device_hotpluggable.hotplug.single_vcpu.with_migrate.s390-virtio: PASS

@nanliu-r @maxujun @zhenyzha please help me check if this works on your platform as well

@PaulYuuu please help me review this patch

**Review by PaulYuuu — APPROVED** [review]

**Comment by zhenyzha** [comment]
this's cases no aarch64, please ignore me

**Review by nanliu-r — APPROVED** [review]

**Comment by maxujun** [comment]
(1/1) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.cpu_device_hotpluggable.hotplug.single_vcpu.with_migrate: STARTED
 (1/1) Host_RHEL.m8.u10.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.10.0.ppc64le.io-github-autotest-qemu.cpu_device_hotpluggable.hotplug.single_vcpu.with_migrate: PASS (322.87 s)

LGTM.

**Comment by fbq815** [comment]
@PaulYuuu seems this is ready to be merged

**Pull request merged**
