### PR TITLE
generic.test: fix python3 compatibility issue for ioquit

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>
ID: 1643339

### CODE REVIEW

**Comment by XueqiangWei** [comment]
(1/1) repeat1.Host_RHEL.m7.u6.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.io-github-autotest-qemu.ioquit: PASS (174.75 s)

Tested with python3, also passed

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

**Comment by luckyh** [comment]
see also https://github.com/autotest/tp-qemu/pull/1582

**Comment by CongLi** [comment]
Ack.

**Comment by XueqiangWei** [comment]
track by #1582

**Pull request closed without merging**
