### PR TITLE
    netperf_stress: update netperf.exe

### PR DESCRIPTION
**Pull request by kimi1978wy**
this netperf.exe can run on win2008-32/64 guests successfully.
6517c4c8b120f51df4e05e5a424cd  netperf.exe

id: 1471653

Signed-off-by: Yu Wang <wyu@redhat.com>

### CODE REVIEW

**Comment by kimi1978wy** [comment]
ran on win2008-32/64 and win8.1-32, can pass this test 
cmd: 
python ConfigTest.py --testcase=netperf_stress_test.TCP_STREAM.guest2guest --guestname=Win2008 --platform=i386 --driveformat=virtio_scsi --clone=no

smp_4.2048m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Win2008.i386.sp2.io-github-autotest-qemu.netperf_stress_test.TCP_STREAM.guest2guest: PASS (901.99 s)
smp_4.2048m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Win2008.i386.sp2.io-github-autotest-qemu.netperf_stress_test.TCP_STREAM.guest2guest: PASS (931.44 s)
 smp_4.2048m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_scsi.up.virtio_net.Win8.i386.1.io-github-autotest-qemu.netperf_stress_test.TCP_STREAM.guest2guest: PASS (1009.48 s)

**Comment by luckyh** [comment]
@kimi1978wy hi, can you please explain what is the issue you met? And, does the new binary fit all windows platforms?

**Comment by kimi1978wy** [comment]
@luckyh former netperf.exe cannot run on windows2008-32/64, it has compatibility problem, it occurred error "c:\netperf.exe is not a valid win32 application" in guests. 
The new netperf.exe can run on all platforms, it used for our manual netperf test on different windows platforms before.

**Comment by kimi1978wy** [comment]
@luckyh their version are the same, 2.6.0-r594

**Pull request merged**
