### PR TITLE
Update fio package for  non x86 platform

### PR DESCRIPTION
**Pull request by zixi-chen**
Signed-off-by: Zixi Chen <zixchen@redhat.com>
ID: 1940737

### CODE REVIEW

**Comment by zixi-chen** [comment]
x86_64: 
(1/2) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.fio_linux.aio_native: PASS (611.54 s)
 (2/2) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.fio_linux.aio_threads: PASS (602.96 s)

aarch64:
 (1/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.fio_linux.aio_native.arm64-pci: PASS (298.34 s)
 (2/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.fio_linux.aio_threads.arm64-pci: PASS (278.81 s)

@YongxueHong @PaulYuuu Could you please review this patch?

**Comment by YongxueHong** [comment]
@zixi-chen  if the another `fio-3.13-48-ga819.tar.bz2` works for aarch64, you just specify it with  for x86 in cfg:
```
x86_86:
    fio_pkg = fio-3.25.tar.bz2
```
or you could download one version which could work all architecture from source @PaulYuuu mentions https://github.com/autotest/tp-qemu/pull/2642#issuecomment-802522522

**Comment by PaulYuuu** [comment]
@zixi-chen 
1. Please do not disclose unreleased versions in github.
2. Correct the title, this is not only for aarch64, the last source archive cannot be compiled at non-x86 platforms, it contains some files that have been compiled by you, that's why we need to replace it.

**Comment by zixi-chen** [comment]
@YongxueHong 
Sorry I didn't really catch up with your comment, is the cfg in the fio package? I didn't change cfg files.
As fio-3.13-48-ga819.tar.bz2 is not upload by me. Could you kindly point out which file do you find config below? Thanks.
x86_86:
    fio_pkg = fio-3.25.tar.bz2


@PaulYuuu 
Update comments, will update commit info.

**Comment by YongxueHong** [comment]
> @YongxueHong
> Sorry I didn't really catch up with your comment, is the cfg in the fio package? I didn't change cfg files.
> As fio-3.13-48-ga819.tar.bz2 is not upload by me. Could you kindly point out which file do you find config below? Thanks.
> x86_86:
> fio_pkg = fio-3.25.tar.bz2
> 

@zixi-chen 
Please update it according to @PaulYuuu 's comments.
Thanks

> @PaulYuuu
> Update comments, will update commit info.

**Comment by zixi-chen** [comment]
> > @YongxueHong
> > Sorry I didn't really catch up with your comment, is the cfg in the fio package? I didn't change cfg files.
> > As fio-3.13-48-ga819.tar.bz2 is not upload by me. Could you kindly point out which file do you find config below? Thanks.
> > x86_86:
> > fio_pkg = fio-3.25.tar.bz2
> 
> @zixi-chen
> Please update it according to @PaulYuuu 's comments.
> Thanks
> 
@YongxueHong update commit info to non x86 platform
The package I updated is download by the link https://github.com/axboe/fio/releases @PaulYuuu given.

**Comment by zixi-chen** [comment]
Based on the config file, this fio package support a few platforms. I may also need to check i386 and s390 at least, what do you think @PaulYuuu 

if test ! -z "$cpu" ; then
  # command line argument
  :
elif check_define __i386__ ; then
  cpu="i386"
elif check_define __x86_64__ ; then
  cpu="x86_64"
elif check_define __sparc__ ; then
  if check_define __arch64__ ; then
    cpu="sparc64"
  else
    cpu="sparc"
  fi
elif check_define _ARCH_PPC ; then
  if check_define _ARCH_PPC64 ; then
    cpu="ppc64"
  else
    cpu="ppc"
  fi
elif check_define __mips__ ; then
  cpu="mips"
elif check_define __ia64__ ; then
  cpu="ia64"
elif check_define __s390__ ; then
  if check_define __s390x__ ; then
    cpu="s390x"
  else
    cpu="s390"
  fi
elif check_define __arm__ ; then
  cpu="arm"
elif check_define __aarch64__ ; then
  cpu="aarch64"
elif check_define __hppa__ ; then
  cpu="hppa"
else
  cpu=`uname -m`
fi

**Comment by PaulYuuu** [comment]
> Based on the config file, this fio package support a few platforms. I may also need to check i386 and s390 at least, what do you think @PaulYuuu
> 
> if test ! -z "$cpu" ; then
> 
> # command line argument
> :
> elif check_define **i386** ; then
> cpu="i386"
> elif check_define **x86_64** ; then
> cpu="x86_64"
> elif check_define **sparc** ; then
> if check_define **arch64** ; then
> cpu="sparc64"
> else
> cpu="sparc"
> fi
> elif check_define _ARCH_PPC ; then
> if check_define _ARCH_PPC64 ; then
> cpu="ppc64"
> else
> cpu="ppc"
> fi
> elif check_define **mips** ; then
> cpu="mips"
> elif check_define **ia64** ; then
> cpu="ia64"
> elif check_define **s390** ; then
> if check_define **s390x** ; then
> cpu="s390x"
> else
> cpu="s390"
> fi
> elif check_define **arm** ; then
> cpu="arm"
> elif check_define **aarch64** ; then
> cpu="aarch64"
> elif check_define **hppa** ; then
> cpu="hppa"
> else
> cpu=`uname -m`
> fi

For `i386`, basically many operating systems have abandoned it, so I think we can ignore it.
For `s390x`(not `s390`), @fbq815 could you try to compile fio-3.25 on s390x? Thanks in advance.

**Comment by PaulYuuu** [comment]
Seems there is no reply, I think we can merge this one accordingly.
What do you think? @zixi-chen @YongxueHong

**Comment by YongxueHong** [comment]
> Seems there is no reply, I think we can merge this one accordingly.
> What do you think? @zixi-chen @YongxueHong

Hi @PaulYuuu 
Looks good for me.
Thanks.

**Review by YongxueHong — APPROVED** [review]

**Comment by PaulYuuu** [comment]
Okay, thanks all.

**Pull request merged**
