### PR TITLE
stress_boot: Fixed the issue of unequal number of vCPUs when booting vm

### PR DESCRIPTION
**Pull request by yiqianwei**
ID: 2602

### CODE REVIEW

**Comment by yiqianwei** [comment]
Test results: 
 (1/1) Host_RHEL.m10.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.stress_boot.q35: PASS (380.55 s)

**Comment by yiqianwei** [comment]
@yanan-fu  and @jingzhao84 , Could you help to review this patch? thanks

**Comment by yanan-fu** [comment]
There are not only 1 problems about the cpu topology in this case:
1. Suggest align the vm cpu number to 2:
`vcpu_maxcpus = int(math.floor(float(vm_cpu_num) / 2) * 2)`
2. Do not set `smp`,  set the `vcpu_maxcpus` only,   avocado-vt will adjust the topology automatically
3. If the `vcpu_maxcpus=1`,  launch vm will failed as the default `vcpu_sockets` is `2`, To resolve this issue, you can refer:
```
vcpu_sockets = 1
vcpu_cores = 1
vcpu_threads = 1
```

**Comment by yiqianwei** [comment]
Test results:
 (1/1) Host_RHEL.m10.u0.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.10.0.x86_64.io-github-autotest-qemu.stress_boot.q35: PASS (837.65 s)

**Comment by yiqianwei** [comment]
@yanan-fu , I have updated this patch, please check it again,thanks

**Comment by yanan-fu** [comment]
Suggest add one more checking:
```
if host_cpu_num <= max_vms:
    test.cancel("No enough physical cpus to pin all guests")
```

**Comment by yiqianwei** [comment]
> test.cancel("No enough physical cpus to pin all guests")

Hi @yanan-fu , Could I modify the code as follows? thanks

    if host_cpu_num <= int(params.get("max_vms")):
        test.cancel("No enough physical cpus to pin all guests")
    elif vm_cpu_num == 1:
        params["vcpu_sockets"] = 1
        params["vcpu_threads"] = 1
        params["vcpu_cores"] = 1
    else:
        vm_cpu_num = int(math.floor(float(vm_cpu_num) / 2) * 2)

**Review by yanan-fu — APPROVED** [review]

**Pull request merged**
