### PR TITLE
seabios_basic: optimize testing procedure

### PR DESCRIPTION
**Pull request by ybduan**
Until catching the second boot menu hint displaying after rebooting,
then send the boot menu key.

ID: 1802150

Signed-off-by: ybduan <yduan@redhat.com>

### CODE REVIEW

**Comment by XueqiangWei** [comment]
All checks have failed, please update it.

**Comment by ybduan** [comment]
Please help review this PR, thanks! @XueqiangWei

**Comment by XueqiangWei** [comment]
Tested with virtio-scsi/virtio-blk+q35/i440fx, all work well.

(1/8) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.seabios.basic: PASS (96.01 s)
 (2/8) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.seabios.basic.q35: PASS (99.00 s)
 (3/8) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.seabios.basic: PASS (185.62 s)
 (4/8) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.seabios.basic.q35: PASS (193.45 s)
 (5/8) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.seabios.basic: PASS (102.96 s)
 (6/8) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.seabios.basic.q35: PASS (98.25 s)
 (7/8) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.seabios.basic: PASS (188.96 s)
 (8/8) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.seabios.basic.q35: PASS (211.38 s)

LGTM,
Acked-by xuwei@redhat.com

**Comment by ybduan** [comment]
Please help review this PR, thanks! @luckyh

**Comment by luckyh** [comment]
@ybduan would you please elaborate what the issue is and how it happens?

**Comment by ybduan** [comment]
This case will send the "boot_menu_key" after guest rebooting and then display the boot menu.
The original code sends the "boot_menu_key" when catches the boot menu hint after rebooting.
```Python
        if not (boot_menu_hint and utils_misc.wait_for(boot_menu, timeout, 1)):
            test.fail("Could not get boot menu message after rebooting")
        # Send boot menu key in monitor.
        vm.send_key(boot_menu_key)
```
But, in fact, there are two problems.
1. There will be two boot menu hints in seabios log. One arises when booting the guest, and the other arises after rebooting.
Above codes will send the boot menu key when catching the first boot menu hint, but not the second one which occurs after rebooting.
This may lead to sending the boot menu key at wrong time, and we may not get the boot menu.
So I change the code to send the boot menu key until catching the second boot menu hint.
```Python
        if not (boot_menu_hint and utils_misc.wait_for(boot_menu_check, timeout, 1)):
```
2. The original codes put "vm.send_key(boot_menu_key)" in restarting guest logic. But if there is no restarting guest logic, we will not send the boot menu key and then cannot get the boot menu list in the following codes.
So I put "vm.send_key(boot_menu_key)" outside restarting guest logic at line 85.

**Comment by luckyh** [comment]
Thanks all.

**Pull request merged**
