### PR TITLE
unplug_block_during_io_reboot: New case to test unplug block during io

### PR DESCRIPTION
**Pull request by YongxueHong**
New a case that reboot after hot unplug a disk with IO stress test
running on it.

ID: 1703632
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by YongxueHong** [comment]
Depends on #1735

**Comment by YongxueHong** [comment]
@lolyu  @XueqiangWei @peixiu @kimi1978wy @qingwangrh pls help me to review, thanks.

**Comment by YongxueHong** [comment]
@XueqiangWei  @peixiu  @kimi1978wy  @zhenyzha @lolyu  help to review, thanks.

**Comment by peixiu** [comment]
Tested on win2008-r2 and win2016 guest, all passed.
 (1/1) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.unplug_block_during_io_reboot: PASS (253.73 s)
 (1/1) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2008.x86_64.r2.io-github-autotest-qemu.unplug_block_during_io_reboot: PASS (174.57 s)

LGTM~
Acked-by: Peixiu Hou phou@redhat.com

**Comment by kimi1978wy** [comment]
Test with virtio-scsi on windows guest, all passed:
 (4/6) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win7.x86_64.sp1.io-github-autotest-qemu.unplug_block_during_io_reboot: PASS (137.80 s)
 (5/6) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.x86_64.io-github-autotest-qemu.unplug_block_during_io_reboot: PASS (170.87 s)
 (6/6) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.x86_64.1.io-github-autotest-qemu.unplug_block_during_io_reboot: PASS (154.33 s)
 (5/8) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.unplug_block_during_io_reboot: PASS (271.48 s)
 (6/8) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win7.i386.sp1.io-github-autotest-qemu.unplug_block_during_io_reboot: PASS (154.87 s)
 (7/8) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.i386.io-github-autotest-qemu.unplug_block_during_io_reboot: PASS (159.86 s)
 (8/8) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win8.i386.1.io-github-autotest-qemu.unplug_block_during_io_reboot: PASS (130.74 s)

LGTM
Acked by: Yu Wang wyu@redhat.com

**Comment by XueqiangWei** [comment]
(1/1) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.8.x86_64.io-github-autotest-qemu.unplug_block_during_io_reboot.q35: PASS (140.92 s)
 (1/1) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.unplug_block_during_io_reboot.q35: PASS (135.83 s)

LGTM,
Acked-by xuwei@redhat.com

**Comment by zhenyzha** [comment]
(1/1) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.unplug_block_during_io_reboot: PASS (225.14 s)
 (1/1) Host_RHEL.m7.u7.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.ppc64le.io-github-autotest-qemu.unplug_block_during_io_reboot: PASS (180.79 s)

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Comment by YongxueHong** [comment]
Thanks all, let's merge it.

**Pull request merged**
