### PR TITLE
iommu: Add device intel-iommu before all virtio devices

### PR DESCRIPTION
**Pull request by vivianQizhu**
Depends on https://github.com/avocado-framework/avocado-vt/pull/2726

id: 1866233
Signed-off-by: Qianqian Zhu <qizhu@redhat.com>

### CODE REVIEW

**Comment by vivianQizhu** [comment]
@CongLi @huangyum @zhenyzha @lijinlijin Please help call feature owners check those features that been influenced: iommu, balloon, vioinput, chardev/virtio serial, cpu, network/dpdk, virtio rng. Thanks.

What this patch updates: move `-device intel-iommu` from the end of qemu command line up to the position before any virtio devices.

Background: https://bugzilla.redhat.com/show_bug.cgi?id=1786404#c25
Per this qemu developer's comment, the device intel-iommu should be added before any virtio devices, so previously we test these cases in wrong way (to add extra params thus intel-iommu will be added into the end of qemu command line).

**Comment by lijinlijin** [comment]
@xiagao @menli820 @6-dehan
Could you check your features' part?

**Comment by CongLi** [comment]
@qingwangrh @yduan @qcheng-redhat please review this patch.

**Comment by zhenyzha** [comment]
@PaulYuuu @MiriamDeng please review this patch, thanks.

**Comment by xiagao** [comment]
Acked-by: Xiaoling Gao<xiagao@redhat.com>
Test pass for balloon and netkvm,below is the result.
(1/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.boot_nic_with_intel_iommu.q35: PASS (122.76 s)
 (2/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.balloon_check.balloon_evict_and_enlarge.iommu_enabled.q35: PASS (439.60 s)

**Comment by 6-dehan** [comment]
Acked-by: Dehan Meng demeng@redhat.com
Test pass for serial ,below is the result.
(2/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_serial_file_transfer.unix_socket.iommu_enabled.q35: PASS (185.80 s)

**Comment by MiriamDeng** [comment]
LGTM, since it is not really supported on ppc ,just run existed balloon test cases for regression test, and all passed without any negative effect.
 (01/12) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (1529.18 s)
 (02/12) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.rh_kernel_update: PASS (434.18 s)
 (03/12) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.balloon_check.balloon_evict.balloon-migrate: PASS (308.58 s)
 (04/12) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.balloon_check.balloon_evict.balloon-reboot: PASS (349.48 s)
 (05/12) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.balloon_check.balloon_evict.balloon-shutdown: PASS (160.14 s)
 (06/12) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.balloon_check.balloon_evict.balloon-stop_continue: PASS (178.02 s)
 (07/12) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.balloon_check.balloon_enlarge.balloon-migrate: PASS (288.58 s)
 (08/12) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.balloon_check.balloon_enlarge.balloon-reboot: PASS (362.48 s)
 (09/12) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.balloon_check.balloon_enlarge.balloon-shutdown: PASS (176.22 s)
 (10/12) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.balloon_check.balloon_enlarge.balloon-stop_continue: PASS (177.41 s)
 (11/12) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.balloon_check.balloon_evict_and_enlarge.balloon_base: PASS (165.59 s)
 (12/12) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.balloon_check.balloon_evict_and_enlarge.balloon_oom: PASS (166.15 s)

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=block_with_iommu --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=Win2019,RHEL.8.3.0 --driveformat=virtio_blk,virtio_scsi --nicmodel=virtio_net --imageformat=qcow2 --machines=q35,i440fx --customsparams="image_aio=threads\ncd_format=ide" 

(01/16) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (858.73 s)
 (02/16) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (835.88 s)
 (03/16) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.rh_kernel_update: PASS (258.24 s)
 (04/16) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.rh_kernel_update.q35: PASS (278.91 s)
 (05/16) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (980.64 s)
 (06/16) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (895.61 s)
 (07/16) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (844.76 s)
 (08/16) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (865.64 s)
 (09/16) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.rh_kernel_update: PASS (391.63 s)
 (10/16) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.rh_kernel_update.q35: PASS (389.18 s)
 (11/16) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (1014.80 s)
 (12/16) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (931.61 s)
 (13/16) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_with_iommu.with_installation.cdrom.extra_cdrom_ks.q35: PASS (1079.49 s)
 (14/16) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_with_iommu.verify_enabled.q35: PASS (147.08 s)
 (15/16) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_with_iommu.verify_enabled.reload_kernel.q35:PASS (85.97 s)
 (16/16) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_with_iommu.with_installation.cdrom.extra_cdrom_ks.q35: PASS (1072.00 s)

LGTM

**Comment by yanglei-rh** [comment]
LGTM
Acked-by: Lei Yang

Test pass for virtual network:
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.boot_nic_with_intel_iommu.q35: PASS (70.69 s)
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.x86_64.io-github-autotest-qemu.boot_nic_with_intel_iommu.q35: PASS (64.45 s)
(2/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.boot_nic_with_intel_iommu.q35: PASS (100.12 s)
(2/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.boot_nic_with_intel_iommu.q35: PASS (90.65 s)

**Comment by menli820** [comment]
LGTM

Test pass on viostor, vioscs, rng and input device:

(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.block_with_iommu.with_installation.cdrom.extra_cdrom_ks.q35: PASS (633.28 s)

(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_with_iommu.with_installation.cdrom.extra_cdrom_ks.q35: PASS (935.78 s)

(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.vioinput_keyboard.iommu_enabled.q35: PASS (540.59 s)
(1/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.vioinput_mice.iommu_enabled.device_mouse.q35: PASS (418.04 s)
(2/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.vioinput_mice.iommu_enabled.device_tablet.q35: PASS (327.38 s)

(1/3) Host_RHEL.m8.u3.product_av.virtio_rng.rng_builtin.qcow2.virtio_blk.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.rng_bat.iommu_enabled.q35: PASS (166.71 s)
(2/3) Host_RHEL.m8.u3.product_av.virtio_rng.rng_random.qcow2.virtio_blk.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.rng_bat.iommu_enabled.q35: PASS (81.66 s)
(3/3) Host_RHEL.m8.u3.product_av.virtio_rng.rng_egd.qcow2.virtio_blk.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.rng_bat.iommu_enabled.q35: PASS (88.59 s)

**Comment by ybduan** [comment]
LGTM

 (1/9) Host_RHEL.m8.u3.product_av.virtio_rng.rng_builtin.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.rng_bat.iommu_enabled.q35: PASS (134.88 s)
 (2/9) Host_RHEL.m8.u3.product_av.virtio_rng.rng_builtin.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.rng_bat.iommu_enabled.scenario1.q35: PASS (133.73 s)
 (3/9) Host_RHEL.m8.u3.product_av.virtio_rng.rng_builtin.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.rng_bat.iommu_enabled.scenario2.q35: PASS (61.73 s)
 (4/9) Host_RHEL.m8.u3.product_av.virtio_rng.rng_random.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.rng_bat.iommu_enabled.q35: PASS (133.25 s)
 (5/9) Host_RHEL.m8.u3.product_av.virtio_rng.rng_random.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.rng_bat.iommu_enabled.scenario1.q35: PASS (134.67 s)
 (6/9) Host_RHEL.m8.u3.product_av.virtio_rng.rng_random.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.rng_bat.iommu_enabled.scenario2.q35: PASS (62.21 s)
 (7/9) Host_RHEL.m8.u3.product_av.virtio_rng.rng_egd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.rng_bat.iommu_enabled.q35: PASS (165.75 s)
 (8/9) Host_RHEL.m8.u3.product_av.virtio_rng.rng_egd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.rng_bat.iommu_enabled.scenario1.q35: PASS (164.94 s)
 (9/9) Host_RHEL.m8.u3.product_av.virtio_rng.rng_egd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.rng_bat.iommu_enabled.scenario2.q35: PASS (120.85 s)

**Comment by vivianQizhu** [comment]
@quanwenli Call for your review, thanks.

**Comment by quanwenli** [comment]
> @quanwenli Call for your review, thanks.

LGTM

JOB LOG    : /root/avocado/job-results/job-2020-08-31T02.40-dabaa82/job.log
 (1/1) repeat1.Host_RHEL.m8.u3.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.virtio_net_dpdk.q35: PASS (260.44 s)

**Comment by vivianQizhu** [comment]
Thanks all.

**Comment by huangyum** [comment]
Hi, seems Windows guest can't boot with device intel-iommu on an amd host. 
Tested cases: 
     vioinput_keyboard.iommu_enabled.q35, 
     balloon_check.balloon_evict_and_enlarge.iommu_enabled.q35
Guest: win2019
Host: AMD EPYC

**Comment by vivianQizhu** [comment]
@huangyum Did this test case pass before? Cause this patch only modify the order of command line, not adding anything, if it does not work, it should have never work before.

**Comment by lijinlijin** [comment]
@huangyum @vivianQizhu 
AMD iommu issue on win2019 can be tracked on product bz1842832.

**Comment by huangyum** [comment]
@vivianQizhu I just tried without this patch, the issue exists too. I agree it should have nothing to do with this patch. Thanks.

**Comment by vivianQizhu** [comment]
Okay. Thanks @lijinlijin @huangyum

**Comment by huangyum** [comment]
@lijinlijin I see, thanks!

**Pull request merged**
