### PR TITLE
blockdev_full_backup_multi_disks:correct blk_extra_param setting

### PR DESCRIPTION
**Pull request by aliang123**
Correct blk_extra_params setting for virtio_blk

Signed-off-by: Aihua Liang <aliang@redhat.com>
id:2124464

### CODE REVIEW

**Comment by MiriamDeng** [comment]
@maxujun can you help to review it ? Thanks

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m9.u2.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.blockdev_full_backup_multi_disks.with_data_plane.q35: PASS (114.83 s)

**Comment by aliang123** [comment]
@zhencliu @maxujun @MiriamDeng, please help to review, thanks.

**Comment by zhencliu** [comment]
LGTM

**Comment by maxujun** [comment]
No problem from my side.

**Comment by maxujun** [comment]
LGTM,

 (1/1) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.7.9.ppc64le.io-github-autotest-qemu.blockdev_full_backup_multi_disks.with_data_plane: PASS (223.65 s)

**Pull request merged**
