### PR TITLE
ntttcp:use serial login instead of SSH/Netcat

### PR DESCRIPTION
**Pull request by leidwang**
Currently,VM's session will be lost deue to Ncat reset
So I would like to replace it with serial login to improve it

ID:2076210
Signed-off-by: Leidong Wang <leidwang@redhat.com>

### CODE REVIEW

**Comment by leidwang** [comment]
Run the case  10 times on my host,all passed.So I think it is useful for current problem.

**Comment by leidwang** [comment]
Hi @Kemama Could you help to review this PR when you are free?Thanks!

**Comment by Kemama** [comment]
Hi, @leidwang 

After apply the path, here are the test result:
```
(01/10) repeat1.Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.ntttcp.q35: STARTED
 (01/10) repeat1.Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.ntttcp.q35: PASS (4696.49 s)
 (02/10) repeat2.Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.ntttcp.q35: STARTED
 (02/10) repeat2.Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.ntttcp.q35: PASS (5476.95 s)
 (03/10) repeat3.Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.ntttcp.q35: STARTED
 (03/10) repeat3.Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.ntttcp.q35: ERROR: Login timeout expired    (output: 'exceeded 237 s timeout, last failure: Could not verify DHCP lease: 9a:9e:7d:98:12:46 --> 10.73.74.223') (538.14 s)
 (04/10) repeat4.Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.ntttcp.q35: STARTED
 (04/10) repeat4.Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.ntttcp.q35: PASS (4877.30 s)
 (05/10) repeat5.Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.ntttcp.q35: STARTED
 (05/10) repeat5.Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.ntttcp.q35: PASS (5070.22 s)
 (06/10) repeat6.Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.ntttcp.q35: STARTED
 (06/10) repeat6.Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.ntttcp.q35: PASS (4733.86 s)
 (07/10) repeat7.Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.ntttcp.q35: STARTED
 (07/10) repeat7.Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.ntttcp.q35: PASS (5184.47 s)
 (08/10) repeat8.Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.ntttcp.q35: STARTED
 (08/10) repeat8.Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.ntttcp.q35: PASS (5087.68 s)
 (09/10) repeat9.Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.ntttcp.q35: STARTED
 (09/10) repeat9.Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.ntttcp.q35: PASS (5485.64 s)
 (10/10) repeat10.Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.ntttcp.q35: STARTED
 (10/10) repeat10.Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.ntttcp.q35: PASS (5069.75 s)
RESULTS    : PASS 9 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2022-07-20T01.35-293dfa1/results.html
```

LGTM. Thanks for your effort.

ACK: mama <mama@redhat.com>

**Comment by leidwang** [comment]
Hi @vivianQizhu Could you help to review this patch?Thanks!

**Review by vivianQizhu — APPROVED** [review]

**Pull request merged**
