### PR TITLE
fio-perf: add virtiofsd version to report

### PR DESCRIPTION
**Pull request by xiagao**
ID: 2182290
1. decode the byte string to string.
2. add virtiofsd version to report

### CODE REVIEW

**Comment by xiagao** [comment]
@YanhuiMa Could you help review this patch? thx.

**Comment by leidwang** [comment]
Hi @YanhuiMa Could you help to review this patch when you free?Thanks!

**Comment by YanhuiMa** [comment]
Sorry for the late review. It looks good to me. Thanks.

**Comment by xiagao** [comment]
@YongxueHong  Call for your review, thx.

**Comment by xiagao** [comment]
@YongxueHong Could you have a check this pr, thants.

**Review by YongxueHong — APPROVED** [review]
LGTM

**Pull request merged**
