### PR TITLE
Blockdev mirror test with sync mode top

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1878440

### CODE REVIEW

**Comment by zhencliu** [comment]
local fs:
 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_sync_top: PASS (163.74 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-18T00.12-dcdaec3/results.html
JOB TIME   : 170.06 s

iscsi direct:
 (1/1) Host_RHEL.m8.u3.product_av.iscsi_direct.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_sync_top: PASS (181.23 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-18T00.24-a02a911/results.html
JOB TIME   : 187.33 s

gluster direct:
 (1/1) Host_RHEL.m8.u3.product_av.gluster_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_mirror_sync_top: PASS (224.66 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2020-09-18T19.11-399515d/results.html
JOB TIME   : 228.18 s

nbd:
 (1/1) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_sync_top: PASS (198.54 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-18T07.29-e0273a9/results.html
JOB TIME   : 204.68 s

hi @YongxueHong @aliang123 , can you please help to review the patch? Thanks.

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_mirror_sync_top.q35: PASS (285.15 s)

Acked-by: Aihua Liang <aliang@redht.com>

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by zhencliu** [comment]
hi @ngu-niny , can you please help to review this patch? Thanks.

**Comment by ngu-niny** [comment]
LGTM and test PASS on ppc:

 (2/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.blockdev_mirror_sync_top: PASS (313.11 s)

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
