### PR TITLE
Add nic adaptability for multi_nics_verify

### PR DESCRIPTION
**Pull request by fbq815**
Virtual_network: add nic adaptability for multi_nics_verify to avoid missing ip address

ID: 2129274

Signed-off-by: Boqiao Fu <bfu@redhat.com>

### CODE REVIEW

**Comment by fbq815** [comment]
Test result:
JOB ID     : a8a5bb3615748a4ae953aa82a428eb3e19afcf95
JOB LOG    : /root/avocado/job-results/job-2022-09-30T03.55-a8a5bb3/job.log
 (1/5) repeat1.Host_RHEL.m9.u2.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.s390x.io-github-autotest-qemu.multi_nics_verify.nic_virtio.s390-virtio: STARTED
 (1/5) repeat1.Host_RHEL.m9.u2.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.s390x.io-github-autotest-qemu.multi_nics_verify.nic_virtio.s390-virtio: PASS (110.50 s)
 (2/5) repeat2.Host_RHEL.m9.u2.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.s390x.io-github-autotest-qemu.multi_nics_verify.nic_virtio.s390-virtio: STARTED
 (2/5) repeat2.Host_RHEL.m9.u2.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.s390x.io-github-autotest-qemu.multi_nics_verify.nic_virtio.s390-virtio: PASS (103.40 s)
 (3/5) repeat3.Host_RHEL.m9.u2.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.s390x.io-github-autotest-qemu.multi_nics_verify.nic_virtio.s390-virtio: STARTED
 (3/5) repeat3.Host_RHEL.m9.u2.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.s390x.io-github-autotest-qemu.multi_nics_verify.nic_virtio.s390-virtio: PASS (218.42 s)
 (4/5) repeat4.Host_RHEL.m9.u2.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.s390x.io-github-autotest-qemu.multi_nics_verify.nic_virtio.s390-virtio: STARTED
 (4/5) repeat4.Host_RHEL.m9.u2.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.s390x.io-github-autotest-qemu.multi_nics_verify.nic_virtio.s390-virtio: PASS (102.80 s)
 (5/5) repeat5.Host_RHEL.m9.u2.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.s390x.io-github-autotest-qemu.multi_nics_verify.nic_virtio.s390-virtio: STARTED
 (5/5) repeat5.Host_RHEL.m9.u2.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.s390x.io-github-autotest-qemu.multi_nics_verify.nic_virtio.s390-virtio: PASS (275.96 s)
RESULTS    : PASS 5 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2022-09-30T03.55-a8a5bb3/results.html
JOB TIME   : 817.99 s

@PaulYuuu @maxujun @yanglei-rh @Kemama please help me review this patch and check if it's working on your platform

**Comment by yanglei-rh** [comment]
X86 Test Pass
 (1/2) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_nics_verify.nic_virtio.q35: PASS (493.36 s)
 (2/2) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_nics_verify.with_multiqueue.nic_virtio.q35: PASS (1553.64 s)
 (1/2) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.multi_nics_verify.nic_virtio.q35: PASS (579.21 s)
 (2/2) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.x86_64.io-github-autotest-qemu.multi_nics_verify.with_multiqueue.nic_virtio.q35: PASS (560.82 s)

**Comment by Kemama** [comment]
```
 (2/3) Host_RHEL.m9.u2.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.multi_nics_verify.nic_virtio.q35: STARTED
 (2/3) Host_RHEL.m9.u2.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.multi_nics_verify.nic_virtio.q35: PASS (338.25 s)
 (3/3) Host_RHEL.m9.u2.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.multi_nics_verify.with_multiqueue.nic_virtio.q35: STARTED
 (3/3) Host_RHEL.m9.u2.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.multi_nics_verify.with_multiqueue.nic_virtio.q35: PASS (2770.63 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

```
```
 (2/3) Host_RHEL.m9.u2.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.multi_nics_verify.nic_virtio.q35: STARTED
 (2/3) Host_RHEL.m9.u2.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.multi_nics_verify.nic_virtio.q35: PASS (348.73 s)
 (3/3) Host_RHEL.m9.u2.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.multi_nics_verify.with_multiqueue.nic_virtio.q35: STARTED
 (3/3) Host_RHEL.m9.u2.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.multi_nics_verify.with_multiqueue.nic_virtio.q35: PASS (417.10 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```
```
 (2/3) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.multi_nics_verify.nic_virtio.q35: STARTED
 (2/3) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.multi_nics_verify.nic_virtio.q35: PASS (577.47 s)
 (3/3) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.multi_nics_verify.with_multiqueue.nic_virtio.q35: STARTED
 (3/3) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.multi_nics_verify.with_multiqueue.nic_virtio.q35: PASS (2888.53 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

```
LGTM

**Review by PaulYuuu — APPROVED** [review]

**Comment by fbq815** [comment]
@Kemama @yanglei-rh  please help me approve this patch, then maintainer could help me merge this patch, thanks

**Review by yanglei-rh — APPROVED** [review]

**Review by Kemama — APPROVED** [review]

**Comment by maxujun** [comment]
(1/2) Host_RHEL.m8.u7.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.ppc64le.io-github-autotest-qemu.multi_nics_verify.nic_virtio: STARTED 
(2/2) Host_RHEL.m8.u7.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.ppc64le.io-github-autotest-qemu.multi_nics_verify.with_multiqueue.nic_virtio:  PASS (276.27 s)
LGTM

**Comment by fbq815** [comment]
@PaulYuuu Hi yihyu, since everyone is acked, could you please help me merge this patch

**Pull request merged**
