### PR TITLE
qemu: Update isa_serials to serials in cfg files

### PR DESCRIPTION
**Pull request by ypu**
Related pullreq: 
https://github.com/autotest/virt-test/pull/2184

### CODE REVIEW

**Comment by ypu** [comment]
ID: 1220714

**Comment by ypu** [comment]
@xutian thanks for your remind. Can you help to check this pullreq?

**Comment by xutian** [comment]
LGTM,

Acked-by: Xu Tian <xutian@redhat.com>

**Comment by ypu** [comment]
Thanks @xutian will merge it.

**Pull request merged**
