### PR TITLE
change nics_virt-tests-vm1 to vm1 in multi_nics_stress.cfg

### PR DESCRIPTION
**Pull request by kimi1978wy**
change vm name to vm1 in order to boot 4 nics on vm1 as before

id:1479121

Signed-off-by: Yu Wang <wyu@redhat.com>

### CODE REVIEW

**Comment by kimi1978wy** [comment]
it can boot 4 nics as polarion cases. it is because vm name changed, cannot recognize "nics_virt-tests-vm1 = 'nic1 nic2 nic3 nic4'"

-device virtio-net-pci,mac=9a:8e:8f:90:91:92,id=idWtAbBE,vectors=4,netdev=idATgbno,bus=pci.0,addr=0x4 -netdev tap,id=idATgbno,vhost=on,vhostfd=21,fd=20 -device virtio-net-pci,mac=9a:93:94:95:96:97,id=idcXCu77,vectors=4,netdev=idzULK9i,bus=pci.0,addr=0x5 -netdev tap,id=idzULK9i,vhost=on,vhostfd=23,fd=22 -device virtio-net-pci,mac=9a:98:99:9a:9b:9c,id=idJ083rl,vectors=4,netdev=iddVVgR5,bus=pci.0,addr=0x6 -netdev tap,id=iddVVgR5,vhost=on,vhostfd=25,fd=24 -device virtio-net-pci,mac=9a:9d:9e:9f:a0:a1,id=idy6JtXO,vectors=4,netdev=idk65buz,bus=pci.0,addr=0x7 -netdev tap,id=idk65buz,vhost=on,vhostfd=27,fd=26

**Comment by xiywang** [comment]
Acked-by: Xiyue Wang xiywang@redhat.com

**Comment by suqinhuang** [comment]
Acked

**Comment by CongLi** [comment]
Thanks all.

**Comment by CongLi** [comment]
Please update the reason in the commit log too.

**Comment by kimi1978wy** [comment]
@CongLi commit log done
Thanks all.

**Comment by CongLi** [comment]
Thanks all.

**Pull request merged**
