### PR TITLE
tp-qemu: add missing param in cfgs who call case "driver_in_use".

### PR DESCRIPTION
**Pull request by CongLi**
Signed-off-by: Cong Li <coli@redhat.com>

id: 1334977

### CODE REVIEW

**Comment by CongLi** [comment]
@suqinhuang 

Could you help review this PR?

Thanks.

**Comment by suqinhuang** [comment]
Acked-by: Suqin Huang

**Comment by XueqiangWei** [comment]
LGTM,
Acked by XueqiangWei xuwei@redhat.com

**Comment by CongLi** [comment]
Thanks @suqinhuang @XueqiangWei .

**Pull request merged**
