### PR TITLE
pvpanic:update path of nmi in the guest on ppc

### PR DESCRIPTION
**Pull request by MiriamDeng**
ID:2020582 

Signed-off-by: MiriamDeng <mdeng@redhat.com>

### CODE REVIEW

**Comment by MiriamDeng** [comment]
@PaulYuuu @maxujun  could you help to review it ? Thanks.

**Comment by MiriamDeng** [comment]
I need to adjust it and please hold on, thanks.

**Comment by MiriamDeng** [comment]
Test results,
JOB ID     : 1960c81587d4c8f43ad3bd52a30eb864501195db
JOB LOG    : /root/avocado/job-results/job-2021-11-18T21.21-1960c81/job.log
 (1/6) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.pvpanic_basic.nmi: PASS (70.72 s)
 (2/6) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.pvpanic.with_stop_continue: PASS (97.52 s)
 (3/6) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.pvpanic.with_shutdown: PASS (172.16 s)
 (4/6) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.pvpanic.with_reboot: PASS (166.06 s)
 (5/6) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.pvpanic.with_system_reset: PASS (168.42 s)
 (6/6) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.pvpanic.with_live_migration: PASS (146.43 s)
RESULTS    : PASS 6 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by maxujun** [comment]
LGTM, Ack

**Review by PaulYuuu — APPROVED** [review]

**Pull request merged**
