### PR TITLE
Seabios bug fix

### PR DESCRIPTION
**Pull request by spcui**
ID: 1210151

### CODE REVIEW

**Comment by xutian** [comment]
@spcui 

Pep8 check failed, please fix and push it again.

Xu

**Comment by spcui** [comment]
hi @xutian already updated, could you help review again? thanks

**Comment by xutian** [comment]
@spcui  it better to move all function define in the head of funtion run().

**Comment by xutian** [comment]
LGTM,

Acked:  @xutian

**Comment by suqinhuang** [comment]
Acked-by: Suqin Huang

**Comment by ypu** [comment]
Thanks @spcui @xutian and @suqinhuang will merge it.

**Pull request merged**
