### PR TITLE
image_compare_bypass_host_cache: add new case

### PR DESCRIPTION
**Pull request by lolyu**
id:1777242
add new case to test `O_DIRECT` is on for `open` when cache mode is
`none`.

Signed-off-by: lolyu <lolyu@redhat.com>

### CODE REVIEW

**Comment by lolyu** [comment]
depends on #https://github.com/avocado-framework/avocado-vt/pull/2353

**Comment by lolyu** [comment]
```
 (1/1) Host_RHEL.m7.u7.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.image_compare_bypass_host_cache: PASS (21.65 s)
```

**Comment by hellohellenmao** [comment]
(1/1) Host_RHEL.m7.u8.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.image_compare_bypass_host_cache: PASS (21.90 s)

**Comment by hellohellenmao** [comment]
@YongxueHong Help to review, please.

**Pull request merged**
