### PR TITLE
storage_benchmark: Correct the clean method in windows

### PR DESCRIPTION
**Pull request by YongxueHong**
1. The command of checking the running process in windows
   should be "TASKLIST /FI "IMAGENAME eq $process_name.EXE".
2. No clean the env files if there are not env files.

ID: 1703339
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by YongxueHong** [comment]
@CongLi  @hereischen  @lolyu  @XueqiangWei  @kimi1978wy  @peixiu  pls help review, thanks.

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

**Comment by XueqiangWei** [comment]
LGTM,
Acked-by xuwei@redhat.com

**Comment by CongLi** [comment]
Ack.

**Comment by peixiu** [comment]
LGTM,
Acked-by: Peixiu Hou  phou@redhat.com

**Comment by kimi1978wy** [comment]
Acked-by: Yu Wang <wyu@redhat.com>

**Comment by YongxueHong** [comment]
Thanks all.

**Pull request merged**
