### PR TITLE
Check number of interrupts on guest after execute some tests

### PR DESCRIPTION
**Pull request by PaulYuuu**
Get interrupt info on guest, execute test and check again, to verify
that the interruption has increased.

ID: 1809450 1809452 1809454 1809456 1809459
Signed-off-by: Yihuang Yu <yihyu@redhat.com>

### CODE REVIEW

**Comment by PaulYuuu** [comment]
test result:
ppc:
```
 (1/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.interrupt_check.disk.scsi_device: PASS (105.00 s)
 (2/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.interrupt_check.disk.usb_device: PASS (117.19 s)
 (3/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.interrupt_check.net.virtio_device: PASS (83.65 s)
 (4/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.interrupt_check.net.spapr_device: PASS (83.53 s)
 (5/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.interrupt_check.event.IPI: PASS (81.84 s)
 (6/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.interrupt_check.event.RAS_HOTPLUG: PASS (88.08 s)
```
x86:
```
 (1/3) Host_RHEL.m8.u2.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.interrupt_check.disk.scsi_device: PASS (83.55 s)
 (2/3) Host_RHEL.m8.u2.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.interrupt_check.disk.usb_device: PASS (93.67 s)
 (3/3) Host_RHEL.m8.u2.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.interrupt_check.net.virtio_device: PASS (47.95 s)
```

**Comment by zhenyzha** [comment]
(1/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.interrupt_check.disk.scsi_device: PASS (104.12 s)
 (2/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.interrupt_check.disk.usb_device: PASS (125.95 s)
 (3/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.interrupt_check.net.virtio_device: PASS (81.79 s)
 (4/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.interrupt_check.net.spapr_device: PASS (103.87 s)
 (5/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.interrupt_check.event.IPI: PASS (86.65 s)
 (6/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.interrupt_check.event.RAS_HOTPLUG: PASS (93.45 s)

reviewing

**Comment by zhenyzha** [comment]
LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Comment by PaulYuuu** [comment]
Update variant names to avoid duplicates, thanks Zhenyu.
```
 (1/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.interrupt_check.disk_interrupt.scsi_device: PASS (107.88 s)
 (2/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.interrupt_check.disk_interrupt.usb_device: PASS (106.73 s)
 (3/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.interrupt_check.net_interrupt.virtio_device: PASS (82.23 s)
 (4/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.interrupt_check.net_interrupt.spapr_device: PASS (82.88 s)
 (5/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.interrupt_check.event_interrupt.IPI: PASS (99.66 s)
 (6/6) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.interrupt_check.event_interrupt.RAS_HOTPLUG: PASS (84.14 s)
```

**Pull request merged**
