### PR TITLE
 qemu_guest_agent_snapshot: update class name which has been changed in live_snapshot_basic.

### PR DESCRIPTION
**Pull request by CongLi**
Based on e11f160

Signed-off-by: Cong Li <coli@redhat.com>

### CODE REVIEW

**Comment by CongLi** [comment]
15:00:21 INFO | PASS 1-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_snapshot

**Comment by xutian** [comment]
Please rewrite your commit summary, and move commit ID from summary to commit message

**Comment by xutian** [comment]
code change looks ok to me.

**Comment by CongLi** [comment]
@xutian 

Commit log has been changed, could you help review it again?

Thanks.

**Comment by xutian** [comment]
Acked

**Comment by XueqiangWei** [comment]
LGTM,
Acked-by XueqiangWei <xuwei@redhat.com>

**Comment by CongLi** [comment]
Thanks @xutian @XueqiangWei , merged.

**Pull request merged**
