### PR TITLE
Update a parameter for numa stress test on ppc64le

### PR DESCRIPTION
**Pull request by MiriamDeng**
ID:2139976

Signed-off-by: MiriamDeng <mdeng@redhat.com>

### CODE REVIEW

**Comment by MiriamDeng** [comment]
@maxujun @PaulYuuu Can you help to review it  ?  Thanks.

**Comment by maxujun** [comment]
Can't analyze case，Please remove tab blank before "# Due to an known issue 2099550 on ppc64le" and "ppc64, ppc64le".

**Comment by MiriamDeng** [comment]
Updated

**Comment by MiriamDeng** [comment]
> 
Hi Xuma,
We can't use large size of tmpfs_size (full of memory of node 0) , or we will hit the known issue mentioned in the cfg file.

**Comment by MiriamDeng** [comment]
> > 
> 
> Hi Xuma, We can't use large size of tmpfs_size (full of memory of node 0) , otherwise we will hit the known issue mentioned in the cfg file. For the above error you met, it's another issue. I will check it.

**Review by PaulYuuu — DISMISSED** [review]

**Comment by maxujun** [comment]
> > > 
> > 
> > 
> > Hi Xuma, We can't use large size of tmpfs_size (full of memory of node 0) , otherwise we will hit the known issue mentioned in the cfg file. For the above error you met, it's another issue. I will check it.
(1/1) Host_RHEL.m8.u8.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.ppc64le.io-github-autotest-qemu.numa.numa_stress: FAIL: Memory still stick in node 0 (276.38 s)

It's the test result for this patch on ppc,not large size of tmpfs_size. I didn't find the best way to disable oom killer.I suggest disable this case for ppc because the host memory of ppc is usually so large than x86 host that trigger oom killer for this case.

**Comment by MiriamDeng** [comment]
Thanks xuma,
It's easy to disable the test case but let us wait for the result, if #3595 can fix the root problem. And then decide to disable it or not on ppc. Thanks.

**Comment by MiriamDeng** [comment]
> > > > 
> > > 
> > > 
> > > Hi Xuma, We can't use large size of tmpfs_size (full of memory of node 0) , otherwise we will hit the known issue mentioned in the cfg file. For the above error you met, it's another issue. I will check it.
> > > (1/1) Host_RHEL.m8.u8.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.ppc64le.io-github-autotest-qemu.numa.numa_stress: FAIL: Memory still stick in node 0 (276.38 s)
> 
> It's the test result for this patch on ppc,not large size of tmpfs_size. I didn't find the best way to disable oom killer.I suggest disable this case for ppc because the host memory of ppc is usually so large than x86 host that trigger oom killer for this case.

Do you agree with me if we disable the test case on ppc  at the moment ? Thanks @maxujun @PaulYuuu .

**Comment by PaulYuuu** [comment]
> Do you agree with me if we disable the test case on ppc at the moment ? Thanks @maxujun @PaulYuuu .

It's okay for me.

**Comment by maxujun** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Hi Xuma, We can't use large size of tmpfs_size (full of memory of node 0) , otherwise we will hit the known issue mentioned in the cfg file. For the above error you met, it's another issue. I will check it.
> > > > (1/1) Host_RHEL.m8.u8.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.ppc64le.io-github-autotest-qemu.numa.numa_stress: FAIL: Memory still stick in node 0 (276.38 s)
> > 
> > 
> > It's the test result for this patch on ppc,not large size of tmpfs_size. I didn't find the best way to disable oom killer.I suggest disable this case for ppc because the host memory of ppc is usually so large than x86 host that trigger oom killer for this case.
> 
> Do you agree with me if we disable the test case on ppc at the moment ? Thanks @maxujun @PaulYuuu .

OK for me.

**Comment by MiriamDeng** [comment]
root@ibm-p9wr-07 io-github-autotest-qemu]# git am 3580.patch
Applying: Disable numa stress on ppc64le
No related test case has been filtered out, thanks.

**Review by PaulYuuu — APPROVED** [review]

**Pull request merged**
