### PR TITLE
tp-qemu: single_driver_install: some corrections of code.

### PR DESCRIPTION
**Pull request by CongLi**
1. fix a syntax error.
The end double quote of variant "guest_alias" will be
analyzed as a string \" in raw string.
2. Update the path of driver virtio serial.

Signed-off-by: Cong Li <coli@redhat.com>

id: 1334077

### CODE REVIEW

**Comment by maxujun** [comment]
the issue has already fixed with win2012r2 ,but there are some other issues as following:
1.with drive format virtio_blk:the vm of the cases after "virtio_install.with_vioscsi" will appear blue screen
2.with drive format virtio_scsi:the cdroms will disappear when uninstall vioscsi,and it make reinstalling vioscsi failed
3.the case "with_vioserial" always failed bacause the path of the driver is wrong ,can't find the driver via path E:\vioser\2k12R2\amd64,it's in the path E:\vioserial\2k12R2\amd64

**Comment by CongLi** [comment]
@maxujun 

1. could you check whether it's a product bug of BSOD ?
2.             cd_format_fixed =ide
Could you using autotest only for the test, exclude internal cfg?
3. I will fix the driver path problem, thanks for your review.

**Comment by maxujun** [comment]
@CongLi 
ok
about this patch,LGTM
Acked-by: xuma@redhat.com

**Comment by CongLi** [comment]
16:50:15 INFO | PASS 1-smp_8.2048m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.Win2012.x86_64.r2.io-github-autotest-qemu.single_driver_install.virtio_install.with_vioserial

**Comment by maxujun** [comment]
LGTM
Acked-by: xuma@redhat.com

**Comment by suqinhuang** [comment]
Acked-by: Suqin Huang

**Pull request merged**
