### PR TITLE
luks_compare: add new case

### PR DESCRIPTION
**Pull request by lolyu**
id: 1777186
add new test case to compare luks images with different cache modes.

Signed-off-by: lolyu <lolyu@redhat.com>

### CODE REVIEW

**Comment by lolyu** [comment]
@YongxueHong @hellohellenmao please help to review, thanks.

**Comment by hellohellenmao** [comment]
Add the bug id, please.

**Comment by hellohellenmao** [comment]
(1/6) Host_RHEL.m7.u8.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.luks_compare:  PASS (987.33 s)
 (2/6) Host_RHEL.m7.u8.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.luks_compare.cache_mode.none:  PASS (1016.79 s)
 (3/6) Host_RHEL.m7.u8.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.luks_compare.cache_mode.writeback:  PASS (976.49 s)
 (4/6) Host_RHEL.m7.u8.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.luks_compare.cache_mode.unsafe:  PASS (983.14 s)
 (5/6) Host_RHEL.m7.u8.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.luks_compare.cache_mode.directsync:  PASS (991.96 s)
 (6/6) Host_RHEL.m7.u8.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.luks_compare.cache_mode.writethrough:  PASS (973.70 s)

**Comment by lolyu** [comment]
needs a further update, please do not review, thanks.

**Comment by hellohellenmao** [comment]
From the log file, I noticed that there is `/bin/qemu-img` for `convert`, while for `compare`, there is `qemu-img`.  Check, please.

 05:24:53 INFO | Running '/bin/qemu-img convert --object secret,id=image1_encrypt0,data=redhat --object secret,id=convert_encrypt0,data=convert -O luks -o key-secret=convert_encrypt0 'json:{"driver": "luks", "file": {"driver": "file", "filename": "/home/kvm_autotest_root/images/rhel77-64-virtio-scsi.luks"}, "key-secret": "image1_encrypt0"}' /home/kvm_autotest_root/images/luks_to_luks.luks'

05:32:58 INFO | Running 'qemu-img compare --object secret,id=image1_encrypt0,data=redhat --object secret,id=convert_encrypt0,data=convert 'json:{"driver": "luks", "file": {"driver": "file", "filename": "/home/kvm_autotest_root/images/rhel77-64-virtio-scsi.luks"}, "key-secret": "image1_encrypt0"}' 'json:{"driver": "luks", "file": {"driver": "file", "filename": "/home/kvm_autotest_root/images/luks_to_luks.luks"}, "key-secret": "convert_encrypt0"}''

**Comment by lolyu** [comment]
depends on #2007

**Comment by lolyu** [comment]
```
 (1/6) Host_RHEL.m7.u7.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.luks_compare: PASS (896.68 s)
 (2/6) Host_RHEL.m7.u7.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.luks_compare.cache_mode.none: PASS (1202.35 s)
 (3/6) Host_RHEL.m7.u7.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.luks_compare.cache_mode.writeback: PASS (908.49 s)
 (4/6) Host_RHEL.m7.u7.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.luks_compare.cache_mode.unsafe: PASS (856.50 s)
 (5/6) Host_RHEL.m7.u7.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.luks_compare.cache_mode.directsync: PASS (1147.35 s)
 (6/6) Host_RHEL.m7.u7.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.luks_compare.cache_mode.writethrough: PASS (890.97 s)

```

**Comment by hellohellenmao** [comment]
(1/6) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.luks_compare: PASS (3983.65 s)
 (2/6) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.luks_compare.cache_mode.none: PASS (2641.75 s)
 (3/6) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.luks_compare.cache_mode.writeback: PASS (3118.99 s)
 (4/6) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.luks_compare.cache_mode.unsafe: PASS (2574.92 s)
 (5/6) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.luks_compare.cache_mode.directsync: PASS (2006.79 s)
 (6/6) Host_RHEL.m8.u1.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.luks_compare.cache_mode.writethrough: PASS (2280.02 s)

**Pull request merged**
