### PR TITLE
rng_iommu: restrict iommu testing only for Intel platform

### PR DESCRIPTION
**Pull request by ybduan**
ID: 1951893

Signed-off-by: ybduan <yduan@redhat.com>

### CODE REVIEW

**Comment by ybduan** [comment]
(1/9) Host_RHEL.m8.u4.product_av.virtio_rng.rng_builtin.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.rng_bat.iommu_enabled.q35: CANCEL: This case only support Intel platform (35.23 s)
 (2/9) Host_RHEL.m8.u4.product_av.virtio_rng.rng_builtin.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.rng_bat.iommu_enabled.scenario1.q35: CANCEL: This case only support Intel platform (27.42 s)
 (3/9) Host_RHEL.m8.u4.product_av.virtio_rng.rng_builtin.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.rng_bat.iommu_enabled.scenario2.q35: CANCEL: This case only support Intel platform (26.40 s)
 (4/9) Host_RHEL.m8.u4.product_av.virtio_rng.rng_random.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.rng_bat.iommu_enabled.q35: CANCEL: This case only support Intel platform (27.26 s)
 (5/9) Host_RHEL.m8.u4.product_av.virtio_rng.rng_random.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.rng_bat.iommu_enabled.scenario1.q35: CANCEL: This case only support Intel platform (27.71 s)
 (6/9) Host_RHEL.m8.u4.product_av.virtio_rng.rng_random.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.rng_bat.iommu_enabled.scenario2.q35: CANCEL: This case only support Intel platform (26.27 s)
 (7/9) Host_RHEL.m8.u4.product_av.virtio_rng.rng_egd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.rng_bat.iommu_enabled.q35: CANCEL: This case only support Intel platform (32.59 s)
 (8/9) Host_RHEL.m8.u4.product_av.virtio_rng.rng_egd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.rng_bat.iommu_enabled.scenario1.q35: CANCEL: This case only support Intel platform (34.66 s)
 (9/9) Host_RHEL.m8.u4.product_av.virtio_rng.rng_egd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.rng_bat.iommu_enabled.scenario2.q35: CANCEL: This case only support Intel platform (34.90 s)

**Comment by ybduan** [comment]
Please help review this PR, thanks! @yanan-fu

**Comment by yanan-fu** [comment]
`only HostCpuVendor.intel` is enough.

**Comment by ybduan** [comment]
Yes, you're right. Thanks!

**Comment by ybduan** [comment]
(1/3) Host_RHEL.m8.u4.product_av.virtio_rng.rng_builtin.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.rng_bat.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (2/3) Host_RHEL.m8.u4.product_av.virtio_rng.rng_random.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.rng_bat.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (3/3) Host_RHEL.m8.u4.product_av.virtio_rng.rng_egd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.rng_bat.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

**Comment by yanan-fu** [comment]
Ack

**Pull request merged**
