### PR TITLE
blockdev_stream_hotunplug: Add hotunplug test during stream

### PR DESCRIPTION
**Pull request by zhencliu**
hotunplug frontend device: Succeeded
  hotunplug format node: CHeck the proper error message output

Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1902371

### CODE REVIEW

**Comment by zhencliu** [comment]
iscsi direct + virtio-blk
 (1/1) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream_hotunplug.q35: PASS (181.71 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-28T16.40-4874d0f/results.html
JOB TIME   : 184.99 s

local fs:
 (1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream_hotunplug.q35: PASS (189.01 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-28T03.50-c57c15c/results.html
JOB TIME   : 191.47 s

nbd:
 (1/1) Host_RHEL.m8.u3.product_av.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_hotunplug: PASS (201.89 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-28T04.05-a8e395d/results.html
JOB TIME   : 204.32 s

ceph:
 (1/1) Host_RHEL.m8.u3.product_av.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_stream_hotunplug.q35: PASS (201.70 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-11-28T16.51-cdc0be7/results.html
JOB TIME   : 205.01 s

**Comment by zhencliu** [comment]
hi @YongxueHong @ngu-niny , can you please help review this patch? Thanks.
it deps on #2504

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by ngu-niny** [comment]
Test PASS:

(5/6) type_specific.io-github-autotest-qemu.blockdev_stream_hotunplug:  PASS (248.99 s)

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
