### PR TITLE
win_driver_utils:add condition to copy msi files

### PR DESCRIPTION
**Pull request by xiagao**
Currently all installer test cases will
copy msi and installer related files, actually
there is no need to copy msi if there is no specific requirement.
So that, add condition in this utils.
ID: 2415

### CODE REVIEW

**Comment by xiagao** [comment]
@6-dehan Could you help review this patch?

**Review by 6-dehan — APPROVED** [review]
LGTM after confirming with @xiagao 
 (1/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: STARTED
 (1/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (987.85 s)
 (2/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.gagent_driver_update_via_installer_tool.q35: STARTED
 (2/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.gagent_driver_update_via_installer_tool.q35: PASS (347.05 s)

**Comment by xiagao** [comment]
@vivianQizhu Could you please help review? thanks.

**Review by leidwang — APPROVED** [review]
LGTM.

**Review by vivianQizhu — APPROVED** [review]

**Pull request merged**
