### PR TITLE
tp-qemu: multi_queues_test.py: Update the case steps.

### PR DESCRIPTION
**Pull request by CongLi**
Signed-off-by: Cong Li <coli@redhat.com>

id: 1202280

### CODE REVIEW

**Comment by xutian** [comment]
I don't think this is a reasonable fix. Please check is this a valid test case, or  it required some setup before test.

Thanks,
@xutian

**Comment by CongSmile** [comment]
Hi @xutian 

I have updated the code, could you help review it again?

Thanks.

**Comment by CongSmile** [comment]
This PR based on #421.

smp must be equal to queues when need check cpu affinity.

Thanks.

**Comment by Zhengtong** [comment]
review work blocked on powerpc by id:1314636

**Comment by CongLi** [comment]
Close this one.
@xutian will fix this problem.

**Pull request closed without merging**
