### PR TITLE
add case for block stream feature

### PR DESCRIPTION
**Pull request by xutian**
ID: 1785995

Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
deps on #2035

**Comment by xutian** [comment]
@aliang123 and @ngu-niny  would you like to help review this patch, thanks.

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_stream.q35: FAIL: AttributeError("'NoneType' object has no attribute 'get_output'",)

**Comment by xutian** [comment]
@aliang123  and @ngu-niny  updated test step,  test done in my side, please help double check.

[root@virtlab-66-85-182 kar]# python3 ./workspace/avocado-vt/scripts/scan_results.py 
CaseName                                 Status          StartTime       EndTime         Result     TimeElapsed
'1-Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_stream' Finshed 2019-12-24 11:17:17 2019-12-24 11:18:54 PASS 97.027489
Summary: 
Finshed=1, PASS=1

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u2.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.2.0.x86_64.io-github-autotest-qemu.blockdev_stream.q35: PASS (99.90 s)

**Comment by aliang123** [comment]
Acked-by: Aihua Liang<aliang@redhat.com>

**Comment by ngu-niny** [comment]
Test PASS:

'1-Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.2.0.ppc64le.io-github-autotest-qemu.blockdev_stream' Finshed 2019-12-24 00:37:43 2019-12-24 00:42:18 PASS 275.547433

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
