### PR TITLE
Add SecurityHealthService access for Win2025 and WinNext

### PR DESCRIPTION
**Pull request by peixiu**
New guests need set administrator access for SecurityHealthService

ID:2342

Signed-off-by: Peixiu Hou <phou@redhat.com>

### CODE REVIEW

**Comment by peixiu** [comment]
python3 ConfigTest.py --testcase=hv_check_cpu_utilization --clone=no --guestname=Win2025  --machines=q35 --firmware=ovmf

 (1/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.hv_check_cpu_utilization.q35: STARTED
 (1/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.hv_check_cpu_utilization.q35: PASS (4211.72 s)
 (2/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.hv_check_cpu_utilization.with_migration.q35: STARTED
 (2/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.hv_check_cpu_utilization.with_migration.q35: PASS (4268.82 s)

Hi @menli820 @YongxueHong  Could you help to review this patch? 

Thanks!
Peixiu

**Comment by menli820** [comment]
@peixiu  for the commit title, suggest a change to  "hv_check_cpu_utilization: XX"  , other ack.

**Comment by peixiu** [comment]
Hi @menli820 , with the case name, the title will longer than 72 characters, that'll triger the commiet lint failed. 
And in order to keep the title's key info, I prefer to don't use the case name at this commit. How do you think?

Thanks~

**Comment by YongxueHong** [comment]
> Hi @menli820 , with the case name, the title will longer than 72 characters, that'll triger the commiet lint failed. And in order to keep the title's key info, I prefer to don't use the case name at this commit. How do you think?
> 
> Thanks~
Hi @peixiu 
You could simplify the title like `hv_check_cpu_utilization: Add SecurityService access for new windows` since you will give further details in the commit message.
Or you could just remove the str `[tp-qemu]` in the previous title since the string does not make sense.

**Comment by peixiu** [comment]
@YongxueHong @menli820 Done, thanks!
BTW, adding the case name in the commit title is a review reference, yes?

**Comment by YongxueHong** [comment]
> @YongxueHong @menli820 Done, thanks! BTW, adding the case name in the commit title is a review reference, yes?


Hi @peixiu 
Yes, we suggest the title format is `$Target name: $header content (limited to 72 characters. No period.)
`
and we recommend the target name is the case name, you could use the feature name as the target name if you modify many files for the same feature. and you could remove the target name since the limitation requirement, like in this case. But we suggest using the recommended format for the title first.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Review by menli820 — APPROVED** [review]

**Comment by menli820** [comment]
LGTM

**Comment by peixiu** [comment]
> > @YongxueHong @menli820 Done, thanks! BTW, adding the case name in the commit title is a review reference, yes?
> 
> Hi @peixiu Yes, we suggest the title format is `$Target name: $header content (limited to 72 characters. No period.) ` and we recommend the target name is the case name, you could use the feature name as the target name if you modify many files for the same feature. and you could remove the target name since the limitation requirement, like in this case. But we suggest using the recommended format for the title first.

Got it, Thanks!

**Pull request merged**
