### PR TITLE
qemu.tests: Update nic_bonding to cover more test point.

### PR DESCRIPTION
**Pull request by FengYang**
ID: 1128057

Signed-off-by: Feng Yang <fyang@redhat.com>

### CODE REVIEW

**Comment by yaxue** [comment]
Hi @FengYang ,
should we add the step to check the md5 value after transferred ? maybe it will be more complete.
Any wrong place feel free to contact me, thanks

**Comment by FengYang** [comment]
On 01/23/2015 02:20 PM, yaxue wrote:
>
> Hi @FengYang <https://github.com/FengYang> ,
> should we add the step to check the md5 value after transferred ?
> maybe it will be more complete.
> Any wrong place feel free to contact me, thanks
>
Hi yaxue,

We already have md5 check steps in run_file_transfer() function.

**Comment by yaxue** [comment]
Hi @FengYang ,
Yes , has re-checked the function run_file_transfer() and find the step. Thank you.
LGTM
Acked-by: Yang Xue <yaxue@redhat.com>

**Comment by FengYang** [comment]
Thanks @yaxue

**Pull request merged**
