### PR TITLE
hotplug_virtio_mem.cfg: Add support on windows side

### PR DESCRIPTION
**Pull request by menli820**
Add support on windows side to test viomem hotplug.

ID: 3166

### CODE REVIEW

**Comment by menli820** [comment]
# python3 ConfigTest.py --testcase=hotplug_virtio_mem --guestname=Win2025 --driveformat=virtio_blk  --clone=no --machines=q35

 (1/1) Host_RHEL.m9.u6.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.hotplug_virtio_mem.q35: STARTED
 (1/1) Host_RHEL.m9.u6.ovmf.qcow2.virtio_blk.up.virtio_net.Guest.Win2025.x86_64.io-github-autotest-qemu.hotplug_virtio_mem.q35: PASS (178.23 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by menli820** [comment]
@leidwang please help to review this patch when you free, thanks

**Review by leidwang — APPROVED** [review]
LGTM.

**Comment by menli820** [comment]
@PaulYuuu  please help to review it when you free, thanks

**Review by PaulYuuu — APPROVED** [review]

**Pull request merged**
