### PR TITLE
virtio_fs: add memory check steps with verifier enabled

### PR DESCRIPTION
**Pull request by xiagao**
For driver test, if driver verifier is enabled, to get memory leak, it's better to disable or uninstall driver after driver test.
ID: 2138792
Signed-off-by: Xiaoling Gao <xiagao@redhat.com>

### CODE REVIEW

**Comment by xiagao** [comment]
(1/2) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_hotplug.plug.one_fs_source.q35: STARTED
 (1/2) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_hotplug.plug.one_fs_source.q35: PASS (459.62 s)
 (2/2) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_hotplug.unplug.one_fs_source.q35: STARTED
 (2/2) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_hotplug.unplug.one_fs_source.q35: PASS (147.24 s)
 (24/68) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.none.with_writeback.q35: STARTED
 (24/68) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.none.with_writeback.q35: PASS
 (32/68) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_cache.auto.with_nfs_source.q35: STARTED
 (32/68) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_share_data_multi_backend.with_cache.auto.with_nfs_source.q35: PASS (371.16 s)
 (49/68) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_share_data_hugepage.basic_test.with_cache.auto.q35: STARTED
 (49/68) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_share_data_hugepage.basic_test.with_cache.auto.q35: PASS
 (58/68) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_sys_admin.without_xattr.with_cache.none.q35: STARTED
 (58/68) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_sys_admin.without_xattr.with_cache.none.q35: PASS (370.00 s)

**Comment by xiagao** [comment]
@leidwang  @YongxueHong  Call for your review, thanks.

**Review by hereischen — DISMISSED** [review]

**Comment by leidwang** [comment]
LGTM.

**Review by leidwang — APPROVED** [review]

**Review by hereischen — APPROVED** [review]

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
