### PR TITLE
Remove ib700 test cases for q35

### PR DESCRIPTION
**Pull request by yiqianwei**
Device 'ib700' can't go on PCIE bus, so remove it

ID: 2035734

Signed-off-by: Yiqian Wei <yiwei@redhat.com>

### CODE REVIEW

**Comment by yiqianwei** [comment]
Test results:
(01/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (02/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.rh_kernel_update.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (03/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.system_reset_bootable.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (04/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.system_powerdown.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (05/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.system_reset_during_boot.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (06/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.stop_continue.stop_cont_only.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (07/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.boot.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (08/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.reboot.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (09/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.shutdown.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (10/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.boot_with_watchdog.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (11/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.magic_close.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (12/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_action.reboot_guest.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (13/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_action.shutdown_guest.i6300esb.q35:CANCEL: Test cancelled due to --dry-run (0.00 s)
 (14/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_action.pause_guest.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (15/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_action.noaction.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (16/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_action.debug.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (17/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_action.poweroff.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (18/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_action.inject_nmi.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (19/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.migration_when_wdt_timeout.reboot_guest.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (20/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.migration_when_wdt_timeout.pause.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (21/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.migration_when_wdt_timeout.x_rdma.reboot_guest.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (22/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.migration_when_wdt_timeout.x_rdma.pause.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (23/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.migration_when_wdt_timeout.rdma.reboot_guest.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (24/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.migration_when_wdt_timeout.rdma.pause.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (25/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.hotplug_unplug_watchdog_device.i6300esb.q35:CANCEL: Test cancelled due to --dry-run (0.00 s)
 (26/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.stop_cont_test.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (27/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.watchdog_test_suit.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (28/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.heartbeat_test.valid.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (29/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.heartbeat_test.invalid_1.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (30/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.heartbeat_test.invalid_0.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (31/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.heartbeat_test.invalid_min.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (32/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.heartbeat_test.invalid_max.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)
 (33/33) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.x86_64.io-github-autotest-qemu.watchdog.heartbeat_test.invalid_excp.i6300esb.q35: CANCEL: Test cancelled due to --dry-run (0.00 s)

**Comment by yiqianwei** [comment]
@yanan-fu  Would you please help to review this patch? thanks a lot.

**Comment by yanan-fu** [comment]
Could you add the reason for this change in the commit info, thanks

**Comment by yiqianwei** [comment]
> Could you add the reason for this change in the commit info, thanks
@yanan-fu ,  I have updated it, please check it, thanks

**Review by yanan-fu — APPROVED** [review]
Ack

**Pull request merged**
