### PR TITLE
qemu.test: qemu_img_convert_with_backing_file

### PR DESCRIPTION
**Pull request by XueqiangWei**
convert image with parameters -B -n

Signed-off-by: Xueqiang Wei <xuwei@redhat.com>
ID: 1942225, 1942226, 1942227

### CODE REVIEW

**Comment by XueqiangWei** [comment]
depends on avocado-framework/avocado-vt/pull/2971

**Comment by XueqiangWei** [comment]
1/1) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img_convert_with_backing_file.q35: PASS (201.20 s)
(1/1) Host_RHEL.m8.u4.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img_convert_with_backing_file.q35: PASS (515.30 s)

**Comment by XueqiangWei** [comment]
@zhencliu Please help review it. Many thanks.

**Comment by XueqiangWei** [comment]
(1/1) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img_convert_with_backing_file.q35: PASS (212.90 s)

**Comment by XueqiangWei** [comment]
(1/1) Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.qemu_img_convert_with_backing_file.q35: PASS (204.24 s)

@zhencliu Please help review it. Many thanks.

**Comment by zhencliu** [comment]
LGTM

The following is just something fyi.
For these cases, we can see, so many test steps, we might encapsulate these steps in several functions, then we can organize these functions(with meaningful names) in a clear way

**Pull request merged**
