### PR TITLE
qemu-guest-agent: Erase some invalid timeout settings

### PR DESCRIPTION
**Pull request by 6-dehan**
qemu_guest_agent.py: clean timeout parameters for some commands.

ID: 2031084
Signed-off-by: demeng <demeng@redhat.com>

### CODE REVIEW

**Comment by 6-dehan** [comment]
@vivianQizhu could you help to review that ? thanks
(1/1) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.gagent_ssh_public_key_injection.q35: PASS (62.39 s)

**Comment by vivianQizhu** [comment]
Hello @BohdanMar Would you please help review it? I suppose you hit same issue. cc @PaulYuuu

**Comment by BohdanMar** [comment]
Hello @vivianQizhu 
After running testcase "qemu_guest_agent.virtio_serial.gagent_ssh_public_key_injection" with new patch - it works well, without any errors.
 (1/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.arm64-pci: PASS (1514.03 s)
 (2/2) Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.aarch64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.gagent_ssh_public_key_injection.arm64-pci: PASS (128.17 s)

Acked-by: Bogdan Marcynkov bmarcynk@redhat.com

**Comment by PaulYuuu** [comment]
Thanks all.

**Pull request merged**
