### PR TITLE
blockdev_stream_forbidden_actions: Add qmp cmd test during stream

### PR DESCRIPTION
**Pull request by zhencliu**
mirror/commit/resize/live snapshot/stream action should be forbidden
  when doing block-stream

Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1904988

### CODE REVIEW

**Comment by zhencliu** [comment]
local fs:
 (1/1) Host_RHEL.m8.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream_forbidden_actions.q35: PASS (89.69 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-07T05.09-55b5342/results.html
JOB TIME   : 92.18 s

nbd:
 (1/1) Host_RHEL.m8.u3.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_forbidden_actions: PASS (141.44 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-07T05.19-de455c2/results.html
JOB TIME   : 143.91 s

iscsi direct:
 (1/1) Host_RHEL.m8.u3.iscsi_direct.raw.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_stream_forbidden_actions.q35: PASS (56.55 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-12-07T18.23-dba7c78/results.html
JOB TIME   : 59.70 s

**Comment by zhencliu** [comment]
Hi @ngu-niny @YongxueHong , can you please help to review this patch? Thanks.

@ngu-niny , for the error msg check, as there is no specific error msg for each qmp cmd in manual case, I just follow the output during my testing, here is a summary:

mirror/commit:
Need a root block node

live snapshot/stream:
Node '${top_device_node}' is busy: block device is in use by block job: stream

block_resize:
Device '(null)' is in use

Just FYI.

**Comment by ngu-niny** [comment]
LGTM and test PASS:

PASS 1-type_specific.io-github-autotest-qemu.blockdev_stream_forbidden_actions

Acked-by: Nini Gu <ngu@redhat.com>

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
