### PR TITLE
boot_from_virtiofs: support linux guest only

### PR DESCRIPTION
**Pull request by xiagao**
ID: 2188880

### CODE REVIEW

**Comment by xiagao** [comment]
@leidwang  Pls help review this one, thank you.

**Review by leidwang — DISMISSED** [review]
LGTM.

**Comment by xiagao** [comment]
@YongxueHong Call for your review, thanks.

**Comment by YongxueHong** [comment]
Hi @xiagao 
Could you add the details of the reason in the commit message?
Thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Pull request merged**
