### PR TITLE
qemu.tests: Update the balloon disable check string

### PR DESCRIPTION
**Pull request by ypu**
Update the check string as the output from monitor is changed.

### CODE REVIEW

**Comment by ypu** [comment]
ID: 1146807

**Comment by CongSmile** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by suqinhuang** [comment]
Hi ypu,
How about to set the check string in our cfg file? 

Regards,
Suqin

**Comment by ypu** [comment]
@suqinhuang Just think the output from monitor is kind of stable. It should not have a lot of change. So can we just keep it like this this time. And if we met it again. Will make it configurable in cfg. thanks for your comments.

**Comment by suqinhuang** [comment]
LGTM
Acked-by: Suqin Huang

**Comment by ypu** [comment]
Thanks @CongSmile and @suqinhuang Will merge it.

**Pull request merged**
