### PR TITLE
thp_fragment: updates tool to v2 and extracts it to a new location

### PR DESCRIPTION
**Pull request by mcasquer**
thp_fragment: updates tool to v2 and extracts it to a new location

Updates the thp_fragment to the new version where the tool
works better in environments with a great amount of memory.
Also extracts this tool to the 'root deps' directory as it is
going to be used by a new provider script and the tarball will
no longer needed, this way the file can be reviewed easily by
the maintainers where new changes arrive and the extraction
step can be saved.

Signed-off-by: mcasquer <mcasquer@redhat.com>
ID: 2067

### CODE REVIEW

**Comment by mcasquer** [comment]
@luckyh @yanan-fu @YongxueHong please, could you review this PR? Thanks !

**Comment by YongxueHong** [comment]
Hi @mcasquer 
I got your purpose, there is just one concern that it may affect the related test case which is calling the previous path, for example, https://github.com/autotest/tp-qemu/blob/539f0cb578680f344610b18487ba511e2ecd6897/generic/tests/trans_hugepage_defrag.py#L67C8-L67C73

Would you like to run a regression with the new path?
Thanks.

**Comment by mcasquer** [comment]
> Hi @mcasquer I got your purpose, there is just one concern that it may affect the related test case which is calling the previous path, for example, https://github.com/autotest/tp-qemu/blob/539f0cb578680f344610b18487ba511e2ecd6897/generic/tests/trans_hugepage_defrag.py#L67C8-L67C73
> 
> Would you like to run a regression with the new path? Thanks.

@YongxueHong yeah sorry, I forgot to put on 'ready for review' the rest of the PRs, but this is already handled applying the other patches :grinning: 

```
 (1/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.trans_hugepage.defrag.q35: STARTED
 (1/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.trans_hugepage.defrag.q35: PASS (55.72 s)
 (2/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.trans_hugepage.relocated.q35: STARTED
 (2/2) Host_RHEL.m9.u5.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.5.0.x86_64.io-github-autotest-qemu.trans_hugepage.relocated.q35: PASS (725.84 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```
Ps: https://github.com/autotest/tp-qemu/pull/3988, https://github.com/autotest/tp-qemu/pull/3989, https://github.com/autotest/tp-qemu/pull/3979

**Comment by yanan-fu** [comment]
The provider script be removed with the latest update ?

**Comment by mcasquer** [comment]
> The provider script be removed with the latest update ?

It is being moved to the root deps directory in order to be used by the #3988 script

**Comment by yanan-fu** [comment]
> > The provider script be removed with the latest update ?
> 
> It is being moved to the root deps directory in order to be used by the #3988 script

 okay, split into 2 patch is ok for me, thanks!

**Review by yanan-fu — APPROVED** [review]
Ack

**Comment by mcasquer** [comment]
@YongxueHong could you review again this PR? Thanks!

**Comment by mcasquer** [comment]
According to the @PaulYuuu comment in https://github.com/autotest/tp-qemu/pull/3988#discussion_r1546236850 I agree that it's feasible to store directly the C script file

**Comment by mcasquer** [comment]
@PaulYuuu @yanan-fu @YongxueHong could you review this PR again? Thanks!

**Comment by mcasquer** [comment]
> @PaulYuuu @yanan-fu @YongxueHong could you review this PR again? Thanks!

Keep in mind that difference with the last change has been only the file extraction, the C code is the same

**Review by yanan-fu — APPROVED** [review]
Ack

**Review by PaulYuuu — APPROVED** [review]

**Review by YongxueHong — APPROVED** [review]

**Comment by mcasquer** [comment]
It seems when doing the extraction I missed the v2 tool, updating again...

**Review by PaulYuuu — APPROVED** [review]

**Comment by mcasquer** [comment]
Could this patch be merged? Thanks !

**Comment by YongxueHong** [comment]
> Could this patch be merged? Thanks !

Hi @mcasquer 
Let's wait for other related patches to be approved since it will result in a regression error if we merge one, not merge them simultaneously.
Thanks for understanding.

**Pull request merged**
