### PR TITLE
rebase_onto_qcow2: add new case

### PR DESCRIPTION
**Pull request by lolyu**
id:1775528
add case to cover that rebase could change the backing file from
luks/raw to a new qcow2 image.

Signed-off-by: lolyu <lolyu@redhat.com>

### CODE REVIEW

**Comment by lolyu** [comment]
@hellohellenmao @YongxueHong please help to review, thanks.

**Comment by lolyu** [comment]
```
 (1/1) Host_RHEL.m8.u0.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.0.1.x86_64.io-github-autotest-qemu.rebase_onto_qcow2: PASS (269.04 s)
```

**Comment by lolyu** [comment]
```
 (1/1) Host_RHEL.m8.u0.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.rebase_onto_qcow2: PASS (896.79 s)
```

**Comment by hellohellenmao** [comment]
(1/1) Host_RHEL.m7.u8.luks.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.rebase_onto_qcow2: PASS (1182.84 s)

**Pull request merged**
