### PR TITLE
migration_with_remote_storage: support nbd

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1845749

### CODE REVIEW

**Comment by zhencliu** [comment]
(1/2) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.migration_with_remote_storage: PASS (226.48 s)
 (2/2) Host_RHEL.m8.u3.product_av.nbd.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.migration_with_remote_storage.with_post_copy: PASS (126.62 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-06-09T20.48-1a921b0/results.html

**Comment by zhencliu** [comment]
please be noticed that the image should be  shared access on the nbd server, e.g.
qemu-nbd -t --fork -e 3 -f raw /home/nbd/image

**Comment by zhencliu** [comment]
@XueqiangWei @YongxueHong Can you please help to review the case, thanks.

--testcase=migration_with_remote_storage

**Comment by zixi-chen** [comment]
(1/2) Host_RHEL.m8.u3.product_av.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.migration_with_remote_storage: PASS (159.74 s)
 (2/2) Host_RHEL.m8.u3.product_av.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.migration_with_remote_storage.with_post_copy: PASS (62.78 s)
 
LGTM
ACK

**Comment by zhencliu** [comment]
with latest vt patch
 (1/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.migration_with_remote_storage: PASS (302.79 s)
 (2/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.migration_with_remote_storage.with_post_copy: PASS (118.14 s)
 (3/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.remote_image_snapshot.to_local: PASS (208.71 s)
 (4/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_qcow2: PASS (144.16 s)
 (5/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_raw: PASS (147.89 s)
 (6/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_block.fmt_luks: PASS (173.43 s)
 (7/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_qcow2: PASS (169.89 s)
 (8/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_raw: PASS (158.17 s)
 (9/9) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_hotplug_with_remote_storage.with_scsi.fmt_luks: PASS (151.73 s)
RESULTS    : PASS 9 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by zhencliu** [comment]
(1/2) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.migration_with_remote_storage: PASS (291.02 s)
 (2/2) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.migration_with_remote_storage.with_post_copy: PASS (131.75 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

hi @YongxueHong , can you please help to merge it, thanks.

**Pull request merged**
