### PR TITLE
balloon_hotplug.cfg:change hotplug/unplug repeat time to 100

### PR DESCRIPTION
**Pull request by lijinlijin**
change balloon hotplug/unplug repeat time from 5 to 100

Signed-off-by: Li Jin <lijin@redhat.com>

ID:1479122

### CODE REVIEW

**Comment by CongLi** [comment]
Nack.

You have already implemented in internal.
balloon_hotplug:
    Windows:
        balloon_repeats = 100

**Comment by lijinlijin** [comment]
In the internal config file,it's only for windows.
Now both linux and windows need to run 100 times

**Comment by CongLi** [comment]
Ok, please help remove internal cfg later.

Thanks.

**Comment by CongLi** [comment]
Thanks @lijinlijin

**Pull request merged**
