### PR TITLE
Enable cpu hotplug test in ovmf

### PR DESCRIPTION
**Pull request by huangyum**
ID: 1847324
Signed-off-by: Yumei Huang <yuhuang@redhat.com>

### CODE REVIEW

**Comment by huangyum** [comment]
Test with ovmf would fail for now due to qemu bugs.

**Comment by huangyum** [comment]
@PaulYuuu Would you please help review, thanks.

**Comment by PaulYuuu** [comment]
@huangyum If the edk2 patch will not backport to early RHEL8 releases, I think we need to filter them out.

**Comment by huangyum** [comment]
@PaulYuuu Seems it will only support from 8.3, added the filter, pls review again, thanks.

**Comment by huangyum** [comment]
Close it since qemu is not supported yet, though ovmf package is ready.

**Pull request closed without merging**
