### PR TITLE
qemu.tests: Update migration_with_netperf.

### PR DESCRIPTION
**Pull request by FengYang**
Signed-off-by: Feng Yang <fyang@redhat.com>

### CODE REVIEW

**Comment by FengYang** [comment]
[root@dhcp-10-126 qemu]# ../../../../../../tools/scan_results.py 
Test                                                                                                             Status     Seconds  Info
----                                                                                                             ------     -------  ----
        (Result file: /usr/code/autotest/client/results/default/status)
virt.qemu.qcow2.virtio_blk.smp2.virtio_net.Win2012.x86_64.r2.io-github-autotest-qemu.migrate.with_netperf.tcp    GOOD       1173     completed successfully
----                                                                                                             GOOD       1180     
[root@dhcp-10-126 qemu]#

**Comment by FengYang** [comment]
ID: 1182001

**Comment by xiagao** [comment]
hi,fyang
why did you set host's password with redhat.Is 'kvmautotest' not right?
and i have run this case,it failed with host's password.

thanks,
xiagao

**Comment by yaxue** [comment]
LGTM
Acked-by: Yang Xue <yaxue@redhat.com>

**Comment by FengYang** [comment]
Thanks @yaxue

**Comment by xiagao** [comment]
Acked-by: Xiaoling Gao  xiagao@redhat.com

**Pull request merged**
