### PR TITLE
hotplug_memory: update sub-test name

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>

### CODE REVIEW

**Comment by XueqiangWei** [comment]
ID 1321539

**Comment by suqinhuang** [comment]
Acked-by: Suqin Huang

**Comment by mazhang** [comment]
Acked-by: Maosheng Zhang <mazhang@redhat.com>

**Comment by xutian** [comment]
Merged. thanks @XueqiangWei  @suqinhuang  and @mazhang

**Pull request merged**
