### PR TITLE
qemu.tests: Update param "guest_alias" in configurations.

### PR DESCRIPTION
**Pull request by CongLi**
1. Win2008r2 is missing of param "guest_alias".
2. Fix the error of Win2008 guest_name.
3. Add Win2016 guest.

Signed-off-by: Cong Li <coli@redhat.com>

id: 1397835

### CODE REVIEW

**Comment by suqinhuang** [comment]
could you pls add win2016 as well

**Comment by CongLi** [comment]
@suqinhuang 

Could you help review this PR?

Thanks.

**Comment by suqinhuang** [comment]
Ack

**Comment by CongLi** [comment]
Thanks @suqinhuang @yanan-fu .

**Pull request merged**
