### PR TITLE
qemu.tests: Add new case of live snapshot with stop_cont.

### PR DESCRIPTION
**Pull request by CongLi**
Signed-off-by: Cong Li <coli@redhat.com>

id: 1321838

### CODE REVIEW

**Comment by CongLi** [comment]
15:40:45 INFO | PASS 1-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u3.qcow2.virtio_blk.up.virtio_net.RHEL.7.3.x86_64.io-github-autotest-qemu.live_snapshot.with_stop_cont

**Comment by CongLi** [comment]
Close this PR, which will be implemented in #703 .

Thanks.

**Comment by CongLi** [comment]
@vivianQizhu 
Could you please help review this PR?

Many thanks. :)

**Comment by xutian** [comment]
test pass and looks ok to me.

**Comment by vivianQizhu** [comment]
LGTM, Acked-by: Qianqian Zhu qizhu@redhat.com

**Comment by xutian** [comment]
Merged, thanks @CongLi and @vivianQizhu .

**Pull request merged**
