### PR TITLE
qemu.tests: make migrate..with_netperf case more reasonable

### PR DESCRIPTION
**Pull request by xutian**
Response test owner's request to update netperf clinets numbers
to make test more reasonable.

ID: 993578

Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
13:40:57 INFO | 		GOOD	virt.qemu.smp_8.16384m.repeat1.run_test.Host_RHEL.7.2.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.migrate.with_netperf.tcp	virt.qemu.smp_8.16384m.repeat1.run_test.Host_RHEL.7.2.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.migrate.with_netperf.tcp	timestamp=1428903657	localtime=Apr 13 13:40:57	completed successfully
13:40:57 INFO | 	END GOOD	virt.qemu.smp_8.16384m.repeat1.run_test.Host_RHEL.7.2.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.migrate.with_netperf.tcp	virt.qemu.smp_8.16384m.repeat1.run_test.Host_RHEL.7.2.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.migrate.with_netperf.tcp	timestamp=1428903657	localtime=Apr 13 13:40:57

**Comment by ypu** [comment]
Hi @xutian others looks good to me. But the commit summary seems should be "make migrate..".

**Comment by CongSmile** [comment]
Hi @xutian 

Could you help update the commit log?

Others are fine for me.

Thanks.

**Comment by xutian** [comment]
@CongSmile 

Done thanks.

**Comment by CongSmile** [comment]
Acked-by: Cong Li <coli@redhat.com>

**Comment by xutian** [comment]
thanks 
@CongSmile  and @ypu

**Pull request merged**
