### PR TITLE
Update Suspend under netperf

### PR DESCRIPTION
**Pull request by FengYang**
ID: 1010788 1010789

### CODE REVIEW

**Comment by ypu** [comment]
@FengYang The patch looks good but have some conflict can you update it?

**Comment by FengYang** [comment]
Hi, @ypu  have update it. thanks

**Comment by FengYang** [comment]
Base on https://github.com/autotest/virt-test/pull/1953

**Comment by ypu** [comment]
LGTM

Acked-by:Yiqiao Pu <ypu@redhat.com>

**Comment by ypu** [comment]
Thanks @FengYang will merge it.

**Pull request merged**
