### PR TITLE
block_iscsi_lvm: Assign unattended delivery method explicitly

### PR DESCRIPTION
**Pull request by YongxueHong**
Assign unattended delivery method to cdrom explicitly in the
scenarios where unatteneded install guest OS form extra cdrom.

ID: 1838501
Signed-off-by: Yongxue Hong <yhong@redhat.com>

### CODE REVIEW

**Comment by YongxueHong** [comment]
Hi @qingwangrh  @menli820
Please help me to review it, thanks.

**Comment by menli820** [comment]
python3 ConfigTest.py --testcase=block_iscsi_lvm --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=Win2019 --driveformat=virtio_scsi --nicmodel=virtio_net --imageformat=luks --machines=q35 --customsparams="image_aio=native\ncd_format=ide" --clone=no 

 (1/2) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_iscsi_lvm.with_installation.cdrom.extra_cdrom_ks.with_scsi_hd.q35: PASS (1093.90 s)
 (2/2) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_iscsi_lvm.with_installation.cdrom.extra_cdrom_ks.with_scsi_block.q35: PASS (1020.27 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

Acked-by: Menghuan Li menli@redhat.com

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=block_iscsi_lvm.with_installation.cdrom.extra_cdrom_ks.with_scsi_hd --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=RHEL.8.3.0 --driveformat=virtio_scsi --nicmodel=virtio_net --imageformat=luks --machines=q35,i440fx --customsparams="image_aio=threads" --clone=no

(1/2) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_iscsi_lvm.with_installation.cdrom.extra_cdrom_ks.with_scsi_hd: ERROR: VM creation command failed:    "MALLOC_PERTURB_=1  /usr/libexec/qemu-kvm -S  -name 'avocado-vt-vm1'  -sandbox on  -machine pc  -nodefaults -device VGA,bus=pci.0,addr=0x2 -m 14336  -smp 12,maxcpus=12,cores=6,threads=1,dies=1,sockets=2  -cpu 'Opteron_G5',+k... (171.04 s)
 (2/2) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_iscsi_lvm.with_installation.cdrom.extra_cdrom_ks.with_scsi_hd.q35: PASS (1801.88 s)

It looks like have issue with data plane, not due to this issue.  i suggest set the cd_format to ide or disable data place under pc.
http://fileshare.englab.nay.redhat.com/pub/section2/images_backup/qbugs/code2302/2020-07-08-0002

**Comment by YongxueHong** [comment]
Hi @qingwangrh 
Have updated codes according your comments, please help me to reivew it again, thanks.

CC @zhenyzha 
Please help me to review it on power arch, thanks.

**Comment by zhenyzha** [comment]
python3 ConfigTest.py --testcase=block_iscsi_lvm.with_installation.cdrom.extra_cdrom_ks --iothread_scheme=roundrobin --nr_iothreads=2 --platform=ppc64le --guestname=RHEL.8.3.0 --driveformat=virtio_scsi --nicmodel=virtio_net --imageformat=luks --customsparams="image_aio=threads" --clone=no

 (1/2) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.block_iscsi_lvm.with_installation.cdrom.extra_cdrom_ks.with_scsi_hd: PASS (1171.28 s)
 (2/2) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.block_iscsi_lvm.with_installation.cdrom.extra_cdrom_ks.with_scsi_block: PASS (1196.32 s)

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=block_iscsi_lvm.with_installation.cdrom.extra_cdrom_ks.with_scsi_hd --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=RHEL.8.3.0,Win2019 --driveformat=virtio_scsi,virtio_blk --nicmodel=virtio_net --imageformat=luks --machines=q35,i440fx --customsparams="image_aio=threads" --clone=no

(1/4) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_iscsi_lvm.with_installation.cdrom.extra_cdrom_ks.with_scsi_hd: PASS (1393.11 s)
 (2/4) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.block_iscsi_lvm.with_installation.cdrom.extra_cdrom_ks.with_scsi_hd.q35: PASS (1099.01 s)
 (3/4) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_iscsi_lvm.with_installation.cdrom.extra_cdrom_ks.with_scsi_hd: PASS (1044.55 s)
 (4/4) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.block_iscsi_lvm.with_installation.cdrom.extra_cdrom_ks.with_scsi_hd.q35: PASS (933.76 s)


LGTM

**Comment by YongxueHong** [comment]
Thanks all.

**Pull request merged**
