### PR TITLE
IPU: adjust steps for getting rhsm pool id while doing IPU with rhsm

### PR DESCRIPTION
**Pull request by MiriamDeng**
ID:2180350
Signed-off-by: MiriamDeng <mdeng@redhat.com>

### CODE REVIEW

**Comment by MiriamDeng** [comment]
[stdlog] 2023-03-23 05:23:36,431 aexpect.client DEBUG| [10.73.210.200] Sending command: dnf install leapp-upgrade-el8toel9 -y
[stdlog] 2023-03-23 05:24:03,912 aexpect.client DEBUG| [10.73.210.200] Sending command: echo $?
[stdlog] 2023-03-23 05:24:04,013 aexpect.client DEBUG| [10.73.210.200] Sending command: curl -kLO https://gitlab.cee.redhat.com/leapp/oamg-rhel7-vagrant/raw/master/roles/init/files/prepare_test_env.sh
[stdlog] 2023-03-23 05:24:05,373 aexpect.client DEBUG| [10.73.210.200] Sending command: echo $?
[stdlog] 2023-03-23 05:24:05,475 aexpect.client DEBUG| [10.73.210.200] Sending command: source prepare_test_env.sh
[stdlog] 2023-03-23 05:24:05,579 aexpect.client DEBUG| [10.73.210.200] Sending command: echo $?
[stdlog] 2023-03-23 05:24:05,681 aexpect.client DEBUG| [10.73.210.200] Sending command: get_data_files
[stdlog] 2023-03-23 05:24:24,815 aexpect.client DEBUG| [10.73.210.200] Sending command: echo $?
...
[stdlog] 2023-03-23 05:24:48,242 aexpect.client DEBUG| [10.73.210.200] Sending command: rhsm_get_poolid RH00003
...

**Comment by MiriamDeng** [comment]
Please try RHEL8.6 guest (with RHSM) instead since the newer RHEL version is not available on server. Thank you !
Please help to review it, thank you !
@PaulYuuu @fbq815

**Review by PaulYuuu — DISMISSED** [review]

**Comment by fbq815** [comment]
I've tried on s390x, and seems our command for subscription is missing the pool id parameter:
[root@localhost ~]# subscription-manager attach --pool 
usage: subscription-manager attach [OPTIONS]
subscription-manager: error: argument --pool: expected one argument

**Comment by MiriamDeng** [comment]
> I've tried on s390x, and seems our command for subscription is missing the pool id parameter: [root@localhost ~]# subscription-manager attach --pool usage: subscription-manager attach [OPTIONS] subscription-manager: error: argument --pool: expected one argument

Add checkpoint if there's no revelant pool is avaible on CDN server. Please help to check it thanks.

**Comment by fbq815** [comment]
RHEL7-8：
with_rhsm:
JOB ID     : 8a59c824eee73384fccc7fa830a477765f470e60
JOB LOG    : /root/avocado/job-results/job-2023-07-04T03.51-8a59c82/job.log
 (1/1) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.in_place_upgrade_legacy.with_rhsm_rhel7_to_rhel8.compose_install.s390-virtio: STARTED
 (1/1) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.in_place_upgrade_legacy.with_rhsm_rhel7_to_rhel8.compose_install.s390-virtio: PASS (2086.22 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2023-07-04T03.51-8a59c82/results.html
JOB TIME   : 2087.46 s

**Review by fbq815 — APPROVED** [review]

**Comment by MiriamDeng** [comment]
@PaulYuuu can we help to check if we can merge this pr ? Thank you !

**Review by PaulYuuu — APPROVED** [review]

**Pull request merged**
