### PR TITLE
Make background stress work in balloon test

### PR DESCRIPTION
**Pull request by suqinhuang**
update the video play params

Signed-off-by: Suqin Huang <shuang@redhat.com>

id: 1427014

### CODE REVIEW

**Comment by suqinhuang** [comment]
PASS 1-smp_1.4096m.repeat1.run_test.Host_RHEL.m7.u4.qcow2.virtio_blk.up.virtio_net.Win7.x86_64.sp1.io-github-autotest-qemu.balloon_in_use.with_live_migration.during_bg_test

**Comment by CongLi** [comment]
@lijinlijin 

Could you please help assign the review later?

**Comment by kimi1978wy** [comment]
@suqinhuang does this patch depend on any other patch? I cannot run it pass when only apply this patch.

**Comment by kimi1978wy** [comment]
After applying #924 and #983, this case can pass. 
But I find that , the migration occurred after "stop the video" , and the video start again after migration complete. 

**10:34:35 INFO | Stop background video**
10:34:35 DEBUG| Sending command: taskkill /IM wmplayer.exe /F
10:34:35 DEBUG| Sending command: echo %errorlevel%
10:34:40 DEBUG| Attempting to log into 'avocado-vt-vm1' (timeout 800s)
10:34:40 DEBUG| Found/Verified IP 10.66.8.170 for VM avocado-vt-vm1 NIC 0
10:34:40 INFO | Context: Checking the background command in the guest pre migration
**10:34:44 INFO | Migrating to tcp:localhost:5200**
10:34:44 DEBUG| (monitor avocado-vt-vm1.qmpmonitor1) Sending command 'migrate'
10:34:44 DEBUG| Send command: {'execute': 'migrate', 'arguments': {'uri': 'tcp:localhost:5200', 'blk': False, 'inc': False}, 'id': 'LuHdUGRQ'}

**Comment by suqinhuang** [comment]
@kimi1978wy which test did run, before, during or after

**Comment by kimi1978wy** [comment]
@suqinhuang  I ran during bg test. After discuss with lijin, we need bg_test during the whole migration process(till migrate to dst guest ). bg_test can be only evict/enlarge memory, playing video is not a must for this case.

**Comment by suqinhuang** [comment]
https://github.com/autotest/tp-qemu/pull/1024

**Comment by suqinhuang** [comment]
close this patch, trace with patch 1024

**Pull request closed without merging**
