### PR TITLE
qemu.tests: Add virtio serial unplug test case and script.

### PR DESCRIPTION
**Pull request by xutian**
This  PR is new version for origin PR https://github.com/autotest/tp-qemu/pull/274

Signed-off-by: Feng Yang <fyang@redhat.com>
Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
ID: 1157455 1157384

**Comment by xutian** [comment]
@CongSmile  and  @XueqiangWei would you like to review this case .

**Comment by xutian** [comment]
deps on PR https://github.com/autotest/virt-test/pull/2216

**Comment by PyLearner** [comment]
virt.qemu.smp_8.4096m.repeat1.run_test.Host_RHEL.7.2.qcow2.virtio_blk.up.virtio_net.RHEL.7.1.x86_64.io-github-autotest-qemu.virtio_serial_hotunplug.unplug_chardev    FAIL       60       Unhandled QMPCmdError: QMP command u'chardev-remove' failed    (arguments: {u'id': u'devvc1'},    error message: {u'class': u'GenericError', u'desc': u"Chardev 'devvc1' is busy"})    [context: Hot unplug device vc1]
virt.qemu.smp_8.4096m.repeat1.run_test.Host_RHEL.7.2.qcow2.virtio_blk.up.virtio_net.RHEL.7.1.x86_64.io-github-autotest-qemu.virtio_serial_hotunplug.unplug_serial     FAIL       194      Unhandled VMConfigMissingError: Missing config 'isa_serial' for VM virt-tests-vm1    [context: Running sub test 'migration' after hotunplug --> Checking the background command in the guest pre migration --> migrating 'virt-tests-vm1' --> creating destination VM --> creating 'virt-tests-vm1']

**Comment by PyLearner** [comment]
review failed 

virt.qemu.smp_8.4096m.repeat1.run_test.Host_RHEL.7.2.qcow2.virtio_blk.up.virtio_net.RHEL.7.1.x86_64.io-github-autotest-qemu.virtio_serial_hotunplug.unplug_chardev    FAIL       60       Unhandled QMPCmdError: QMP command u'chardev-remove' failed    (arguments: {u'id': u'devvc1'},    error message: {u'class': u'GenericError', u'desc': u"Chardev 'devvc1' is busy"})    [context: Hot unplug device vc1]



virt.qemu.smp_8.4096m.repeat1.run_test.Host_RHEL.7.2.qcow2.virtio_blk.up.virtio_net.RHEL.7.1.x86_64.io-github-autotest-qemu.virtio_serial_hotunplug.unplug_serial     FAIL       194      Unhandled VMConfigMissingError: Missing config 'isa_serial' for VM virt-tests-vm1    [context: Running sub test 'migration' after hotunplug --> Checking the background command in the guest pre migration --> migrating 'virt-tests-vm1' --> creating destination VM --> creating 'virt-tests-vm1']

**Comment by vipmike007** [comment]
I hit the same issue

**Comment by vipmike007** [comment]
And another one :
Traceback (most recent call last):
  File "/home/test10/autotest-devel/client/shared/test.py", line 411, in _exec
    _call_test_function(self.execute, *p_args, **p_dargs)
  File "/home/test10/autotest-devel/client/shared/test.py", line 830, in _call_test_function
    raise error.UnhandledTestFail(e)
UnhandledTestFail: Unhandled VMMigrateFailedError: Migration failed    [context: Running sub test 'migration' after hotunplug --> Checking the background command in the guest pre migration --> migrating 'virt-tests-vm1']
Traceback (most recent call last):
  File "/home/test10/autotest-devel/client/shared/test.py", line 823, in _call_test_function
    return func(*args, **dargs)
  File "/home/test10/autotest-devel/client/shared/test.py", line 291, in execute
    postprocess_profiled_run, args, dargs)
  File "/home/test10/autotest-devel/client/shared/test.py", line 209, in _call_run_once
    *args, **dargs)
  File "/home/test10/autotest-devel/client/shared/test.py", line 313, in run_once_profiling
    self.run_once(*args, **dargs)
  File "/home/test10/autotest-devel/client/tests/virt/virt.py", line 155, in run_once
    run_func(self, params, env)
  File "/home/test10/autotest-devel/client/shared/error.py", line 141, in new_fn
    return fn(*args, **kwargs)
  File "/home/test10/autotest-devel/client/tests/virt/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/virtio_serial_hotunplug.py", line 109, in run
    utils_test.run_virt_sub_test(test, params, env, sub_type, sub_type_tag)
  File "/home/test10/autotest-devel/client/tests/virt/virttest/utils_test/__init__.py", line 1298, in run_virt_sub_test
    run_func(test, params, env)
  File "/home/test10/autotest-devel/client/shared/error.py", line 141, in new_fn
    return fn(*args, **kwargs)
  File "/home/test10/autotest-devel/client/tests/virt/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/migration.py", line 209, in run
    migration_exec_cmd_dst=mig_exec_cmd_dst, env=env)
  File "/home/test10/autotest-devel/client/shared/error.py", line 141, in new_fn
    return fn(*args, **kwargs)
  File "/home/test10/autotest-devel/client/tests/virt/virttest/qemu_vm.py", line 3586, in migrate
    raise virt_vm.VMMigrateFailedError("Migration failed")
VMMigrateFailedError: Migration failed

**Comment by xutian** [comment]
@PyLearner and @vipmike007   Deivces  is busy? please check is that's bug of product.

**Comment by suqinhuang** [comment]
@xutian ,
https://github.com/autotest/virt-test/pull/2216 is closed, could you re-send it.

Thanks
Suqin

**Pull request closed without merging**
