### PR TITLE
[WIP]virtio_storage_in_use: Add a argument join_timeout for thread

### PR DESCRIPTION
**Pull request by YongxueHong**
virtio_storage_in_use: Add a argument join_timeout for thread    
    Add an argument join_timeout for the cases related during_bg_test that
    starts a thread under background.

 driver_in_use: Update the way of getting argument timeout of thread
    To avoid sharing the login_timeout, add an extra available argument
    timeout of thread.

ID: 1719111

Signed-off-by: Yongxue Hong yhong@redhat.com

### CODE REVIEW

**Comment by YongxueHong** [comment]
@CongLi  @XueqiangWei @peixiu @kimi1978wy  help me review this patch, thanks.

**Comment by CongLi** [comment]
@ngu-niny could you please help review it in power side?

Thanks.

**Comment by XueqiangWei** [comment]
LGTM,
Acked-by xuwei@redhat.com

**Comment by hereischen** [comment]
Acked-by: Haotong Chen hachen@redhat.com

**Comment by peixiu** [comment]
Tested job virtio_storage_in_use.with_vioscsi.system_disk.with_system_reset.during_bg_test 10 times on win2019 guest, all passed.

Acked-by: Peixiu Hou phou@redhat.com

**Comment by kimi1978wy** [comment]
Tested "virtio_storage_in_use.with_block.system_disk.with_system_reset.during_bg_test" 10 times on win2012r2  guest, all passed.

 (01/10) repeat1.Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2012.x86_64.r2.io-github-autotest-qemu.virtio_storage_in_use.with_block.system_disk.with_system_reset.during_bg_test.q35: PASS (174.00 s)
 (02/10) repeat2.Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2012.x86_64.r2.io-github-autotest-qemu.virtio_storage_in_use.with_block.system_disk.with_system_reset.during_bg_test.q35: PASS (136.91 s)
 (03/10) repeat3.Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2012.x86_64.r2.io-github-autotest-qemu.virtio_storage_in_use.with_block.system_disk.with_system_reset.during_bg_test.q35: PASS (140.14 s)
 (04/10) repeat4.Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2012.x86_64.r2.io-github-autotest-qemu.virtio_storage_in_use.with_block.system_disk.with_system_reset.during_bg_test.q35: PASS (132.75 s)
 (05/10) repeat5.Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2012.x86_64.r2.io-github-autotest-qemu.virtio_storage_in_use.with_block.system_disk.with_system_reset.during_bg_test.q35: PASS (128.72 s)
 (06/10) repeat6.Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2012.x86_64.r2.io-github-autotest-qemu.virtio_storage_in_use.with_block.system_disk.with_system_reset.during_bg_test.q35: PASS (130.35 s)
 (07/10) repeat7.Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2012.x86_64.r2.io-github-autotest-qemu.virtio_storage_in_use.with_block.system_disk.with_system_reset.during_bg_test.q35: PASS (136.30 s)
 (08/10) repeat8.Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2012.x86_64.r2.io-github-autotest-qemu.virtio_storage_in_use.with_block.system_disk.with_system_reset.during_bg_test.q35: PASS (130.14 s)
 (09/10) repeat9.Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2012.x86_64.r2.io-github-autotest-qemu.virtio_storage_in_use.with_block.system_disk.with_system_reset.during_bg_test.q35: PASS (133.10 s)
 (10/10) repeat10.Host_RHEL.m8.u0.qcow2.virtio_blk.up.virtio_net.Guest.Win2012.x86_64.r2.io-github-autotest-qemu.virtio_storage_in_use.with_block.system_disk.with_system_reset.during_bg_test.q35: PASS (132.08 s)

Acked-by: Yu Wang <wyu@redhat.com>

**Comment by zhenyzha** [comment]
Tested "virtio_storage_in_use.with_vioscsi.system_disk.with_system_reset.during_bg_test" 10 times on RHEL.7.7 guest, all passed.

 04:05:15 DEBUG|     join_timeout = 30

(01/12) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.extra_c
drom_ks.default_install.aio_threads: PASS (2289.80 s)
 (02/12) Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.ppc64le.io-github-autotest-qemu.rh_kernel_update: PASS (289.56 s
)
 (03/12) repeat1.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.ppc64le.io-github-autotest-qemu.virtio_storage_in_use.wi
th_vioscsi.system_disk.with_system_reset.during_bg_test: PASS (379.66 s)
 (04/12) repeat2.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.ppc64le.io-github-autotest-qemu.virtio_storage_in_use.wi
th_vioscsi.system_disk.with_system_reset.during_bg_test: PASS (344.24 s)
 (05/12) repeat3.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.ppc64le.io-github-autotest-qemu.virtio_storage_in_use.wi
th_vioscsi.system_disk.with_system_reset.during_bg_test: PASS (345.74 s)
 (06/12) repeat4.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.ppc64le.io-github-autotest-qemu.virtio_storage_in_use.wi
th_vioscsi.system_disk.with_system_reset.during_bg_test: PASS (346.76 s)
 (07/12) repeat5.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.ppc64le.io-github-autotest-qemu.virtio_storage_in_use.wi
th_vioscsi.system_disk.with_system_reset.during_bg_test: PASS (340.14 s)
 (08/12) repeat6.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.ppc64le.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.system_disk.with_system_reset.during_bg_test: PASS (346.10 s)
 (09/12) repeat7.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.ppc64le.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.system_disk.with_system_reset.during_bg_test: PASS (355.34 s)
 (10/12) repeat8.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.ppc64le.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.system_disk.with_system_reset.during_bg_test: PASS (356.29 s)
 (11/12) repeat9.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.ppc64le.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.system_disk.with_system_reset.during_bg_test: PASS (356.55 s)
 (12/12) repeat10.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.ppc64le.io-github-autotest-qemu.virtio_storage_in_use.with_vioscsi.system_disk.with_system_reset.during_bg_test: PASS (375.23 s)

Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Comment by CongLi** [comment]
Update my comment:

As we talked, I did not get the point of the fix, please provide enough reason for it.

Thank you.

**Pull request closed without merging**
