### PR TITLE
IPU:Fix the issue of yum update by following known document

### PR DESCRIPTION
**Pull request by MiriamDeng**
ID:2209619

Signed-off-by: Min Deng <mdeng@redhat.com>

### CODE REVIEW

**Comment by MiriamDeng** [comment]
@PaulYuuu @fbq815 could you help to review this patch ? Thanks.

**Comment by MiriamDeng** [comment]
Test log
 (1/1) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.x86_64.io-github-autotest-qemu.in_place_upgrade_legacy.with_rhsm_rhel7_to_rhel8.compose_install.q35: STARTED
 (1/1) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.x86_64.io-github-autotest-qemu.in_place_upgrade_legacy.with_rhsm_rhel7_to_rhel8.compose_install.q35: PASS (5654.21 s)

**Comment by MiriamDeng** [comment]
As I discussed it with bfu, I will help to provide S390x's test result for this patch, it passed
 (1/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.s390-virtio: STARTED
 (1/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.s390-virtio: PASS (538.09 s)
 (2/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.in_place_upgrade_legacy.without_rhsm_rhel7_to_rhel8.compose_install.s390-virtio: STARTED
 (2/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.in_place_upgrade_legacy.without_rhsm_rhel7_to_rhel8.compose_install.s390-virtio: PASS (1357.00 s)

**Comment by fbq815** [comment]
> As I discussed it with bfu, I will help to provide S390x's test result for this patch, it passed (1/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.s390-virtio: STARTED (1/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.s390-virtio: PASS (538.09 s) (2/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.in_place_upgrade_legacy.without_rhsm_rhel7_to_rhel8.compose_install.s390-virtio: STARTED (2/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.s390x.io-github-autotest-qemu.in_place_upgrade_legacy.without_rhsm_rhel7_to_rhel8.compose_install.s390-virtio: PASS (1357.00 s)

thanks min's help trigger this test

**Review by PaulYuuu — APPROVED** [review]

**Pull request merged**
