### PR TITLE
Add capability for watchdog since -watchdog is deprecated

### PR DESCRIPTION
**Pull request by fbq815**
Watchdog: switch -watchdog to -device since -watchdog is deprecated.

ID: 2155430

Signed-off-by: Boqiao Fu <bfu@redhat.com>

### CODE REVIEW

**Comment by fbq815** [comment]
Test result:
JOB ID     : 0e68c93d9a990c94d02316ae9f6e24847db61d80
JOB LOG    : /root/avocado/job-results/job-2022-12-21T05.32-0e68c93/job.log
 (01/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.s390x.io-github-autotest-qemu.watchdog.boot_with_watchdog.diag288.s390-virtio: STARTED
 (01/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.s390x.io-github-autotest-qemu.watchdog.boot_with_watchdog.diag288.s390-virtio: PASS (24.43 s)
 (02/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.s390x.io-github-autotest-qemu.watchdog.magic_close.diag288.s390-virtio: STARTED
 (02/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.s390x.io-github-autotest-qemu.watchdog.magic_close.diag288.s390-virtio: PASS (264.29 s)
 (03/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.reboot_guest.diag288.s390-virtio: STARTED
 (03/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.reboot_guest.diag288.s390-virtio: PASS (65.88 s)
 (04/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.shutdown_guest.diag288.s390-virtio: STARTED
 (04/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.shutdown_guest.diag288.s390-virtio: PASS (57.14 s)
 (05/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.pause_guest.diag288.s390-virtio: STARTED
 (05/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.pause_guest.diag288.s390-virtio: PASS (80.83 s)
 (06/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.noaction.diag288.s390-virtio: STARTED
 (06/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.noaction.diag288.s390-virtio: PASS (268.98 s)
 (07/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.debug.diag288.s390-virtio: STARTED
^C (07/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.debug.diag288.s390-virtio: PASS (270.26 s)
 (08/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.poweroff.diag288.s390-virtio: STARTED
 (08/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.7.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.poweroff.diag288.s390-virtio: PASS (55.08 s)
 (09/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.s390x.io-github-autotest-qemu.watchdog.boot_with_watchdog.diag288.s390-virtio: STARTED
 (09/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.s390x.io-github-autotest-qemu.watchdog.boot_with_watchdog.diag288.s390-virtio: PASS (20.45 s)
 (10/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.s390x.io-github-autotest-qemu.watchdog.magic_close.diag288.s390-virtio: STARTED
 (10/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.s390x.io-github-autotest-qemu.watchdog.magic_close.diag288.s390-virtio: PASS (264.17 s)
 (11/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.reboot_guest.diag288.s390-virtio: STARTED
 (11/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.reboot_guest.diag288.s390-virtio: PASS (65.08 s)
 (12/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.shutdown_guest.diag288.s390-virtio: STARTED
 (12/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.shutdown_guest.diag288.s390-virtio: PASS (55.02 s)
 (13/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.pause_guest.diag288.s390-virtio: STARTED
 (13/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.pause_guest.diag288.s390-virtio: PASS (80.71 s)
 (14/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.noaction.diag288.s390-virtio: STARTED
 (14/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.noaction.diag288.s390-virtio: PASS (270.09 s)
 (15/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.debug.diag288.s390-virtio: STARTED
 (15/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.debug.diag288.s390-virtio: PASS (269.09 s)
 (16/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.poweroff.diag288.s390-virtio: STARTED
 (16/16) Host_RHEL.m9.u2.v0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.2.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.poweroff.diag288.s390-virtio: PASS (54.75 s)
RESULTS    : PASS 16 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2022-12-21T05.32-0e68c93/results.html
JOB TIME   : 2175.81 s

@PaulYuuu please help me review and merge this patch
I only involve you because this will only infulence s390x

**Comment by yanan-fu** [comment]
@fbq815  This is not a s390x only issue,  x86 have the same problem. 
I think the default value for `watchdog_type_check` need be updated for different qemu version:
https://github.com/autotest/tp-qemu/blob/0352bc1d1111dec72739db4b8ec84c76622768ee/qemu/tests/watchdog.py#L171

cc @yiqianwei

**Comment by yiqianwei** [comment]
> @fbq815 This is not a s390x only issue, x86 have the same problem. I think the default value for `watchdog_type_check` need be updated for different qemu version:
> 
> https://github.com/autotest/tp-qemu/blob/0352bc1d1111dec72739db4b8ec84c76622768ee/qemu/tests/watchdog.py#L171
> 
> cc @yiqianwei

@yanan-fu and @fbq815 
Use the "/usr/libexec/qemu kvm -device ?" command to check that the host qemu-kvm supports watchdog device.
Modify the Watchdog.py file as follows:
        watchdog_type_check = params.get(
            "watchdog_type_check", " -device '?'")

**Comment by fbq815** [comment]
RHEL.9.0.0
JOB ID     : 2791793afc6e56509f4678e4473ff0cf4cf9fe14
JOB LOG    : /root/avocado/job-results/job-2023-01-12T22.26-2791793/job.log
 (01/10) Host_RHEL.m9.u0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.unattended_install.url.extra_cdrom_ks.default_install.aio_threads.s390-virtio: STARTED
 (01/10) Host_RHEL.m9.u0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.unattended_install.url.extra_cdrom_ks.default_install.aio_threads.s390-virtio: FAIL: Timeout elapsed while waiting for install to finish (5120.20 s)
 (02/10) Host_RHEL.m9.u0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.s390-virtio: STARTED
 (02/10) Host_RHEL.m9.u0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.s390-virtio: PASS (1057.16 s)
 (03/10) Host_RHEL.m9.u0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.watchdog.boot_with_watchdog.diag288.s390-virtio: STARTED
 (03/10) Host_RHEL.m9.u0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.watchdog.boot_with_watchdog.diag288.s390-virtio: PASS (21.85 s)
 (04/10) Host_RHEL.m9.u0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.watchdog.magic_close.diag288.s390-virtio: STARTED
 (04/10) Host_RHEL.m9.u0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.watchdog.magic_close.diag288.s390-virtio: PASS (261.63 s)
 (05/10) Host_RHEL.m9.u0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.reboot_guest.diag288.s390-virtio: STARTED
 (05/10) Host_RHEL.m9.u0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.reboot_guest.diag288.s390-virtio: PASS (62.48 s)
 (06/10) Host_RHEL.m9.u0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.shutdown_guest.diag288.s390-virtio: STARTED
 (06/10) Host_RHEL.m9.u0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.shutdown_guest.diag288.s390-virtio: PASS (52.36 s)
 (07/10) Host_RHEL.m9.u0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.pause_guest.diag288.s390-virtio: STARTED
 (07/10) Host_RHEL.m9.u0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.pause_guest.diag288.s390-virtio: PASS (78.14 s)
 (08/10) Host_RHEL.m9.u0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.noaction.diag288.s390-virtio: STARTED
 (08/10) Host_RHEL.m9.u0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.noaction.diag288.s390-virtio: PASS (266.34 s)
 (09/10) Host_RHEL.m9.u0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.debug.diag288.s390-virtio: STARTED
 (09/10) Host_RHEL.m9.u0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.debug.diag288.s390-virtio: PASS (266.65 s)
 (10/10) Host_RHEL.m9.u0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.poweroff.diag288.s390-virtio: STARTED
 (10/10) Host_RHEL.m9.u0.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.poweroff.diag288.s390-virtio: PASS (52.01 s)
RESULTS    : PASS 9 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2023-01-12T22.26-2791793/results.html
JOB TIME   : 7244.76 s

RHEL.8.8.0:
JOB ID     : 0d4a9a967fa104ecaeb47540258a7eda6e9f6175
JOB LOG    : /root/avocado/job-results/job-2023-01-12T22.59-0d4a9a9/job.log
 (01/10) Host_RHEL.m8.u8.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.s390x.io-github-autotest-qemu.unattended_install.url.extra_cdrom_ks.default_install.aio_threads.s390-virtio: STARTED
 (01/10) Host_RHEL.m8.u8.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.s390x.io-github-autotest-qemu.unattended_install.url.extra_cdrom_ks.default_install.aio_threads.s390-virtio: ERROR: VM creation command failed:    'MALLOC_PERTURB_=1  /usr/libexec/qemu-kvm -S  -name \'avocado-vt-vm1\'  -sandbox on  -machine s390-ccw-virtio,memory-backend=mem-machine_mem  -nodefaults  -vga none -m 4096 -object memory-backend-ram,size=4096M,id=mem-machin... (7.78 s)
 (02/10) Host_RHEL.m8.u8.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.s390x.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.s390-virtio: STARTED
 (02/10) Host_RHEL.m8.u8.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.s390x.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.s390-virtio: PASS (594.31 s)
 (03/10) Host_RHEL.m8.u8.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.s390x.io-github-autotest-qemu.watchdog.boot_with_watchdog.diag288.s390-virtio: STARTED
 (03/10) Host_RHEL.m8.u8.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.s390x.io-github-autotest-qemu.watchdog.boot_with_watchdog.diag288.s390-virtio: PASS (32.78 s)
 (04/10) Host_RHEL.m8.u8.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.s390x.io-github-autotest-qemu.watchdog.magic_close.diag288.s390-virtio: STARTED
 (04/10) Host_RHEL.m8.u8.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.s390x.io-github-autotest-qemu.watchdog.magic_close.diag288.s390-virtio: PASS (265.25 s)
 (05/10) Host_RHEL.m8.u8.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.reboot_guest.diag288.s390-virtio: STARTED
 (05/10) Host_RHEL.m8.u8.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.reboot_guest.diag288.s390-virtio: PASS (66.51 s)
 (06/10) Host_RHEL.m8.u8.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.shutdown_guest.diag288.s390-virtio: STARTED
 (06/10) Host_RHEL.m8.u8.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.shutdown_guest.diag288.s390-virtio: PASS (54.99 s)
 (07/10) Host_RHEL.m8.u8.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.pause_guest.diag288.s390-virtio: STARTED
 (07/10) Host_RHEL.m8.u8.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.pause_guest.diag288.s390-virtio: PASS (80.79 s)
 (08/10) Host_RHEL.m8.u8.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.noaction.diag288.s390-virtio: STARTED
 (08/10) Host_RHEL.m8.u8.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.noaction.diag288.s390-virtio: PASS (270.16 s)
 (09/10) Host_RHEL.m8.u8.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.debug.diag288.s390-virtio: STARTED
 (09/10) Host_RHEL.m8.u8.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.debug.diag288.s390-virtio: PASS (270.64 s)
 (10/10) Host_RHEL.m8.u8.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.poweroff.diag288.s390-virtio: STARTED
 (10/10) Host_RHEL.m8.u8.product_rhel.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.s390x.io-github-autotest-qemu.watchdog.watchdog_action.poweroff.diag288.s390-virtio: PASS (54.52 s)
RESULTS    : PASS 9 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2023-01-12T22.59-0d4a9a9/results.html
JOB TIME   : 1705.48 s

**Comment by yanan-fu** [comment]
@fbq815  It is QEMU 7.2 that `- watchdog` be deprecated. Could you double confirm from when  `-device ` be involved ?   We need make it work for all.

**Comment by yanan-fu** [comment]
> @fbq815 It is QEMU 7.2 that `- watchdog` be deprecated. Could you double confirm when was `-device ` involved ? We need make it work for all of the supported version.

**Comment by fbq815** [comment]
> > @fbq815 It is QEMU 7.2 that `- watchdog` be deprecated. Could you double confirm when was `-device ` involved ? We need make it work for all of the supported version.

double check and I 've sync with developers, at least from s390x side, we could use -device all the time
checked with qemu 6.2 and qemu 7.0 that "-device" is able to use

**Comment by yanan-fu** [comment]
> double check and I 've sync with developers, at least from s390x side, we could use -device all the time checked with qemu 6.2 and qemu 7.0 that "-device" is able to use

What do you mean `all the time`, can you share the specific version ?  This kind of change is not arch specific. Generally speaking, we need check it from QEMU 2.1 at least (RHEL 8.1).  
I am not very clear about when we start testing s390x, we can also check it from x86 side,  @yiqianwei could you help with this ?  Thanks!

**Comment by yiqianwei** [comment]
> > double check and I 've sync with developers, at least from s390x side, we could use -device all the time checked with qemu 6.2 and qemu 7.0 that "-device" is able to use
> 
> What do you mean `all the time`, can you share the specific version ? This kind of change is not arch specific. Generally speaking, we need check it from QEMU 2.1 at least (RHEL 8.1). I am not very clear about when we start testing s390x, we can also check it from x86 side, @yiqianwei could you help with this ? Thanks!

@yanan-fu , With qemu-kvm-2.12.0-64.module+el8.0.0.z+3418+a72cf898.2.x86_64 version, already used  '-device' 
# /usr/libexec/qemu-kvm -device i6300esb
VNC server running on ::1:5900

**Comment by fbq815** [comment]
> > double check and I 've sync with developers, at least from s390x side, we could use -device all the time checked with qemu 6.2 and qemu 7.0 that "-device" is able to use
> 
> What do you mean `all the time`, can you share the specific version ? This kind of change is not arch specific. Generally speaking, we need check it from QEMU 2.1 at least (RHEL 8.1). I am not very clear about when we start testing s390x, we can also check it from x86 side, @yiqianwei could you help with this ? Thanks!

I think it's ok if we use "device" to substitute "watchdog
[root@s390x-kvm-011 ~]# rpm -qa | grep qemu
qemu-kvm-2.12.0-63.module+el8+2833+c7d6d092.s390x
[root@s390x-kvm-011 ~]# /usr/libexec/qemu-kvm -device ?
Misc devices:
name "diag288"

**Comment by yanan-fu** [comment]
I also confirmed with qemu 2.12 with x86 side,  device `i6300esb` and `ib700` are there with `-device ?`.   So this change is safe i think.

Ack

**Review by yanan-fu — APPROVED** [review]

**Comment by yanan-fu** [comment]
@fbq815 Could you please update the commit title ?  It is not s390x only issue now. Thanks!

**Comment by fbq815** [comment]
> @fbq815 Could you please update the commit title ? It is not s390x only issue now. Thanks!

Updated, could you please help me merge this commit?

**Comment by yanan-fu** [comment]
> > @fbq815 Could you please update the commit title ? It is not s390x only issue now. Thanks!
> 
> Updated, could you please help me merge this commit?

I see the commit title has not been updated, could you double confirm ? Thanks!

**Comment by fbq815** [comment]
> > > @fbq815 Could you please update the commit title ? It is not s390x only issue now. Thanks!
> > 
> > 
> > Updated, could you please help me merge this commit?
> 
> I see the commit title has not been updated, could you double confirm ? Thanks!

Updated

**Review by yanan-fu — APPROVED** [review]

**Review by PaulYuuu — APPROVED** [review]

**Comment by yiqianwei** [comment]
ACK

**Comment by PaulYuuu** [comment]
Thanks all, let's merge it.

**Pull request merged**
