### PR TITLE
blockdev_inc_backup_always:Do incremental live backup with bitmap-mode:always

### PR DESCRIPTION
**Pull request by aliang123**
Do incremental live backup with bitmap-mode:always

Signed-off-by: Aihua Liang <aliang@redhat.com>
id:1983911

### CODE REVIEW

**Comment by aliang123** [comment]
depends on https://github.com/autotest/tp-qemu/pull/2919

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_always.q35: PASS (42.94 s)

**Comment by aliang123** [comment]
@zhencliu @ngu-niny, please help to review, thanks

**Comment by aliang123** [comment]
@zhencliu @ngu-niny, please help to review, thanks

**Comment by zhencliu** [comment]
hi @aliang123 , it might not be good to use a same py file with two diff cfgs, for
1. the py name is blockdev_inc_backup_never, it's hard to tell that py file is the auto script for blockdev_inc_backup_always test case.
2. the test steps in blockdev_inc_backup_never only describes the 'never' mode
So, 
1. you can rename blockdev_inc_backup_never to other name, e.g. blockdev_inc_backup_bm_mode_neg, and modify the test steps to add bitmap mode 'always', or
2. you can copy a new py file blockdev_inc_backup_bm_mode_always, which is used for this patch

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.blockdev_inc_backup_always.q35: PASS (43.54 s)

**Comment by zhencliu** [comment]
LGTM

**Comment by ngu-niny** [comment]
02-Host_RHEL.m8.u5.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_always Finshed 2021-07-23 09:18:05 2021-07-23 09:19:37 PASS 91.790424

05-Host_RHEL.m8.u5.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_always Finshed 2021-07-23 09:23:16 2021-07-23 09:25:37 PASS 140.871039

08-Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_always Finshed 2021-07-23 09:29:23 2021-07-23 09:31:23 PASS 119.733968

11-Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.ppc64le.io-github-autotest-qemu.blockdev_inc_backup_always Finshed 2021-07-23 09:35:19 2021-07-23 09:37:40 PASS 141.498402

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
