### PR TITLE
blockdev_stream_vm_stop_cont: add stream test with vm stop/cont

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1881753

### CODE REVIEW

**Comment by zhencliu** [comment]
local fs:
 (3/3) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_stop_cont: PASS (161.29 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-23T02.59-0110a54/results.html
JOB TIME   : 2082.75 s

nbd:
(1/1) Host_RHEL.m8.u3.product_av.nbd.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_stop_cont: PASS (237.55 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-23T04.04-137abb6/results.html
JOB TIME   : 245.07 s

gluster direct:
 (1/1) Host_RHEL.m8.u3.product_av.gluster_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.1.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_stop_cont: PASS (210.31 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2020-09-23T16.05-62e018a/results.html
JOB TIME   : 213.66 s

iscsi direct:
 (1/1) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_stop_cont: PASS (158.28 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-23T04.14-543590b/results.html
JOB TIME   : 163.86 s

hi @aliang123 @YongxueHong , can you please help to review the patch, thanks.
btw: this one deps on #2418 , so please ignore the ci check failure

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_stop_cont.q35: PASS (274.53 s)

Acked-by: Aihua Liang <aliang@redhat.com>

**Comment by zhencliu** [comment]
hi @ngu-niny , can you please help to review this patch? Thanks.
btw: it deps on #2418 
also, confirmed with Aihua, we don't need to cover a long chain like polarion case, just data->data_snap is OK, fyi.

**Comment by zhencliu** [comment]
(1/3) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_stress: PASS (317.09 s)
(2/3) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_stop_cont: PASS (291.66 s)
(3/3) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_reboot: PASS (304.83 s)
RESULTS : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML : /home/kar/workspace/job-results/job-2020-09-27T20.47-c1ce6a6/results.html
JOB TIME : 919.88 s

hi @ngu-niny , code updated, can you please help make a double check? Thanks.

**Comment by zhencliu** [comment]
(1/3) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_reboot: PASS (766.92 s)
 (2/3) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_stop_cont: PASS (722.71 s)
 (3/3) Host_RHEL.m8.u3.product_av.iscsi_direct.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_stress: PASS (738.47 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2020-09-27T22.07-87dc65a/results.html
JOB TIME   : 2234.10 s

**Comment by aliang123** [comment]
(1/1) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.blockdev_stream_vm_stop_cont.q35: PASS (618.82 s)

acked for test run on system disk.

**Review by YongxueHong — APPROVED** [review]
LGTM

**Comment by ngu-niny** [comment]
LGTM.

Acked-by: Nini Gu ngu@redhat.com

**Pull request merged**
