### PR TITLE
blockdev_mirror_same_src_tgt: Mirror to the same node

### PR DESCRIPTION
**Pull request by zhencliu**
Signed-off-by: Zhenchao Liu <zhencliu@redhat.com>

ID: 1931309

### CODE REVIEW

**Comment by zhencliu** [comment]
local fs:
 (1/1) Host_RHEL.m8.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_mirror_same_src_tgt.q35: PASS (33.79 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2021-02-22T01.28-527238f/results.html
JOB TIME   : 35.53 s

iscsi direct + virtio-blk:
 (1/1) Host_RHEL.m8.u3.iscsi_direct.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_mirror_same_src_tgt.q35: PASS (33.93 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2021-02-22T01.39-8347586/results.html
JOB TIME   : 35.65 s

nbd:
 (1/1) Host_RHEL.m8.u3.nbd.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_mirror_same_src_tgt: PASS (61.71 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2021-02-22T01.44-149feeb/results.html
JOB TIME   : 63.45 s

ceph:
(1/1) Host_RHEL.m8.u3.ceph.raw.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.x86_64.io-github-autotest-qemu.blockdev_mirror_same_src_tgt.q35: PASS (62.35 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2021-02-22T01.53-e9064ba/results.html
JOB TIME   : 64.05 s

**Comment by zhencliu** [comment]
hi @ngu-niny , can you please help to review this patch, thanks.

**Comment by zhencliu** [comment]
hi @ngu-niny , can you please help to review this patch, thanks.

**Comment by ngu-niny** [comment]
LGTM and test PASS:

'3-Host_RHEL.m8.u4.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.4.0.ppc64le.io-github-autotest-qemu.blockdev_mirror_same_src_tgt' Finshed 2021-02-25 01:46:46 2021-02-25 01:49:31 PASS 165.395137

Acked-by: Nini Gu <ngu@redhat.com>

**Pull request merged**
