### PR TITLE
hotplug_mem: fix hugepage issue for migration case

### PR DESCRIPTION
**Pull request by huangyum**
ID: 1644496，1456123
Signed-off-by: Yumei Huang <yuhuang@redhat.com>
Depends on https://github.com/avocado-framework/avocado-vt/pull/1809

### CODE REVIEW

**Comment by huangyum** [comment]
Host_RHEL.m7.u6.qcow2.virtio_blk.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.hotplug_memory.after.guest_migration.hotplug.backend_file.policy_default.two: PASS (325.54 s)

**Comment by vivianQizhu** [comment]
@MiriamDeng Please help review, thanks.

**Comment by MiriamDeng** [comment]
Sure,I need to check it on ppc platform as soon as I got the log,thanks.

**Comment by huangyum** [comment]
@MiriamDeng The case failed due to some incorrect config in internal cfg, which I have sent an internal patch to fix it. Please patch them all and retest, thanks.

**Comment by MiriamDeng** [comment]
ACK. Thanks! @huangyum 
 (56/81) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.6.10.ppc64.io-github-autotest-qemu.hotplug_memory.after.guest_migration.hotplug.backend_file.policy_default.two: PASS (213.46 s)
 (57/81) Host_RHEL.m8.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.6.10.ppc64.io-github-autotest-qemu.hotplug_memory.after.guest_migration.hotplug.backend_file.policy_bind.two: PASS (217.71 s)

**Comment by vivianQizhu** [comment]
Thanks @huangyum @MiriamDeng

**Pull request merged**
