### PR TITLE
migration_with_dst_problem: fix the path of image2

### PR DESCRIPTION
**Pull request by dinghuiqing**
Change the path of image2 from tmp dir to "/usr/share/avocado/data/avocado-vt/".

ID: 1208357 
Signed-off-by: Huiqing Ding huding@redhat.com

### CODE REVIEW

**Comment by CongLi** [comment]
Hi @dinghuiqing 

Please fix the pep8 problem.

**Comment by dinghuiqing** [comment]
Thanks @CongLi 
Fixed the pep8 problem.

**Comment by PandaWei** [comment]
Good to me

**Comment by CongLi** [comment]
Ack-by: Cong Li <coli@redhat.om>

**Pull request merged**
