### PR TITLE
Netperf: update netperf client to fix an error

### PR DESCRIPTION
**Pull request by leidwang**
Currently, netperf can not start when vcpu>32, and our developer fix this bz in netperf, so we need to replace it.

ID:2218410

### CODE REVIEW

**Comment by leidwang** [comment]
(1/1) Host_RHEL.m9.u2.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.netperf_stress_test.TCP_STREAM.host2guest.q35: PASS (252.91 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2023-06-28T23.15-ba41283/results.html

**Comment by leidwang** [comment]
Hi @yanglei-rh  Could you please help to review this patch?
Please check the bz2218410 for details as I am not sure if it is suitable to add the details to github, thanks!

Hi @PaulYuuu Could you please help to review it from multi_arch side? Btw, this change will only affect windows test. Thanks!

**Comment by leidwang** [comment]
Hi @PaulYuuu Could you please help to review it from multi_arch side? Btw, this change will only affect windows test. Thanks!

**Review by PaulYuuu — APPROVED** [review]
It should only be for windows.

**Pull request merged**
