### PR TITLE
Removed python2 imports

### PR DESCRIPTION
**Pull request by bskjois**
Removed the python2 dependant modules as they are out of support now!

Signed-off-by: Kowshik Jois B S <kowsjois@linux.ibm.com>

### CODE REVIEW

**Comment by bskjois** [comment]
@YongxueHong @PaulYuuu @MiriamDeng @maxujun 
May I request to take a look and review this PR

Thanks in Advance!

**Comment by YongxueHong** [comment]
Hi CC @peixiu 
Could you help review this to see if it will affect your feature?
Thanks.

**Comment by PaulYuuu** [comment]
I am okay with this change. Just considering the `six` module is also for 2 and 3 compatibility, do you have plan to remove it as well?

**Comment by peixiu** [comment]
> Hi CC @peixiu Could you help review this to see if it will affect your feature? Thanks.

Hi @heywji , 

Could you help to check if these change will impact virtio-input case running? 

Thanks!

**Comment by bskjois** [comment]
> I am okay with this change. Just considering the `six` module is also for 2 and 3 compatibility, do you have plan to remove it as well?

@PaulYuuu I haven't thought anything with respect to `six` module. I am thinking to consider that and remove as part of a different PR.

**Comment by PaulYuuu** [comment]
> > I am okay with this change. Just considering the `six` module is also for 2 and 3 compatibility, do you have plan to remove it as well?
> 
> @PaulYuuu I haven't thought anything with respect to `six` module. I am thinking to consider that and remove as part of a different PR.

It's fine, thank you for the PR.

**Review by PaulYuuu — APPROVED** [review]

**Comment by bskjois** [comment]
@PaulYuuu Thank you for the review. 
Can we get this PR merged?

**Comment by maxujun** [comment]
LGTM.

**Review by peixiu — APPROVED** [review]
Thanks, LGTM~

**Comment by bskjois** [comment]
@YongxueHong @PaulYuuu @MiriamDeng @maxujun
Shall we please get this PR merged as there are 2 approvals and LGTMs have already been labelled.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by YongxueHong** [comment]
> @YongxueHong @PaulYuuu @MiriamDeng @maxujun Shall we please get this PR merged as there are 2 approvals and LGTMs have already been labelled.

Hi @bskjois 
Thanks for contributing. Just one reminder that we might sign the commits since there is a block for merging.
For further about commit signature verification, you can refer to https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification
Thanks.

**Comment by bskjois** [comment]
@YongxueHong I have rebased and pushed a new commit. There is no blockage now. Can this be merged now or signing is mandatory?
I was thinking to sign and raise all the PRs from next one.

**Comment by YongxueHong** [comment]
> @YongxueHong I have rebased and pushed a new commit. There is no blockage now. Can this be merged now or signing is mandatory? I was thinking to sign and raise all the PRs from next one.

Hi @bskjois 
Yeah, your idea makes sense. Although the signing is not mandatory, everyone is also trying to follow it since it is really meaningful in maintaining the project and bringing benefit to the reporter.
Anyway, let's merge it, as your sign-off is trusted. Looking forward to seeing this applied in your future PRs. Thanks!

**Comment by bskjois** [comment]
Thank you so much @YongxueHong 
I will make sure all my commits from now on will be verified. Thanks!

**Pull request merged**
