### PR TITLE
cgroup.cpu_share: increase the limits to fix limits broken issue

### PR DESCRIPTION
**Pull request by xiangchunfu**
Fix limits broken issue

id: 1872090

Signed-off-by: Xiangchun Fu <xfu@redhat.com>

### CODE REVIEW

**Comment by xiangchunfu** [comment]
＠yfu please help review it when you have time. If need, I can introduce this case to you first. Thanks.

**Comment by xiangchunfu** [comment]
All pass after repeated 50 times.

 (01/50) repeat1.Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.cgroup.cpu_share: PASS (169.02 s)
 ...........
 (50/50) repeat50.Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.cgroup.cpu_share: PASS (172.99 s)

**Comment by yanan-fu** [comment]
As we discussed offline, the issue is: some times the threshold is not large enough that cause case failed, however it is still acceptable, not a bug.   
So, increase the threshold is reasonable.

**Comment by yanan-fu** [comment]
How about: `cgroup.cpu_share: increase the limits`

**Comment by xiangchunfu** [comment]
All pass after repeated 50 times.

 (01/50) repeat1.Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.cgroup.cpu_share: PASS (172.65 s)
.......
 (50/50) repeat50.Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.cgroup.cpu_share: PASS (173.15 s)

**Comment by yanan-fu** [comment]
Acked-by: Yanan Fu <yfu@redhat.com>

**Pull request merged**
