### PR TITLE
Improve virtio_scsi_variants test cases efficiency

### PR DESCRIPTION
**Pull request by qingwangrh**
1.Increase vm monitor login timeout
2.Decrease disk number for virtio_scsi_variants
ID:1838891
Signed-off-by: qingwangrh <qinwang@redhat.com>

### CODE REVIEW

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=multi_disk  --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=RHEL.8.3.0 --driveformat=virtio_scsi --nicmodel=virtio_net --imageformat=luks --machines=q35 --customsparams="image_aio=threads" --clone=no

(1/9) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.multi_disk.one_disk_repeat.q35: PASS (133.60 s)
 (2/9) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.multi_disk.max_disk.q35: PASS (1811.39 s)
 (3/9) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.multi_disk.all_drive_format_types.q35: PASS (131.34 s)
 (4/9) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.block.q35: PASS (184.23 s)
 (5/9) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writethrough.q35: PASS (180.22 s)
 (6/9) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writeback.q35: PASS (179.47 s)
 (7/9) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_lun.q35: PASS (1075.25 s)
 (8/9) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_scsiid_lun.q35: PASS (486.24 s)
 (9/9) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun.q35: PASS (1090.97 s)

**Comment by qingwangrh** [comment]
@zhenyzha @YongxueHong @menli820 Please help to review.

**Comment by zhenyzha** [comment]
python3 ConfigTest.py --testcase=multi_disk --iothread_scheme=roundrobin --nr_iothreads=2 --platform=ppc64le --guestname=RHEL.8.3.0 --driveformat=virtio_scsi,virtio_blk --nicmodel=virtio_net --imageformat=qcow2 --customsparams="image_aio=threads" --clone=no

 (01/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.multi_disk.one_disk_repeat: PASS (162.63 s)
 (02/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.multi_disk.max_disk: PASS (1966.80 s)
 (03/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.multi_disk.with_virtio_scsi_TMF: PASS (1800.92 s)
 (04/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.multi_disk.all_drive_format_types: ERROR: Shell command failed: 'parted -s "/dev/sdb" mklabel gpt'    (status: 1,    output: 'Error: Input/output error during read on /dev/sdb\n') (183.83 s)
 (05/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.multi_disk.one_disk_repeat: PASS (186.46 s)
 (06/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.multi_disk.max_disk: PASS (3111.16 s)
 (07/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.multi_disk.all_drive_format_types: ERROR: Shell command failed: 'parted -s "/dev/sdc" mklabel gpt'    (status: 1,    output: 'Error: Input/output error during read on /dev/sdc\n') (156.11 s)
 (08/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.block: PASS (274.87 s)
 (09/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writethrough: PASS (267.83 s)
 (10/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writeback: PASS (278.32 s)
 (11/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_lun: PASS (732.80 s)
 (12/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_scsiid_lun: PASS (350.48 s)
 (13/13) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun: PASS (757.70 s)

The 7th error seems to be a script problem
log: http://10.0.136.47/zhenyzha/multi_disk-RHELAV8.3.0/results.html

**Comment by YongxueHong** [comment]
Hi, @zhenyzha 
This patch is a force on fixing` 'Could not connect to monitor 'qmpmonitor1''` issue with the image format luks.
I guess there is no such issue on qcow2 and raw format.
And the` ERROR: Shell command failed: 'parted -s "/dev/sdb"....` , maybe another issue, please new a bug to track.
So please re-test it with luks image format, thanks.

**Comment by zhenyzha** [comment]
> Hi, @zhenyzha
> This patch is a force on fixing` 'Could not connect to monitor 'qmpmonitor1''` issue with the image format luks.
> I guess there is no such issue on qcow2 and raw format.
> And the` ERROR: Shell command failed: 'parted -s "/dev/sdb"....` , maybe another issue, please new a bug to track.
> So please re-test it with luks image format, thanks.

Okay, testing, the results will be updated later.

**Comment by qingwangrh** [comment]
According to my test for zhenyzha mentioned issue
python ConfigTest.py --testcase=multi_disk.all_drive_format_types  --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=RHEL.8.3.0 --driveformat=virtio_scsi,virtio_blk --nicmodel=virtio_net --imageformat=qcow2 --machines=q35 --customsparams="image_aio=threads" --clone=no

(1/2) Host_RHEL.m8.u2.product_av.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.multi_disk.all_drive_format_types.q35: PASS (108.91 s)
 (2/2) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.multi_disk.all_drive_format_types.q35: PASS (103.89 s)

It looks like ppc only issue

**Comment by zhenyzha** [comment]
(01/11) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (1502.97 s)
 (02/11) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.rh_kernel_update: ERROR: 'list' object has no attribute 'splitlines' (252.66 s)
 (03/11) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.multi_disk.one_disk_repeat: PASS (170.41 s)
 (04/11) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.multi_disk.max_disk: PASS (4987.30 s)
 (05/11) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.multi_disk.all_drive_format_types: ERROR: Shell command failed: 'parted -s "/dev/sdc" mklabel gpt'    (status: 1,    output: 'Error: Input/output error during read on /dev/sdc\n') (208.34 s)
 (06/11) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.block: PASS (297.85 s)
 (07/11) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writethrough: PASS (279.61 s)
 (08/11) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writeback: PASS (297.44 s)
 (09/11) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_lun: PASS (1021.97 s)
 (10/11) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_scsiid_lun: PASS (493.19 s)
 (11/11) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun: PASS (1060.56 s)

Thanks for the comparison and verification of @qingwangrh , 
currently luks can be connected to the monitor. I will debug other errors by myself.
LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Comment by menli820** [comment]
Test on win2019 

 (01/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (1269.48 s)
 (02/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (2345.18 s)
 (03/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.one_disk_repeat: PASS (245.35 s)
 (04/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.one_disk_repeat.q35: PASS (192.20 s)
 (05/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.max_disk: PASS (1818.15 s)
 (06/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.max_disk.q35: PASS (1867.22 s)
 (07/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.all_drive_format_types: PASS (206.82 s)
 (08/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.all_drive_format_types.q35: PASS (170.71 s)
 (09/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.block: PASS (261.14 s)
 (10/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.block.q35: PASS (268.65 s)
 (11/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writethrough: PASS (223.45 s)
 (12/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writethrough.q35: PASS (228.54 s)
 (13/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writeback: PASS (230.36 s)
 (14/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writeback.q35: PASS (229.61 s)
 (15/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_lun: ERROR: Shell process terminated while waiting for command to complete: 'del c:\\cmd.exe; true'    (status: 1,    output: '') (1703.79 s)
 (16/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_lun.q35: ERROR: Shell process terminated while waiting for command to complete: 'del c:\\cmd.exe; true'    (status: 1,    output: '') (1589.59 s)
 (17/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_scsiid_lun: PASS (1056.71 s)
 (18/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_scsiid_lun.q35: PASS (1076.50 s)
 (19/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun: ERROR: Shell process terminated while waiting for command to complete: 'del c:\\cmd.exe; true'    (status: 1,    output: '') (1612.32 s)
 (20/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun.q35: ERROR: Shell process terminated while waiting for command to complete: 'del c:\\cmd.exe; true'    (status: 1,    output: '') (1643.14 s)
RESULTS    : PASS 16 | ERROR 4 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

The error log:
http://10.66.86.2/kvm_autotest_job_log/?jobid=4405129

**Comment by qingwangrh** [comment]
@menli820 patch updated

**Comment by qingwangrh** [comment]
python3 ConfigTest.py --testcase=multi_disk --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=Win2019 --driveformat=virtio_scsi --nicmodel=virtio_net --imageformat=luks --machines=q35 --customsparams="image_aio=native\ncd_format=ide" --clone=no

(1/9) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.one_disk_repeat.q35: PASS (349.38 s)
 (2/9) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.max_disk.q35: PASS (2990.66 s)
 (3/9) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.all_drive_format_types.q35: PASS (354.39 s)
 (4/9) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.block.q35: PASS (736.85 s)
 (5/9) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writethrough.q35: PASS (605.38 s)
 (6/9) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writeback.q35: PASS (620.33 s)
 (7/9) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_lun.q35: PASS (2639.80 s)
 (8/9) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_scsiid_lun.q35: PASS (2255.73 s)
 (9/9) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun.q35: PASS (2601.58 s)

python3 ConfigTest.py --testcase=multi_disk --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=Win2019 --driveformat=virtio_scsi --nicmodel=virtio_net --imageformat=luks --machines=i440fx --customsparams="image_aio=native\ncd_format=ide" --clone=no

(1/9) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.one_disk_repeat: PASS (331.72 s)
 (2/9) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.max_disk: PASS (2974.48 s)
 (3/9) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.all_drive_format_types: PASS (377.61 s)
 (4/9) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.block: PASS (718.55 s)
 (5/9) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writethrough: PASS (606.61 s)
 (6/9) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writeback: PASS (628.14 s)
 (7/9) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_lun: PASS (2598.39 s)
 (8/9) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_scsiid_lun: PASS (2253.75 s)
 (9/9) Host_RHEL.m8.u3.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun: PASS (2833.87 s)

**Comment by menli820** [comment]
Test on win2019
python3 ConfigTest.py --testcase=multi_disk --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=Win2019 --driveformat=virtio_scsi --nicmodel=virtio_net --imageformat=luks --machines=q35,i440fx --customsparams="image_aio=native\ncd_format=ide" --clone=yes

 (01/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads: PASS (1827.31 s)
 (02/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: PASS (1590.45 s)
 (03/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.one_disk_repeat: PASS (348.67 s)
 (04/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.one_disk_repeat.q35: PASS (271.16 s)
 (05/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.max_disk: PASS (2365.50 s)
 (06/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.max_disk.q35: PASS (2450.83 s)
 (07/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.all_drive_format_types: PASS (267.14 s)
 (08/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.all_drive_format_types.q35: PASS (244.67 s)
 (09/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.block: PASS (339.33 s)
 (10/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.block.q35: PASS (329.90 s)
 (11/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writethrough: PASS (280.74 s)
 (12/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writethrough.q35: PASS (293.54 s)
 (13/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writeback: PASS (310.23 s)
 (14/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.generic.with_cache_writeback.q35: PASS (311.18 s)
 (15/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_lun: /-PASS (1731.63 s)
 (16/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_lun.q35: PASS (1654.86 s)
 (17/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_scsiid_lun: PASS (1383.75 s)
 (18/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_scsiid_lun.q35: PASS (1426.89 s)
 (19/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun: ERROR: VM 'avocado-vt-vm1' failed to start: Error occurred while executing make_create_command(). Check the log for traceback. (40.74 s)
 (20/20) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun.q35: ERROR: VM 'avocado-vt-vm1' failed to start: Error occurred while executing make_create_command(). Check the log for traceback. (40.60 s)
RESULTS    : PASS 18 | ERROR 2 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

ignore the error above,its for my env issue as discussed with you.

python3 ConfigTest.py --testcase=multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun  --iothread_scheme=roundrobin --nr_iothreads=2 --platform=x86_64 --guestname=Win2019 --driveformat=virtio_scsi --nicmodel=virtio_net --imageformat=luks --machines=q35,i440fx --customsparams="image_aio=native\ncd_format=ide" --clone=no

 (1/1) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun.q35: PASS (1414.89 s)
 (1/2) Host_RHEL.m8.u2.product_av.luks.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.multi_disk.virtio_scsi_variants.multi_bus_scsiid_lun: PASS (1267.20 s)

Acked-by: Menghuan Li menli@redhat.com

**Pull request merged**
