### PR TITLE
hugepage_mem_stress: includes verify_guest_dmesg

### PR DESCRIPTION
**Pull request by mcasquer**
hugepage_mem_stress: includes verify_guest_dmesg

This commit includes verify_guest_dmesg
as cfg param to avoid any possible failure.

ID: 1760
Signed-off-by: mcasquer <mcasquer@redhat.com>

### CODE REVIEW

**Comment by mcasquer** [comment]
After applying the current patch:
```
# git am 3920.patch
Applying: hugepage_mem_stress: change to vm verify_dmesg
```
hugepage_mem_stress test cases passed successfully
```
 (1/2) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hugepage_mem_stress.q35: STARTED
 (1/2) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hugepage_mem_stress.q35: PASS (113.26 s)
 (2/2) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hugepage_mem_stress.non_existent_mem_path.q35: STARTED
 (2/2) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hugepage_mem_stress.non_existent_mem_path.q35: PASS (257.88 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```

**Comment by mcasquer** [comment]
@yanan-fu @PaulYuuu could you review this Pull Request? Thanks!

**Comment by mcasquer** [comment]
As we discussed internally this is a minor and quick fix for these two cases

**Comment by PaulYuuu** [comment]
For the commit message, we can focus on why to change it, excluding any internal discussion.

**Comment by mcasquer** [comment]
> For the commit message, we can focus on why to change it, excluding any internal discussion.

@PaulYuuu explained now in the commit message

**Comment by yanan-fu** [comment]
For this case, it is the last step to verify guest dmesg,  For this situation, i prefer to use `verify_guest_dmesg = yes`  to let the framework to check the guest dmesg in post step.

**Comment by mcasquer** [comment]
> verify_guest_dmesg

@PaulYuuu what do you think about Yanan's idea?

**Comment by PaulYuuu** [comment]
@mcasquer, yes I agree. But this only works on Linux guests, so please check it will not cause window to fail, or set:
```
Linux:
	verify_guest_dmesg = yes
```

**Comment by mcasquer** [comment]
Test cases pass successfully 
```
 (1/2) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hugepage_mem_stress.q35: STARTED
 (1/2) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hugepage_mem_stress.q35: PASS (136.58 s)
 (2/2) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hugepage_mem_stress.non_existent_mem_path.q35: STARTED
 (2/2) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.hugepage_mem_stress.non_existent_mem_path.q35: PASS (333.66 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```

**Comment by mcasquer** [comment]
@PaulYuuu @yanan-fu could you review again this PR? Thanks!

**Review by yanan-fu — APPROVED** [review]
Ack

**Comment by yanan-fu** [comment]
> @mcasquer, yes I agree. But this only works on Linux guests, so please check it will not cause window to fail, or set:
> 
> ```
> Linux:
> 	verify_guest_dmesg = yes
> ```

FYI 
For windows guest,  no much side effect to use `verify_guest_dmesg = yes`, it will be true as failed to get kernel message all the time:
https://github.com/avocado-framework/avocado-vt/blob/fca87a6504ea23cbc6fd9451dea80756c09736a1/virttest/utils_misc.py#L3183C5-L3183C5

And, limit it to linux guest only can save some time, more better  ^^

@PaulYuuu Could you review the latest version ? Thanks!

**Comment by PaulYuuu** [comment]
> > @mcasquer, yes I agree. But this only works on Linux guests, so please check it will not cause window to fail, or set:
> > ```
> > Linux:
> > 	verify_guest_dmesg = yes
> > ```
> 
> FYI For windows guest, no much side effect to use `verify_guest_dmesg = yes`, it will be true as failed to get kernel message all the time: [avocado-framework/avocado-vt@`fca87a6`/virttest/utils_misc.py#L3183C5-L3183C5](https://github.com/avocado-framework/avocado-vt/blob/fca87a6504ea23cbc6fd9451dea80756c09736a1/virttest/utils_misc.py#L3183C5-L3183C5)
> 
> And, limit it to linux guest only can save some time, more better ^^
> 
> @PaulYuuu Could you review the latest version ? Thanks!

Yes, and it's strange that verify dmesg in windows guest.

**Review by PaulYuuu — APPROVED** [review]

**Comment by yanan-fu** [comment]
Thanks all!

**Pull request merged**
