### PR TITLE
Add throttle mix parameter case

### PR DESCRIPTION
**Pull request by qingwangrh**
Improve sampling accuracy
ID:1895818,1895822,1895821,1895823,1895824,1895826
Signed-off-by: qingwangrh <qinwang@redhat.com>

### CODE REVIEW

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=throttle_parameter_test --guestname=Win2019 --clone=no

(01/22) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.throttle_parameter_test.normal_read.with_iops: PASS (208.87 s)
 (02/22) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.throttle_parameter_test.normal_read.with_bps: PASS (198.79 s)
 (03/22) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.throttle_parameter_test.normal_read.with_iops_bps: PASS (198.59 s)
 (04/22) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.throttle_parameter_test.normal_write.with_iops: PASS (198.60 s)
 (05/22) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.throttle_parameter_test.normal_write.with_bps: PASS (198.68 s)
 (06/22) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.throttle_parameter_test.normal_write.with_iops_bps: PASS (198.62 s)
 (07/22) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.throttle_parameter_test.normal_rw.with_iops: PASS (198.55 s)
 (08/22) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.throttle_parameter_test.normal_rw.with_bps: PASS (198.69 s)
 (09/22) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.throttle_parameter_test.normal_rw.with_iops_bps: PASS (198.62 s)
 (10/22) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.throttle_parameter_test.normal_rw.with_iops_bps_rw: PASS (198.83 s)
 (11/22) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.throttle_parameter_test.burst_read.with_iops: PASS (332.77 s)
 (12/22) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.throttle_parameter_test.burst_read.with_bps: PASS (332.86 s)
 (13/22) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.throttle_parameter_test.burst_read.with_iops_bps: PASS (332.85 s)
 (14/22) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.throttle_parameter_test.burst_write.with_iops: PASS (332.95 s)
 (15/22) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.throttle_parameter_test.burst_write.with_bps: PASS (332.35 s)
 (16/22) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.throttle_parameter_test.burst_write.with_iops_bps: PASS (332.94 s)
 (17/22) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.throttle_parameter_test.burst_rw.with_iops: PASS (332.95 s)
 (18/22) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.throttle_parameter_test.burst_rw.with_bps: PASS (332.74 s)
 (19/22) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.throttle_parameter_test.burst_rw.with_iops_bps: PASS (332.19 s)
 (20/22) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.throttle_parameter_test.mix.with_iops_size: PASS (195.92 s)
 (21/22) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.throttle_parameter_test.mix.with_iops_size_burst: PASS (291.81 s)
 (22/22) Host_RHEL.m8.u2.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.throttle_parameter_test.mix.with_iops_bps_all: PASS (349.21 s)

**Comment by qingwangrh** [comment]
python ConfigTest.py --testcase=throttle_parameter_test --guestname=RHEL.8.3.0 --clone=no

(01/22) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.throttle_parameter_test.normal_read.with_iops: PASS (190.87 s)
 (02/22) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.throttle_parameter_test.normal_read.with_bps: PASS (223.03 s)
 (03/22) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.throttle_parameter_test.normal_read.with_iops_bps: PASS (232.82 s)
 (04/22) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.throttle_parameter_test.normal_write.with_iops: PASS (187.50 s)
 (05/22) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.throttle_parameter_test.normal_write.with_bps: PASS (185.03 s)
 (06/22) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.throttle_parameter_test.normal_write.with_iops_bps: PASS (186.10 s)
 (07/22) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.throttle_parameter_test.normal_rw.with_iops: PASS (193.65 s)
 (08/22) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.throttle_parameter_test.normal_rw.with_bps: PASS (238.96 s)
 (09/22) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.throttle_parameter_test.normal_rw.with_iops_bps: PASS (244.15 s)
 (10/22) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.throttle_parameter_test.normal_rw.with_iops_bps_rw: PASS (241.87 s)
 (11/22) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.throttle_parameter_test.burst_read.with_iops: PASS (323.12 s)
 (12/22) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.throttle_parameter_test.burst_read.with_bps: PASS (349.73 s)
 (13/22) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.throttle_parameter_test.burst_read.with_iops_bps: PASS (353.66 s)
 (14/22) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.throttle_parameter_test.burst_write.with_iops: PASS (320.57 s)
 (15/22) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.throttle_parameter_test.burst_write.with_bps: PASS (320.40 s)
 (16/22) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.throttle_parameter_test.burst_write.with_iops_bps: PASS (319.60 s)
 (17/22) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.throttle_parameter_test.burst_rw.with_iops: PASS (322.11 s)
 (18/22) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.throttle_parameter_test.burst_rw.with_bps: PASS (355.92 s)
 (19/22) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.throttle_parameter_test.burst_rw.with_iops_bps: PASS (361.30 s)
 (20/22) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.throttle_parameter_test.mix.with_iops_size: PASS (202.29 s)
 (21/22) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.throttle_parameter_test.mix.with_iops_size_burst: PASS (301.90 s)
 (22/22) Host_RHEL.m8.u3.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.x86_64.io-github-autotest-qemu.throttle_parameter_test.mix.with_iops_bps_all: PASS (380.56 s)

**Comment by qingwangrh** [comment]
@YongxueHong @zhencliu Please help to review ,thanks.

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by zhencliu** [comment]
LGTM

**Pull request merged**
