### PR TITLE
storage_benchmark: support context manager protocol

### PR DESCRIPTION
**Pull request by lolyu**
add support for with statement.

Signed-off-by: lolyu <lolyu@redhat.com>

### CODE REVIEW

**Comment by lolyu** [comment]
Modify `fio_linux`:
```
diff --git a/qemu/tests/fio_linux.py b/qemu/tests/fio_linux.py
index efde2a4..015052a 100644
--- a/qemu/tests/fio_linux.py
+++ b/qemu/tests/fio_linux.py
@@ -51,11 +51,8 @@ def run(test, params, env):
     vm = env.get_vm(params["main_vm"])
     vm.verify_alive()
     session = vm.wait_for_login(timeout=float(params.get("login_timeout", 240)))
-    try:
-        fio = generate_instance(params, session, 'fio')
+    
+    with generate_instance(params, session, 'fio') as fio:
         for did in _get_data_disks():
             for option in params['fio_options'].split(';'):
                 fio.run('--filename=%s %s' % (did, option))
-    finally:
-        fio.clean()
-        session.close()
```

test result:
```
03:03:48 INFO | PASS 1-Host_RHEL.m7.u7.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.io-github-autotest-qemu.fio_linux.aio_native
```

**Comment by lolyu** [comment]
(1/2) Host_RHEL.m7.u7.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.io-github-autotest-qemu.fio_linux.aio_native: PASS (388.81 s)
 (2/2) Host_RHEL.m7.u7.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.io-github-autotest-qemu.fio_linux.aio_threads: PASS (379.73 s)

**Comment by lolyu** [comment]
Please take a review @hereischen @YongxueHong @XueqiangWei

**Comment by luckyh** [comment]
There are some restrictions of the use cases, for example, the context would be broken by a reboot (that because the session held by the benchmark obj has been shut down.)

**Comment by lolyu** [comment]
I restrict the usage scenario to only replace `try finally` block. I think this is sufficient for this.

**Comment by YongxueHong** [comment]
> sufficient

I will update this code to support reboot or shutdown then the session will be re-created.

**Pull request closed without merging**
