### PR TITLE
virtio_aer_opt: new case to check aer and ats capabilties in guest os

### PR DESCRIPTION
**Pull request by yanan-fu**
id: 1984298

Signed-off-by: Yanan Fu <yfu@redhat.com>

### CODE REVIEW

**Comment by yanan-fu** [comment]
@jingzhao84  @yiqianwei Could you help review ? Thanks!

Test result and key test log:
```
05:14:05 DEBUG| Sending command: lspci -vvv -s 05:00.0 | grep 'Advanced Error Reporting'
05:14:05 DEBUG| Sending command: echo $?
05:14:05 DEBUG| Sending command: lspci -vvv -s 05:00.0 | grep 'Address Translation Service'
05:14:05 DEBUG| Sending command: echo $?
05:14:05 DEBUG| Sending command: lspci -vvv -s 04:00.0 | grep 'Advanced Error Reporting'
05:14:06 DEBUG| Sending command: echo $?
05:14:06 DEBUG| Sending command: lspci -vvv -s 04:00.0 | grep 'Address Translation Service'
05:14:06 DEBUG| Sending command: echo $?
05:14:06 DEBUG| Sending command: lspci -vvv -s 06:00.0 | grep 'Advanced Error Reporting'
05:14:06 DEBUG| Sending command: echo $?
05:14:06 DEBUG| Sending command: lspci -vvv -s 06:00.0 | grep 'Address Translation Service'
05:14:06 DEBUG| Sending command: echo $?
...
05:14:15 INFO | PASS 1-Host_RHEL.m9.u0.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.virtio_aer_opt.q35
```

**Comment by yanan-fu** [comment]
@yiqianwei Any more comments for this patch ?

**Comment by yiqianwei** [comment]
> @yiqianwei Any more comments for this patch ?

@yanan-fu, LGTM and test result on x86_64:

 (1/1) Host_RHEL.m8.u5.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.x86_64.io-github-autotest-qemu.virtio_aer_opt.q35: PASS (36.98 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2021-09-01T02.25-888a244/results.html

**Comment by yanan-fu** [comment]
Thanks all!

**Pull request merged**
