### PR TITLE
tp-qemu.multi_host migration: Add a separate directory for multi_host migration

### PR DESCRIPTION
**Pull request by XueqiangWei**
Signed-off-by: Xueqiang Wei <xuwei@redhat.com>

### CODE REVIEW

**Comment by XueqiangWei** [comment]
ID 1394608

**Comment by XueqiangWei** [comment]
depends on avocado-framework/avocado-vt#782 autotest/autotest-server-tests#18

**Comment by XueqiangWei** [comment]
10:04:59 INFO | GOOD	virt.case3.remote_nfs.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.multi_host.migrate_multi_host.after_login_vm.vhost_src_yes_dst_yes.mig_online.tcp	virt.case3.remote_nfs.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.multi_host.migrate_multi_host.after_login_vm.vhost_src_yes_dst_yes.mig_online.tcp	timestamp=1479895501	localtime=Nov 23 10:05:01	completed successfully
10:04:59 INFO | END GOOD	virt.case3.remote_nfs.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.multi_host.migrate_multi_host.after_login_vm.vhost_src_yes_dst_yes.mig_online.tcp	virt.case3.remote_nfs.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.multi_host.migrate_multi_host.after_login_vm.vhost_src_yes_dst_yes.mig_online.tcp	timestamp=1479895501	localtime=Nov 23 10:05:01	
10:05:00 INFO | END GOOD	----	----	timestamp=1479895501	localtime=Nov 23 10:05:01	
10:05:02 INFO | Client complete
10:05:57 INFO | GOOD	virt.case3.remote_nfs.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.multi_host.migrate_multi_host.after_login_vm.vhost_src_yes_dst_yes.mig_online.tcp	virt.case3.remote_nfs.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.multi_host.migrate_multi_host.after_login_vm.vhost_src_yes_dst_yes.mig_online.tcp	timestamp=1479895559	localtime=Nov 23 10:05:59	completed successfully
10:05:57 INFO | END GOOD	virt.case3.remote_nfs.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.multi_host.migrate_multi_host.after_login_vm.vhost_src_yes_dst_yes.mig_online.tcp	virt.case3.remote_nfs.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.x86_64.io-github-autotest-qemu.multi_host.migrate_multi_host.after_login_vm.vhost_src_yes_dst_yes.mig_online.tcp	timestamp=1479895559	localtime=Nov 23 10:05:59	
10:05:58 INFO | END GOOD	----	----	timestamp=1479895559	localtime=Nov 23 10:05:59

**Comment by CongLi** [comment]
LGTM,
acked-by: Cong Li coli@redhat.com

**Comment by aliang123** [comment]
Acked-by: Aihua Liang <aliang@redhat.com>

**Comment by XueqiangWei** [comment]
@xutian please help double check this pullreq, thank you

**Comment by xutian** [comment]
fine,  merged, thanks @XueqiangWei

**Pull request merged**
