### PR TITLE
fix parameters which have been changed

### PR DESCRIPTION
**Pull request by nanliu-r**
fix cfg file parameters which have been changed.

id:1728934

Signed-off-by: Nana Liu nanliu@redhat.com

### CODE REVIEW

**Comment by nanliu-r** [comment]
fix port parameters in file virtio_serial_empty_line.cfg.

Signed-off-by: Nana Liu nanliu@redhat.com

id:1728934

**Comment by nanliu-r** [comment]
Test results: 

(19/40) repeat10.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.guest_to_host: PASS (62.89 s)
 (20/40) repeat10.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.host_to_guest: PASS (59.60 s)
 (21/40) repeat11.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.guest_to_host: PASS (75.57 s)
 (22/40) repeat11.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.host_to_guest: PASS (56.25 s)
 (23/40) repeat12.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.guest_to_host: PASS (65.63 s)
 (24/40) repeat12.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.host_to_guest: PASS (59.17 s)
 (25/40) repeat13.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.guest_to_host: PASS (60.35 s)
 (26/40) repeat13.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.host_to_guest: PASS (60.35 s)
 (27/40) repeat14.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.guest_to_host: PASS (55.00 s)
 (28/40) repeat14.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.host_to_guest: PASS (65.36 s)
 (29/40) repeat15.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.guest_to_host: PASS (58.46 s)
 (30/40) repeat15.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.host_to_guest: PASS (60.83 s)
 (31/40) repeat16.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.guest_to_host: PASS (67.49 s)
 (32/40) repeat16.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.host_to_guest: PASS (54.86 s)
 (33/40) repeat17.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.guest_to_host: PASS (59.29 s)
 (34/40) repeat17.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.host_to_guest: PASS (60.54 s)
 (35/40) repeat18.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.guest_to_host: PASS (66.51 s)
 (36/40) repeat18.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.host_to_guest: PASS (61.05 s)
 (37/40) repeat19.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.guest_to_host: PASS (60.90 s)
 (38/40) repeat19.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.host_to_guest: PASS (64.28 s)
 (39/40) repeat20.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.guest_to_host: PASS (62.54 s)
 (40/40) repeat20.Host_RHEL.m8.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.7.x86_64.io-github-autotest-qemu.virtio_serial_empty_line.host_to_guest: PASS (65.38 s)
RESULTS    : PASS 40 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by yanan-fu** [comment]
@nanliu-r  Please add id,   others LGTM

**Comment by nanliu-r** [comment]
> @nanliu-r Please add id, others LGTM

I have added the id In previous comments. :)


Signed-off-by: Nana Liu nanliu@redhat.com

id:1728934

**Comment by yanan-fu** [comment]
Acked-by: Yanan Fu <yfu@redhat.com>

**Pull request merged**
