### PR TITLE
qmp_command: fix issue of query block status while using q35 machine type 

### PR DESCRIPTION
**Pull request by jingzhao84**
ID: 1592680

Signed-off-by: jinzhao <jinzhao@redhat.com>

### CODE REVIEW

**Comment by jingzhao84** [comment]
@yanan-fu @huangyum  could you help to review this pr? thanks

**Comment by huangyum** [comment]
Please edit your commit title and/or commit msg by following rules in the link below:
http://avocado-framework.readthedocs.io/en/61.0/ContributionGuide.html#git-workflow

**Comment by jingzhao84** [comment]
@huangyum updated thanks

**Comment by jingzhao84** [comment]
Host_RHEL.m7.u6.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.qmp_command.qmp_query-blockstats.q35: PASS (47.17 s)

Host_RHEL.m7.u6.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.qmp_command.qmp_query-blockstats: PASS (46.21 s)

**Comment by yanan-fu** [comment]
Better add "qmp_command:"  in commit tile.

And, are you sure this is the expect result of q35 ?

**Comment by jingzhao84** [comment]
@yanan-fu  yes, q35 machine type does not support floppy block in the default, only pc machine support it in the default. detailed please check the bz comments

**Comment by yanan-fu** [comment]
@jingzhao84 thanks for your explanation.  I checked the bz before, as it only show the output, and i think we can not get a conclusion for a given output,  so i double confirm with you if it is the expect result, just puzzled if it is a product bz. 

With this change , it will only support  i440fx and q35,  please consider other platform,  or you can leave `cmd_return_value `for i440fx  as default.

**Comment by huangyum** [comment]
I agree with @yanan-fu , just adding two new lines should be OK.

> q35:
>                cmd_return_value = "device;wr_highest_offset;rd_bytes;wr_operations;rd_operations;wr_bytes;parent;sd0"

**Comment by jingzhao84** [comment]
@huangyum @yanan-fu thanks your comments, and had updated

Host_RHEL.m7.u6.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.qmp_command.qmp_query-blockstats.q35: PASS (47.74 s)

Host_RHEL.m7.u6.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.5.x86_64.io-github-autotest-qemu.qmp_command.qmp_query-blockstats: PASS (45.04 s)

**Comment by huangyum** [comment]
Acked-by: Yumei Huang <yuhuang@redhat.com>

Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.io-github-autotest-qemu.qmp_command.qmp_query-blockstats: PASS (71.46 s)

Host_RHEL.m7.u5.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.6.x86_64.io-github-autotest-qemu.qmp_command.qmp_query-blockstats.q35: PASS (71.38 s)

**Comment by yanan-fu** [comment]
Acked-by: Yanan Fu <yfu@redhat.com>

**Comment by jingzhao84** [comment]
@luckyh  could you help to review this pr, thanks

**Pull request merged**
