### PR TITLE
power_hpt_mmu_test: add new case for hpt guest with huge page backend

### PR DESCRIPTION
**Pull request by MiriamDeng**
Add new case for hpt guest with huge page backend

ID: 1839601,1839603

Signed-off-by: mdeng <mdeng@redhat.com>

### CODE REVIEW

**Comment by MiriamDeng** [comment]
Test results,
 (14/15) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.power_hpt_mmu_test.with_huge_page.increase: PASS (133.06 s)
 (15/15) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.power_hpt_mmu_test.with_huge_page.reduce: PASS (114.22 s)

**Comment by MiriamDeng** [comment]
@PaulYuuu Could you help to review ,thanks a lot.

**Comment by PaulYuuu** [comment]
LGTM

**Comment by MiriamDeng** [comment]
Hi @zhenyzha 
Could you please also help to review this patch, thanks in advance.
Min

**Comment by zhenyzha** [comment]
Applying: Add new case for hpt guest with huge page backend
.git/rebase-apply/patch:15: trailing whitespace.
            extra_params += " -mem-path /mnt/kvm_hugepage" 
warning: 1 line adds whitespace errors.

**Comment by MiriamDeng** [comment]
(1/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.8.ppc64le.io-github-autotest-qemu.power_hpt_mmu_test.with_huge_page.increase: PASS (101.29 s)
 (2/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.8.ppc64le.io-github-autotest-qemu.power_hpt_mmu_test.with_huge_page.reduce: PASS (87.94 s)
 (3/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.power_hpt_mmu_test.with_huge_page.increase: PASS (119.79 s)
 (4/4) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.power_hpt_mmu_test.with_huge_page.reduce: PASS (104.95

**Comment by zhenyzha** [comment]
(1/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.ppc64le.io-github-autotest-qemu.power_hpt_mmu_test.with_huge_page.increase: PASS (109.16 s)
 (2/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.7.9.ppc64le.io-github-autotest-qemu.power_hpt_mmu_test.with_huge_page.reduce: PASS (120.98 s)
 (1/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.power_hpt_mmu_test.with_huge_page.increase: PASS (120.15 s)
 (2/2) Host_RHEL.m8.u3.product_av.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.3.0.ppc64le.io-github-autotest-qemu.power_hpt_mmu_test.with_huge_page.reduce: PASS (131.57 s)

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Comment by PaulYuuu** [comment]
Thanks all.

**Pull request merged**
