### PR TITLE
virtio_fs: add iozone test on shared directory

### PR DESCRIPTION
**Pull request by xiagao**
ID: 2040572
Signed-off-by: Xiaoling Gao <xiagao@redhat.com>

### CODE REVIEW

**Comment by xiagao** [comment]
(01/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.auto.q35: STARTED
| (01/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.auto.q35: PASS (203.06 s)
 (02/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.auto.with_writeback.q35: STARTED
\ (02/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.auto.with_writeback.q35: PASS (190.67 s)
 (03/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.always.q35: STARTED
| (03/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.always.q35: PASS (196.50 s)
 (04/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.always.with_writeback.q35: STARTED
\ (04/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.always.with_writeback.q35: PASS (191.07 s)
 (05/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.none.q35: STARTED
/ (05/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.none.q35: PASS (177.93 s)
 (06/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.none.with_writeback.q35: STARTED
\ (06/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.0.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.none.with_writeback.q35: PASS (230.67 s)
 (07/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.auto.q35: STARTED
| (07/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.auto.q35: PASS (342.80 s)
 (08/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.auto.with_writeback.q35: STARTED
/ (08/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.auto.with_writeback.q35: PASS (333.93 s)
 (09/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.always.q35: STARTED
| (09/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.always.q35: PASS (324.43 s)
 (10/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.always.with_writeback.q35: STARTED
/ (10/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.always.with_writeback.q35: PASS (329.71 s)
 (11/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.none.q35: STARTED
\ (11/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.none.q35: PASS (368.25 s)
 (12/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.none.with_writeback.q35: STARTED
/ (12/12) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.none.with_writeback.q35: PASS (330.91 s)

**Comment by xiagao** [comment]
@zhenyzha @YongxueHong  Could you have a look?

**Review by YongxueHong — APPROVED** [review]
LGTM.

**Comment by zhenyzha** [comment]
```
 (1/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.auto.arm64-pci: STARTED
| (1/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.auto.arm64-pci: PASS (283.28 s)
 (2/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.auto.with_writeback.arm64-pci: STARTED
\ (2/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.auto.with_writeback.arm64-pci: PASS (274.99 s)
 (3/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.always.arm64-pci: STARTED
/ (3/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.always.arm64-pci: PASS (254.31 s)
 (4/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.always.with_writeback.arm64-pci: STARTED
| (4/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.always.with_writeback.arm64-pci: PASS (275.12 s)
 (5/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.none.arm64-pci: STARTED
/ (5/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.none.arm64-pci: PASS (253.14 s)
 (6/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.none.with_writeback.arm64-pci: STARTED
/ (6/6) Host_RHEL.m9.u1.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.1.0.aarch64.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.none.with_writeback.arm64-pci: PASS (255.53 s)
```

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

**Review by zhenyzha — APPROVED** [review]

**Pull request merged**
